### ISSUE TITLE
[FR] weak symbols for API additions

### ISSUE THREAD

**Issue by enh** [android/ndk#1003]
the roadmap used to say:

```
iOS developers are used to using weak symbols to refer to function that
may be present in their equivalent of `targetSdkVersion` but not in their
`minSdkVersion`. They use a run-time null check to decide whether the
new function is available or not. Apparently clang also has some support
for emitting a warning if you dereference one of these symbols without
a corresponding null check.

This seems like a more convenient option than is currently available
on Android, especially since no currently shipping version of Android
includes a function to check which version of Android you're running on.

We might not want to make this the default (because it's such a break
with historical practice, and might be surprising), but we should offer
this as an option.

An interesting technical problem here will be dealing with the `DT_NEEDED`
situation for "I need this library (but it might not exist yet)".
```

the `__FILE_OFFSET_BITS` experience has made us question whether this would
actually cause more harm than good, but danalbert at least still thinks this is something we should do, just that it _shouldn't_ be the default behavior, and we might want to choose a scary name for the flag to enable it.

danalbert points out that we can solve the `DT_NEEDED` problems by removing symbol versioning from NDK libraries and ensuring that the zygote preloads all NDK libraries.

see also https://github.com/android-ndk/ndk/issues/479 which is somewhat related, but something we should do anyway.

**Comment by DanAlbert** [comment]
Dup of https://github.com/android/ndk/issues/837

**Comment by DanAlbert** [comment]
> danalbert points out that we can solve the DT_NEEDED problems by removing symbol versioning from NDK libraries and ensuring that the zygote preloads all NDK libraries.

That's pretty useless for old devices though, and we can fix new devices by just only putting things in libandroid :(
