### ISSUE TITLE
[Bug] Split DWO and merge into DWP (r20)

### ISSUE THREAD

**Issue by metora** [android/ndk#1005]
I use some cc1 option to make single dwp file.
1.-Xclang -split-dwarf-file -Xclang MyLib.dwp -Xclang -enable-split-dwarf
2.objcopy A.o A.dwo
3.dwp MyLib.dwp A.dwo B.dwo ... Z.dwo

It was run normally below r20.
And now it will make MyLib.dwp directly, not just named it in object.

How to run it like before?

**Comment by DanAlbert** [comment]
Could you elaborate? I don't understand what is meant by "And now I will make MyLib.dwp directly, not just named it in object." I don't know much about split dwarf, so I don't know what the expected behavior is.

@stephenhines might know more

**Comment by DanAlbert** [comment]
Closing for lack of info.
