### ISSUE TITLE
Android Studio C/C++ RFC: CMake Build Cohabitation

### ISSUE THREAD

**Issue by jomof** [android/ndk#1011]
This is a request for comments (RFC) for a proposed improvement to Android Studio's CMake integrations. 
Please see the tracking issue in Android Studio's tracker: https://issuetracker.google.com/134757616

**Comment by DanAlbert** [comment]
To clarify Jomo's original post: this is a planned Android Studio feature that we want external feedback on. It's being posted here for improved visibility. Probably best to use the issuetracker bug (or the google doc) for discussion to keep things all in one place :)

**Comment by Zingam** [comment]
You could check what I had to do to "seperate" my Windows CMake based source code from the Android specific project:
https://github.com/Zingam/GunBox-Android
I either drop the C++ in specific folders or I create a symbolic link to the Windows CMake project sources.

A list of other CMake integration issues:
  - CMake messages are not displayed by Android Studio.

**Comment by jomof** [comment]
Thank you Zingam, I think we've finally sorted the CMake messages not display issue in 3.6 recent canaries.
I'm taking a look at your project now

**Comment by DanAlbert** [comment]
(closing as this is just an announcement)
