### ISSUE TITLE
[DOC] Incorrect paths and arguments

### ISSUE THREAD

**Issue by thomasuster** [android/ndk#1030]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
https://developer.android.com/ndk/guides/other_build_systems

**Problem**
```
$ $NDK/toolchains/llvm/prebuilt/$HOST_TAG/clang++ \
    -target aarch64-linux-android21 foo.cpp
```
should be
```
$ $NDK/toolchains/llvm/prebuilt/$HOST_TAG/bin/clang++ \
    -target=aarch64-linux-android21 foo.cpp
```
(bin folder missing, target argument syntax incorrect.)

**Comment by DanAlbert** [comment]
The missing `bin/` was fixed some time ago, but I forgot to fix the `--target` part. `--target` is actually also okay, `--target` just requires `--target=...` instead of `--target ...`, and one of the examples in that doc was wrong. I've sent a CL to fix that now.
