### ISSUE TITLE
[BUG] asan-smoke fails when linked with lld after clang update

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1034]
When updating to Clang r353983e, we see the following failure:

```
FAIL asan-smoke.asan_smoke [arm64-v8a-21-lld]: android-29 marlin HT67L0200247 QPP4.190502.014.A3
CANNOT LINK EXECUTABLE "./asan_smoke": cannot locate symbol "_Unwind_GetIP" referenced by "/data/local/tmp/tests/arm64-v8a-21-lld/ndk-build/asan-smoke/arm64-v8a/libclang_rt.asan-aarch64-android.so"...
```

This is a regression from r353983c:

```bash
$ readelf -sW prebuilts/clang/host/linux-x86/clang-r353983c/runtimes_ndk_cxx/libclang_rt.asan-aarch64-android.so | grep _Unwind_Ge
tIP
  5238: 00000000000d5448     8 FUNC    LOCAL  DEFAULT   14 _Unwind_GetIP
  5242: 00000000000d5450    20 FUNC    LOCAL  DEFAULT   14 _Unwind_GetIPInfo
$ readelf -sW prebuilts/clang/host/linux-x86/clang-r353983e/runtimes_ndk_cxx/libclang_rt.asan-aarch64-android.so | grep _Unwind_GetIP
    34: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _Unwind_GetIP
  5288: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _Unwind_GetIP
```

`_Unwind_GetIP` comes from libgcc and so should be statically linked into the library. This indicates that either the dynamic libgcc was used (which Android doesn't support or include, so that seems unlikely), or the symbol was being incorrectly resolved from another shared library that mistakenly re-exported libgcc.

What's particularly interesting is that this does work with bfd. That deserves further analysis, but the undefined symbol in the asan library is a bug in the toolchain regardless of what happened there.

**Comment by DanAlbert** [comment]
> What's particularly interesting is that this does work with bfd. That deserves further analysis

The answer appears to be that lld is hiding libgcc by default. We do this for arm32 in the build system to avoid conflicts between libgcc and libunwind, but don't for the other architectures since they don't use libunwind.

IMO that's a feature. lld is doing the right thing by hiding libgcc, so at least there's only one bug.

**Comment by stephenhines** [comment]
https://android-review.googlesource.com/c/toolchain/llvm_android/+/986963 is almost certainly the root cause of the new issue. @kongy, can you take a look at getting the build working again when you are back?
