### ISSUE TITLE
[BUG] set `CMAKE_CXX_COMPILER_FRONTEND_VARIANT` to support CMake 3.15

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1049]
https://gitlab.kitware.com/cmake/cmake/issues/19515

**Comment by rcdailey** [comment]
@DanAlbert Can this be hotfixed to r19 and r20 please? It's a huge blocker for my team. I hope doing so is a relatively easy and reasonable task.

**Comment by DanAlbert** [comment]
We don't hotfix non-regressions, and we don't hotfix more than one release back. We're looking in to shifting resources around so we have the time for things like that, but we're not there yet.

**Comment by azymohliad** [comment]
As a workaround I set `-std=c++17` to my target explicitly for now, @rcdailey:
```target_compile_options(MyTarget PRIVATE -std=c++17)```

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/1121705
