### ISSUE TITLE
[BUG] clang crashs when building renderdoc for android

### ISSUE THREAD

**Issue by cenomla** [android/ndk#1053]
### Description
Clang segfaults when trying to compile a specific file from renderdoc

Stack Trace: https://pastebin.com/bVuMychS 
Relevant files (cpp and sh cmd): [rep.tar.gz](https://github.com/android-ndk/ndk/files/3462358/rep.tar.gz)

#### Environment Details
Version: r20
Build System: CMake
OS: Arch Linux
Target NDK API level: 21

**Comment by pirama-arumuga-nainar** [comment]
The crash in llvm::LiveRange::join makes me think it might be the same as #1000 which should be fixed when we get a new compiler (in r21).

**Comment by cenomla** [comment]
Good to know, apparently this code compiles in earlier versions (r13a, r18)

**Comment by Zingam** [comment]
> The crash in llvm::LiveRange::join makes me think it might be the same as #1000 which should be fixed when we get a new compiler (in r21).

Will this new compiler bring enable C++20 features? I was hoping for Concepts but it looks they won't appear before 2020 in clang.

**Comment by pirama-arumuga-nainar** [comment]
The Clang in r21 has all features implemented in clang-8 and some ongoing features for clang-9.

In general, we try to keep up with upstream's ToT (as opposed to specific numbered Clang releases) and so they should be available sooner rather than later.

**Comment by DanAlbert** [comment]
Confirmed the crash with r20, it does not reproduce with the new compiler in master (r21).

**Comment by DanAlbert** [comment]
(btw, thanks a bunch for the super simple repro case!)
