### ISSUE TITLE
[BUG] gold lays out note sections incorrectly

### ISSUE THREAD

**Issue by froydnj** [android/ndk#1063]
### Description

We are seeing GNU gold incorrectly lay out `.note.*` sections in shared libraries, which in turn causes `strip` to get confused and produce incorrect output, which in turn causes tools downstream of `strip` to complain about the incorrect data in the ELF headers.

A testcase with a `README.md` detailing the problem can be found in https://github.com/froydnj/android-note-linking-bug.  We can reproduce the bug with GNU gold from the r17b and r20 NDKs.  In short, gold combines the `.note.android.ident` and `.note.gnu.build-id` sections into a single segment, but does not correctly describe the beginning address and/or alignment of the segment, and the segment additionally takes up more space than necessary.  For whatever reason, this bug causes `strip` to do peculiar things to the binary.

Linking with GNU binutils ld or lld does not exhibit the same problem, though the other two linkers address the problem in different ways.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r20
* Build system: Custom
* Host OS: Linux, Debian/Ubuntu
* NDK API level: 21
* Device API level: N/A

**Comment by stephenhines** [comment]
We're actively working on trying to make LLD the default linker for the Android NDK, so gold bugs may not be fixed quickly. Have you considered switching to LLD by default?

**Comment by froydnj** [comment]
> We're actively working on trying to make LLD the default linker for the Android NDK, so gold bugs may not be fixed quickly. Have you considered switching to LLD by default?

The topic hasn't really come up.  We're currently on NDK r17b; has LLD improved markedly since then?  Is it likely to be the default for r21 or r22?

**Comment by DanAlbert** [comment]
> Is it likely to be the default for r21 or r22?

r22 is starting to look likely. Hard to say until we start seeing (or don't see) bugs filed against r21. The version that is in r20 had some rough edges on Windows, so I'm waiting to have one release where it looks good before flipping the default.

If you do get moved to r20 (or soon, r21), it'd be worth a shot to figure out if you're going to have any issues when the change happens.

**Comment by DanAlbert** [comment]
r22 is the plan now since r21 looks pretty good for LLD. @froydnj have you had a chance to try lld? We'll probably have a hard time getting anyone to look at gold, so I'm hoping we can call that the fix here.

**Comment by DanAlbert** [comment]
Gold is gone.
