### ISSUE TITLE
[BUG] Clang options to enable optional CPU features - do not work

### ISSUE THREAD

**Issue by psiha** [android/ndk#1066]
- NDK r20
- CMake, Ninja, Android Studio 3.3 & 3.4
- Windows

I am trying to enable VFP4 (FMA) extensions in ARMv7 builds:

- the -mfpu=neon-vfp4 options documented here https://android.googlesource.com/platform/ndk/+/master/sources/android/cpufeatures/cpu-features.h does not work (Clang rejects it as unsupported)
- the per-function way of using the GCC-style function __attribute__(( __target__("fpu=neon-vfp4") ))  also does not work (the compiler accepts it, as in compiles the code, but does not use VFP4/FMA instruction or are the intrisics to use them explicitly available - i.e. as if __ARM_FEATURE_FMA is not defined within the function)
- the cpu_dispatch function attributes also do not work (do not compile at all - as if they aren't supported for non-intel CPUs)

...but this feature/capabitility - of both being able to statically/with compile-time options and dynamically/through function attributes - use optional CPU features (such as FMA and FP16 on ARMv7 and for example DOT and FP16 compute on ARMv8) are a must for developing new HPC application without having to resort to handwritten assembly (BIG NO NO!) for every single hardware combination

**Comment by DanAlbert** [comment]
Closing since it all looks like this is working as expected. Let us know if you find a different answer for @pirama-arumuga-nainar's question in 3.

**Comment by yitshak** [comment]
תודה
בתאריך יום ו׳, 20 בספט׳ 2019, 00:13, מאת Dan Albert ‏<
notifications@github.com>:
