### ISSUE TITLE
[BUG] [bionic] [linker] Reference count of library is incorrectly incremented if any of library in dependency graph references its DT_NEEDED library.

### ISSUE THREAD

**Issue by kasper93** [android/ndk#1067]
Since I did not get any response for a month on https://issuetracker.google.com/issues/138312818 I am cross posting, I hope to get more attention here. I know it is not specifically related to NDK itself, sorry about that.

## Description

Reference counting of the libraries is broken due to invalid group handling starting from Android O. Let's consider following case:

**linker-test** -[dlopen]-> **TestLib** -[DT_NEEDED]-> **BlackBoxLib** -[10 x dlopen]-> **liblog**

**TestLib** -[DT_NEEDED]-> **liblog**

Looking at the linker code I see that whenever library is "needed" by other library it will be added to the same local_group_root which will count refs for that group.

Now let's consider our example. TestLib has dependency on **liblog** and after it is loaded any and all references to liblog will also increese reference count of TestLib which will prevent it from being unloaded if any of the library in dependency graph doesn't close liblog or have it as DT_NEEEDED.

And even if BlackBoxLib handles its dependencies properly, let say by dlclosing everything in global dtor it will not be unloaded since that destructor will not fire, because we already created a dependency cycle.

I prepared simple testcase, please refer to the code for the details. Basically BlackBoxLib doesn't release liblog which prevents TestLib from being unloaded since their reference count is incorrectly counted. **linker-test** dlopens **TestLib** which depends on **BlackBoxLib** and **liblog**. Then **BlackBoxLib** dlopens **liblog** 10 times and at this point it is impossible to unload **TestLib** as its reference count has been increased while in fact there should be only one reference to it.

The issue in on Android P+. It seems to work ok on Oreo.

### Steps to reproduce
1. Clone test project https://github.com/kasper93/android-linker-test
1. ndk-build
1. ./run.sh

#### Actual output (Android P+)

```
int main()
BlackBoxLib::BlackBoxLib()
TestLib::TestLib()
void test_lib_entrypoint()
void blackbox_entrypoint()
dlclose(libtest.so) 0: 0
dlclose(libtest.so) 1: 0
dlclose(libtest.so) 2: 0
dlclose(libtest.so) 3: 0
dlclose(libtest.so) 4: 0
dlclose(libtest.so) 5: 0
dlclose(libtest.so) 6: 0
dlclose(libtest.so) 7: 0
dlclose(libtest.so) 8: 0
dlclose(libtest.so) 9: 0
TestLib::~TestLib()
BlackBoxLib::~BlackBoxLib()
dlclose(libtest.so) 10: 0
dlclose(libtest.so) 11: -1
dlerror: dlclose failed: invalid handle: 0xb0887107
END
```

#### Expected output

```
int main()
BlackBoxLib::BlackBoxLib()
TestLib::TestLib()
void test_lib_entrypoint()
void blackbox_entrypoint()
TestLib::~TestLib()
BlackBoxLib::~BlackBoxLib()
dlclose(libtest.so) 0: 0
dlclose(libtest.so) 1: -1
dlerror: dlclose failed: invalid handle: 0x72ccd117
END
```

**Comment by rprichard** [comment]
> Since I did not get any response for a month on https://issuetracker.google.com/issues/138312818

This GitHub tracker is the right place to file the issue.

I see the same behavior when I run the linker test on an O device. IIRC, the linker's group handling was overhauled in M and hasn't substantially changed since then.

If liblog.so is already loaded before linker-test loads libtest.so, then liblog.so will be its own local group root and dlopening it again later won't increment the refcount for the libtest.so group.

**Comment by rprichard** [comment]
When Bionic loads TestLib, it becomes the local group root for TestLib, BlackBoxLib, and liblog. In principle, TestLib could have interposed symbols from the other two libraries, and if it had, then unloading TestLib would be hazardous if liblog were still loaded. Bionic avoids this hazard by incrementing the TestLib group when liblog is dlopen'ed.

It looks like libc behavior varies:
 * glibc 2.28 (from gLinux) would allow unloading TestLib as long as it didn't interpose liblog's symbols.
 * FreeBSD 11.1 appears to ignore the interposition situation, allowing a relocation to point to an unloaded DSO. (It's the app's responsibility to avoid this situation.)
 * musl's dlclose is a no-op.

**Comment by rprichard** [comment]
I don't think we're likely to do anything about this issue. I believe the current behavior was intentional, and I don't think we would want to modify the linker to allow unloading libraries more easily.

**Comment by dimitry-** [comment]
I can confirm that the current behaviour is intentional.
