### ISSUE TITLE
[BUG] add sys/sysctl.h for compatibility with other implementations

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1068]
The man page says this header is linux/sysctl.h, but BSD seems to have it as sys/sysctl.h, and glibc has a sys/sysctl.h as well. We should add the header to bionic for compatibility.

**Comment by DanAlbert** [comment]
Actually, despite glibc's wrapper:

> Glibc does not provide a wrapper for this system call; call it using syscall(2).  Or rather...  don't call it: use of this system call has long been discouraged, and it is  so  unloved  that  it  is
likely  to  disappear  in  a future kernel version.  Since Linux 2.6.24, uses of this system call result in warnings in the kernel log.  Remove it from your programs now; use the /proc/sys interface
instead.

Maybe not having this is a feature.

**Comment by enh-google** [comment]
yeah, musl doesn't have it at all. where did you come across this?

**Comment by DanAlbert** [comment]
https://stackoverflow.com/q/57681336/632035

**Comment by enh-google** [comment]
huh. how does [that](https://github.com/FFmpeg/FFmpeg/blob/7c0b3ba7ddaa6540560c8b7884697a7487b669e4/configure#L1288) compile, given that bionic doesn't have the sysctl function?

**Comment by enh-google** [comment]
if you didn't reproduce this yourself, i suspect that this (and the other issues they hit) are because they're not actually using the cross compiler for configure?

**Comment by DanAlbert** [comment]
> i suspect that this (and the other issues they hit) are because they're not actually using the cross compiler for configure?

Maybe. I haven't tried to repro it myself.

**Comment by DanAlbert** [comment]
Unless this starts being reported more widely, we probably shouldn't fix this.
