### ISSUE TITLE
[question] how to bind a thread to a specific cpu core in android?

### ISSUE THREAD

**Issue by zfk0531** [android/ndk#1074]
I found a method which uses "syscall(__NR_sched_setaffinity, tid, sizeof(mask), &mask);" to bind a thread to CPU cores in Android. But when I test on android system, this function does not always work. Some times it can bind thread to CPU cores successfully, but some times it fails. Is there any other better method to bind threads to CPU cores in Android?

Or, is there any problem in my usage of this method? I just call this function once when the thread is launched. And I am not sure which CPU core is the thread running on when this function is called.

**Comment by enh-google** [comment]
`<sched.h>` exposes the `sched_setaffinity()` function, and there's at least one CTS test that requires that it succeeds. you'll have to give more detail about "does not always work"...

**Comment by zfk0531** [comment]
Thanks very much. We do some test again. And we find that, when the Linux system shut down some cpu core by some power save mechanism such as Hotplug, we can not bind threads to specific cpu cores. If we bind threads to specific cpu cores successfully, shut down cpu core may break the binding. And the threads binded to cpu cores before will run in any cpu core. So, we guesss this problem is related to shut down cpu core. 

BTW, is there any method to disable Hotplug? or disable system to shut down cpu cores?

**Comment by enh-google** [comment]
> BTW, is there any method to disable Hotplug? or disable system to shut down cpu cores?

not that i know of. seems like that could have unfortunate consequences with overheating anyway.
