### ISSUE TITLE
llvm-strip not stripping enough

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1083]
I'm seeing incomplete stripping happening again. Stripping a binary with `llvm-strip --strip-unneeded` and then `strip --strip-unneeded` afterward yields the following with bloaty:

```
    FILE SIZE        VM SIZE
 --------------  --------------
  [NEW] +49.7Ki  [ = ]       0    .debug_loc
  [NEW] +18.7Ki  [ = ]       0    .debug_info
  [NEW] +11.7Ki  [ = ]       0    .debug_line
  [NEW] +7.15Ki  [ = ]       0    .debug_abbrev
  [NEW] +4.36Ki  [ = ]       0    .debug_str
  [NEW] +4.23Ki  [ = ]       0    .debug_ranges
  [NEW] +1.19Ki  [ = ]       0    .debug_aranges
   +32%    +104  [ = ]       0    .shstrtab
  [NEW]     +65  [ = ]       0    .debug_macinfo
  +0.2%      +4  [ = ]       0    [Unmapped]
   +31% +97.2Ki  [ = ]       0    TOTAL
```

About 100kb larger when llvm-strip is used (a 30% increase compared to GNU strip).

However, it looks like --strip-all with llvm-strip yields the same binary as GNU strip. --strip-unneeded has the same --help description in both, so it seems the behavior is wrong.

Also note that --strip-all has different behavior with llvm-strip than with GNU strip:

From llvm-strip:

> --strip-all-gnu Compatible with GNU strip's --strip-all
> --strip-all Remove non-allocated sections outside segments. .gnu.warning* sections are not removed

_Originally posted by @DanAlbert in https://github.com/android/ndk/issues/843#issuecomment-533736991_

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar found the upstream fix, so we're getting this cherry-picked for r21

**Comment by nickdesaulniers** [comment]
https://android-review.googlesource.com/c/toolchain/llvm-project/+/1127424

**Comment by DanAlbert** [comment]
Updated in master.
