### ISSUE TITLE
[question] Profiling 32-bit native code on API 15-22

### ISSUE THREAD

**Issue by rcdailey** [android/ndk#1085]
I'm using NDK r20 to build 32-bit shared libraries used via JNI on API 15, API 17, and API 22. Yes, I realize API 15 is not supported in r20 but "it just works". Let's put that aside for now.

I want to be able to profile samples of time spent in various functions in my library code. Ideally I need to do this on API 15, since this is our older device and has many performance issues. However, the documentation states that Simpleperf is only supported on API 21+, and only 26+ in some cases. It isn't clear to me why this inconsistency exists. In my case, the Profiler tools in Android Studio won't even allow me to profile C++ below API 26.

How can I sample performance on API 22 and below? Third party libraries? Some obscure hacks to get the simpleperf tooling to work? I really need advice here.

**Comment by enh-google** [comment]
@yabinc can probably explain why simpleperf doesn't work pre-21...

i don't think we have any good alternatives though. is there a reason you don't trust that the profiles on more recent releases are representative of your code running on old releases too?

**Comment by rcdailey** [comment]
At Ziosk they have have custom made hardware that runs the Android OS on it. Older devices, API 15 and 17 are locked to specific hardware and an ARM cpu. API 22 is a 3rd piece of hardware that has an x86 CPU. There are differences in CPU architecture and hardware specifications (performance) that may yield different profiling outcomes. For example, the older hardware (API 15) has much worse file IO than the newest hardware. To get the most accurate results possible, I would like to run on the API 15 platform.

**Comment by enh-google** [comment]
ah. yeah, "completely different ISA" has been known to cause differences :-)

**Comment by enh-google** [comment]
i don't know, but i suspect that the Studio decision was influenced by this:

https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/README.md#why-we-suggest-profiling-on-android-n-devices

**Comment by yabinc** [comment]
Yeah, some reasons are explained in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/README.md#why-we-suggest-profiling-on-android-n-devices

To give more details, simpleperf is a profiling tool replying on kernel functions. We don't have Android CTS tests requiring kernel functions needed for simpleperf until Android N (which is API 24).
So although we can run simpleperf on devices before Android N, there is no guarantee that the kernel on device supports it. And some functions are likely to not supported or have bugs if the kernel version is older than 3.18.

For android studio profiler tool, they don't have feature for running on old devices.

We currently don't have working solutions for sampling performance on old devices. But there
are two possible ways:
1. use ptrace to stop the app process like every 1ms, and get the stack trace of each thread.
2. create a thread in the app process, let it install an interrupt handler or stop all threads like every 1ms, and get the stack trace of each thread.

The good side of these two ways is that they don't rely on kernel functions and can work on old devices.
The bad side is that they don't use functions provided by modern kernels and hardware, and can
significantly slow down the app process.

I worked on them years before, but gave up for more meaningful stuff. We can pick them up if they are really needed.

**Comment by rcdailey** [comment]
At the moment I'm resorting to selectively defining local RAII objects in functions I want to sample that provides some timing mechanisms within the scope of those functions. It's really primitive but it's the quickest/easiest thing I can do right now. I would prefer more intrinsic introspection but it doesn't sound like I can have that. The workarounds provided above seem difficult to do.

Thanks for the help everyone.

**Comment by enh-google** [comment]
can you run your ARM binary on a modern ARM device? assuming you don't have custom hardware you need to talk to on the ziosk devices, that's going to be by far your easiest solution.

**Comment by rcdailey** [comment]
For this particular scenario, no custom hardware is necessary. However, unfortunately, the application in question requires root privileges. I'd have to find a device I can root for testing. But I do like your idea and will take it into consideration.
