### ISSUE TITLE
[BUG] __android_log_print() accepts empty tag.

### ISSUE THREAD

**Issue by stolk** [android/ndk#1087]
#### Description

adb logcat can show log entries that are missing a tag.

```
E/        (  637): vibra_led_off
E/        (  637): vibra_led_on timeout_ms = 10
E/        (  637): vibra_led_on timeout_ms = 30
E/        (  637): vibra_led_off
```

__android_log_print() should not accept logs with an empty tag.

#### Reproduction Steps
```
__android_log_print( ANDROID_LOG_WARN, "", "This Should Not Be Logged." );
```

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 20.0.5594570
* Build system: any
* Host OS: Linux
* ABI:
* NDK API level:
* Device API level: 28

**Comment by DanAlbert** [comment]
@enh-google wdyt? Any point in accepting an empty log tag? We can fix the platform to reject it and fortify the API so it's rejected at compile time if not.

**Comment by enh-google** [comment]
what's the point in _rejecting_ an empty tag? that's a behavior change to an API that's been there since the beginning, so we'd need a strong motivation to do this...

**Comment by stolk** [comment]
> @enh-google wdyt? Any point in accepting an empty log tag? We can fix the platform to reject it and fortify the API so it's rejected at compile time if not.



> what's the point in _rejecting_ an empty tag? that's a behavior change to an API that's been there since the beginning, so we'd need a strong motivation to do this...

1. It makes it harder to track down the origin of the log message.
2. It makes it harder to filter the log message.
3. No existing application will break if non-tagged messages do not make it into the log.

**Comment by enh-google** [comment]
it makes it harder to debug "why don't i see my log message?" though, and (judging by `adb logcat` on my Pixel 2 XL) there's already a bunch of Qualcomm logging relying on this.

**Comment by DanAlbert** [comment]
I'd actually misunderstood the API here, I was thinking we were talking about the `#define LOG_TAG blah` interface that the platform has for `ALOGE` and co, where it would be fairly easy to accidentally miss that.

@stolk Did you end up with an empty log tag through something similar? The missing log tag is pretty obvious to a developer calling `__android_log_print` directly, so maybe the check should be somewhere else?

> No existing application will break if non-tagged messages do not make it into the log.

You're a lot more optimistic than I am.

**Comment by alexcohn** [comment]
This specific example seems to be coming from some strangely instrumented platform code, probably [vibrator.c](https://android.googlesource.com/platform/hardware/libhardware/+/master/modules/vibrator/vibrator.c#117). This means that it cannot be fixed in NDK.

**Comment by enh-google** [comment]
`nullptr` is actually the default for `LOG_TAG` in the platform if you don't set one, and has been basically forever.

talked to the logd maintainer, and he agrees that -- though we might not do this if we were starting again from scratch -- the pain of moving all existing code to an explicit tag isn't worth the benefit.
