### ISSUE TITLE
[BUG] Failure to link an executable when using ASAN

### ISSUE THREAD

**Issue by xyzz** [android/ndk#1088]
#### Description

clang fails to link an executable when `-fsanitize=address` is used.

```
xyz@xyz-PC ~/android-ndk-r20 % cat test.c 
int main() {
	return 0;
}
xyz@xyz-PC ~/android-ndk-r20 % ./toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang test.c -o test            # this works       
xyz@xyz-PC ~/android-ndk-r20 % ./toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang test.c -fsanitize=address -o test # this doesn't work
/home/xyz/android-ndk-r20/./toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libm.so, needed by /home/xyz/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7/lib/linux/libclang_rt.asan-aarch64-android.so, not found (try using -rpath or -rpath-link)
/home/xyz/android-ndk-r20/./toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/xyz/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7/lib/linux/libclang_rt.asan-aarch64-android.so, not found (try using -rpath or -rpath-link)
/home/xyz/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7/lib/linux/libclang_rt.asan-aarch64-android.so: undefined reference to `signgam@LIBC'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When using clang++ instead, the executable does get linked (with a warning), however I haven't tested if the produced executable works:
```
xyz@xyz-PC ~/android-ndk-r20 % ./toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ test.c -fsanitize=address -o test
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
/home/xyz/android-ndk-r20/./toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/xyz/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7/lib/linux/libclang_rt.asan-aarch64-android.so, not found (try using -rpath or -rpath-link)
```

The same issue occurs with r19c and `make_standalone_toolchain`. The issue doesn't occur with standalone toolchains in r18b.

#### Environment Details

* NDK Version: 20.0.5594570
* Build system: Standalone
* Host OS: Ubuntu 18.04
* ABI: aarch64
* NDK API level: 21
* Device API level: n/a

**Comment by stephenhines** [comment]
The issue is that the sanitizer library depends on libm for some functionality. When doing a C++ compilation, libm is included by default. I am not sure if it is intentional that sanitizer runtime libraries depend on libm. @eugenis, is this actually expected?

**Comment by eugenis** [comment]
Yes, this is expected. Well, the only reason for this dependency is
the slightly insane signature of "lgamma" function, which returns part
of its result in a global variable.

This is some kind of a bug in the BFD linker. The executable itself
does not depend on libm, so there is no reason to add -lm on the link
command line. The runtime library depends on it, and the linker fails
to find this transitive dependency, specifically when non-empty
--sysroot flag is involved. Both gold and lld linkers handle this just
fine, how about -fuse-ld=gold for a workaround? "-lm" would work, too.

**Comment by xyzz** [comment]
Thanks, the `fuse-ld=gold` workaround works for my project.

**Comment by DanAlbert** [comment]
Yeah, this sounds a lot like an old bfd annoyance that was never fixed in a build we have. We're replacing bfd with lld, so nothing else to do here.
