### ISSUE TITLE
[question] Compile C++17 - recommended way 

### ISSUE THREAD

**Issue by crazyhappygame** [android/ndk#1089]
NDK20, ABI: any, System: any

1. What is recommended  way to enable C++17
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
```
2. What is the recommended NDK compiler version? C++14, C++17?
I am asking because default Android CMake 3.6 support only C++14

**Comment by DanAlbert** [comment]
If you're using a version of CMake that doesn't know about C++17, yeah, using `-std` with `CMAKE_CXX_FLAGS` is your best bet. If you're using a newer version of CMake, I think what you want is:

```cmake
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

(or the per-target equivalent, if appropriate)

The only downside to the explicit `-std` is that it's not portable if your project also builds with msvc, so make sure you guard that if needed.

**Comment by crazyhappygame** [comment]
Thank you for answer. 

Is it using of latest CMake 3.15 version recommend and fully supported? 
Is it guaranted that next ndk version will work with CMake 3.15 and newer?

p.s.
I would like to switch to latest CMake.
But why Android SDK have CMake 3.6 by default and CMake 3.10.2 optional if latest CMake can be used?

**Comment by DanAlbert** [comment]
> Is it using of latest CMake 3.15 version recommend and fully supported?
Is it guaranted that next ndk version will work with CMake 3.15 and newer?

If you find issues we'll fix them, but it's not something we actively test.

> But why Android SDK have CMake 3.6 by default and CMake 3.10.2 optional if latest CMake can be used?

That's a different team (we're responsible for the things contained in the NDK proper, so the ndk subdirectory within the SDK). Please file a bug against Studio at https://b.android.com. We'd like to see it updated as well.
