### ISSUE TITLE
[BUG] Crashes trying to compile with the optimizations turned on

### ISSUE THREAD

**Issue by alervd** [android/ndk#1090]
#### Description

Compile output:

C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -c -D__ANDROID_API__=21 -target armv7-none-linux-androideabi -gcc-toolchain C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING --sysroot=C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot -isystem C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi -isystem C:\Users\user\AppData\Local\Android\android-ndk-r20/sources/cxx-stl/llvm-libc++/include -isystem C:\Users\user\AppData\Local\Android\android-ndk-r20/sources/android/support/include -isystem C:\Users\user\AppData\Local\Android\android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -mthumb -Oz -std=gnu++14 -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION_MAJOR=6 -DAPP_VERSION_MINOR=0 -DAPP_VERSION_REVISION=0 -DAPP_VERSION_BUILD=0 -DAPP_VERSION_HASH=\"localbuild\" -DAPP_VERSION_BRANCH=\"local\" -DAPP_VERSION_TYPE=\"\" -DQT_NO_DEBUG_OUTPUT -DQT_NO_WARNING_OUTPUT -DQT_NO_DEBUG -DNDEBUG -DDOWNLOADSWWW_LIBRARY -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -IC:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww -I. -IC:/Work/Qt/5.12.5/android_armv7/include -IC:/Work/Qt/5.12.5/android_armv7/include/QtNetwork -IC:/Work/Qt/5.12.5/android_armv7/include/QtCore -I. -IC:/Work/Qt/5.12.5/android_armv7/mkspecs/android-clang -o wwwdownload.obj C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww/wwwdownload.cpp
LLVMSymbolizer: error reading file: 'kernel32.pdb': LLVM was not compiled with support for DIA. This usually means that you are not using MSVC, or your Visual Studio installation is corrupt.
LLVMSymbolizer: error reading file: 'ntdll.pdb': LLVM was not compiled with support for DIA. This usually means that you are not using MSVC, or your Visual Studio installation is corrupt.
#0 0x0000000000af4c27 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6f4c27)
#1 0x0000000000b63b65 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x763b65)
#2 0x0000000000b6657c (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x76657c)
#3 0x0000000000b69696 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x769696)
#4 0x0000000000b18d3d (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x718d3d)
#5 0x0000000000d31977 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x931977)
#6 0x0000000000d31c03 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x931c03)
#7 0x0000000000d32359 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x932359)
#8 0x0000000001210d7c (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xe10d7c)
#9 0x0000000002d30942 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2930942)
#10 0x0000000001ee1c34 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1ae1c34)
#11 0x000000000190c1f6 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x150c1f6)
#12 0x00000000015ecd76 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x11ecd76)
#13 0x00000000015c6b65 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x11c6b65)
#14 0x000000000166e401 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x126e401)
#15 0x0000000000402fac (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2fac)
#16 0x0000000002f9e8dd (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2b9e8dd)
#17 0x0000000000401395 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1395)
#18 0x00000000004014c8 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x14c8)
#19 0x00007ff801bc7974 (C:\WINDOWS\System32\KERNEL32.DLL+0x17974)
#20 0x00007ff801d0a271 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x6a271)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:\Users\user\AppData\Local\Temp\wwwdownload-0e9cdf.cpp

clang++: note: diagnostic msg: C:\Users\user\AppData\Local\Temp\wwwdownload-0e9cdf.sh
[files.zip](https://github.com/android/ndk/files/3673986/files.zip)

clang++: note: diagnostic msg: 

********************

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 20.0.5594570
* Build system: qmake (Qt framework)
* Host OS: Windows, Linux
* ABI: arm7
* NDK API level: 21
* Device API level: N/A

**Comment by alervd** [comment]
For now I have to use this to avoid the crash:
#pragma clang optimize off

**Comment by pirama-arumuga-nainar** [comment]
I don't see the error with the windows_x86_64 clang++.exe under wine or the linux clang from r20. 
 Can you re-run wwwdownload-0e9cdf.sh to check if it reproduces?  It's possible that this was a crash due to running out of memory.

**Comment by alervd** [comment]
What do you mean re-run? It happens all the time on all our machines. My PC has 8GB of memory. It's not enough for it?

**Comment by alervd** [comment]
Make sure you use the same command line switches. It's important.

**Comment by alervd** [comment]
I ran it under Windows'es Linux subsystem and did not get crash too. I.e. this sh is not able to really reproduce the problem. Getting the following output instead:

`$ ./wwwdownload-0e9cdf.sh                                                                                                                                                                                                                                              In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownload.cpp:2:                                                                                                                                                                                                                                                    In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownload.h:4:                                                                                                                                                                                                                                                      In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownloadsection.h:9:                                                                                                                                                                                                                                               In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownloader.h:9:                                                                                                                                                                                                                                                    C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww/../../../../progress/                                                                                                                                                                                       operationspeedtracker.h:62:20: error: no member named 'time' in namespace 'std';                                                                                                                                                                                        did you mean simply 'time'?                                                                                                                                                                                                                                               auto timeNow = std::time(nullptr);                                                                                                                                                                                                                                                    ^~~~~~~~~                                                                                                                                                                                                                                                              time                                                                                                                                                                                                                                                C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/include\time.h:6                                                                                                                                                                                       2:8: note: 'time' declared here                                                                                                                                                                                                                                        time_t time(time_t* __t);                                                                                                                                                                                                                                                     ^                                                                                                                                                                                                                                                               In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownload.cpp:2:                                                                                                                                                                                                                                                    In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownload.h:4:                                                                                                                                                                                                                                                      In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownloadsection.h:9:                                                                                                                                                                                                                                               In file included from C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww                                                                                                                                                                                       /wwwdownloader.h:9:                                                                                                                                                                                                                                                    C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww/../../../../progress/                                                                                                                                                                                       operationspeedtracker.h:63:9: error: no member named 'difftime' in namespace 'st                                                                                                                                                                                       d'; did you mean simply 'difftime'?                                                                                                                                                                                                                                        if (std::difftime(timeNow, m_currentSecond) >= 1)                                                                                                                                                                                                                          ^~~~~~~~~~~~~                                                                                                                                                                                                                                                          difftime                                                                                                                                                                                                                                                       C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/include\time.h:6                                                                                                                                                                                       8:8: note: 'difftime' declared here                                                                                                                                                                                                                                    double difftime(time_t __lhs, time_t __rhs);                                                                                                                                                                                                                                  ^                                                                                                                                                                                                                                                               2 errors generated.
--`

It generates compile errors here. That's not the real case for this source, as it does not really contains compile errors.

**Comment by pirama-arumuga-nainar** [comment]
Aah, my bad.  I got the same compiler error as well.  I'll run this natively on Windows tomorrow.

In the mean time, can you try with r21 canary if possible?  That has fixes for some compiler crashes.

**Comment by alervd** [comment]
I don't see it here: https://developer.android.com/ndk/downloads ...

**Comment by enh-google** [comment]
if you're looking to download an NDK canary build, you want https://ci.android.com/builds/branches/aosp-master-ndk/grid? (as described on https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md)...

**Comment by pirama-arumuga-nainar** [comment]
I'm getting the same error re: std::time when running on Windows (without WSL), with both r20 and r21.  Can you double check the repro file you uploaded?  @DanAlbert independently tried to repro and got the same issue with std::time.

**Comment by pirama-arumuga-nainar** [comment]
The issue is that the repro source is not fully preprocessed and some code gets pruned because of the _QT_HAS_INCLUDE checks.

For a proper repro, can you do the following:
1. Run the repro command, but with `-save-temps -v`
2. Attach the `.ii` file generated, and the output from `-v`?

**Comment by alervd** [comment]
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin
Found candidate GCC installation: C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi\4.9.x
Selected GCC installation: C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x
Candidate multilib: thumb;@mthumb
Candidate multilib: armv7-a;@march=armv7-a
Candidate multilib: armv7-a/thumb;@march=armv7-a@mthumb
Candidate multilib: .;
Selected multilib: armv7-a/thumb;@march=armv7-a@mthumb
 "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple thumbv7-none-linux-android -E -save-temps=cwd -disable-free -disable-llvm-verifier -discard-value-names -main-file-name wwwdownload.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature -d16 -target-feature +vfp2 -target-feature -vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature -neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file "C:\\Work\\Source\\build-fdm-Android_for_armeabi_v7a_Clang_Qt_5_12_5_for_Android_ARMv7-Release\\vmscl\\inet\\qt\\download\\downloadswww\\wwwdownload.gcno" -resource-dir "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7" -isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi" -isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sources/cxx-stl/llvm-libc++/include" -isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sources/android/support/include" -isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include" -D __ANDROID_API__=21 -D ANDROID_HAS_WSTRING -D ANDROID -D _REENTRANT -D APP_VERSION_MAJOR=6 -D APP_VERSION_MINOR=0 -D APP_VERSION_REVISION=0 -D APP_VERSION_BUILD=0 -D "APP_VERSION_HASH=\"localbuild\"" -D "APP_VERSION_BRANCH=\"local\"" -D "APP_VERSION_TYPE=\"\"" -D QT_NO_DEBUG_OUTPUT -D QT_NO_WARNING_OUTPUT -D QT_NO_DEBUG -D NDEBUG -D DOWNLOADSWWW_LIBRARY -D QT_DEPRECATED_WARNINGS -D QT_NO_DEBUG -D QT_NETWORK_LIB -D QT_CORE_LIB -I C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww -I . -I C:/Work/Qt/5.12.5/android_armv7/include -I C:/Work/Qt/5.12.5/android_armv7/include/QtNetwork -I C:/Work/Qt/5.12.5/android_armv7/include/QtCore -I . -I C:/Work/Qt/5.12.5/android_armv7/mkspecs/android-clang -isysroot "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sysroot" -internal-isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sysroot/usr/local/include" -internal-isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7\\include" -internal-externc-isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi" -internal-externc-isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sysroot/include" -internal-externc-isystem "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20/sysroot/usr/include" -Oz -Wall -W -std=gnu++14 -fdeprecated-macro -fdebug-compilation-dir "C:\\Work\\Source\\build-fdm-Android_for_armeabi_v7a_Clang_Qt_5_12_5_for_Android_ARMv7-Release\\vmscl\\inet\\qt\\download\\downloadswww" -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fno-builtin-memmove -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-slp -o wwwdownload.ii -x c++ C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww/wwwdownload.cpp -faddrsig
clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-w64-windows-gnu
ignoring nonexistent directory "C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/local/include"
ignoring nonexistent directory "C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/include"
ignoring duplicate directory "."
ignoring duplicate directory "C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi"
#include "..." search starts here:
#include <...> search starts here:
 C:/Work/Source/fdm-qml/vmscl/inet/qt/download/downloadswww
 .
 C:/Work/Qt/5.12.5/android_armv7/include
 C:/Work/Qt/5.12.5/android_armv7/include/QtNetwork
 C:/Work/Qt/5.12.5/android_armv7/include/QtCore
 C:/Work/Qt/5.12.5/android_armv7/mkspecs/android-clang
 C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi
 C:\Users\user\AppData\Local\Android\android-ndk-r20/sources/cxx-stl/llvm-libc++/include
 C:\Users\user\AppData\Local\Android\android-ndk-r20/sources/android/support/include
 C:\Users\user\AppData\Local\Android\android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include
 C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\8.0.7\include
 C:\Users\user\AppData\Local\Android\android-ndk-r20/sysroot/usr/include
End of search list.
 "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple thumbv7-none-linux-android -emit-llvm-bc -emit-llvm-uselists -save-temps=cwd -disable-free -disable-llvm-verifier -discard-value-names -main-file-name wwwdownload.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature -d16 -target-feature +vfp2 -target-feature -vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature -neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file "C:\\Work\\Source\\build-fdm-Android_for_armeabi_v7a_Clang_Qt_5_12_5_for_Android_ARMv7-Release\\vmscl\\inet\\qt\\download\\downloadswww\\wwwdownload.gcno" -resource-dir "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7" -Oz -Wall -W -std=gnu++14 -fdeprecated-macro -fdebug-compilation-dir "C:\\Work\\Source\\build-fdm-Android_for_armeabi_v7a_Clang_Qt_5_12_5_for_Android_ARMv7-Release\\vmscl\\inet\\qt\\download\\downloadswww" -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fno-builtin-memmove -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-slp -disable-llvm-passes -o wwwdownload.bc -x c++-cpp-output wwwdownload.ii -faddrsig
clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-w64-windows-gnu
#include "..." search starts here:
End of search list.
 "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple thumbv7-none-linux-android -S -save-temps=cwd -disable-free -disable-llvm-verifier -discard-value-names -main-file-name wwwdownload.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature -d16 -target-feature +vfp2 -target-feature -vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature -neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file "C:\\Work\\Source\\build-fdm-Android_for_armeabi_v7a_Clang_Qt_5_12_5_for_Android_ARMv7-Release\\vmscl\\inet\\qt\\download\\downloadswww\\wwwdownload.gcno" -resource-dir "C:\\Users\\user\\AppData\\Local\\Android\\android-ndk-r20\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7" -Oz -Wall -W -std=gnu++14 -fdebug-compilation-dir "C:\\Work\\Source\\build-fdm-Android_for_armeabi_v7a_Clang_Qt_5_12_5_for_Android_ARMv7-Release\\vmscl\\inet\\qt\\download\\downloadswww" -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fno-builtin-memmove -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-slp -o wwwdownload.s -x ir wwwdownload.bc -faddrsig
clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-w64-windows-gnu
LLVMSymbolizer: error reading file: 'kernel32.pdb': LLVM was not compiled with support for DIA. This usually means that you are not using MSVC, or your Visual Studio installation is corrupt.
LLVMSymbolizer: error reading file: 'ntdll.pdb': LLVM was not compiled with support for DIA. This usually means that you are not using MSVC, or your Visual Studio installation is corrupt.
#0 0x0000000000af4c27 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6f4c27)
#1 0x0000000000b63b65 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x763b65)
#2 0x0000000000b6657c (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x76657c)
#3 0x0000000000b69696 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x769696)
#4 0x0000000000b18d3d (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x718d3d)
#5 0x0000000000d31977 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x931977)
#6 0x0000000000d31c03 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x931c03)
#7 0x0000000000d32359 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x932359)
#8 0x0000000001210d7c (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xe10d7c)
#9 0x000000000190c632 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x150c632)
#10 0x00000000015ecd76 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x11ecd76)
#11 0x00000000015c6b65 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x11c6b65)
#12 0x000000000166e401 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x126e401)
#13 0x0000000000402fac (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2fac)
#14 0x0000000002f9e8dd (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2b9e8dd)
#15 0x0000000000401395 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1395)
#16 0x00000000004014c8 (C:\Users\user\AppData\Local\Android\android-ndk-r20\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x14c8)
#17 0x00007ff801bc7974 (C:\WINDOWS\System32\KERNEL32.DLL+0x17974)
#18 0x00007ff801d0a271 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x6a271)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: C:\Users\user\AppData\Local\Android\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:\Users\user\AppData\Local\Temp\wwwdownload-8f6314.cpp
clang++: note: diagnostic msg: C:\Users\user\AppData\Local\Temp\wwwdownload-8f6314.sh
clang++: note: diagnostic msg: 

********************

**Comment by pirama-arumuga-nainar** [comment]
`#4 0x0000000001e43747 llvm::LiveRange::join(llvm::LiveRange&, int const*, int const*, llvm
::SmallVectorImpl<llvm::VNInfo*>&) (/usr/local/google/work//ndks/r20/r20/toolchains/llvm/p
rebuilt/linux-x86_64/bin/clang+++0x1e43747`

This is the same as #1000 and #1053.  The fix should be in r21.
