### ISSUE TITLE
[BUG] AMediaCrypto_requiresSecureDecoderComponent is NOT static

### ISSUE THREAD

**Issue by peak3d** [android/ndk#1093]
#### Description

https://developer.android.com/ndk/reference/group/media.html#amediacrypto_requiressecuredecodercomponent is implemented as a static function, but the result depends on the DRM session -> a pointer to AMediaCrypto should be passed here.

Java reference: https://developer.android.com/reference/android/media/MediaCrypto.html#requiresSecureDecoderComponent(java.lang.String)

#### Environment Details

- All NDK versions
- All android versions

**Comment by enh-google** [comment]
i brought this up with the media folks, and they ask for you to file a bug with them. see "GfxMedia" on https://source.android.com/setup/contribute/report-bugs for the link.
