### ISSUE TITLE
[BUG] libunwind_llvm fails when upgraded to the version used in the platform

### ISSUE THREAD

**Issue by rprichard** [android/ndk#1094]
The NDK's libunwind_llvm is out-of-date. The latest upstream LLVM revision was r296359, from Feb 2017. https://android-review.googlesource.com/c/platform/external/libunwind_llvm/+/673669/

The platform has a newer version, r355142, from Feb 2019. https://android-review.googlesource.com/c/platform/external/libunwind_llvm/+/919535/

When I merge the platform's version into the NDK, many arm32 NDK tests fail:

```
FAIL libc++.std/strings/string.view/string.view.ops/compare.pointer_size.pass.cpp [armeabi-v7a-16-default]: android-29 walleye HT76W1A00023 QP1A.191105.004
terminating with uncaught exception of type std::out_of_range: string_view::substr
/x/ndk/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::out_of_range: string_view::substr" failed
Aborted 

FAIL libc++.std/strings/basic.string/string.ops/string_substr/substr.pass.cpp [armeabi-v7a-16-lld]: android-16 yakju 014E23851601B009 JZO54K
terminating with uncaught exception of type std::out_of_range: basic_string
assertion "terminating with uncaught exception of type std::out_of_range: basic_string" failed: file "/x/ndk/external/libcxx/../../external/libcxxabi/src/abort_message.cpp", line 72, function "abort_message"
Segmentation fault 

FAIL libc++.std/strings/basic.string/string.modifiers/string_replace/size_size_pointer_size.pass.cpp [armeabi-v7a-16-lld]: android-29 walleye HT76W1A00023 QP1A.191105.004
terminating with uncaught exception of type std::out_of_range: basic_string
/x/ndk/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::out_of_range: basic_string" failed
Aborted 

FAIL libc++.std/strings/basic.string/string.nonmembers/string.io/stream_extract.pass.cpp [armeabi-v7a-16-default]: android-29 walleye HT76W1A00023 QP1A.191105.004
terminating with uncaught exception of type std::__ndk1::ios_base::failure: ios_base::clear: unspecified iostream_category error
/x/ndk/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::__ndk1::ios_base::failure: ios_base::clear: unspecified iostream_category error" failed
Aborted 

FAIL libc++.std/strings/basic.string/string.modifiers/string_replace/size_size_pointer_size.pass.cpp [armeabi-v7a-16-lld]: android-16 yakju 014E23851601B009 JZO54K
terminating with uncaught exception of type std::out_of_range: basic_string
assertion "terminating with uncaught exception of type std::out_of_range: basic_string" failed: file "/x/ndk/external/libcxx/../../external/libcxxabi/src/abort_message.cpp", line 72, function "abort_message"
Segmentation fault 

FAIL static-executable-exceptions.static-executable [armeabi-v7a-21-lld]: android-29 walleye HT76W1A00023 QP1A.191105.004
terminating with uncaught exception of type int
/x/ndk/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type int" failed
Aborted 

...
```

**Comment by DanAlbert** [comment]
(assigned to you because I assume you're already looking at this; if not feel free to put it back in the unassigned bucket)

**Comment by rprichard** [comment]
I suspect this is caused by disagreement about the meaning of the `info.arm_section_length` field.

There were two patches one after another:
 - https://reviews.llvm.org/D30306: remove the dl_unwind_find_exidx call because we don't need it
 - https://reviews.llvm.org/D30681: switch arm_section_length from num-of-records to bytes

We require dl_unwind_find_exidx on Bionic pre-API21, so it was added back:
 - https://reviews.llvm.org/D39468

That CL set `info.arm_section_length` incorrectly when it was committed to upstream, but it worked when we cherry-picked it to the NDK's version.

The platform works (I think) because it disables the special `dl_unwind_find_exidx` call in favor of `dl_iterate_phdr`. We know that `dl_iterate_phdr` is much slower than `dl_unwind_find_exidx`, though, so we probably want to enable the special API whenever we can (Bionic + arm32).

I'll work on patches for LLVM.

**Comment by rprichard** [comment]
Even with that fix, the `static-executable-exceptions.static-executable` test still fails. The commit dropping `dl_unwind_find_exidx` above also dropped this hack:

```
-#elif defined(__linux__)
-
-typedef long unsigned int *_Unwind_Ptr;
-extern "C" _Unwind_Ptr __gnu_Unwind_Find_exidx(_Unwind_Ptr addr, int *len);
-
-// Emulate the BSD dl_unwind_find_exidx API when on a GNU libdl system.
-#define dl_unwind_find_exidx __gnu_Unwind_Find_exidx
```

Without the hack, a static executable will use the `dl_unwind_find_exidx` from `libdl_static.cpp` (which returns 0) rather than the correct `__gnu_Unwind_Find_exidx` from `exidx_static.c`

Rather than restore the hack, maybe we need to make `dl_unwind_find_exidx` in libdl_static.cpp do the right thing.

**Comment by rprichard** [comment]
Fixed: https://android-review.googlesource.com/q/topic:%22ndk-unwinder-r355152%22+(status:open%20OR%20status:merged)
