### ISSUE TITLE
[FR] Enable LLVM Polly

### ISSUE THREAD

**Issue by a1batross** [android/ndk#1096]
In our app, we don't write vectorized code by hand, instead we're relying on compiler autovectorization. In legacy NDK we used GCC's Graphite and now when we switched to latest NDK r20, I've noticed that Polly, LLVM's alternative to GCC Graphite, isn't enabled in NDK toolchains.

Simple way to check if it's enabled: 
```
$ ./aarch64-linux-android21-clang -mllvm -polly -xc -c - -o test.o < /dev/null
clang (LLVM option parsing): Unknown command line argument '-polly'.  Try: 'clang (LLVM option parsing) -help'
clang (LLVM option parsing): Did you mean '-color'?
$ echo $?
1
```

When on Clang 8 from LLVM's APT repository it doesn't show an error:
```
$ clang-8 -target aarch64-linux-android21 -mllvm -polly -xc -c - -o test.o < /dev/null
$ echo $?
0
```

Our app is crossplatform, so testing Polly on Linux ARM machine is resulted performance boost around 10%. Is there any bugs on Android so it's not available?

**Comment by stephenhines** [comment]
This is just something that we have not had time to evaluate or test in the context of Android. It is something we can look into for future releases, but I can't commit to a specific release yet.

**Comment by a1batross** [comment]
@stephenhines thanks for answer!

Actually, I have my own research with Polly on Android as part of study of how I can use thirdparty Android NDK compiler, for example, Clang/LLVM from Ubuntu repositories, apt.llvm.org or self-built, but that set up to use NDK's sysroots.
Also, being a fan of hardfloat ABI, I also set compiler to use sysroot from older NDK with uncut hardfloat ABI support. This doesn't apply to the topic, but still was a nice try.

I did ran tests and benchmarks to ensure that this way of hack didn't generated worse code than NDK's toolchain.

So, here is results: 

| Toolchain | Avg FPS |
| ------------ | ----------- |
| NDK Clang ARMv7 | 77 FPS |
| Host Clang softfp | 77 FPS |
| Host Clang hardfp | 75.8 FPS |
| Host Clang softfp Polly | 85 FPS |
| Host Clang hardfp Polly | 89 FPS |
| NDK Clang AArch64 | 100 FPS |
| Host Clang AArch64 Polly | 102 FPS |

We just ended up with renderer performance on AArch64, but for ARMv7 devices that half of our audience still uses it's given a nice performance boost.

**Comment by stephenhines** [comment]
https://android-review.googlesource.com/c/toolchain/llvm_android/+/1261718 enables this for our toolchain. We'll be marking Polly support as experimental in an upcoming release of the NDK.

**Comment by DanAlbert** [comment]
I think that change missed the train for the r22 compiler, so triaging to r23. @stephenhines please correct me/move it if that's wrong.

**Comment by stephenhines** [comment]
This actually will make it for R22, since we need to take Yabin's update as well.

**Comment by DanAlbert** [comment]
@stephenhines 

```
$ prebuilts/clang/host/linux-x86/clang-r383902c/bin/clang++ -mllvm -polly foo.cpp -c
clang (LLVM option parsing): Unknown command line argument '-polly'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--color'?
```

Seems this wasn't actually enabled? @nickdesaulniers as well because he was interested in using this.

**Comment by stephenhines** [comment]
Yeah, I missed that the build configuration wasn't actually picked up. We need to explicitly build polly (actually "Polly") and then bundle the necessary libraries to make this work. Let's move this to r23 instead.

**Comment by DanAlbert** [comment]
Bummer. https://android-review.googlesource.com/c/platform/ndk/+/1350665 fixes the changelog.

https://android-review.googlesource.com/c/platform/ndk/+/1350664 adds a test that we should submit when this gets added.

**Comment by stephenhines** [comment]
It does actually work, but Polly isn't built into the toolchain itself (and I am not 100% convinced whether we will want to do that just yet). You have to load the plugin for it to work, so the following command line works for me:

`bin/clang-11 -Xclang -load -Xclang lib64/LLVMPolly.so -target aarch64-linux-android21 -mllvm -polly -xc -c - -o test.o < /dev/null`

Note the both additional `-load` and the plugin location need to have a `-Xclang` argument in front to work properly. This method should work just fine in NDK r22, and we can look into including the plugin directly in Clang (removing the need for those extra arguments) for a future release.l

**Comment by DanAlbert** [comment]
Ah, okay. I'll retriage so I can fix the docs and add the test then.

**Comment by DanAlbert** [comment]
The windows prebuilts are missing the Polly library, so I'm not going to advertise this.

Also even with the library, needing to name LLVMPolly.so makes it annoying to write cross-platform build scripts, since you'd need to instead use LLVMPolly.dll for Windows. Getting it loaded by default for r23 is probably the right call.

**Comment by a1batross** [comment]
Good to know it's gonna be available next revision.

Thank you <3

**Comment by DanAlbert** [comment]
As long as you're not on windows you can use it with r22, fwiw. The flags listed above should work fine.
