### ISSUE TITLE
[BUG]Crash while calling string::reserve with size more than 200 MB.

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1099]
#### Description

Our application is receiving large data from the network and storing all the information in string as chars. while doing so,
if the capacity is not big enough, it is calling string::reserve to reserve extra space and then calling append to push the
data to string. Since the data is very hug, at certain point, it is calling reserve with size 270MB. We have the error handling
if reserve throws exception. This was working properly with GNUSTL. But after moving migrating to Libc++, this call is crashing.

when I dig into reserve code, there is this logic
   ```
if (__res_arg != __cap)
    {
        pointer __new_data, __p;
        bool __was_long, __now_long;
        if (__res_arg == __min_cap - 1)
        {
            __was_long = true;
            __now_long = false;
            __new_data = __get_short_pointer();
            __p = __get_long_pointer();
        }
        else
        {
            if (__res_arg > __cap)
                __new_data = __alloc_traits::allocate(__alloc(), __res_arg+1);
            else
            {
            #ifndef _LIBCPP_NO_EXCEPTIONS
                try
                {
            #endif  // _LIBCPP_NO_EXCEPTIONS
                    __new_data = __alloc_traits::allocate(__alloc(), __res_arg+1);
            #ifndef _LIBCPP_NO_EXCEPTIONS
                }
                catch (...)
                {
                    return;
                }
            #else  // _LIBCPP_NO_EXCEPTIONS
                if (__new_data == nullptr)
                    return;
            #endif  // _LIBCPP_NO_EXCEPTIONS
            }
            __now_long = true;
            __was_long = __is_long();
            __p = __get_pointer();
        }
        traits_type::copy(_VSTD::__to_raw_pointer(__new_data),
                          _VSTD::__to_raw_pointer(__p), size()+1);
```
						  
						  
traits_type::copy is called without null checking. So whenever  the allocated memory in the below condition is NULL, app is crashing.
```
if (__res_arg > __cap)
                __new_data = __alloc_traits::allocate(__alloc(), __res_arg+1);
```

Could you please let me know why there is no null check before copying the contents?? Or is it a bug?

#### Environment Details

* NDK Version: 16b
* Build system: Custom
* Host OS: Windows

**Comment by DanAlbert** [comment]
That does look like a bug. Have you tried an up to date NDK?

Either way, it looks like you're out of memory.

**Comment by pendyalasyam** [comment]
Thanks Dan for quick response. Out of memory is expected in our code and we handled it gracefully. Our project is based on ndk16b and upgrading it is so complex for us. However, in the latest NDK also code is same. Its the same logic.

**Comment by DanAlbert** [comment]
Discussed with @rprichard and it sounds like I misread the code earlier. I assume you have disabled exceptions? The allocator should throw `bad_alloc` on failure if exceptions are enabled. If they aren't enabled, there's no way to signal failure to the caller with this API. The best it could do would be to abort instead. It should maybe do that, but that doesn't help your use case.

Alternatively, do you have a custom allocator that is not throwing on failure?

GNU libstdc++ can't have done differently and still complied with the standard either, so I'm not sure why that previously worked.

**Comment by pendyalasyam** [comment]
No... we are not using custom allocator for strings.
I debugged little more and found memory allocation is being done by __builtin_operator_new(__size).
Tried to find its code but could not found in libc++ code. May be this is compiler built in operator. If so we wont be having any control over how it behaves.

**Comment by DanAlbert** [comment]
Do you disable exceptions?

**Comment by pendyalasyam** [comment]
I see all our files are compiled with -fexceptions. So I think exceptions are enabled.

**Comment by pendyalasyam** [comment]
One more observation.

In header file new, I edited the __allocate definition which is in turn called by ndk allocator

inline _LIBCPP_INLINE_VISIBILITY void *__allocate(size_t __size) {
#ifdef _LIBCPP_HAS_NO_BUILTIN_OPERATOR_NEW_DELETE
  return ::operator new(__size);
#else
  void* ptr = __builtin_operator_new(__size);
  
  if(__size > 200000000)
  {
	__android_log_print(ANDROID_LOG_ERROR, "SyamDebug", "allocating size %zu %p", __size, ptr);
  }
  if(ptr == 0 || ptr == nullptr || ptr == NULL)
	throw bad_alloc();
   return ptr;
#endif
}


Though its printing ptr as 0x0, its not hitting throw bad_alloc and reaching return at last line.

**Comment by DanAlbert** [comment]
This sounds an awful lot like a bug in `__builtin_operator_new` then. You'll need to try with an up to date NDK to confirm (use https://ci.android.com/builds/branches/aosp-ndk-release-r21/grid?head=5935234&tail=5935234, preferably).

> its not hitting throw bad_alloc

I bet the compiler is optimizing out the null check because returning null from `__builtin_operator_new` is "impossible".

**Comment by rprichard** [comment]
It looks like the compiler does optimize out a null check, https://godbolt.org/z/RhGohN. However, `__builtin_operator_new` is turning into a call to `operator new(unsigned long)`, and `operator new(unsigned long)` can't return `nullptr` (because it's supposed to throw `std::bad_alloc` on out-of-memory instead).

https://clang.llvm.org/docs/LanguageExtensions.html#builtin-operator-new-and-builtin-operator-delete:

> `__builtin_operator_new` allocates memory just like a non-placement non-class new-expression. This is exactly like directly calling the normal non-placement `::operator new`, except that it allows certain optimizations that the C++ standard does not permit for a direct function call to `::operator new` (in particular, removing `new` / `delete` pairs and merging allocations).

**Comment by DanAlbert** [comment]
Okay, so it looks like ToT Clang is at least right. @pendyalasyam, you probably need to update your NDK. I'll try the trivial giant allocation case tomorrow to see if I can confirm that.

**Comment by pendyalasyam** [comment]
Found that  __builtin_operator_new is in turn calling noexcept version operator new which is overwritten in our code. I think this seems to be issue. I think it should call into one which throws exception on allocation failure.

**Comment by DanAlbert** [comment]
> Found that __builtin_operator_new is in turn calling noexcept version operator new

... why? Played around with godbolt a bit and I couldn't get it to do that.

**Comment by pendyalasyam** [comment]
Got it... Actually we overridden ::operator new and with in we are calling functions which are noexcept. So it is not throwing exception. Problem was in our code. There seems to be no issue with libc++.

Thanks @DanAlbert & @rprichard for you guidance.
