### ISSUE TITLE
[BUG] RenderScript ScriptIntrinsicYuvToRGB is logging errors when running on Google Pixel/Pixel XL.

### ISSUE THREAD

**Issue by chandusam2002** [android/ndk#1100]
--------------------------------------------------------------------------------

#### Description
RenderScript ScriptIntrinsicYuvToRGB failing with the following error when doing a conversion from Yuv to RGB. 
2019-10-14 13:51:51.940 4811-4871/com.example.androidcamerargb W/Adreno-RS: <rsdVendorAllocationMap2:684>: Got a NULL Allocation handle! alloc: 0x7fffd9000
2019-10-14 13:51:51.940 4811-4871/com.example.androidcamerargb E/RenderScript: VendorMap Failed to map alloc: 0x7fffd9000

Other error that was noticed during the start up
2019-10-14 13:51:51.277 4811-4871/com.example.androidcamerargb W/Adreno-RS: <rsdVendorContextInitQCOM:440>: Unsupported GPU a530!
2019-10-14 13:51:51.277 4811-4871/com.example.androidcamerargb W/Adreno-RS: <rsdVendorContextInitQCOM:545>: Failed to create vendor context err 0

* This happens only on a Google Pixel XL. No issues when I tried on a Moto g 5 plus.

#### Environment Details

* NDK Version: 26.1.1
* Host OS: Mac
* NDK API level: 26.1.1

#### Code 
        Type.Builder yuvTypeBuilder = new Type.Builder(rs, Element.YUV(rs));
        yuvTypeBuilder.setX(dimensions.getWidth());
        yuvTypeBuilder.setY(dimensions.getHeight());
        yuvTypeBuilder.setYuvFormat(ImageFormat.YUV_420_888);

        mInputAllocation = Allocation.createTyped(rs, yuvTypeBuilder.create(),
                Allocation.USAGE_IO_INPUT | Allocation.USAGE_SCRIPT);

        mOutputBitmap= Bitmap.createBitmap(mDimensions.getWidth(), mDimensions.getHeight(), Bitmap.Config.ARGB_8888);
        mOutputAllocation = Allocation.createFromBitmap(mRs, mOutputBitmap);

         mInputAllocation.ioReceive();
         mYuvToRgbIntrinsic.forEach(mOutputAllocation);

         mOutputAllocation.syncAll(Allocation.USAGE_SHARED);
          mOutputAllocation.copyTo(mOutputBitmap);

**Comment by chandusam2002** [comment]
The width and height information is generated using the logic below
#### Code
    private static Size chooseOptimalSize(Size[] choices, int textureViewWidth,
            int textureViewHeight, int maxWidth, int maxHeight, Size aspectRatio) {

        // Collect the supported resolutions that are at least as big as the preview Surface
        List<Size> bigEnough = new ArrayList<>();
        // Collect the supported resolutions that are smaller than the preview Surface
        List<Size> notBigEnough = new ArrayList<>();
        int w = aspectRatio.getWidth();
        int h = aspectRatio.getHeight();
        for (Size option : choices) {
            if (option.getWidth() <= maxWidth && option.getHeight() <= maxHeight &&
                    option.getHeight() == option.getWidth() * h / w) {
                if (option.getWidth() >= textureViewWidth &&
                    option.getHeight() >= textureViewHeight) {
                    bigEnough.add(option);
                } else {
                    notBigEnough.add(option);
                }
            }
        }

**Comment by DanAlbert** [comment]
> This happens only on a Google Pixel XL. No issues when I tried on a Moto g 5 plus.

That sounds like it's a platform issue then, not an NDK issue. @miaowang14, do you agree? Should I close this and forward it to b.android.com?

> NDK Version: 26.1.1

We're on r20 right now, so if you can send me the source for r26 that would be great :)

Non-jokingly, which NDK are you using?

> NDK API level: 26.1.1

API levels are integers, so I'm not sure what this means. We need to know your minSdkVersion and the OS version the app is running on.

**Comment by chandusam2002** [comment]
@DanAlbert Apologize for the incorrect NDK version and API levels. I was looking at an source.properties file in a different directory. 

NDK Version: 20.0.5594570
minSdkVersion 24
OS Version: MacOS Mojave (version: 10.14.6)
Android Api Level: 29

**Comment by DanAlbert** [comment]
That makes more sense, thanks.

**Comment by chandusam2002** [comment]
Even with this error the yuv -> rgb conversion is succeeding.

**Comment by stephenhines** [comment]
```
2019-10-14 13:51:51.277 4811-4871/com.example.androidcamerargb W/Adreno-RS: rsdVendorContextInitQCOM:440: Unsupported GPU a530!
2019-10-14 13:51:51.277 4811-4871/com.example.androidcamerargb W/Adreno-RS: rsdVendorContextInitQCOM:545: Failed to create vendor context err 0
```
Those error strings are expected if the GPU driver is not working or unsupported. I don't think there is anything to be concerned with there, since I don't believe we had GPU-accelerated RS for Pixel. In any case, I do think that this is not an NDK bug, and is possibly a platform bug for the RS folks.
