### ISSUE TITLE
why the steady_clock is not reliable when the app running in background [question]

### ISSUE THREAD

**Issue by aldam70** [android/ndk#1101]
Info
NDK Version: r13b
ABI: armV5
Build system: Gradle

Issue

I'm using steady_clock in cpp code as a reliable timer, i know that the steady_clock is a monotonous clock and it works fine in linux demo, but port to Android ndk, it cannot calculate the elapsed time correctly, it may works fine in first several hours, but it will stop increasing and may resume increasing in about 30 mins, the behavior is weird for me! The app is running in the background.

Anyone can explain this problem? And any solution for this problem is appreciate!

Many thanks！

**Comment by enh-google** [comment]
this is WAI, i'm afraid. (`<chrono>` is a bit of a disappointment in many ways, this being one of the least of them.)

basically steady_clock is implemented by `CLOCK_MONOTONIC`, which -- as you can see from http://man7.org/linux/man-pages/man3/clock_gettime.3.html -- "does not count time that the system is suspended". what you need -- as explained on the same page -- is `CLOCK_BOOTTIME`.

here's the one we use in the Android OS itself (full [.h](https://android.googlesource.com/platform/system/core/+/refs/heads/master/base/include/android-base/chrono_utils.h), [.cpp](https://android.googlesource.com/platform/system/core/+/refs/heads/master/base/chrono_utils.cpp) and [tests](https://android.googlesource.com/platform/system/core/+/refs/heads/master/base/chrono_utils_test.cpp) also available):

```
// A std::chrono clock based on CLOCK_BOOTTIME.
class boot_clock {
 public:
  typedef std::chrono::nanoseconds duration;
  typedef std::chrono::time_point<boot_clock, duration> time_point;

  static time_point now();
};

boot_clock::time_point boot_clock::now() {
#ifdef __linux__
  timespec ts;
  clock_gettime(CLOCK_BOOTTIME, &ts);
  return boot_clock::time_point(std::chrono::seconds(ts.tv_sec) +
                                std::chrono::nanoseconds(ts.tv_nsec));
#else
  // Darwin and Windows do not support clock_gettime.
  return boot_clock::time_point();
#endif  // __linux__
}
```

**Comment by aldam70** [comment]
Thank you very much for your solution, it do work in my project!
