### ISSUE TITLE
[BUG] when swhitching from GCC to Clang, got alignment issue, here how to fix it

### ISSUE THREAD

**Issue by noangel** [android/ndk#1102]
I have a class in a header file, called Vector:

`class Vector {`
`float x, y, z, w;`
`public:`
`inline Vector4( float x, float y, float z, float w )`
`{`
`this->x=x; this->y=y; this->z = z; this->w=w;`
`}`
`inline Vector4 & Vector4::operator =( const Vector & vec )`
`{`
`    this->x = vec.x; //<--SIGBUS :(`
`    this->y = vec.y;`
`    this->z = vec.z;`
`    this->w = vec.w;`
`    return *this;`
`}`
`//a lot of code...`
`}`
`#ifdef __GNUC__`
`__attribute__ ((aligned(16)))`
`#endif`
`;`

My app uses class above for working with vectors. In my source:

`Vector v = Vector(1,1,1,1); //<--SIGBUS :(`

Looks good? It even worked... until I switched to Clang. And on some(!) phones, like Nexus 4(?!) I got SIGBUS every time I tried to run an app contains code above. "But my Vector is aligned!" thought me. Error was 16 byte alignment required, but address had 8 byte alignment. I thought, maybe my clang is old(used 16b NDK), but it worked the same built by clang from r20.
I added -O0 to build options, and it somehow fixed, but I want optimized build and make it work.
I checked my Android.mk and fortunately found a reason it crashes: LOCAL_ARM_NEON := true.
If I enable Neon, GCC somehow uses VFP almost everywhere, except Neon inline functions - these are converted to Neon code. But Clang is smarter, if I enable Neon, it tries to optimize everywhere, and Neon code used where I thought it will not be. Now I disabled Neon and it all works, but here is a ticket for You, who may have similar problem. Try to disable Neon, and check again.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: any NDK with clang support
* Build system: ndk-build on library side, CMake on app side
* Host OS: macOS 10.15, but it doesn't matter
* ABI: armeabi-v7a, may also happen on arm64-v8a
* NDK API level: 14, but it doesn't matter
* Device API level: crashed devices API level is 19-21

**Comment by DanAlbert** [comment]
You ifdef'd out the alignment attribute on Clang. Use the C++11 alignas.

**Comment by stephenhines** [comment]
> Although from the sample you gave it shouldn't be necessary? Is the code you provided complete? These issues usually come from type punning off a char array.

The alignment issue is needing 16-byte alignment for some NEON instructions. Without the additional attribute, this type only has a 4-byte required alignment. When they see an 8-byte aligned instance of it, the NEON instruction breaks (as mentioned in the initial description). __GNUC__ is the wrong macro to be checking for, as it is not set for Clang.

**Comment by DanAlbert** [comment]
@noangel can you provide the actual crashing code? There seem to be a bunch of transcription errors in your code (I see a mix of `Vector` and `Vector4`, plus you seem to be defining the assignment operator of a different class...). You may have found a bug here, but it's impossible to tell with what we were given. Please upload a repro case.

**Comment by DanAlbert** [comment]
Also, github pro tip: use fenced code blocks instead of manually turning every line of your sample into separate code section.

    ```c++
    void foo {
        bar();
    }
    ```

instead of

    `void foo {`
    `    bar();`
    `}`

It formats better *and* it's less work.

**Comment by noangel** [comment]
Sorry for being late, different timezone...

Code formatting fixed. I have many classes like Vector, it's not open source. SIGBUS always happens in Vector constructor or operator=(). Pointer caused SIGBUS has always 8 byte align, error reason is 16 byte align required.

> You ifdef'd out the alignment attribute on Clang. Use the C++11 alignas.

% ./clang -dM -E -x c /dev/null | grep __GNUC__
#define __GNUC__ 4
% ./clang --version
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: <...>/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/.

Also added `#error` into ifdef, and ndk-build gives compile error on that line, with clang, so looks like __GNUC__ is defined for me at least.

I'll try alignas:
``` class alignas(16) Vector {
...
}; ```

@DanAlbert

**Comment by DanAlbert** [comment]
> so looks like __GNUC__ is defined for me at least.

Yeah, @stephenhines corrected me on this earlier. My mistake.

> I have many classes like Vector, it's not open source.

That's often the case. This looked like something fairly simple to reduce though. I can guess at things that would cause this problem (like I did originally, type punning from an inadequately aligned type is the usual cause of this in the GCC -> Clang transition), but that's not useful if it doesn't match your use case.
