### ISSUE TITLE
[BUG] Shaderc header target does not install all required headers

### ISSUE THREAD

**Issue by sfan5** [android/ndk#1105]
#### Description

`sources/third_party/shaderc/Android.mk` contains make targets that are supposed to install the shaderc headers to `$(NDK_APP_LIBS_OUT)/../include`.
Currently, these targets install shaderc.h and shaderc.hpp.
However, the newer shaderc shipped with r21 also comes with env.h, status.h, visibility.h.

If you attempt to use shaderc as installed by Android.mk, the absence of those headers causes this error:
<pre>
In file included from ../src/spirv_shaderc.c:19:
<...>/include/shaderc/shaderc.h:26:10: fatal error: 'shaderc/env.h' file not found
#include "shaderc/env.h"
         ^~~~~~~~~~~~~~~
</pre>

#### Environment Details

* NDK Version: 21.0.5935234
* Build system: ndk-build
* Host OS: Arch Linux x86_64
* ABI: (irrelevant)
* NDK API level: (irrelevant)
* Device API level: (irrelevant)

**Comment by DanAlbert** [comment]
Reopening until we get this merged to the NDK

**Comment by dneto0** [comment]
The Shaderc patch was merged into AOSP via https://android-review.googlesource.com/c/platform/external/shaderc/shaderc/+/1148183

**Comment by DanAlbert** [comment]
@dneto0 those headers didn't used to be installed to the out directory by default, and now they are because they became a dependency of the static library. This broke the test runner.

I don't really know why we're installing these headers at all, to be honest. What's the reasoning?
