### ISSUE TITLE
[BUG] Failed to strip huge size *.so with windows_x86-64 toolchain

### ISSUE THREAD

**Issue by el8latspq** [android/ndk#1107]
#### Description

We use ndk-build to build our native code. For some reasons, we can't split the output into separated *.so files but one, which results in one single *.so file whose size is close to 2GB before being stripped. When ndk tried to strip it, error occurred with message *"Memory exhausted"*.

This problem only showed up in Windows 64-bit hosts with windows_x86-64 toolchain. After some investigations, we found that it might be a bug of binutils due to cross compiling with mingw-x64. Details are below:

Looking at `bfd_alloc` of `bfd/opncls.c`

```c
void *
bfd_alloc (bfd *abfd, bfd_size_type size)
{
  void *ret;
  unsigned long ul_size = (unsigned long) size;

  if (size != ul_size
      /* Note - although objalloc_alloc takes an unsigned long as its
	 argument, internally the size is treated as a signed long.  This can
	 lead to problems where, for example, a request to allocate -1 bytes
	 can result in just 1 byte being allocated, rather than
	 ((unsigned long) -1) bytes.  Also memory checkers will often
	 complain about attempts to allocate a negative amount of memory.
	 So to stop these problems we fail if the size is negative.  */
      || ((signed long) ul_size) < 0)
    {
      bfd_set_error (bfd_error_no_memory);
      return NULL;
    }

  ret = objalloc_alloc ((struct objalloc *) abfd->memory, ul_size);
  if (ret == NULL)
    bfd_set_error (bfd_error_no_memory);
  return ret;
}
```

The problem is, for mingw-x64, `signed/unsigned long` is actually *32 bits wide*, which means that with `size` greater than 2147483647, the condition `((signed long) ul_size) < 0` will be true. As a result, `bfd_alloc` fails with `bfd_error_no_memory`.

We tried to replace `unsigned long` with `size_t` (and some other modifications to make it compiled) , built our own binutils, and everything seemed to be fine: `strip` worked without "Memory exhausted" any more.

As it's due to cross compiling, we consider filing it here instead of upstream.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 20.0.5594570
* Build system: ndk-build
* Host OS: Windows 10 64-bit
* ABI: Any

**Comment by DanAlbert** [comment]
We moved away from binutils strip in favor of llvm-strip in r21, so this should already be fixed there (r21 is in beta, so try that if you want to be sure).

> For some reasons, we can't split the output into separated *.so files but one, which results in one single *.so file

BTW, we actually recommend that you use a single .so rather than several. It's better for both APK size and app startup time because the linker can prune more.

**Comment by el8latspq** [comment]
That's great! We have been expecting r21 for some lld bug fixes as well. We'd like to try the beta soon to confirm this.

**Comment by DanAlbert** [comment]
Yeah, Windows LLD in r21 is *much* better.
