### ISSUE TITLE
[question] why both 5.0 and 5.0.300080 headers were maintained in r16b.

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1112]
Currently we are migrating ndk in our project. Till now, r16b is being used and  we are now migrating to r21 beta. 

We had to make some tweaks in clang headers to pass our project compilation. We did the same changes in both 5.0 & 5.0.300080.

But when I am trying to migrating to r21 beta, I see there is only one folder i.e.
`android-ndk-r21-windows-x86_64\android-ndk-r21\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\9.0.8`

So I want to understand why two versions of headers were maintained in r16b and why similar requirement is not needed now?

Could some body please help me understand.

**Comment by stephenhines** [comment]
We changed the way that we build/package Clang for Android is the simple explanation. In the past, we had the separate directories because of the way we were constructing runtime libraries (and copying headers). For r21, you should be able to just use the single path (9.0.8).
