### ISSUE TITLE
[question] Why does armv7 use libunwind as the unwinder?

### ISSUE THREAD

**Issue by smeenai** [android/ndk#1113]
As https://android.googlesource.com/platform/ndk/+/HEAD/docs/BuildSystemMaintainers.md#unwinding details, the choice to use libunwind on armv7 means lots of care has to be taken to prevent unwinder clashes between libunwind and libgcc. I'm sure there's a reason libunwind is the preferred unwinder on armv7, and I wanted to find out what that was. I'm guessing there's also reasons why libunwind *isn't* the preferred unwinder on other platforms; are there plans to use it in the future?

Additionally, one other way to avoid unwinder clashes between libgcc and libunwind would be to use compiler-rt instead of libgcc, since compiler-rt doesn't have an unwinder. Is there anything to watch out for when doing this (specifically for armv7)?

**Comment by DanAlbert** [comment]
Because (when the decision was made, anyway, maybe this is no longer the case) libgcc didn't work for exception handling on arm and libunwind didn't work for exception unwinding anywhere else.

@rprichard has been looking into both of these lately so he knows better as to the future plans.

**Comment by smeenai** [comment]
Makes sense, thanks! I saw a couple of upstream libunwind diffs from @rprichard, which I assume are related :)

Also, any thoughts on using compiler-rt instead of libgcc on armv7? I've tried it and it seems to work fine in my testing; I just wanted to know if there are any known issues to watch out for with that configuration.

**Comment by stephenhines** [comment]
We use compiler-rt for everything except unwinding on AOSP (the platform OS release). As @DanAlbert mentioned, @rprichard is looking into simplifying everything so that we can just use compiler-rt by itself everywhere.

**Comment by smeenai** [comment]
Got it, makes sense. Thanks!
