### ISSUE TITLE
[Bug][Cmake][Android_LD]Does not effect at linker stage

### ISSUE THREAD

**Issue by seal2002** [android/ndk#1115]
Hello,

I compile my App with Cmake and try to use lld linker with instruction [here]
(https://github.com/android-ndk/ndk/wiki#downloads.)
The output log is receive as below

> CMake Warning:
>   Manually-specified variables were not used by the project:
>     ANDROID_LD
> CMake Warning:
>   Manually-specified variables were not used by the project:
>     ANDROID_LD

I search around the issue or documents. However, I can't find any topic relate to this,
My question is the flag **Android_LD** is exist?
My enviroments:
Windows 10 1903 64bit
Cmake 3.10.2, andorid ndk both 19 & 20.
ABI= armeabi-v7a, armeabi-v8a, x86
Android build tools= 28.0.3
Android platform API= 28
Minimum support: 19 for 32bit, 21 for 64bit

Regards,
Seal

**Comment by DanAlbert** [comment]
`ANDROID_LD` is an r21 feature.
