### ISSUE TITLE
Android Studio shows shared C++ lib's files in red.

### ISSUE THREAD

**Issue by dacobi** [android/ndk#1125]
I'm working on an Android app that uses two shared C++ libs.
First lib is SLD2 which came with Android Studio project files and works. 
I then added Bullet Physics to the project and it does compile, but all the project and source/include files are marked red.

I have this directory structure:

```
MyApp
     jni
          Android.mk
          Application.mk
          SDL2
               Android.mk
          BULLET
               Android.mk               
          src
               Android.mk                
               main.c
```
The Android.mk in jni/src has

LOCAL_SHARED_LIBRARIES := SDL2 \
                                                      libBullet

The Android.mk in jni has

include $(call all-subdir-makefiles)

What else do I need to include for Android Studio to recognise the library?

I'm using Android Studio 3.5.1 in Linux

**Comment by DanAlbert** [comment]
Does it build?

**Comment by DanAlbert** [comment]
If it builds then this is the wrong bug tracker. File the bug against studio. The NDK is not the UI.
