### ISSUE TITLE
Ad question

### ISSUE THREAD

**Issue by adquestions** [android/ndk#1126]
Hello! I have a very unique app that allows me to force my users to view ads without having to worry about them getting annoyed. My users will not be clicking on the ads though, they are only going to be forced to watch them. So, I wanted to know what are the best ads to use, where I would get the most revenue. Also, I know revenue differs because of different factors, but can I get a range or a ballpark figure as to how much revenue I can expect per impression with the information I have given you? Thank you!

**Comment by DanAlbert** [comment]
This is a bug tracker for Android C++. We don't have the answers you're looking for.
