### ISSUE TITLE
[BUG] ndkbinder causes SIGILL if ParcelFileDescriptor (ScopedFileDescriptor) is part of method argument in AIDL

### ISSUE THREAD

**Issue by atsushieno** [android/ndk#1129]
This is about ndkbinder (likely it's internal, but ndkbinder is **the** public API surface that exposes this issue).

(1) Create an .aidl file that contains an interface with a method that passes a ParcelFileDescriptor for a file descriptor e.g. a return value from `ASharedMemory_create()`.

```
interface Foo {
    void doSomething(inout ParcelFileDescriptor fd);
}
```

(2) generate ndkbinder proxy and stubs using `aidl --lang=ndk`. The corresponding C++ class would have the argument of `ScopedFileDescriptor*` type. If you have `in` parameter instead of `inout` then the type is `const ScopedFileDescriptor&`.

(3) In C++ create a class that implements `BnXxx` class (which is automatically generated, derived from `ndk::BnCInterface<Xxx>`). No need to actually write anything in the overriden method. Even an empty method can cause the problem.

(4) Create a client, bind to the service, and call the service method.

This results in:

> 2019-11-10 19:48:53.249 6976-7003/foo.bar.baz A/libc: Fatal signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr 0xc0052ea0 in tid 7003 (Binder:6976_3), pid 6976 (n.aaphostsample)

The overriden service implementation would look like this:

```
::ndk::ScopedAStatus doSomething(::ndk::ScopedFileDescriptor* in_fd) override {
}
```

It crashes at the end of the method. I believe it is at cleaning up local variables on the stack.

Neither of getR() or set(-1) on ScopedFileDescriptor* didn't help.

NdkBinedr API actually seems like some wrapper around old non-public binder API and I'm not sure if they have caused the same issue before. But ndkbinder must work now that use of non-public API is prohibited.

#### Environment

Host: Ubuntu Linux 19.04 / Android Studio 4.0.0 Canary 1 / Android sdk build tools 29.0.2 / Android ndk is 20.0.5594570 (21.0.5935234 causes `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume"` for some reason and cannot verify further. I believe it is rather about ndkbinder implementation in the system or aidl tool anyways.) / native code built with CMake 3.10.2 via build.gradle. / runtime: x86 emulator (non-Google), API Level 29

**Comment by atsushieno** [comment]
I'm trying to send an FD from ASharedMemory_create() at client to my service using ParcelFileDescriptor. When I was just using int64_t for bare FD, the int value received at the service was just invalid and ASharedMemory_getSize() returned 0. When I made changes to it to use ParcelFileDescriptor (like above), ASharedMemory_getSize() returned the expected value, so I am right on using ParcelFileDescriptor. If this method stub does not cause crash it is likely useful.

**Comment by DanAlbert** [comment]
You'll need to file a bug against the platform following http://b.android.com. The NDK only contains stubs; not the implementation, so there isn't anything we can do to fix it.

> 21.0.5935234 causes java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" for some reason

This is interesting though. Could you provide some more info? What library did that fire on?

**Comment by atsushieno** [comment]
Okay, I will file another report for platform and/or sdk there.

> This is interesting though. Could you provide some more info? What library did that fire on?

Unfortunately it is non-public source. If I could create a repro for that issue then I will file another issue here.

**Comment by atsushieno** [comment]
filed as https://issuetracker.google.com/issues/144256391, closing this issue.

**Comment by enh-google** [comment]
thanks; i've assigned that bug to the relevant engineer.

**Comment by atsushieno** [comment]
>  21.0.5935234 causes java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" for some reason

minor update on this: it did happen when I was using r20 too, so it's more likely AGP/build-tools issue. One possible cause is that I had been doing somewhat weird thing, debugging one app codebase but changing application IDs, to make them look different to the system. It might have been causing problem at Apply Changes or debugging operations. In any case it is not likely related to NDK.
