### ISSUE TITLE
[BUG] “ANeuralNetworksExecution_startCompute” can't be called twice on Android version 10.0

### ISSUE THREAD

**Issue by mingmingtasd** [android/ndk#1132]
#### Description
Sometimes we need to call the function “ANeuralNetworksExecution_startCompute” twice to realize some features. But if we call these functions in this sequence: “ANeuralNetworksExecution_startCompute(execution, &event)”-->“ANeuralNetworksExecution_wait(event)”-->“ANeuralNetworksExecution_free(event)”-->ANeuralNetworksExecution_startCompute(execution, &event)"-->(some other functions......), there will be an error described as "ANeuralNetworksExecution_startCompute" called on an execution that has already started" caused by the second calling for "ANeuralNetworksExecution_startCompute". 

While on Android version 9.0, there will be no error if we call these functions in this order.

Here's a test case you can use to reproduce this issue:

https://github.com/mingmingtasd/ndk-samples
Please visit the link above and continue to open the file named [nn_sample](https://github.com/mingmingtasd/ndk-samples/tree/master/nn_sample). Under [nn_sample](https://github.com/mingmingtasd/ndk-samples/tree/master/nn_sample), the codes for testing are all in [simple_model.cpp](https://github.com/mingmingtasd/ndk-samples/blob/master/nn_sample/app/src/main/cpp/simple_model.cpp). And you  can follow the [README.md](https://github.com/mingmingtasd/ndk-samples/blob/master/nn_sample/README.md) to reproduce.

#### Environment Details
* NDK Version: 20.1.5948944.
* Build system: CMake
* Host OS: ubuntu 16.04
* ABI: arm64-v8a
* NDK API level: 29
* Device API level: 29
* Android verison: 10.0
* Android phone: Google Pixel 2XL

**Comment by DanAlbert** [comment]
The NDK only contains the stubs for this, so there's nothing we can do to fix it. You'll need to file a platform bug following http://b.android.com.

**Comment by DanAlbert** [comment]
(we can help you get it triaged after you file it if you give us the link though)

**Comment by mingmingtasd** [comment]
@DanAlbert Hi, I submit this issue here https://issuetracker.google.com/issues/144381394. Is that OK? Thanks!!!
