### ISSUE TITLE
[question] How to build ndk's libc++_shared.so locally

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1133]
Hi Team,

I have been working on native side of android app development from some time. Our projects are so complex and so if there is any issue happening due to libc++ code, it is very difficult for us to debug. So if we know how to build libc++_shared.so, we can add debug statements as per our needs and debug issues happily.

If there is any good documentation on how to build libc++_shared.so locally, could you please provide the details. 

Thanks

**Comment by DanAlbert** [comment]
It can't be built independently: https://android.googlesource.com/platform/ndk/+/master/docs/Building.md

**Comment by pendyalasyam** [comment]
Thanks Dan.
