### ISSUE TITLE
[question] Using Android ndk in macOS Catalina

### ISSUE THREAD

**Issue by saminjv** [android/ndk#1134]
As you know macOS Catalina has more strict gatekeeper which blocks all unsigned binaries including Android ndk. Currently using Android NDK is quite painful because I have to run make and keep allowing all ndk binaries manually (e.g clang, clang++). I tested r19c, r20b and the latest beta version but all of them have this issue. Is it possible to have the latest version signed to solve this problem?

**Comment by DanAlbert** [comment]
https://github.com/android/ndk/issues/1060
