### ISSUE TITLE
[BUG] Incorrect __INTRODUCED_IN attribute for getauxval()

### ISSUE THREAD

**Issue by mdmt1** [android/ndk#1137]
getauxval() declaration in sys/auxv.h:
`unsigned long int getauxval(unsigned long int __type) __INTRODUCED_IN(18);`

This function is not available on some API 19 devices. I have encountered this on Samsung "goyavewifi" tablet (Spreadtrum SC8830 based).

Also, [cpu-features.c](https://android.googlesource.com/platform/ndk/+/ndk-release-r21/sources/android/cpufeatures/cpu-features.c#505) states:

> // Probe the system's C library for a 'getauxval' function and call it if
> // it exits, or return 0 for failure. This function is available since API
> // level 20.

**Comment by enh-google** [comment]
so it looks like it was introduced by [2c5153b043b44e9935a334ae9b2d5a4bc5258b40](https://android.googlesource.com/platform/bionic/+/2c5153b043b44e9935a334ae9b2d5a4bc5258b40%5E%21/) in 2013-01. annoyingly the build servers are refusing to tell me what releases that SHA made it into, but just from the date it's clearly way too late for API 18, so you're correct that API 18 is a mistake.

but given the date, it looks like it should have been in API 19?

i'm a bit surprised by the claim in the cpu-features.c code comment. the checkin comment had the weaker "The first one is that API level 20 exposes getauxval()".

if you have access to that device, could you check whether the libc.so on it has any of the other API level 19 functions? swapon()/swapoff(), futimens(), timerfd_create()/timerfd_settime()/timerfd_gettime(), statvfs()/fstatvfs()?

in the meantime, i'll try to find one of our API 19 devices and/or emulator images and see what they say.

reminder to self: when we update the header, update status.md to match.

**Comment by mdmt1** [comment]
> so it looks like it was introduced by 2c5153b043b44e9935a334ae9b2d5a4bc5258b40 in 2013-01. annoyingly the build servers are refusing to tell me what releases that SHA made it into, but just from the date it's clearly way too late for API 18, so you're correct that API 18 is a mistake.

Why too late? 4.3 was released in July 2013. geauxval.cpp is included in [refs/heads/jb-mr2-release](https://android.googlesource.com/platform/bionic/+/refs/heads/jb-mr2-release/libc/bionic/getauxval.cpp).

I have checked API 18 and API 19 x86 emulator images just now. getauxval() is present on both of them.

This made me look again at my code, and I found a bug in it. I was accessing getauxval() by using dlopen() + dlsym() and was calling dlopen(NULL, 0) instead of dlopen("libc.so", 0). This works on API >= 21 (which is why I didn't caught it during testing), but on API < 21 dlsym() returns NULL.

I don't have access to this Samsung "goyavewifi" tablet, but it seems that it was just the first device that hit this bug in my code. There is very small percentage of API 18 + API 19 devices among my install base and I released the fix right away, which explains why I didn't receive crashes from other devices.

So it looks like this whole bug report is a mistake on my part.

**Comment by enh-google** [comment]
> Why too late? 4.3 was released in July 2013. geauxval.cpp is included in [refs/heads/jb-mr2-release](https://android.googlesource.com/platform/bionic/+/refs/heads/jb-mr2-release/libc/bionic/getauxval.cpp).

/me bows to your superior search skills :-) (we have a really convenient search tool internally, but unfortunately its cutoff is K, and i didn't do the extra work to actually check jb-mr2.)

> This made me look again at my code, and I found a bug in it. I was accessing getauxval() by using dlopen() + dlsym() and was calling dlopen(NULL, 0) instead of dlopen("libc.so", 0). This works on API >= 21 (which is why I didn't caught it during testing), but on API < 21 dlsym() returns NULL.

ah, i see. thanks for chasing that down. (there's certainly been a lot of confusion on this issue as you can see from some of the code comments. there's at least one first-party app that thinks getauxval() doesn't arrive until API 21, perhaps because they're confused between 32-bit and 64-bit...)
