### ISSUE TITLE
 a problem with __declspec(property) in functions marked as constexpr

### ISSUE THREAD

**Issue by lukasz-szczur** [android/ndk#1141]
Hello.
In Android Studio 3.5.2 (linux version) I use Android NDK r20b (Android (5220042 based on r346389c) clang version 8.0.7).
[fsarr.txt](https://github.com/android/ndk/files/3902778/fsarr.txt) contains errors (marked in the comments) emitted by the compiler.
Is it impossible to use __declspec(property) in functions marked as constexpr?

**Comment by lukasz-szczur** [comment]
I compile the code with the following flags:
-std=c++17 -fexceptions -fdeclspec -Wall -Wextra -pedantic -Wno-unused-getter-return-value -O2

**Comment by DanAlbert** [comment]
Isn't `__declspec` a Windows-only attribute?

**Comment by lukasz-szczur** [comment]
I can use __declspec(property... in clang. I don't know if the implementation is "official", but I can declare appropriate functions and the compiler calls them when a programmer gets / sets a property (works the same way on Android and Debian). I sent a question to llvm-dev@lists.llvm.org.  No answer so far

**Comment by DanAlbert** [comment]
@stephenhines seems Clang does support `__declspec(property)`, but that it doesn't work with `constexpr`. Not sure if there's a reason for that or if it's just a bug.

**Comment by lukasz-szczur** [comment]
They changed something in x86-64 clang 10.0.0 and the snippet compiles now. The error is present in older versions of the compiler, eg. x86-64 clang 9.0.0. You can see this here https://godbolt.org/z/B6z8-F

**Comment by DanAlbert** [comment]
Cool, that simplifies things. Guess it was a bug and someone fixed it upstream already. Nothing for us to do other than continue taking updates.

**Comment by DanAlbert** [comment]
We got the fix for this at some point. Not sure when exactly, but definitely by r23.
