### ISSUE TITLE
[BUG] CMake detects incorrect operating system that run on

### ISSUE THREAD

**Issue by personshelldon** [android/ndk#1144]
Hello! I try to pass OS specific flags to `CMake` linker flags, but seems `CMake` detects host system incorrectly:
```
set(CMAKE_SHARED_LINKER_FLAGS
        "${CMAKE_SHARED_LINKER_FLAGS} -flto=full -Wl,--exclude-libs,ALL")

if(UNIX OR ANDROID_NDK_MAJOR GREATER 20)
    set(CMAKE_SHARED_LINKER_FLAGS
            "${CMAKE_SHARED_LINKER_FLAGS} -fuse-ld=lld")
endif()
```
In this case `if(UNIX)` is always `true` on Windows system.

#### Environment Details

* NDK Version: r20b
* Build system: CMake
* Host OS: Windows 10
* ABI: -
* NDK API level: -
* Device API level: -

**Comment by DanAlbert** [comment]
That's correct. You're targeting Android, which is unix-like.
