### ISSUE TITLE
Clang of NDK21-beta2 a.k.a clang-9.0.8 throws -Wstring-plus-int with (String literal + 1)

### ISSUE THREAD

**Issue by sreekanthj93** [android/ndk#1145]
Clang 9.0.8 throws an error when compiled with below code, note: compiled -Wall -Werror
#define ABC "test"
some_function((ABC + 1), some other args) this can be some_function(("TEST" + 1), some other args)
Both are exactly same..

error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]

This used to work fine till clang-8.0.7 NDK20b.

If this is a correct compilation warning, i'd like to know how it used to work till older clang(s)

**Comment by sreekanthj93** [comment]
Please don't provide a fix here..
I'm already aware of the fix.

**Comment by DanAlbert** [comment]
What's the problem? I don't understand what you're trying to describe. Can you provide the failing snippet and the clang output?

**Comment by sreekanthj93** [comment]
`function_x(const char *s) {
// do something
}
function_y() {
function_x(("LITERAL" + 1));
}
`
clang throws error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]

where-in with older clang there's no error..

**Comment by DanAlbert** [comment]
Might just be a new warning.

**Comment by sreekanthj93** [comment]
okay..

**Comment by stephenhines** [comment]
https://reviews.llvm.org/rC350335 is where this increase in strictness went into Clang. It is a pretty valid warning in most cases, and the workaround is to just use array indexing (which it suggests).
