### ISSUE TITLE
Importance of _WIN32, _LIBCPP_MSVCRT_LIKE, _LIBCPP_LOCALE__L_EXTENSIONS

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1146]
Hi Team,

I am posting this question to understand few concepts related to clang and Libc++. Currently we are upgrading NDK in our project. We are building android applications on windows using ndk.

Host OS: Windows
Target OS: Android
NDK: R21

1. I wrote a sample cpp file and generated the preprocessed file using clang++. In the generated file, I found _WIN32 is defined as 1. Please help me understand why _WIN32 is defined as 1 when building for android?
2. I found _LIBCPP_MSVCRT_LIKE as defined. Please help me understand what is the purpose of this flag?
3. My understand is that _LIBCPP_LOCALE__L_EXTENSIONS should not be defined for my configuration. Because this flag has to be enabled for BSDs where _l functions are defined. Android being non-BSD platform, the flag should not be defined. Is my understanding correct?

Thank you.

**Comment by enh-google** [comment]
how exactly did you build? it sounds to me like you built _on_ Windows without specifying an Android target, so the compiler targeted the host by default, which was Windows.

even #3 is probably because you accidentally targeted Windows:
```
#if defined(__APPLE__) || defined(__FreeBSD__) || defined(_LIBCPP_MSVCRT_LIKE) || \
    defined(__sun__) || defined(__NetBSD__) || defined(__CloudABI__)
#define _LIBCPP_LOCALE__L_EXTENSIONS 1
#endif
```

you'll probably have matched the `_LIBCPP_MSVCRT_LIKE` case.
