### ISSUE TITLE
[BUG] ld.lld generates armv4t binary when compiling for armv7

### ISSUE THREAD

**Issue by mbbill** [android/ndk#1147]
#### Description
Steps to repro:

- create a very simple test file, say "a.c"
- build it with clang `armv7a-linux-androideabi22-clang.cmd -fuse-ld=lld  -shared a.c -o a.so`
- dump header with `arm-linux-androideabi-objdump.exe -f a.so` shows
```
a.so:     file format elf32-littlearm
architecture: armv4t, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00001000
```
note the *architecture: armv4t*.

if we build without `-fuse-ld=lld`, then we get
```
a.so:     file format elf32-littlearm
architecture: arm, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000000
```
this time we get *architecture: arm*

More investigation shows that `lld` will use the first input object file as the output architecture. The full command line that `clang` internally calls `ld.lld` is pretty long and the first object file in that command line is `crtbegin_so.o`.

if we objdump the `crtbegin_so.o` we get *architecture: armv4t*

So the problem could be either in `ld.lld` or the `crtbegin_so.o`

#### Environment Details

* NDK Version: 20 (test 20b and the result is the same)
* Build system: custom
* Host OS: Windows
* ABI: arm-linux-androideabi
* NDK API level: 22
* Device API level:

**Comment by DanAlbert** [comment]
Looks like this is already fixed in r21.

```bash
$ android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi22-clang -fuse-ld=lld -shared foo.c -o libfoo21.so
$ android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-objdump -f libfoo.so

libfoo21.so:     file format elf32-littlearm
architecture: arm, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00001000
```

(used objdump from r20 just to make sure that the change was in clang/lld rather than objdump)

> if we objdump the crtbegin_so.o we get architecture: armv4t
>
> So the problem could be either in ld.lld or the crtbegin_so.o

Yeah, that's interesting. I think we only build a single CRT object per-ABI, so it's weird that this varies between LLD and Gold. We should probably fix the CRT objects to be built as arm7 either way, though I don't think it'll make much difference in behavior/performance since the CRT objects are fairly minimal.

**Comment by DanAlbert** [comment]
Thanks for the simple repro steps btw. Was trivial to verify r21.

**Comment by mbbill** [comment]
I just tried 21 beta2 and can confirm it's fixed! Thanks for the quick reply!
