### ISSUE TITLE
[question] What is the expected location for include_next header files

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1153]
Hi Team,

At some places in libc++ header files, I see they are calling #include_next to include header files from other alternative path. 

Example: 
Header: F:\androidndk21\sources\cxx-stl\llvm-libc++\include\cstddef

> // Don't include our own <stddef.h>; we don't want to declare ::nullptr_t.
> #include_next <stddef.h>

When you write this code, what is the expected location of these header files (stddef.h) ?.

For your information: I am using NDK  R21 beta2

Thanks..

**Comment by jmgao** [comment]
It'll be from the compiler's builtin headers: `toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/<version>/include/stddef.h`

**Comment by enh-google** [comment]
but clang should just do the right thing for you here, even if you have your own build system, if you just leave it alone:

https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Sysroot
