### ISSUE TITLE
[question]Should I use target-specific toolchain to support API-level above a level?

### ISSUE THREAD

**Issue by kakyoism** [android/ndk#1158]
Say if I must support API 26 and the above, should I select a level-specific toolchain, such as `aarch64-linux-android26-clang`?

**Comment by enh-google** [comment]
either that or use `-target`. the compiler needs to know what version of Android you're targeting so that you get the right declarations in the headers/libraries.

**Comment by kakyoism** [comment]
@enh-google I guess my real question is: does aarch64-linux-android26-clang support android26 AND THE ABOVE or just android26?

**Comment by enh-google** [comment]
yes, for the NDK "26" or whatever means ">= 26".

**Comment by kakyoism** [comment]
> yes, for the NDK "26" or whatever means ">= 26".

Thanks!
