### ISSUE TITLE
[question] Header include paths and undefined `size_t`

### ISSUE THREAD

**Issue by kakyoism** [android/ndk#1159]
My environment: NDK 20, macOS 10.14

Trying to build a project for arm64, I've got compiling errors about unknown C standard types, which I tried to fix by adding all possible include folders to `-I`. I've eliminated most `uint32_t`-related issues, now down to `size_t` where I'm stuck

```
In file included from conftest.c:11:
In file included from /Applications/Android/sdk/ndk-bundle/sysroot/usr/include/stdio.h:42:
In file included from /Applications/Android/sdk/ndk-bundle/sysroot/usr/include/sys/types.h:39:
/Applications/Android/sdk/ndk-bundle/sysroot/usr/include/bits/pthread_types.h:38:3: error: unknown type name 'size_t'
  size_t stack_size;
  ^
```

My flags

```shell
Host=darwin-x86_64
export TOOLCHAIN_NAME=llvm
export TOOLCHAIN_PREFIX="${ANDROID_NDK_ROOT}/toolchains/${TOOLCHAIN_NAME}/prebuilt/$Host"
ANDROID_BUILD_SYSROOT="${TOOLCHAIN_PREFIX}/sysroot"

CFLAGS="--sysroot=${ANDROID_BUILD_SYSROOT} -I${ANDROID_NDK_ROOT}/toolchains/renderscript/prebuilt/${Host}/clang-include -I${ANDROID_NDK_ROOT}/sysroot/usr/include -I${ANDROID_BUILD_PREFIX}/include -I${ANDROID_NDK_ROOT}/sources/cxx-stl/llvm-libc++/include -I${ANDROID_BUILD_SYSROOT}/usr/include/c++/v1 -I${ANDROID_BUILD_SYSROOT}/usr/include"

CPPFLAGS="--sysroot=${ANDROID_BUILD_SYSROOT} -I${ANDROID_NDK_ROOT}/toolchains/renderscript/prebuilt/${Host}/clang-include -I${ANDROID_NDK_ROOT}/sysroot/usr/include -I${ANDROID_BUILD_PREFIX}/include -I${ANDROID_NDK_ROOT}/sources/cxx-stl/llvm-libc++/include -I${ANDROID_BUILD_SYSROOT}/usr/include/c++/v1 -I${ANDROID_BUILD_SYSROOT}/usr/include -I${ANDROID_NDK_ROOT}/sysroot/usr/include"

CXXFLAGS="--sysroot=${ANDROID_BUILD_SYSROOT} -I${ANDROID_NDK_ROOT}/toolchains/renderscript/prebuilt/${Host}/clang-include -I${ANDROID_NDK_ROOT}/sysroot/usr/include -I${ANDROID_BUILD_PREFIX}/include/c++/v1 -I${ANDROID_BUILD_PREFIX}/include -I${ANDROID_NDK_ROOT}/sources/cxx-stl/llvm-libc++/include -I${ANDROID_BUILD_SYSROOT}/usr/include/c++/v1 -I${ANDROID_BUILD_SYSROOT}/usr/include" 
```

According to [the guide](https://android.googlesource.com/platform/ndk/+/ndk-release-r19/docs/BuildSystemMaintainers.md), I would not need to include folder as long as I used a correct `--sysroot` switch. But I had lots of `unknown type uint32_t` errors by doing that. That's why I tried to include more folders, which seems to have fixed those errors. 

But then how should I fix the size_t problem?

**Comment by enh-google** [comment]
you should probably try r20 or r21, which set up more things automatically. you should never need to do this.

**Comment by kakyoism** [comment]
> you should probably try r20 or r21, which set up more things automatically. you should never need to do this.

Well, I am using r20 as I listed at the top of my post.

**Comment by kakyoism** [comment]
> you should probably try r20 or r21, which set up more things automatically. you should never need to do this.

@enh-google Well, I am using r20 as I listed at the top of my post. 

May I confirm that in order to have all the include/lib paths in place, the only thing I need to do is to make my flags like these:

```shell
Host=darwin-x86_64
export TOOLCHAIN_NAME=llvm
export TOOLCHAIN_PREFIX="${ANDROID_NDK_ROOT}/toolchains/${TOOLCHAIN_NAME}/prebuilt/$Host"
ANDROID_BUILD_SYSROOT="${TOOLCHAIN_PREFIX}/sysroot"

CFLAGS="--sysroot=${ANDROID_BUILD_SYSROOT}"

CPPFLAGS="--sysroot=${ANDROID_BUILD_SYSROOT}"

CXXFLAGS="--sysroot=${ANDROID_BUILD_SYSROOT}"
```

???

**Comment by DanAlbert** [comment]
Drop basically all of those flags. You don't need to manually configure toolchain includes post-r19 (aside from the rs headers). You specifying those flags explicitly broke the compiler's include search order.

**Comment by nwardrip** [comment]
Was this issue resolved? I am running into the same issue.

**Comment by PengQ1** [comment]
I am met the same issue using r21, waiting for a solution now.

**Comment by DanAlbert** [comment]
File a new bug with repro instructions if you're having issues. The command line given above is incorrect, and that's why the problem exists. Follow the docs and file bugs if you have issues.
