### ISSUE TITLE
[question] openmp static library with NDK r21

### ISSUE THREAD

**Issue by andoroid35** [android/ndk#1160]
I'm migrating to NDK r21.
Since I want to use static openmp library, setting "-static-openmp" to CMAKE_C_FLAGS instead of "-fopenmp" used in NDK r20, but it's not working.
Is there any example to use "-static-openmp"?

**Comment by enh-google** [comment]
from the tests (https://android.googlesource.com/platform/ndk/+/master/tests/device/openmp/CMakeLists.txt) it looks like you need to supply *both* of those options for static openmp?
