### ISSUE TITLE
[BUG] mm_malloc.h:49:12: error: use of undeclared identifier 'malloc'

### ISSUE THREAD

**Issue by Gh0stBlade** [android/ndk#1162]
#### Description

Every time I compile my code using the android NDK i get the following error:
`mm_malloc.h:49:12: error: use of undeclared identifier 'malloc'`

Yet my project does not make use of malloc or free.

* NDK Version: 20.1.5948944
* Build system: CMake
* Host OS: Windows
* ABI: armeabi-v7a
* NDK API level: N/a
* Device API level: N/a

**Comment by enh-google** [comment]
there's nothing we can do to help unless you show us the source.

**Comment by Gh0stBlade** [comment]
I don't think the source is relevant here, especially since I'm working on a rather large project I doubt anyone would be interested in going through the code. It seems to be affecting even the smallest of samples of just "malloc" or "free" on its own. I had to hack mm_malloc.h to extern decl malloc and free to fix this issue.

**Comment by DanAlbert** [comment]
We don't need the full source, but we do need a repro case.

**Comment by zhangjinbiao** [comment]
I met the same problem when i import a old project which run correctly in other computer

**Comment by DanAlbert** [comment]
Same answer. We can't help without a repro case.

**Comment by DanAlbert** [comment]
Yeah, I fully believe the bug is real, we just have nowhere to begin with it.

**Comment by sunguapi** [comment]
yeah,I also encountered this problem today

**Comment by enh-google** [comment]
> yeah,I also encountered this problem today

but do you have example failing code we can use? without that, this bug will never be fixed, because we can't reproduce it.

**Comment by sunguapi** [comment]
> > yeah,I also encountered this problem today
> 
> but do you have example failing code we can use? without that, this bug will never be fixed, because we can't reproduce it.
>>
>
>>Yes, I have solved it, the reason may be that 'vscode' cannot read the header file defined by ourselves, and the header file should not be repeatedly referenced
