### ISSUE TITLE
How can I add ndk to android studio when downloaded manually? 

### ISSUE THREAD

**Issue by maveroid** [android/ndk#1163]
NDK - android-ndk-r20b-linux-x86_64.zip
OS - Manjaro Linux 18.1.5

**Comment by GeorgBorhauer** [comment]
In Android Studio you can select the compiler by yourself. Click on File --> Project Structure --> SDK Location. Choose the location where you unpack the file(No empty spaces in the path -- As well e.g. "Program Files" ;) ) and click Apply & OK

**Comment by maveroid** [comment]
Okay... Thanks a lot
But what if I want to add to path... I mean use with other frameworks like flutter... I tried creating ANDROID_NDK_ROOT but unfortunately for me it did not work... It's not listed in the sdk tools in sdk manager and Flutter didn't can't find it as well... What do you think I should do?

**Comment by GeorgBorhauer** [comment]
Extract the file in an own directory. Then you can add to Android Studio. You should be careful with the name in the path.  Otherwise, you should precise your question.

**Comment by maveroid** [comment]
Okay 👌
It worked after changing the dir
