### ISSUE TITLE
What is the reason for - error: constexpr variable 'struct2Var' must be initialized by a constant expression?

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1165]
When I am compiling the following program with clang, it is throwing error: constexpr variable 'struct2Var' must be initialized by a constant expression {var, 2100433}. If I remove __attribute__((weak)) from "var" declaration, it is passing without any issues.

struct myStruct
{
public:
constexpr myStruct(wchar_t x) : m_cch(x){}
 const wchar_t m_cch;
};

extern  __attribute__((weak)) const constexpr myStruct var('a');

struct myStruct2
{
 const wchar_t stzKey = 0;

 int intvar = 0;
};

static constexpr const myStruct2 struct2Var[1]
{
  {var.m_cch, 2100433}
};

So my guess is Clang is removing constexpr if variable is defined as __attribute__((weak)). Could you please confirm if it is the actual reason. If it is not the actual reason, kindly let me know what is the actual reason. Thanks

Repro: https://godbolt.org/z/QhhD2H

**Comment by DanAlbert** [comment]
A weak reference can't be known until the application is linked, so I'm not sure how it could be constexpr.
