### ISSUE TITLE
[FR]Is it possible to syncronize callback methods for Alooper

### ISSUE THREAD

**Issue by copypasteearth** [android/ndk#1167]
hello I have an Alooper with 2 callback functions

```
mainThreadLooper = ALooper_forThread(); // get looper for this thread
			ALooper_acquire(mainThreadLooper); // add reference to keep object alive
			pipe(messagePipe); //create send-receive pipe
			// listen for pipe read end, if there is something to read
			//// - notify via provided callback on main thread
			int com = pipe(commandPipe);
			LOGD("pipe command: %d",com);
			ALooper_addFd(mainThreadLooper, messagePipe[0],
					0, ALOOPER_EVENT_INPUT, looperCallback, NULL);
		int l = ALooper_addFd(mainThreadLooper, commandPipe[0],
					  0, ALOOPER_EVENT_INPUT, commandLooperCallback, NULL);
```

the problem is that sometimes one is called later that the other and vice versa. I was wondering if there was a way to synchronize them. I am making the write calls from a pthread

thank you for your time

**Comment by DanAlbert** [comment]
If this is actually a FR, you'll need to file a platform bug since the NDK only exposes the platform APIs; it doesn't implement them.

Someone else here (or on our mailing list, which I see you've also posted to) might know if this is currently doable or not.
