### ISSUE TITLE
How to compile PHP core  c source code with iconv[question]

### ISSUE THREAD

**Issue by arshidkv12** [android/ndk#1168]
I completed PHP c source code without iconv. It is working fine. But I can't compile PHP c source code with iconv. Where is iconv.h location in unrooted phone ? How to compile with iconv ?

**Comment by enh-google** [comment]
iconv.h was introduced in API level 28 (as you can see from looking at the header file).

if you need to target older devices (and the license is appropriate to your project), you might want to consider GNU libiconv.

**Comment by arshidkv12** [comment]
Please note, I want compile standalone PHP c source code to .so file. I can compile without iconv. But iconv not working.

**Comment by enh-google** [comment]
you'll have to give us a more reproduceable bug report than "not working". if you want us to look at this, please supply a small C program that reproduces your claimed issue. note that on Android, most character sets aren't supported, just these:
```
static bool __parse_encoding(const char* s, Encoding* encoding, Mode* mode) {
  const char* suffix = strstr(s, "//");
  if (suffix) {
    if (!mode) return false;
    if (strcmp(suffix, "//IGNORE") == 0) {
      *mode = IGNORE;
    } else if (strcmp(suffix, "//TRANSLIT") == 0) {
      *mode = TRANSLIT;
    } else {
      return false;
    }
  }
  if (__match_encoding(s, "utf8")) {
    *encoding = UTF_8;
  } else if (__match_encoding(s, "ascii") || __match_encoding(s, "usascii")) {
    *encoding = US_ASCII;
  } else if (__match_encoding(s, "utf16le")) {
    *encoding = UTF_16_LE;
  } else if (__match_encoding(s, "utf16be")) {
    *encoding = UTF_16_BE;
  } else if (__match_encoding(s, "utf32le")) {
    *encoding = UTF_32_LE;
  } else if (__match_encoding(s, "utf32be")) {
    *encoding = UTF_32_BE;
  } else if (__match_encoding(s, "wchart")) {
    *encoding = WCHAR_T;
  } else {
    return false;
  }
  return true;
}
```

**Comment by arshidkv12** [comment]
I am trying to compile
https://github.com/php/php-src

Getting error, please reinstall iconv library.





On Jan 13, 2020 10:33 PM, "enh-google" <notifications@github.com> wrote:

you'll have to give us a more reproduceable bug report than "not working".
if you want us to look at this, please supply a small C program that
reproduces your claimed issue. note that on Android, most character sets
aren't supported, just these:

static bool __parse_encoding(const char* s, Encoding* encoding, Mode* mode) {
  const char* suffix = strstr(s, "//");
  if (suffix) {
    if (!mode) return false;
    if (strcmp(suffix, "//IGNORE") == 0) {
      *mode = IGNORE;
    } else if (strcmp(suffix, "//TRANSLIT") == 0) {
      *mode = TRANSLIT;
    } else {
      return false;
    }
  }
  if (__match_encoding(s, "utf8")) {
    *encoding = UTF_8;
  } else if (__match_encoding(s, "ascii") || __match_encoding(s, "usascii")) {
    *encoding = US_ASCII;
  } else if (__match_encoding(s, "utf16le")) {
    *encoding = UTF_16_LE;
  } else if (__match_encoding(s, "utf16be")) {
    *encoding = UTF_16_BE;
  } else if (__match_encoding(s, "utf32le")) {
    *encoding = UTF_32_LE;
  } else if (__match_encoding(s, "utf32be")) {
    *encoding = UTF_32_BE;
  } else if (__match_encoding(s, "wchart")) {
    *encoding = WCHAR_T;
  } else {
    return false;
  }
  return true;
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/android/ndk/issues/1168?email_source=notifications&email_token=ABT5Y5PQN3IQKKIOTYJUNMLQ5SNFRA5CNFSM4KGBM7V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZPVUY#issuecomment-573766355>,
or unsubscribe
