### ISSUE TITLE
Migration from NDK 13 to NDK 21 - unwind exceptions, exceptions not caught

### ISSUE THREAD

**Issue by Marian-Kechlibar** [android/ndk#1169]
Hello,

so I maintain a pretty large native Android application which consists of several pure C libraries, one C++ library and some Java code. We compile the same code for Symbian, Windows and Linux, too. 

Until very recently, the Android APK was built on Linux with command-line scripts, with **NDK 13b**, **clang** compiler and **Ant**. Given that this is already a very obsolete configuration, I spent a few weeks last December porting the compilation to Microsoft Visual Studio 2019 with Ant (I could not get Gradle working flawlessly in MSVC). 

I can already build and run the project using MSVC 2019, for all targets (ARM32, ARM64, x86), it works on Google Emulator and on real devices. But I still have to build it using NDK 13b. The following code is the crucial problem when attempting migration to anything newer:

```
	try{
		ret = handledFunction(thread->iFunction, thread->iPtr);
	}catch (const TPanicEx& panic){
		//exception occured throught User::Panic, is already handled
		exitType = EExitPanic;
		ret = panic.GetCode();
		exitCategory.Copy(panic.GetText().Left(16));
	}catch(const TTerminateEx& /*ex*/){
		//Terminate exception
	}catch(const std::exception& ex){
		//std exception
		exitType = EExitPanic;
		ret = 123986; //some unique code
		TPtrC8 what((const TUint8*)ex.what());
		exitCategory.Copy(what.Left(16));
#if (PLATFORM == ANDROID) 
	} catch (__cxxabiv1::__forced_unwind&) {
		//forced unwind might be thrown by pthread_cancel or pthread_exit.
		//This exception must be rethrown otherwise the app will crash
	    throw;
#endif //PLATFORM
	}catch(...){
		//Any other exception
		exitType = EExitPanic;
		ret = 123988;
		thread->iExitCategory.Copy(_L("Unknown ex"));
	}
```
The section around **__cxxabiv1::__forced_unwind&** is where I have a big problem. This symbol is no longer visible in newer NDKs and if I just remove the code, my app will crash whenever the first thread exits, which is like 12 seconds in. 

Also, it seems that general exceptions are no longer caught. The breakpoints just won't trigger.

I know this is not a NDKs fault, just my own. But I would be very grateful for any help. I would like to compile this code against long-term NDK 21b.

**Comment by enh-google** [comment]
this comment:
```
		//forced unwind might be thrown by pthread_cancel or pthread_exit.
		//This exception must be rethrown otherwise the app will crash
```

seems odd, because Android doesn't _have_ pthread_cancel(), and our pthread_exit() doesn't actually do the forced unwind (because it didn't in 2009, and we haven't wanted to risk breaking existing code that's expecting this _not_ to happen since).

are you actually crashing because you've thrown an exception between two different shared objects? that's a fairly common failure mode on Android: https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#rtti_exceptions-not-working-across-library-boundaries

otherwise i'd recommend running this in the debugger and seeing what's actually being thrown here, because it seems unlikely that it's what you _think_ is happening.

**Comment by Marian-Kechlibar** [comment]
Something very strange is definitely happening.

I tried to run the application under debugger when built against NDK 13b. This is a version of the app which runs correctly on the device, or at least seems to.

Breakpoints in C++ code are getting hit, breakpoints in Java code are not getting hit.

Anyway, the application starts up, the C++ code in main() runs, but then I start receiving a long sequence of "Segmentation faults" in the very first thread of the app (its id is 1 and its name is equal to the name of the app), which is probably created by the system. Unfortunately, there is no further information, just "Uncaught exception", "Segmentation fault", and the stack frame says "Unknown/Just-In-Time Compiled code". 

I wonder if the GLES application window has been initialized incorrectly or what.

The fun is, we have been developing this app since 2010, plenty of end customers have it and so far, no one knew that Segmentation faults happen in the very first thread.

I am not sure what to do now. Segfault is a serious problem, but I do not have any clue as what is happening and before sanitizing this, I cannot proceed to the problem that I asked you to help with. Any ideas?

**Comment by enh-google** [comment]
> Anyway, the application starts up, the C++ code in main() runs, but then I start receiving a long sequence of "Segmentation faults" in the very first thread of the app

that makes me think that you're debugging old school with gdb? the ART runtime uses SIGSEGV for NullPointerExceptions rather than emitting actual checks in the code, if it can prove that the offset will be small enough that it can't reach mapped readable/writable memory. there's a script somewhere to shut gdb up, but i don't know if it's included in NDK.

what i actually meant was "use Android Studio's debugger". that way everything just works out of the box.

(note to self that we should look into ensuring the script is in the NDK [and probably used by ndk-gdb by default!].)

**Comment by Marian-Kechlibar** [comment]
> that makes me think that you're debugging old school with gdb? 

Indeed I am, because that is what MSVC does by default. I am not even sure if it can be made to use a different debugger.

We develop this software mostly using Microsoft Visual Studio and test it on Windows. We used to cross-compile it for Android from command line (using ndk-build) on Linux, but a month ago I spent a few weeks setting up a MSVC project for Android, and I succeeded, or so I thought...

The intent was to have a single IDE (Microsoft Visual Studio) for both the Windows and Android port, given that me and my colleagues are used to working with MSVC. We already have some automatic build system based on MSVC as well.

That is why I wanted to avoid developing under Android Studio. But if it is necessary for advanced debugging, I may try cobbling the Android Studio project together. 

> the ART runtime uses SIGSEGV for NullPointerExceptions rather than emitting actual checks in the  code, if it can prove that the offset will be small enough that it can't reach mapped readable/writable memory. there's a script somewhere to shut gdb up, but i don't know if it's included in NDK.

This is probably the real cause for the SIGSEGVs. When I switch to Java debugging, I see a lot of uncaught NullPointerExceptions in the output, together with some NumberFormatExceptions etc., but the SIGSEGVs are no longer present. I am not sure where all those exceptions come from... if I had any clue, I would try to eliminate them.

> 
> what i actually meant was "use Android Studio's debugger". that way everything just works out of the box.

I will try to set up the Android Studio project, but it may take some days. Setting up the MSVC solution took me more than a week.

> 
> (note to self that we should look into ensuring the script is in the NDK [and probably used by ndk-gdb by default!].)

**Comment by Marian-Kechlibar** [comment]
Update: I was able to determine where these NullPointerExceptions come from. 
They are deep in the system libraries, in MediaCodecList.getCodecInfo(). They are caught there, but the NDK will still re-interpret them as SIGSEGV. And given how many codecs are there, it is about 60 SIGSEGVs.
I commented out the call, it was not necessary for the program run. So now I can actually debug on device, great.

**Comment by Marian-Kechlibar** [comment]
Once I got the Null Pointer Exceptions out of the way, my application works great on the device. The unwind exception was not necessary and, as you said, does not really appear. The problem was the SIGSEGVs emerging from the Null Pointer Exceptions.

I suggest that you look at this (SIGSEGV from a caught and handled Null Pointer Exception looks like an overkill to me), but my own problem is probably solved. Thank you for the SIGSEGV hint, without it, I would be stranded.

**Comment by DanAlbert** [comment]
That's how null pointer handling works in most language runtimes. The operation is allowed to segfault and the runtime handles the signal, turning it into an exception. Android has had this behavior for quite some time.

**Comment by Marian-Kechlibar** [comment]
I can accept that, but in that case, it needs to be addressed in the OS itself. If a fairly innocent system API call such as MediaCodecList.getCodecInfos() generates almost a hundred Null Pointer Exceptions internally, it makes debugging on such device all but impossible. This is e.g. case of my Galaxy A70.

Maybe I should report this somehow to Google.
