### ISSUE TITLE
[BUG] TSAN linkage is broken in r21

### ISSUE THREAD

**Issue by vlovich** [android/ndk#1170]
#### Description

A basic test program fails to link against TSAN on r21 with:
```
/toolchain/llvm-project/compiler-rt/lib/tsan/rtl/tsan_platform_linux.cc:428: error: undefined reference to '__tsan::__interception::real_setjmp'
/toolchain/llvm-project/compiler-rt/lib/tsan/rtl/tsan_platform_linux.cc:428: error: undefined reference to '__tsan::__interception::real_setjmp'
```

This has been fixed in upstream rL365806 but r21 has been branched from r365631 before this fix was landed.

Test case:
```
#include <future>

int main() {
  while (true) {
    auto f = std::async([] { return 123; });
    if (!f.valid()) {
      return 1;
    }
    if (f.get() != 123) {
      return 1;
    }
    if (f.valid()) {
      return 1;
    }
  }
}
```

#### Environment Details
Pkg.Desc = Android NDK
Pkg.Revision = 21.0.6113669

Build system: Standalone toolchain
Host OS: Windows & Mac

**Comment by DanAlbert** [comment]
Same answer as in https://github.com/android/ndk/issues/1171 for now. Closing as dup
