### ISSUE TITLE
[BUG]Error: D register out of range for selected VFP version -- `vcvt.u32.f64 s0,d16'

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1172]
Hi Team,

We are currently doing NDK upgrade from version R16 to R21 and during the process we are encountering the following error while building for android-arm.

C:\Users\user1\AppData\Local\Temp\RegisterConsumer-3cb299.s:958: Error: D register out of range for selected VFP version -- `vcvt.u32.f64 s0,d16'

If I change our compilation flag from -mfpu=vfp to -mfpu=vfpv3-d16, the error is disappeared.

I dont have much idea about vfp and vfpv3-d17 and their internal details, so I am not sure about its runtime implications.

Could you please tell me why it is not failing with R16 and why it is failing with R21. 

Also please help me understand the implications of changing -mfpu from vfp to vfpv3-d16?

Thanks...

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: R21 beta2
* Build system: custom
* Host OS: Windows

**Comment by pirama-arumuga-nainar** [comment]
https://embeddedartistry.com/blog/2017/10/11/demystifying-arm-floating-point-compiler-options/ describes vfp, vfpv3 etc.

https://en.wikipedia.org/wiki/List_of_ARM_microarchitectures lists some processors that support vfpv3.

Based on the first link, D16 should only be available in vfpv3-d32 and not vfpv3-d16.  Also, was this generated by the compiler or is it inline assembly?  If you could provide a repro (esp. if it was generated by the compiler), it could help understand why this used to work in r16.

**Comment by DanAlbert** [comment]
I'm assuming you got the answer you needed, so closing. If not, Pirama has some questions that we'll need answer to.
