### ISSUE TITLE
import itertools ImportError: dlopen(/Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/itertools.so

### ISSUE THREAD

**Issue by k3vinlusec** [android/ndk#1173]
Hi, I was trying to debug .so in an app with gdb,   I encountered the following error. 
k3vin@Kais-MacBook-Pro bin % ./gdb
Traceback (most recent call last):
  File "/Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/share/gdb/python/gdb/__init__.py", line 143, in auto_load_packages
    __import__(modname)
  File "/Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/share/gdb/python/gdb/command/frame_filters.py", line 22, in <module>
    from gdb.FrameIterator import FrameIterator
  File "/Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/share/gdb/python/gdb/FrameIterator.py", line 17, in <module>
    import itertools
ImportError: dlopen(/Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/itertools.so, 2): Symbol not found: _PyBool_Type
  Referenced from: /Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/itertools.so
  Expected in: flat namespace
 in /Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/lib/python2.7/lib-dynload/itertools.so

GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) 

GDB is located at /Users/k3vin/Library/Android/sdk/ndk/21.0.6113669/prebuilt/darwin-x86_64/bin

How to fix the error? Thanks!

**Comment by k3vinlusec** [comment]
The testing system:  MacBook Pro,  macOS 10.15.2.   Could you reproduce it?

**Comment by enh-google** [comment]
(i see the same on 10.14 if i run `./prebuilt/darwin-x86_64/bin/gdb`, so i don't think this is 10.15-specific.)

**Comment by k3vinlusec** [comment]
I want to use GEF in GDB to debug the app,   if this issue won't be fixed, I cannot use GEF in GDB.

**Comment by DanAlbert** [comment]
@hhb have you had a chance to look at this?

**Comment by k3vinlusec** [comment]
I compile the gdb 8.3 source code from google android by myself, and set target aarch64-linux-android, built with python3, it works well with GEF-gdb

**Comment by hhb** [comment]
I'm still trying to figure out what's happening. _PyBool_Type is defined in libpython2.7.a. libpython is statically linked into gdb binary. But gdb doesn't export any symbol. Linking flag issue?

It is also interesting that this didn't cause any problem on other platforms.

**Comment by hhb** [comment]
The unstripped binary does have PyBool_Type. Maybe we should not strip it.

**Comment by DanAlbert** [comment]
IIRC there's a flag to choose specific symbols to avoid stripping. I would assume that if it needs to continue exporting "unused" symbols there's probably a version script that goes with it?

**Comment by enh-google** [comment]
`strip --keep-symbol`

**Comment by DanAlbert** [comment]
Fix is in build 6352462 on https://ci.android.com/builds/branches/aosp-ndk-release-r21/grid?
