### ISSUE TITLE
How to link libandroid_runtime.so/libnativehelper.so for Android 10 ?

### ISSUE THREAD

**Issue by wxuefei** [android/ndk#1186]
NDK version 20/21, arm64, windows

My so module works fine before android 10, but build failed for  android 10. I create a minimum project for this problem:

Android.mk
=
LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE:= test3

LOCAL_SRC_FILES:= 	test3.cpp 

LOCAL_CPPFLAGS += -std=c++17

ALPS_ROOT = D:/android/android_source/android10/alps
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/base/include 
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/native/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/av/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/native/libs/binder/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/base/libs/androidfw/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/core/base/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/core/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/core/libcutils/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/core/libutils/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/core/liblog/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/core/libsystem/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/hardware/libhardware/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/hardware/libhardware_legacy/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/external/skia/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/external/skia/include/core
LOCAL_CFLAGS += -I$(ALPS_ROOT)/external/skia/include/config/
LOCAL_CFLAGS += -I$(ALPS_ROOT)/external/tinyalsa/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/bionic/libc/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/bionic/libc/kernel/uapi
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/libhidl/base/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/libhidl/transport/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/system/libhidl/transport/token/1.0/utils/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/hardware/interfaces/graphics/bufferqueue/1.0
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/wilhelm/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/native/libs/nativebase/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/native/libs/nativewindow/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/native/libs/math/include
LOCAL_CFLAGS += -I$(ALPS_ROOT)/external/skia/include/gpu
LOCAL_CFLAGS += -I$(ALPS_ROOT)/bionic/libc/kernel/android/uapi
LOCAL_CFLAGS += -I$(ALPS_ROOT)/frameworks/native/opengl/include

LOCAL_LDFLAGS	+= -Wl,-rpath-link,../android-libs-arm64-v8a 
LOCAL_LDFLAGS	+= -L../android-libs-arm64-v8a

LOCAL_LDLIBS	+= -lm -llog 

LOCAL_LDLIBS	+= -landroid 
LOCAL_LDLIBS	+= -lEGL -lGLESv1_CM -lGLESv2 -lOpenSLES
LOCAL_LDLIBS	+= -lutils 
LOCAL_LDLIBS	+= -lgui 
LOCAL_LDLIBS	+= -lsync 
LOCAL_LDLIBS	+= -lnativewindow
LOCAL_LDLIBS	+= -lnativehelper
LOCAL_LDLIBS	+= -landroid_runtime

include $(BUILD_EXECUTABLE)

test3.cpp
=
#include <EGL/egl.h>
#include <GLES/gl.h>

#include <android/log.h>
#include <utils/Log.h>
#include <gui/Surface.h>
#include <gui/SurfaceComposerClient.h>
#include <gui/ISurfaceComposer.h>
#include <ui/DisplayInfo.h>

using namespace android;

int main(int argc, char **argv) {

	sp<SurfaceComposerClient> client = new SurfaceComposerClient();
	
	sp<SurfaceControl> surfaceControl = client->createSurface(String8("resize"),
		100, 100, PIXEL_FORMAT_RGBX_8888, 0);
	
	return 0;
}

output
=
Android NDK: WARNING:jni/Android.mk:test3: non-system libraries in linker flags: -lutils -lgui -lnativehelper
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[arm64-v8a] Compile++      : test3 <= test3.cpp
[arm64-v8a] Executable     : test3
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniThrowException@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniThrowNullPointerException@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniGetReferent@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniGetNioBufferBaseArrayOffset@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'JniInvocationCreate@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniThrowIOException@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniLogException@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniGetNioBufferBaseArray@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniGetFDFromFileDescriptor@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'JniInvocationDestroy@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'JniInvocationInit@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniThrowExceptionFmt@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'JNI_CreateJavaVM@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniThrowRuntimeException@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniSetFileDescriptorOfFD@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniCreateFileDescriptor@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniGetNioBufferPointer@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniGetNioBufferFields@LIBNATIVEHELPER_1'
../android-libs-arm64-v8a/libandroid_runtime.so: undefined reference to 'jniRegisterNativeMethods@LIBNATIVEHELPER_1'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [d:/Android/ndk21/build//../build/core/build-binary.mk:738: obj/local/arm64-v8a/test3] Error 1

**Comment by ggfan** [comment]
this lib is your own lib? I though you are supposed to use [PREBUILT_SHARED_LIBRARY](https://developer.android.com/ndk/guides/prebuilts).  a while back there is [a sample for that,](https://github.com/android/ndk-samples/blob/master/other-builds/ndkbuild/hello-libs/app/Android.mk) you might try it out.  The build warning seems to be related to your usage.

**Comment by DanAlbert** [comment]
That's not a valid NDK project. Like the warning says, those are system libraries that are not available to apps. If you're not building an app, don't use the NDK.

**Comment by wxuefei** [comment]
My project is a share library, it uses some native api, it works fine before Android 10.
What's the LIBNATIVEHELPER_1 mean ? 
It's  forbidden for Android 10 ??

**Comment by wxuefei** [comment]
> That's not a valid NDK project. Like the warning says, those are platform libraries that are not available to apps. If you're not building an app, don't use the NDK.

This project just is minimum demo. My project is a share library, it uses some native api, it works fine for Android 2~9.
What's the LIBNATIVEHELPER_1 mean ?
It's forbidden for Android 10 ??

**Comment by ggfan** [comment]
if you are directly building inside android source tree, you would essentially follow android develop tradition on aosp, and build your app in that environment; if you want to use services in android not exposed from NDK, you do it with your own way ( open lib with dlopen() and get the function entry points for your known lib at your application run time, not linking time ).

**Comment by wxuefei** [comment]
> if you are directly building inside android source tree, you would essentially follow android develop tradition on aosp, and build your app in that environment; if you want to use services in android not exposed from NDK, you do it with your own way ( open lib with dlopen() and get the function entry points for your known lib at your application run time, not linking time ).

Thanks! I'll try it!

**Comment by DanAlbert** [comment]
No, those are not app APIs. If you're able to load them from the system in an app it's a bug. The libraries are not exposed to apps because they do not have a stable ABI. Your app *will* be broken on a future release.

If you need those libraries, you need to copy them into your APK.

**Comment by wxuefei** [comment]
> No, those are not app APIs. If you're able to load them from the system in an app it's a bug. The libraries are not exposed to apps because they do not have a stable ABI. Your app _will_ be broken on a future release.
> 
> If you need those libraries, you need to copy them into your APK.

Thanks !

**Comment by IHbib** [comment]
I apologize for reopening this issue but I am interested into the technical reason as to why the linker couldn't link libnativehelper.so with libandroid_runtime.so. It's for educational purposes if you wouldn't mind.

After looking into libnativehelper.so myself it seems any strings regarding "LIBNATIVEHELPER_1" are missing though I'm unsure as to whether that's important. The exported functions do exist though so why wouldn't the linker link the functions when they clearly exist?

**Comment by Bajranghudda** [comment]
I am also facing similar kind of problem, I am also using both libraries as a dependency in my library. But I am getting errors while I am putting product_specific: true in my library. The error is - 

```
Android.bp : dependency "libnativehelper" of "mylib" missing varient : 
missing variant:
  os:android, image:vendor.30, arch:arm_armv8-2a_cortex-a75, sdk:, link:shared, version:
available variants:
  os:android, image:, arch:arm64_armv8-a_kryo300, sdk:, link:shared, version:
  os:android, image:, arch:arm_armv8-2a_cortex-a75, sdk:, link:shared, version:
  os:linux_glibc, arch:x86, link:shared
  os:linux_glibc, arch:x86_64, link:shared
  os:windows, arch:x86, link:shared
  os:windows, arch:x86_64, link:shared
```

**Comment by DanAlbert** [comment]
That's not related to the NDK. File a platform bug at b.android.com.
