### ISSUE TITLE
[BUG] cannot locate symbol "__aeabi_memclr8" referenced by lib${NAME}.so

### ISSUE THREAD

**Issue by Yaakushi** [android/ndk#1188]
#### Description

I'm trying to compile two libraries -- `libtwampc.so` and its dependency, `libdep.so` -- using the NDK for the `armeabi-v7a` ABI, although, while I can load both libraries and use them successfully in most devices, I've come across a few cases while `libdep.so` is successfully load, and yet, when I try to subsequently load `libtwampc.so`, I get a `java.lang.UnsatisfiedLinkError` Exception thrown, like this:

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.ceptro.simet.medidor, PID: 25434
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr8" referenced by "libtwampc.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at br.ceptro.simet.medidor.TwampFragment.<clinit>(TwampFragment.kt:21)
        at br.ceptro.simet.medidor.MainActivity$onCreate$1.onNavigationItemSelected(MainActivity.kt:19)
        at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:204)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:115)
        at android.view.View.performClick(View.java:4640)
        at android.view.View$PerformClick.run(View.java:19431)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5598)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
```

I don't have a whole lot of devices to test on, but all of the failing devices seem to be running some version of Android 4.*, even if I'm targeting API level 16 in the NDK build (as well as in the `minSdkVersion`, even if that shouldn't matter).

I'm aware of issue #126, and I even posted there, and I was told to post the output of `readelf -sW libtwampc.so | grep memclr8`:

```
   1: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __aeabi_memclr8
1101: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __aeabi_memclr8
```

I'll try to come up with a proper test case, since the library with the issue is somewhat complex.

#### Environment Details

* NDK Version: 20.1.5948944
* Build system: Standalone toolchain
* Host OS: Arch Linux 
* ABI: armeabi-v7a
* NDK API level: 16
* Device API level: 18
* CPPFLAGS used in build: `-g -fPIC -DANDROID_PLATFORM=android-16 -DAPP_PLATFORM=android-16 -D__ANDROID_API__=16`
* Environment setup:
```bash
export ARCHITECTURE=armv7a-linux-androideabi
export API_LEVEL=16

export NDK_VERSION=20.1.5948944
export NDK=$HOME/Android/Sdk/ndk/$NDK_VERSION/
export HOST_TAG=linux-x86_64

export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/$HOST_TAG
export AR=$TOOLCHAIN/bin/${ARCHITECTURE}-ar
export AS=$TOOLCHAIN/bin/${ARCHITECTURE}-as
export CC=$TOOLCHAIN/bin/${ARCHITECTURE}${API_LEVEL}-clang
export CXX=$TOOLCHAIN/bin/${ARCHITECTURE}${API_LEVEL}-clang++
export LD=$TOOLCHAIN/bin/${ARCHITECTURE}-ld
export RANLIB=$TOOLCHAIN/bin/${ARCHITECTURE}-ranlib
export STRIP=$TOOLCHAIN/bin/${ARCHITECTURE}-strip
```

**Comment by Yaakushi** [comment]
That's embarrassing, I meant to add a line break and I somehow pressed ctrl+enter instead of just enter, then github just posted the issue with most of the details lacking. Sorry about that, but I've added the missing information and I'm reopening the issue now.

**Comment by DanAlbert** [comment]
Could you also try running https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/parse_elfnote.py on your libraries? That should give you output like the following:

```bash
$ ./parse_elfnote.py ~/src/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libc++_shared.so 
----------ABI INFO----------
ABI_ANDROID_API: 16
ABI_NDK_VERSION: r21
ABI_NDK_BUILD_NUMBER: 6113669
```

It sure looks like you're not actually getting the API set correctly, but your flags look right to me.

**Comment by Yaakushi** [comment]
Funnily enough, trying to run the `parse-elfnote` python script on the faulty lib yielded me this:

`error: failed to find section: .note.android.ident`

While running the same script on `libdep.so` yielded me the expected result:

```
----------ABI INFO----------
ABI_ANDROID_API: 16
ABI_NDK_VERSION: r20b
ABI_NDK_BUILD_NUMBER: 5948944
```

I've tried to manually build the faulty lib to make sure there was nothing wrong going on with the build system, but even then, I got the same error from the parse-elfnote.

**Comment by rprichard** [comment]
I would have thought that an Android 4.x loader would ignore any version symbols, so linking against `__aeabi_memclr8@@LIBC_N` should work as well as `__aeabi_memclr8`.

Can you provide the output from: `readelf -d libtwampc.so` ?

**Comment by Yaakushi** [comment]
```
$ readelf -d libtwampc.so
Dynamic section at offset 0x6f60 contains 15 entries:
  Tag        Type                         Name/Value
 0x00000003 (PLTGOT)                     0x8018
 0x00000002 (PLTRELSZ)                   600 (bytes)
 0x00000017 (JMPREL)                     0xec8
 0x00000014 (PLTREL)                     REL
 0x00000011 (REL)                        0xe20
 0x00000012 (RELSZ)                      168 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   17
 0x00000006 (SYMTAB)                     0x114
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000005 (STRTAB)                     0x694
 0x0000000a (STRSZ)                      1301 (bytes)
 0x00000004 (HASH)                       0xbac
 0x00000001 (NEEDED)                     Shared library: [libjson-c.so]
 0x00000000 (NULL)                       0x0
```

`libjson-c.so` is the dependency library that seems to be working fine.

**Comment by rprichard** [comment]
The `libtwampc.so` library has no `(NEEDED)` dependency on `libc.so`. If `libjson-c.so` has a dependency on `libc.so`, then loading `libtwampc.so` should be able to get the libc symbols transitively, but IIRC older Android loaders didn't work that way.

Ordinarily, when the Clang compiler drivers (`toolchains/llvm/prebuilt/$HOST_TAG/bin/*clang*`) produce a shared object, they automatically link the new library against `libc.so`. Apparently that's not happening here.

Maybe this line is involved? It's in [the NDK guide](https://developer.android.com/ndk/guides/other_build_systems#autoconf) and I saw it used above:
```
export LD=$TOOLCHAIN/bin/aarch64-linux-android-ld
```
If a build system invoked ld directly rather than through the driver, maybe that would explain the behavior? (I would guess that autoconf-based project normally wouldn't need to invoke ld directly?)

Maybe you could try leaving `LD` unset, or try setting it to the same value as `CC` or `CXX`. If it works, we should see a `libc.so` line with `readelf -d libtwampc.so | grep NEEDED`.

I'm also wondering if these CPPFLAGS are needed:
```
-DANDROID_PLATFORM=android-16 -DAPP_PLATFORM=android-16 -D__ANDROID_API__=16
```
IIRC the clang driver will automatically set `__ANDROID_API__` using the value of `--target`. (The driver wrappers like `armv7a-linux-androideabi16-clang` are shell scripts that pass a `--target` option.)

Aside: When it invokes ld, the clang driver also automatically prepends `crtbegin_so.o` before other input object files and appends `crtend_so.o` after all the inputs. These files are responsible for a handful of things, like destructing C++ objects on dlclose and providing the `.note.android.ident` section (see `crtbrand.S`). https://osscs.corp.google.com/android/platform/superproject/+/master:bionic/libc/arch-common/bionic/

**Comment by Yaakushi** [comment]
Oh, wow, that's really interesting! I would've never thought about a library not linking against libc because one of its dependencies already did it.

After unsetting `LD` in my envinroment, I have successfully compiled a version of `libtwampc.so` with a `(NEEDED)` dependency on `lib.c`:

```
$ readelf -d libtwampc.so
[...]
0x00000004 (HASH)                       0xdb4
0x00000001 (NEEDED)                     Shared library: [libjson-c.so]
0x00000001 (NEEDED)                     Shared library: [libdl.so]    
0x00000001 (NEEDED)                     Shared library: [libc.so]     
0x0000001a (FINI_ARRAY)                 0x7d68
[...]
```

The new version of `libtwampc.so` also has a proper `.note.android.ident` section, and, more importantly, my test devices running Android 4.x seems to be able to load it just fine! :) I'm not using the flags mentioned above anymore, and, honestly, I just added them after I went through a few similar issues where people wrote that adding such flags solved their problem, even if they did nothing in my case.

**Comment by DanAlbert** [comment]
Good catch, @rprichard!

@Yaakushi, I think if you ever *do* need to set `LD`, you want to set it the same way you set `CC` or `CXX` (use clang++ for C++ projects, but clang is fine for C projects; the only difference is whether or not libc++ is linked).

**Comment by DanAlbert** [comment]
> @Yaakushi, I think if you ever do need to set LD, you want to set it the same way you set CC or CXX (use clang++ for C++ projects, but clang is fine for C projects; the only difference is whether or not libc++ is linked).

Actually, thinking about this a bit more, I think the fault here lies with the build script that's using `LD`. Would need to see how it's used to know for sure, but I would expect the build script to use `CC` or `CXX` when linking as appropriate on its own and only use `LD` when it really does need the linker. I'm not sure though.
