### ISSUE TITLE
[question] How do I install a specific version of the NDK / how do I check what library in my project is requiring it?

### ISSUE THREAD

**Issue by danielesegato** [android/ndk#1190]
I need to work on a project I didn't touch before.

I can't even produce an APK because when I try to assemble I get:

```
> Task :app:stripDevDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripDevDebugDebugSymbols'.
> No version of NDK matched the requested version 21.0.5935234. Versions available locally: 16.1.4479499, 17.2.4988734, 18.1.5063045, 19.0.5106443, 19.2.5345600, 20.0.5392854, 20.0.5471264, 20.0.5594570, 20.1.5948944, 21.0.6011959, 21.0.6113669, 21.0.6113669
```

Android Studio 4.0 Canary 9
Build #AI-193.5233.102.40.6137316, built on January 15, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: 

OS: Ubuntu 19.10

I've installed all the non-obsolete NDK that show up in the SDK Tools tab in Android Studio, and the version `21.0.5935234` which apparently is needed by something in that project, is not showing up as an install option even if i show obsoletes.

Is there a way to install that specific version on my system or is there a way to find out what is causing it to be needed?

I've a great deal of experience with Android Development, but not so much with the NDK.

using the `--debug` option with gradle I can see more:
```
2020-02-14T12:37:32.936+0100 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] android.ndkVersion from module build.gradle is not set
2020-02-14T12:37:32.936+0100 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] ndk.dir in local.properties is not set
2020-02-14T12:37:32.936+0100 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] ANDROID_NDK_HOME environment variable is not set
2020-02-14T12:37:32.936+0100 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] sdkFolder is /home/$myusername/usr/android/sdk
2020-02-14T12:37:32.936+0100 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] Because no explicit NDK was requested, the default version '21.0.5935234' for this Android Gradle Plugin will be used
```

Looks like NDK is not correctly setup in my system and for that reason is using a not released version of the NDK?
doesn't seem like a reasonable fallback to me or am I missing something?

**Comment by enh-google** [comment]
21.0.5935234 seems to be r21-beta1, so my recommendation would be to bump that to the actual released version of r21 instead.

see https://developer.android.com/studio/projects/install-ndk#apply-specific-version for what to search for and change.

**Comment by DanAlbert** [comment]
> Looks like NDK is not correctly setup in my system and for that reason is using a not released version of the NDK?

r21 beta 1 was mistakenly built as r21 stable, so the two ended up with the same package name, and therefore the same download link. We had to unpublish r21 beta 1 from the SDK to publish r21 stable, which means the SDK manager no longer knows about it.

Unfortunately it's the default version of the NDK used for canary 9 which makes this particularly painful. You can work around it for now by explicitly setting `android.ndkVersion` to r21 like @enh-google advises. The next release of 4.0 should have the fix (and should be out in the next couple weeks, I believe).
