### ISSUE TITLE
Outdated CMake Version 3.10.2

### ISSUE THREAD

**Issue by Gibson85** [android/ndk#1191]
Hi, I am facing the next problem. The shipped CMake Version of Android Studio will become 2 years old in a few days. Thats at least for me a big show stopper. Are there any plans to updated CMake in the near future?

**Comment by H-G-Hristov** [comment]
The usual answer is: This is a Studio issue and you should report it there. You can actually use an external CMake in Kotlin DSL speak it looks like:

```
externalNativeBuild {
        cmake {
            // Tells Gradle to put outputs from external native
            // builds in the path specified below.
            setBuildStagingDirectory("${rootProject.extra["nativeStagingDirectory"]}/${project.name}")

            // Tells Gradle to find the root CMake build script in the same
            // directory as the module's build.gradle.kts.kts file. Gradle requires this
            // build script to add your CMake project as a build dependency and
            // pull your native sources into your Android project.
            setPath("${rootProject.extra["appProjectDirectory"]}/CMakeLists.txt")
            setVersion(Versions.cmake)
        }
    }

```

**Comment by DanAlbert** [comment]
@H-G-Hristov is correct. We have no control over this. File a Studio bug and we can get it in front of the right people for you. FWIW, I think this is currently being looked in to by that team.
