### ISSUE TITLE
NDKR21 Clang is introducing undefined reference to v-table;  but with NDKR16, its fine.

### ISSUE THREAD

**Issue by jvinodu** [android/ndk#1193]
#### Difference between NDKR16 and NDK21.  Code which is compiling and linking fine with NDKR16 is throwing linker error while linking(undefined reference to v-table of Class1) with NDKR21

NDKR21 is introducing an undefined reference to the v-table, while NDKR16 is not.
Also read README.txt in the attachment for further details
#### 
Host : Windows 10 64 bit.  NDK version R21 (21.0.6011959-beta2)
* ABI: x86_64
* NDK API level: 21
[](url)
[SkMakeFinalRepro_public.zip](https://github.com/android/ndk/files/4235898/SkMakeFinalRepro_public.zip)

**Comment by DanAlbert** [comment]
Did you find an answer?

**Comment by enh-google** [comment]
(i think they filed the more detailed bug https://github.com/android/ndk/issues/1194 instead, after investigating some more...)
