### ISSUE TITLE
[BUG] Compiler difference between NDK R21 and NDKR16

### ISSUE THREAD

**Issue by jvinodu** [android/ndk#1194]
#### Clang in NDKR21 is inserting an extra reference to v table when compared to that in NDKr16
Hi Team,

We have one CPP file in our project code which looks exactly similar to below code

```
////##############Test.cpp#############////
typedef unsigned long size_t;
typedef long ptrdiff_t;
#include<memory>
class Class1  {
public:
    virtual ~Class1();
};

class Class2 {
public:
	Class2()  {}
};

class Class3 final : public Class1 {
public:
    virtual void Function1(const int& deviceRgn, int);
private:
    std::unique_ptr<int> Variable1;
};



class Class4  {
public:
    Class4();
   ~Class4();

private:
        std::unique_ptr<Class3> Variable2;
	Class2 Variable3;
};

Class4::Class4() {}
////##############Test.cpp - End#############////
```

Our current build system is using NDK R16 and the above code works without any issues.

But if we are compiling the same code with NDK R21, we are running into undefined reference
to vtable error for Class3.

After spending some time investigating the header files, we could not understand what the issue is actually. Then we wanted to narrow down by first checking whether it is compiler issue or not. In order to figure this out, we first redirected the memory header file to preprocessedmemory.h

`androidndk16\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe @flags.rsp -std=c++1z -E  genpreprocess.cpp -o preprocessedmemory.h`

where our genpreprocess.cpp just includes memory header file.

Now our test.cpp file looks like below
```
#include<preprocessedmemory.h>
//rest of the code as shown above
```

Now when we generate object code for this test.cpp as below using old clang, we are not seeing any reference to vtable of Class3
`androidndk16\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe @flags.rsp -std=c++1z -c test.cpp -o test.obj & ndroidndk16\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-nm.exe --demangle test.obj | grep vtable`

But when we generate object code for this test.cpp as below using new clang, we are not seeing reference to vtable of Class3 
`androidndk21\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe @flags.rsp -std=c++1z -c test.cpp -o test.obj & ndroidndk16\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-nm.exe --demangle test.obj | grep vtable`

**Output>>U vtable for SkRecorder**

Please find all these files in below zip file

[SkMakeFinalRepro_to_public_3.zip](https://github.com/android/ndk/files/4244733/SkMakeFinalRepro_to_public_3.zip)

Could you please help us understand what has changed? between these two clang versions(5.0.3 and 9.0.8). Is this change done consciously? If so, please provide us with the references to understand those concepts.

#### Environment Details #######
* NDK Version: R16 & R21
* Host OS: Windows 10
* ABI: x86, x86_64

**Comment by pendyalasyam** [comment]
@DanAlbert , could you please help look into this issue.

**Comment by DanAlbert** [comment]
I'll look when I have the time.

**Comment by DanAlbert** [comment]
@stephenhines can check me on this, but I think this behavior is expected.

https://itanium-cxx-abi.github.io/cxx-abi/abi.html#vague-vtable

> The virtual table for a class is emitted in the same object containing the definition of its key function, i.e. the first non-pure virtual function that is not inline at the point of class definition.

You're not getting a vtable defined for `Class3` because `Class3` has no definition for its key function, `Class3::Function1`. If you add a definition for `Class3::Function1`, you get the following:

```
~/src/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ @flags.rsp -std=c++1z -c test.cpp -o test.o && readelf -sW test.o | c++filt  | grep vtable
    27: 0000000000000000    40 OBJECT  GLOBAL DEFAULT   18 vtable for Class3
    28: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND vtable for __cxxabiv1::__si_class_type_info
```

The new undefined reference is satisfied by libc++.

The behavior prior to r21 appears to be a bug. It's possible that the references to the vtable were somehow being pruned and that's what was causing it to work before, but it doesn't appear that the r21 behavior is wrong.

**Comment by pendyalasyam** [comment]
Got it..
Could you please clarify me on this?
When we are removing "final" `Class3 `definition, no reference to vtable is being triggered in the generated output code. Could you please help us understand why?

**Comment by DanAlbert** [comment]
I would guess that `Class3` being final allows the compiler to devirtualize the class.
