### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2bitProgammer** [android/ndk#1204]
#### Description

The `build/cmake/android.toolchain.cmake file `(line 448) creates a list of the `ANDROID_COMPILER_FLAGS`. As part of the list, the `-g` flag is passed.  `ANDROID_COMPILER_FLAGS` is then used to create the `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` (lines 618/619).   I believe the `-g` should only be set in the `ANDROID_COMPILER_FLAGS_DEBUG`. 

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: At least 20+
* Build system: CMake
* Host OS: Doesn't matter
* ABI:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
Android's debugging story is a little different from most. We _always_ build code with debug info and strip the binaries that are included in the APK. This lets you use the debug info in your build directory even on release builds.

CMake actually has a good mode for this: RelWithDebInfo. Unfortunately Studio doesn't use that (at least last I checked), so we can't change it in the NDK until Studio changes that, plus however long we want to support extant Gradle versions.

Is this causing any issues?

**Comment by 2bitProgammer** [comment]
I don't know that it's causing issues other than the fact that it's
producing non-standard/unexpected results - i.e. when I built my Release
version I was shocked at how large it was pre-stripping, only to find out
that it had been compiled with -g, which is exactly what RelWithDebInfo is
for.   To me it seems that like it should NOT be in the Release build, and
if for whatever reason you can't build with RelWithDebInfo (e.g. Studio),
then you should have to manually add that flag, as you are doing something
that is non-standard anyway.

**Comment by DanAlbert** [comment]
Studio is the norm for Android builds, so degrading those isn't something we can do. You should be stripping your release builds anyway.

**Comment by 2bitProgammer** [comment]
Agreed.

Do you know of a good way to strip the binaries in cmake and keep both
versions?  I created an add_custom_command to attach to the POST_BUILD of
the target, but that will do the strip in-place unless I use the -o flag.
I can do the -o flag fine, but I'm using a generator expression
$<TARGET_FILE:my_target> to get the filename, and you can't set OUTPUT or
BYPRODUCT with generators in the custom command.  I've hacked around this
by doing a cp command before the strip, but this has the
unfotrunate side-effect that doing a clean or install doesn't see the file
that I've copied.

**Comment by DanAlbert** [comment]
My understanding is that the normal way of getting stripped binaries out of CMake is to use the `install/strip` target. This way you get stripped binaries in the install directory and the originals in the build directory. I think you need to set up install rules for your outputs, but there might be defaults. It's not something I have a ton of experience with.

**Comment by DanAlbert** [comment]
Closing since I don't think there's anything we can do about this on our end. Please correct me if I've misunderstood :)
