### ISSUE TITLE
Converting strings to std::__ndk1 instead of std::__1 

### ISSUE THREAD

**Issue by AnchoretBaladev** [android/ndk#1208]
I'm compiling poco for android with NDK-r20b where the strings are converting to std::__ndk1 intead of std::__1. My android build aws server requires it to be built with std::__1. Is there any way if I can build it with std::__1.
Current Build is :-
0000000000000000 DF UND 0000000000000000 Poco::URI::URI(Poco::URI const&)
0000000000000000 DF UND 0000000000000000 Poco::URI::URI()
0000000000000000 DF UND 0000000000000000 Poco::URI::URI(std::__ndk1::basic_string<char, std::__ndk1::char_traits, std::__ndk1::allocator > const&)

**Expected Build:-**0000000000000000 DF UND 0000000000000000 Poco::URI::URI(Poco::URI const&)
0000000000000000 DF UND 0000000000000000 Poco::URI::URI()
0000000000000000 DF UND 0000000000000000 Poco::URI::URI(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&)

Can anyone please help if how can I achieve it?

**Comment by DanAlbert** [comment]
Whatever you have that's using `std::__1` is wrong (or perhaps very old, old enough that it has some nasty bugs and you shouldn't use it). The namespace is different to ensure that you can't link together incompatible libraries. The libraries with that namespace are not compatible with the NDK. Where are those libraries coming from?

**Comment by AnchoretBaladev** [comment]
I know that its wrong or old...But its required for now. Those libraries are by default being generated by my build system..and to match it i also need to generate same type with ndk. is there any flag or something by which i can generate the strings as std::__1.

**Comment by enh-google** [comment]
the whole point of this is to ensure that both sides match. so if one of your libraries is built by an older NDK, you need to make sure that the rest of your code is being built with a compatible NDK. the computer is helpfully telling you "you can't mix these two".

you either need to upgrade your NDK on the AWS build servers, or downgrade your local NDK. (they don't have to be the _exact_ same version, though that's usually the best idea!)

this is working as intended to help you catch this error early at build time rather than with strange bugs at runtime.

**Comment by DanAlbert** [comment]
Really don't downgrade though. You'd need to downgrade far enough that the libc++ you'd be using would not be reliable. If you have to downgrade that far, don't use libc++.

**Comment by AnchoretBaladev** [comment]
So you mean i need to change the libc++ flag in android.toolchain.cmake, is that so then what is the flag i should use?

**Comment by DanAlbert** [comment]
That won't help if you can't rebuild the incompatible libraries. You need to figure out where those are coming from and rebuild them with a newer NDK.

**Comment by AnchoretBaladev** [comment]
I dont have permissions to change those libs, I have to downgrade my poco libs while cross-compiling it for arm64-v8a. How can i make the NDK-r20b to use std::__1 instead of std::__ndk1? Or do i need to use any older NDK to achieve the same?

**Comment by enh-google** [comment]
correct. if you're putting together files built with two different NDK versions, and you can't change one of those NDK versions, you should change the other NDK version to match.

**Comment by DanAlbert** [comment]
Can you reach out to the vendor and get them to build the libraries with a newer NDK? Like I said, libc++ in the NDK was _not_ reliable back then, so you should be wary of using anything that requires it.

**Comment by jayhou** [comment]
> Can you reach out to the vendor and get them to build the libraries with a newer NDK? Like I said, libc++ in the NDK was _not_ reliable back then, so you should be wary of using anything that requires it.

I have the same problem ,  I need to use ndk build library in AOSP, but AOSP use std::__1, this cause the link error. And the ndk build library is huge and complex enough, It's build by ndk cmake toolchain,  I can't use AOSP build it.  How can I solve this kind of problem? Thanks very much!

**Comment by DanAlbert** [comment]
Libraries built with the NDK and code built for the platform are **not** compatible except via NDK APIs. You cannot have C++ interfaces between these because they do not have the same ABI for the C++ standard library (or necessarily even the language).

This is why there's a different namespace: to prevent you from accidentally building broken code.

**Comment by jayhou** [comment]
> Libraries built with the NDK and code built for the platform are **not** compatible except via NDK APIs. You cannot have C++ interfaces between these because they do not have the same ABI for the C++ standard library (or necessarily even the language).
> 
> This is why there's a different namespace: to prevent you from accidentally building broken code.

Got it ... thanks, it's seems I have to use the c interfaces.

**Comment by alexcohn** [comment]
> it's seems I have to use the c interfaces.

Or you can build your libraries with platform tools, which is very reasonable if you install them on specific devices.

**Comment by jayhou** [comment]
> > it's seems I have to use the c interfaces.
> 
> Or you can build your libraries with platform tools, which is very reasonable if you install them on specific devices.

thanks for your advise ,  but my libraries also depend on comercial .so files which built from ndk...

**Comment by alexcohn** [comment]
> thanks for your advise , but my libraries also depend on comercial .so files which built from ndk...

This should not prevent them to work when built as part of the platform

**Comment by haoXu1990** [comment]
Is there a solution to the problem?

**Comment by enh-google** [comment]
> Is there a solution to the problem?

yes --- build _all_ your code with the same version of the NDK[1].

anything else is _not_ guaranteed to work and is a bad idea.

if you have a binary dependency, ask the owners for a newer build. if they won't or can't, you should really consider whether you want your project to depend on something that won't or can't build on an NDK that's less than 5 years old...

strictly, there's another sensible alternative, and that's the one you see with Android's own NDK APIs: make all the interfaces _between_ libraries C, not C++. it doesn't matter what libc++ any library uses _internally_ as long as it's never exposed to another library.

____
1.  where, as alexcohn points out "NDK" can include "platform" for advanced users.

**Comment by DanAlbert** [comment]
It's not quite so bad as needing to build all your libraries with the exact same NDK, but they must use the same STL. Like @enh-google says, whatever library has the `__1` references needa to be rebuilt.

Locking the thread to make sure any new instances of this go through the new bug template so we get the info we need to help.

**Comment by DanAlbert** [comment]
One more thing: the code that references `__1` is either built with pre-NDK r11, or is built against the OS's libc++. In any case, they are not compatible.
