### ISSUE TITLE
Move ndk-build and CMake to llvm-ar

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1209]
Need to figure out what stopped us from doing this on Darwin and make the switch for r22.

**Comment by DanAlbert** [comment]
It seems the problem is that the automatic `--format=gnu` that is supposed to happen for ELF objects doesn't work when LTO is used. Using llvm-ar with LTO on Darwin requires an explicit `--format=gnu` or the build will fail later with:

```txt
libbar.a: error adding symbols: Archive has no index; run ranlib to add one
```

Note that ranlib is being run, and that part of the error is trying to be helpful and failing. The problem is that the archive is in Darwin format.

**Comment by DanAlbert** [comment]
@stephenhines @pirama-arumuga-nainar this sounds like it might just be a missing check in llvm-ar. iirc the IR that's in the LTO "object" includes the target, so it should be able to determine the correct format. Thoughts?

**Comment by pirama-arumuga-nainar** [comment]
We do the same for the [platform](https://cs.android.com/android/platform/superproject/+/master:build/soong/cc/builder.go;l=588) as well.

There's some logic in `llvm-ar` to [infer](https://github.com/llvm-mirror/llvm/blob/master/tools/llvm-ar/llvm-ar.cpp#L888) the format from the inputs.  We'd briefly looked at why this was not working but don't recall the details know.

**Comment by DanAlbert** [comment]
Confirmed that this is still an issue with llvm-ar from clang-r377782c.

**Comment by pirama-arumuga-nainar** [comment]
Aah, just looking at the earlier comments.  Yes, this'd be broken for FullLTO since we won't be able to [infer](https://github.com/llvm-mirror/llvm/blob/master/tools/llvm-ar/llvm-ar.cpp#L863) this from the file format.

I think we should infer the format from the triple.

**Comment by pirama-arumuga-nainar** [comment]
Committed as `fe5599eac6a57ad5a354e3b6fec9e97332304bac`.  I'll wait for the build failures over the weekend before cherry-picking it to AOSP in case I actually broke something on Darwin.

@DanAlbert Do you also want this in an r21 respin?  This is tagged for r22 currently.

**Comment by DanAlbert** [comment]
r22 only is fine. We're not using llvm-ar in r21. Thanks for checking :+1:
