### ISSUE TITLE
[DOC] SHA1 hash for Darwin r18b NDK download has changed and does not match what is listed on the website

### ISSUE THREAD

**Issue by jideshv** [android/ndk#1211]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
https://developer.android.com/ndk/downloads/older_releases

**Problem**
We are downloading: https://dl.google.com/android/repository/android-ndk-r18b-darwin-x86_64.zip 

However, when we verify this download we get a SHA1 of `be9fa7a95fa2cdd95eca59cb4d02148325b74874` instead of what is listed on the site as `98cb9909aa8c2dab32db188bbdc3ac6207e09440`. This seemed to have changed in the last 24 hours, we have been using this package before successfully.

**Comment by DanAlbert** [comment]
Thanks for the heads up. I'll pass this along and figure out who overwrote what.

**Comment by enh-google** [comment]
see also https://issuetracker.google.com/151859037.

**Comment by jideshv** [comment]
Thanks Dan for the follow up on this. This has now been fixed per the linked issue tracker item. I have also verified so closing this issue.

**Comment by DanAlbert** [comment]
Thanks again for reporting the issue!
