### ISSUE TITLE
[BUG] NDK 21.0 causes SEGV_MAPERR crash in app while 20.1 has no issues

### ISSUE THREAD

**Issue by peterdk** [android/ndk#1220]
#### Description
I am in no way a expert in C/C++, so reproducing a simple testcase will take some time. Anyway, I want to share my experience with some weird crashes in my app when switching to NDK 21.0 from NDK 20.1. 
I export audio using LAME but also using a very simple WAV exporter. Both have worked flawlessly on a huge number of devices (100.000+ installs).
I switched to NDK 21.0 from NDK 20.1. Now, whenever I run my exporter, be it LAME or my WAV exporter, it almost immediately crashes with: 
````
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x776b8b5da8 in tid 27872 (AsyncTask #2), pid 27678
````
Simply setting ndkVersion to 20.1 and recompiling, fixes the crash.

This is on a armv64 device.

I will try to get a solid testcase, but am wondering if this is due to a error in my code, or simply due to a compiler issue or so?

#### Environment Details
* NDK Version: 20.1.5948944, 21.0.6113669
* Build system: CMake
* Host OS: Windows 
* ABI: ARM64
* NDK API level: android-19
* Device API level: 28

**Comment by peterdk** [comment]
Never mind, I found 2 issues in my code, that somehow now got triggered. One was a char[4] strcpy of a 5 byte value string. And I updated LAME to the latest trunk version, which solved the crash there.

**Comment by DanAlbert** [comment]
Out of curiosity, did you get a fortify crash message for the first problem? Could be that you were previously getting away with writing past the end of the array but now you're getting the diagnostic for memory corruption.

**Comment by jmgao** [comment]
Doubt it, that would be a SIGABRT. It was probably something along the lines of stack layout changing and the byte after the char array changing from padding or some other trashable data to a pointer.

**Comment by peterdk** [comment]
I did found a message in logcat saying libc: memcpy 5 bytes into 4 byte array, or something similar. Is that what you mean?

**Comment by DanAlbert** [comment]
Yep, that's the one.
