### ISSUE TITLE
[question]It looks like NDK complier put snprintf() or memcpy() into my project. Where are they used? and How to control this ‘optimization’？

### ISSUE THREAD

**Issue by renren-github** [android/ndk#1221]
[NDK-r20c, NDK-build method]
My C project contains no memcpy() nor snprint().
Here is the .mk file I have:
First I use APP_STL := stlport_shared, the .so file was detected by the Auto scan tool  containing memcpy() function, whitch is considerred to be dangreous function in my company. Then I modify to APP_STL := c++_static, and the tool scans no memcpy but come out snprintf() instead, which is still a dangreous function.
I want to know which proocess the NDK build these functions  and how to control this process? Anyone help?

**Comment by enh-google** [comment]
stlport is no longer in the NDK. please upgrade to a current NDK.

**Comment by renren-github** [comment]
> stlport is no longer in the NDK. please upgrade to a current NDK.

Yes，actually I do changed the NDK from r15 to r20. Thus I have to change the APP_STL to c++static. Would you please tell me what the complier do to  the C project and how come the memecpy() and snprintf() function inserted to the final .SO file? Thanks a lot.

**Comment by enh-google** [comment]
since you haven't provided a reproducible test case, we can't say, but you can use objdump to see where the calls are coming from.

alternatively, you can get a rough idea from grepping the libc++ source in $NDK/sources/cxx-stl/.

**Comment by renren-github** [comment]
> since you haven't provided a reproducible test case, we can't say, but you can use objdump to see where the calls are coming from.
> 
> alternatively, you can get a rough idea from grepping the libc++ source in $NDK/sources/cxx-stl/.

Thanks. I've located the function snprintf. It seems not a local call?

$:aarch64-linux-android-addr2line -e E:\myso\obj\local\armeabi-v7a\libmylib.so 0000160c

/usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libunwind_llvm/src/AddressSpace.hpp:478

I have no idea where is this file and what the AddressSpace is used for in generating the so file.

**Comment by DanAlbert** [comment]
The stdlib uses these functions internally. They're necessary and not unsafe.
