### ISSUE TITLE
Timelines for NDK r21b release

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1222]
Hi Team,

Bug https://github.com/android/ndk/issues/1198 is a serious blocker for our project to upgrade to r21 and so we are waiting for the fix which is tagged for r21b now. Could you please let me know when can I expect the r21b release.

Thanks...

**Comment by DanAlbert** [comment]
Soon. We never know how long it'll take to get something through QA, but we're finalizing a build atm.

**Comment by DanAlbert** [comment]
Build 6352462 from https://ci.android.com/builds/branches/aosp-ndk-release-r21/grid? will be very close to the build we ship if it isn't *the* build that we ship. We're waiting a few days to see if https://github.com/android/ndk/issues/1060 can get fixed before we send anything to QA, but a rough estimate is probably within 2 weeks.

**Comment by pendyalasyam** [comment]
@DanAlbert, Thanks for the build link. We tested the 6352462 build and seems the problem is resolved.

**Comment by enh-google** [comment]
thanks for the feedback! we hope to get r21b through QA next week and ship the week after that.

**Comment by DanAlbert** [comment]
r21b has been handed off to QA, btw (same build as I shared here earlier)

**Comment by pendyalasyam** [comment]
@DanAlbert, Thanks...
We have been validating with the build but we can not go ahead with this build, until you release officially. So want to know when you will be releasing r21b officiallly?

**Comment by DanAlbert** [comment]
In ~12 hours. Got the go ahead from QA on Friday but shipping so close to the end of the week seemed like a bad idea :)

**Comment by pendyalasyam** [comment]
Thanks.... Eagerly waiting :)

**Comment by DanAlbert** [comment]
It's live now. I'm still pushing website updates but so far you can see it on https://github.com/android/ndk/wiki#current-lts-release. It's in the stable channel of the SDK as well.
