### ISSUE TITLE
[FR] Please add MediaCodec::setVideoScalingMode

### ISSUE THREAD

**Issue by peak3d** [android/ndk#1224]
**Is your feature request related to a problem? Please describe.**
Amazon FireTV devices resize the output surface on start of video playback from e.g. 10920x882 -> 1920x1080 and stretch the video so it fits into the surface. 

**Describe the solution you'd like**
We would like to call setVideoScalingMode(VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)

**Describe alternatives you've considered**
Don't do any action when INFO_OUTPUT_FORMAT_CHANGED is retrieved (dequeOutputBufer)
But this would lead tothe fact that we don't get intermediate streamchanges and have to analyze stream by ourself.

**Additional context**
The application is Kodi MediaPlayer

**Comment by enh-google** [comment]
this seems like you're actually writing OS code rather than an app? (MediaCodec::* is the internal C++ API. AMediaCodec_* is the public C API.)

either way, you'll want to report this over on https://source.android.com/setup/contribute/report-bugs in the media component.

**Comment by peak3d** [comment]
Kodi is an app, and we use NDK for the video playback.

https://developer.android.com/reference/android/media/MediaCodec#setVideoScalingMode(int)

Is the public JAVA API call for this, but there is no such a function in AMediaCodec (NDK)

**Comment by enh-google** [comment]
like i said, you'll want to file API requests in the android bug tracker. the NDK just delivers what the OS exports.

**Comment by peak3d** [comment]
Not 100% sure if this is what you are searching for:
https://android.googlesource.com/platform/frameworks/base/+/ccbf84f/media/jni/android_media_MediaCodec.cpp

It may be the JNI bridge, but native_window_set_scaling_mode(surface, mode); should be also accessible by NDK, or do I misread things?
