### ISSUE TITLE
[question] Will you update cmake and ninja?

### ISSUE THREAD

**Issue by andreya108** [android/ndk#1226]
Now current available cmake version for ndk is 3.10 while 3.17 is already released.
Bundled ninja version is 1.8.2 while 1.10.0 is already available.
Will you update cmake and ninja?

**Comment by DanAlbert** [comment]
Yes, a team is working on updating CMake. I don't think there are any plans to update Ninja. It's not something this team ships though, so file a Studio bug if you want updates on it.

Filing the Studio bug also lets that team know that updating CMake is important to users. A large number of users complaining on their bug tracker will be much more effective bthat me complaining indirectly :)

**Comment by andreya108** [comment]
I see, I will definitely follow your instructions.

But that's strange about ninja since it is bundled with studio's cmake
(reside in cmake bin directory).

пн, 6 апр. 2020 г., 21:49 Dan Albert <notifications@github.com>:

**Comment by DanAlbert** [comment]
It's definitely possible that updating Ninja is part of the plan and I just haven't heard about it :)

Are there new Ninja features/bug fixes you're looking for, or just generally wanting up to date tools? I agree with you either way, just curious.

**Comment by andreya108** [comment]
Sometimes on our CI ninja is failing build restarting constantly 100 times.
But I'm not sure this is ninja issue, or wether it fixed in new version.

But one thing I noticed when reading ninja changelog is c++ modules support
in 1.10.
Possibly, it can be useful for everyone who uses latest clang features
available in NDK):

https://groups.google.com/forum/m/#!msg/ninja-build/piOltAhywFA/zPfkrTtRCwAJ

вт, 7 апр. 2020 г., 0:05 Dan Albert <notifications@github.com>:

**Comment by DanAlbert** [comment]
Thanks for the link. I'll have to read through that tomorrow. I'm not sure what part Ninja would need to play in modules, so that's interesting. You'll need support from CMake and ndk-build as well, btw. I don't know about CMake, but it's not something we have planned for ndk-build (strictly speaking it is on the roadmap, but there's no expected timeline).

**Comment by pete-woods** [comment]
Where would I go about filing an Android studio bug for this issue? Upgrading to ninja 1.10 will fix parallel build issues inside Docker containers (1.10 includes a fix to correctly read the number of CPU cores available to the Docker container)

**Comment by enh-google** [comment]
https://developer.android.com/studio/report-bugs

**Comment by pete-woods** [comment]
Thanks! 🙏
