### ISSUE TITLE
[FR] switch from libgcc to libclang_rt

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1231]
Once https://github.com/android/ndk/issues/1230 is fixed we can move Android toolchains from libgcc to libclang_rt to avoid issues like https://github.com/android/ndk/issues/1202.

**Comment by DanAlbert** [comment]
@rprichard all done, right?

**Comment by rprichard** [comment]
Yes, the NDK is entirely switched over from libgcc to libunwind and libclang_rt.builtins. I suppose I just forgot to close this issue.
