### ISSUE TITLE
Why Android NDK Doesn't allow Internal Referencing Between C/C++ & Java Code like Android Cmake?[BUG]

### ISSUE THREAD

**Issue by mail2chromium** [android/ndk#1233]
I am using Android NDK to build shared libraries since last year. I am very curious why Android NDK doesn't allow Internal referencing with Java and JNI folders such as:

- Java and C/C++ Code
- Internal C/C++ Linkage Referencing 

by just clicking **CTRL + ClICK**. As you can see here

**Cmake Referencing:**

![javatoc++](https://user-images.githubusercontent.com/42235538/79116035-d8936880-7da0-11ea-8a3f-2faaac7760de.gif)

**NDK Referencing:**

![referncing](https://user-images.githubusercontent.com/42235538/79116292-7c7d1400-7da1-11ea-935f-fb587de0e7fb.gif)

Is there any flag, I am missing or we are not allowed to do referencing between the Code. Java Code Referencing is very fine using **CTRL + CLICK**.

**Additional Information:**

- OS-Name Microsoft Windows 10 Pro
- Android Studio 3.6.2
- NDK-Verison android-ndk-r13b (I have also tried android-ndk-r20b)

**Comment by enh-google** [comment]
that's a Studio question, not an NDK one. file Studio bugs here: https://developer.android.com/studio/report-bugs
