### ISSUE TITLE
Fatal error: ( file not found ) Android-NDK

### ISSUE THREAD

**Issue by mail2chromium** [android/ndk#1234]
I am trying to compile WebRTC Native Stack for VoiceEngine. I have fetched the complete WebRTC Native Stack from [chromium][1] and placed it into *JNI-Directory* of the Android Project. 

----------

**System Information:**

- OS-Name Microsoft Windows 10 Pro
- Android Studio 3.6.2
- NDK-Verison `android-ndk-r13b` (I have also tried `android-ndk-r20b`)
- [WebRTC-Native Stack][5] 

----------

**JNI-Directory Files:**

- webrtc
- Android.mk
- Application.mk
- org_webrtc_voiceengine.cc
- org_webrtc_voiceengine.h

----------

**Android.mk**

    LOCAL_PATH 		:= $(call my-dir)
    include $(CLEAR_VARS)
    
    ########################################
       ######  Important Flags  ########
    ########################################
    
    LOCAL_CFLAGS 	:= -w
    LOCAL_CFLAGS 	+= -O0
    LOCAL_LDLIBS 	+= -llog
    LOCAL_CFLAGS   	+= -Wall
    LOCAL_LDLIBS 	+= -landroid
    LOCAL_CPPFLAGS 	+= -std=c++14
    LOCAL_CFLAGS   	+= -DWEBRTC_POSIX
    LOCAL_CFLAGS   	+= -DWEBRTC_ANDROID
    LOCAL_CPPFLAGS 	+= -stdlib=libstdc++
    LOCAL_LDLIBS   	+= -lOpenSLES -llog
    LOCAL_PRELINK_MODULE 	:= false
    
    ########################################
    
    LOCAL_SRC_FILES := org_webrtc_voiceengine.cc
    
    include $(LOCAL_PATH)/webrtc/voice_engine/Android.mk
    include $(CLEAR_VARS)
    
    LOCAL_MODULE    := libwebrtc-voice
    LOCAL_STATIC_LIBRARIES := lib_voice
    
    include $(BUILD_SHARED_LIBRARY)

I am including an *Android.mk* such as `$(LOCAL_PATH)/webrtc/voice_engine/Android.mk` is same as given here: [google-git-webrtc-module-voice-engine][2] and here are related [source-files][3].

----------

**Application.mk**

    APP_ABI :=  all
    
    APP_STL := c++_static
    #APP_STL:=gnustl_static
    
    APP_PLATFORM := android-16
    
    STLPORT_FORCE_REBUILD := true
    NDK_TOOLCHAIN_VERSION := clang
    
    APP_CPPFLAGS := -fexceptions -fno-stack-protector -latomic
    APP_CPPFLAGS += -std=c++14 -stdlib=libstdc++ -Wno-return-type

----------

**NDK-BUILD**

By using the command `ndk-build clean & ndk-build`, I have tried to compile native-stack such as:

[![NDK-Building][4]][4]

----------

**Error:**

    fatal error: 'webrtc/modules/interface/module_common_types.h' file not found

This is happening almost for every related header files in the WebRTC Native Stack. What I have tried is, including the full path of this file such as:

    #include "F:/Webrtc/VoiceEngine/app/src/main/jni/webrtc/modules/interface/module_common_types.h"

This worked. But if I do this, the same error happens for some other header file in the same native stack. The other big problem with using this `Fully Specified Path` is that *WebRTC Native Stack* becomes a burden. As then, there would be a lot of hierarchal linkage disorder between native classes.   

One other thing which I can do is that I can put all the related stuff of *voice engine native stack* into the same directory, which again will disturb all the linkage between WebRTC Native Stack and, indeed a messy development technique.

- Is there any way to figure out where is the exact issue?
- How can I fix this without changing WebRTC Native Stack linkage?

----------

  [1]: https://webrtc.googlesource.com/src/+/refs/heads/master
  [2]: https://chromium.googlesource.com/external/webrtc/stable/src/+/19aeff6e9e23ba73cc8d7a4eea36c59a9c468013/voice_engine/main/source/Android.mk
  [3]: https://chromium.googlesource.com/external/webrtc/stable/src/+/19aeff6e9e23ba73cc8d7a4eea36c59a9c468013/voice_engine/main/source/
  [4]: https://i.stack.imgur.com/8rPOr.gif
  [5]: https://webrtc.googlesource.com/src

**Comment by DanAlbert** [comment]
webrtc/voice_engine/Android.mk is an AOSP makefile, not an NDK makefile. It won't work with the NDK.

Also, _please_ don't make us wait through a gif to see your build output. It takes ages and it's not searchable. Just paste the log next time.
