### ISSUE TITLE
[BUG]couldn't use the standard libs in the cpp &  std:: experimenta::filesystem

### ISSUE THREAD

**Issue by hensonwells** [android/ndk#1236]
#### Issue Description：
1.A few common c++ standard header files couldn‘t find ，it would get lots of errors if I include the path which would contain the header files I have to use.
e.g. <io.h> <direct.h> <stdio.h> 
2. It also not allow to add a new namespace like that：
`namespace fs = std::experimental::filesystem;`
I want to use the filesystem to Traversal the path,any good idea to solve it？
Thanks.

#### Environment Details
* NDK Version: 21.0.6113669
* Build system: ndk-build
* Host OS: Windows
*  STL: c++_shared
*  ABI:all
* NDK API level:r21

**Comment by DanAlbert** [comment]
> 1.A few common c++ standard header files couldn‘t find ，it would get lots of errors if I include the path which would contain the header files I have to use.
e.g. <io.h> <direct.h> <stdio.h>

Need more info

> 2. It also not allow to add a new namespace like that：
namespace fs = std::experimental::filesystem;

https://github.com/android/ndk/issues/609

**Comment by enh-google** [comment]
(i'll note that `<io.h>` and `<direct.h>` are both *Windows* header files that are never available for Android anyway...)

**Comment by DanAlbert** [comment]
Closing until we get info on studio.h failing to be found.
