### ISSUE TITLE
[question] Can a calloc/malloc fail be salvageable?

### ISSUE THREAD

**Issue by afjoseph** [android/ndk#1238]
Hey. This is a silly question, perhaps, but I just wanna know if NDK's jemalloc would ever return malloc/calloc in a way that one can exit gracefully from.

So, if there is a state change and a page fault occurs, is there even a salvageable way that a developer would return?

Many thanks

P.S: It seems that I am mixing "malloc/calloc fails" and "malloc/calloc return 0" together. Please do let me know if this mixture is healthy as well.

**Comment by enh-google** [comment]
TL;DR: yes

the malloc family return nullptr and set errno to ENOMEM on failure to allocate. the C++ new family throw on failure to allocate, which will end up in std::terminate if you don't catch or use the nothrow variants.

**Comment by DanAlbert** [comment]
As far as "can exit gracefully from" large allocations can fail even when there's plenty of memory left for other things.
