### ISSUE TITLE
[BUG] network drive issues for clang with r21

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1239]
Mirroring https://issuetracker.google.com/148483368 so we can include it in our milestone.

Seems that r21's Clang regressed file path behavior when the working directory is a network drive. Stil being confirmed, but https://reviews.llvm.org/D67166 looks like the fix.

**Comment by dadude999** [comment]
Thanks @DanAlbert! I had noticed this as well and was going to file a ticket, but I see that's been taken care of. This will be very helpful for those of us working on Mac with Windows VMs (using Visual Studio's NDK integration to build). A shame that Visual Studio for Mac doesn't have the NDK integration.
