### ISSUE TITLE
[question] Accessing Android X Support Library from NDK developed library

### ISSUE THREAD

**Issue by Langohr23** [android/ndk#1242]
Hello,

I am currently developing a library in c++. I would like to use the Fingerprint/Biometric API in my library.

Now I found out about the Android X Library for Biometrics. Is it possible to ship this support library together with my c++ Application to clients? If not, could I implement a biometric prompt in C++ by myself while the clients code ist still java or e.g. Flutter? Does someone has expirience with linking android x support libraries in c++?

What would be the most secure/best way to use the Android Keystore in an C++ Library?

Thank you for your help :)

**Comment by DanAlbert** [comment]
There's no C++ API, so you'll need to use those APIs via JNI.

For distribution you can do one of two things:

1. Ship your library as a Java API that delegates its implementation to C++. This is sometimes better or sometimes worse depending on your use case, but this is definitely the only easy option right now.
2. Ship your C++ library as an AAR, for which there isn't much tooling for currently. https://android-developers.googleblog.com/2020/02/native-dependencies-in-android-studio-40.html describes the feature in general, but there's still no way to build these easily (should be in 4.1).
