### ISSUE TITLE
[question] Access Android Java Functions from C++

### ISSUE THREAD

**Issue by Langohr23** [android/ndk#1245]
Hello,

is it possible to access Android Java Methods (like the Biometric Prompt) directly from C++ by loading the JNI Environment? 

So can I do:
 jclass jniBiometricPrompt = env->FindClass("android/hardware/biometrics/BiometricPrompt");

Or do I always need to ship a JAR which I call from C++ and that calls the BiometricPrompt? (C++ -> over JNI -> Jar -> Android Biometric Prompt)

Thank you for your help!

**Comment by Falken42** [comment]
In general, yes.

However, Android JNI does not implement `DefineClass`, so you cannot create new Java classes with JNI in C++.  If you need to implement a listener or callback class (I assume you'll want to handle `BiometricPrompt.AuthenticationCallback` somehow), you'll still need to create and compile that class in Java, and use `FindClass` to access it from C++.

There's more info in the NDK JNI documentation: https://developer.android.com/training/articles/perf-jni

**Comment by enh-google** [comment]
yeah, this is exactly what JNI is for. that said, you may still find it easier to write most of the code in Java to minimize the amount of JNI you actually have to write.

**Comment by Langohr23** [comment]
So also the above mentioned callbacks are completely (without adding a jar) in C++ over jni possible?

**Comment by enh-google** [comment]
see @Falken42's detailed comment. "in general, yes, but for this specific API you'll probably need to write some Java ... and in general it's a lot less painful if you have some glue Java anyway".
