### ISSUE TITLE
[How to rebuild libc++ from source without build-cxx-stl.sh?]

### ISSUE THREAD

**Issue by hoodar** [android/ndk#1246]
Please include any context relevant to your question (NDK version, ABI, build system, etc).
There is a build-cxx-stl.sh in build/tools in old NDK packages. But it is gone in recent builds. How to rebuild libc++ from NDK package now? Thanks in advance!

**Comment by DanAlbert** [comment]
You have to build the NDK. https://android.googlesource.com/platform/ndk/+/master/docs/Building.md
