### ISSUE TITLE
[BUG] _Unwind_Resume got changed to LOCAL HIDDEN from GLOBAL DEFAULT

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1247]
Hi Team,

_Unwind_Resume is symbol got changed to LOCAL HIDDEN in NDK R21B while it is GLOBAL DEFAULT in NDK R21.

This is leading to dlopen open failed for some of our third party libraries which are built with old NDK.

Is this intentional? If so, can we understand the reason

**F:>"F:\nugetcache\ndkr21b\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-readelf.exe" -sW "F:\nugetcache\ndkr21b\sources\cxx-stl\llvm-libc++\libs\arm64-v8a\libc++_shared.so" | findstr -i unwind_res**
  4054: 00000000000b44dc   248 FUNC    LOCAL  DEFAULT   11 _Unwind_Resume_or_Rethrow
  4230: 00000000000b43e0   252 FUNC    LOCAL  DEFAULT   11 _Unwind_Resume

**F:>"F:\nugetcache\ndkr21\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-readelf.exe" -sW "F:\nugetcache\ndkr21\sources\cxx-stl\llvm-libc++\libs\arm64-v8a\libc++_shared.so" | findstr -i unwind_res**
  1930: 00000000000b5e40   252 FUNC    GLOBAL DEFAULT   11 _Unwind_Resume
  2201: 00000000000b5f3c   248 FUNC    GLOBAL DEFAULT   11 _Unwind_Resume_or_Rethrow
  5336: 00000000000b5f3c   248 FUNC    GLOBAL DEFAULT   11 _Unwind_Resume_or_Rethrow
  6310: 00000000000b5e40   252 FUNC    GLOBAL DEFAULT   11 _Unwind_Resume

#### Environment Details
* NDK Version: NDK R21B
* Build system: Custom
* Host OS: Windows

**Comment by DanAlbert** [comment]
Yes, it's intentional: https://github.com/android/ndk/wiki/Changelog-r21#r21b. This was a regression in r21.

> This is leading to dlopen open failed for some of our third party libraries which are built with old NDK.

Rebuild them and they'll get the fix.
