### ISSUE TITLE
use of undeclared identifier 'AHardwareBuffer_allocate'

### ISSUE THREAD

**Issue by shiv-u** [android/ndk#1249]
#### Description
I am getting the error <b>use of undeclared identifier 'AHardwareBuffer_allocate'</b> when I try to build the project. I am calling the function AHardwareBuffer_allocate in a c++ file and I also have included hardware_buffer_jni.h .  AHardwareBuffer_allocate(&usage, &inputNativeBuffer); this is the function call where usage is a AHardwareBuffer_Desc variable and inputNativeBuffer is a pointer to AHardwareBuffer.
#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 21.0.6113669
* Build system:  CMake
* Host OS: Ubuntu 18.04.3 LTS
* ABI: arm64-v8a
* NDK API level: 21

**Comment by tonilsz** [comment]
I have faced that problem just now with AHardwareBuffer_lock, testing with setting up min sdk version to 28 solve it, but you can't check in ndk build versión. At the moment I will ignore it because java part checks that it's not called when isn't min 28.

**Comment by DanAlbert** [comment]
`AHardware` buffer is not available in API level 21. Check the headers to see when it was added.

**Comment by shiv-u** [comment]
@DanAlbert  Our android api level is 28 and ndk api level is 21.

**Comment by DanAlbert** [comment]
I'm not sure what you mean by "NDK API level" and "Android API level". The only thing that matters here is the API level you're building for, which for everything related to the NDK is your `minSdkVersion`. If your `minSdkLevel` is less than 26, this API is not available at build time. You can conditionally use it on new devices via `dlopen`/`dlsym`.
