### ISSUE TITLE
ndk-stack can't symbolize crash generated by arm64-v8a .so

### ISSUE THREAD

**Issue by Piasy** [android/ndk#1251]
#### Description

Using `ndk-stack -sym <unstripped so dir> -dump <crash log>`, I can get the correct source file and line number if the crash log is generated by devices using armeabi-v7a .so libs, and use armeabi-v7a as unstripped so dir.

But if the crash log is generated by devices using arm64-v8a .so libs, when I use arm64-v8a as unstripped so dir, ndk-stack fail with: `XXX.so: File format not recognized`. If I use armeabi-v7a as unstripped so dir, ndk-stack won't fail, but the source file and line number is wrong, which is reasonable.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.2.4203891, 21.1.6352462 is the same
* Build system: CMake
* Host OS: Mac
* ABI: arm64-v8a and armeabi-v7a
* NDK API level: android-21 for arm64-v8a, android-16 for armeabi-v7a
* Device API level: 28, Google Pixel 2

**Comment by DanAlbert** [comment]
> XXX.so: File format not recognized

What does `readelf -dW XXX.so` say? It's a little odd that it fails with both r15 and r21, because @enh-google rewrote ndk-stack entirely recently...

**Comment by Piasy** [comment]
Hi @DanAlbert , thanks for your reply, here is the output:

```bash
Dynamic section at offset 0x8cfd0 contains 39 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libandroid.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libOpenSLES.so]
 0x0000000000000001 (NEEDED)             Shared library: [libAAAA.so]
 0x0000000000000001 (NEEDED)             Shared library: [libBBBB.so]
 0x0000000000000001 (NEEDED)             Shared library: [libCCCC.so]
 0x0000000000000001 (NEEDED)             Shared library: [libDDDD.so]
 0x0000000000000001 (NEEDED)             Shared library: [libEEEE.so]
 0x0000000000000001 (NEEDED)             Shared library: [libFFFF.so]
 0x0000000000000001 (NEEDED)             Shared library: [libGGGG.so]
 0x0000000000000001 (NEEDED)             Shared library: [libHHHH.so]
 0x0000000000000001 (NEEDED)             Shared library: [libJJJJ.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000000e (SONAME)             Library soname: [libXXXX.so]
 0x000000000000001a (FINI_ARRAY)         0x8d8b8
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x0000000000000004 (HASH)               0x228
 0x000000006ffffef5 (GNU_HASH)           0x2328
 0x0000000000000005 (STRTAB)             0xa338
 0x0000000000000006 (SYMTAB)             0x3e10
 0x000000000000000a (STRSZ)              49099 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x8e280
 0x0000000000000002 (PLTRELSZ)           15816 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x199c8
 0x0000000000000007 (RELA)               0x16bd8
 0x0000000000000008 (RELASZ)             11760 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x16b78
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x16304
 0x000000006ffffff9 (RELACOUNT)          67
 0x0000000000000000 (NULL)               0x0
```

BTW, I run this command in a Ubuntu docker container, and I obfuscated some libraries' name.

**Comment by cferris1000** [comment]
From your readelf, that shared library is 64 bit. Is the stack you are trying to unwind also 64 bit?

There is a test for ndk stack that uses a 64 bit shared library and it works, so I'm not sure what would cause this to fail.

**Comment by Piasy** [comment]
Hi @cferris1000 , thanks for your reply!

But what do you mean by "Is the stack you are trying to unwind also 64 bit"?

The crash stack trace is generated by a device using arm64-v8a .so library, not sure if that's what you ask.

**Comment by cferris1000** [comment]
I though there was a possibility that you were unwinding a 32 bit process (arm) using a 64 bit shared library (arm64/aarch64). As I menteiond, there is a test for using ndk stack with arm64 so there seems to be something unique about your case.

Can you include an example of the unwind data that is failing? If possible, also including the shared libary that is not getting line numbers properly. If you can't include the shared library, then the output of readelf -e could help to verify if information is missing from the shared libary.

**Comment by Piasy** [comment]
Okay, I'll create a simpler example project.

**Comment by Piasy** [comment]
Sorry man, it's my fault, I was still using `ndk-stack` from r15, when I run `ndk-stack` of r21, it works fine!

**Comment by Piasy** [comment]
Hi @cferris1000 , I have another problem, I prepared a simple reproduce project.

The test code is:

```cpp

static char* newPtr() {
    return new char[1];
}

static void resetPtr(char** ptr) {
    *ptr = nullptr;
}

static int usePtr(char* ptr) {
    int var = *ptr;
    var++;
    return var;
}

JNIEXPORT void JNICALL
Java_com_piasy_ndk_1stack_1repro_MainActivity_testJni(
        JNIEnv*, jclass) {
    char* ptr = newPtr();
    usePtr(ptr);
    resetPtr(&ptr);
    usePtr(ptr);
    resetPtr(nullptr);
    usePtr(ptr);
}
```

It should crash at the second call to `usePtr` due to null pointer dereference.

When I run debug build, both `armeabi-v7a` and `arm64-v8a` work as expected, I mean the crash log and symbolication. 

Here is the crash log: [debug-crash.txt](https://github.com/android/ndk/files/4613303/debug-crash.txt).

But when I run release build, both `armeabi-v7a` and `arm64-v8a`, at first, the crash message is strange, it's `signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x7532c7960c`, and the symbolication is the second call to `resetPtr`, yes of course the second call to `resetPtr` should crash too, but should also be a null pointer dereference, right?

Here is the crash log: [release-crash.txt](https://github.com/android/ndk/files/4613316/release-crash.txt).

And here is the project: [ndk-stack-repro.zip](https://github.com/android/ndk/files/4613321/ndk-stack-repro.zip).

Thanks!

**Comment by cferris1000** [comment]
I think the compiler optimized the code and pulled the resetPtr call above everything else.

If you compile with -O0 then I would expect you to see the backtrace you expect.

**Comment by Piasy** [comment]
okay, it seems reading address 0x0 won't crash in release mode, but writing address 0x0 will crash.

Thank you anyway, I've no question now.
