### ISSUE TITLE
[BUG] simpleperf incorrectly resolves symbol names in a loaded .ko kernel module

### ISSUE THREAD

**Issue by MT-Wizard** [android/ndk#1252]
--------------------------------------------------------------------------------

#### Description

After recording a profile that includes kernel traces, and have some work in a .ko module, report -g shows wrong symbols names in it

#### Environment Details

rvc-dev branch
coral device
incremental-fs.ko kernel module
recording a dd command reading a file from a mounted IncFS filesystem
When the IncFS filesystem built as a part of the kernel the symbols are correct; .ko mode shows symbols from .ko, but somehow mixed up

**Comment by yabinc** [comment]
Thanks for reporting the problem, I want to check below things:
1. Is incremental-fs.ko in one of the directories in GetModulesInUse() in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/environment.cpp#157?
2. Have you enabled kernel addrs before recording, by `echo 0 >/proc/sys/kernel/kptr_restrict`? Although simpleperf will try to do it before recording, I prefer to manually enable it to make sure it isn't the problem.
3. Do you run simpleperf with root user (via su cmd)? If not, I prefer to run as root to exclude permission issues.

And can you provide below files for debugging?
1. recorded perf.data
2. incremental-fs.ko
3. if not obvious, describe what symbols are mixed-up?

**Comment by MT-Wizard** [comment]
1. Yes, it's in the vendor modules dir
2. no, but the symbols show up pretty well. Probably simpleperf's try succeeds. Will enable it for the next runs
3. Yes, it's an -eng Android build with adbd running as root

I'll attach those as soon as I have a module-based incrementalfs.ko build. So far switched to a non-module to unblock profiling

**Comment by yabinc** [comment]
We fixed a kernel module symbolization issue in simpleperf, https://android-review.googlesource.com/c/platform/system/extras/+/1511230. It will be in ndk r23.
Please reopen the issue if it doesn't work.
