### ISSUE TITLE
[question] LOGD c++-style function instead of macro

### ISSUE THREAD

**Issue by Consti10** [android/ndk#1254]
How can I convert the c-style LOGD macro
`#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG_MDEBUG, __VA_ARGS__)`
That can be seen in almost every android project into a c++17 equivalent ?
This 
` template<class... Args>
    static void CPULOGD(const Args&... args) {
        __android_log_print(ANDROID_LOG_DEBUG, TAG,args...);
    }`
does not compile due to the 
_error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]_
warning:

**Comment by enh-google** [comment]
you could pull the format argument out explicitly? so CPULOGD takes an explicit `const char* fmt` so that the compiler can see when that is/isn't a constant.

**Comment by Consti10** [comment]
This solution is probably improvable but at least it compiles:
`static void CPULOGD(const char* fmt,...) {
        va_list argptr;
        va_start(argptr, fmt);
        __android_log_vprint(ANDROID_LOG_DEBUG, TAG,fmt,argptr);
        va_end(argptr);
    }`
not using a macro here has the advantage of hiding CPULOGD inside a namespace.

**Comment by enh-google** [comment]
that's basically how `__android_log_print` is implemented behind the scenes. fwiw, that's probably what i would have done.

(if you want to go "full C++" your obvious choices are something with `operator<<` like https://android.googlesource.com/platform/system/core/+/refs/heads/master/base/include/android-base/logging.h or -- something we're considering but haven't actually done yet -- using https://github.com/fmtlib/fmt.)

**Comment by Consti10** [comment]
Thanks for the interesting links.

**Comment by enh-google** [comment]
oh, one thing you should definitely do if you haven't already: copy & paste the `__attribute__((__format__ ...` stuff from the bionic headers to your new logging function so that the compiler can check your format string matches its arguments. basically, you want to add `__attribute__((__format__(printf, 1, 2)))` to yours.

**Comment by Consti10** [comment]
Thanks. I wrote a quick Medium article about this topic:
[Best way to log in android native code c++ style](https://medium.com/@geierconstantinabc/best-way-to-log-in-android-native-code-c-style-7461005610f6)

**Comment by enh-google** [comment]
probably worth mentioning the `uint8_t*` gotcha that seems to be the most common mistake Googlers make with that API --- they expect the equivalent of `%p` but get `%s`.

you might want to reset the iostream flags between each call too. 99% of folks forget to pair every `std::hex` with a matching `std::dec`, and then _everyone else's_ logging comes out wrong.

for me the second best thing about [what we on Android call] the Google-style logging, after the fact that you can [almost always] stop thinking about types, is that it's just one extra character to add `strerror(errno)` on the end. we use `LOG(...) << ...;` normally and `PLOG(...) << ...;` [as in perror(3)] for the latter. i'd definitely recommend that for any production version of this.
