### ISSUE TITLE
Without linking against the libc++ runtime, what am I missing out?

### ISSUE THREAD

**Issue by piggy181** [android/ndk#1256]
I thought including C++ runtime such as libc++ is a prerequisite to coding anything C++ in Android. But according to https://developer.android.com/ndk/guides/cpp-support#none, it's possible to build Android app without linking against c++ runtime. 

My question is: what is not included or what feature is missing out when a project is built without linking with a c++ runtime? In a project with lots of C++ code and exception handling, it still compiles fine  without "-DANDROID_STL=c++_shared"

**Comment by enh-google** [comment]
you're missing out on the the C++ *library* (known as STL, Standard Template Library, for historical reasons) --- `std::string` and `std::vector<T>` and so on.

if you just want the C++ *language* then `ANDROID_STL=none` is fine.

**Comment by piggy181** [comment]
std::string is there even without C++ runtime. Try using new application wizard in Android Studio to create an application with C++ support. The default *.cpp file uses std::string

**Comment by piggy181** [comment]
I've found the answer myself. Without specifying "ANDROID_STL", it's the same as using c++_static. To opt out, have to use ANDROID_STL=none which means application can't access any of the standard header.

**Comment by enh-google** [comment]
i've sent out a small documentation improvement internally (https://critique-ng.corp.google.com/cl/312168692) to make the ndk-build/CMake difference clearer.
