### ISSUE TITLE
How to link libandroid_runtime.so/libnativehelper.so for Android 10 ?

### ISSUE THREAD

**Issue by IHbib** [android/ndk#1268]
I apologize for opening this issue( #1186 ) but I'm interested into why the references didn't work due to educational purposes.

I looked into libnativehelper.so and it does indeed export all these unreferenced functions, so why didn't clang++ link it? Searching for the string "LIBNATIVEHELPER_1" inside libnativehelper.so doesn't bring any results, could this be the reason?

**Comment by DanAlbert** [comment]
I think that version script is only used to generate the vndk (or maybe apex) version of libnativehelper. Not sure, tbh.
