### ISSUE TITLE
[BUG] build on linux with code-coverage, run in windows

### ISSUE THREAD

**Issue by jingcb** [android/ndk#1269]
I built a dynamic library with c++ flags " -fprofile-arcs -ftest-coverage",  and use the library to build a aar file. what ever debug or release.

and i sent the aar to windows to use.

some errors has happened:
"__start___llvm_prf_cnts", "__start___llvm_prf_data", "__start___llvm_prf_names", "__start___llvm_prf_vnds", these symbols can not locate.

so i use "nm" to check these symbols.  they are all "d" type.

but  when i build the dynamic library on win as same, , the library donot have  these symbols. 
the library build with linux has many symbols what is start with "____llvm_profile".

i use " -fprofile-arcs -ftest-coverage" just for gcov.

* NDK Version: r20b  and r21
* Build system:  gradlew and CMake
* Host OS: Linux
* ABI:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
We don't have enough information. We need to know how you're building the library and how you're using it. Given the description, I'm guessing we need specifics and won't be able to provide any answers without a test case.

**Comment by jingcb** [comment]
> We don't have enough information. We need to know how you're building the library and how you're using it. Given the description, I'm guessing we need specifics and won't be able to provide any answers without a test case.

it just a common library.   i write cmake file to create it,  and and the cmake file to buid.gradle file. 
use gradlew to create aar.

i think , the important point is  why add " -fprofile-arcs -ftest-coverage" to cxx flags to  cmake file on linux, the library will have this symbols.   but i do all same on windows,  it will not.

the point is " -fprofile-arcs -ftest-coverage" has different effect 
on't have enough information. We need to know how you're building the library and how you're using it. Given the description, I'm guessing we need specifics and won't be able to provide any answers without a test case.

it just a common library.   i write cmake file to create it,  and and the cmake file to buid.gradle file. 
use gradlew to create aar.

i think , the important point is  why add " -fprofile-arcs -ftest-coverage" to cxx flags to  cmake file on linux, the library will have this symbols.   but i do all same on windows,  it will not.

the point is " -fprofile-arcs -ftest-coverage" has different effect between linux and win10.

**Comment by pirama-arumuga-nainar** [comment]
The flag also need to be passed to the linker - but I'm assuming you're doing that.

The issue sounds similar to #881 that was just closed - `__start___llvm_*` symbols are present but not available at link/load time.  This happens with the bfd linker, which is the default for arm64.  Can you try with `-fuse-ld=lld` or `-fuse-ld=gold`?

**Comment by jingcb** [comment]
it is worked!
