### ISSUE TITLE
[BUG] cannot locate ndk header files from header files

### ISSUE THREAD

**Issue by Moussawi90** [android/ndk#1273]
--------------------------------------------------------------------------------

#### Description

After upgrading to latest ndk (version: 21.2.6472646) the included header files in project header files give that header not found

Example: I have a source file (decoder.c) with its header file (decoder.h). In the header file I have `#include<stdio.h>` it give me error 'stdio.h' file not found. But when I add `#include<stdio.h>` to the source file (decoder.c) it doesn't give error

N.B.:

1. This issue appears after upgrading to last ndk i.e. before upgrading it works without any error
2. I upgraded ndk and firebase plugin (may you assume that firebase has effect)
3. When the code is working properly before upgrading I have in the header file (decoder.h) definitions for variables with types u_char, u_short .... And after upgrading, and giving that unknow type u_char since headers cannot be located, I tried to show hints, but the one hint that get attention is "Create new C++ class 'u_char'" so maybe there is conflict between c and c++ after upgrading

#### Environment Details

* NDK Version:  21.2.6472646
* Build system: CMake 3.10.2.4988404
* Host OS: Windows 10
* ABI: Default
* NDK API level: 29
* Device API level: 29 (emulator)

**Comment by DanAlbert** [comment]
We have loads of tests that show this isn't a problem. We need a repro case. Provide one and we'll reopen, but there's nothing we can do with the information we've been given.
