### ISSUE TITLE
Identical files should be replaced with symlinks

### ISSUE THREAD

**Issue by tanius** [android/ndk#1275]
#### Description

The Android NDK package contains many identical large files.

A lot of disk space can be saved by including only one version of the file and the others as symlinks. For file systems that do not support symlinks (like on Windows) that solution could not apply, but it can apply to Linux for example.

The current distribution format (ZIP, as [seen here](https://github.com/android/ndk/wiki#supported-downloads))) cannot represent symlinks. But since different distribution formats are used for different operating systems already ([DMG and ZIP](https://github.com/android/ndk/wiki#supported-downloads)), transitioning to `.tar.gz` for the Linux platform download seems not far fetched.

In Android NDK 21.1.6352462, a quick analysis with [fdupes](https://en.wikipedia.org/wiki/Fdupes) shows that **2.3 GiB of 3.9 GiB** are occupied by the duplicates of other files and could technically be saved by replacing the duplicates with symlinks:

```
$ cd /opt/android-sdk/ndk/21.1.6352462
$ fdupes --summarize -r .
4166 duplicate files (in 2838 sets), occupying 2364.0 megabytes
$ du -hs .
3,9G    .
```

Test case: the issue would be considered fixed if the space occupied by duplicates (as analysed above, for example) is a lot less. It does not have to be zero, but at least duplicates of library files could be symlinked, as is standard practice in Linux distributions (cf. `ls -l /usr/lib`). Since several of the included library files are large (>90 MiB), that would already help a lot.

#### Environment Details

* NDK Version: 21.1.6352462
* NDK installation source: using `sdkmanager`
* Host OS: Linux (Ubuntu 19.10 amd64)

**Comment by tanius** [comment]
(I guess I had better made this a feature request, since nothing is broken. Sorry about that. Can't edit the label now.)

**Comment by DanAlbert** [comment]
Yeah, I'd actually done this analysis myself recently. In the past we actually went through a lot of effort to avoid symlinks in the NDK because they were not supported by the SDK manager. We'd introduced a handful in r12 and the symlinks were installed as plain text files. Needless to say, things broke :) They are supported now though, so this is actually something that has made it back onto my todo list.

> The current distribution format (ZIP, as seen here)) cannot represent symlinks.

There's a supported-more-or-less-everywhere extension to zip for symlinks, so that shouldn't be a problem.

Incidentally, there is actually a bug open to investigate using different distribution formats for the SDK (brotli being the leading candidate), but that's a different team and I don't think the owner has had any time to investigate further yet. It wouldn't change the _installed_ size of the NDK, but it would reduce the download size significantly.

**Comment by DanAlbert** [comment]
Also worth mentioning that a lot of those dupes are actually just legacy things that will disappear soonish. Binutils is installed twice, for example, as is libc++ and a handful of other components. All that should be cleaned up in r23 or r24, but even after that there's a huge amount of dupes within a single toolchain.

**Comment by DanAlbert** [comment]
We've made _some_ progress on this for r23. Not sure we'll finish, but it's improving. Size is down a lot due to dropping binutils as well.

**Comment by DanAlbert** [comment]
Partially complete. Will continue working on it in r24.

**Comment by DanAlbert** [comment]
r24 had some more progress but there's still more to do. Moving forward.

**Comment by jfgoog** [comment]
Some things that jump out:

59882112 bytes each:
./android-ndk-r25-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
./android-ndk-r25-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/lld

2172904 bytes each:
./android-ndk-r25-canary/prebuilt/linux-x86_64/bin/python
./android-ndk-r25-canary/prebuilt/linux-x86_64/bin/python2.7
./android-ndk-r25-canary/prebuilt/linux-x86_64/bin/python2

Replacing these with symlinks would save 65M

A lot of stuff in sources/cxx-stl is duplicated in toolchains/llvm/prebuilt/linux-x86_64/sysroot. For example, 

10437274 bytes each:
./android-ndk-r25-canary/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a
./android-ndk-r25-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_static.a

**Comment by jfgoog** [comment]
Current figures, as of https://android-review.googlesource.com/c/platform/ndk/+/2051541:
```
Compressed size: 436.06M (213.24M less)
Uncompressed size: 1.34G (820M less)
Files: 6900
Symlinks: 27
634 duplicate files (in 412 sets), occupying 18.2 megabytes
```

I also looked at possible savings from better compression formats:
```
Uncompressed size, 1.43G
.zip, 457.57M
.tar.gz, 452.56M
.tar.bz2, 407.47M
.tar.br, 283.83M
.tar.xz, 236.36M
```

I filed a feature request with the Android Studio team to see what it would take to support a better compression format for the NDK.
