### ISSUE TITLE
Flashlight brightness in a changed world [FR]

### ISSUE THREAD

**Issue by irisonia** [android/ndk#1277]
Globally, it has become crucial to be able to monitor people's health remotely, using apps.
Since such apps require placing a finger over the flashlight+camera for a while,  programmable control over the flashlight brightness is now required. Please consider allowing it. Thanks!

**Comment by enh-google** [comment]
this bug tracker is for the NDK only. see https://source.android.com/setup/contribute/report-bugs for other places to report bugs/feature requests.
