### ISSUE TITLE
[BUG] clang crash when compiling C++ file

### ISSUE THREAD

**Issue by Ardy123** [android/ndk#1279]
Mac OSX 10.15.4
NDK version: 21.3.6528147

I cannot share the code of the c++ file but here is the clang strack trace that is generated from the crash when attempting to compile it...

1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/Users/afalls/code/niantic/narwhal-ian/nar/firstparty/6d-infinitam/LNTLib/Nodes/Implementation/CPU/Conv_Implementation_CPU.cpp'.
4.	Running pass 'ARM Instruction Selection' on function '@_ZN6LNTLib23Conv_Implementation_CPU16InnerProductSimdIN3vcl4neon6Vec32fEEEvPKfiS6_iPf'
0  clang++                  0x0000000106443f98 void std::__1::__call_once_proxy<std::__1::tuple<void (&)()> >(void*) + 452872
1  clang++                  0x0000000106442fd8 void std::__1::__call_once_proxy<std::__1::tuple<void (&)()> >(void*) + 448840
2  clang++                  0x00000001064445b9 void std::__1::__call_once_proxy<std::__1::tuple<void (&)()> >(void*) + 454441
3  libsystem_platform.dylib 0x00007fff6f59e5fd _sigtramp + 29
4  libsystem_platform.dylib 0x0000000000000004 _sigtramp + 18446603338648001060
5  clang++                  0x0000000105500c19
6  clang++                  0x0000000106e1ddd7 llvm::Pass* llvm::callDefaultCtor<llvm::RegBankSelect>() + 43751
7  clang++                  0x0000000106e1be05 llvm::Pass* llvm::callDefaultCtor<llvm::RegBankSelect>() + 35605
8  clang++                  0x0000000106fc58f0 llvm::Pass* llvm::callDefaultCtor<llvm::RegBankSelect>() + 1779200
9  clang++                  0x0000000106fc507a llvm::Pass* llvm::callDefaultCtor<llvm::RegBankSelect>() + 1777034
10 clang++                  0x0000000106fc2904 llvm::Pass* llvm::callDefaultCtor<llvm::RegBankSelect>() + 1766932
11 clang++                  0x00000001054afb74
12 clang++                  0x0000000105b983fd llvm::Pass* llvm::callDefaultCtor<llvm::MachineDominatorTree>() + 92477
13 clang++                  0x0000000105e626e1 llvm::SymbolTableListTraits<llvm::BasicBlock>::toPtr(llvm::ValueSymbolTable&) + 249473
14 clang++                  0x0000000105e629e3 llvm::SymbolTableListTraits<llvm::BasicBlock>::toPtr(llvm::ValueSymbolTable&) + 250243
15 clang++                  0x0000000105e62fd4 llvm::SymbolTableListTraits<llvm::BasicBlock>::toPtr(llvm::ValueSymbolTable&) + 251764
16 clang++                  0x00000001066141cb void llvm::DomTreeBuilder::Calculate<llvm::DominatorTreeBase<llvm::VPBlockBase, false> >(llvm::DominatorTreeBase<llvm::VPBlockBase, false>&) + 559739
17 clang++                  0x000000010685770a void llvm::DomTreeBuilder::Calculate<llvm::DominatorTreeBase<llvm::VPBlockBase, false> >(llvm::DominatorTreeBase<llvm::VPBlockBase, false>&) + 2932666
18 clang++                  0x00000001077a6763 llvm::RawInstrProfReader<unsigned long long>::getCounter(unsigned long long) const + 72083
19 clang++                  0x0000000106b1a44a llvm::Registry<clang::PluginASTAction>::begin() + 16218
20 clang++                  0x0000000106ab8c30 void llvm::DomTreeBuilder::Calculate<llvm::DominatorTreeBase<llvm::VPBlockBase, false> >(llvm::DominatorTreeBase<llvm::VPBlockBase, false>&) + 5428448
21 clang++                  0x0000000106b98044 llvm::Registry<clang::PluginASTAction>::begin() + 531284
22 clang++                  0x0000000105279259
23 clang++                  0x0000000105276fd9
24 libdyld.dylib            0x00007fff6f3a5cc9 start + 1
25 libdyld.dylib            0x00000000000000cf start + 18446603338650067975
clang++: error: unable to execute command: Illegal instruction: 4

**Comment by DanAlbert** [comment]
@stephenhines anything you can do without the source? I suspect not, but SIGILL is a little weird.

**Comment by pirama-arumuga-nainar** [comment]
@Ardy123 Can you post the failing command line?  Sometimes misconfiguring arm/aarch64 features and attributes show up as crashes since Clang cannot deduct the misconfiguration.

Another option is to use [creduce](https://embed.cs.utah.edu/creduce/) to find a reduced test case that can potentially be shared publicly.

**Comment by DanAlbert** [comment]
Happy to reopen if we get more info, but we can't do anything with what we have.
