### ISSUE TITLE
[question] creation apk with ndk and command line tools

### ISSUE THREAD

**Issue by lch32111** [android/ndk#1280]
NDK version : 20.0.5594570
ABI : arm64-v8a
build system : cmake  + ndk cmake toolchain + ninja + aapt2

I'm not sure this question is proper for this issue tracking. 
If it's not, I will delete this.

Hi I'm trying to creating a complete apk file, which can run in my android device.
My question is how I can link the main entry file into apk?

my creation process is like this
1. Create Manifest (NativeActivity)
2. Compile Resources with AAPT2
3. build project with cmake toolchain
4. Compile Native Source Codes(C/C++) with ninja
     - I got .so/.a files from here
     - and I guess that libnative_app_glue.a will be the main entry for the android application
5. Create APK file with AAPT2
6. Jar Sign
7. Zip Align

And When I'm in the process No.5, I'm trying to link the .so/.a files. But
I can't achieve what I think, which links .so/.a (native source libraries) to apk file.
And There is no document how to do it. (But I can find there is a method for this in AAPT (not AAPT2)

Can I get any help for this?

**Comment by DanAlbert** [comment]
APKs are just zip files. You don't need aapt to add native libraries to a zip file.

Anything more complicated than that and we don't really have the expertise to help though. Gradle makes APKs, not the NDK.

Honesty though, just use Gradle. There's no point reinventing this particular wheel.

**Comment by axzezdev** [comment]
I'm trying to do this same thing.  Can't get the aapt2 tool to include my .so.  I know we should use Gradle, but we build all of our target platforms using the same tools from the same code base and I have this working with aapt now.  I would just like to get it working with aapt2 if it is possible.  After I link with aapt2 I used zip to add the lib in manually, but this won't load on my phone, so it must be more than just including the .so in the right place in the apk.

**Comment by DanAlbert** [comment]
Same answer as before: you're talking to the wrong team.

**Comment by kerrhome** [comment]
Thanks @DanAlbert, would you be able to direct us to the right team that could help?  I would appreciate it.

**Comment by DanAlbert** [comment]
b.android.com

**Comment by enh-google** [comment]
(b.android.com is very hit-or-miss in terms of getting to the right people, so if you post back here with a link to the bug we can try to make sure it gets in front of the right people...)
