### ISSUE TITLE
[question] Integrating a 3rd party shared library within an AAR library

### ISSUE THREAD

**Issue by GEllickson-Hover** [android/ndk#1283]
I have read various documents and SO answers on choosing a static or shared C++ runtime, including [issue 796](https://github.com/android/ndk/issues/796), but I'm still a little confused as to how to integrate shared libraries into an AAR, for use in another project that also has other shared libraries.

Background:
- My project will need to produce an AAR library for use within a React-Native project
- This library will require integrating OpenCV, additional custom code in C++ which uses OpenCV, and a JNI layer, which exposes the actual usage of the library to the java consumer
- OpenCV 4.3.0 compiled their .so files for `libc++_shared`. I believe they also used NDK 18.
- OpenCV 4.1.0 and below were compiled with `libc++_static`, but I could pull from source and recompile the latest with libc++_static
- The react-native project I am integrating with already has a bunch of share libraries and I see that there is already a libc++_shared.so that gets bundled into to the apk.

Questions:
For my AAR library, should I use a version of OpenCV's shared libraries that are compiled for  libc++_static or libc++_shared if I also need to compile my own C++ code to interact with it? If shared, do I have to ensure I use the same ndk version as the  React-Native project since only one libc++_shared.so will be bundled in the final app APK?

I've tried both ways using CMake with the `-DANDROID_STL`arg and a very basic JNI call, and at a glance they seem to work in our React-Native project. Using shared, since only one libc++_shared.so gets bundled, I'm not sure the consequences of that as the version in the AAR was slightly smaller than the one I see in the final APK. However, if I take a version of OpenCV that was compiled with libc++_static, will I still be able to communicate safely via my own C++ code to OpenCV since my code will also need to be compiled into a .so with and use some C++ runtime as well?

Thank you and apologies for any poorly phrased portions. I am new to the NDK.

**Comment by DanAlbert** [comment]
The simplest answer to your question is that you should use libc++_shared, should use OpenCV's libraries using that as well, and that you don't need to worry about much else. Typically, that's going to be enough.

If you wanted to be _really_ defensive about it, you could build a version of your library per-NDK version. I do not know of any compatibility issues that would make this necessary (unless you're trying to support NDK r10, but just don't do that), so this is probably overkill. The exception would be if you're shipping an LTO'd static library, since that's probably very dependent on the exact version of LLVM used.

> However, if I take a version of OpenCV that was compiled with libc++_static, will I still be able to communicate safely via my own C++ code to OpenCV since my code will also need to be compiled into a .so with and use some C++ runtime as well?

Rule of thumb is that the only safe way to use libc++_static is when there is only a single shared library in the whole application. That's not wholly true, but it's close. https://android.googlesource.com/platform/ndk/+/master/docs/user/middleware_vendors.md explains in more detail.

**Comment by GEllickson-Hover** [comment]
@DanAlbert Awesome, thank you! I had been leaning that direction, but was first confused from the wording in the [C++ support section](https://developer.android.com/ndk/guides/cpp-support#shared_runtimes) that "JNI libraries distributed with Java AARs must not use the shared runtime to avoid conflicting with other libraries and the app." I think I broadly understand now what that message is intended for.

Also, I've seen many of your comments in here and SO as well, and you're very helpful, so thank you again for taking the time :)

**Comment by DanAlbert** [comment]
Happy to help :)

**Comment by maestroIgor** [comment]
Just to be sure, so it is quite safe to use in one app two native libraries when one is build with NDK 20... and another with NDK 21...?

**Comment by DanAlbert** [comment]
It's best to avoid if possible because we obviously can't test all the possible permutations of that, but it's often unavoidable so we do try to keep that configuration working.

**Comment by alexcohn** [comment]
> it is quite safe to use in one app two native libraries when one is build with NDK 20... and another with NDK 21...?

It's better than rebuilding *your* library with NDK r20 because the app includes a third-party lib that cannot be rebuilt with the latest NDK. Unfortunately, when you are forced to use a library that was built with, say, NDK r.15, the decision is much less trivial.
