### ISSUE TITLE
[question] Context for FragmentActivity/Biometric Manager

### ISSUE THREAD

**Issue by Langohr23** [android/ndk#1286]
We are currently working on an SDK/Library written in C++ that uses the Android Keystore/ Biometric Prompt. 

We try to write as many Code as possible in C++ and only the bare minimum in java. The communication between both is made via JNI-calls. 

To use the BiometricPrompt we need the Context of the application. To get the BiometricPrompt it looks more or less as this:

android.content.Context context;
BiometricManager biometricManager = BiometricManager.from(context);

In our C++ Code this AndroidContext is represented as a jObject. Is there any possibility to retrieve the AndroidContext in our C++ or pass the context as a String?

We would like to avoid to pass the AndroidContext as an object over JNI, as we have a JSON API to our C++ Code.

Summarized we would like to know if something like this is possibilities:
- Retrieve the AndroidContext without an JNI call from inside the C++-Code 
- Pass the AndroidContext over JNI as a string. How we imagine it:

Java : String strContext = hex_encode(context);
C++ :  reinterpret_cast<jobject>(hex_decode(strContext));
 
Thank you for you help!

**Comment by enh-google** [comment]
no, you'll need to pass it down.

**Comment by alexcohn** [comment]
Yes, you can retrieve a valid context in C++, but this will be the your Application object. See *[How to get the Android context instance when calling JNI method?](https://stackoverflow.com/a/46871051)* by Harlan Chen.
