### ISSUE TITLE
[question] Out of tree LLVM passes

### ISSUE THREAD

**Issue by tammela** [android/ndk#1287]
Hello,

I have been trying to integrate a sample out of tree LLVM pass to work with the Android build system and I have been running into a couple of issues.

Compiling and running it against the vanilla LLVM 9 distribution works fine.
```
$ clang -Xclang -load -Xclang hello.dylib test.c
Hello from out of tree pass!
```

Loading the same shared object against the NDK's pre-built clang yields this error.

```
error: unable to load plugin 'hello.dylib': 'dlopen(hello.dylib, 9): Symbol not found:
      __ZN4llvm10ModulePass17assignPassManagerERNS_7PMStackENS_15PassManagerTypeE
  Referenced from: hello.dylib
  Expected in: flat namespace
 in hello.dylib'
```

De-mangling the symbol, it seems that it's missing:
```
_llvm::ModulePass::assignPassManager(llvm::PMStack&, llvm::PassManagerType)
```

As a next step I forked Android's LLVM repository and checked it out to `98c855489587874b2a325e7a516b99d838599c6f`. Which is the hash reported in NDK `21.2.6472646`.  Built the LLVM libraries with plugin support and built the out of tree pass against it.

Loading the shared object against the NDK's pre-built clang yields the same error reported above.

Q: Is plugin/pass support available in the NDK's pre-built clang?

**Comment by stephenhines** [comment]
https://android-review.googlesource.com/c/toolchain/llvm_android/+/1349388 should resolve this in our future Mac builds. It turns out that Mac actually strips more symbols from executables, which breaks the way that LLVM plugins are supposed to work. This should restore all LLVM symbols for future builds.

**Comment by DanAlbert** [comment]
No test case provided so I can't verify, but the presumed fix is in r23.
