### ISSUE TITLE
[BUG] windows python prebuilt no longer has datetime module, breaking shaderc

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1291]
On Windows:

```
> python run_test.py --rebuild --filter shaderc_libcxx
...
FAIL shaderc_libcxx [x86-16-deprecated]: fcntl(): Bad file descriptor
"[x86] Generate enum<->string mapping <= grammar JSON files"
fcntl(): Bad file descriptor
"[x86] Vendor extended instruction set: debuginfo tables <= grammar"
fcntl(): Bad file descriptor
"[x86] Grammar (from unified1)  : instructions & operands <= grammar JSON files"
fcntl(): Bad file descriptor
"[x86] Grammar (from unified1)  : instructions & operands <= grammar JSON files"
fcntl(): Bad file descriptor
"[x86] Vendor extended instruction set: opencl.debuginfo.100 tables <= grammar"
fcntl(): Bad file descriptor
"[x86] Vendor extended instruction set: spv-amd-shader-trinary-minmax tables <= grammar"
fcntl(): Bad file descriptor
"[x86] Vendor extended instruction set: spv-amd-shader-explicit-vertex-parameter tables <= grammar"
fcntl(): Bad file descriptor
Traceback (most recent call last):
  File "C:/Users/Dan/Desktop/android-ndk-r22-canary/build//../sources/third_party/shaderc/third_party/spirv-tools/utils/update_build_version.py", line 32, in <module>
    import datetime
ImportError: No module named datetime
...
```

If I run the Python that's in the NDK's prebuilts directory and just try to `import datetime` it shows the same error. Seems we're missing that?

**Comment by hhb** [comment]
datetime module failed the build for windows:
build/temp.win32-2.7/src/ndk/toolchain/python/Python-2.7.5/Modules/datetimemodule.o:datetimemodule.c:(.text+0x84c3): undefined refer
ence to `gmtime'
build/temp.win32-2.7/src/ndk/toolchain/python/Python-2.7.5/Modules/datetimemodule.o:datetimemodule.c:(.text+0x85e6): undefined reference to `localtime'

Investigating...

**Comment by DanAlbert** [comment]
(I hate the the python build doesn't fail when it fails to build...)

**Comment by hhb** [comment]
Looks like this is a MinGW bug. gmtime / localtime is decorated with __forceinline so there's no symbol generated for them. But in datetimemodule.c they try to get the pointer to the functions.

This is fixed by [6988d73a95fbbd97a0bdbb517008cf18f4eb5f02](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/6988d73a95fbbd97a0bdbb517008cf18f4eb5f02/). Cherrypicked in [aosp/1350713](https://android-review.googlesource.com/c/toolchain/mingw/+/1350713)

**Comment by DanAlbert** [comment]
Thanks for the quick fix!

**Comment by hhb** [comment]
Let's leave this open until we have a new mingw prebuilts. (Just in case I forgot to upload it)

**Comment by DanAlbert** [comment]
Ah, sorry, forgot that was needed.

**Comment by stephenhines** [comment]
The patch actually broke the mingw build, so we probably need another fix before we get prebuilts.

**Comment by pirama-arumuga-nainar** [comment]
Haibo fixed the build with https://android-review.googlesource.com/c/toolchain/mingw/+/1351332.

**Comment by hhb** [comment]
And this is the prebuilts:
https://android-review.googlesource.com/c/platform/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/+/1351127

**Comment by DanAlbert** [comment]
I'm still (again?) seeing this.

**Comment by hhb** [comment]
Fixed. https://android-review.googlesource.com/c/platform/manifest/+/1441672
