### ISSUE TITLE
[question] Finding power consumption information from simpleperf.

### ISSUE THREAD

**Issue by jainilparikh** [android/ndk#1293]
Hi, 
I wanted to know if its possible to determine the power consumption by an application using simpleperf? If yes how?

Secondly whenever I try to run simpleperf stat -p 15555 -e  "specific trace event " --interval 1   the output of the tracepoint is always 0? My application is running while the above command runs.

My device runs on ARM cortex-73.

**Comment by DanAlbert** [comment]
Measuring power draw of any one program is more or less impossible to do accurately with any tool. There are just too many factors at play.

**Comment by yabinc** [comment]
Hi Jainilparikh,

Thanks for your question!

> I wanted to know if its possible to determine the power consumption by an application using simpleperf? If yes how?

Probably no. Simpleperf is a cpu profiler. It doesn't know things happen on screen or wifi. So I suggest checking https://developer.android.com/topic/performance/power/setup-battery-historian instead.

For a little possibility to help, simpleperf supports recording tracepoint events. And there may have some power related tracepoint events. But 1. It needs `adb root` to get info from tracepoint events through simpleperf. 2. I don't know how.
If you don't have a better choice and want to explore in this way, I can forward the info to android perf team and see if they
have any experience.

> Secondly whenever I try to run simpleperf stat -p 15555 -e "specific trace event " --interval 1 the output of the tracepoint is always 0? My application is running while the above command runs.

The biggest possibility is the event never happens while process 15555 is running on cpu. And the question has very limited
context, so I can't analyze more.

**Comment by jainilparikh** [comment]
Hi Yabinc,
I have root access to my device. I actually dont have another choice except simpleperf as I am collecting some other system parameters using it. And I want the power reading to be in sync with them. Could you forward this to the android perf team maybe They can help.

**Comment by DanAlbert** [comment]
The perf team lead is who I checked with before making my post above :)

**Comment by jainilparikh** [comment]
oh ok.

**Comment by yabinc** [comment]
> I actually dont have another choice except simpleperf as I am collecting some other system parameters using it.

By default, simpleperf uses monotonic time in the system. So it's easy to sync it with events from other sources.
I found energy profiler in Android Studio (https://developer.android.com/studio/profile/energy-profiler), which shows energy
consumption in timeline. I am pretty sure you can match that timeline with profiling data generated by simpleperf.

There is also battery info in /sys/class/power_supply/battery, but that's for system wide.

**Comment by jainilparikh** [comment]
Thanks Yabinc, I will look into the methods you suggested.
