### ISSUE TITLE
[BUG] asan on API27

### ISSUE THREAD

**Issue by akallabeth** [android/ndk#1296]
### Description

I´m trying to run a ASAN enabled build according to https://developer.android.com/ndk/guides/asan
The (modified) sample can be found here https://github.com/akallabeth/ExampleASAN

The sample crashes on `System.loadLibrary`

Running the same sample on images >27 works as expected

#### Environment Details

Devices or Emulator running on API 27

* NDK 21.3.6528147
* CMake 3.10.2

**Comment by DanAlbert** [comment]
That project doesn't have any wrap.sh.

**Comment by akallabeth** [comment]
@DanAlbert yes, it uses a workaround and sets the required environment in java code working around #1297 
Could you please reopen? The sample works on API 28 and above, just with API 27 it crashes on `loadLibrary`

**Comment by DanAlbert** [comment]
That won't work. The library has to be loaded before the Java process starts. That's why you need wrap.sh at all.

**Comment by DanAlbert** [comment]
I suspect it's just sort of working on API 28, and that it would see a lot of false positives if used much?
