### ISSUE TITLE
[BUG] ASAN wrap.sh not working

### ISSUE THREAD

**Issue by akallabeth** [android/ndk#1297]
### Description

1. I´m trying to build a ASAN enabled apk with `wrap.sh` in the apk alongside the native libraries
1. APK can not be installed (invalid apk)
1. Remove the `wrap.sh` and set the environment variables using `android.system.Os.setevn`
1. APK can be installed and works

#### Environment Details

* NDK 21.3.6528147
* CMake 3.10.2
* ABI: Tested on 27, 28, 29, 30

**Comment by DanAlbert** [comment]
That project doesn't have any wrap.sh.

**Comment by DanAlbert** [comment]
(sorry, posted on wrong bug)

**Comment by DanAlbert** [comment]
Although here I think we need a repro case.

**Comment by DanAlbert** [comment]
If I build my own ASan app I get a completely different problem: https://github.com/android/ndk/issues/1298

**Comment by nfedera** [comment]
The docs fail to mention that `android:extractNativeLibs="true"`  must be added to the manifest xml

**Comment by nfedera** [comment]
The most likely reason for this pitfall is that the [docs](https://developer.android.com/ndk/guides/wrap-script#packaging_wrapshl) say that `android:extractNativeLibs="true"` is the default, which does not seem to be true for Studio users.

**Comment by DanAlbert** [comment]
Ah, right. That was the default when the docs were written but that changed recently in AGP (4.0, I think?)

Yes, if I remove that line from my manifest I get the same issue. Sent a patch to update the docs with the following wording:

> It's also necessary to set `android:extractNativeLibs="true"` in
> `<application>`. Depending on your `minSdkVersion` and the version of the
> Android Gradle Plugin you're using this may be the default, but you may want to
> set this explicitly to `true` to avoid any surprises.

**Comment by DanAlbert** [comment]
(and a similar update to the doc for asan proper)
