### ISSUE TITLE
[BUG] error occurs while building mediapipe android application.

### ISSUE THREAD

**Issue by pianyun** [android/ndk#1301]
--------------------------------------------------------------------------------

#### Description

ERROR: /mediapipe/mediapipe/util/tracking/BUILD:409:1: C++ compilation of rule '//mediapipe/util/tracking:motion_estimation' failed (Exit 254) clang failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/2453/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=28' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig '-Werror=return-type' '-Werror=int-to-pointer-cast' '-Werror=pointer-to-int-cast' '-Werror=implicit-function-declaration' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-armeabi-v7a-opt/bin/mediapipe/util/tracking/_objs/motion_estimation/motion_estimation.pic.d '-frandom-seed=bazel-out/android-armeabi-v7a-opt/bin/mediapipe/util/tracking/_objs/motion_estimation/motion_estimation.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -iquote . -iquote bazel-out/android-armeabi-v7a-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/android-armeabi-v7a-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/android-armeabi-v7a-opt/bin/external/zlib -iquote external/com_github_glog_glog_v_0_3_5 -iquote bazel-out/android-armeabi-v7a-opt/bin/external/com_github_glog_glog_v_0_3_5 -iquote external/com_google_absl -iquote bazel-out/android-armeabi-v7a-opt/bin/external/com_google_absl -iquote external/eigen_archive -iquote bazel-out/android-armeabi-v7a-opt/bin/external/eigen_archive -isystem external/com_google_protobuf/src -isystem bazel-out/android-armeabi-v7a-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/android-armeabi-v7a-opt/bin/external/zlib -isystem external/com_github_glog_glog_v_0_3_5/src -isystem bazel-out/android-armeabi-v7a-opt/bin/external/com_github_glog_glog_v_0_3_5/src -isystem external/eigen_archive -isystem bazel-out/android-armeabi-v7a-opt/bin/external/eigen_archive -w '-std=c++14' -DPARALLEL_INVOKER_ACTIVE '--sysroot=external/androidndk/ndk/platforms/android-28/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c mediapipe/util/tracking/motion_estimation.cc -o bazel-out/android-armeabi-v7a-opt/bin/mediapipe/util/tracking/_objs/motion_estimation/motion_estimation.pic.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/motion_estimation-998769.cpp
clang: note: diagnostic msg: /tmp/motion_estimation-998769.sh
clang: note: diagnostic msg:

********************
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu failed to build
INFO: Elapsed time: 1798.400s, Critical Path: 1605.28s
INFO: 572 processes: 571 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version:  both r18b and r20 are failed.
* Build system: ndk-build
* Host OS:  linux docker under windows.
* ABI: arm64-v8a,armeabi-v7a
* NDK API level: 28

**Comment by stephenhines** [comment]
This needs a source file and the command line to reproduce the error. From the description above, we can't diagnose any issue. Also, can you please try this with NDK r21 to see if it still fails first?

**Comment by DanAlbert** [comment]
Closing for lack of information. We'll reopen if we get the information we need to proceed.
