### ISSUE TITLE
[BUG] std::make_shared memory corruption in std::vector

### ISSUE THREAD

**Issue by ajunkala** [android/ndk#1302]
#### Description

I am updating code and did an NDK version bump from r19 to r21d. I appear to have come across a strange bit of memory corruption that is happening when I use std::make_shared. It seems to have appeared between 19.2.5345600 and 20.0.5594570. I noticed it when I bumped to the latest (21.3.6528147) and then checked in: 21.3.6528147, 21.1.6352462, 20.1.5948944, 20.0.5594570, 19.2.5345600 ,17.2.4988734

It only happens with std::make_shared. Using the std::shared_ptr constructor w/ a raw pointer doesn't lead to corruption.
It appears to manifest when the std::shared_ptr is pushed onto a std::vector. I.e when poking values the shared_ptr is fine before calling push_back(), and shows corruption after.

The structure where I am seeing it happen is:

```
  struct Connection
  {
    std::shared_ptr<Town> start;
    std::shared_ptr<Town> end;
    float distance_crow;
    std::vector<NeighbourCell> route;

    bool operator<(const Connection& rhs) const;
    bool findRoute(WorldCell* cells, std::shared_ptr<const WorldGenerationSettings> settings);
  };
```

for reference (may be relevant for following comments):

```
  struct NeighbourCell
  {
    short x;
    short y;
    size_t index;
  };
```

The corruption manifests in two ways.
Occasionally (and not consistently) a std::vector<std::shared_ptr<Connection>> will have the first two entries reset at some point (i.e. they appear as nullptr when poked in the debugger). This happens inconsistently so I haven't been able to probe it for much info.
Consistently a 'route' vector (the one in the Connection structure) will be corrupted on some (not all) pushes. This becomes noticeable when, at a later time, route.push_back() is called, since it tests size, gets back the size of a crazy high value, and throws.

I have used the following code to repro the issue as far as a c++ function called from Activity::onCreate

   ```
 for(int i = 0; i < 20000; i++)
    {
      auto connection = std::make_shared<Connection>();
//      auto connection = std::shared_ptr<Connection>(new Connection()); // This does not result in corruption
      if(connection->route.size() != 0)
        LOGE("%d created: %p size: %zu", i, connection.get(), connection->route.size());
      testable.push_back(connection);
      if(connection->route.size() != 0)
        LOGE("%d create %p pushed is junk size: %zu", i, connection.get(), connection->route.size());
    }
```

LOGE is a simple macro that passes through to __android_log_vprint to provide an area tag.

It seems to consistently happen at the same spot (e.g. the original detection point had the first detected corruption on the 3rd Connection created every time). And the first LOGE will not be hit, but the second one will.

#### Environment Details

Occurs in ndk versions:
 21.3.6528147, 21.1.6352462, 20.1.5948944, 20.0.5594570
Does not occur in ndk versions:
 19.2.5345600 ,17.2.4988734

Seen both in linux and windows builds
Android Studio 3.6 and 4.0

Running on Nokia 4.2 w Android 10 June 5 patch.

**Comment by ajunkala** [comment]
Going to close this for now. I have experimented a bit more this evening and discovered that when the I move the code where I see the corruption happening, it disappears. This leads me to suspect something is writing where it shouldn't be and r20 has exposed it (or something about r20+ causes it to write where it shouldn't).

**Comment by DanAlbert** [comment]
Sounds good, hadn't found time to investigate yet anyway :) Reopen if you find otherwise.

**Comment by ajunkala** [comment]
I wasn't sure if I should reopen it, but after digger deeper I finally found the culprit. A good fix is on my side, however I figured I would leave a note in case it highlights a deeper issue showing up in r20.

The problem is that I had two structs in the same namespace with the name Connection. This wasn't intentional. They are from separate (functionality and temporally :) ) features. Because they are separate it did not kick up any duplicate symbols issues since no files ever bring both in for compilation. 

What seems to be happening starting in r20 is it grabbed the wrong template instantiation of std::make_shared<Connection>. 
We'll say there is ConnectionA and ConnectionB. In the code with the corruption, I want a std::shared_ptr<ConnectionA>, so I call std::make_shared<ConnectionA>(), however the actually offset being hit is std::make_shared<ConnectionB>. So it allocates something of the wrong size. Thus bad stuff happens later. 
It took a while to notice, but ASAN spat out this odd construction on an overflow:
std::__ndk1::shared_ptr<AW::Connection> std::__ndk1::shared_ptr<AW::Connection>::make_shared<std::__ndk1::shared_ptr<AW::PuzzlePiece>&>(std::__ndk1::shared_ptr<AW::PuzzlePiece>&)

PuzzlePiece is what tipped me off, that is the parameter in the constructor of 'ConnectionB', ConnectionA has a default constructor.

I don't have a good repo code set for you (it is late here), but if I would hazard a guess you need:
Two structs, same name, header guards, namespace but different layout (helpful w/ something that does basic checks like std:::vector)
Instantiations of std::make_shared templates for both somewhere.
And a call to std::make_shared for one that (hopefully) ends up going to the wrong one.

**Comment by enh-google** [comment]
did you try linking with lld? it's usually much better at spotting and reporting ODR violations.

**Comment by ajunkala** [comment]
Hadn't before, rolled back my changes out of curiosity and it looks like it doesn't catch this one either.

**Comment by DanAlbert** [comment]
There's no symbol for the struct itself and template functions are inlineish so there probably isn't any way for LLD to know.

> I don't have a good repo code set for you

It sounds like this is WAI, as annoying as this behavior is here. C++ runs wild with ODR. I think this is just one of those cases, sadly.
