### ISSUE TITLE
[FR] Expose AServiceManager binder_ndk APIs through this standalone APK

### ISSUE THREAD

**Issue by rpavlik** [android/ndk#1304]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can build a native app/library that provides a service using AIDL and binder_ndk, but I need an implementation of `Service` (server side) or `ServiceConnection` (client side) in Java/Kotlin in order to expose/access that service.

**Describe the solution you'd like**

I'd like NDK updated so that the stub libraries expose the AServiceManager (and ABinderProcess probably also) entry points, and the `android/binder_manager.h` (and `android/binder_process.h`) headers are included. Specifically, the following entry points:

- AServiceManager_addService
- AServiceManager_checkService
- AServiceManager_getService
- ideally, also ABinderProcess_joinThreadPool
- ideally, also ABinderProcess_setThreadPoolMaxThreadCount
- ideally, also ABinderProcess_startThreadPool

This would presumably involve:

- moving those two headers from here <https://android.googlesource.com/platform/frameworks/native/+/master/libs/binder/ndk/include_platform/android> - which is `include_apex` in android-10 - to just `include_ndk/android`
- Removing the `# apex llndk` decoration from the mentioned entry points in the linker version script https://android.googlesource.com/platform/frameworks/native/+/master/libs/binder/ndk/libbinder_ndk.map.txt

Preferably this would work even against android-10/platform 29, since those symbols do exist, but if there's some compelling reason they can't be exposed by default earlier, I'd be interested to hear it.

Regarding their stability: They're not tested in the CTS, but they are tested in the libbinder_ndk tests themselves:  https://android.googlesource.com/platform/frameworks/native/+/master/libs/binder/ndk/tests/  (which build against the platform and thus don't hit this issue), and are even used in other tests in the platform, e.g. https://cs.android.com/android/platform/superproject/+/master:packages/modules/DnsResolver/tests/dns_responder/dns_responder_client_ndk.cpp?q=aservicemanager as well as in other services/code in the platform e.g. https://cs.android.com/android/platform/superproject/+/master:hardware/interfaces/light/aidl/default/main.cpp?q=AServiceManager

**Describe alternatives you've considered**

The other alternative is to build against the platform itself, where AServiceManager_* and friends are provided by binder_ndk and not stripped out. However, that's a very large dependency for a handful of entry points that already appear stabilized, and risks resulting in an unnecessary coupling with a single platform version.

**Additional context**

These are slightly documented in platform docs: https://source.android.com/devices/architecture/aidl/aidl-backends#how-to  The documentation there is actually probably the most complete prose documentation for the whole binder_ndk system, since over on the non-platform (developer.a.c) side there is just a reference documentation matching the header file. The platform docs state that "These operations can only be done when compiling against platform Android." with respect to the service manager actions, but they don't explain why, and whether that's an intentional, permanent decision, or a default posture until use cases/requests came in for non-platform uses.

Thank you for considering this!

**Comment by DanAlbert** [comment]
You'll need to file a platform bug (b.android.com) if you want new system APIs. We don't own the OS side of this so there isn't anything we can do about it.

Feel free to leave a link to the platform bug here and we can help get it triaged though.

**Comment by rpavlik** [comment]
Ah, thanks for the info. I have filed it here: https://issuetracker.google.com/issues/160351035

**Comment by DanAlbert** [comment]
Np, thanks for filing! I assigned it to the relevant owner.

**Comment by ZZ0R0** [comment]
Any update on this ?

Still missing these files from the ndk, i do'nt understand why because there are many ones presents

**Comment by DanAlbert** [comment]
The people that monitor this thread don't work on the platform APIs, we only ship them. If you want to talk to the people that have the power to do something about this, comment on https://issuetracker.google.com/issues/160351035.
