### ISSUE TITLE
Where can I download libc++_shared.so for Android?

### ISSUE THREAD

**Issue by Karraya** [android/ndk#1311]
My Android missing Libc++_shared.so and giving me trouble to run certain operation. Where can I download it? I am planing to push it to my device using adb. Libc++_shared.so must be 64 bit.

**Comment by atsushieno** [comment]
They are included in NDK releases (try something like `find ~/Library/Android/sdk/ndk/21.3.6528147/ -name libc++_shared.so`) but this is probably what you actually want (unless you are trying to imlement some dev tool like hot reloading): https://stackoverflow.com/a/57160242/1465645

I hit the missing library issue with my projects that depends on various shared libraries that were built with "waf" build system (I tailored them for Android) last week.

**Comment by DanAlbert** [comment]
What @atsushieno said: this isn't something you should be concerned with unless you're making your own build system. If you _are_ making your own build system, see https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md.

But odds are you just want Gradle to handle this for you, in which case see https://developer.android.com/ndk/guides/cpp-support#selecting_a_c_runtime
