### ISSUE TITLE
[BUG] Clang and CMake can not detect `-fsanitize=address` with `check_c_compiler_flag` on `arm64-v8a` only

### ISSUE THREAD

**Issue by akallabeth** [android/ndk#1312]
#### Description

1. Trying to detect the availability of `-fsanitize=address` (or memory/thread for that matter) with `check_c_compiler_flag`
1. Detection works on `x86`, `x86_64`, `armeabi-v7a`
1. Detection breaks on `arm64-v8a`

#### Environment Details

* NDK Version: From 18.1.5063045 to 21.3.6528147
* Build system: `CMake`
* Host OS: Ubuntu 20.04 and Debian 10
* ABI: `arm64-v8a`
* NDK API level: all (Tested from 21 to 30)

#### Code sample
```
cmake_minimum_required(VERSION 3.4)

project(test LANGUAGES C)

include(CheckCCompilerFlag)
CHECK_C_COMPILER_FLAG ("-fno-omit-frame-pointer" fno-omit-frame-pointer)
set(CMAKE_REQUIRED_FLAGS "-fsanitize=address")
CHECK_C_COMPILER_FLAG ("-fsanitize=address" fsanitize-address)
message("Detected: ${fsanitize-address}")

```

**Comment by DanAlbert** [comment]
Just a guess, pass `-DANDROID_LD=lld` when invoking CMake? The common answer when something affects only aarch64 is that it's a bfd issue since only aarch64 still uses bfd.

**Comment by akallabeth** [comment]
@DanAlbert Thank you, that actually works.

**Comment by DanAlbert** [comment]
Glad to hear it. Going to close this then. I'm mildly curious why it isn't working with bfd, but bfd is deprecated in r22 and will hopefully be gone in r23 so the fix wouldn't be all that useful :)
