### ISSUE TITLE
Facing problem in NDK integration while using android studio 4.0

### ISSUE THREAD

**Issue by farhansaid127** [android/ndk#1313]
My NDK was working in before android studio updating. i have update my android studio to 4.0 and i am getting the below error

Could not find method ndkVersion() for arguments [21.3.6528147] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

i have installed the ndk version  [21.3.6528147]  at below location
D:\sdk\ndk\21.3.6528147

but it is still giving the same error.

**Comment by DanAlbert** [comment]
It sort of sounds like you're using an old Gradle plugin.

If not, follow b.android.com and file a studio bug.

**Comment by guoziren** [comment]
Comment or delete ndkVersion 'version number' at build.gradle

**Comment by DanAlbert** [comment]
Upgrading to a newer version of the Gradle plugin is the better choice of that's an option for you.
