### ISSUE TITLE
[BUG]clang++ compiler crash

### ISSUE THREAD

**Issue by xphcyh** [android/ndk#1316]
Stack dump:
0.	Program arguments: /Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -cc1 -triple thumbv7-none-linux-android21 -emit-obj -mnoexecstack -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CAnMapRend.stdout.7e6334f2a26f.99193.YhVKIu.ii -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature +fpregs -target-feature +vfp2 -target-feature +vfp2d16 -target-feature +vfp2d16sp -target-feature +vfp2sp -target-feature +vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature +vfp3sp -target-feature -fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature -vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature +fp64 -target-feature +d32 -target-feature +neon -target-feature -crypto -target-feature -fp16fml -target-feature +strict-align -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=line-tables-only -dwarf-version=4 -debugger-tuning=gdb -ffunction-sections -fdata-sections -coverage-notes-file /root/ci_workspace/6908c5f2/GNaviMap/build/android/armeabi-v7a/release/CMakeFiles/GNaviMap.dir/root/ci_workspace/6908c5f2/GNaviMap/amap_framework/effects/CAnMapRenderEffectCreator.cpp.gcno -resource-dir /Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8 -O3 -Wformat -Werror=format-security -Werror=return-type -fdeprecated-macro -fdebug-compilation-dir /root/ci_workspace/6908c5f2/GNaviMap/build/android/armeabi-v7a/release -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fvisibility-inlines-hidden -stack-protector 2 -fno-signed-char -fwchar-type=short -fno-signed-wchar -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -load abtor_string_protect.so -o CMakeFiles/GNaviMap.dir/root/ci_workspace/6908c5f2/GNaviMap/amap_framework/effects/CAnMapRenderEffectCreator.cpp.o -x c++-cpp-output /root/workspace/.cache/tmp/CAnMapRend.stdout.7e6334f2a26f.99193.YhVKIu.ii 
1.	<eof> parser at end of file
2.	Code generation
 #0 0x0000000002e6e2b5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e6e2b5)
 #1 0x0000000002e6e63e llvm::sys::RunSignalHandlers() (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e6e63e)
 #2 0x0000000002e6e4e8 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e6e4e8)
 #3 0x00007f0d7b14d390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #4 0x0000000001d64261 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1d64261)
 #5 0x0000000001d5b6b6 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1d5b6b6)
 #6 0x0000000001cf7d14 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1cf7d14)
 #7 0x0000000001cf7c8a (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1cf7c8a)
 #8 0x000000000214657c (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x214657c)
 #9 0x00000000021451a0 llvm::ConstantExpr::handleOperandChangeImpl(llvm::Value*, llvm::Value*) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x21451a0)
#10 0x0000000002144633 llvm::Constant::handleOperandChange(llvm::Value*, llvm::Value*) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2144633)
#11 0x0000000002135ca9 llvm::Value::doRAUW(llvm::Value*, llvm::Value::ReplaceMetadataUses) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2135ca9)
#12 0x00000000027c5c9b (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x27c5c9b)
#13 0x00000000027c4755 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x27c4755)
#14 0x00000000027c3b43 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x27c3b43)
#15 0x0000000003e08ff1 llvm::FPPassManager::doInitialization(llvm::Module&) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x3e08ff1)
#16 0x00000000022aaed2 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x22aaed2)
#17 0x00000000022a7afe llvm::legacy::PassManagerImpl::run(llvm::Module&) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x22a7afe)
#18 0x00000000022be5d6 (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x22be5d6)
#19 0x00000000022a26b7 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x22a26b7)
#20 0x00000000022a160f (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x22a160f)
#21 0x000000000202c57c clang::ParseAST(clang::Sema&, bool, bool) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x202c57c)
#22 0x000000000251f39d clang::FrontendAction::Execute() (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x251f39d)
#23 0x000000000251ea5a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x251ea5a)
#24 0x000000000251b7ea clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x251b7ea)
#25 0x000000000251859a cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x251859a)
#26 0x000000000236f97a main (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x236f97a)
#27 0x00007f0d7a24d830 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20830)
#28 0x0000000003dc0c39 _start (/Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x3dc0c39)
clang++: error: unable to execute command: Segmentation fault
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5900059 based on r365631c) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290) (based on LLVM 9.0.8svn)
Target: armv7-none-linux-android21
Thread model: posix
InstalledDir: /Users/amap/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
CMakeFiles/GNaviMap.dir/build.make:5028: recipe for target 'CMakeFiles/GNaviMap.dir/root/ci_workspace/6908c5f2/GNaviMap/amap_framework/effects/CAnMapRenderEffectCreator.cpp.o' failed
make[2]: *** [CMakeFiles/GNaviMap.dir/root/ci_workspace/6908c5f2/GNaviMap/amap_framework/effects/CAnMapRenderEffectCreator.cpp.o] Error 254

**Comment by stephenhines** [comment]
We need the files to reproduce this or it is less likely that we can actually address the problem.

**Comment by xphcyh** [comment]
Pkg.Desc = Android NDK
Pkg.Revision = 21.0.6113669
我使用以上版本的ndk进行代码编译时，经常碰到在这个CAnMapRenderEffectCreator.cpp文件上出现crash;重新编译时，偶现能编译正常的情况。

**Comment by xphcyh** [comment]
无效bug
