### ISSUE TITLE
[question]  arm-linux-androideabi-gcc: not found | Error 127, Error 2, 

### ISSUE THREAD

**Issue by LovableFatty** [android/ndk#1321]
![image](https://user-images.githubusercontent.com/31664445/88107870-bad25e00-cb5c-11ea-9a56-84bb89c620bb.png)
Steps I followed:
make ARCH=arm goldfish_armv7_defconfig
make ARCH=arm menuconfig
    check "enable loadable module support"
    check "module unloading"
make ARCH=arm SUB_ARCH=arm CROSS_COMPILE=$/home/noah/Downloads/prebuilt-darwin/darwin-x86/toolchain/arm-linux-androideabi-4.4.x/bin/arm-linux-androideabi-

**Comment by LovableFatty** [comment]
It states arm-linux-androideabi-gcc: not found but going into the file shows arm-linux-androideabi-gcc
![image](https://user-images.githubusercontent.com/31664445/88108765-400a4280-cb5e-11ea-8741-fa91ec3a25d8.png)

**Comment by stephenhines** [comment]
It looks like you're trying to build the Linux kernel with some NDK prebuilts that you have, but you really need to supply us with more information before we can help here. I'm also going to point out that you need to be building the Linux kernel with Clang instead of gcc, as we no longer provide support for gcc in the Android toolchain. @nickdesaulniers, can you post a sample command line for your suggested kernel build?

**Comment by stephenhines** [comment]
Actually, I just spotted your bug. `$/home/noah/Downloads/prebuilt-darwin/darwin-x86/toolchain/arm-linux-androideabi-4.4.x/bin/arm-linux-androideabi-` in your command line should probably be `$HOME/Downloads/...` or just drop the `$` from that part of your command line.

**Comment by LovableFatty** [comment]
> Actually, I just spotted your bug. `$/home/noah/Downloads/prebuilt-darwin/darwin-x86/toolchain/arm-linux-androideabi-4.4.x/bin/arm-linux-androideabi-` in your command line should probably be `$HOME/Downloads/...` or just drop the `$` from that part of your command line.

![image](https://user-images.githubusercontent.com/31664445/88109554-96c44c00-cb5f-11ea-84b6-c578810d115d.png)
![image](https://user-images.githubusercontent.com/31664445/88109646-bce9ec00-cb5f-11ea-94a4-4e47610927c8.png)

**Comment by DanAlbert** [comment]
The NDK doesn't have GCC 4.4. The path you're using isn't pointing at a real directory.

**Comment by LovableFatty** [comment]
> The NDK doesn't have GCC 4.4. The path you're using isn't pointing at a real directory.

![image](https://user-images.githubusercontent.com/31664445/88109831-063a3b80-cb60-11ea-83e6-3ffe29b897ad.png)
Doesn't this image showcase gcc 4.4.3? Also what do you mean by 'The path you're using isn't pointing at a real directory.' ?

**Comment by LovableFatty** [comment]
> building the Linux kernel with Clang

After I build a linux kernel with clang how do I build an android LKM? that's my end goal

**Comment by DanAlbert** [comment]
That's an _extremely_ old NDK then.

**Comment by stephenhines** [comment]
> > building the Linux kernel with Clang
> > @stephenhines
> > After I build a linux kernel with clang how do I build an android LKM? that's my end goal

This isn't the place for building Android kernels and modules. It is the bug tracker for the NDK. If you're going to be using Clang, you can possibly get help from https://github.com/ClangBuiltLinux.

**Comment by nickdesaulniers** [comment]
Android kernels are now built with Clang.  We've removed GCC from prebuilts/gcc/...
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md

Use `make CC=clang ...` to build with Clang rather than gcc.  https://github.com/ClangBuiltLinux/linux/wiki/Steps-for-compiling-the-kernel-with-Clang#cross-compiling as an example.

**Comment by LovableFatty** [comment]
> Android kernels are now built with Clang. We've removed GCC from prebuilts/gcc/...
> https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md
> 
> Use `make CC=clang ...` to build with Clang rather than gcc. https://github.com/ClangBuiltLinux/linux/wiki/Steps-for-compiling-the-kernel-with-Clang#cross-compiling as an example.
@DanAlbert 
I found this example:
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang HOSTCC=clang
My current make command is: make ARCH=arm SUB_ARCH=arm CROSS_COMPILE=$HOME/Downloads/android-ndk-r10e-linux/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-
To adopt clang would my make command be:
$ ARCH=arm CROSS_COMPILE=$Path=/to/my/ndk make CC=clang HOSTCC=clang ?
