### ISSUE TITLE
[BUG] clang++: Error: selected processor does not support `bfc w19,#0,#16'

### ISSUE THREAD

**Issue by tcamargo** [android/ndk#1322]
#### Description
clang++ is generating invalid assembly code if I use -march=armv8-a or don't use -march at all.

```
Compiling src/mame/drivers/gba.cpp...
/home/camargo/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++    -MMD -MP -MP -D__LIBRETRO__ -DNDEBUG -DPTR64=1 -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../3rdparty/bgfx/3rdparty/khronos" -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/mame" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../src/lib/netlist" -I"../../../../../3rdparty" -I"../../../../generated/mame/layout" -I"../../../../../3rdparty/libflac/include" -I"../../../../../3rdparty/glm" -I"../../../../../3rdparty/libjpeg" -I"../../../../../3rdparty/rapidjson/include" -I"../../../../../3rdparty/zlib"  -O2 -fPIC -pipe -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-cast-align -Wno-tautological-compare -Wno-unused-value -Wno-constant-logical-operand -fdiagnostics-show-note-include-stack -Wno-unknown-warning-option -Wno-extern-c-compat -Wno-unknown-attributes -Wno-ignored-qualifiers -Wno-missing-braces -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -Wunused-value -Wno-macro-redefined -DASIO_HAS_STD_STRING_VIEW -Wno-unused-function -gcc-toolchain /home/camargo/ndk/android-ndk-r21d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -march=armv8-a -Wno-undef -Wno-typedef-redefinition -Wno-incompatible-ms-struct -Wno-asm-operand-widths -std=c++14 -Woverloaded-virtual -Wno-extern-c-compat -Wno-tautological-constant-out-of-range-compare -Wno-tautological-pointer-compare -include ../../../../libretro/obj/libretro/emu.h -include /home/camargo/batocera/mame/src/osd/libretro/retroprefix.h -o "../../../../libretro/obj/libretro/src/mame/drivers/gba.o" -c "../../../../../src/mame/drivers/gba.cpp"
/tmp/gba-94cb59.s: Assembler messages:
/tmp/gba-94cb59.s:948: Error: selected processor does not support `bfc w19,#0,#16'
clang++: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [nintendo.make:1329: ../../../../libretro/obj/libretro/src/mame/drivers/gba.o] Error 1
```

Error goes away if I use -march=armv8.2-a.

##### Test case
1. Clone https://github.com/tcamargo/mame
1. Checkout libretro/android-fix
2. Set the necessary NDK environment variables. Sample:
```
export NDK=/home/camargo/ndk/android-ndk-r21d
export ANDROID_NDK_ROOT=${NDK}
export ANDROID_NDK_LLVM=${NDK}/toolchains/llvm/prebuilt/linux-x86_64
export ANDROID_NDK_ARM=${NDK}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
export ANDROID_NDK_ARM64=${NDK}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
```
4. Compile mame (it will take a while to get to the problematic file)
`make -f makefile platform=arm64 -j6 OSD=retro verbose=1 RETRO=1 NOWERROR=1 NOASM=1 gcc=android-arm64 OS=linux TARGETOS=android-arm64 CONFIG=libretro NO_USE_MIDI=1 TARGET=mame REGENIE=1`

#### Environment Details

* NDK Version: 
Pkg.Desc = Android NDK
Pkg.Revision = 21.3.6528147
* Build system: genie
* Host OS: Linux - Archlinux 5.7.8-arch1-1

**Comment by enh-google** [comment]
is the bug here that you're passing `-fno-integrated-as` as part of your build? i think the problem here isn't clang (which i'm assuming supports its own output), but a mismatch between clang and gas...

**Comment by tcamargo** [comment]
Should I try to remove -fno-integrated-as? I don't remember if I tried that.

**Comment by enh-google** [comment]
> Should I try to remove -fno-integrated-as? I don't remember if I tried that.

definitely. we'll probably remove gas (the non-integrated assembler) at some point anyway, and it's already pretty old.

**Comment by tcamargo** [comment]
I just remembered i tried that before opening this bug. Compilation works but dlopen fails.

`07-20 21:23:59.257 31592 31681 E RetroArch: Failed to open libretro core: "/data/user/0/com.retroarch.aarch64/cores/mame_libretro_android.so" 07-20 21:23:59.258 31592 31681 E RetroArch: Error(s): dlopen failed: "/data/data/com.retroarch.aarch64/cores/mame_libretro_android.so" has invalid shdr offset/size: 413212352/2240`

**Comment by rprichard** [comment]
Maybe the NDK Clang driver should ignore `-fno-integrated-as` (e.g. print an unused argument warning)?

**Comment by DanAlbert** [comment]
```
$ du -sh mame_libretro_android.so
394M    mame_libretro_android.so
$ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --strip-unneeded mame_libretro_android.so -o stripped.so
$ du -sh stripped.so
303M    stripped.so
$ ~/src/bloaty/bloaty stripped.so
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  40.3%   121Mi  33.9%   121Mi    .text
   0.0%       0  16.0%  57.6Mi    .bss
  13.8%  41.6Mi  11.6%  41.6Mi    .rela.dyn
  11.3%  34.3Mi   9.5%  34.3Mi    .dynstr
  10.3%  31.1Mi   8.6%  31.1Mi    .rodata
   8.1%  24.4Mi   6.8%  24.4Mi    .data.rel.ro
   5.1%  15.5Mi   4.3%  15.5Mi    .eh_frame
   4.2%  12.6Mi   3.5%  12.6Mi    .dynsym
   1.9%  5.72Mi   1.6%  5.72Mi    .gcc_except_table
   1.3%  3.81Mi   1.1%  3.81Mi    .eh_frame_hdr
   0.9%  2.72Mi   0.8%  2.72Mi    .gnu.hash
   0.7%  2.22Mi   0.6%  2.22Mi    .hash
   0.7%  1.98Mi   0.6%  1.98Mi    .rela.plt
   0.7%  1.97Mi   0.5%  1.97Mi    .got
   0.4%  1.32Mi   0.4%  1.32Mi    .plt
   0.3%  1.05Mi   0.3%  1.05Mi    .gnu.version
   0.0%  41.2Ki   0.0%  41.1Ki    .init_array
   0.0%  28.1Ki   0.0%  28.0Ki    .data
   0.0%  1.38Ki   0.0%     272    [8 Others]
   0.0%     656   0.0%     592    .dynamic
   0.0%     510   0.0%     510    [LOAD #0 [RX]]
 100.0%   302Mi 100.0%   359Mi    TOTAL
```

**Comment by rprichard** [comment]
I tried building the project after commenting out `-fno-integrated-as` (in scripts/toolchain.lua), and I was able to dlopen the resulting mame_libretro_android.so (tested on a Pixel 2 running QQ3A.200805.001). The section header offset/size looks fine as well (but it doesn't match the reported 413212352 offset above):

```
$ readelf -h mame_libretro_android.so  | grep section
  Start of section headers:          413535000 (bytes into file)
  Size of section headers:           64 (bytes)
  Number of section headers:         35
$ wc -c mame_libretro_android.so 
413537240 mame_libretro_android.so
```
The section headers end exactly at the end of the file, but that should be OK. The linker's CheckFileRange correctly uses a `range_end <= file_size_` check rather than `range_end < file_size_`.

What is the file size of `/data/data/com.retroarch.aarch64/cores/mame_libretro_android.so`?

**Comment by tcamargo** [comment]
Sorry for the confusion. That error message came from a user report with an older build. I built again yesterday and will send it for testing. I can't test myself.. :(

https://camargo.batocera.org/libretro-mame/android-aarch64/mame_libretro_android.so

**Comment by tcamargo** [comment]
Thanks for your support. In the end, it was a bogus user report. -fno-integrated-as did the trick.

**Comment by DanAlbert** [comment]
`-fno-integrated-as` isn't going to work out of the box in a release or two, so you'll want to get that figured out. Either that or you can build GAS yourself.

**Comment by DanAlbert** [comment]
(oh, or do you mean *removing* that did the trick?)

**Comment by tcamargo** [comment]
It did previously but I thought it generated a bad build. I can test aarch64 atm and relied on user reports. @rprichard said he was able to load the generated shared library, so I decided to try again. Mame core is working...
