### ISSUE TITLE
[question] make compile error (help a newbie)

### ISSUE THREAD

**Issue by LovableFatty** [android/ndk#1323]
Please include any context relevant to your question (NDK version, ABI, build system, etc).
Hi, I'm trying to follow a old guide from 2015. Using NDK:r10e-linux86_64 OS:Kali Kernel: Goldfish 3.4
My steps are:
git clone https://android.googlesource.com/kernel/goldfish
cd goldfish
git checkout -t origin/android-goldfish-3.4 -b android-goldfish-3.4
make ARCH=arm goldfish_armv7_defconfig
make ARCH=arm menuconfig
		check "enable loadable module support" // I want to build a LKM for android 
		check "module unloading" 
make ARCH=arm SUB_ARCH=arm CROSS_COMPILE=$HOME/Downloads/android-ndk-r10e-linux/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/
Note: I had other error messages and I fixed it by removing -fno-delete-null-pointer-checks & -mno0thumb bc It told me these were unrecognized command line options
Error:
![image](https://user-images.githubusercontent.com/31664445/88440036-9b883a80-cdc1-11ea-9088-d1e1934e061b.png)
/home/noah/goldfish/kbuild:40 
![image](https://user-images.githubusercontent.com/31664445/88440391-a68f9a80-cdc2-11ea-8c72-4777f407c46b.png)
/home/noah/goldfish/Makefile:986
![image](https://user-images.githubusercontent.com/31664445/88440438-c6bf5980-cdc2-11ea-9aa4-7e6969eb4506.png)

**Comment by DanAlbert** [comment]
https://github.com/android/ndk/issues/1321#issuecomment-662157120 pointed to docs on building the Android kernel. A guide from 2015 is going to be wrong.
