### ISSUE TITLE
docs wrong for using NDK with autoconf for arm32

### ISSUE THREAD

**Issue by fysiskhund** [android/ndk#1324]
#### Description
When I follow the official instructions in [https://developer.android.com/ndk/guides/other_build_systems](https://developer.android.com/ndk/guides/other_build_systems), specifically for building libraries with Autoconf, in the Linux toolchain (`export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64`) and target armv7a  (android
`export TARGET=armv7a-linux-androideabi`), I get the following error after running make:

`./libtool: line 1720: /common/tools/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi-ar: No such file or directory`

As of version 21.3.6528147, the AR tool, as referenced by the documentation, does not exist. Neither do AS, LD and STRIP tools. Other targets (aarch64, x86, etc) do have the corresponding AR, AS, LD, RANLIB and STRIP tools.

I looked a little further into the  and found the following tools:
```
arm-linux-androideabi-addr2line 
arm-linux-androideabi-c++filt
arm-linux-androideabi-gprof
arm-linux-androideabi-ld.gold
arm-linux-androideabi-objdump
arm-linux-androideabi-size
arm-linux-androideabi-ar
arm-linux-androideabi-dwp
arm-linux-androideabi-ld
arm-linux-androideabi-nm
arm-linux-androideabi-ranlib
arm-linux-androideabi-strings
arm-linux-androideabi-as
arm-linux-androideabi-elfedit
arm-linux-androideabi-ld.bfd
arm-linux-androideabi-objcopy
arm-linux-androideabi-readelf
arm-linux-androideabi-strip
```
I believe the "missing" AR, AS, LD, RANLIB and STRIP commands are those shown, but they have a name that does not match the pattern the documentation instructs one should use.

I referenced them in the environment variables instead, leaving the CC and CXX variables unchanged and was able to successfully build an external library.

**I believe that the arm-linux-androideabi- tools should be renamed to match the pattern from the documentation.** 
(Or is there something I'm missing?) Thanks

#### Environment Details

* NDK Version: 21.3.6528147 (they are also missing in 21.2.6472646; not sure about earlier versions)
* Build system: toolchain "as is" (i.e. as extracted by the SDK manager in Android Studio) and Autoconf
* Host OS: Debian GNU/Linux
* ABI: armv7a-linux-androideabi (others are fine and all tools match the pattern)
* NDK API level: 21
* Device API level: N/A

**Comment by DanAlbert** [comment]
The docs are wrong, not the implementation.

Clang needs to be armv7a-linux-androideabi$API because clang uses the executable name to determine the default target.

All of the other tools need to be arm-linux-androideabi because that's what GNU binutils produces.

FYI, all of the arm-linux-androideabi named tools are going away soon in favor of `llvm-ar` and co. These docs will need to be updated to account for that as well.

**Comment by DanAlbert** [comment]
The answer for how to solve your issue, btw, is to use each version of the prefix where it is appropriate. Use the armv7a one for clang and arm for everything else.

Also note that without a minSdkVersion suffix on the clang binary you're going to build broken binaries unless you've specified that to clang some other way.

**Comment by DanAlbert** [comment]
Triaging to r22 because we'll want to update that guidance to point to the LLVM tools since they're the new defaults in r22.

**Comment by fysiskhund** [comment]
Okay, thank you for the explanation :)

I had already tried "mixing" the tools and was able to build the library I needed, but wanted to be sure.
I'll keep an eye for the new release and docs.

**Comment by kroggen** [comment]
I used this script to create symbolic links:

```
cd $ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/

for source in arm-linux-androideabi-*
do
    dest=${source/arm/armv7a}
    ln -sf $source $dest
done

cd -
```

**Comment by DanAlbert** [comment]
Fixed https://developer.android.com/ndk/guides/other_build_systems. If the page looks unchanged for you (in English) it's just a caching issue that'll sort itself out (I can see the updated version). For non-English translations of the page my understanding is that my changing of the doc puts it in a translation queue and it'll get fixed soon.
