### ISSUE TITLE
[BUG]Can't create a static library in Android C++ project

### ISSUE THREAD

**Issue by Shuyun6** [android/ndk#1325]
1. I create a Android c++ project in Android Studio by default way. [File -> New -> New Project -> Native C++]
2. It's default Android native project, and after I build it, I can find _libnative-lib.so_ in _app/build/intermediates/cmake/debug/obj/armeabi-v7a/_
because in CMakelists.txt :
```
add_library( # Sets the name of the library.
             native-lib

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             native-lib.cpp
        )
```
3. Then I want to get a static library like _libnative-lib.a_, so change _SHARED_ to _STATIC_
```
add_library( # Sets the name of the library.
             native-lib

             # Sets the library as a shared library.
             STATIC

             # Provides a relative path to your source file(s).
             native-lib.cpp
        )
```
then build it
BUT I can't find any files in _app/build/intermediates/cmake/debug/obj/armeabi-v7a/_

How to solve this problem?

**Comment by alexcohn** [comment]
You should explicitly list the static libraries as [targets](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.ExternalNativeCmakeOptions.html#com.android.build.gradle.internal.dsl.ExternalNativeCmakeOptions:targets) for cmake in your **build.gradle**.

The doc explains that *If you don't configure this property, Gradle builds all executables and shared object libraries that you define in your CMake project.*

**Comment by Shuyun6** [comment]
> You should explicitly list the static libraries as [targets](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.ExternalNativeCmakeOptions.html#com.android.build.gradle.internal.dsl.ExternalNativeCmakeOptions:targets) for cmake in your **build.gradle**.
> 
> The doc explains that _If you don't configure this property, Gradle builds all executables and shared object libraries that you define in your CMake project._

@alexcohn Thanks! It helps me a lot!

**Comment by DanAlbert** [comment]
Thanks, @alexcohn! Got sidetracked trying to find the docs and forgot to come back to this.

**Comment by cnwutianhao** [comment]
My Android Studio Version: `Android Studio Dolphin | 2021.3.1 Patch 1`

First, change `SHARED` to `STATIC` in CMakeList: 

```
cmake_minimum_required(VERSION 3.18.1)

project("mystaticapplication")

add_library( # Sets the name of the library.
        mystaticapplication

        # Sets the library as a shared library.
        STATIC

        # Provides a relative path to your source file(s).
        native-lib.cpp)

find_library( # Sets the name of the path variable.
        log-lib

        # Specifies the name of the NDK library that
        # you want CMake to locate.
        log)

target_link_libraries( # Specifies the target library.
        mystaticapplication

        # Links the target library to the log library
        # included in the NDK.
        ${log-lib})
```

And then, add the `externalNativeBuild` block to your module-level `build.gradle` file: 
```
android {
    ...

    defaultConfig {
        ...

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_PLATFORM=latest', '-DANDROID_TOOLCHAIN=clang'
                targets 'mystaticapplication'
                cppFlags ''
            }
        }
    }

    ...

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.18.1'
        }
    }

    ...
}
```

Finally, `Rebuild Project`, It will generate the .a file you want:
```
...\app\build\intermediates\cxx\Debug\...\obj\arm64-v8a\libmystaticapplication.a
```
