### ISSUE TITLE
device image with hwasan[question]

### ISSUE THREAD

**Issue by 64Teenage** [android/ndk#1333]
the device image was built with hwasan using flag: make SANITIZE_TARGET=hwaddress. But after i flash it to device, then it can't boot up. the android version is 10, my platform is qcom(armv8a).
does anyone knows why?

**Comment by enh-google** [comment]
not without at least a stack trace, no.

but this also isn't an NDK question. you'll want to file a bug in buganizer and include your TAM. (or if you're a qcom customer rather than a qcom employee, you'll want to talk to qcom...)
