### ISSUE TITLE
[question] Shipping rules with AAR to disable AGP stripping

### ISSUE THREAD

**Issue by matpag** [android/ndk#1336]
We have an Android library that contains `.so` files built with CMake and then DexGuard process everything, obfuscate, encrypt native code and build the final AAR.

When a developer uses our library and build the APK, during the merging step of all libraries the strip tool produces some warning about not correctly formatted `.so` that can't be stripped out by `llvm-strip` tool.

This is what we have in console if we run ` ./gradlew :app:stripReleaseDebugSymbols --info` which is part of the `assembleRelease` task.

```
Starting process 'command '/USER/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip''. Working directory: /USER/Desktop/Projects/TestApp/app 
Command: /USER/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip --strip-unneeded -o /USER/Desktop/Projects/TestApp/app/build/intermediates/stripped_native_libs/release/out/lib/arm64-v8a/libMyLib.so /USER/Desktop/Projects/TestApp/app/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libMyLib.so
Successfully started process 'command '/USER/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip''
/USER/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip: error: '/USER/Desktop/Projects/TestApp/app/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libMyLib.so': The file was not recognized as a valid object file
Unable to strip library /USER/Desktop/Projects/TestApp/app/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libMyLib.so due to error 1 returned from /USER/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip, packaging it as is.
```
I've omitted some logs but the messages are the same for all "armeabi-v7a", "arm64-v8a", "x86", "x86_64".

I know that we can disable stripping using something like:
```
packagingOptions {
    doNotStrip "lib/*/libMyLib.so"
}
```
but we would bundle this "rule" in the AAR like we do for Proguard with `consumer-rules.pro`.

Is there a way to stop AGP to try to strip out native libraries and prevent the final consumer to see 300 hundreds lines of warnings while building?

I know the best option would be to produce a strippable `so`, and we are working on this too, but the question still remains.

Thank you.

NDK 21.3.6528147
CMake 3.4.1
AGP 4.0.1
AS 4.0.1

**Comment by DanAlbert** [comment]
Sorry for the delayed response. Saw this and it immediately got buried by other things :( 

You'll need to ask Studio. This tracker is for the NDK itself, not AGP.
