### ISSUE TITLE
[question] [FR] Generating prefab folder within .aar library

### ISSUE THREAD

**Issue by cirlam** [android/ndk#1337]
I currently produce a .aar library, that I would like to be able to distribute to customers to use as they wish - one use case is an NDK/C++ only app that consumes this .aar library. 

As I understand it, for this to work, I would need to generate my .aar library with /prefab directory inside it. The current build tools don't appear to do this - is there support on the way to generate this? 

Thank you!

**Comment by DanAlbert** [comment]
https://developer.android.com/studio/preview/features#4.1-prefab-publish does this from AGP.

https://android.googlesource.com/platform/tools/ndkports/ does this for arbitrary packages.

**Comment by alexcohn** [comment]
I guess the request is to have a dual-purpose .aar, which can be used both as a prefab (C++ dependency) and as a Java library with native methods. I made some experiments with such .aar layout, and reported [some problems](https://issuetracker.google.com/issues/120166563#comment8).
