### ISSUE TITLE
[BUG]  error: undefined reference to 'aligned_alloc'

### ISSUE THREAD

**Issue by tcamargo** [android/ndk#1339]
#### Description

clang++ linking is failing since mame switched to aligned_alloc.

```
Linking mame_libretro_android.so...
/home/camargo/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -o ../../../../../mame_libretro_android.so ../../../../libretro/obj/libretro/src/mame/mame.o ../../../../libretro/obj/libretro/src/osd/libretro/libretro-internal/libretro.o ../../../../libretro/obj/libretro/src/osd/libretro/retromain.o ../../../../libretro/obj/libretro/generated/mame/mame/drivlist.o ../../../../libretro/obj/libretro/generated/version.o     -L"/home/camargo/ndk/android-ndk-r21d/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a" -L"/home/camargo/ndk/android-ndk-r21d/platforms/android-24/arch-arm/usr/lib" -L"." -L"../../../../libretro/bin/mame_mame" -L"../../../../libretro/bin" -shared -nostdlib -no-canonical-prefixes -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -gcc-toolchain /home/camargo/ndk/android-ndk-r21d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/camargo/ndk/android-ndk-r21d/platforms/android-24/arch-arm /home/camargo/ndk/android-ndk-r21d/platforms/android-24/arch-arm/usr/lib/crtbegin_so.o /home/camargo/ndk/android-ndk-r21d/platforms/android-24/arch-arm/usr/lib/crtend_so.o -target armv7-none-linux-androideabi -march=armv7-a -mthumb -fPIC -shared ../../../../libretro/bin/mame_mame/libadp.a ../../../../libretro/bin/mame_mame/libalba.a
(...) many files (...)
../../../../libretro/bin/mame_mame/libocore_retro.a -lc -ldl -lm -landroid -llog -lc++_static -lc++abi -lstdc++ -landroid_support -lunwind -lgcc -lEGL -lGLESv1_CM -lGLESv2
../../../../libretro/bin/mame_mame/liboptional.a(netlist.o):netlist.cpp:function netlist_mame_analog_output_device::pre_parse_action(netlist::nlparse_t&): error: undefined reference to 'aligned_alloc'
../../../../libretro/bin/mame_mame/liboptional.a(netlist.o):netlist.cpp:function netlist_mame_logic_output_device::pre_parse_action(netlist::nlparse_t&): error: undefined reference to 'aligned_alloc'
../../../../libretro/bin/mame_mame/liboptional.a(netlist.o):netlist.cpp:function netlist_mame_stream_output_device::pre_parse_action(netlist::nlparse_t&): error: undefined reference to 'aligned_alloc'
../../../../libretro/bin/mame_mame/liboptional.a(netlist.o):netlist.cpp:function netlist_mame_device::base_validity_check(validity_checker&) const: error: undefined reference to 'aligned_alloc'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
#### Test case
1. Clone https://github.com/libretro/mame.git
1. Checkout af902d6ba630a91d9f75508c5e4f14b89c61acfa
2. Set the necessary NDK environment variables. Sample:
```
export NDK=/home/camargo/ndk/android-ndk-r21d
export ANDROID_NDK_ROOT=${NDK}
export ANDROID_NDK_LLVM=${NDK}/toolchains/llvm/prebuilt/linux-x86_64
export ANDROID_NDK_ARM=${NDK}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
export ANDROID_NDK_ARM64=${NDK}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
```
3. Compile mame
`make -f Makefile.libretro platform=android -j8`

#### Environment Details

* NDK Version:
  Pkg.Desc = Android NDK
  Pkg.Revision = 21.3.6528147
* Build system: genie
* Host OS: Linux - Archlinux 5.7.8-arch1-1

**Comment by DanAlbert** [comment]
Is there a way to build incrementally? It takes a very long time to show me my configuration mistakes even at `-j72`, and then it starts all over.

**Comment by tcamargo** [comment]
Build is always incremental. I think you got the impression because makefiles are generated every time. Export REGENIE=0 (via environment or directly in Makefile.libretro) to skip that.

**Comment by DanAlbert** [comment]
Doesn't seem to make a difference.

**Comment by DanAlbert** [comment]
Oh, I was confused because you'd originally commented on a bug that was about the C++17 aligned allocators. You're talking about the C library's `aligned_alloc`. That was added in P. Your build system isn't identifying your `minSdkVersion` correctly when compiling netlist.o but is when trying to link mame_libretro_android.so, so the API is incorrectly visible at compile time and the linker is protecting you from using unavailable APIs.

You can't use `aligned_alloc` directly unless you have minSdkVersion 28 or higher.

**Comment by rprichard** [comment]
Right, use `memalign` or `posix_memalign` instead.
 * `memalign` is always available on Android.
 * `posix_memalign` was added in API 17 (but is available on API 16 via libandroid_support.a, which is linked by default when targeting API 16).

I'm guessing this is the code that needs changing?

https://github.com/libretro/mame/blob/a72ce9e2561c315035c7bf01a0490766b42bf2ec/src/lib/netlist/plib/palloc.h#L419-L434

It's probably sufficient to change `defined(__APPLE__)` to `defined(__APPLE__) || defined(__ANDROID__)`. You could also use `defined(__BIONIC__)`, but I suppose I'd use `defined(__ANDROID__)`.

**Comment by tcamargo** [comment]
@rprichard Yes, that is problematic code block. I workaround by setting PUSE_ALIGNED_ALLOCATION to 0. Thanks for the explanation. Your proposal is right.
@DanAlbert I found a reference to minSdkVersion 24. Not sure exactly what that means. First time playing with ndk. Thanks for your support!
