### ISSUE TITLE
[BUG]See sensitive information save in native-lib resource

### ISSUE THREAD

**Issue by duonghv97** [android/ndk#1340]
**Note**: Bugs against Android Studio or Gradle should be filed at
http://b.android.com, not here.

I am using Cmake 3.4.1 save sensitive information but when attacker can decompile key in project

* NDK Version: 3.4.1

**Comment by DanAlbert** [comment]
I'm not sure what your question is, but this doesn't appear to be NDK related?

**Comment by duonghv97** [comment]
As far as I know the NDK used to conceal information. I used NDK version
3.4 to conceal information, but when building an app on the store, other
people can still use the techniques to see what information I was hiding.
Thanks

Vào Th 6, 18 thg 9, 2020 vào lúc 02:53 Dan Albert <
notifications@github.com> đã viết:

**Comment by DanAlbert** [comment]
The NDK offers no mechanisms for concealing app secrets that Java does not. Java is probably better, in fact, since I don't think any of the keystore APIs are availy to the NDK.
