### ISSUE TITLE
[question] llvm-ar seems to have issues when host platform is Darwin. 

### ISSUE THREAD

**Issue by heemansh** [android/ndk#1342]
llvm-ar throws linker issues during cross-compilation when the host platform is Darwin. I saw a bug opened for that but it is marked for milestone r22. This is a blocking issue for me as I am unable to update NDK version in my project on which higher NDK version clients are dependent on. Is it possible that the commit can be cherry-picked into r21 ?
Thanks

**Comment by DanAlbert** [comment]
Why? llvm-ar isn't recommended in r21. You should be using GNU ar in r21.

**Comment by heemansh** [comment]
https://github.com/android/ndk/issues/1209, i saw this issue and how to shift to GNU ar. Did you mean overriding ar locally ?

**Comment by DanAlbert** [comment]
That issue is a tracking bug for switching to llvm-ar in r22. You shouldn't do anything in r21.
