### ISSUE TITLE
[BUG] CMake configuration files are not bundled with prebuild LLVM toolchain

### ISSUE THREAD

**Issue by zOrg1331** [android/ndk#1344]
#### Description

Android NDK's prebuilt LLVM toolchain does not contain CMake files which are referenced by `llvm-config` tool:

```
$ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-config --cmakedir
<$NDK>/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm
```

The returned directory does not exist. However, it exists in the corresponding [VCS tree](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/ndk-release-r21/clang-r365631c2/lib64/cmake/).

Putting these files manually into `/toolchains/llvm/prebuilt/linux-x86_64/lib64/cmake/llvm` works. However, additional fixes to `LLVMExports-release.cmake` are required as a lot of unbundled executables and libraries are mentioned there.

In order to trigger/verify the problem it is enough to create CMakeLists.txt file containing:
```
find_package(LLVM REQUIRED CONFIG)
```

And calling `cmake` as described in the official documentation:
```
export NDK=$HOME/Android/ndk-bundle
export API=21
export ABI=arm64-v8a
cmake \
    -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI=$ABI \
    -DANDROID_NATIVE_API_LEVEL=$API \
    -DLLVM_DIR=`$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-config --cmakedir` \
    .
```

#### Environment Details

* NDK Version: 21.3.6528147
* Build system: CMake
* Host OS: Linux (ALTLinux Sisyphus)
* ABI: not relevant
* NDK API level: not relevant
* Device API level: not relevant

**Comment by hhb** [comment]
We intentionally [removed](https://android.googlesource.com/platform/ndk/+/refs/heads/master/ndk/checkbuild.py#484) these cmake file from NDK. Because we do not expect people to link to that LLVM. The unbundled executables are removed based on the same reason.

Can you tell more about your use case? What are you trying to build? Since you are targeting Android, there shouldn't be much thing you can link to... (Yeah you can use host tools and some libs....)

**Comment by zOrg1331** [comment]
> We intentionally [removed](https://android.googlesource.com/platform/ndk/+/refs/heads/master/ndk/checkbuild.py#484) these cmake file from NDK. Because we do not expect people to link to that LLVM. The unbundled executables are removed based on the same reason.

I see now, thank you. I was confused by presence of `llvm-config` which lead me to nonexisting path. At this moment I thought that LLVM is fully built for NDK and can be used by software that wants to use LLVM's JIT features. Apparently, using bare NDK for this purpose was wrong idea from the beginning.
