### ISSUE TITLE
[BUG] gdbserver x86_64

### ISSUE THREAD

**Issue by alex-curiou** [android/ndk#1347]
**Env**
* NDK Version: r21d
* Manifest branch: ndk-release-r21
* Build system: ndk-build
* Host OS: Ubuntu 14.04.6 LTS
* ABI: x86_64

**Build steps**
1. Download sources for master-ndk;
2. Build GDB server by python checkbuild.py --arch x86_64 --module gdbserver;

**Problem description**

When You try to attach the gdbserver to a running process as a root from a shell the server quits with a message:
"stack corruption detected
Aborted"

**Steps to reproduce**

1. Connect to a x86_64 emulator by 'adb shell';
2. become root;
3. Try to attach to any running process with by PID (for example 5432):
/data/data/com.termux/files/usr/bin/gdbserver --attach :23945 5432
or try to start any process to debug
/data/data/com.termux/files/usr/bin/gdbserver :23945 /data/data/com.termux/files/usr/bin/less
4. The server fails to start with the message:
stack corruption detected
Aborted

**Expected behavior**

The server attaches to the process with the given PID:
Attached; pid = 7734
Listening on port 23945

or (for the case when the process is started by gdbserver)
Process /data/data/com.termux/files/usr/bin/less created; pid = 7674
Listening on port 23945

**Additional information**

gdbserver during startup calls function void linux_ptrace_test_ret_to_nx(void) (from nat/linux-ptrace.c):
```
...
elf_gregset_t regs;
...
if (ptrace (PTRACE_GETREGS, child, (PTRACE_TYPE_ARG3) 0, (PTRACE_TYPE_ARG4) &regs) < 0)
...
```

And elf_gregset_t is a typedef of an array of 23 elements and the kernel returns 27 elements. There are also additional usages of this typedef in GDB server.

***The issue is because of NDK's sysroot/usr/include/sys/procfs.h. Just to compare.***
The NDK r21d version of sys/procfs.h
```
...
#include <sys/ucontext.h>
__BEGIN_DECLS
typedef unsigned long elf_greg_t;
typedef elf_greg_t elf_gregset_t[NGREG];
...

```
***GNU version bits/procfs.h (from my current Ubuntu installation)***
```
...
/* And the whole bunch of them. We could have used `struct
user_regs_struct' directly in the typedef, but tradition says that
the register set is an array, which does have some peculiar
semantics, so leave it that way. */
#define ELF_NGREG (sizeof (struct user_regs_struct) / sizeof (elf_greg_t))
typedef elf_greg_t elf_gregset_t[ELF_NGREG];
...
```

***One way to fix it is to patch the NDK's sysroot/usr/include/sys/procfs.h before the build (do not sure about affecting the rest of bionic)***
```
...
typedef unsigned long elf_greg_t;
#if defined(__x86_64__)
#define ELF_NGREG (sizeof (struct user_regs_struct) / sizeof(elf_greg_t))
typedef elf_greg_t elf_gregset_t[ELF_NGREG];
#else
typedef elf_greg_t elf_gregset_t[NGREG];
#endif
...
```

***Kernel side***
```
kernel returns from arch/x86/kernel/ptrace.c
        case PTRACE_GETREGS:
          return copy_regset_to_user (
              child, task_user_regset_view (get_current ()),
              REGSET_GENERAL, 0, sizeof(struct user_regs_struct), datap);
```

and struct user_regs_struct comes from arch/x86/include/asm/user_64.h
```
    struct user_regs_struct
    {
      unsigned long r15;
      unsigned long r14;
      unsigned long r13;
      unsigned long r12;
      unsigned long bp;
      unsigned long bx;
      unsigned long r11;
      unsigned long r10;
      unsigned long r9;
      unsigned long r8;
      unsigned long ax;
      unsigned long cx;
      unsigned long dx;
      unsigned long si;
      unsigned long di;
      unsigned long orig_ax;
      unsigned long ip;
      unsigned long cs;
      unsigned long flags;
      unsigned long sp;
      unsigned long ss;
      unsigned long fs_base;
      unsigned long gs_base;
      unsigned long ds;
      unsigned long es;
      unsigned long fs;
      unsigned long gs;
    };
```

**Comment by enh-google** [comment]
you're saying our NGREG #define is wrong for x86-64?

**Comment by alex-curiou** [comment]
I'm saying that `typedef elf_greg_t elf_gregset_t[NGREG]` is inconsistent with its GDB usage for x86_64 kernel,
and gdbserver 8.3 from NDK is affected

**Comment by enh-google** [comment]
yeah, i think https://android-review.googlesource.com/c/platform/bionic/+/1419433 should fix it properly, by separating NGREG and ELF_NGREG from each other.

**Comment by alex-curiou** [comment]
thanks

**Comment by enh-google** [comment]
merged to the platform. i actually have no idea whether NDK r22 will include a header update, but at least if i assign this to r22 danalbert will see it :-)

**Comment by alex-curiou** [comment]
> merged to the platform. i actually have no idea whether NDK r22 will include a header update, but at least if i assign this to r22 danalbert will see it :-)

That's nice, the x86_64 world will become more stable now =)

**Comment by enh-google** [comment]
reopening just to ensure that it does get danalbert's attention as a possible for r22. otherwise we might be accidentally guaranteeing that it doesn't make it until r23 :-)

**Comment by DanAlbert** [comment]
Pretty sure I have a bug open reminding me to update the sysroot again before r22, so yes.
