### ISSUE TITLE
[BUG]use of undeclared identifier 'catopen'

### ISSUE THREAD

**Issue by vintonliu** [android/ndk#1348]
#### Description
Trying to build cxx shared library with CMake config like below:
CMAKE_CONFIG="-DANDROID=1 \
                -DCMAKE_SYSTEM_NAME=Android \
                -DANDROID_NDK=/Users/macos/android-ndk-r20 \
                -DCMAKE_TOOLCHAIN_FILE=/Users/macos/android-ndk-r20/build/cmake/android.toolchain.cmake \
                -DCMAKE_BUILD_TYPE=Debug \
                -DANDROID_ABI=armeabi-v7a \
                -DANDROID_NATIVE_API_LEVEL=19"

when building, got error below
/Users/macos/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/locale:3566:30: error: use of undeclared identifier 'catopen'
    catalog __cat = (catalog)catopen(__nm.c_str(), NL_CAT_LOCALE);
                             ^
/Users/macos/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/locale:3588:17: error: use of undeclared identifier 'catgets'
    char* __n = catgets(__cat, __set, __msgid, __ndflt.c_str());
                ^
/Users/macos/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/locale:3606:5: error: use of undeclared identifier 'catclose'
    catclose(__cat);
    ^
3 errors generated.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r20
* Build system: CMake
* Host OS: Mac
* ABI: armeabi-v7a, arm64-v8a
* NDK API level: 19
* Device API level:

**Comment by DanAlbert** [comment]
Assuming you figured this out, but those APIs aren't available until several releases after KitKat.
