### ISSUE TITLE
[question] Is find_library still needed for ndk libraries

### ISSUE THREAD

**Issue by Consti10** [android/ndk#1349]
I am wondering if the following code inside CMake files is still needed with the android ndk
Example for the android ndk 'log library'
```
find_library( log-lib
              log )
```

Since all my projects seem to build fine when directly linking with the android 'log' library for example.
Example code that shows the old way of linking to android libraries:
```
find_library( log-lib
             log )
target_link_libraries(TelemetryReceiver
        ${log-lib} )
```

Example code without find_library:
```
target_link_libraries(TelemetryReceiver
        log )
```

**Comment by DanAlbert** [comment]
It has never been needed.

**Comment by Consti10** [comment]
For example, why does the blueprint for an android studio native project still include it ?

**Comment by enh-google** [comment]
looking at `tools/base/build-system/integration-test/test-projects/prefabApp/app/src/main/cpp/CMakeLists.txt` it seems like some guy called danalbert did it in a CMakeLists.txt too :-)

**Comment by DanAlbert** [comment]
It's idiomatic for CMake (I guess; that's what the samples did and that's where I learned it from), but it's not required. CMake will `-l` link things that aren't `find_library`-esque, and the Android sysroot is available to the linker.
