### ISSUE TITLE
[question]Can not enable rtti exception for MinGW

### ISSUE THREAD

**Issue by ShyJ** [android/ndk#1351]
Hello,
I hava been trying to cross-compile my lib using CMake 3.18 + MinGW64 + NDK r21b for Android. 
I hava tried `ANDROID_CPP_FEATURES=rtti exception` and `ANDROID_STL_FORCE_FEATURES` to enable rtti and exceptions, but still show error ` error: cannot use 'try' with exceptions disabled`

In flags.make file generated by CMake i found` -frtti -fexceptions `flags were overwrited 
`CXX_FLAGS = -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -frtti -fexceptions  -fPIC -fno-rtti -fno-exceptions -std=c++14`
I removed `-fno-rtti -fexceptions` and compile successed. How can i enable the rtti and exceptions using option or variable of cmake.

**Environment:**
- NDK Version: NDK r21b 
- Build system: CMake with android.toolchain
- Host: Win 10

**Comment by DanAlbert** [comment]
I don't understand what you're trying to do. The NDK uses Clang. Mingw targets windows. RTTI and exceptions are enabled by default in our toolchain.

https://developer.android.com/studio/projects/install-ndk explains how to use CMake with the NDK.

**Comment by ShyJ** [comment]
Sorry for the unclear place. 
I used cmake-gui and android.toolchain.cmake file in ndk-r21b/build/cmake fold, and the cmake generator is `MinGW Makefiles`, then used mingw32-make.exe with powershell to compile the makefiles generated by cmake. 

This is the flags.make file 
```
# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.18

# compile CXX with D:/code/Android/NDK/android-ndk-r21b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
CXX_DEFINES = -DNOMINMAX

CXX_INCLUDES = -ID:\FacialAnimation\3rdparty\cereal -ID:\FacialAnimation\3rdparty\eigen-3.3.3 -ID:\FacialAnimation\3rdparty\plog -isystem D:\FacialAnimation\3rdparty\libs_android\opencv-4.1.0-ndk21-static\sdk\native\jni\include -isystem D:\FacialAnimation\3rdparty\libs_android\ncnn-20190908-armv7-ndk21\include\ncnn

CXX_FLAGS = -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -frtti -fexceptions  -fPIC -fno-rtti -fno-exceptions -std=c++14
```
The `-frtti -fexceptions` flags is added by `ANDROID_CPP_FEATURES=rtti exception`, and i don't know where the last `-fno-rtti -fno-exceptions` flags are from.

**Comment by ShyJ** [comment]
The command line is like this
```
cmake -DCMAKE_TOOLCHAIN_FILE=D:/code/NDK/android-ndk-r21b/build/cmake/android.toolchain.cmake \
-DANDROID_ABI="armeabi-v7a" \
-DOpenCV_DIR=D:/code/FacialAnimation/3rdparty/opencv-4.1.0-ndk21-static/sdk/native/jni \
-Dncnn_DIR=D:/code/FacialAnimation/3rdparty/libs_android/ncnn-20190908-armv7-ndk21/lib/cmake/ncnn \
-DANDROID_STL=c++_static \
-DANDROID_PLATFORM=android-16 \
-DANDROID_CPP_FEATURES="rtti exceptions" \
-G "MinGW Makefiles" ..
```
and opencv and ncnn libs ara compiled in the same way

**Comment by DanAlbert** [comment]
It looks like one of your CMake files is adding those flags. I just checked and we certainly don't unless you specifically request them. All the RTTI/exceptions flags would be added together if it was us: https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/build/cmake/android.toolchain.cmake;l=534;drc=46aa31c5003c17f4e170bf091d4cfa09128583ec

The fact `-fPIC` comes between the `-fexceptions` and `-fno-exceptions` to me indicates that this is something in your code and not ours. Also, we have tests that show this isn't a problem for the trivial case. We need a repro case to dig any further, but like I said I'm pretty sure these flags are just being added by some code in the project you're building. If you can make a repro case we're happy to reopen.
