### ISSUE TITLE
[DOC] bug: NDK r22 expected release date for Beta 1 Q3 2020

### ISSUE THREAD

**Issue by oscarbg** [android/ndk#1354]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
URL to the incorrect documentation (if the problem is that there is no documentation and it belongs on a new page, say so).

https://github.com/android/ndk/wiki

**Problem**
What's wrong? Does something need clarification/expansion? Is there a typo?

NDK r22 expected release date for Beta 1 should be Q4 2020

**Comment by enh-google** [comment]
sorry about that (both the delay, and the fact that the docs weren't updated to reflect it). i've updated the docs.

the good news is that we have made some good progress recently: https://android-review.googlesource.com/c/platform/ndk/+/1445351/1/docs/changelogs/Changelog-r22.md
