### ISSUE TITLE
[question] GWP ASAN special usecases

### ISSUE THREAD

**Issue by afjoseph** [android/ndk#1355]
Hey. Silly question, but does [GWP-ASAN](https://developer.android.com/ndk/guides/gwp-asan) catch more cases than regular [ASAN](https://github.com/google/sanitizers/wiki/AddressSanitizer)? I do realize GWP-ASAN is an LLVM technology and they use different underlying methodologies, but my question is from a practical point of view: does GWP-ASAN cover the cases that ASAN doesn't (For example, [leak sanitization](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer), which does not [cover Android](https://github.com/google/sanitizers/issues/1141#issuecomment-530980640)).

**Comment by enh-google** [comment]
GWP-ASan does not include leak detection (though there is separately work on making lsan work on Android: https://reviews.llvm.org/D85927

the main benefit of GWP-ASan is that it runs in the field, so you're getting coverage of actual use cases, not just whatever internal testing you do.
