### ISSUE TITLE
[question] Which part of the phone is monitored for the NDK Thermal API sensor?

### ISSUE THREAD

**Issue by theoctopusride** [android/ndk#1358]
In the docs for the NDK Thermal API/Android 11, I couldn't find which part is being monitored for temperature changes within the device. Since there are multiple parts in the phone that monitor temperature, do you know which one is specifically being monitored for the NDK Thermal API? Thank you!

**Comment by enh-google** [comment]
looks like wvw owns this API, so i've asked him for more details.

**Comment by enh-google** [comment]
https://source.android.com/devices/architecture/hidl/thermal-mitigation is the documentation for the OEM side of this.
