### ISSUE TITLE
[BUG]  It is not able to compile a simple test program.

### ISSUE THREAD

**Issue by HillalRoy** [android/ndk#1363]
#### Description
I also try to create new project with android native c++ template but the output is same
The Build output
```console
E:\dev\Android\SOUNIC\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at C:/Users/Hillal/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Users/Hillal/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/dev/Android/SOUNIC/app/.cxx/cmake/debug/arm64-v8a/CMakeFiles/CMakeTmp
    
    Run Build Command:"C:\Users\Hillal\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe" "cmTC_0bd68"
    [1/2] Building C object CMakeFiles/cmTC_0bd68.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_0bd68
    FAILED: cmTC_0bd68 
    cmd.exe /C "cd . && C:\Users\Hillal\AppData\Local\Android\Sdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android23 --gcc-toolchain=C:/Users/Hillal/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Hillal/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -D__STDC_FORMAT_MACROS  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/cmTC_0bd68.dir/testCCompiler.c.o  -o cmTC_0bd68  -latomic -lm && cd ."
    The system cannot find the path specified.
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt

```

#### Environment Details
* Android StudioVersion:  4.1
* NDK Version: 21.3.6528147
* Build system:  CMake c++17
* Host OS: Windows 10
* ABI: 'x86', 'x86_64',  'armeabi-v7a', 'arm64-v8a'

**Comment by DanAlbert** [comment]
Not enough information. We have tests that show that Clang and CMake work just fine. Nothing we can do without a repro case. Provide one and we'll reopen.

**Comment by hujianglang** [comment]
what is the solution ？

**Comment by DanAlbert** [comment]
Until we know what the problem is we don't know. Do you have a repro case you can upload?

**Comment by HillalRoy** [comment]
Sorry the problem was mine `pc env`.


I had a auto run script that script was deleted but forget to remove from `auto run`.


If you have same problem the goto the `registry` of command prompt and check auto run.

**Comment by hchanon** [comment]
To add details following HillalRoy comments, I hit the same problem and
fixed it by removing the AutoRun entry from "Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor" on my Windows machine.
The Autorun key was calling Conda. (from some Python tooling)
I did not investigate the mechanism that interfered with the CMake build.

**Comment by pnemonic78** [comment]
Try use latest NDK, e.g. 22.0.7026061

**Comment by dhirajnitk** [comment]
```
 FAILED: cmTC_1f121 
    cmd.exe /C "cd . && E:\Android\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi27 --gcc-toolchain=E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -O2  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/cmTC_1f121.dir/testCCompiler.c.o  -o cmTC_1f121  -latomic -lm && cd ."
```

>    clang: error: unable to execute command: program not executable
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     ninja: build stopped: subcommand failed.

**Comment by DanAlbert** [comment]
Same as before. We can't help without a repro case.

**Comment by dhirajnitk** [comment]
I can't build anything until  I put this on top
SET (CMAKE_C_COMPILER_WORKS 1)
SET (CMAKE_CXX_COMPILER_WORKS 1)


Now I  am getting  linking error without any trace for native .so files although it is building Cpp files successfully.

The app was building fine before on windows Android studio

**Comment by DanAlbert** [comment]
Can you upload a repro case?

**Comment by dhirajnitk** [comment]
I certainly feel its mixture of environment and ndk problem. I am facing this issue on 22.0.7026061, but if I migrate to 18.1.5063045, the issue disappears. Few days ago it was working fine on 22.0.7026061. I saw the cmd output & I dont see any corruption with conda. I have also commected the local ninja installation from path environment.


> 
>  C/C++ debug|arm64-v8a : CMake Error at E:/Android/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
>   The C compiler
> 
>     "E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: D:/Users/Dhiraj Kumar/Helloworld_android/app/.cxx/cmake/debug/arm64-v8a/CMakeFiles/CMakeTmp
>     
>     Run Build Command:"E:\Android\cmake\3.10.2.4988404\bin\ninja.exe" "cmTC_8b765"
>     [1/2] Building C object CMakeFiles/cmTC_8b765.dir/testCCompiler.c.o
>     [2/2] Linking C executable cmTC_8b765
>     FAILED: cmTC_8b765
>     cmd.exe /C "cd . && E:\Android\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android27 --gcc-toolchain=E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -O2  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/cmTC_8b765.dir/testCCompiler.c.o  -o cmTC_8b765  -latomic -lm && cd ."
>     clang: error: unable to execute command: program not executable
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     ninja: build stopped: subcommand failed.
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (project)
> 
> D:\Users\Dhiraj Kumar\Helloworld_android\app\src\main\cpp\CMakeLists.txt : C/C++ debug|arm64-v8a : Configuration failed.
> executing external native build for cmake D:\Users\Dhiraj Kumar\Helloworld_android\app\src\main\cpp\CMakeLists.txt

**Comment by dhirajnitk** [comment]
> D:\ndk-samples\hello-jni\app\src\main\cpp\CMakeLists.txt : C/C++ arm8Debug|armeabi-v7a : CMake Error at E:/Android/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
>   The C compiler
> 
>     "E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: D:/ndk-samples/hello-jni/app/.cxx/cmake/arm8Debug/armeabi-v7a/CMakeFiles/CMakeTmp
>     
>     Run Build Command:"E:\Android\cmake\3.10.2.4988404\bin\ninja.exe" "cmTC_f1d4a"
>     [1/2] Building C object CMakeFiles/cmTC_f1d4a.dir/testCCompiler.c.o
>     [2/2] Linking C executable cmTC_f1d4a
>     FAILED: cmTC_f1d4a 
>     cmd.exe /C "cd . && E:\Android\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi27 --gcc-toolchain=E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=E:/Android/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/cmTC_f1d4a.dir/testCCompiler.c.o  -o cmTC_f1d4a  -latomic -lm && cd ."
>     clang: error: unable to execute command: program not executable
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     ninja: build stopped: subcommand failed.
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt
> 
> 


Unable to build hello-jni from ndk_samples.

**Comment by DanAlbert** [comment]
> clang: error: unable to execute command: program not executable

Sounds like a permissions issue. Either the install went wrong or maybe your antivirus is getting in the way. This isn't something we've encountered so I'm fairly confident it isn't a problem with the package itself.

Guessing at a question you might be asking yourself: "But how could that be true if it did work once?" Presumably the not-full-rebuild didn't run whichever program is broken, which is why only the rebuild broke.

**Comment by dhirajnitk** [comment]
It works on 18.1.5063045 so there is something peculiar with android studio & ndk 22.xxxxxxx

**Comment by DanAlbert** [comment]
You probably need to file a Studio bug. If it's not something wrong with the NDK package itself we aren't the ones that can fix it. Given that everything works fine for me when I extract the package myself I don't think it's an issue with the package. If you have reason to believe otherwise, please file a new bug with that data.

**Comment by kirkaDev** [comment]
> It works on 18.1.5063045 so there is something peculiar with android studio & ndk 22.xxxxxxx

I had the same issue with ndkVersion "23.1.7779620" and with several CMake versions. After changing to 18.1.5063045 it becomes ok.

**Comment by rwilliams-janacare** [comment]
> To add details following HillalRoy comments, I hit the same problem and fixed it by removing the AutoRun entry from "Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor" on my Windows machine. The Autorun key was calling Conda. (from some Python tooling) I did not investigate the mechanism that interfered with the CMake build.

This fix worked for me. Appears related to https://stackoverflow.com/questions/66901281/the-conda-init-command-is-messing-up-my-cmd-startup-in-win10
