### ISSUE TITLE
Is Android NDK API forward-compatible?

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1373]
From https://developer.android.com/guide/topics/manifest/uses-sdk-element.html  -> android:minSdkVersion I understand that apps developed with lower SDK version will be able to install on higher SDK version and work. We call this forward compatibility.

Similarly is it guaranteed that apps developed with older NDK API level  will be able to compile and work on higher NDK API Level?

I mean, if I link my libraries against libraries present in androidndk\platforms\android-23, is there any guarantee that my libraries will definitely work on platforms with API level > 23?

**Comment by enh-google** [comment]
yes, the guarantee is the same as for Java. CTS covers C API too, not just Java. (though obviously there are gaps in test coverage for both.)
