### ISSUE TITLE
migrate from included vulkan validation layers to releases on github

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1374]
The NDK includes the vulkan validation layer (VVL) source. In the past this was used for building VVL binaries for Android. However, as of NDK r21, LunarG now releases VVL binaries for Android on the VVL [GitHub page](https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases), and these VVL releases are referenced from the [NDK documentation](https://developer.android.com/ndk/guides/graphics/validation-layer) as the binaries to use.

Because of this, the VVL source in the NDK should be removed to avoid confusion as its stale and no longer recommended for building layers.

The removal of VVL source should be done in two steps:

- [x] Remove the vulkan validation steps from the NDK build scripts
- [x] Remove the actual validation layer source branch from the NDK
- [x] Add an `Android.mk` in place that throws an error for anyone attempting to use the layers from the NDK.

**Comment by Zingam** [comment]
If Vulkan stuff is removed from the NDK. I was wondering you might provide a script for automatically downloading these for lazy people? Or a copy&paste sample how to do it with Gradle. Or maybe install them via Android Studio SDK manager? Or make AAR along with https://github.com/android/ndk/issues/945#issue-427307031 and all headers?
Are the headers tied to the platform or are just any headers?

**Comment by DanAlbert** [comment]
@cnorthrop, do you have docs for this?

I think an AAR for these is a good idea too. I believe that's waiting for me to finish the tools to build those for non-AGP projects (the work is basically done for ndkports but has been stalled by things outside our control for a while now).

(closing because the work I'd planned to do here is done; will reopen if we identify more work that belongs here)

**Comment by DanAlbert** [comment]
I'm late in following up, but https://developer.android.com/ndk/guides/graphics/validation-layer look to be very good docs for this, including how to integrate them from the github release.
