### ISSUE TITLE
Where is androideabi-gcc (arm) | ndkr21

### ISSUE THREAD

**Issue by raifpy** [android/ndk#1375]
My $ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin output;

arm-linux-androideabi-addr2line
arm-linux-androideabi-ar
arm-linux-androideabi-as
arm-linux-androideabi-c++filt
arm-linux-androideabi-dwp
arm-linux-androideabi-elfedit
arm-linux-androideabi-gprof
arm-linux-androideabi-ld
arm-linux-androideabi-ld.bfd
arm-linux-androideabi-ld.gold
arm-linux-androideabi-nm
arm-linux-androideabi-objcopy
arm-linux-androideabi-objdump
arm-linux-androideabi-ranlib
arm-linux-androideabi-readelf
arm-linux-androideabi-size
arm-linux-androideabi-strings
arm-linux-androideabi-strip

i can't find androideabi-gcc anyware! (find | grep gcc)
Where is this :)

**Comment by enh-google** [comment]
GCC was removed in NDK r18. the NDK is clang-only since then.

https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#ndk-r18

**Comment by enh-google** [comment]
(if you're maintaining a custom build system, you probably want to read https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md.)
