### ISSUE TITLE
[BUG] xfatal error: error in backend: Error while trying to spill LR from class GPR: Cannot scavenge register without an emergency spill slot!

### ISSUE THREAD

**Issue by guolinaileen** [android/ndk#1376]
fatal error: error in backend: Error while trying to spill LR from class GPR: Cannot scavenge register without an emergency spill slot!
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
Target: arm-unknown-linux-android23
Thread model: posix
InstalledDir: third_party/android/ndk/stable/toolchains/llvm/prebuilt/linux-x86_64/bin/../real-bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/SkSLByteCode-bea05c.cpp
clang: note: diagnostic msg: /tmp/SkSLByteCode-bea05c.sh
clang: note: diagnostic msg:

********************

Internal bug report. b/172773885
I added a .txt extension to both files, so that I could attach them.

[SkSLByteCode-bea05c.cpp.txt](https://github.com/android/ndk/files/5562636/SkSLByteCode-bea05c.cpp.txt)
[SkSLByteCode-bea05c.sh.txt](https://github.com/android/ndk/files/5562638/SkSLByteCode-bea05c.sh.txt)

#### Environment Details

* NDK Version: 23.
* Build system: ndk-build? CMake? Standalone toolchain? Custom? (If gradle, file
  a bug against Android Studio as specified above.) ndk-build
* Host OS: Windows, Mac, or Linux? Which Linux?  gLinux
* ABI: Armeabi-v7a
* NDK API level: 23

**Comment by DanAlbert** [comment]
> NDK Version: 23.

If you could share the source for that it'd save us a lot of effort ;)

Guessing r21d based on the path. Looks the same as https://github.com/android/ndk/issues/1377
