### ISSUE TITLE
creating High Priority Threads (suitable for DAWs/Audio/Metronome's and such)

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1378]
First: The workaround described by @enh-google seems to work.
I have also validated that when detaching the VM and then re-attaching it the Thread priority set by either `android.os.Process#setThreadPriority()` and `Thread.currentThread().setPriority()` is persistent.
Here is the cpp code:
```
// calls android.os.Process.setThreadPriority()
    static void setProcessThreadPriority(JNIEnv* env,int wantedPriority){
        jclass jcProcess = env->FindClass("android/os/Process");
        jmethodID jmSetThreadPriority=env->GetStaticMethodID(jcProcess,"setThreadPriority","(I)V");
        env->CallStaticVoidMethod(jcProcess,jmSetThreadPriority,(jint)wantedPriority);
    }
 // calls android.os.Process.getThreadPriority(android.os.Process.myTid())
    static void printProcessThreadPriority(JNIEnv* env){
        jclass jcProcess = env->FindClass("android/os/Process");
        jmethodID jmGetThreadPriority=env->GetStaticMethodID(jcProcess,"getThreadPriority","(I)I");
        jmethodID jmMyTid=env->GetStaticMethodID(jcProcess,"myTid","()I");
        jint myTid=env->CallStaticIntMethod(jcProcess,jmMyTid);
        jint currentPrio=env->CallStaticIntMethod(jcProcess,jmGetThreadPriority,(jint)myTid);
        LOGD("printProcessThreadPriority %d",currentPrio);
    }
```
And a short example code to test it:
```
 static void doSomething2(JavaVM* jvm,int prio) {
        JNIEnv* env=attachThread(jvm);
        printProcessThreadPriority(env);
        setProcessThreadPriority(env,prio);
        printProcessThreadPriority(env);
        detachThread(jvm);

        env=attachThread(jvm);
        printProcessThreadPriority(env);
        detachThread(jvm);
    }
 static void test(JNIEnv* env){
        JavaVM* jvm;
        env->GetJavaVM(&jvm);
        std::thread* thread1=new std::thread(doSomething2,jvm,-20);
    }
```
This produces the following output:
```
printProcessThreadPriority -10
printProcessThreadPriority -20
printProcessThreadPriority -20
```
Leading me to believe:
a) when a ndk thread is created it has a default priority of -10 ( which is pretty high) 
b) you can attach & detach the JVM to change the priority of a NDK thread
c) even increasing the priority to -20 (highest) works , but is not recommended
[Full source code](https://github.com/Consti10/LiveVideo10ms/blob/master/VideoTelemetryShared/Helper/NDKThreadHelper.hpp)

_Originally posted by @Consti10 in https://github.com/android/ndk/issues/1255#issuecomment-627936683_

can this be sufficient to create a high priority thread from NDK or would more work need to be done?

**Comment by Consti10** [comment]
Correct, that's all you need to create a high priority thread.

**Comment by Consti10** [comment]
Here is my current implementation:
https://github.com/Consti10/LiveVideo10ms/blob/5c00a4c586d8ee187b1d3cd47f123a86bf375aa3/Shared/src/main/cpp/NDKHelper/NDKThreadHelper.hpp

**Comment by mgood7123** [comment]
> Correct, that's all you need to create a high priority thread.

and this high priority thread (given the correct priority number) is say equivalent to AAudio's data callback thread, right?

**Comment by Consti10** [comment]
> and this high priority thread (given the correct priority number) is say equivalent to AAudio's data callback thread, right?

Yes, and using higher priority threads for Audio, Networking and video decoding can make a difference.
Note that the Android system tries really hard to reduce power, which often conflicts with real-time applications.
Sustained performance is a really good concept, but supported on few devices. (Since gvr was dropped there is even less incentive for vendors to implement it).
Regarding your questions 2 and 3 I'd recommend asking this in a new Thread (or just testing it yourself)

**Comment by enh-google** [comment]
(no bug here.)
