### ISSUE TITLE
[DOC] AAudioStreamBuilder_setDataCallback thread priority

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1379]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
URL to the incorrect documentation (if the problem is that there is no documentation and it belongs on a new page, say so).

https://developer.android.com/ndk/reference/group/audio#group___audio_1gae442c5d1bbeb317878bc74569599295a

**Problem**
"This callback function will be called on a real-time thread owned by AAudio. See AAudioStream_dataCallback for more information."

the term `real-time` is unclear if the thread in question is a High Priority thread (suitable for DAW/Metronome use) or not

**Comment by enh-google** [comment]
i've forwarded this to @philburk who will know more.

**Comment by philburk** [comment]
The callback threads generally do have higher priority and better real-time properties than normal threads. This may vary by device.

I have improved the docs with ag/13122757

It now says:
> This callback function will be called on a real-time thread owned by AAudio.
> The low latency streams may have callback threads with higher priority than normal streams.

**Comment by mgood7123** [comment]
> The callback threads generally do have higher priority and better real-time properties than normal threads. This may vary by device.
> 
> I have improved the docs with ag/13122757
> 
> The docs are generated from the AAudio.h header file. It now says:
> 
> > This callback function will be called on a real-time thread owned by AAudio.
> > The low latency streams may have callback threads with higher priority than normal streams.
