### ISSUE TITLE
Linking gRPC libraries with Qt5.12.9, built in CentOS7 with Android NDK 21.1.6352462, clang++

### ISSUE THREAD

**Issue by toshi555** [android/ndk#1380]
Is grpc_csharp_ext.so needed to use gRPC in Android?

I am trying to use gRPC in Android tablet with Qt5.12.9 which was built in CentOS7.  I was able to built an executable, but as soon as I launch it in the Android, it crashes right away even with a simple Qt Gui application like below.  However, if I exclude the 'grpc_csharp_ext.so' library, the simple application will be launched ok.  The problem here is when I exclude the library, the real application I am building has a lot of linking errors, saying undefined reference to gRPC.. ....  So, I think the library has to be linked.  I made sure there is only one 'grpc_csharp_ext.so' library in the machine.  But is there any way to find out what is crashing the application?  Or, is there any work around to launch it?  I have inserted my simple application that crashes the gui right away below.  Am I doing something wrong?

OS: CentOS 7
Qt: ver. 5.12.9
Android NDK: 21.1.6352462
gRPC version: 1.33.2
Boost version: 1.74.0

// BuildQt.sh
mkdir Qt-5.12.9
cd Qt-5.12.9
git clone git://code.qt.io/qt/qt5.git
cd qt5
git checkout 5.12.9
perl init-repository
export LLVM_INSTALL_DIR=/usr/llvm
cd ..
mkdir qt5-build
cd qt5-build/
../qt5/configure -xplatform android-clang --disable-rpath -nomake tests -nomake examples -android-ndk   $HOME/Android/Sdk/ndk/21.1.6352462    -android-sdk  $HOME/Android/Sdk   -android-ndk-host linux-x86_64 -skip qttranslations -skip qtserialport -no-warnings-are-errors --c++std=c++14  -qt-zlib -qt-libpng  --opensource -optimized-qmake
make -j2
sudo make install

// BuildBoostForAndroid.sh
#!/bin/bash

version=1.74.0
echo "Building boost $version..."

set -eu

toolchain=$PWD/toolchain
if [ ! -d "$toolchain" ]; then
  echo "Building toolchain..."
  $ANDROID_NDK_ROOT/build/tools/make-standalone-toolchain.sh \
      --arch=arm --platform=android-21 \
      --install-dir="$toolchain" \
      --toolchain=arm-linux-androideabi-clang \
      --use-llvm --stl=libc++
else
  echo "Toolchain already built"
fi

dir_name=boost_$(sed 's#\.#_#g' <<< $version)
archive=${dir_name}.tar.bz2
if [ ! -f "$archive" ]; then
  wget -O $archive "https://dl.bintray.com/boostorg/release/$version/source/$archive"
else
  echo "Archive $archive already downloaded"
fi

echo "Extracting..."
if [ ! -d "$dir_name" ]; then
  tar xf $archive
else
  echo "Archive $archive already unpacked into $dir_name"
fi
cd $dir_name

echo "Generating config..."
user_config=tools/build/src/user-config.jam
rm -f $user_config
cat <<EOF > $user_config
import os ;
using clang : android
:
"$toolchain/bin/clang++"
:
<archiver>$toolchain/bin/arm-linux-androideabi-ar
<ranlib>$toolchain/bin/arm-linux-androideabi-ranlib
;
EOF

echo "Bootstrapping..."
./bootstrap.sh #--with-toolset=clang

echo "Building..."
./b2 -j32 \
    --with-atomic \
    --with-chrono \
    --with-container \
    --with-date_time \
    --with-exception \
    --with-fiber \
    --with-filesystem \
    --with-graph \
    --with-graph_parallel \
    --with-iostreams \
    --with-locale \
    --with-log \
    --with-math \
    --with-mpi \
    --with-program_options \
    --with-random \
    --with-regex \
    --with-serialization \
    --with-system \
    --with-test \
    --with-thread \
    --with-timer \
    --with-type_erasure \
    --with-wave \
    toolset=clang-android \
    architecture=arm \
    variant=release \
    --layout=versioned \
    target-os=android \
    threading=multi \
    threadapi=pthread \
    link=static \
    runtime-link=static \

echo "Running ranlib on libraries..."
libs=$(find "bin.v2/libs/" -name '*.a')
for lib in $libs; do
  "$toolchain/bin/arm-linux-androideabi-ranlib" "$lib"
done

echo "Done!"

// gRPC-Build1.sh
rm -fr .build
mkdir .build
cd .build
export ANDROID_NDK=$HOME/Android/Sdk/ndk/21.1.6352462
cmake ../grpc \
 -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake\
 -D_gRPC_PLATFORM_ANDROID=ON \
 -DgRPC_BUILD_CODEGEN=OFF \
 -DANDROID_ABI=armeabi-v7a\
 -DANDROID_PLATFORM=android-26\
 -DANDROID_STL=c++_static\
 -DRUN_HAVE_STD_REGEX=0\
 -DRUN_HAVE_POSIX_REGEX=0\
 -DRUN_HAVE_STEADY_CLOCK=0\
 -DCMAKE_BUILD_TYPE=Release
cmake --build . --target grpc++

// gRPC-Build2.sh
cd .build
export ANDROID_NDK=$HOME/Android/Sdk/ndk/21.1.6352462
cmake ../grpc \
 -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake\
 -DgRPC_BUILD_CODEGEN=OFF \
 -DANDROID_ABI=armeabi-v7a\
 -DANDROID_PLATFORM=android-26\
 -DCMAKE_BUILD_TYPE=Release
cmake --build .

// main.cpp
#include <QApplication>
#include <QLineEdit>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QLineEdit* lineEdit = new QLineEdit();
    lineEdit->resize(400,100);
    lineEdit->setText("LineEdit TEST!!!!!!!!!!!!!!!");
    lineEdit->show();
    return app.exec();
}

// build script
rm -fr build-Android-CLang21-1
mkdir build-Android-CLang21-1
cd build-Android-CLang21-1

/usr/local/Qt-5.12.9/bin/qmake ../TestGrpc.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" ANDROID_ABIS="armeabi-v7a"

$HOME/Android/Sdk/ndk/21.1.6352462/prebuilt/linux-x86_64/bin/make -f ./Makefile qmake_all

make -j2

// run script
cd  build-Android-CLang21-1
$HOME/Android/Sdk/ndk/21.1.6352462/prebuilt/linux-x86_64/bin/make INSTALL_ROOT=$HOME/GrpcTesting/build-Android-CLang21-1 install
cd ..

/usr/local/Qt-5.12.9/bin/androiddeployqt --input $HOME/GrpcTesting/build-Android-CLang21-1/android-libTestGrpc.so-deployment-settings.json --output $HOME/GrpcTesting/GrpcExperiments/build-Android-CLang21-1 --android-platform android-30 --jdk /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.272.b10-1.el7_9.x86_64 --gradle

/usr/local/Qt-5.12.9/bin/androiddeployqt --verbose --output build-Android-CLang21-1 --no-build --input build-Android-CLang21-1/android-libTestGrpc.so-deployment-settings.json --gradle --reinstall --device R52MA11GJDH

//TestGrpc.pro
QT += widgets
QT += core
QT += gui

CONFIG += c++14

DEFINES += BUILD_ZLIB

INCLUDEPATH += /usr/local/include/boost
INCLUDEPATH += $HOME/boost_1_74_0/boost_1_74_0

SOURCES += main.cpp
QML_DESIGNER_IMPORT_PATH =

qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

ANDROID_ABIS = armeabi-v7a

QMAKE_CXX_FLAGS += -U_FORTIFY_SOURCE -DFORTIFY_SOURCE=2

LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/base
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/container
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/debugging
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/flags
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/hash
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/numeric
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/random
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/status
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/strings
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/synchronization
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/time
LIBS += -L$HOME/grpc/.build/third_party/abseil-cpp/absl/types
LIBS += -L$HOME/grpc/.build/third_party/cares/cares/lib
LIBS += -L$HOME/grpc/.build/third_party/protobuf
LIBS += -L$HOME/grpc/.build/third_party/re2
LIBS += -L$HOME/grpc/.build/third_party/boringssl-with-bazel
LIBS += -L$HOME/grpc/.build/third_party/zlib
LIBS += -L$HOME/grpc/.build
#####################################################

LIBS += -labsl_dynamic_annotations
LIBS += -labsl_spinlock_wait
LIBS += -labsl_log_severity
LIBS += -labsl_raw_logging_internal
LIBS += -labsl_throw_delegate
LIBS += -labsl_base
LIBS += -labsl_malloc_internal
LIBS += -labsl_exponential_biased
LIBS += -labsl_periodic_sampler
LIBS += -labsl_scoped_set_env
LIBS += -labsl_hashtablez_sampler
LIBS += -labsl_raw_hash_set
LIBS += -labsl_debugging_internal
LIBS += -labsl_stacktrace
LIBS += -labsl_demangle_internal
LIBS += -labsl_symbolize
LIBS += -labsl_examine_stack
LIBS += -labsl_leak_check_disable
LIBS += -labsl_failure_signal_handler
LIBS += -labsl_leak_check
LIBS += -labsl_flags_marshalling
LIBS += -labsl_flags_program_name
LIBS += -labsl_flags_config
LIBS += -labsl_flags_registry
LIBS += -labsl_flags_internal
LIBS += -labsl_flags
LIBS += -labsl_flags_usage_internal
LIBS += -labsl_flags_usage
LIBS += -labsl_flags_parse
LIBS += -labsl_city
LIBS += -labsl_hash
LIBS += -labsl_int128
LIBS += -labsl_random_internal_randen_slow
LIBS += -labsl_random_internal_distribution_test_util
LIBS += -labsl_random_internal_randen_hwaes_impl
LIBS += -labsl_random_internal_randen_hwaes
LIBS += -labsl_random_internal_seed_material
LIBS += -labsl_random_internal_randen
LIBS += -labsl_random_seed_gen_exception
LIBS += -labsl_random_internal_pool_urbg
LIBS += -labsl_random_seed_sequences
LIBS += -labsl_random_distributions
LIBS += -labsl_status
LIBS += -labsl_strings_internal
LIBS += -labsl_strings
LIBS += -labsl_str_format_internal
LIBS += -labsl_cord
LIBS += -labsl_graphcycles_internal
LIBS += -labsl_synchronization
LIBS += -labsl_time_zone
LIBS += -labsl_civil_time
LIBS += -labsl_time
LIBS += -labsl_bad_optional_access
LIBS += -labsl_bad_variant_access
LIBS += -labsl_bad_any_cast_impl
LIBS += -lcares
LIBS += -lprotobuf
LIBS += -lprotoc
LIBS += -lprotobuf-lite
LIBS += -lre2
LIBS += -lcrypto
LIBS += -lssl
##LIBS += -lz
LIBS += -laddress_sorting
LIBS += -lgpr
LIBS += -lupb
LIBS += -lgrpc
LIBS += -lgrpc++
LIBS += -lgrpc_unsecure
LIBS += -lgrpc++_alts
LIBS += -lgrpc++_unsecure
LIBS += -lgrpc_plugin_support
LIBS += -lgrpc_csharp_ext

#####################################################

android: {
    message("building for android")
    system(cmake $$PWD)
    QMAKE_LFLAGS += -nostdlib++
    QT += androidextras
    DISTFILES += \
    android/AndroidManifest.xml \
    android/build.gradle \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew \
    android/gradlew.bat \
    android/res/values/libs.xml \
    android/res/drawable/logo.png

    INCLUDEPATH += /usr/local/include

    equals(ANDROID_TARGET_ARCH, armeabi-v7a) {
    message("building for armeabi-v7a")

    $$PWD/android/lib/libgrpc++.a
    $$PWD/android/lib/libgrpc.a
    $$PWD/android/lib/libgpr.a
    $$PWD/android/lib/libcrypto.a
    $$PWD/android/lib/libssl.a
    $$PWD/android/lib/libz.a
    $$PWD/android/lib/libcares.a
    $$PWD/android/lib/libprotobuf.a
    $$PWD/android/lib/libaddress_sorting.a
    $$PWD/android/lib/libgrpc++_unsecure.a
    $$PWD/android/lib/libgrpc++_cronet.a
    $$PWD/android/lib/libgrpc_unsecure.a
    $$PWD/android/lib/libgrpc_plugin_support.a
    $$PWD/android/lib/libgrpc_cronet.a
    $$PWD/android/lib/libgrpc_csharp_ext.so
    $$PWD/android/lib/libprotocd.a
    $$PWD/android/lib/libprotobuf-lited.a

    }
    equals(ANDROID_TARGET_ARCH, arm64-v8a) {
    message("building for arm64-via")

    $$PWD/android/lib64/libgrpc++.a
    $$PWD/android/lib64/libgrpc.a
    $$PWD/android/lib64/libgpr.a
    $$PWD/android/lib64/libcrypto.a
    $$PWD/android/lib64/libssl.a
    $$PWD/android/lib64/libz.a
    $$PWD/android/lib64/libcares.a
    $$PWD/android/lib64/libprotobuf.a
    $$PWD/android/lib64/libaddress_sorting.a
    $$PWD/android/lib64/libgrpc++_unsecure.a
    $$PWD/android/lib64/libgrpc++_cronet.a
    $$PWD/android/lib64/libgrpc_unsecure.a
    $$PWD/android/lib64/libgrpc_plugin_support.a
    $$PWD/android/lib64/libgrpc_cronet.a
    $$PWD/android/lib64/libgrpc_csharp_ext.so
    $$PWD/android/lib64/libprotocd.a
    $$PWD/android/lib64/libprotobuf-lited.a

    LIBS += -L$$PWD/android/lib64 -lgpr -lgrpc -lgrpc_unsecure -lgrpc_plugin_support -lgrpc++ -lgrpc++_unsecure -lgrpc++_cronet  -lgrpc_cronet -lc -lcrypto -lssl -lprotobuf -lprotocd -lgrpc_csharp_ext  -lcares  -laddress_sorting -lz

    }

    equals(ANDROID_TARGET_ARCH, x86)  {
    message("building for x86")

    $$PWD/android/libx86/libgrpc++.a
    $$PWD/android/libx86/libgrpc.a
    $$PWD/android/libx86/libgpr.a
    $$PWD/android/libx86/libcrypto.a
    $$PWD/android/libx86/libssl.a
    $$PWD/android/libx86/libz.a
    $$PWD/android/libx86/libcares.a
    $$PWD/android/libx86/libprotobuf.a
    $$PWD/android/libx86/libaddress_sorting.a
    $$PWD/android/libx86/libgrpc++_unsecure.a
    $$PWD/android/libx86/libgrpc++_cronet.a
    $$PWD/android/libx86/libgrpc_unsecure.a
    $$PWD/android/libx86/libgrpc_plugin_support.a
    $$PWD/android/libx86/libgrpc_cronet.a
    $$PWD/android/libx86/libgrpc_csharp_ext.so
    $$PWD/android/libx86/libprotocd.a
    $$PWD/android/libx86/libprotobuf-lited.a

    LIBS += -L$$PWD/android/libx86 -lgpr -lgrpc -lgrpc_unsecure -lgrpc_plugin_support -lgrpc++ -lgrpc++_unsecure -lgrpc++_cronet  -lgrpc_cronet -lc -lcrypto -lssl -lprotobuf -lprotocd -lgrpc_csharp_ext  -lcares  -laddress_sorting -lz

    }

    equals(ANDROID_TARGET_ARCH, x86_64)  {
    message("building for x86_64")

    $$PWD/android/libx86_64/libgrpc++.a
    $$PWD/android/libx86_64/libgrpc.a
    $$PWD/android/libx86_64/libgpr.a
    $$PWD/android/libx86_64/libcrypto.a
    $$PWD/android/libx86_64/libssl.a
    $$PWD/android/libx86_64/libz.a
    $$PWD/android/libx86_64/libcares.a
    $$PWD/android/libx86_64/libprotobuf.a
    $$PWD/android/libx86_64/libaddress_sorting.a
    $$PWD/android/libx86_64/libgrpc++_unsecure.a
    $$PWD/android/libx86_64/libgrpc++_cronet.a
    $$PWD/android/libx86_64/libgrpc_unsecure.a
    $$PWD/android/libx86_64/libgrpc_plugin_support.a
    $$PWD/android/libx86_64/libgrpc_cronet.a
    $$PWD/android/libx86_64/libgrpc_csharp_ext.so
    $$PWD/android/libx86_64/libprotocd.a
    $$PWD/android/libx86_64/libprotobuf-lited.a

    LIBS += -L$$PWD/android/libx86_64 -lgpr -lgrpc -lgrpc_unsecure -lgrpc_plugin_support -lgrpc++ -lgrpc++_unsecure -lgrpc++_cronet  -lgrpc_cronet -lc -lcrypto -lssl -lprotobuf -lprotocd -lgrpc_csharp_ext  -lcares  -laddress_sorting -lz

    }
}

**Comment by enh-google** [comment]
> Is grpc_csharp_ext.so needed to use gRPC in Android?

that's a question for the grpc folks, not an NDK question.
