### ISSUE TITLE
AAudio callback thread implementation

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1381]
in relation to https://github.com/android/ndk/issues/1255#issuecomment-627936683 , would it be possible to mimic AAudio's callback by

creating a new pthread

setting its priority to say -20

and then for example

```C++
void main_audio_thread(void * arg) {

    Data * data = reinterpret_cast(Data*>(arg);

    void * buffer = allocateBufferWithAppropriateFormat(data);

    while(data->running) {

        process(data->stream, buffer, data->frames);

        AAudiostream_write(data->stream, buffer, data->frames);

    }

    delete[] buffer;
}
```

**Comment by enh-google** [comment]
you're probably better off with these questions on the Oboe github where you'll have the audio folks like @philburk to talk to...

**Comment by philburk** [comment]
I'm here too. The above code should work. But you cannot get the same kind of real-time thread that the AAudio callback runs as. Also the AAudio stream cannot get a FAST track on some systems unless you use the callback.

But I suspect latency is not a big issue for you because you are processing a stream to generate audio.
Note that you should check the return value from the write to detect disconnected or broken streams.

**Comment by mgood7123** [comment]
> I'm here too. The above code should work. But you cannot get the same kind of real-time thread that the AAudio callback runs as. Also the AAudio stream cannot get a FAST track on some systems unless you use the callback.
> 
> But I suspect latency is not a big issue for you because you are processing a stream to generate audio.
> Note that you should check the return value from the write to detect disconnected or broken streams.

oh ok

**Comment by mgood7123** [comment]
> I'm here too. The above code should work. But you cannot get the same kind of real-time thread that the AAudio callback runs as. Also the AAudio stream cannot get a FAST track on some systems unless you use the callback.
> 
> But I suspect latency is not a big issue for you because you are processing a stream to generate audio.
> Note that you should check the return value from the write to detect disconnected or broken streams.

how might I go about... getting latency accurate results using the callback thread, for a metronome? as most DAWS manually start up a RT thread and measure latency from in the RT thread, and use that to sync tempo and metronome (I may be wrong tho)
