### ISSUE TITLE
sample-accurate timing

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1382]
is it possible to have a sample-accurate timing using the AAudio data callback?

for purposes such as DAW use and step sequencer/piano roll use

if so, how might this be set up and what might it look like?

**Comment by enh-google** [comment]
@philburk

**Comment by mgood7123** [comment]
> @philburk

rip

welp in his absence, it is possible but you need a tempo grid

a basic implementation is

```
class TempoGrid {
public:
    int beats_per_minute;
    int notes_per_bar;
    int sample_rate;
    int samples_per_bar;
    int samples_per_note;
    float notes_per_second;
    bool mapped;

    static inline void map_tempo_to_frame(TempoGrid &grid) {
        grid.samples_per_note = grid.sample_rate * 60 / grid.beats_per_minute;
        grid.samples_per_bar = grid.samples_per_note * grid.notes_per_bar;
        grid.notes_per_second = (float) grid.sample_rate/ (float) grid.samples_per_note;
        grid.mapped = true;
    }

    TempoGrid(int beats_per_minute = 120, int notes_per_bar = 4, int sample_rate = 48000);

    bool sample_matches_samples_per_note(uint64_t sample);
};

TempoGrid::TempoGrid(int beats_per_minute, int notes_per_bar, int sample_rate) {
    mapped = false;
    this->beats_per_minute = beats_per_minute;
    this->notes_per_bar = notes_per_bar;
    this->sample_rate = sample_rate;
}

bool TempoGrid::sample_matches_samples_per_note(uint64_t sample) {
    return sample == samples_per_note || (sample % samples_per_note) == 0;
}
```

and then in your data callback

```
if (engineFrame == 0 || tempoGrid.sample_matches_samples_per_note(engineFrame)) {
    playNote(audioBuffer);
}
```

where `engineFrame` is increased in accordance to each frame of audio data written to AAudio's output buffer

**Comment by philburk** [comment]
The audio stream is isochronous. That means that each frame corresponds to a fixed unit of time.
So "sample accurate" output simply involves placing sound events on the proper frame.
That is entirely up to the application.   Here is an example of some pseudo-code that places an impulse sound exactly once per period in a mono stream.

    static int64_t frameCounter = 0;
    for (int i = 0; i < numFrames; i++) {
        // Play a tick on a regular period.
        *output++ = ((frameCounter % tickPeriod) == 0) ? 1.0 : 0.0;
        frameCounter++;
    }
