### ISSUE TITLE
[BUG] gsm0610_lpc.o crash err

### ISSUE THREAD

**Issue by kyoungjib** [android/ndk#1384]
C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/spandsp/saturated.h:88:22: note: include the header <math.h> or explicitly provide a declaration for 'lrint'
  PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
  Stack dump:
  0.	Program arguments: C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gsm_jni/spandsp/gsm0610_lpc.o.d -target armv7-none-linux-androideabi16 -fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes --sysroot C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -D_FORTIFY_SOURCE=2 -fpic -march=armv7-a -O2 -DNDEBUG -IC:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/spandsp -IC:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp -IC:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni -O3 -DANDROID -O3 -Wformat -Werror=format-security -c C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/gsm0610_lpc.c -o C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gsm_jni/spandsp/gsm0610_lpc.o 
  1.	<eof> parser at end of file
  2.	Code generation
  3.	Running pass 'Function Pass Manager' on module 'C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/gsm0610_lpc.c'.
  4.	Running pass 'Greedy Register Allocator' on function '@gsm0610_lpc_analysis'
   #0 0x00007ff7caa3d450 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x29fd450)
   #1 0x00007ff7caa40059 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x2a00059)
   #2 0x00007ff7c96fee57 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x16bee57)
   #3 0x00007ff7c96faa9f (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x16baa9f)
   #4 0x00007ff7caa27a50 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x29e7a50)
   #5 0x00007ff7c96fa0ac (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x16ba0ac)
   #6 0x00007ff7c877b9d2 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x73b9d2)
   #7 0x00007ff7c82619a4 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x2219a4)
   #8 0x00007ff7c8267fb3 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x227fb3)
   #9 0x00007ff7c82621a2 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x2221a2)
  #10 0x00007ff7c919e731 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x115e731)
  #11 0x00007ff7c94b8772 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1478772)
  #12 0x00007ff7ca701653 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x26c1653)
  #13 0x00007ff7c9420f14 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x13e0f14)
  #14 0x00007ff7c86a2de0 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x662de0)
  #15 0x00007ff7c86fae13 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x6bae13)
  #16 0x00007ff7c8046205 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x6205)
  #17 0x00007ff7c8044481 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x4481)
  #18 0x00007ff7c9264eb6 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1224eb6)
  #19 0x00007ff7c8569c41 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x529c41)
  #20 0x00007ff7c9264989 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1224989)
  #21 0x00007ff7c866f7e9 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x62f7e9)
  #22 0x00007ff7c866fcb5 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x62fcb5)
  #23 0x00007ff7c8682076 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x642076)
  #24 0x00007ff7c8043edd (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x3edd)
  #25 0x00007ff7c8041395 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1395)
  #26 0x00007ff7c80414c8 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x14c8)
  #27 0x00007ff8f0fe7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
  #28 0x00007ff8f113cec1 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4cec1)
  clang: error: clang frontend command failed due to signal (use -v to see invocation)
  Android (6875598, based on r399163b) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
  Target: armv7-none-linux-android16
  Thread model: posix
  InstalledDir: C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin
  clang: note: diagnostic msg: 
  ********************
  
  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
  Preprocessed source(s) and associated run script(s) are located at:
  clang: note: diagnostic msg: C:\Users\devpc\AppData\Local\Temp\gsm0610_lpc-38ae20.c
  clang: note: diagnostic msg: C:\Users\devpc\AppData\Local\Temp\gsm0610_lpc-38ae20.sh
  clang: note: diagnostic msg: 
  
  ********************
  make: *** [C:/Android/sdk/ndk-bundle/build//../build/core/build-binary.mk:476: C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gsm_jni/spandsp/gsm0610_lpc.o] Error 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
15 actionable tasks: 2 executed, 13 up-to-date

**Comment by stephenhines** [comment]
@kyoungjib Can you attach the files that it created to this bug? Without that, we realistically won't be able to reproduce this bug and fix it.

**Comment by kyoungjib** [comment]
> C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/spandsp/saturated.h:88:22: note: include the header <math.h> or explicitly provide a declaration for 'lrint'
> PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
> Stack dump:
> 0. Program arguments: C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gsm_jni/spandsp/gsm0610_lpc.o.d -target armv7-none-linux-androideabi16 -fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes --sysroot C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -D_FORTIFY_SOURCE=2 -fpic -march=armv7-a -O2 -DNDEBUG -IC:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/spandsp -IC:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp -IC:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni -O3 -DANDROID -O3 -Wformat -Werror=format-security -c C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/gsm0610_lpc.c -o C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gsm_jni/spandsp/gsm0610_lpc.o
> 
> 1. parser at end of file
> 2. Code generation
> 3. Running pass 'Function Pass Manager' on module 'C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/src/main/jni/spandsp/gsm0610_lpc.c'.
> 4. Running pass 'Greedy Register Allocator' on function '@gsm0610_lpc_analysis'
>    #0 0x00007ff7caa3d450 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x29fd450)
>    #1 0x00007ff7caa40059 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x2a00059)
>    #2 0x00007ff7c96fee57 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x16bee57)
>    #3 0x00007ff7c96faa9f (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x16baa9f)
>    #4 0x00007ff7caa27a50 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x29e7a50)
>    #5 0x00007ff7c96fa0ac (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x16ba0ac)
>    #6 0x00007ff7c877b9d2 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x73b9d2)
>    #7 0x00007ff7c82619a4 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x2219a4)
>    #8 0x00007ff7c8267fb3 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x227fb3)
>    #9 0x00007ff7c82621a2 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x2221a2)
>    #10 0x00007ff7c919e731 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x115e731)
>    #11 0x00007ff7c94b8772 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1478772)
>    #12 0x00007ff7ca701653 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x26c1653)
>    #13 0x00007ff7c9420f14 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x13e0f14)
>    #14 0x00007ff7c86a2de0 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x662de0)
>    #15 0x00007ff7c86fae13 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x6bae13)
>    #16 0x00007ff7c8046205 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x6205)
>    #17 0x00007ff7c8044481 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x4481)
>    #18 0x00007ff7c9264eb6 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1224eb6)
>    #19 0x00007ff7c8569c41 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x529c41)
>    #20 0x00007ff7c9264989 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1224989)
>    #21 0x00007ff7c866f7e9 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x62f7e9)
>    #22 0x00007ff7c866fcb5 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x62fcb5)
>    #23 0x00007ff7c8682076 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x642076)
>    #24 0x00007ff7c8043edd (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x3edd)
>    #25 0x00007ff7c8041395 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x1395)
>    #26 0x00007ff7c80414c8 (C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x14c8)
>    #27 0x00007ff8f0fe7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
>    #28 0x00007ff8f113cec1 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4cec1)
>    clang: error: clang frontend command failed due to signal (use -v to see invocation)
>    Android (6875598, based on r399163b) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
>    Target: armv7-none-linux-android16
>    Thread model: posix
>    InstalledDir: C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin
>    clang: note: diagnostic msg:
> 
> PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> Preprocessed source(s) and associated run script(s) are located at:
> clang: note: diagnostic msg: C:\Users\devpc\AppData\Local\Temp\gsm0610_lpc-38ae20.c
> clang: note: diagnostic msg: C:\Users\devpc\AppData\Local\Temp\gsm0610_lpc-38ae20.sh
> clang: note: diagnostic msg:
> 
> make: *** [C:/Android/sdk/ndk-bundle/build//../build/core/build-binary.mk:476: C:/SipUA_3.5_Onnuri_sun_32_64x_v10/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gsm_jni/spandsp/gsm0610_lpc.o] Error 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s
> 15 actionable tasks: 2 executed, 13 up-to-date

there is no problem , it is my mistake , fixed thanks
