### ISSUE TITLE
[BUG] objdump not working with .obj files

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1387]
Hi Team,

When I am trying to dump the contents of .obj file using llvm-objdump, it is reporting "The file was not recognized as a valid object file".  When I try to use the same tool for shared libraries(.so), it is working with out any issues.

I expect  llvm-objdump to work with .obj files too. Isn't it? 

**Command and Error:**

"D:\androidndk.21.0.14\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objdump.exe"  --disassemble-functions=_ZNSt6__ndk110shared_ptrIN16HeadingDetection22HeadingDetectionEngineEE11make_sharedIJP3DODEEES3_DpOT_ "D:\Proj\Build\droidx64\ship\testapp\headingdetection_integration\droid\obj\droidx64\HeadingDetectionUtil.obj"
D:\androidndk.21.0.14\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objdump.exe: error: 'D:\Proj\Build\droidx64\ship\testapp\headingdetection_integration\droid\obj\droidx64\HeadingDetectionUtil.obj': The file was not recognized as a valid object file

#### Environment Details
* NDK Version: NDK R21B
* Build system: custom
* Host OS: Windows

**Comment by pirama-arumuga-nainar** [comment]
Is it possible you're using LTO?  In that case the object file would be LLVM IR and llvm-objdump cannot display it.

If not, please share a reproducer.

**Comment by DanAlbert** [comment]
Closing for lack of info. Will reopen if we get the info we need.

**Comment by pendyalasyam** [comment]
@pirama-arumuga-nainar ... It looks this issue and https://github.com/android/ndk/issues/1637 are related.
