### ISSUE TITLE
use symlinks to save space on Linux and Darwin

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1389]
The SDK manager appears to support extracting symlinks now, so we can save some space for Linux and Darwin (not Windows because symlink support cannot be guaranteed for all users) by symlinking all the duplicated files (`clang` and `clang++`, for example).

**Comment by alexcohn** [comment]
Speaking about Windows support and saving space: it would be terrific if the user could simply choose to run the Linux version of NDK with WSL shell. This works perfectly except integration with Android Studio. I understand that this enhancement request should be filed for Android Studio and/or Gradle plugin, but I believe that mentioning this here is still appropriate, and your opinion could be instrumental in pushing this request in right direction.

**Comment by DanAlbert** [comment]
The current r23 canary is 3.5GiB extracted (1.1GiB zipped, but I'd hope that the zip's compression dedups)

**Comment by DanAlbert** [comment]
https://github.com/android/ndk/issues/1275 was a more specific version of this. Broadening the scope of that and duping.
