### ISSUE TITLE
[question] Audio buffering

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1392]
can AAudio have more than two buffers?

eg it is often recomended to set the frames to half the capacity of the buffer so Audio can double buffer

```
buffer capacity: 384
frames per data callback: 192

| 192 | 192 |
|WRITE|READ |
```

but is it possible to quadruple buffer by setting the buffer to a fourth of the capacity?

```
buffer capacity: 384
frames per data callback: 96

|  96 |  96 |  96 |  96 |
|WRITE|WRITE|WRITE|READ |
```

**Comment by enh-google** [comment]
@philburk

**Comment by DanAlbert** [comment]
@philburk While I don't mind our bug tracker being used for this, is there somewhere we should be directing people for audio questions like this so they go straight to you and your team?

**Comment by philburk** [comment]
You could send them to https://github.com/google/oboe

Questions for AAudio usually also apply to Oboe because Oboe wraps the AAudio API.

**Comment by mgood7123** [comment]
> You could send them to https://github.com/google/oboe
> 
> Questions for AAudio usually also apply to Oboe because Oboe wraps the AAudio API.

done :)
