### ISSUE TITLE
WSL support for studio

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1393]
Speaking about Windows support and saving space: it would be terrific if the user could simply choose to run the Linux version of NDK with WSL shell. This works perfectly except integration with Android Studio. I understand that this enhancement request should be filed for Android Studio and/or Gradle plugin, but I believe that mentioning this here is still appropriate, and your opinion could be instrumental in pushing this request in right direction.

_Originally posted by @alexcohn in https://github.com/android/ndk/issues/1389#issuecomment-739415341_

**Comment by DanAlbert** [comment]
As you say, a Studio thing rather than an NDK thing, but forking the discussion from the other bug.

Generally requests have more weight coming from real users than from me. If you want to file it I can help route it to the right people. This sure sounds like support for yet another operating system though, so I wouldn't have high hopes of that being done.

**Comment by alexcohn** [comment]
Sure, I have filed this request: https://issuetracker.google.com/issues/174903916. Would be glad if you could ⭐️  it.

It's hard for me to measure the additional complexity that this feature brings; Microsoft is very serious in their WSL move, so in the long run, we can expect that this will not be support for 'yet another operating system', but rather 'NDK can drop support for Windows shell'!

**Comment by DanAlbert** [comment]
> in the long run, we can expect that this will not be support for 'yet another operating system', but rather 'NDK can drop support for Windows shell'!

AIUI it's off by default and requires Administrator privileges to enable, and I'm doubtful that would change. I think it's important that non-admins are able to install and use the NDK, since that describes most university labs.

**Comment by alexcohn** [comment]
Today it's off out of the box, but possibly this will change in the future. But don't mix _enable WSL_ which requires Admin, with _use WSL_, which doesn't. As soon as the PC is configured to run WSL (by university lab admin), the students will be able to install and use the Linux NDK.
