### ISSUE TITLE
[question] AAudio large buffers

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1395]
if a large buffer (eg 16k buffer capacity with 8k frames per data callback) is given, is it normal for audio data to temporarily go out of sync and then catch back up to sync and then temporarily go out of sync again?

as I find that using small buffers (eg default determined by AAudio) lets the audio stay perfectly in sync

while large buffers causes audio to go out of sync until AAudio re-syncs the audio

but this will continually keep going out of sync as AAudio keeps re-syncing

**Comment by enh-google** [comment]
@philburk

**Comment by philburk** [comment]
This is being answered at: https://github.com/google/oboe/issues/1134
Please close this one.
