### ISSUE TITLE
[BUG] If there are spaces in ANDROID_SDK_ROOT, ndk-build will not work.

### ISSUE THREAD

**Issue by vvb2060** [android/ndk#1400]
#### Description

If there are spaces in `ANDROID_SDK_ROOT`, `ndk-build` will not work.
test case: GitHub Actions `windows-latest` OS 
log: https://github.com/vvb2060/XposedDetector/runs/1550701901?check_suite_focus=true#step:5:62

#### Environment Details

* NDK Version:  `21.3.6528147` and `22.0.6917172-beta1`
* Build system: `ndk-build` command and gradle
* Host OS: Windows
* ABI: N/A
* NDK API level: N/A
* Device API level: N/A

**Comment by DanAlbert** [comment]
I doubt this is something that will ever work reliably, FYI. This is extremely difficult to do correctly in a make based system, especially one like ours which makes heavy use of `eval` (you need to escape variables differently depending on how deep it will be used in a callstack).

We should probably emit a warning if the NDK is installed to such a path. We already do that when the _source_ is in a path that contains spaces, but we don't check the NDK itself I guess.

We should also squash this particular case, but I suspect we'll regress.

**Comment by Mafiaboy2020** [comment]
Google .inc 
mocks everyone with its stupid programs 👉 NDK
Thanks for watching.

**Comment by DanAlbert** [comment]
Apparently this is already forbidden: https://android.googlesource.com/platform/ndk/+/refs/heads/master/build/ndk-build#53 and https://android.googlesource.com/platform/ndk/+/refs/heads/master/build/core/build-local.mk#43. The former of course isn't used on Windows, but the latter doesn't appear to work there either. Your GHA log has unfortunately been culled, so I have no idea what the original report was, but this does seem quite broken on Windows.

**Comment by vvb2060** [comment]
https://github.com/actions/runner-images/issues/1122#issuecomment-735583719

**Comment by DanAlbert** [comment]
Adding this seems to be the way to catch the problem (will upload a patch in a moment):

```bat
for /f "tokens=2" %%a in ("%~dp0") do (
    echo ERROR: NDK path cannot contain spaces
    exit /b 1
)
```

**Comment by DanAlbert** [comment]
> https://github.com/actions/runner-images/issues/1122#issuecomment-735583719

Thanks! I tried the same thing you did (quote the thing in ndk-build.cmd) and ran into the same problem (that's insufficient). The fix you ended up merging makes sense to me.

> Apparently this is already forbidden: https://android.googlesource.com/platform/ndk/+/refs/heads/master/build/ndk-build#53 and https://android.googlesource.com/platform/ndk/+/refs/heads/master/build/core/build-local.mk#43

_make_ can't catch the second case on windows. `$(lastword $(MAKEFILE_LIST))` when the NDK's install directory is `android-ndk-r25c with spaces` is `spaces\build\..\build\core\build-local.mk`. ndk-build.cmd already passes a quoted path to make, so that really is just make being different on Windows (a bug, but not one I care to chase).

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/2552855 and https://android-review.googlesource.com/c/platform/ndk/+/2552856

**Comment by DanAlbert** [comment]
> make can't catch the second case on windows.

This, in case it wasn't clear, is a pretty big blocker for us ever doing better at this. Still probably less problematic than `eval`, but it's an early enough blocker that I don't think it's even worth trying.
