### ISSUE TITLE
[BUG] NDK ignore the APP_STL variable

### ISSUE THREAD

**Issue by vvb2060** [android/ndk#1401]
#### Description

The prefab requires ` c++_static`, I added `APP_STL := c++_static` to `Application.mk`. However, NDK ignored this variable when the cpp file did not exist in `LOCAL_SRC_FILES`, make build fail: `error: undefined reference to 'operator delete(void*)'`

test case: https://github.com/vvb2060/XposedDetector/commit/334279e7176563956e48e676dba98875dc62abc2 https://github.com/vvb2060/XposedDetector/commit/5cca1de8ed83a1bb52a5bc64ffaa09e6686641c6
log: https://github.com/vvb2060/XposedDetector/runs/1551353201?check_suite_focus=true#step:5:60
#### Environment Details

* NDK Version: 21.3.6528147
* Build system: ndk-build
* Host OS: Mac and Ubuntu
* ABI: ALL
* NDK API level: 21
* Device API level: N/A

**Comment by DanAlbert** [comment]
Just to make sure I've understood the test case, the imported library uses C++ but the importing code does not?

**Comment by vvb2060** [comment]
prefab use c++, LOCAL_MODULE only has `.c` file: `LOCAL_SRC_FILES := vvb2060.c`

**Comment by DanAlbert** [comment]
Gotcha. That's a prefab bug then. Refiled as https://github.com/google/prefab/issues/125
