### ISSUE TITLE
[BUG] std::byte not present

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1404]
Refiling https://issuetracker.google.com/175488693

**Comment by enh-google** [comment]
here was the original bug report:

I just upgraded to c++ 17 within a C++ module linked to my App. Despite upgrading the compile switch to "-std=c++17" in its build.gradle, invalidating cache & restarting, the compiler still does not recognize std::byte (of course I'm including <cstddef>):
```
error: no member named 'byte' in namespace 'std'
```
I'm using the latest NDK, v22.0.6917172.

Here is the complete cmake section:
```
externalNativeBuild {

            cmake {
                // Pass arguments to CMake
                arguments "-DANDROID_TOOLCHAIN=clang",
                        "-DANDROID_ARM_NEON=TRUE",
                        "-DANDROID_STL=c++_static"//,
                //"-DCMAKE_BUILD_TYPE=Debug"

                cFlags "-fexceptions", "-frtti" // Sets optional flags for the C compiler.
                cppFlags "-std=c++17"
                cppFlags"-fpack-struct=8" // MUST MATCH NATIVE SDK AND EMBEDDED
            }
}
```
The same exact code compile perfectly on Visual Studio with the c++17 switch.

What could be the issue?

**Comment by enh-google** [comment]
i just tried adding a reference to `std::byte` in the HelloJNI sample and got that error when i tried to build because the cmake default is C++11. but when i added
```
set(CMAKE_CXX_STANDARD 14)
```
to the CMakeLists.txt it worked fine with current Studio and NDK r22.

**Comment by enh-google** [comment]
i'm assuming this is WAI and a bug in the original submitter's build. (i notice they don't appear to be on this bug, so i'll copy & paste the previous comment back to buganizer too :-( )
