### ISSUE TITLE
[BUG] ndk-21d clang crashes with neon intrinsic instruction

### ISSUE THREAD

**Issue by 1bsyl** [android/ndk#1406]
ndk-21d clang crashes with neon intrinsic instruction
in "Running pass 'Simple Register Coalescing'"

Android (6454773 based on r365631c2) clang version 9.0.8 
(https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn) 
Target: aarch64-none-linux-android21

this doesn't happen with ndk-r22

[files.tar.gz](https://github.com/android/ndk/files/5714842/files.tar.gz)

**Comment by DanAlbert** [comment]
Possible dup of https://github.com/android/ndk/issues/1248?

**Comment by pirama-arumuga-nainar** [comment]
@DanAlbert Looks like you might have a new prebuilt for r21e (https://android-review.googlesource.com/c/platform/prebuilts/clang/host/linux-x86/+/1524308).  Can you check if this is fixed in r21e?

**Comment by DanAlbert** [comment]
Yeah, was going to post that here once I manage to get a build together.

**Comment by DanAlbert** [comment]
The preprocessed source is no longer valid for the latest compiler:

```
/home/slvn/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/include/arm_neon.h:35789:25: error: incompatible constant for this __builtin_neon function
  __ret = (float16x4_t) __builtin_neon_vcvt_f16_f32((int8x16_t)__p0, 8);
                        ^                                            ~
/home/slvn/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/include/arm_neon.h:35810:25: error: incompatible constant for this __builtin_neon function
  __ret = (float32x4_t) __builtin_neon_vcvt_f32_f16((int8x8_t)__p0, 41);
                        ^                                           ~~
```

@1bsyl could you test using a build from https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md? If it's fixed let us know, and if not, upload a fresh repro case?

**Comment by DanAlbert** [comment]
It _looks_ like those two constants are actually just backward. The newest arm_neon.h source has them the other way around, and if I swap them in the preprocessed source it compiles without crashing. I did have to make some other changes to the arguments that were used though because the cc1 args are not the same as they were in r21, so still need you to verify the fix on your end, @1bsyl.

**Comment by 1bsyl** [comment]
ok thanks @DanAlbert, tested with 
android-ndk-7170692-linux-x86_64.zip on branch aosp-master-ndk on target linux at 7170692
and it compiles & runs !

**Comment by DanAlbert** [comment]
Excellent, thanks for following up :)

**Comment by wwdsmm** [comment]
grtgt
,kjh,kjko89.,;
