### ISSUE TITLE
[BUG] sysroot headers missing since r22?

### ISSUE THREAD

**Issue by tmm1** [android/ndk#1407]
```
$ ls -d /usr/local/share/android-sdk/ndk/21.3.6528147/sysroot
/usr/local/share/android-sdk/ndk/21.3.6528147/sysroot

$ ls -d /usr/local/share/android-sdk/ndk/22.0.7026061/sysroot
ls: cannot access '/usr/local/share/android-sdk/ndk/22.0.7026061/sysroot': No such file or directory
```

**Comment by rprichard** [comment]
The sysroot moved to `<NDK>/toolchains/llvm/prebuilt/<host-tag>/sysroot` starting with NDK r19. r22 removed the deprecated `sysroot` and `platforms` directories from the top-level of the NDK.

 - https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#sysroot
 - https://github.com/android/ndk/wiki/Changelog-r19 (specifically, issue #780)
 - https://github.com/android/ndk/wiki/Changelog-r22

By using the appropriate driver (e.g. `toolchains/llvm/prebuilt/<host-tag>/bin/aarch64-linux-android21-clang`), it shouldn't be necessary to do things like pass `--sysroot=`, include the STL header directories, etc. The driver should handle all that stuff implicitly.

**Comment by tmm1** [comment]
Thank you for the explanation

**Comment by DanAlbert** [comment]
> Thank you for the explanation

The changelogs are helpful for things like this :) I know Studio doesn't show them and that's frustrating, but we publish them on [our wiki](https://github.com/android/ndk/wiki) and they always include announcements for things like this.
