### ISSUE TITLE
[BUG] duplicate symbol linker errors since r22

### ISSUE THREAD

**Issue by tmm1** [android/ndk#1409]
Projects that used to build with r21 now fail with r22 due to duplicate symbols:

https://github.com/termux/termux-packages/pull/6174#issuecomment-750879420

```
ld: error: duplicate symbol: spoolfile
>>> defined at relay.c
>>>            relay.o:(spoolfile)
>>> defined at relay_aux.c
>>>            relay_aux.o:(.bss+0x1C4)
```

https://github.com/golang/go/issues/42655

```
ld: error: duplicate symbol: x_cgo_inittls
>>> defined at gcc_android.c:90
>>>            $WORK/b059/_x003.o:(x_cgo_inittls)
>>> defined at gcc_linux_arm.c:13
>>>            $WORK/b059/_x006.o:(.bss+0x4)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tmm1** [comment]
This was fixed in golang using `__attribute__((common))`

https://go-review.googlesource.com/c/go/+/280312/1..3#message-0841c797f67d8380ac1b745ffe9ceb6e0b6352ea

**Comment by rprichard** [comment]
Between r21d and r22, the upstream Clang driver changed its default from `-fcommon` to `-fno-common` -- https://reviews.llvm.org/D75056. (FWIW: I see that the Android platform [currently overrides the new default using `-fcommon`](https://cs.android.com/android/platform/superproject/+/master:build/soong/cc/config/clang.go;l=107-109;drc=8aa4e3f99e784748625cd9fc1addfd057fc8b73d).)

**Comment by DanAlbert** [comment]
Unless this is a way more widespread problem than I think it is, we should keep clang's defaults. Will leave open to see if others encounter it.

**Comment by antonimmo** [comment]
I'm facing the same issue.

- go version: go1.15.6 linux/amd64
- ndk-22.0.7026061 located at $ANDROID_HOME/ndk/22.0.7026061

Following these steps https://github.com/hyperledger/aries-framework-go/tree/master/cmd/aries-agent-mobile#21-make-all I came across this output:

```
make bindings
----------------------------------------
   gomobile: Creating Android bindings  
----------------------------------------
gomobile bind -v -ldflags '-s -w' -target=android -javapkg=org.hyperledger.aries -o=/home/ant/github/aries-framework-go/cmd/aries-agent-mobile/build/android/aries-agent.aar github.com/hyperledger/aries-framework-go/cmd/aries-agent-mobile/...
runtime/cgo
# runtime/cgo
ld: error: duplicate symbol: x_cgo_inittls
>>> defined at gcc_android.c:90
>>>            $WORK/b039/_x003.o:(x_cgo_inittls)
>>> defined at gcc_linux_arm.c:13
>>>            $WORK/b039/_x006.o:(.bss+0x4)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gomobile: go build -v -ldflags -s -w -buildmode=c-shared -o=/tmp/gomobile-work-531629794/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 2

Makefile:79: recipe for target 'bindings-android' failed
make: *** [bindings-android] Error 1
```

This happened with both `GO111MODULE=off` and `GO111MODULE=on`.

I've tried with ndk-21.3.6528147 and ndk-19.2.5345600 and worked nicely (with `GO111MODULE=on`).

**Comment by DanAlbert** [comment]
I'd recommend raising the issue with the golang team if you haven't already.

**Comment by rprichard** [comment]
I think it's already been fixed in upstream Golang. See https://go-review.googlesource.com/c/go/+/280312. The fix was small (i.e. add `__attribute__((common))` to override the new compiler default), so it looks like it's being backported to 1.14 and 1.15: https://github.com/golang/go/issues/42655#issuecomment-751794985.

**Comment by auxor** [comment]
I got the same issue with r22

**Comment by obito02** [comment]
I had the same problem but I managed to compile with SDK 23, I was adding this in the .go file of my project with CGO **#cgo CFLAGS: -fcommon**  I hope that the next versions of NDK do not occur to invalidate the -fcommon flag because actually in my case rewriting the code will take more time.

**Comment by DanAlbert** [comment]
Has anyone raised the bug with go yet?

**Comment by DanAlbert** [comment]
Did you see https://github.com/android/ndk/issues/1409#issuecomment-760566166? Are you using an older version of go?

**Comment by obito02** [comment]
> Did you see [#1409 (comment)](https://github.com/android/ndk/issues/1409#issuecomment-760566166)? Are you using an older version of go?

No, i am use new version of Go 1.17 and NDK 23 new version, i fix this errro with CGO flag

**Comment by DanAlbert** [comment]
Maybe go only caught some of the cases where the attribute is needed then? I'm not sure. I don't think we have any reason to believe that this problem is observable outside go though, so closing. Anyone landing here with issues using go should file those bugs against go.
