### ISSUE TITLE
[BUG] ASAN program received signal SIGSEGV,Segmentation fault

### ISSUE THREAD

**Issue by liaohang122** [android/ndk#1416]
main.cpp：

```
#include <iostream>
using namespace std;

string heap_overflow(){
    char *p = (char*)malloc(1);
    *(p+2)='0';
    free(p);
    return string("bug");
}

int main() {
    cout<<heap_overflow();
    return 0;
}
```

ndk clang++ cmd:
```
/root/package/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi26 --gcc-toolchain=/root/package/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/root/package/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/sysroot    -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fPIE   -fsanitize=address -fsanitize-recover=address -fsanitize-address-use-after-scope -std=gnu++1z  ./main.cpp
```
```
export ASAN_OPTIONS=halt_on_error=0:handle_segv=0:detect_stack_use_after_return=1
./a.out   
```

result is  ```Segmentation fault(core dumped)```

 but just delete the  ```cout``` , code like this and recompile with the same ndk clang++ command
 ```
int main() {
    heap_overflow();
    return 0;
}
```
asan and program are run well, cc  @DanAlbert 

* NDK Version: 21.3.6528147
* Build system: Linux X86_64 Ubuntu 20.x   use ndk clang++
* Host OS: Android ARM 
* ABI: armeabi-v7a
* NDK API level: 26
* Device API level: Android 9

**Comment by jmgao** [comment]
clang is probably optimizing your entire program into `int main() { return 0; }`.

**Comment by liaohang122** [comment]
> clang is probably optimizing your entire program into `int main() { return 0; }`.
but asan has printed out out-of-bounds logs, so you can try it @jmgao

**Comment by hhb** [comment]
@liaohang122  So you mean the first case (with cout) is unexpected because it segfault without asan logs? Maybe the program crashed before asan. Can you remove `*(p+2)='0';` in the first case and try again?

I tried your program and got asan output in both cases. But I did add some compiler parameters to point to `iostream`, libgcc and statically link libc++.
