### ISSUE TITLE
[question] clang/llvm support for mips (even if NDK doesn't support it for builds)

### ISSUE THREAD

**Issue by saurik** [android/ndk#1417]
I love the Android NDK: it offers binary builds across every major platform of an open source fork of llvm that is so well maintained that it offers an LTS variant. I use it for _everything_: I compile _all targets_ using the Android NDK. Now, of course, this isn't "supported"... I mean, "clearly", and nor am I expecting it to be: I literally use the Android NDK to compile for iOS! and Windows! Only... somehow... despite clang being able to target absolutely everything, I can't use the copy of clang in the Android NDK to target, specifically, MIPS. It is almost as if MIPS--and only MIPS--was turned off or something, in the NDK build of clang. Am I right that this is the case? Is there a reason for this? I totally 100% appreciate deprecating and removing support for MIPS from the sysroots and other tooling that comes with the NDK... but I would have expected that, were I to bring my own sysroots for my own targets, that the copy of clang wouldn't be adulterated.

**Comment by saurik** [comment]
(For the record, the error I get if I pass -target mips-linux-gnu to the Android NDK copy of clang is "error: unable to create target: 'No available targets are compatible with triple "mips-unknown-linux-gnu"'".)

**Comment by stephenhines** [comment]
Hi, we don't include any architectures that aren't supported by the NDK in our distribution as it would bloat the download/install size (and compile time for us). We made the decision to remove MIPS support from the NDK toolchain when MIPS was removed as a supported Android target. You'll also notice we don't include support for PowerPC in our toolchain for a similar reason.
