### ISSUE TITLE
How can I reduce .text align[question]

### ISSUE THREAD

**Issue by yingnaj** [android/ndk#1421]
1. I'm not sure that the alignment of `.text` would affect the binary size of my main library **.so, and I fount that alignment of other library is usually 4 or 8 but it got 32 in my **.so
2. I've tried `-falign-functions` to change it but it isn't work, setting 4 nor 8.

![image](https://user-images.githubusercontent.com/43540376/103726442-e6b2a480-5013-11eb-952f-c9202c14baa9.png)

NDK Version: 21.1.6352462
Build system: ndk-build
Host OS: Windows
ABI: both armeabi-v7a & arm64-v8a

**Comment by pirama-arumuga-nainar** [comment]
`-falign-functions` sets the minimum alignment and could still result in a higher alignment if a function has a higher alignment via `__attribute__((aligned))`.  The higher-alignment function could also be present in an assembly source or in a prebuilt.

The alignment of `.text` is the maximum among all the `.text.*` sections in the linker input files.  My suggestion would be to inspect the input `.o`/`.a` files.

**Comment by bangyanh** [comment]
Thanks @pirama-arumuga-nainar .
I've checked all `.o`/`.a` files and found a function added `__attribute__((aligned(32)))` in protobuf. It affect the final alignment of `.text` in my .so. However the size of `.text` was almost not reduced as it changed from 32 to 4 or 8.
I wonder if the alignment of `.text` would impact its size, or there were other ways to optimize the binary size, where I have used some options below:
`-Oz -fexceptions -fvisibility=hidden -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,-z,noexecstack`
Note that I have to use c++ exception.

**Comment by pirama-arumuga-nainar** [comment]
I missed that question in your original post.  I don't think the alignment would reduce the overall size by much, unless there are lots of small functions in the binary.

The `.text` section seems to be the largest, based on the screenshot in the report.   You mention all the common flags to reduce binary sizes.  `-mthumb` may help for `arm32`.  @DanAlbert Do you have other suggestions?

**Comment by DanAlbert** [comment]
`-fomit-frame-poubter`

**Comment by bangyanh** [comment]
Thanks a lot!! @DanAlbert @pirama-arumuga-nainar 
Besides, **can I link STL library in dynamic way**? 
When I changed from `-DANDROID_STL=c++_static` to `-DANDROID_STL=c++_shared` I found `libc++_shared.so` in my pack. I've referred to [https://developer.android.google.cn/ndk/guides/cpp-support#shared_runtimes](url) that `libc++_shared.so` 's not the part of android OS. 
Besides I found there's libc++.so in android system: `/system/lib64/libc++.so`. I wonder if there any way to link my .so to this lib.

**Comment by enh-google** [comment]
> Besides I found there's libc++.so in android system: /system/lib64/libc++.so. I wonder if there any way to link my .so to this lib.

no, as explained in https://developer.android.com/ndk/guides/cpp-support#shared_runtimes :

> On Android, the libc++ used by the NDK is not part of the OS. This gives NDK users access to the latest libc++ features and bug fixes even when targeting old versions of Android. The trade-off is that if you use libc++_shared.so, you must include it in your APK. If you're building your application with Gradle this is handled automatically.

**Comment by enh-google** [comment]
like pirama said, you'll have to look at your .o files with objdump rather than readelf to work out what's really changed in the text section...
