### ISSUE TITLE
[question]clang++.exe: error: unsupported option '-fPIE' for target 'x86_64-w64-windows-gnu'

### ISSUE THREAD

**Issue by peguine** [android/ndk#1424]
both ndk version 18b and the latest have this problem
i use clion , mingw-w64 and ndk on windows
cmake options
`-DCMAKE_TOOLCHAIN_FILE="D:\soft\android-ndk-r18b\build\cmake\android.toolchain.cmake"
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a
-DANDROID_ABI=arm64-v8a
-DANDROID_PLATFORM=android-24
-DCMAKE_ANDROID_NDK="D:\soft\android-ndk-r18b"
-DCMAKE_SYSTEM_VERSION=24
-DCMAKE_C_FLAGS=""
-DCMAKE_CXX_FLAGS=""
-DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang`

c complier =D:\soft\android-ndk-r18b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe
D:\soft\android-ndk-r18b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe

Problems were encountered while collecting compiler information:
	clang++.exe: error: unsupported option '-fPIE' for target 'x86_64-w64-windows-gnu'

**Comment by peguine** [comment]
and this only happens in debug mode. no errors occur in release mode.
in debug mode, the makefile generates sucessfully.

**Comment by DanAlbert** [comment]
The NDK doesn't support non-Android targets.

**Comment by goodandrewsoft** [comment]
![image](https://user-images.githubusercontent.com/2471892/111875547-10d4fb00-89a3-11eb-85f5-7439a2908b65.png)

**Comment by DanAlbert** [comment]
Anything here is likely obsolete with r23. If there are further issues please file a bug with a repro case. Our tests are working just fine on Windows so if you're seeing issues there is something specific to your project or environment that is causing the problem and we cannot guess what it is.

**Comment by goodandrewsoft** [comment]
Ndk 21 works on clion for windows
