### ISSUE TITLE
[question] Is NDK 22 a rolling release or the next LTS release?

### ISSUE THREAD

**Issue by buttaface** [android/ndk#1425]
The [documented release process lays out two tracks](https://github.com/android/ndk/wiki/NDK-Release-Process), which hasn't been followed so far. Could someone correct that wiki page or relabel NDK 22 on the downloads page, depending on what the new process is?

**Comment by DanAlbert** [comment]
Relabeled r22. "Rolling" was implied by the absence of "LTS", but I've made it explicit.

**Comment by buttaface** [comment]
Thanks for clearing it up. 😄
