### ISSUE TITLE
ld: error: found local symbol '_end' in global part of symbol table in file ../../../../src/main/jniLibs/arm64-v8a/libMNN_CL.so

### ISSUE THREAD

**Issue by saikirantokala** [android/ndk#1430]
Can you please help me to solve this error

**Comment by DanAlbert** [comment]
We can't do anything with this little information. Please upload a repro case and we can investigate.

**Comment by enh-google** [comment]
you might also have more luck reporting this at https://github.com/alibaba/MNN/issues --- we haven't heard of any other problems like this, so it's probably an issue with libMNN_CL rather than a general issue.
