### ISSUE TITLE
[question]how to run a c++ program  without Java in android, standalone toolchain can't use

### ISSUE THREAD

**Issue by boulevarder** [android/ndk#1437]
https://developer.android.com/ndk/guides/standalone_toolchain
Standalone toolchains (obsolete)
Now can i use Standalone toolchains ?

**Comment by enh-google** [comment]
all toolchains are now "standalone". see https://developer.android.com/ndk/guides/other_build_systems instead.

**Comment by boulevarder** [comment]
> all toolchains are now "standalone". see https://developer.android.com/ndk/guides/other_build_systems instead.

thx!!!

**Comment by DanAlbert** [comment]
Do you have a suggestion for how to make the blurb at the top of the Standalone Toolchain page more clear? It's supposed to have given you that answer already, but apparently isn't clear enough.

**Comment by enh-google** [comment]
yeah, i was wondering whether we should delete everything below the red box... (since we can't edit the entire internet to remove links.)

the other alternative i wondered about was deleting the whole page and putting in a redirect to the "other build systems" page instead.

**Comment by boulevarder** [comment]
> yeah, i was wondering whether we should delete everything below the red box... (since we can't edit the entire internet to remove links.)
> 
> the other alternative i wondered about was deleting the whole page and putting in a redirect to the "other build systems" page instead.

i think deleting everything below the red box may be clearer.

**Comment by DanAlbert** [comment]
The rest of the page is still required for anyone using an older (pre r19) NDK, but maybe it's been long enough to not worry about that any more.

**Comment by enh-google** [comment]
> The rest of the page is still required for anyone using an older (pre r19) NDK, but maybe it's been long enough to not worry about that any more.

yeah, my thinking there was "pre-r19 is so not supported at this point that i'm fine with you having to dig that out of the library of alexandria".
