### ISSUE TITLE
[question] Where can i Download prebuilt binaries for arm64/aarch64 ?

### ISSUE THREAD

**Issue by Tanishq-Banyal** [android/ndk#1440]
I searched on android developers website, but only found ndk for x86_64. But my Computer has a arm cpu (arm64/aarch64).

Does anybody maintains prebuilt binaries for arm64 (linux) ?
(Minimum NDK 19)

Why there are no releases in this repository ?

**Comment by enh-google** [comment]
correct. (that's probably quite hard though. @kongy is working on macOS/arm64 but i don't know how much overlap there is between the patches he's needed to support that and what you'd need for [what i assume is] Linux/arm64...)

**Comment by pirama-arumuga-nainar** [comment]
Clang for arm64 Linux is already supported in upstream ([builder](http://lab.llvm.org:8011/#/builders/7)).  You need to patch the [toolchain build scripts](https://android.googlesource.com/toolchain/llvm_android/+/master/README.md), which currently assume only aarch64 is supported.  There is an out-of-date [patch](https://android-review.googlesource.com/c/toolchain/llvm_android/+/1455048), to get you started.

**Comment by Tanishq-Banyal** [comment]
NVM Found it :-
https://github.com/Lzhiyong/termux-ndk/issues

**Comment by ramanveerji** [comment]
Can I get the arm64/ aarch64 version of ndk for mt ubuntu server?

**Comment by ramanveerji** [comment]
> > Can I get the arm64/ aarch64 version of ndk for mt ubuntu server?
> 
> You clearly don't know how to read.

But i have not found that. Help me read.

**Comment by enh-google** [comment]
@ThunderStud613 --- no need to be rude. on the internet, you never know how good the other person's English is (and that doesn't mean they're _stupid_).

@ramanveerji --- no, there is no prebuilt. you can follow pirama-arumuga-nainar's instructions to build your own, but that's definitely playing on "hard mode". for now, sticking to x86-64 (or using macOS/arm64) is "easy mode". there are no current plans to have a linux/arm64 download (nor linux/riscv64, before anyone asks!) we'll continue to re-evaluate this as arm64 [or riscv64!] hardware becomes more popular and practically useful.
