### ISSUE TITLE
[question] correct way of dealing with generated files on git

### ISSUE THREAD

**Issue by mariuspena** [android/ndk#1443]
Hi,

I recently switched to using ndkbuild in gradle and when compiling I get a lot of files like these:
```
armeabi-v7a/android_gradle_build.json
armeabi-v7a/android_gradle_build_mini.json
armeabi-v7a/build_command.txt
armeabi-v7a/build_model.json
armeabi-v7a/build_output.txt
armeabi-v7a/json_generation_record.json
armeabi-v7a/prefab_config.json
abi_configuration_6o2iu3qf.json
abi_configuration_m28263a4_key.json
ndk_locator_record_345tk5j3.json
```

Should I keep adding these files on git ?

**Comment by DanAlbert** [comment]
No.

**Comment by renuac** [comment]
Commit's |$#£πProject's(GradlePLUSTreble AOSPR11 gsi gms CANARY BUILD!


*. bootstrapcdn.*

Em qua, 3 de fev de 2021 07:56, Dan Albert <notifications@github.com>
escreveu:

**Comment by enh-google** [comment]
to save you work in future, you probably want to ensure that the generated output *directory* is in your .gitignore file, not each individual file.

**Comment by DanAlbert** [comment]
Android Studio does generate that .gitignore for you, and GitHub maintains a list of recommended gitignore files [here](https://github.com/github/gitignore).
