### ISSUE TITLE
[BUG] NDK22: Enabling LTO forces CMake to choose gold linker which crashes the build

### ISSUE THREAD

**Issue by cmelchior** [android/ndk#1444]
#### Description

I'm trying to upgrade our CMake build from NDK 21 to 22.0.7026061, however, I'm running into some problems with the default linker when enabling LTO.

If I enable LTO with `arguments "-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON"` in `build.gradle`, the linker flags look like this: 

```
LINK_FLAGS = -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments   -Wl,-gc-sections   -fuse-ld=gold
```
Notice `-fuse-ld=gold` in the end. This causes the following error to be thrown `  /usr/local/Caskroom/android-sdk/4333796/ndk/22.0.7026061/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: --no-rosegment: unknown option`, which makes sense since gold was removed in NDK 22.

After some investigation, it turns out gold is being forced by the `CMAKE_CXX_LINK_OPTIONS_IPO` variable. Trying to manually add my own linker flag through `CMAKE_SHARED_LINKER_FLAGS` only makes it appear before the IPO flags, which means they get ignored

My understanding is that `CMAKE_CXX_LINK_OPTIONS_IPO` is defined by CMake itself, so it is a bit unclear exactly if this is a bug in the Android NDK or CMake, but right now it appears the only work-around is manually modifying the `CMAKE_CXX_LINK_OPTIONS_IPO` variable. In our build I'm setting it to:

```
set(CMAKE_CXX_LINK_OPTIONS_IPO "")
```

This makes the build default to whatever the Android toolchain file is doing, but obviously, this is not ideal.

#### Environment Details

* NDK Version: 22.0.7026061
* Build system: CMake (v. 3.18.4)
* Host OS: Mac
* ABI: Tested on x86_64 and arm64-v8a

**Comment by cmelchior** [comment]
Seems to be a problem in CMake itself: https://github.com/Kitware/CMake/blob/af695cee7346fa0eee478f71952fd02f0df989cf/Modules/Compiler/Clang.cmake#L81

**Comment by DanAlbert** [comment]
@hhb to confirm, but I'm guessing there's nothing we can do about this since you (I believe) are not using our toolchain file.

Or possibly that option doesn't work even with our toolchain file. I've never come across that option. I've always just added `-flto` to my flags.

**Comment by cmelchior** [comment]
`-DCMAKE_TOOLCHAIN_FILE=/usr/local/Caskroom/android-sdk/4333796/ndk/21.0.6113669/build/cmake/android.toolchain.cmake`

Is being passed to CMake from Gradle according to the logs, so the toolchain file should be used.

**Comment by DanAlbert** [comment]
Might just be outside the realm of what we can impact. Given all the other flags it looks like our toolchain did try to set up LLD and then CMake overrode that.

**Comment by cmelchior** [comment]
Yes, I mostly raised it for visibility. It is fair to argue that this happens because CMake tries to work around a bug in the NDK that is no longer relevant and the NDK trying to fix a fix for an old bug also seems like a slippery road 😄

**Comment by DanAlbert** [comment]
Good news is that issues like this should be much more rare in r23 :)

**Comment by hhb** [comment]
Yeah this has to be fixed upstream in CMake. I'll check what can we do since CMake tries to be compatible with pretty old NDKs. I'll update in [#242](https://github.com/android-ndk/ndk/issues/242).

**Comment by PabloMK7** [comment]
Still experiencing this issue on NDK27, see: https://github.com/azahar-emu/azahar/actions/runs/15684623888/job/44184551717#step:6:159

EDIT: It turns out CMake mitigated this issue by [checking NDK version lower than 22 in their built-in modules](https://github.com/Kitware/CMake/blob/a2dc4b4e9bb794f60aeb38652149d2334b6ad167/Modules/Compiler/Clang.cmake#L84). However, prior to CMake version 3.25.3, in some configurations the [CMAKE_ANDROID_NDK_VERSION variable was not being populated properly](https://gitlab.kitware.com/cmake/cmake/-/issues/24386), breaking the NDK version check. The easy solution to this problem was to [bump the CMake version for our project manually](https://github.com/azahar-emu/azahar/pull/1151).

**Comment by DanAlbert** [comment]
If it's the same problem then you have to talk to CMake. This was not an NDK bug. If you believe this is an NDK bug, please file a new bug, because the bug discussed here was not an NDK bug.
