### ISSUE TITLE
[question] ndkBuild output folder (where are the so files) 

### ISSUE THREAD

**Issue by mariuspena** [android/ndk#1445]
Hi

I am using this configuration in gradle
```
// NDK
    ndkVersion "21.3.6528147"
    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
            buildStagingDirectory 'src/main/libs'
        }
    }
```

I cannot seem to find the .so files anymore under the buildStagingDirectory
But I find some .so files in:

_
app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨ndkBuild⁩ ▸ ⁨{buildVariant} ▸ ⁨obj⁩ ▸ ⁨local⁩ ▸ ⁨arm64-v8a⁩
app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨ndkBuild⁩ ▸ ⁨{buildVariant}⁩ ▸ ⁨obj⁩ ▸ ⁨local⁩ ▸ ⁨armeabi-v7a⁩

⁨app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨merged_native_libs⁩ ▸ ⁨{buildVariant} ▸ ⁨out⁩ ▸ ⁨lib⁩ ▸ ⁨arm64-v8a⁩
⁨app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨merged_native_libs⁩ ▸ ⁨{buildVariant} ▸ ⁨out⁩ ▸ ⁨lib⁩ ▸ ⁨armeabi-v7a⁩

app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨stripped_native_libs⁩ ▸ ⁨{buildVariant} ▸ ⁨out⁩ ▸ ⁨lib⁩ ▸ ⁨armeabi-v7a⁩
app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨stripped_native_libs⁩ ▸ ⁨{buildVariant} ▸ ⁨out⁩ ▸ ⁨lib⁩ ▸ ⁨arm64-v8a
⁩_

And I can find the .zip file (for uploading on Google Play)
_**app⁩ ▸ ⁨build⁩ ▸ ⁨outputs⁩ ▸ ⁨native-debug-symbols⁩ ▸ ⁨{buildVariant} ▸ .zip**_

If I do not set the buildStagingDirectory in gradle, according to the documentation the app/.cxx folder will be used. 
Either way that folder only contains .json, .txt, .log files. No .so files there.
I could not find any documentation on specifying the output folder

My questions are:
1. How can you set the output folder ?
2. Are these ⁨_app⁩ ▸ ⁨build⁩ ▸ ⁨intermediates⁩ ▸ ⁨ndkBuild⁩ ▸ ⁨{buildVariant} ▸ ⁨obj⁩ ▸ ⁨local⁩ ▸ ⁨arm64-v8a_⁩ the final .so files ?

PS: previously I was using the command line ndk-build and I could set the output folder to src/main/libs..

**Comment by DanAlbert** [comment]
You're in the wrong place for Gradle questions. File a bug against Gradle or Studio by following b.android.com.

**Comment by alexcohn** [comment]
It is working as expected. The [buildStagingDirectory](https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/NdkBuild#buildstagingdirectory) specifies the path to external native build output directory, to replace the default `<project_dir>/.cxx/`. I agree that the official explanation above may be confusing, but this directory contains intermediate build files (logs, objects, etc.). The `.so` files go normally to `<project_dir>/build` directory, and if you need to put them elsewhere, you should use the [arguments](https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/ExternalNativeNdkBuildOptions#arguments(kotlin.String)) parameter. Note that this goes inside a different `externalNativeBuild { ndkBuild {} }` clause, this one – under [defaultConfig](https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/DefaultConfig), and yes, you can have alternative settings for other flavors.

To choose the directory for ndkBuild outputs, see [Change ndk-build output locations](https://stackoverflow.com/a/31265415/192373):
````
android {
    // Similar to other properties in the defaultConfig block, you can override
    // these properties for each product flavor you configure.
    defaultConfig {
        externalNativeBuild {
            ndkBuild {
                // Passes an optional argument to ndk-build.
                arguments "NDK_OUT=${projectDir}/src/main/lib"
            }
        }
    }
}
````

Note that this `NDK_OUT` must be absolute path. Unfortunately, it seems that the recent releases of NDK (v21, v22) don't recognize `NDK_LIB_OUT` anymore.

**Comment by mariuspena** [comment]
@alexcohn u save lives! :)
