### ISSUE TITLE
[FR]Android.bp files are not supported in NDK 

### ISSUE THREAD

**Issue by nrk0729** [android/ndk#1446]
**Is your feature request related to a problem? Please describe.**
Given that Google is pushing for Android.bp and new build systems and most importantly they are not willing to support .mk files. It is very important NDK to support these build system.

If this is already supported, please let us know.

**Comment by DanAlbert** [comment]
> Given that Google is pushing for Android.bp and new build systems and most importantly they are not willing to support .mk files. It is very important NDK to support these build system.

The premise is false. Google is not pushing Android.bp, that's just for AOSP's build system. We are absolutely willing to support Android.mk. ndk-build remains fully supported.

The Android.mk files in AOSP are not ndk-build build scripts. Those are for a separate build system that is not compatible with ndk-build despite using files of the same name (the historical naming was a giant mistake but we're stuck with it).
