### ISSUE TITLE
[FR] improve clang display of API levels for -Wunguarded-availability

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1455]
https://android-review.googlesource.com/c/platform/external/jsoncpp/+/1607004/2..3//COMMIT_MSG#b9

`Android 16.0.0` meaning "API 16" is damn confusing.

**Comment by DanAlbert** [comment]
Reproducer:

```
$ cat foo.cpp
extern void foo() __attribute__((__availability__(android,introduced=31)));

int main() {
  foo();
}
$ android-ndk-r24-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target aarch64-linux-android21 foo.cpp -Weverything
foo.cpp:4:3: warning: 'foo' is only available on Android 31 or newer [-Wunguarded-availability]
  foo();
  ^~~
foo.cpp:1:13: note: 'foo' has been marked as being introduced in Android 31 here, but the deployment target is Android 21.0.0
extern void foo() __attribute__((__availability__(android,introduced=31)));
            ^
foo.cpp:4:3: note: enclose 'foo' in a __builtin_available check to silence this warning
  foo();
  ^~~
1 warning generated.
```

**Comment by enh-google** [comment]
> foo.cpp:1:13: note: 'foo' has been marked as being introduced in Android 31 here, but the deployment target is Android 21.0.0

oh, that's even stranger --- we get "Android 31" in the first part of the message, but "Android 21.0.0" in the second!

**Comment by jfgoog** [comment]
The reason I was having trouble reproducing it in a test is that `// expected-foo` doesn't check for an exact match, just a substring. Now I understand what's going on, and I have a fix.

**Comment by DanAlbert** [comment]
Change is in review: https://reviews.llvm.org/D114163

Not likely to be backported, but should be included whatever LLVM we pick up for r25, so moving buckets.
