### ISSUE TITLE
[question]how to use third party library which need .ini file in android ndk?

### ISSUE THREAD

**Issue by cyqkevin** [android/ndk#1456]
NDK version, ABI, build system
android studio 4.1.1, NDK:21.2.6472646,  armeabi-v7a

**Comment by cyqkevin** [comment]
i have already pack these library to apk but i don't know how to pack .ini file these library needed to apk. what shoud i do ?

**Comment by alexcohn** [comment]
Typically, you would put the **`.ini`** file in assets. The API to read assets from native code is quite easy. Its only drawback is that the library cannot obtain the `context` that is needed to access the AssetManager without cooperation of the application. There is a feature request to provide a documented way for C++ code to find its Application context autonomously.

Whether the **`.ini`** file is part of your AAR or if it is supplied by the app developer, gradle will pack it into the APK. The delicate issue is that gradle will not merge the two files, if both exist.

**Comment by alexcohn** [comment]
@DanAlbert is there a documented way now to obtain a Context from C++?

**Comment by DanAlbert** [comment]
Use JNI? `GameActivity` probably has it exposed on some part of the structure it gives the app as well. I closed this because it looks like you answered the question in the OP.

**Comment by alexcohn** [comment]
There is an [undocumented way](https://stackoverflow.com/a/46871051/192373) to call `getApplication()` from **`currentActivityThread`**, but I am not sure this will remain available in future releases.

**Comment by DanAlbert** [comment]
I don't think I can help with either of those problems short of bothering some other Googler to look at an API bug. It sounds like you're asking for a new API, or possibly for an existing non-public API to be made public? Neither of those are within my power, but I can try to get attention to a framework bug if one gets filed on b.android.com. I don't understand the context (pun intended) well enough to file that bug myself.

**Comment by alexcohn** [comment]
Yes, the framework 'bug' was filed some while ago: https://issuetracker.google.com/issues/178391033. It as also discussed [here](https://github.com/android/ndk/issues/1320).

**Comment by DanAlbert** [comment]
Ugh. The history on that bug is aggravating. I'll go find someone.

**Comment by DanAlbert** [comment]
Assigned and left a comment. Don't hesitate to bug me if triage goes wrong again.
