### ISSUE TITLE
[question] Full native access to all Android SDK features as a long term goal?

### ISSUE THREAD

**Issue by levinem** [android/ndk#1466]
Since Android's NDK is used by some very high profile projects like Flutter (for its Android backend) as well as many gaming engines, is the NDK's ultimate goal to be a first class citizen in terms of native access to all Android SDK's capabilities or is the end goal to still require using the JNI to access particular features?

**Comment by DanAlbert** [comment]
> or is the end goal to still require using the JNI to access particular features?

Most of the APIs you're referring to are _implemented_ in Java. JNI will always be a part of using those APIs.

We want to provide some libraries in Jetpack that'll provide the JNI layer for you for cases where it makes sense, but no, we don't plan on having 100% coverage of the Java API surface. I don't think that's feasible.
