### ISSUE TITLE
[question] Sending File Descriptor over STREAMS

### ISSUE THREAD

**Issue by ylz-at** [android/ndk#1468]
Currently, we can use `ParcelFileDescriptor` to send fd over binder or something else, but what if I need to let native talks to native?

Is there any example to send fd over STREAMS?

I'm following the example, http://poincare.matf.bg.ac.rs/~ivana/courses/ps/sistemi_knjige/pomocno/apue/APUE/0201433079/ch17lev1sec4.html

server side use something like
``` cpp
ioctl(fd, I_SENDFD, fd_to_send)
```

client side use something like
```cpp
ioctl(fd, I_RECVFD, &recvfd)
```

and the structure for I_SENDFD and I_RECVFD is,

```cpp
   struct strrecvfd {
       int    fd;       /* new descriptor */
       uid_t  uid;      /* effective user ID of sender */
       gid_t  gid;      /* effective group ID of sender */
       char   fill[8];
   };
```

I tried to do this with NDK r22, but failed to include `<stropts.h>` where `strrecvfd`, `I_SENDFD` and `I_RECVFD` is defined.

**Comment by jmgao** [comment]
STREAMS does not exist on any modern operating system, it's an ancient API from the 80s.
The modern equivalent is sendmsg over a unix domain socket: the manpage you'll want to read is the `SCM_RIGHTS` section of [man 7 unix](https://man7.org/linux/man-pages/man7/unix.7.html). It's an extremely easy API to implement incorrectly, so you might be better off just copy/pasting [this implementation](https://android.googlesource.com/platform/system/libbase/+/refs/heads/master/cmsg.cpp#32).

**Comment by ylz-at** [comment]
@jmgao thanks!!! I was just trying to avoid using the socket. Looks like it was the only way to go.
