### ISSUE TITLE
[BUG] Verbose build not working

### ISSUE THREAD

**Issue by mirabilos** [android/ndk#1481]
#### Description

None of the usual methods to enable verbose build are working:
- `export VERBOSE=1` before running `./gradlew build`
- [adding `arguments "-DCMAKE_VERBOSE_MAKEFILE=1"` to `defaultConfig.externalNativeBuild`](https://stackoverflow.com/a/43442227/2171120)
- [adding `set(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "ON" FORCE)` to CMakeLists](https://github.com/ninja-build/ninja/issues/900)

See also: https://stackoverflow.com/a/45621514/2171120

We wouldn’t have this trouble if Unix Makefiles would be used instead of ninja (an opaque not-used-elsewhere-in-the-real-world tool)…

#### Environment Details

* NDK Version: 21.4.7075529
* Build system: CMake
* Host OS: Debian sid
* ABI: any
* NDK API level: doesn’t matter
* Device API level: neither

**Comment by mirabilos** [comment]
I think I _might_ have found the **cause** of this bug. It _looks_ like the AGP invokes ninja directly:

    /**
     * Returns the build command for the given target (given the output folder and cmake
     * executable).
     */
    @NonNull
    public static String getBuildCommand(
            @NonNull File cmakeExecutable, @NonNull File outputFolder, @NonNull String targetName) {
        return getNinjaExecutable(cmakeExecutable)
                + " -C "
                + "\""
                + outputFolder.getAbsolutePath()
                + "\""
                + " "
                + targetName;
    }

**Comment by mirabilos** [comment]
AFAICT the only way to override this is to move the ninja executable aside and put a wrapper shell script there ☹

**Comment by DanAlbert** [comment]
Wrong place for gradle bugs. We have no control over what gradle hides from you. File a bug against Android Studio (and feel free to link it here if it's not getting triaged).

**Comment by mirabilos** [comment]
I didn’t know it was a gradle bug initially…

**Comment by DanAlbert** [comment]
Yeah, no worries. Just explaining why I'm closing this.

**Comment by mirabilos** [comment]
Right.

I’ve filed this at https://issuetracker.google.com/issues/184060944 in case someone stumbles upon this.

**Comment by DanAlbert** [comment]
Thanks. Will give the triage process a chance to work but will track down someone if it doesn't :)

**Comment by giladreich** [comment]
@mirabilos for the record, check my comment here how I solved this: https://github.com/android/ndk-samples/issues/341#issuecomment-1126772855

Hope this helps.

**Comment by mirabilos** [comment]
@giladreich that’s the same as I wrote in https://github.com/android/ndk/issues/1481#issuecomment-810635981 though, nothing new there.

The `CMakeSettings.json` workaround from https://issuetracker.google.com/issues/184060944#comment2 did the trick for me.
