### ISSUE TITLE
[question] RSS subscription to releases

### ISSUE THREAD

**Issue by tyranron** [android/ndk#1484]
Is there any page on GitHub or on https://developer.android.com/ndk/ with releases list, which can be tracked via RSS/Atom feed? So once new version is released, you're get notified. Tried to found, but didn't succeed. Thanks!

**Comment by tyranron** [comment]
Ok, found how to do it via Google Groups.

Here is the link is someone will need it:
https://groups.google.com/forum/feed/android-ndk-announce/msgs/rss.xml

**Comment by tyranron** [comment]
I don't know of any.

**Comment by DoDoENT** [comment]
Can you then re-open the issue at least?

**Comment by DoDoENT** [comment]
It's not RSS, but it appears that the google group is still active: https://groups.google.com/g/android-ndk-announce

I've added myself to it and enabled e-mail notification, but I would still prefer RSS feed that I could link to our companys slack channel...

**Comment by DanAlbert** [comment]
https://support.google.com/groups/answer/9718200?hl=en#highlights&unavailable&mobile&member&view_options&permissions_settings& says the groups change was intentional. Fixing that is way above my pay grade.

https://support.google.com/groups/thread/118690869/when-will-googlegroups-rss-feed-be-back-online?hl=en I guess. There's nothing my team can feasibly do about this. Please go complain to Google Groups (really, please do).

**Comment by DanAlbert** [comment]
I don't suppose it's possible to subscribe to https://github.com/android/ndk/wiki? We do make commits for every release already (there are a small number of other changes that get pushed to that page, but they're also release related), I just don't know if the wiki is subscribable.

We also tag every release in https://android.googlesource.com/platform/ndk/+refs, so if you can find a way to subscribe to that, that'll also cover it. I'd really like to not add yet another step to our release process.

**Comment by DanAlbert** [comment]
(if none of those options work, I suspect creating empty releases in this repo is probably the least effort for us, but if either of those does work I'd prefer those since it's one less thing to forget to do)

**Comment by DoDoENT** [comment]
newreleases.io uses GitHub's API to obtain notifications for releases. It doesn't use git natively. I didn't find a way to subscribe to wiki only.

Also, regarding the googlesource.com, it doesn't appear to be supported 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/158844/222266172-f6003d7a-35fd-490f-9e1a-e27652885605.png">

It is possible to create a microservice that will periodically poll googlesource.com's git and check for new tags, but this looks like a lot of work for something such simple.

**Comment by DanAlbert** [comment]
I've added a note to our release docs that we should make a github release at the end of the process. Ping me here when I inevitably forget the first time because I'm doing it all from muscle memory anyway...

**Comment by tyranron** [comment]
@DoDoENT 

> Then we can use the service, such as [newreleases.io](https://newreleases.io/) to monitor this Github project for new releases or even just tags and automatically get notified. We are using this service already to track releases for lots of different open-source projects we are interested in and it works very well.

You don't need a separate service for that. GitHub is capable to do it out-of-the-box. Just add `.atom` to the desired page. Like this:
<https://github.com/android/ndk/releases.atom>

> I don't suppose it's possible to subscribe to https://github.com/android/ndk/wiki?

<https://github.com/android/ndk/wiki.atom>

**Comment by DoDoENT** [comment]
@tyranron , wow, I didn't know that GitHub automatically exports atom feed. I'll add a subscription to the wiki. Thanks!

**Comment by DanAlbert** [comment]
Amazingly I didn't forget: https://github.com/android/ndk/releases

The "assets" section is useless but github won't let me remove it afaict.
