### ISSUE TITLE
__fp16 usage with -march=armv8-a+fp16 generates illegal instruction

### ISSUE THREAD

**Issue by alecazam** [android/ndk#1486]
#### Description

We are trying to use __fp16 across all clang-based builds.  Use of this construct works fine on iOS, macOS, and other clang platforms.  We build with a Makefile.   But on Android, using this construct results in an "Illegal Instruction" on something as simple as the following.   My understanding was that armv8 should support __fp16.   And that armv8.2 supports the fp16 math ops via _Float16.

```
__fp16 value = 1.0f;
```

#### Environment Details

* NDK Version: 20.0.5594570
* Build system: Custom makefile based (see below)
* Host OS: macOS Big Sur
* ABI: arm64-v8a
* NDK API level: 30
* Device API level: Redmi Note 8 Pro with Android 9

-------

These is our full set of settings to compile:

API_LEVEL 	:= 30
MIN_SDK 	:= 26
NATIVE_SDK 	:= $(MIN_SDK)
NDK_VER 	:= 20.0.5594570
CLANG_VER 	:= 8.0
ABI 		        := arm64-v8a

NDK_DIR 	:= $(ANDROID_HOME)/ndk/$(NDK_VER)
TOOLCHAIN 	:= $(NDK_DIR)/toolchains/llvm/prebuilt/darwin-x86_64

CC := $(CCACHE) $(TOOLCHAIN)/bin/aarch64-linux-android$(NATIVE_SDK)-clang
CXX := $(CCACHE) $(TOOLCHAIN)/bin/aarch64-linux-android$(NATIVE_SDK)-clang++ -x c++ -std=gnu++11 -stdlib=libc++
ASM := $(CCACHE) $(TOOLCHAIN)/bin/aarch64-linux-android-as

CXXFLAGS := \
	-D__arm64__\
	-D__ARM_NEON__\
	-DANDROID=1\
	-DVK_NO_PROTOTYPES=1\
	-march=armv8-a+fp16\
	-fPIC\
	-fno-exceptions\
	-fno-rtti\
	-funwind-tables\
	-fsigned-char\
	-isysroot $(TOOLCHAIN)/sysroot\
	-glldb\
	-Wno-gnu-string-literal-operator-template\
	# -Werror\

**Comment by stephenhines** [comment]
From the latest version of the [ARM Architecture Reference Manual](https://developer.arm.com/documentation/ddi0487/latest?_ga=2.173870119.528578308.1617992983-4823023.1617992983), it says the following about `FEAT_FP16` on p. A2-79:

```
This feature is OPTIONAL in Armv8.2 implementations, unless one of the following is implemented:
• The Scalable Vector Extension (SVE).
• FEAT_FHM.
```
I don't see any of these as being required for Cortex-A76 or Cortex-A55, which are the two kinds of cores on your device, so it is very likely that the hardware support for FP16 isn't there, and you are correctly being notified that the instruction is illegal on this device.

**Comment by enh-google** [comment]
> Use of this construct works fine on iOS, macOS, and other clang platforms. 

fwiw, i suspect you just haven't tested iOS hard enough... according to wikipedia, their 2017 SoCs didn't have armv8.2 either. arm64 Macs are however new enough that they're all armv8.6.

if you do want to use FP16, you'll need to test at runtime. to do it directly, you'll want `getauxval(AT_HWCAP) & HWCAP_FPHP` --- for some reason it's called FPHP ("half precision") rather than FP16.

**Comment by alecazam** [comment]
Yes, I tested that and it's false on these devices, but I thought that was just access to vcvt_f16_f32 which can convert 4x in one call.   I thought armv8.2 finally requires those instructions to be supported.  Seems a bit late in the game to finally support fp16 conversion, since the GPUs have been using the type since the very beginning.

**Comment by alecazam** [comment]
Our minspec is arm64 on iOS.  That complies with arm8.4 on the 5S.   We're not looking to support anything older that would have been on 32-bit chips.  But we have the same arm64 requirement on Android.   I guess we'll just take a slow path on Android until the compilers and chips address this missing piece more robustly.

**Comment by enh-google** [comment]
> We're not looking to support anything older that would have been on 32-bit chips.

to be clear, i'm still talking about 64-bit chips. the https://en.wikipedia.org/wiki/Apple_A10X and earlier are armv8.1. A11 was (according to wikipedia) their first armv8.2 chip.

**Comment by enh-google** [comment]
> It's unclear what chips and arm version are required for Android. Could use more in-depth docs on this.

i don't think the docs would help much --- you need the ifunc checking HWCAP_FPHP regardless. like srhines said above --- arm v8.2 doesn't _require_ these optional extensions, and (as Arm imply by _not_ mentioning it in https://community.arm.com/developer/tools-software/oss-platforms/b/android-blog/posts/bringing-armv8-2-instructions-to-android-runtime) most Arm cores don't have them.

**Comment by DanAlbert** [comment]
> It's unclear what chips and arm version are required for Android. Could use more in-depth docs on this.

The docs aren't detailed because the _requirement_ isn't detailed. The only thing that's _required_ is the base level aarch64 instruction set. If you only want to target devices with better chips, you can block the CPUs that don't support the features in the Play Console.
