### ISSUE TITLE
SIGVMAP is received when access the pointer  by allocating it dynamically. it works fine ndk10 

### ISSUE THREAD

**Issue by sandeepgargkumar** [android/ndk#1489]
void * CreateMutex ( )
{
	pthread_mutex_t *l_p_mutex;

	l_p_mutex = (pthread_mutex_t*) malloc(sizeof(pthread_mutex_t)); 
       // this is value of l_p_mutex  0xea8670 which is address alocated by Malloc

	*l_p_mutex = (pthread_mutex_t) PTHREAD_MUTEX_INITIALIZER; // it crashes on this line
    //  i got this Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xea8670 in tid 6170

        pthread_mutex_init(l_p_mutex, NULL);
	return (void*) l_p_mutex;
}
please help me to resolve this  it is working fine in NDK10 this issue is come in NDK19

**Comment by DanAlbert** [comment]
https://linux.die.net/man/3/pthread_mutex_init

> Attempting to initialize an already initialized mutex results in undefined behavior.

> In cases where default mutex attributes are appropriate, the macro PTHREAD_MUTEX_INITIALIZER can be used to initialize mutexes that are statically allocated. The effect shall be equivalent to dynamic initialization by a call to pthread_mutex_init() with parameter attr specified as NULL, except that no error checks are performed.

Either initialize with `PTHREAD_MUTEX_INITIALIZER` or call `pthread_mutex_init`, not both, and don't use `PTHREAD_MUTEX_INITIALIZER` on heap allocated mutexes.

Your code also works fine for me on an API 29 x86_64 emulator. You need to fill out the bug template if you want us to be able to investigate.
