### ISSUE TITLE
[BUG] string.compare() and strcmp() disagree on string equality

### ISSUE THREAD

**Issue by hevrard** [android/ndk#1494]
#### Description

When comparing two strings which appear to be equal, strcmp() returns 0 but string.compare() returns 1.

A minimal app that repro the issue is attached: [BugNDKStringCompare.zip](https://github.com/android/ndk/files/6350096/BugNDKStringCompare.zip)

Note that **you need to run this before the app** to be able to repro:

```
adb shell setprop debug.bug.procname com.example.bugndkstringcompare
```

The relevant part of the code is:

```
    // Get process name from /proc/self/cmdline
    std::ifstream t("/proc/self/cmdline");
    auto self = std::string((std::istreambuf_iterator<char>(t)),
                     std::istreambuf_iterator<char>());
    LOG("self:    |%s|", self.c_str());

    // Read from system property
    char sysprop[PROP_VALUE_MAX];
    __system_property_get("debug.bug.procname", sysprop);
    LOG("sysprop: |%s|", sysprop);

    // Compare
    LOG("strcmp(): %d", strcmp(self.c_str(), sysprop));
    LOG("string.compare(): %d", self.compare(sysprop));
```

Then the logcat shows:

```
 I/HUGUES: self:    |com.example.bugndkstringcompare|
 I/HUGUES: sysprop: |com.example.bugndkstringcompare|
 I/HUGUES: strcmp(): 0
 I/HUGUES: string.compare(): 1
```

This illustrates how strcmp() and string.compare() disagree, with apparently string.compare() being wrong.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: `Pkg.Revision = 21.3.6528147`
* Build system: gradle for the minimal app, but this bug was found while working on [AGI](https://github.com/google/agi), which uses Bazel to build.
* Host OS: Linux: gLinux `Debian 5.10.19-1rodete1 (2021-03-11) x86_64 GNU/Linux`
* ABI: arm64
* NDK API level: in the minimal repro app: minSdkVersion 28, targetSdkVersion 30
* Device API level: 30 (Pixel4XL with build: `coral:11/RQ3A.210401.001`)

**Comment by DanAlbert** [comment]
Fascinating. Thanks for all the detail!

**Comment by matled** [comment]
Having a quick look at this: `/proc/self/cmdline` contains a trailing '\0':
```
$ xxd < /proc/self/cmdline 
00000000: 7878 6400                                xxd.
```

I assume self is therefore `foo\0`. The `sysprop` value converted to a `std::string` is likely just `foo`, without the trailing `\0` as part of the the string. `strcmp` will only compare up to `\0` and `string.compare`, operating on `std::string`, compares including the `\0`.

(Drive-by comment, I don't have much context here and no way to verify this right now. Thought this may help debugging this issue, though.)

**Comment by matled** [comment]
Verified on my Linux machine (i.e. not Android/NDK):

```cpp
#include <cstdio>
#include <cstring>
#include <fstream>

int main(int argc, char** argv) {
  std::ifstream t("/proc/self/cmdline");
  auto self = std::string((std::istreambuf_iterator<char>(t)),
                          std::istreambuf_iterator<char>());
  // self: |./test|
  printf("self: |%s|\n", self.c_str());

  // strcmp(): 0
  printf("strcmp(): %d\n", strcmp(self.c_str(), self.c_str()));
  // string.compare(): 1
  printf("string.compare(): %d\n", self.compare(self.c_str()));
  // self.length() = 7
  printf("self.length() = %zu\n", self.length());
  // strlen(self.c_str()) = 6
  printf("strlen(self.c_str()) = %zu\n", strlen(self.c_str()));
}
```

**Comment by hevrard** [comment]
@matled thanks a lot for the detailed follow-up!

I can confirm that I get the same on Android. So the issue appears to be that the C++ string constructed from reading `/proc/self/cmdline` contains `\0` characters.

This is documented in `man proc`:

```
The command-line arguments appear in this file as a set of strings separated by null bytes ('\0'),
with a further null byte after the last string.
```

So this is not an NDK issue.

**Comment by DanAlbert** [comment]
Makes sense to me. Thanks, @matled!
