### ISSUE TITLE
[BUG]  Building the NDK from latest sources fails if 'python' is not on the path.

### ISSUE THREAD

**Issue by dneto0** [android/ndk#1495]
This is the symptom:

#### Environment Details

I'm building the NDK from sources, starting with https://android.googlesource.com/platform/ndk.git and the platform manifest at master-ndk.

I'm using Linux to build it. x86-64, derived from Debian.

'python' is not on my path, as that has been deprecated in favour of python3.

When I build like this:

      mkdir out; cd out
      python3 ../ndk/checkbuild.py

then the build fails with this as one of its errors:

...
libc++: PASS 0/4 FAIL 4/4 SKIP 0/4
FAIL libc++ [armeabi-v7a-16-new]: Traceback (most recent call last):
  File "project/ndk/ndk/ndk/test/builder.py", line 117, in _run_test
    result, additional_tests = test.run(obj_dir, dist_dir, test_filters)
  File "project/ndk/ndk/ndk/test/types.py", line 667, in run
    self.run_lit(lit, ndk_path, libcxx_src, libcxx_install, build_dir,
  File "project/ndk/ndk/ndk/test/types.py", line 618, in run_lit
    subprocess.call(lit_args, stdout=stdout, stderr=stderr)
  File "project/ndk/prebuilts/python3/linux/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "project/ndk/prebuilts/python3/linux/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "project/ndk/prebuilts/python3/linux/lib/python3.9/subprocess.py", line 1819, in _execute_child 
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

The problem appears to be the 'python' at this line: https://android.googlesource.com/platform/ndk.git/+/refs/heads/master/ndk/test/types.py#493  
That's the part of the test scripts that are constructing the command line for a "lit" test.

**Comment by dneto0** [comment]
A workaround is to create a 'python' shell script on my path that forwards to python3:

```
#!/usr/bin/bash
exec /usr/bin/python3 "$@"
```

**Comment by DanAlbert** [comment]
> A workaround is to create a 'python' shell script on my path that forwards to python3:
> 
> ```
> #!/usr/bin/bash
> exec /usr/bin/python3 "$@"
> ```

`sudo apt install python-is-python3` will do that for you :)

Something we should fix either way, since we didn't intend to rely on the host python at all.

**Comment by dneto0** [comment]
> we didn't intend to rely on the host python at all.

Ok.  So it wouldn't be helpful to submit a change that updated the simple "python" to "python3". Make sense.  I'll leave this alone then.

**Comment by DanAlbert** [comment]
It'd hide the break for now but I think we should just fix this to use our bootstrapped Python instead. I don't think it's _much_ more work to do that.

**Comment by DanAlbert** [comment]
Problem is still present, though largely mitigated by the new poetry based workflow (see `docs/Building.md`)

**Comment by jfgoog** [comment]
There are a number of other things that need to be on the path as well, such as bash. We assume that anything Unix-like will have bash, but it is, in fact, problematic if we want builds to be hermetic.

**Comment by DanAlbert** [comment]
This particular problem (`PythonTest` calls `python` directly) should be an easy fix since we already have code for finding the prebuilt python. The hermeticity problem as a whole is quite a bit more work, but most of those problems are also less likely to encounter than this, since debian (or maybe it's just glinux) doesn't include a binary named `python` by default.

**Comment by DanAlbert** [comment]
I fixed this in https://android-review.googlesource.com/c/platform/ndk/+/2518316.
