### ISSUE TITLE
[question] compiling with arm intrinsics

### ISSUE THREAD

**Issue by ImanHosseini** [android/ndk#1496]
buildToolsVersion: '30.0.2' and NDK R29, in build.gradle I do:
```
        externalNativeBuild {
            cmake {
                cppFlags "-DANDROID_ARM_NEON=ON -mfloat-abi=hard"
            }
        }
```
My code includes 'arm_neon.h'. When I build I get:

clang++: warning: argument unused during compilation: '-mfloat-abi=hard' [-Wunused-command-line-argument]
and then:
#error "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softfp or -mfloat-abi=hard"

Why is this happening and what should I do?

**Comment by DanAlbert** [comment]
Remove the flag? It's not the Android ABI.
