### ISSUE TITLE
[BUG] -Wuninitialized doesn't work

### ISSUE THREAD

**Issue by 1bsyl** [android/ndk#1497]
With at least ndk-21e and ndk-23-beta3

`-Wuninitialized ` isn't detecting use of non initialized variables. (Even with `-O2` and `-O0` )

(it's taken into account, since misspelling it, triggers a warning)

some kind of code: 
```
int some_function(void) {
  int foo;

  if (foo & 1) {
    something();
  }
  ...
}
```

**Comment by pirama-arumuga-nainar** [comment]
The warning does trigger in clang 11.0 and 12.0: https://godbolt.org/z/KoT153Edf.  I also checked this in recent AOSP clang prebuilts.

Please share the specific code and command where the expected warning is not triggered.

**Comment by 1bsyl** [comment]
@pirama-arumuga-nainar  sorry, this is my mistake :)
