### ISSUE TITLE
[question] Best practices for project with lots of native dependencies

### ISSUE THREAD

**Issue by venabled** [android/ndk#1510]
Team, 

Thanks for all the great work on NDK and the recent upgrades in documentation / tooling for handling native dependencies.

I have a project where we're building our existing C++ stack to run on Android, currently using CMake externally to build the dependencies using `ExternalProject`, and it's working pretty well.

I can point my library I'm then building in Android Studio / AGP to use the dependencies via `CMAKE_FIND_ROOT_PATH` and it builds everything fine. The issue is when it goes to package the APK, AGP does a good job of grabbing the .so files that are linked to publicly. The issue is that AGP doesn't transitively grab all those other dependencies, so they're not packaged in the NDK.

Originally I just grabbed everything and jammed them into `src/main/jniLibs/$ABI`, and that *almost* worked except there's some duplicates in there. 

So my current quick hack is to make one final external lib that basically lays out my JNI api, and links against everything privately such that AGP doesn't package any external .so's, and I can have external CMake copy them to `src/main/jniLibs/$ABI`.

Do you think I should just bite the bullet and go full prefab? I was originally going down that path via `vcpkg` and/or more ports in your `ndkports` project, but ran into issues with both those paths. Looking more into prefab I think I can pretty easily generate a massive package with my 30+ shared libraries.

**Comment by DanAlbert** [comment]
I think your choices are either building AARs for each of your dependencies (most work, but most reliable), or resolving the duplicates in your jnilibs directory (quick, but manually maintained).

> So my current quick hack is to make one final external lib that basically lays out my JNI api, and links against everything privately such that AGP doesn't package any external .so's, and I can have external CMake copy them to src/main/jniLibs/$ABI.

If you have the option of statically linking everything into a final libapp.so, do that. Always do that. That gets you the best behavior and performance. If not an app but middleware, see https://developer.android.com/ndk/guides/middleware-vendors.

> Do you think I should just bite the bullet and go full prefab?

Well, yeah, but I'm fairly biased :) AGP, vcpkg, and ndkports can all build them. For packages built outside any of those systems you'd need to follow the docs and write your own tooling to assemble the packages.

> I was originally going down that path via vcpkg and/or more ports in your ndkports project, but ran into issues with both those paths

Can you elaborate?

> Looking more into prefab I think I can pretty easily generate a massive package with my 30+ shared libraries.

I assume you're bundling several third party dependencies here, rather than your own SDK that has 30 individual modules? If so, you'd have something much more reusable by making multiple packages.

**Comment by venabled** [comment]
@DanAlbert sorry was heads down and I've been meaning to respond.

> I think your choices are either building AARs for each of your dependencies (most work, but most reliable), or resolving the duplicates in your jnilibs directory (quick, but manually maintained).

Copy, as I have time I think I'll start prefab'n it up. 

> If you have the option of statically linking everything into a final libapp.so, do that. Always do that. That gets you the best behavior and performance. If not an app but middleware, see https://developer.android.com/ndk/guides/middleware-vendors.

After you responded I went this route. There's one or two libraries that I'm having trouble with bugs in their ./configure scripts for doing a fully static build, but I can pick some of the changes from patches in the `vcpkg` tree to get those to work. For my MVP / demo in the short term I don't need those, though. Fully static build seemed to work, along with my manual shared lib stack with the aforementioned manual removal of duplicates. If we end up cleaning up our public API of our internal library I can probably make that go away too.  


> > I was originally going down that path via vcpkg and/or more ports in your ndkports project, but ran into issues with both those paths
> 
> Can you elaborate?
> 

I really like what they're doing with vcpkg, but it is really hard to get a really clean set of ports that work for all their triplets, and even quick variants. For example, after reading this when I went to try and do my full static build, I tried the current vcpkg from master, and it immediately failed on building libiconv as a glib2 dependency. Also there's been a few PR open that I'm waiting to resolve before spending more time writing a custom port stack, e.g.: microsoft/vcpkg#15605 . I think they just have a monumental task of getting that tool to work well for everyone, but maybe with enough time and some more PR's it would be worth re-investing some time into maintaining a working port stack that supports Android, Linux, and Windows.

I had also started with ndkports, merging in commits from some forks ( https://github.com/atsushieno/ndkports, https://github.com/RikkaW/ndkports ) to support Meson, CMake ports. This is probably still a viable option. When I restarted this project I looked again at my fork and tried to get it running but it was in the middle of JCenter meltdown and the kts-runner wouldn't download, and my Gradle/Kotlin skills were still a bit rusty. Also having upstream being hosted on android.googlesource.com makes it hard to collaborate on community adds, and understanding the roadmap for that tool would be great, too.

> > Looking more into prefab I think I can pretty easily generate a massive package with my 30+ shared libraries.
> 
> I assume you're bundling several third party dependencies here, rather than your own SDK that has 30 individual modules? If so, you'd have something much more reusable by making multiple packages.

For the other platforms we support, I've been moving to conda/mamba to build and distribute packages with prebuilt libs and applications, and that's been working great. Have thought about adding an NDK compiler package / prefab back end to that at some point, but haven't worked it all the way through yet.

**Comment by DanAlbert** [comment]
> but it is really hard to get a really clean set of ports that work for all their triplets, and even quick variants.

Yes, we ran into this problem as well. Conan had the same issue. Most of these corpora don't seem to work for Android. I believe vcpkg intended to set up CI for Android at some point, but idk if they did.

> I had also started with ndkports, merging in commits from some forks ( https://github.com/atsushieno/ndkports, https://github.com/RikkaW/ndkports ) to support Meson, CMake ports. This is probably still a viable option. When I restarted this project I looked again at my fork and tried to get it running but it was in the middle of JCenter meltdown and the kts-runner wouldn't download, and my Gradle/Kotlin skills were still a bit rusty. Also having upstream being hosted on android.googlesource.com makes it hard to collaborate on community adds, and understanding the roadmap for that tool would be great, too.

FWIW I've actually converted ndkports to work as a gradle plugin. The work hasn't been submitted because of a CI SNAFU that I'm trying to get folks to resolve, but it should be quite a bit easier for everyone to use after that (plus it'll support testing).

**Comment by venabled** [comment]
> FWIW I've actually converted ndkports to work as a gradle plugin. The work hasn't been submitted because of a CI SNAFU that I'm trying to get folks to resolve, but it should be quite a bit easier for everyone to use after that (plus it'll support testing).

Ok, that would be awesome. Especially if there's a place to add community ports etc. Most of the builds I have are pretty standard, maybe one or two fixes to outdated cmake practices to get stuff to find/link the right targets.

**Comment by DanAlbert** [comment]
> Especially if there's a place to add community ports

I'd created https://github.com/google/prefab/wiki/Package-List for that, but no one really adds to it :) Seems like a tag on the artifact in whatever host people use would work best? I'm only familiar with our feature-lite maven repository so I don't know if that's something the others support or not.

**Comment by DanAlbert** [comment]
(I think the questions here have been answered, lmk if I missed something)

**Comment by venabled** [comment]
Sorry, should have closed it a while ago. Thanks for following up.
