### ISSUE TITLE
[question] android-ndk-r21d causes a problem with type_info comparison for a 3rd party library on ARM64 architectures

### ISSUE THREAD

**Issue by AleksaJanjatovic** [android/ndk#1513]
Hello everyone,
I've encountered a problem while building a 3rd party POCO library (and subsequently reported the problem [here](https://github.com/pocoproject/poco/issues/3289)). The problem seems to arise when we build the library for ARM64. There is a line of POCO library that compares classes of two objects via *operator==*
```
template <typename ValueType>
ValueType* AnyCast(Any* operand)
	/// AnyCast operator used to extract the ValueType from an Any*. Will return a pointer
	/// to the stored value. 
	///
	/// Example Usage: 
	///	 MyType* pTmp = AnyCast<MyType*>(pAny).
	/// Will return NULL if the cast fails, i.e. types don't match.
{
	return operand && operand->type() == typeid(ValueType) 
				? &static_cast<Any::Holder<ValueType>*>(operand->content())->_held
				: 0;
}
```
And due to the next part of the *ndk* code off *__config* file:
```
#ifndef _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT
# ifdef _LIBCPP_OBJECT_FORMAT_COFF // Windows binaries can't merge typeinfos.
# define _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT 0
#else
// TODO: This isn't strictly correct on ELF platforms due to llvm.org/PR37398
// And we should consider defaulting to OFF.
# define _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT 1
#endif
#endif
```
The code is forced to use the implementation for *__unique_impl* of the file *typeinfo*:
```
  typedef
#if defined(__APPLE__) && defined(__LP64__) && !defined(__x86_64__)
    __non_unique_arm_rtti_bit_impl
#elif _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT == 0
    __non_unique_impl
#elif _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT == 1
    __unique_impl
#else
#   error invalid configuration for _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT
#endif
     __impl;
```
Which compares *type_info.name()* pointers instead of doing the string comparison:
```
  struct __unique_impl : __string_impl_base {
    _LIBCPP_INLINE_VISIBILITY _LIBCPP_ALWAYS_INLINE
    static size_t __hash(__type_name_t __v) _NOEXCEPT {
      return reinterpret_cast<size_t>(__v);
    }
    _LIBCPP_INLINE_VISIBILITY _LIBCPP_ALWAYS_INLINE
    static bool __eq(__type_name_t __lhs, __type_name_t __rhs) _NOEXCEPT {
      return __lhs == __rhs; // THIS IS THE RELEVANT CODE
    }
    _LIBCPP_INLINE_VISIBILITY _LIBCPP_ALWAYS_INLINE
    static bool __lt(__type_name_t __lhs, __type_name_t __rhs) _NOEXCEPT {
      return __lhs < __rhs;
    }
  };
```
This seems to cause a problem when multiple libraries use the same class (in this case, libPocoFoundation and libPocoData of the POCO library, and the class "compiled name" is *NSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE*, aka *const char**)

Is there any way this can be chosen with an already built *ndk* or do I need to parse the *CMake* flag -D_LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT=0 and rebuild the *ndk* by myself? Is this maybe handled in the new versions of the ndk? I have found the llvm [patch](https://reviews.llvm.org/rGbe00e8893fdb814e67d8f06401afe869f878c4cf) that relates to this problem, but I was unable to find whether or not this patch was included in the newer versions of the *21 ndk*.

**Comment by AleksaJanjatovic** [comment]
I would just like to add that the POCO library was built as a shared library.

**Comment by DanAlbert** [comment]
No, libc++ is already built, so changing the preprocessor constants used to build it after the fact does nothing. You need to rebuild it if that's the behavior you want, but that is non-standard behavior that will allow false positives for unrelated types.

https://developer.android.com/ndk/guides/common-problems#rttiexceptions_not_working_across_library_boundaries in case you haven't seen it. Those classes need key functions.
