### ISSUE TITLE
[FR][bionic] Consider marking abort as nomerge

### ISSUE THREAD

**Issue by smeenai** [android/ndk#1514]
Because `abort` is marked as `noreturn`, LLVM tail merges calls to it, so if a function has multiple calls to `abort`, it's not possible to distinguish the call sites from each other in a stack trace.

https://bugs.llvm.org/show_bug.cgi?id=42783 was an LLVM bug for this, which resulted in LLVM gaining a `nomerge` attribute to avoid this tail merging. This attribute is exposed to Clang as well, and in particular, https://reviews.llvm.org/D92800 makes it usable as a function attribute, so that you can e.g. mark the declaration of `abort` as `nomerge`.

We've made that change locally (in a wrapper `stdlib.h`) and it works well for us. If it's considered generally useful, it'd be great to have `abort` (and potentially other related functions like `__assert` and `__assert2`) marked as `nomerge` in the NDK headers directly.

**Comment by DanAlbert** [comment]
Nice find 👍 Makes sense to fix the source of truth to me. We still have a chance to get this into r23, I believe.

**Comment by enh-google** [comment]
looks like that's the only noreturn function in libc where this would matter? the assert functions looked plausible, but they'll have distinct messages to disambiguate anyway. and you're not likely to care for any of the exit family.

unfortunately it seems like we don't have a new enough clang? 
```
/usr/local/google/home/enh/aosp/bionic/libc/include/stdlib.h:44:44: error: '__nomerge__' attribute cannot be applied to a declaration
__noreturn void abort(void) __attribute__((__nomerge__));
                ~~~~~                      ^
```

https://clang.llvm.org/docs/AttributeReference.html#nomerge makes it sound like this should work:
> nomerge attribute can also be used as function attribute to prevent all calls to the specified function from merging. It has no effect on indirect calls.

i notice the test case in https://reviews.llvm.org/D92800 was using C++ attribute syntax --- does LLVM require that this be separately enabled for C too?

oh, looks like it's something to do with versioner? this builds fine:
```
diff --git a/libc/include/stdlib.h b/libc/include/stdlib.h
index d7fdb4a52..fd5d4450d 100644
--- a/libc/include/stdlib.h
+++ b/libc/include/stdlib.h
@@ -41,6 +41,9 @@ __BEGIN_DECLS
 #define EXIT_FAILURE 1
 #define EXIT_SUCCESS 0
 
+#if !defined(__BIONIC_VERSIONER)
+__attribute__((nomerge))
+#endif
 __noreturn void abort(void);
 __noreturn void exit(int __status);
 #if __ANDROID_API__ >= 21
```
is versioner getting an old libclang/libLLVM from somewhere?

**Comment by stephenhines** [comment]
> is versioner getting an old libclang/libLLVM from somewhere?

Yes, it is. https://cs.android.com/android/platform/superproject/+/master:bionic/tools/versioner/src/Android.bp;l=8 shows that it is using `llvm-build-host-tools-defaults`, which is only set when building LLVM host tools. https://cs.android.com/android/platform/superproject/+/master:prebuilts/clang-tools/build-prebuilts.sh might be the right script for recreating all of these. Actually, the last time they checked in new binaries is January 2021 (https://android-review.googlesource.com/c/platform/prebuilts/clang-tools/+/1547542). These should probably be updated.

**Comment by pirama-arumuga-nainar** [comment]
https://android-review.googlesource.com/c/platform/prebuilts/clang-tools/+/1727250 updates the clang-tools prebuilts.

**Comment by stephenhines** [comment]
Thank you for updating them. Is there a script for pulling those prebuilts or did you do it manually? It would be great if there were docs for this that lived alongside the prebuilts, so that anyone could easily do this in the future.

**Comment by pirama-arumuga-nainar** [comment]
> It would be great if there were docs for this that lived alongside the prebuilts

https://android.googlesource.com/platform/prebuilts/clang-tools/+/master/README.md, for future reference.

**Comment by enh-google** [comment]
thanks! (both for the update and even more so for the docs!) i'm still hoping we can remove versioner one of these years, but i don't see the others going away any time soon...

https://android-review.googlesource.com/c/platform/bionic/+/1729453 adds the attribute.

note that we don't really recommend that you debug this way... what you really want is something more like:
```
#include <android/set_abort_message.h>

void f(int x) {
  if (x <= 0) {
    android_set_abort_message("x too small!");
    abort();
  }
  if (x >= 1024) {
    android_set_abort_message("x too large");
    abort();
  }
}
```
only ideally hidden behind whatever assertion implementation you're already using (if only so that you can format a string and, in this example, for example, include the actual value of x). the abort message will be called out specially in the tombstone. (requires API level >= 21, so you might need some dlsym()ing if your code also runs on older versions.)

of course, this doesn't help at all if you're just importing some random third-party code, so fixing abort() makes sense anyway.

**Comment by smeenai** [comment]
Thank you, and thanks for the tip about `android_set_abort_message`! I'll pass that on.

**Comment by smeenai** [comment]
Is there anything left to do here, or can it be closed out?

**Comment by DanAlbert** [comment]
Yeah, work here is basically done. It hasn't made it to the NDK yet but it should when we pick up the new sysroot for API finalization.
