### ISSUE TITLE
[BUG] undefined symbols AMotionEvent_fromJava and AInputEvent_release

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#1515]
#### Description

https://github.com/mgood7123/undefined__AMotionEvent_fromJava__AInputEvent_release__repro

```sh
matthewgood@Matthews-MacBook-Pro NDK_BUG_REPRO_UNDEF_SYMBOL % ./build_cross_MacOS.sh 
case 1: undefined symbol: AMotionEvent_fromJava
ld: error: undefined symbol: AMotionEvent_fromJava
>>> referenced by case_01.cpp
>>>               /var/folders/18/g2fjckl56vlcltqdgzd1j6j80000gn/T/case_01-de0461.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)


case 2: undefined symbol: AInputEvent_release
ld: error: undefined symbol: AInputEvent_release
>>> referenced by case_02.cpp
>>>               /var/folders/18/g2fjckl56vlcltqdgzd1j6j80000gn/T/case_02-d04f8d.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

aarch64-linux-android29-clang++

#### Environment Details

* NDK Version: 23.0.7196353-beta2
* Build system: CMake
* Host OS: Mac
* ABI: aarch64
* NDK API level: 
* Device API level: 29

**Comment by DanAlbert** [comment]
You didn't link the libraries that provide those symbols.

**Comment by mgood7123** [comment]
Would it be `-l android` ?

**Comment by mgood7123** [comment]
> You didn't link the libraries that provide those symbols.

Would it be `-l android` ?

**Comment by Deamon87** [comment]
@mgood7123 Yes, but `libandroid.so` has these function only for API lvl 31+

**Comment by mgood7123** [comment]
So only for S (api 31) and above?

**Comment by mgood7123** [comment]
Or R if it is api 31

Q is api 30 right?

So the functions are only on R (Android 12) and above?

**Comment by Deamon87** [comment]
Likely so. You can check it yourself by searching in `${androidSDK}\ndk\23.0.7599858\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\aarch64-linux-android\` folder for other architecture. For me `libandroid.so` from folder `31` only has text `AMotionEvent_fromJava`

PS: it seems `libandroid.so` is used as a stub here and the real lib comes from actual OS, where the app is run. So copying this file to different folder, say `27`, would not work

**Comment by mgood7123** [comment]
Aw, so any app that wants to support api 30 and lower cannot use this if
their not running on api 31 or higher

For example an app running on a device which only supports android 10 or
less will need to find another way?

**Comment by enh-google** [comment]
i couldn't work out why you were confused --- the error message should have told you exactly what you'd done wrong... but it looks like the header file is missing the `__INTRODUCED_IN(31)` annotation. (the `.map.txt` _does_ contain the corresponding `introduced=31` though, which is why you at least get a _link_ error rather than a _runtime_ error.)

reopening to fix the header...

**Comment by enh-google** [comment]
(fix uploaded internally: https://googleplex-android-review.git.corp.google.com/c/platform/frameworks/native/+/15828516)

**Comment by rprichard** [comment]
Fixed in r23b.
