### ISSUE TITLE
[BUG] unable to execute command: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by AlexanderSerov** [android/ndk#1516]
#### Description

/android_sdk/ndk/21.4.7075529# /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -DMXNET_STATIC_IMPORT -DNNVM_STATIC_IMPORT -Dface_sdk_base_EXPORTS -I/android-libs/arm64-v8a-api21/mxnet/include -I/android-libs/arm64-v8a-api21/boost/include/boost-1_69 -I/android-libs/arm64-v8a-api21/OpenSSL/include -I/android-libs/arm64-v8a-api21/curl/include -I/android-libs/arm64-v8a-api21/curlpp/include -I/android-libs/arm64-v8a-api21/OpenCV/sdk/native/jni/include -I/android-libs/arm64-v8a-api21/OpenBLAS/include -I/src/include -I/src/3rdparty/yaml-cpp/include -std=c++11 -fopenmp -o /experiment/overexposure_checker_priv.cpp.o -c /src/src/face_sdk_quality/priv/overexposure_checker_priv.cpp
Stack dump:
0.      Program arguments: /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -cc1 -triple aarch64-none-linux-android21 -emit-obj -mrelax-all -mnoexecstack -disable-free -disable-llvm-verifier -discard-value-names -main-file-name overexposure_checker_priv.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -mllvm -aarch64-fix-cortex-a53-835769=1 -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /experiment/overexposure_checker_priv.cpp.gcno -resource-dir /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.9 -D MXNET_STATIC_IMPORT -D NNVM_STATIC_IMPORT -D face_sdk_base_EXPORTS -I /android-libs/arm64-v8a-api21/mxnet/include -I /android-libs/arm64-v8a-api21/boost/include/boost-1_69 -I /android-libs/arm64-v8a-api21/OpenSSL/include -I /android-libs/arm64-v8a-api21/curl/include -I /android-libs/arm64-v8a-api21/curlpp/include -I /android-libs/arm64-v8a-api21/OpenCV/sdk/native/jni/include -I /android-libs/arm64-v8a-api21/OpenBLAS/include -I /src/include -I /src/3rdparty/yaml-cpp/include -isysroot /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -internal-isystem /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1 -internal-isystem /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/local/include -internal-isystem /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.9/include -internal-externc-isystem /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android -internal-externc-isystem /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/include -internal-externc-isystem /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /android_sdk/ndk/21.4.7075529 -ferror-limit 19 -fmessage-length 0 -fopenmp -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /experiment/overexposure_checker_priv.cpp.o -x c++ /src/src/face_sdk_quality/priv/overexposure_checker_priv.cpp
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      /src/src/face_sdk_quality/priv/overexposure_checker_priv.cpp:50:19: Generating code for declaration 'face_sdk::priv::overexposure_checker_impl::get_overexposure'
4.      /src/src/face_sdk_quality/priv/overexposure_checker_priv.cpp:62:66: LLVM IR generation of compound statement ('{}')
5.      /src/src/face_sdk_quality/priv/overexposure_checker_priv.cpp:63:70: LLVM IR generation of compound statement ('{}')
 #0 0x0000000002bebe02 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2bebe02)
 #1 0x0000000002be94fe llvm::sys::RunSignalHandlers() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2be94fe)
 #2 0x0000000002bec378 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2bec378)
 #3 0x00007febb333f980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #4 0x000000000267ba29 llvm::PointerType::get(llvm::Type*, unsigned int) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x267ba29)
 #5 0x000000000197c8d4 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x197c8d4)
 #6 0x0000000001cae543 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1cae543)
 #7 0x0000000002ec1346 clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP(llvm::Value*, llvm::ArrayRef<llvm::Value*>, bool, bool, clang::SourceLocation, llvm::Twine const&) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ec1346)
 #8 0x0000000002eb38c5 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2eb38c5)
 #9 0x0000000002e9d8ca clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(clang::ArraySubscriptExpr const*, bool) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e9d8ca)
#10 0x0000000002e9cd13 clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(clang::ArraySubscriptExpr const*, bool) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e9cd13)
#11 0x0000000002e90340 clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e90340)
#12 0x0000000002e9bf0a clang::CodeGen::CodeGenFunction::EmitCheckedLValue(clang::Expr const*, clang::CodeGen::CodeGenFunction::TypeCheckKind) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e9bf0a)
#13 0x0000000002ec7085 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ec7085)
#14 0x0000000002eb9d91 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2eb9d91)
#15 0x0000000002ed298d (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ed298d)
#16 0x0000000002eb9d91 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2eb9d91)
#17 0x0000000002ed2f14 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ed2f14)
#18 0x0000000002ebd81d (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ebd81d)
#19 0x0000000002ebd73d clang::CodeGen::CodeGenFunction::EmitCompoundAssignmentLValue(clang::CompoundAssignOperator const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ebd73d)
#20 0x0000000002e90379 clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e90379)
#21 0x0000000002e8fa8a clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e8fa8a)
#22 0x0000000002ee04ad clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee04ad)
#23 0x0000000002ee0c81 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee0c81)
#24 0x0000000002ee03eb clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee03eb)
#25 0x0000000002ee37dd clang::CodeGen::CodeGenFunction::EmitForStmt(clang::ForStmt const&, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee37dd)
#26 0x0000000002ee0662 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee0662)
#27 0x0000000002ee0c81 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee0c81)
#28 0x0000000002ee03eb clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee03eb)
#29 0x0000000002ee37dd clang::CodeGen::CodeGenFunction::EmitForStmt(clang::ForStmt const&, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee37dd)
#30 0x0000000002ee0662 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2ee0662)
#31 0x0000000002eeb27c clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2eeb27c)
#32 0x0000000002e81292 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e81292)
#33 0x0000000002e82135 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2e82135)
#34 0x0000000002dee9df clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dee9df)
#35 0x0000000002de460a clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2de460a)
#36 0x0000000002dd64ab clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd64ab)
#37 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#38 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#39 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#40 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#41 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#42 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#43 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#44 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#45 0x0000000002dd621b clang::CodeGen::CodeGenModule::EmitDeferred() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd621b)
#46 0x0000000002dd4ab9 clang::CodeGen::CodeGenModule::Release() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2dd4ab9)
#47 0x00000000035fc30f (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x35fc30f)
#48 0x00000000035f9956 (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x35f9956)
#49 0x0000000004490e76 clang::ParseAST(clang::Sema&, bool, bool) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x4490e76)
#50 0x000000000354dbac clang::FrontendAction::Execute() (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x354dbac)
#51 0x00000000034a2af0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x34a2af0)
#52 0x00000000035f4b97 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x35f4b97)
#53 0x000000000192790b cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x192790b)
#54 0x0000000001925507 main (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1925507)
#55 0x00007febb237ebf7 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf7)
#56 0x0000000001922029 _start (/android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1922029)
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)
Target: aarch64-none-linux-android21
Thread model: posix
InstalledDir: /android_sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/overexposure_checker_priv-7ee70d.cpp
clang++: note: diagnostic msg: /tmp/overexposure_checker_priv-7ee70d.sh
clang++: note: diagnostic msg:

********************

#### Environment Details

* NDK Version: 21.4.7075529
* Build system:   ANDROID_BUILD_TOOLS_VERSION=30.0.3, ANDROID_CMAKE_VERSION=3.10.2.4988404
* Host OS: Ubuntu 18.04
* ABI: arm64-v8a
* NDK API level: 
* Device API level: 21

**Comment by AlexanderSerov** [comment]
[diagnostics_and_core.zip](https://github.com/android/ndk/files/6610642/diagnostics_and_core.zip)

**Comment by pirama-arumuga-nainar** [comment]
Please attach the files as mentioned in the crash report:

```
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/overexposure_checker_priv-7ee70d.cpp
clang++: note: diagnostic msg: /tmp/overexposure_checker_priv-7ee70d.sh
clang++: note: diagnostic msg:
```

**Comment by AlexanderSerov** [comment]
- The issue reproduced 100% times.
- The key here is the issue is not reproduced if remove -fopenmp flag from compilation command. 
- This issue is not reproduced on ndk r22

**Comment by pirama-arumuga-nainar** [comment]
> This issue is not reproduced on ndk r22

@DanAlbert What's the LTS policy in this case?  Should we patch `r21` with the next LTS, `r23`, around the corner?  (Also note that this only reproduces with `-fopenmp`.

**Comment by DanAlbert** [comment]
r21's support window ends as soon as r23 ships, which should be in July. Given how long it would take us to turn around the fix the release would only be supported for a few weeks at most, so I don't think it makes sense to patch r21 at this point.
