### ISSUE TITLE
[question] FDSAN bug or bug in finalizer implementation?

### ISSUE THREAD

**Issue by CapSel** [android/ndk#1517]
My question is about fdsan reporting socket closing from libc function `close`. Socket was created using libc function `socket`. This is a TCP socket. It is not passed in any way to java and is not created by java and then passed to library. I've got logs from entire life of this FD.

"...but there must be something wrong!"

It seems that:
- SockImpl creates FD
- finalizer on SockImpl closes FD (**should not do it**) **not informing FDSAN**
- JNI calls `socket()` and gets reused FD (same FD that was just recently closed in finalizer)
- JNI calls `close()` and FDSAN screams `ABORT!` and **reports wrong place**

_yes_ - there is another bug in my App using JNI library - not closing socket with `.close`. After spending few hours analysing lifetime of FD in JNI library I narrowed the problem down to "FSAN bug or bug in finalizer implementation".

**Comment by DanAlbert** [comment]
@jmgao

**Comment by enh-google** [comment]
there's not really enough information to go on here (not even what version of Android you're running), but we haven't seen bugs in fdsan or in the SocketImpl finalizer. but if your earlier statement "It is not passed in any way to java and is not created by java and then passed to library" is true, i'm not sure what SocketImpl has to do with your problem anyway?

without a repro case i don't think we can help much here (other than to confirm that there are no known bugs in fdsan).
