### ISSUE TITLE
[question] Incomplete MediaCodec API

### ISSUE THREAD

**Issue by olokobayusuf** [android/ndk#1518]
I'm trying to port my video encoder application from Java to C/C++ in order to avoid bridging across the JNI. Looking at the [NDK media API](https://developer.android.com/ndk/reference/group/media), it looks like a crucial aspect has been omitted:

When using codecs with raw (YUV) buffers, you need to know which specific YUV format is being used by the codec. YUV formats vary depending on the layout and interleaving of the chroma planes. In Java, you can deduce this information by looking at the base addresses and strides of [the image planes](https://developer.android.com/reference/android/media/MediaCodec#getInputImage(int)).

In the NDK, this is practically impossible as far as I can tell. The native `AMediaCodec` provides no API for working with `AHardwareBuffer` (which looks like the equivalent of the Java `Image`). Furthermore, the formats reported by the codec (`getBufferFormat`/`getInputFormat`) don't provide any information about buffer layouts.

So how is one to build an buffer-based encoder using the NDK?

**Comment by DanAlbert** [comment]
We just ship what the platform gives us. If you file a platform bug we can get the folks that can answer the question CC'd.

**Comment by olokobayusuf** [comment]
@DanAlbert where do I file a platform bug? [Here](https://source.android.com/setup/contribute/report-bugs)? Thanks.

**Comment by DanAlbert** [comment]
Yes.

**Comment by olokobayusuf** [comment]
Done. [Here's the ticket](https://issuetracker.google.com/issues/190784665) for reference. Closing this issue.
