### ISSUE TITLE
[BUG] localeconv is declared for API<21 compilation but with no definition

### ISSUE THREAD

**Issue by serhiihuralniksc** [android/ndk#1520]
#### Description

Simple program that uses `localeconv()` fails at link step for pre-Lollypop builds.
Sources:
````
/* main.c */
#include <locale.h>

int main(int argc, char **argv) {
    (void) argc;
    (void) argv;

    (void) localeconv();

    return 0;
}

# CMakeLists.txt
cmake_minimum_required(VERSION 3.12)
project(LocaleTest C)
add_executable(LocaleTest main.c)
````

Build:
```
$ mkdir build && cd $_
$ cmake ../ -DCMAKE_TOOLCHAIN_FILE=/my/path/to/android-ndk-r23-beta5/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=19
$ make LocaleTest
Scanning dependencies of target LocaleTest
[ 50%] Linking C executable LocaleTest
ld: error: undefined symbol: localeconv
>>> referenced by main.c:8 (/home/shuralnik/locale_test/main.c:8)
>>>               CMakeFiles/LocaleTest.dir/main.c.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/LocaleTest.dir/build.make:102: recipe for target 'LocaleTest' failed
make[3]: *** [LocaleTest] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/LocaleTest.dir/all' failed
make[2]: *** [CMakeFiles/LocaleTest.dir/all] Error 2
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/LocaleTest.dir/rule' failed
make[1]: *** [CMakeFiles/LocaleTest.dir/rule] Error 2
Makefile:137: recipe for target 'LocaleTest' failed
make: *** [LocaleTest] Error 2
```
Brief investigation shows that `localeconv()` is provided by platform since API 21. But it is nevertheless declared in `<locale.h>` even for older APIs. `android_support` also has it declared in its `locale.h` but this declaration is not accompanied by implementation in its source files.

What is the reason for this function to be defined in headers for old APIs but with no implementation from either platform or support lib? Should this declaration be guarded? (Or better have an implementation in support lib)

#### Environment Details

* NDK Version: 23.0.7421159-beta5
* Build system: CMake (though should not be related)
* Host OS: `Linux L9KZ7773 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* ABI: armeabi-v7a
* NDK API level: 19
* Device API level: N/A

**Comment by enh-google** [comment]
as in most of these cases, "blame libc++"... <clocale> unconditionally has a `using ::localeconv`, so we need a declaration. (afaict, uselocale() is the only one of these functions that libc++ is really _using_ as opposed to `using` :-) 

i notice that there's a llvm-libc++/include/support/xlocale/__nop_locale_mgmt.h for newlib, and although #including that on API levels < 21 might remove a bit of cruft from the NDK proper, it wouldn't actually address your problem.

i did try to fix this upstream with https://reviews.llvm.org/D87950 but they didn't like that.

there's a new `[[clang::using_if_exists]]` since https://reviews.llvm.org/D90188 but i don't know if anyone retrofitted that to libc++? danalbert's working on getting us back on the libc++ update train right now, so once that's done, rewriting https://reviews.llvm.org/D87950 to use the new attribute sounds like a good idea, and should let us remove this (modulo uselocale(), which might need to stay?).

**Comment by enh-google** [comment]
ooh, nice --- looks like ldionne just did it recently: https://github.com/llvm/llvm-project/blob/main/libcxx/include/clocale

he seems to have done it for _all_ the `using`s everywhere, so we should be able to do some cleanup once danalbert's update is in...

**Comment by serhiihuralniksc** [comment]
Thanks for a quick response!
> unconditionally has a `using ::localeconv`

It is clear to me now why this declaration was not guarded :)

Well if disregard C++ side, I've just noticed that it looks like `localeconv()` is a part of C89, so probably it should always be available. Otherwise it is really weird to check for presence of something that is mandated by the most ancient C standard (and was not deprecated yet).
Do you think it is possible to add some stub to a support lib to satisfy builds for older targets? Though I barely imagine if it would need some awareness about Bionic' internal state to work properly.

**Comment by enh-google** [comment]
i don't think we'll add a stub in the NDK at this point --- we're so close to everything older than API level 21 being obsolete anyway that i'd guess it'll be removed this time next year.

note that bionic only supports the C/POSIX locale anyway, so there's nothing interesting available from localeconv() on Android --- the decimal point is "." and everything else is "". (unfortunately we still don't have icu4c exposed in the NDK, so for real i18n/l10n Java is probably your best bet [certainly if you're going back as far as API level 19].)

**Comment by serhiihuralniksc** [comment]
> note that bionic only supports the C/POSIX locale anyway

That's a good point, then it should be very easy for me to conditionally provide that stub right in my code to make all third-parties to be happy when linking.
Basically I have all answers to my questions now. Thanks for help!

**Comment by DanAlbert** [comment]
> Well if disregard C++ side, I've just noticed that it looks like `localeconv()` is a part of C89, so probably it should always be available

Sadly until about API 21 the libc API was quite neglected... it basically only covered anything that was needed by the platform. 

> Do you think it is possible to add some stub to a support lib to satisfy builds for older targets?

So, we have that: https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/sources/android/support/. I'm not sure why it didn't work for you. Definitely something to investigate.

**Comment by serhiihuralniksc** [comment]
> So, we have that: https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/sources/android/support/. I'm not sure why it didn't work for you.

Yup, I saw that but somehow there is no `localeconv()` - https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/sources/android/support/src/locale_support.cpp Probably nobody noticed or used it. Or maybe I was looking in a wrong file.

**Comment by serhiihuralniksc** [comment]
I believe this issue is interesting for a very few folks but anyway.
I've accidentally noticed that NDK indeed has `localeconv()` in `libandroid_support.a`:
```
$ readelf --syms --wide ~/tools/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/libandroid_support.a | grep locale
File: /home/shuralnik/tools/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/libandroid_support.a(locale.o)
     1: 00000000     0 FILE    LOCAL  DEFAULT  ABS locale.cpp
     ...
    41: 00000000    59 FUNC    GLOBAL HIDDEN     7 localeconv
    ...
File: /home/shuralnik/tools/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/libandroid_support.a(locale_support.o)
     1: 00000000     0 FILE    LOCAL  DEFAULT  ABS locale_support.cpp
    ...
```
But it comes from `locale.cpp` which is missed in NDK' support sources. It is interesting that `locale_support.cpp` is also presented in support archive. So packaged `android_support` binaries and sources should be out of sync.

And what I don't really understand now is why linker is unable to find `localeconv()`. It is even more weird when I provide my own  `localeconv()`  stub in project sources - this time linker fails due to duplicated symbol.

**Comment by enh-google** [comment]
> Probably nobody noticed or used it. Or maybe I was looking in a wrong file.

you were looking the wrong file. where possible, libandroid_support uses the exact same code that's in bionic. you were looking at the _exceptions_ where we can't do that for some reason. here's where localeconv() gets pulled in:

https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/sources/android/support/Android.mk;l=40

> But it comes from locale.cpp which is missed in NDK' support sources.

yeah, as you can see from the makefile above, it's actually coming straight out of bionic.

> And what I don't really understand now is why linker is unable to find localeconv().

what's the exact link line of the failing linker invocation?

**Comment by serhiihuralniksc** [comment]
> you were looking the wrong file

Got you, no more questions

> what's the exact link line of the failing linker invocation?
```
[2/2] Linking C executable LocaleTest
FAILED: LocaleTest 
: && /home/shuralnik/tools/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi19 --gcc-toolchain=/home/shuralnik/tools/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/shuralnik/tools/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/LocaleTest.dir/main.c.o -o LocaleTest  -latomic -lm && :
ld: error: undefined symbol: localeconv
>>> referenced by main.c:8 (../main.c:8)
>>>               CMakeFiles/LocaleTest.dir/main.c.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
I used demo from the description. Note that this is a C executable. If changed to CXX - it works fine, probably because in the latter case `android_support` is pulled in via `libc++.a` script, which has it for old targets.

**Comment by enh-google** [comment]
> If changed to CXX - it works fine, probably because in the latter case android_support is pulled in via libc++.a script, which has it for old targets.

yeah, that sounds right (since libandroid_support was originally added to get libc++ working on old OS versions). i'll leave this open for @DanAlbert though, since i'm not sure whether it's deliberate or accidental that we don't also add it for C...

**Comment by DanAlbert** [comment]
> i'm not sure whether it's deliberate or accidental that we don't also add it for C...

Deliberate. Can't use libc++ without it so it's unconditional there, but for C there are tradeoffs. It might be preferable to avoid using some functions (especially in the cases where you're getting a no-op implementation like all the locale code) than to bloat your APK with libandroid_support. Should be able to link manually with `-landroid_support`.
