### ISSUE TITLE
[question]I modify some source code in llvm, i want to rebuild aarch64-linux-android21-clang

### ISSUE THREAD

**Issue by dentiscalprum** [android/ndk#1521]
Can you provide a way to rebuild aarch64-linux-android21-clang?
thx!

**Comment by pirama-arumuga-nainar** [comment]
https://android.googlesource.com/toolchain/llvm_android/#instructions-to-rebuild-a-particular-toolchain-release

**Comment by dentiscalprum** [comment]
> https://android.googlesource.com/toolchain/llvm_android/#instructions-to-rebuild-a-particular-toolchain-release

According to the above method, only compiler-rt is recompiled, and aarch64-linux-android21-clang is not recompiled.

**Comment by pirama-arumuga-nainar** [comment]
I'm not sure I understand.  Which source file did you modify in that version?

The above script will create `out/install/linux-x86/clang-dev/bin/clang-<major-version>`, which can be copied over `aarch64-linux-android21-clang`.

**Comment by dentiscalprum** [comment]
This file llvm-toolchain/toolchain/llvm-project/llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp.
Thx!

**Comment by pirama-arumuga-nainar** [comment]
> The above script will create out/install/linux-x86/clang-dev/bin/clang-<major-version>, which can be copied over aarch64-linux-android21-clang.

This step still should help.  Try a clean build (after `rm -rf out`) if you think something is broken with the incremental build.

**Comment by dentiscalprum** [comment]
> > The above script will create out/install/linux-x86/clang-dev/bin/clang-, which can be copied over aarch64-linux-android21-clang.
> 
> This step still should help. Try a clean build (after `rm -rf out`) if you think something is broken with the incremental build.

This file **out/install/linux-x86/clang-dev/bin/clang-<major-version>** 
Can this file generate native code for all platforms, such as: aarch64, x86-64

**Comment by pirama-arumuga-nainar** [comment]
> This file out/install/linux-x86/clang-dev/bin/clang-
Can this file generate native code for all platforms, such as: aarch64, x86-64

yes

**Comment by dentiscalprum** [comment]
> I'm not sure I understand. Which source file did you modify in that version?
> 
> The above script will create `out/install/linux-x86/clang-dev/bin/clang-<major-version>`, which can be copied over `aarch64-linux-android21-clang`.

sorry, i didn't find this file `out/install/linux-x86/clang-dev/bin/clang-<major-version>`
this is the out directory
```cpp
drwxr-xr-x 34 root root 4096 6月  15 22:35 lib
drwxr-xr-x 24 root root 4096 6月  15 10:15 llvm-project
drwxr-xr-x  6 root root 4096 6月  15 19:23 platform_stubs
drwxr-xr-x 18 root root 4096 6月  15 22:34 stage1
drwxr-xr-x  6 root root 4096 6月  15 11:57 stage1-install
drwxr-xr-x 21 root root 4096 6月  15 22:35 stage2
drwxr-xr-x 11 root root 4096 6月  15 22:36 stage2-install
drwxr-xr-x  4 root root 4096 6月  15 19:23 sysroots

**Comment by pirama-arumuga-nainar** [comment]
> > I'm not sure I understand. Which source file did you modify in that version?
> > The above script will create `out/install/linux-x86/clang-dev/bin/clang-<major-version>`, which can be copied over `aarch64-linux-android21-clang`.
> 
> sorry, i didn't find this file `out/install/linux-x86/clang-dev/bin/clang-<major-version>`
> this is the out directory

Did `python toolchain/llvm_android/build.py` complete successfully?  If so, `out/install...` should be created.  You can also use `out/stage2-install/bin/clang-<major-version>` but it's not stripped and you may want to run `strip` on it if you prefer.

**Comment by dentiscalprum** [comment]
> > > I'm not sure I understand. Which source file did you modify in that version?
> > > The above script will create `out/install/linux-x86/clang-dev/bin/clang-<major-version>`, which can be copied over `aarch64-linux-android21-clang`.
> > 
> > 
> > sorry, i didn't find this file `out/install/linux-x86/clang-dev/bin/clang-<major-version>`
> > this is the out directory
> 
> Did `python toolchain/llvm_android/build.py` complete successfully? If so, `out/install...` should be created. You can also use `out/stage2-install/bin/clang-<major-version>` but it's not stripped and you may want to run `strip` on it if you prefer.

The program compiled with `aarch64-linux-android26-clang` and the compiled result of `out/install/linux-x86/clang-dev/bin/clang-11` are different, `out/install/linux-x86/clang-dev/bin/clang- 11` compiled program can be run on ubuntu, but the former is not. I want to run it under android adb after compiling. I would like to ask you whether the compiled programs are the same. 
thx!!!

**Comment by pirama-arumuga-nainar** [comment]
> The program compiled with aarch64-linux-android26-clang and the compiled result of out/install/linux-x86/clang-dev/bin/clang-11 are different, out/install/linux-x86/clang-dev/bin/clang- 11 compiled program can be run on ubuntu, but the former is not. I want to run it under android adb after compiling. I would like to ask you whether the compiled programs are the same.

Are the outputs are different *after* overwriting `aarch64-linux-android26-clang` with `out/install/linux-x86/clang-dev/bin/clang- 11`?  Or are you invoking `out/install/linux-x86/clang-dev/bin/clang- 11` directly?

**Comment by dentiscalprum** [comment]
yes, `out/install/linux-x86/clang-dev/bin/clang-11` outputs elf, while `aarch64-linux-android26-clang` outputs file which can't  run in linux

**Comment by pirama-arumuga-nainar** [comment]
Then it's working as intended.  When invoked as `clang-11`, sources get compiled for the host OS, which is ubuntu, in your case.  When invoked as `aarch64-linux-android26-clang`, clang detects the target from the progname and compiles for `aarch64-linux-android`, which will produce executables for Android.

**Comment by dentiscalprum** [comment]
> Then it's working as intended. When invoked as `clang-11`, sources get compiled for the host OS, which is ubuntu, in your case. When invoked as `aarch64-linux-android26-clang`, clang detects the target from the progname and compiles for `aarch64-linux-android`, which will produce executables for Android.

how should i do to use clang-11 to produce executables for Android ? thanks!!!

**Comment by pirama-arumuga-nainar** [comment]
`cp clang-11 <path-to/aarch64-linux-android26-clang` would be the best way to use this updated clang.

**Comment by dentiscalprum** [comment]
> `cp clang-11 <path-to>/aarch64-linux-android26-clang` would be the best way to use this updated clang.

oh thank you very much! i will try
