### ISSUE TITLE
Why is "'auto' not allowed in function prototype", despite --std=gnu++2a|c++2a?

### ISSUE THREAD

**Issue by 100xCoder** [android/ndk#1525]
I want to use my own math library, for which this feature is needed. This library can be compiled successfully with all the major compilers, and there's even instances running on people's webbrowsers that were able to be built with emscripten, which is clang++ for webassembly. In none of these environments does this problem occur.
Then, since it's also seemingly just a clang++ for android in the NDK, but then what is different? Is the version older?
This appears to be the only thing which is getting in the way of my application of this library to the Android platform. I don't feel much for downgrading my code legibility at thousands of places throughout the code.
Please help me understand.

**Comment by rprichard** [comment]
I tried to reproduce this and wasn't able to. Do you have an example?

test.cpp:
```
auto foo() { return 42; }
```
```
$ /x/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ test.cpp -S
$ /x/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ test.cpp -S -std=c++2a
```
The Clang compiler driver defaults to C++14, which added support for `auto` in function prototypes.

**Comment by 100xCoder** [comment]
class Shambles {
public:
    Shambles(auto x) { }
};

This is an actual case which doesn't compile in my android studio.
I'm new to Android development, and may have misconfigured something.
I added the -std=gnu++2a to CMAKE_CXX_FLAGS. Changing it to c++17 breaks more things
expecting c++20, so I guessed that it's the right place to set the std.

The output for Shambles above:
C:\my\app\src\main\cpp\shader.hpp:27:12: error: 'auto' not allowed in function prototype

I'm on Windows 10, and installed Android Studio from the website only last week.
The NDK came from the SDK Manager inside Android Studio.

Now I did take the sample 'EndlessTunnel' as a starting point. Can that have made a difference?

Build log:
Build command failed.
Error while executing process C:\Users\crist\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\Slideo\app\.cxx\cmake\debug\x86 game}
ninja: Entering directory `C:\Slideo\app\.cxx\cmake\debug\x86'
[1/25] Building CXX object CMakeFiles/game.dir/anim.cpp.o
FAILED: CMakeFiles/game.dir/anim.cpp.o 
C:\Users\crist\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android24 --gcc-toolchain=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgame_EXPORTS -IC:/Slideo/app/src/main/cpp -IC:/Slideo/app/src/main/cpp/data -IC:/Slideo/app/src/main/cpp/math -IC:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/sources/android/native_app_glue -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++2a -Wall -O0 -fno-limit-debug-info  -fPIC   -DGLM_FORCE_SIZE_T_LENGTH -DGLM_FORCE_RADIANS -MD -MT CMakeFiles/game.dir/anim.cpp.o -MF CMakeFiles\game.dir\anim.cpp.o.d -o CMakeFiles/game.dir/anim.cpp.o -c C:/Slideo/app/src/main/cpp/anim.cpp
In file included from C:/Slideo/app/src/main/cpp/anim.cpp:16:
In file included from C:/Slideo/app/src/main/cpp/anim.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/shape_renderer.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/engine.hpp:28:
C:/Slideo/app/src/main/cpp/shader.hpp:27:14: error: 'auto' not allowed in function prototype
    Shambles(auto x) { }
             ^~~~
1 error generated.
[2/25] Building CXX object CMakeFiles/game.dir/ascii_to_geom.cpp.o
FAILED: CMakeFiles/game.dir/ascii_to_geom.cpp.o 
C:\Users\crist\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android24 --gcc-toolchain=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgame_EXPORTS -IC:/Slideo/app/src/main/cpp -IC:/Slideo/app/src/main/cpp/data -IC:/Slideo/app/src/main/cpp/math -IC:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/sources/android/native_app_glue -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++2a -Wall -O0 -fno-limit-debug-info  -fPIC   -DGLM_FORCE_SIZE_T_LENGTH -DGLM_FORCE_RADIANS -MD -MT CMakeFiles/game.dir/ascii_to_geom.cpp.o -MF CMakeFiles\game.dir\ascii_to_geom.cpp.o.d -o CMakeFiles/game.dir/ascii_to_geom.cpp.o -c C:/Slideo/app/src/main/cpp/ascii_to_geom.cpp
In file included from C:/Slideo/app/src/main/cpp/ascii_to_geom.cpp:16:
In file included from C:/Slideo/app/src/main/cpp/ascii_to_geom.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/engine.hpp:28:
C:/Slideo/app/src/main/cpp/shader.hpp:27:14: error: 'auto' not allowed in function prototype
    Shambles(auto x) { }
             ^~~~
1 error generated.
[3/25] Building CXX object CMakeFiles/game.dir/dialog_scene.cpp.o
FAILED: CMakeFiles/game.dir/dialog_scene.cpp.o 
C:\Users\crist\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android24 --gcc-toolchain=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgame_EXPORTS -IC:/Slideo/app/src/main/cpp -IC:/Slideo/app/src/main/cpp/data -IC:/Slideo/app/src/main/cpp/math -IC:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/sources/android/native_app_glue -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++2a -Wall -O0 -fno-limit-debug-info  -fPIC   -DGLM_FORCE_SIZE_T_LENGTH -DGLM_FORCE_RADIANS -MD -MT CMakeFiles/game.dir/dialog_scene.cpp.o -MF CMakeFiles\game.dir\dialog_scene.cpp.o.d -o CMakeFiles/game.dir/dialog_scene.cpp.o -c C:/Slideo/app/src/main/cpp/dialog_scene.cpp
In file included from C:/Slideo/app/src/main/cpp/dialog_scene.cpp:16:
In file included from C:/Slideo/app/src/main/cpp/anim.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/shape_renderer.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/engine.hpp:28:
C:/Slideo/app/src/main/cpp/shader.hpp:27:14: error: 'auto' not allowed in function prototype
    Shambles(auto x) { }
             ^~~~
1 error generated.
[4/25] Building CXX object CMakeFiles/game.dir/obstacle_generator.cpp.o
FAILED: CMakeFiles/game.dir/obstacle_generator.cpp.o 
C:\Users\crist\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android24 --gcc-toolchain=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgame_EXPORTS -IC:/Slideo/app/src/main/cpp -IC:/Slideo/app/src/main/cpp/data -IC:/Slideo/app/src/main/cpp/math -IC:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/sources/android/native_app_glue -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++2a -Wall -O0 -fno-limit-debug-info  -fPIC   -DGLM_FORCE_SIZE_T_LENGTH -DGLM_FORCE_RADIANS -MD -MT CMakeFiles/game.dir/obstacle_generator.cpp.o -MF CMakeFiles\game.dir\obstacle_generator.cpp.o.d -o CMakeFiles/game.dir/obstacle_generator.cpp.o -c C:/Slideo/app/src/main/cpp/obstacle_generator.cpp
In file included from C:/Slideo/app/src/main/cpp/obstacle_generator.cpp:18:
In file included from C:/Slideo/app/src/main/cpp/obstacle_generator.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/engine.hpp:28:
C:/Slideo/app/src/main/cpp/shader.hpp:27:14: error: 'auto' not allowed in function prototype
    Shambles(auto x) { }
             ^~~~
1 error generated.
[5/25] Building CXX object CMakeFiles/game.dir/obstacle.cpp.o
FAILED: CMakeFiles/game.dir/obstacle.cpp.o 
C:\Users\crist\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android24 --gcc-toolchain=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgame_EXPORTS -IC:/Slideo/app/src/main/cpp -IC:/Slideo/app/src/main/cpp/data -IC:/Slideo/app/src/main/cpp/math -IC:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/sources/android/native_app_glue -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++2a -Wall -O0 -fno-limit-debug-info  -fPIC   -DGLM_FORCE_SIZE_T_LENGTH -DGLM_FORCE_RADIANS -MD -MT CMakeFiles/game.dir/obstacle.cpp.o -MF CMakeFiles\game.dir\obstacle.cpp.o.d -o CMakeFiles/game.dir/obstacle.cpp.o -c C:/Slideo/app/src/main/cpp/obstacle.cpp
In file included from C:/Slideo/app/src/main/cpp/obstacle.cpp:17:
In file included from C:/Slideo/app/src/main/cpp/obstacle.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/engine.hpp:28:
C:/Slideo/app/src/main/cpp/shader.hpp:27:14: error: 'auto' not allowed in function prototype
    Shambles(auto x) { }
             ^~~~
1 error generated.
[6/25] Building CXX object CMakeFiles/game.dir/input_util.cpp.o
FAILED: CMakeFiles/game.dir/input_util.cpp.o 
C:\Users\crist\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android24 --gcc-toolchain=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgame_EXPORTS -IC:/Slideo/app/src/main/cpp -IC:/Slideo/app/src/main/cpp/data -IC:/Slideo/app/src/main/cpp/math -IC:/Users/crist/AppData/Local/Android/Sdk/ndk/21.2.6472646/sources/android/native_app_glue -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++2a -Wall -O0 -fno-limit-debug-info  -fPIC   -DGLM_FORCE_SIZE_T_LENGTH -DGLM_FORCE_RADIANS -MD -MT CMakeFiles/game.dir/input_util.cpp.o -MF CMakeFiles\game.dir\input_util.cpp.o.d -o CMakeFiles/game.dir/input_util.cpp.o -c C:/Slideo/app/src/main/cpp/input_util.cpp
In file included from C:/Slideo/app/src/main/cpp/input_util.cpp:17:
In file included from C:/Slideo/app/src/main/cpp/input_util.hpp:19:
In file included from C:/Slideo/app/src/main/cpp/engine.hpp:28:
C:/Slideo/app/src/main/cpp/shader.hpp:27:14: error: 'auto' not allowed in function prototype
    Shambles(auto x) { }
             ^~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by rprichard** [comment]
You're running NDK 21.2.6472646 (i.e. NDK r21c). It looks like that C++20 feature was added in NDK r22:
```
$ /x/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ -std=c++2a test.cpp -S
test.cpp:1:10: error: 'auto' not allowed in function prototype
void foo(auto i) {}
         ^~~~
1 error generated.
$ /x/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ -std=c++2a test.cpp -S
<success>
```
It also looks like the NDK r22 compiler accepts `-std=c++20` in addition to `-std=c++2a`.

FWIW, if you need an LTS NDK release, NDK r23 is the next LTS release and should be out soon-ish (a month or so maybe?).

**Comment by 100xCoder** [comment]
Yep, r22 does it. Thanks.
