### ISSUE TITLE
[BUG] ld: undefined symbol: glGetIntegeri_v and glDispatchCompute

### ISSUE THREAD

**Issue by 100xCoder** [android/ndk#1533]
Steps to reproduce: try to link against the function in the subject.
I think I'm using the latest everything. That's r22.

**Comment by 100xCoder** [comment]
Also, I have OpenGLES 3.2 on my phone, but I can't link to glDispatchCompute. I didn't even consider the possibility of this.
```
ld: error: undefined symbol: glDispatchCompute
```

**Comment by rprichard** [comment]
> Also, I have OpenGLES 3.2 on my phone, but I can't link to glDispatchCompute. I didn't even consider the possibility of this.
> 
> ```
> ld: error: undefined symbol: glDispatchCompute
> ```

This `ld` error is a build-time linker error, so the software installed on your phone isn't relevant yet.

I think you need to link against `libGLESv3.so` (both at build-time and run-time). Maybe you need to add `-lGLESv3` to a list of ldflags somewhere? What build system are you using (e.g. Gradle, cmake, ndk-build, etc.)?

That shared library is available starting with API 18 (Android 4.3), so you also need to link against a new-enough set of stub libraries. If you're using Gradle, setting `minSdkVersion` to 18 or higher should work. If you're invoking the Clang driver, use one with 18 or above (e.g. `armv7a-linux-androideabi18-clang++`). If you're using ndk-build without Gradle, set [`APP_PLATFORM`](https://developer.android.com/ndk/guides/application_mk#app_platform) to `android-18` or up.

**Comment by 100xCoder** [comment]
Oh my god, thank you. I also didn't consider changing the linker flags. My Gradle's minSdkVersion is 28, though, and that's not solving it automatically at all. I am using CMake, so I guess I just needed to change the CMakelists.txt. Thanks, a million! :-)
