### ISSUE TITLE
[question] Using libc++ with unstable ABI in Android apps

### ISSUE THREAD

**Issue by DoDoENT** [android/ndk#1534]
I'm using NDK r22b with a CMake-based build system.

I'm aware that it's possible to build libc++ with unstable ABI. This gives the benefit of more efficient STL implementations at the cost of not being binary compatible with binaries built.

Since we control the entire codebase of our apps and we can rebuild everything from the source, I would like to investigate the possibility of using libc++ with unstable ABI in order to get smaller and possibly faster final binaries.

However, in the days before CMake, NDK shipped with support for building your own version of STL using the `ndk-build` mechanism. I see that even in r22b there are folders `sources/cxx-stl/llvm-libc++` and `sources/cxx-stl/llvm-libc++abi`, but the `llvm-libc++` only provides the `ndk-build` module which instructs to use `build/tools/build-cxx-stl.sh` script which does not exist anymore, so I guess this module is probably outdated. On the other hand, the `llvm-libc++abi` folder does contain a `CMakeLists.txt`, but it expects to be part of the LLVM monorepo.

I would like to build my own version of libc++ from the sources shipped with the NDK, but with custom flags - most notably disabled exceptions and RTTI and with unstable libc++ ABI. Are there any hints on how to do so, without the need to reverse the entire NDK build system and write everything from scratch?

Also, since I'm aware that Google advocates for breaking the ABI in STL and that the emscripten toolchain (also majorly sponsored by Google, just like the Android and NDK) already uses the unstable libc++ ABI by default, do you have any plans on giving the same possibility in the official release of the NDK? For example, a CMake module for the custom building of the shipped libc++ would be great and akin to the already provided `ndk-build` modules.

I'm really interested in what other developers using NDK think about this and especially what is the position of the @DanAlbert and the NDK team about this idea.

**Comment by DoDoENT** [comment]
[Here](https://godbolt.org/z/zrza1Phds) is a Godbolt example of what I'm talking about. The stock version of libc++ has a flawed implementation of `std::variant`, which is fixed in the unstable-ABI version. This version also contains other STL fixes that require ABI breakage.

You can see that GCC is not affected, nor clang when using libc++ with unstable ABI (or when using GCC's STL, but this is no longer available in NDK). This code should compile, but it doesn't:

```
#include <cstdint>
#include <variant>

enum class E1 : std::uint8_t
{
    First,
    Second
};

enum class E2 : std::uint8_t
{
    First,
    Second
};

using T = std::variant< E1, E2 >;
static_assert( sizeof( T ) == 2 )
```

**Comment by DanAlbert** [comment]
> Are there any hints on how to do so, without the need to reverse the entire NDK build system and write everything from scratch?

If your `minSdkVersion` is 21 or higher, you _should_ (I've never tried) just be able to build libc++ from the LLVM repo using the NDK. If you need pre-21 support you need libandroid_support, which only lives in our tree. You could copy it, but it stops being quite as simple.

> ... already uses the unstable libc++ ABI by default, do you have any plans on giving the same possibility in the official release of the NDK?

One of these days we'll take the ABI break. Aside from the `std::variant` issue, there are a handful of smaller improvements as well. Whether we do that by shipping both and old and new ABI variant for a while or with a full break isn't something I can predict with much certainty right now, but I'd guess we'd need to do the former for at least an LTS cycle. r10 -> r11 was an ABI break and it was quite painful, and that was only for the subset of developers using libc++ at the time, which I hope was small given the condition of the NDK's libc++ port in r10.

> For example, a CMake module for the custom building of the shipped libc++ would be great and akin to the already provided ndk-build modules.

We're working toward making sure that the upstream (that is, llvm/llvm-project/libcxx) libc++ build Just Works. Better that way since then you're not bound by our update cycles either. It won't be a thing I'd ever strongly endorse because outside certain situations (like yours, where it's perfectly safe), it's a great way to shoot yourself in the foot with compatibility against third party libraries.

(am closing since I don't think there's NDK work to do here, but that doesn't mean we stop reading, so if you have follow up questions I'm still listening)

**Comment by DoDoENT** [comment]
Based on [this comment](https://github.com/android/ndk/issues/1477#issuecomment-878399206), I've created my own "distribution" of NDK that contains `libc++` and `libc++abi` built with LTO and without exceptions. Since we are internally using `conan` for distributing both toolchains (like NDK) and packages (internal libraries), I just changed the recipe that packages the NDK to also compile the `libc++` and `libc++abi` directly from NDK's LLVM fork.

Since this conan recipe is not part of any IP, I'll share it here in case anyone makes use of it:

```python
from conans import ConanFile, tools
import os


# Based on https://github.com/lasote/conan-android-ndk/blob/master/conanfile.py
# and on https://github.com/lasote/conan-android-toolchain/blob/master/conanfile.py
class AndroidNDKConan(ConanFile):
    name = "AndroidNdk"
    version = "r22b"
    url = "https://developer.android.com/ndk/downloads/"
    description = "Android NDK toolchain"
    settings = "os_build", "arch_build", "os", "arch"
    exports_sources = 'llvm-build.patch'
    no_copy_source = True

    @property
    def _host_arch(self):
        if self.settings.arch_build == 'macos_fat':
            return 'x86_64'
        else:
            return self.settings.arch_build

    @property
    def _llvm_tag_name(self):
        ndk_version_number = int(''.join(filter(str.isdigit, self.version)))
        return f'ndk-r{ndk_version_number}'

    @property
    def _abis(self):
        return ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64']

    def source(self):
        os_name = str(self.settings.os_build).lower().replace('macos', 'darwin')

        url = "https://dl.google.com/android/repository/" + \
              f"android-ndk-{self.version}-{os_name}-{self._host_arch}.zip"

        self.output.info(f"Downloading {url}...")

        tools.download(url, "ndk.zip")
        tools.unzip("ndk.zip", keep_permissions=True)
        os.unlink("ndk.zip")

        # now checkout the android LLVM release for building the custom STL
        self.run(f'git clone https://android.googlesource.com/toolchain/llvm-project -b {self._llvm_tag_name}')

        # patch the LLVM build
        with tools.chdir('llvm-project'):
            tools.patch(patch_file='../llvm-build.patch')

    def build(self):
        # build the custom STL
        common_cmake_parameters = [
            '-DCMAKE_BUILD_TYPE=Release',
            '-DLIBCXX_ABI_VERSION=2',
            '-DLIBCXX_ABI_UNSTABLE=ON',
            '-DLIBCXX_ENABLE_EXCEPTIONS=OFF',
            '-DLIBCXX_ENABLE_RTTI=ON',
            '-DLIBCXX_ENABLE_SHARED=OFF',
            '-DLIBCXXABI_ENABLE_SHARED=OFF',
            '-DLLVM_ENABLE_LTO=ON',
            '-DLLVM_ENABLE_EH=OFF',
            '-DLLVM_ENABLE_RTTI=OFF',
        ]

        if self.settings.os_build == 'Windows':
            common_cmake_parameters.append('-DLLVM_HOST_TRIPLE="x86_64-pc-windows-msvc"')

        for abi in self._abis:
            tools.mkdir(abi)
            with tools.chdir(abi):
                if abi == 'armeabi-v7a':
                    specific_parameters = [
                        "-DLIBCXXABI_USE_LLVM_UNWINDER=ON",
                        "-DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON",
                        "-DLLVM_ENABLE_PROJECTS='libcxx;libcxxabi;libunwind'",
                    ]
                else:
                    specific_parameters = ["-DLLVM_ENABLE_PROJECTS='libcxx;libcxxabi'"]

                cmake_invocation = ' '.join([
                        'cmake',
                        '-GNinja',  # only Ninja generator is supported
                        f'-DCMAKE_TOOLCHAIN_FILE={self.source_folder}/android-ndk-{self.version}/' + \
                        'build/cmake/android.toolchain.cmake',
                        f'-DANDROID_ABI={abi}',
                        f'-DCMAKE_ANDROID_ARCH_ABI:STRING={abi}',
                    ] +
                    common_cmake_parameters +
                    specific_parameters + [
                        f'{self.source_folder}/llvm-project/llvm'
                    ]
                )

                self.run(cmake_invocation)
                self.run('ninja cxx cxxabi')

    def package(self):
        self.copy("*", src=f"android-ndk-{self.version}")
        for abi in self._abis:
            self.copy('libc++*.a', src=f'{abi}/lib', dst=f'mb-stl/{abi}', keep_path=False)

    @property
    def _platform(self):
        return {
            'Windows': 'windows',
            'Macos': 'darwin',
            'Linux': 'linux'
        }.get(str(self.settings.os_build))

    @property
    def _android_abi(self):
        return {"x86": "x86",
                "x86_64": "x86_64",
                "armv7": "armeabi-v7a",
                "armv8": "arm64-v8a"}.get(str(self.settings.arch))

    @property
    def _host(self):
        return self._platform if self.settings.arch_build == 'x86' else self._platform + '-x86_64'

    @property
    def _ndk_root(self):
        return os.path.join(self.package_folder, "toolchains", "llvm", "prebuilt", self._host)

    @property
    def _clang_triplet(self):
        arch = {'armv7': 'armv7a',
                'armv8': 'aarch64',
                'x86': 'i686',
                'x86_64': 'x86_64'}.get(str(self.settings.arch))
        abi = 'androideabi' if self.settings.arch == 'armv7' else 'android'
        return '%s-linux-%s' % (arch, abi)

    @property
    def _llvm_triplet(self):
        arch = {'armv7': 'arm',
                'armv8': 'aarch64',
                'x86': 'i686',
                'x86_64': 'x86_64'}.get(str(self.settings.arch))
        abi = 'androideabi' if self.settings.arch == 'armv7' else 'android'
        return '%s-linux-%s' % (arch, abi)

    def _tool_name(self, tool):
        if 'clang' in tool:
            suffix = '.cmd' if self.settings.os_build == 'Windows' else ''
            return '%s%s-%s%s' % (self._clang_triplet, self.settings.os.api_level, tool, suffix)
        else:
            suffix = '.exe' if self.settings.os_build == 'Windows' else ''
            return '%s-%s%s' % (self._llvm_triplet, tool, suffix)

    def _define_tool_var(self, name, value):
        ndk_bin = os.path.join(self._ndk_root, 'bin')
        path = os.path.join(ndk_bin, self._tool_name(value))
        self.output.info('Creating %s environment variable: %s' % (name, path))
        return path

    def package_id(self):
        self.info.include_build_settings()
        del self.info.settings.arch
        del self.info.settings.os
        self.info.settings.arch_build = self._host_arch

    def package_info(self):
        self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(
            self.package_folder,
            'build',
            'cmake',
            'android.toolchain.cmake'
        )
        self.env_info.CONAN_CMAKE_CUSTOM_CMAKE_ANDROID_NDK = self.package_folder
        self.env_info.CONAN_CMAKE_CUSTOM_ANDROID_TOOLCHAIN = "clang"
        self.env_info.CONAN_CMAKE_CUSTOM_CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION = "clang"
        self.env_info.CONAN_CMAKE_CUSTOM_ANDROID_PLATFORM = "android-16"
        self.env_info.CONAN_CMAKE_CUSTOM_CMAKE_SYSROOT = os.path.join(self.package_folder, 'sysroot')
        self.env_info.CONAN_CMAKE_FIND_ROOT_PATH = os.path.join(self.package_folder, 'sysroot')
        self.env_info.CONAN_CMAKE_SYSTEM_NAME = "Android"
        self.env_info.CONAN_CMAKE_SYSTEM_VERSION = "16"
        self.env_info.CONAN_CMAKE_CUSTOM_ANDROID_STL = "c++_static"
        self.env_info.CONAN_CMAKE_CUSTOM_CMAKE_ANDROID_STL_TYPE = "c++_static"
        self.env_info.ANDROID_NDK = self.package_folder

        if self.settings.os == 'Android':
            # variables needed for non-microblink build systems (vanilla cmake, autotools, make, ...)
            # set them only when using this toolchain on android build
            self.env_info.NDK_ROOT = self._ndk_root
            self.env_info.ANDROID_NDK_HOME = self.package_folder
            self.env_info.CHOST = self._llvm_triplet

            ndk_sysroot = os.path.join(self._ndk_root, 'sysroot')

            self.env_info.SYSROOT = ndk_sysroot
            self.cpp_info.sysroot = ndk_sysroot
            self.env_info.ANDROID_NATIVE_API_LEVEL = '16'

            self.env_info.CC = self._define_tool_var('CC', 'clang')
            self.env_info.CXX = self._define_tool_var('CXX', 'clang++')
            self.env_info.LD = self._define_tool_var('LD', 'ld')
            self.env_info.AR = self._define_tool_var('AR', 'ar')
            self.env_info.AS = self._define_tool_var('AS', 'as')
            self.env_info.RANLIB = self._define_tool_var('RANLIB', 'ranlib')
            self.env_info.STRIP = self._define_tool_var('STRIP', 'strip')
            self.env_info.ADDR2LINE = self._define_tool_var('ADDR2LINE', 'addr2line')
            self.env_info.NM = self._define_tool_var('NM', 'nm')
            self.env_info.OBJCOPY = self._define_tool_var('OBJCOPY', 'objcopy')
            self.env_info.OBJDUMP = self._define_tool_var('OBJDUMP', 'objdump')
            self.env_info.READELF = self._define_tool_var('READELF', 'readelf')
            self.env_info.ELFEDIT = self._define_tool_var('ELFEDIT', 'elfedit')

            self.env_info.ANDROID_STL = "c++_static"
            self.env_info.ANDROID_PLATFORM = "android-16"
            self.env_info.ANDROID_TOOLCHAIN = "clang"
            self.env_info.ANDROID_ABI = self._android_abi

            self.env_info.CMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "BOTH"
            self.env_info.CMAKE_FIND_ROOT_PATH_MODE_LIBRARY = "BOTH"
            self.env_info.CMAKE_FIND_ROOT_PATH_MODE_INCLUDE = "BOTH"
            self.env_info.CMAKE_FIND_ROOT_PATH_MODE_PACKAGE = "BOTH"
```

The `llvm-build.patch` is required only for building on Windows because the LLVM Cmake tries to detect host triple and fails. Note that this is not required for building only `libc++` and `libc++abi`.

```diff
--- a/llvm/cmake/config-ix.cmake
+++ b/llvm/cmake/config-ix.cmake
@@ -383,8 +383,10 @@ endif()

 # By default, we target the host, but this can be overridden at CMake
 # invocation time.
-include(GetHostTriple)
-get_host_triple(LLVM_INFERRED_HOST_TRIPLE)
+if ( NOT LLVM_HOST_TRIPLE )
+    include(GetHostTriple)
+    get_host_triple(LLVM_INFERRED_HOST_TRIPLE)
+endif()

 set(LLVM_HOST_TRIPLE "${LLVM_INFERRED_HOST_TRIPLE}" CACHE STRING
     "Host on which LLVM binaries will run")
```

Finally, in order to work, our projects needed to add the following to their cmake scripts:

```cmake
    # first disable usage of builtin STL, in order to avoid conflicts
    add_link_options( -nostdlib++ )
    add_compile_options( -nostdinc++ )

    string( TOLOWER "${CMAKE_HOST_SYSTEM_NAME}" host_system )
    # next, add custom path to NDK's STL include dir
    # include_directories( SYSTEM ${ANDROID_NDK}/toolchains/llvm/prebuilt/${host_system}-x86_64/sysroot/usr/include/c++/v1 )
    # ...mrmlj... include_directories is completely ignored, so use add_compile_options
    add_compile_options( -isystem ${ANDROID_NDK}/toolchains/llvm/prebuilt/${host_system}-x86_64/sysroot/usr/include/c++/v1 )
    add_definitions( -D_LIBCPP_ABI_VERSION=2 -D_LIBCPP_ABI_UNSTABLE=1 )

    # finally, link the customly built libraries
    link_libraries( ${ANDROID_NDK}/mb-stl/${ANDROID_ABI}/libc++.a ${ANDROID_NDK}/mb-stl/${ANDROID_ABI}/libc++abi.a )

    # add correct link flags for armv7 and in case when target API is less than 21
    # Usually those are added by the official android toolchain, but only when libc++ is selected
    if ( ${ANDROID_ABI} STREQUAL "armeabi-v7a" )
        add_link_options( "-Wl,--exclude-libs,libunwind.a" )
    endif()

    if( ANDROID_PLATFORM_LEVEL LESS 21 )
        add_link_options( "-landroid_support" )
    endif()

    # also make sure to link with the default C runtime library
    add_link_options( "-lc" )
```

Our `minSdkVersion` is 16 and this works correctly. However, I was only able to build a static version of `libc++` and `libc++abi` - the shared version failed to link, probably due to a missing `libandroid_support`. However, this library is part of the NDK and gets linked to the final app when we use the static `libc++(abi)`.

> am closing since I don't think there's NDK work to do here

As you can see, in order to achieve the custom build of `libc++(abi)`, you need to do a lot of things manually - clone the correct commit from the AOSP LLVM fork (over a 1 GB download - not easy on a slower connection), patch the LLVM cmake in order just to build the `libc++(abi)` and finally tweak the cmake in the custom toolchain to be able to use the modified `libc++(abi)`.

This is much more complicated work than it used to be in the `ndk-build` days, when you could simply `import` the `libc++ Android.mk` and build it as part of your project. Currently, the `Android.mk` in question is still part of the NDK distribution, but `libc++` sources are not (there are only sources for `libc++abi`, but not for `libc++`), which makes the `Android.mk` in question unusable.

So, I think there **is** some NDK work to do here:

- restore the libc++ sources in the NDK distribution under the `sources` folder, just like there is for `libc++abi`
- provide a custom `CMakeLists.txt` (or `FindLibCXX.cmake`) for `libc++` and `libc++abi` which will not expect to be part of the LLVM project's build system
- update the default cmake toolchain so that it will recognize, e.g., `c++_custom` as `ANDROID_STL` value, which will then include the provided `libc++` and `libc++abi` into the build system, instead of using the prebuilt `libc++` and `libc++abi`.
- optionally, provide a script for building a custom version of `libc++` and `libc++abi` for those that don't want to build it always as part of their build. This used to exist in `$NDK/build/tools/build-cxx-stl.sh` (mentioned in `Android.mk` file), but this file no longer exists.

**Comment by DanAlbert** [comment]
> So, I think there is some NDK work to do here...

We'll just be using upstream's build system. You won't need a full NDK or Android LLVM checkout to build your own libc++ for Android apps. You'll just clone LLVM and build libc++ there. It has all the same outcomes (vastly simpler checkout and build setup than the NDK, can build libc++ however you want) but should be simpler and better (not using a distinct and un(der?) tested build path, can pick whatever upstream revision you want) for everyone.

**Comment by DoDoENT** [comment]
AFAIK, the CMake files in Android LLVM are the same as in the upstream LLVM (you've only added `ndk-build`-related stuff), or am I wrong?

So, by using the upstream LLVM for building the libc++, I would still need to patch LLVM-related build stuff just because in LLVM repository `libc++` and `libc++abi` cannot be built independently of core LLVM (it provides the configuration variables and common compiler flags). Also, LLVM clone is not a small clone to do (over 1 GB - larger than the entire NDK binary distribution).

I agree that it's a good thing to be able to use upstream LLVM directly with NDK, but for some use cases, it would be enough to just build exactly the same libc++ snapshot that was used in the official NDK distribution, just with some features disabled (RTTI, exceptions) or with slightly different compile flags (LTO, unstable ABI preprocessor definition, ...). This would be easiest if those files were directly distributed with the NDK. However, if that is not what you plan long-term, then at least NDK distribution should provide the commit hash from the upstream LLVM that was used for building the official NDK.

**Comment by DanAlbert** [comment]
> AFAIK, the CMake files in Android LLVM are the same as in the upstream LLVM (you've only added ndk-build-related stuff), or am I wrong?

There's a lot more to that repo than just the CMake files. It's also prebuilt toolchains. Those are the part that's huge. If you clone the upstream LLVM you can skip that huge part of the clone.

> I would still need to patch LLVM-related build stuff just because in LLVM repository libc++ and libc++abi cannot be built independently of core LLVM (it provides the configuration variables and common compiler flags). Also, LLVM clone is not a small clone to do (over 1 GB - larger than the entire NDK binary distribution).

We'd need to bundle all that into the NDK distribution to support rebuilding libc++ there too, so no improvement by doing that.

Bluntly: we are not going to create a wholly separate build process for libc++. We don't have the resources to maintain that.

> at least NDK distribution should provide the commit hash from the upstream LLVM that was used for building the official NDK.

This will come for free since we already note the LLVM revision in the NDK changelog, and libc++ will come from the same build.

**Comment by DoDoENT** [comment]
> If you clone the upstream LLVM you can skip that huge part of the clone.

Check the Conan recipe I [posted earlier](https://github.com/android/ndk/issues/1534#issuecomment-883201516) - I'm cloning _only the Android LLVM_, without the prebuilt toolchains and for the purposes of building only the static libraries, it works.

And my comment on large clone was referring just to that LLVM part (even cloning upstream LLVM is a huge clone, especially when you live in a place where 20 Mbps is considered "very fast Internet" 😛 ).

> We'd need to bundle all that into the NDK distribution to support rebuilding libc++ there too, so no improvement by doing that.

AFAIK, you used to do that. It would be a small CMakeLists.txt file + several CPP files that make the `libc++`.

> Bluntly: we are not going to create a wholly separate build process for libc++. We don't have the resources to maintain that.

A fair point. But then please remove libc++'s `Android.mk` from the NDK distribution. It's misleading.

> This will come for free since we already note the LLVM revision in the NDK changelog, and libc++ will come from the same build.

I wasn't aware of that. Thank you!

**Comment by DanAlbert** [comment]
> AFAIK, you used to do that.

That worked when we didn't use LLVM's build scripts. Deviation from LLVM's built-in way of doing things has been a huge pain though (it's the reason that r23 is shipping with a very out of date libc++).

> But then please remove libc++'s Android.mk from the NDK distribution. It's misleading.

The other half of the `if` in that file is used by ndk-build. It's how ndk-build imports those modules. The half that's only usable during our build process will be removed when we finish the migration, but it's probably not going away because it's how ndk-build avoids the build behaviors that make it so easy to cause unwinder crashes with the other build systems.
