### ISSUE TITLE
Missing platform folder in NDK r22b and upcoming r23

### ISSUE THREAD

**Issue by Azar2477** [android/ndk#1537]
**Note**: Bugs against Android Studio or Gradle should be filed at
http://b.android.com, not here.

Before filing a bug, check that you are using the latest version of the NDK. The
latest stable version and the preview release of the next stable version are
listed on our wiki: https://github.com/android-ndk/ndk/wiki#downloads.

Make sure your issue isn't on the list of common problems before filing a bug:
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md

Delete everything above this line before submitting.

--------------------------------------------------------------------------------

#### Description

If I will use the NDK it says "This NDK has no platforms" because the NDK platforms folder is missing.
In NDK r21e LTS there is the platforms folder from Android API 16 to 30 but no API 31 in platforms folder it should be in the upcoming NDK r23.

#### Environment Details

* NDK Version: 22.1.7171670
* Build system: platforms
* Host OS: Windows 11
* ABI: 31
* NDK API level: r22b
* Device API level: 31

**Comment by enh-google** [comment]
> If I will use the NDK it says "This NDK has no platforms" because the NDK platforms folder is missing.

what exactly says that? that string doesn't seem to appear anywhere in the NDK or Android Studio...

**Comment by rprichard** [comment]
The `platforms` directory became obsolete starting in r19, and it was removed in r22. The files that used to be there are now in the toolchain's sysroot instead, e.g.:

```
$ ls /x/android-ndk-r19c/platforms/android-21/arch-arm64/usr/lib
crtbegin_dynamic.o  libc.a                   libGLESv1_CM.so    libmediandk.so   libz.a
crtbegin_so.o       libcompiler_rt-extras.a  libGLESv2.so       libm.so          libz.so
crtbegin_static.o   libc.so                  libGLESv3.so       libOpenMAXAL.so
crtend_android.o    libdl.a                  libjnigraphics.so  libOpenSLES.so
crtend_so.o         libdl.so                 liblog.so          libstdc++.a
libandroid.so       libEGL.so                libm.a             libstdc++.so

$ ls /x/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21
crtbegin_dynamic.o  libc++.a                 libdl.so           liblog.so        libstdc++.a
crtbegin_so.o       libc.a                   libEGL.so          libm.a           libstdc++.so
crtbegin_static.o   libcompiler_rt-extras.a  libGLESv1_CM.so    libmediandk.so   libz.a
crtend_android.o    libc++.so                libGLESv2.so       libm.so          libz.so
crtend_so.o         libc.so                  libGLESv3.so       libOpenMAXAL.so
libandroid.so       libdl.a                  libjnigraphics.so  libOpenSLES.so
```
The reorganization puts the libraries where the Clang driver expects to find them, making it easier for build systems to invoke Clang. However, it does require build systems to change how they invoke Clang. (e.g. With the new layout, an NDK user can omit many flags and instead rely on the default Clang behavior.)

I'm also wondering where the `This NDK has no platforms` message is coming from.

**Comment by enh-google** [comment]
from https://stackoverflow.com/questions/56228822/ndk-does-not-contain-any-platforms it looks like (old versions of) Studio can output this error. so you might want to check you don't have any of the problems listed on that page, and that you're using the current version of Studio.

**Comment by DanAlbert** [comment]
Outdated AGP seems likely. Closing until we get more info. Nothing we can do with what we have.
