### ISSUE TITLE
[BUG] '__ANDROID_API__' macro redefined

### ISSUE THREAD

**Issue by Over17** [android/ndk#1538]
Hi!

With NDK r23 beta5, I'm getting the following build error:

`Building Library\Bee\artifacts\Android\libunity\arm64-v8a\UnityClassRegistration.o failed with output:
In file included from <built-in>:395:
<command line>(1,9): error: '__ANDROID_API__' macro redefined [-Werror,-Wmacro-redefined]
#define __ANDROID_API__ 22
        ^
<built-in>(386,9): note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 error generated.`

We are using a custom build system, and we were defining __ANDROID_API__ to the min API setting of the project.
With current NDK r21d, we're not seeing this issue.

Where is the define coming from?
How to suppress it when using custom tooling?

Thanks!
Yury

**Comment by DanAlbert** [comment]
> Where is the define coming from?

Clang defines it automatically based on the triple.

> How to suppress it when using custom tooling?
> we were defining ANDROID_API to the min API setting of the project.

Don't do that. Set the `minSdkVersion` as part of the triple.

This is probably worth reading: https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md
