### ISSUE TITLE
[BUG] Undefined reference to libc fortify functions

### ISSUE THREAD

**Issue by Aang23** [android/ndk#1539]
#### Description

I am attempting to link my native library against https://github.com/nanomsg/nng, compiled with CMake against my installed NDK, r22.
Everything goes fine, but linking will fail against quite a few functions.
```
 ld: error: undefined symbol: epoll_create1
 ld: error: undefined symbol: __strncpy_chk2
 ld: error: undefined symbol: __fwrite_chk
```

I checked with nm, and those are available in toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/libc.a, but not toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libc++_static.a which my application is linking against.

#### Environment Details

* NDK Version: 22.1.7171670
* Build system: CMake, called from Gradle
* Host OS: Linux (Arch Linux)
* NDK API level: 22
* Device API level: 28

**Comment by DanAlbert** [comment]
> NDK API level: 22
> toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/

Given the mismatch here I'm guessing your minSdkVersion is 16? Those functions weren't available then. Sounds like something was configured incorrectly in your build but we don't know what you did, so can't help without repro steps. Provide that and we'll reopen.

**Comment by Aang23** [comment]
> > NDK API level: 22
> > toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/
> 
> Given the mismatch here I'm guessing your minSdkVersion is 16? Those functions weren't available then. Sounds like something was configured incorrectly in your build but we don't know what you did, so can't help without repro steps. Provide that and we'll reopen.

No, my minSdkVersion is 28, identical to my targetSdkVersion as I require some Android 10 features.

**Comment by Aang23** [comment]
@DanAlbert do you need any other information?

**Comment by DanAlbert** [comment]
Yes, we need repro steps.
