### ISSUE TITLE
[BUG] BUS unalignment if build with clang in release mode

### ISSUE THREAD

**Issue by sunshinemyson** [android/ndk#1541]
#### Description

Release build will crash in somewhere with bus unaligned memory access exception, if we change it to debug build, exception goes away.

After debug, we found it related with optimization around some function, if we put the #pragma clang optimize off/on around that function, crash also fixed.

Bug description goes here. Include a test case. It's unlikely that anything can
be done without a test case.

will provide assembly code in with optimization on/off

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK version >= 22d
* Build system: CMake
* Host OS: Linux, ubuntu-20.04 LTS
* ABI: armeabi-v7a or armeabi-v7a with neon
* NDK API level: 29
* Device API level: 30

**Comment by sunshinemyson** [comment]
[func_no_opt.txt](https://github.com/android/ndk/files/6862080/func_no_opt.txt)
[func_opt.txt](https://github.com/android/ndk/files/6862081/func_opt.txt)

**Comment by enh-google** [comment]
i suspect we'll need _source_ rather than generated code anyway, but what offset into that code is the crash?

**Comment by DanAlbert** [comment]
The usual answer for this situation is that your code has undefined behavior. Typically an undersigned type like an array of `char` or `uint8_t` being cast to an array of a differently aligned type.

**Comment by sunshinemyson** [comment]
I'll check if i can share the source code or not. Thanks

**Comment by jmgao** [comment]
If you can't share the code, it's worth trying `-Wcast-align -Wover-aligned` to see if clang can spot a bad pointer cast in your code.

**Comment by DanAlbert** [comment]
ubsan can help too.

**Comment by sunshinemyson** [comment]
> 
> 
> If you can't share the code, it's worth trying `-Wcast-align -Wover-aligned` to see if clang can spot a bad pointer cast in your code.

I'll try this. Thanks

**Comment by sunshinemyson** [comment]
> 
> 
> > If you can't share the code, it's worth trying `-Wcast-align -Wover-aligned` to see if clang can spot a bad pointer cast in your code.
> 
> I'll try this. Thanks

Those two flag doesn't raise any warning or error.

**Comment by sunshinemyson** [comment]
> 
> 
> i suspect we'll need _source_ rather than generated code anyway, but what offset into that code is the crash?

[clang_opt_issue.txt](https://github.com/android/ndk/files/6917623/clang_opt_issue.txt)

would you mind check the source? crash at line 63. Thanks

**Comment by stephenhines** [comment]
I have a few thoughts, but it isn't 100% clear to me where the error is yet. First, lines 92 and 112 both move to the next kernel binary. The loop is iterating through `kernelCount`, so please verify if you actually intend to be doing 2 decodes per iteration.

My second thought is that in your loop body, you are casting a `UINT32*` buffer to a `UINT8*` buffer and back again (line 67). Depending on how you encoded those kernel names, you may not have padded them appropriately. If `kernelNameLength` isn't a multiple of 4, you will end up with a misaligned pointer for `linkedBinary`. When you come back in for the next iteration, you would end up getting `SIGBUS` when doing the `*linkedBinary` with that misaligned pointer. I'm pretty sure this is the problem you are seeing. If you want to diagnose this, I would try printing/logging those pointer values (before/after line 67 and line 92 also where you adjust for size of the binary).

```
62            /* skip the kernel name length */
63            kernelNameLength = *linkedBinary;                                                   // <<----- crashed at here
64            linkedBinary++;
65
66            kernelName = (gctCHAR*)linkedBinary;
67            linkedBinary = (gctUINT32*)((gctUINT8*)linkedBinary + kernelNameLength);
```

**Comment by sunshinemyson** [comment]
@stephenhines ,

Thanks. I agree with your analysis of the code. One thing still not clear is we should have the same memory access pattern in opt-disabled mode.  My guess is: does some optimization should not applied in some certain condition? if yes, I want to learn that which pattern in this code trigged this issue. Would like to know your idea.

**Comment by sunshinemyson** [comment]
We found the root cause of this issue: it related with -Oz optimization option with clang compiler. NDK always enabled this option.

We also investigated the configuration of AOSP, it doesn't enable -Oz for native c++ libraries unless the programmer specific it in the Android.mk.

Root cause: 

when -Oz enabled, compiler will use ldmia instruction to replace ldr instruction to reduce binary size. But ldmia required memory alignment for the address.

Question to NDK team: 
 -Oz options should not be enabled by defalut because it will introduce implicit restriction for programmer. This option should enabled by programmer explicitly untill programmer fully understanded what will happen.

Please let me know your idea.

**Comment by sunshinemyson** [comment]
![图片](https://user-images.githubusercontent.com/698804/130174197-31e73996-bc5a-4824-8f52-dd9da89eda38.png)

**Comment by DanAlbert** [comment]
> -Oz options should not be enabled by defalut because it will introduce implicit restriction for programmer

Accessing data with an incorrect alignment is undefined behavior in C++. It happens to be symptomatic for you with `-Oz`, but it is by no means limited to that optimization level. It's quite possible that you'll see the error recur at other optimization levels when your code changes slightly so that the data is placed at a different address, or when the compiler updates. I've personally encountered the same problem plenty of times in AOSP before we were using `-Oz`.

I've had to do this exact same detective work before so I agree it's a pain in the ass that clang can't offer any more help in diagnosing this, fwiw, but it's not something we have any control over.

**Comment by rprichard** [comment]
From the snippet I see, I'd suggest using memcpy to read from linkedBinary into kernelNameLength and subKernelCount. The compiler should be smart enough to see that the memcpy length is a constant 4 and optimize it into the right thing (i.e. a single load instruction that supports unaligned accesses).

Though, I wonder if this project would require using a gcoOS_MemCpy function? Perhaps the compiler wouldn't optimize a call to that as well.

Other options might be using `__builtin_memcpy`, or a packed struct. e.g.:

```
struct PackedInt {
    int val;
} __attribute__((packed));

PackedInt* linkedBinary = ...;
kernelNameLength = linkedBinary->val;
```

**Comment by enh-google** [comment]
yeah, the packed struct is what we used in the libcore NIO implementation to avoid this:
```
// Use packed structures for access to unaligned data on targets with alignment restrictions.
// The compiler will generate appropriate code to access these structures without
// generating alignment exceptions.
template <typename T> static inline T get_unaligned(const T* address) {
    struct unaligned { T v; } __attribute__ ((packed));
    const unaligned* p = reinterpret_cast<const unaligned*>(address);
    return p->v;
}

template <typename T> static inline void put_unaligned(T* address, T v) {
    struct unaligned { T v; } __attribute__ ((packed));
    unaligned* p = reinterpret_cast<unaligned*>(address);
    p->v = v;
}
```
