### ISSUE TITLE
M1 LLVM toolchain

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1544]
Subtask for https://github.com/android/ndk/issues/1299

clang-r416183c already has this, so we just need to update from clang-r416183b.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/1815336/ does this for r24. Will cherry-pick for r23b as well

**Comment by rprichard** [comment]
This is fixed in r23b and in r24-beta1.
