### ISSUE TITLE
M1 CMake

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1545]
Subtask for https://github.com/android/ndk/issues/1299

**Comment by DanAlbert** [comment]
(removing from the project because this isn't tied to an NDK release, it's in the SDK)

**Comment by rprichard** [comment]
CMake 3.22.1 is now available in the SDK Manager's canary channel. This build of CMake contains universal (arm64 + x86_64) binaries for macOS.

**Comment by DanAlbert** [comment]
AGP 7.3 Canary 8 should use CMake 3.22.1 by default. We'll give that some soak time (unsure how long we ought to wait, but probably not more than a month) and then promote it to the stable channel.

**Comment by zjns** [comment]
> AGP 7.3 Canary 8 should use CMake 3.22.1 by default. We'll give that some soak time (unsure how long we ought to wait, but probably not more than a month) and then promote it to the stable channel.

Still not stable?

**Comment by DanAlbert** [comment]
The CMake binaries aren't likely to change before being pushed to stable, but we haven't made that push since https://github.com/android/ndk/issues/1693 is awful surprising behavior for users and we need to ship NDK updates that opt-out by default before we can safely promote CMake 3.22 to stable. r23c and r25 beta 4 have the workaround already, but r24 does not. We'll push to stable once either r24b ships with this fix (release is delayed waiting for toolchain fixes) or r24 reaches EOL (which won't be sooner than July).

**Comment by DanAlbert** [comment]
Okay, now that r25 ks out, CMake 3.22.1 is in the stable channel.

AGP's default still needs to be updated.
