### ISSUE TITLE
M1 Ninja

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1548]
Subtask for https://github.com/android/ndk/issues/1299

**Comment by DanAlbert** [comment]
(removing from the project because this isn't tied to an NDK release, it's in the SDK)

**Comment by DanAlbert** [comment]
No, we were two weeks faster :) https://github.com/android/ndk/issues/1545#issuecomment-1012784638

It's still in canary, which is why the bugs remain open.

**Comment by rprichard** [comment]
The Android SDK's ninja binary is distributed as part of the cmake package.

**Comment by enh-google** [comment]
do we know (roughly?) the timeline when that'll go from canary to stable?

**Comment by DanAlbert** [comment]
We could ambitiously do that any time, but I think it'd be wise to flip the Studio default version before we do that. We don't have any way to know if it's been used by anyone but @rprichard yet.

**Comment by DanAlbert** [comment]
(I'm planning to move the Studio default Soon, once I'm done doing fixing their default NDK)

**Comment by enh-google** [comment]
sgtm. i'm just very confused this week about what "released" even means in Studio land :-)

**Comment by DanAlbert** [comment]
aiui cmake/ninja being in canary means that anyone can use it as long as they enable the canary channel. No updates there are forced so it's safe to do, but it'll recommend canary updates for other packages so it might be annoying. I think you can enable the canary channel, install cmake, then go back to stable though?

**Comment by rprichard** [comment]
> I think you can enable the canary channel, install cmake, then go back to stable though?

I believe this is the case. It'll also be necessary to set the cmake version in gradle, e.g.:
```
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
```

**Comment by vmilea** [comment]
> I'm planning to move the Studio default Soon

What will be the new default?

FWIW - I've been using CMake 3.22.1 from canary with NDK r23b and r24 RC1. No issues so far, and build times on my M1 mac have almost halved with the arm64 Clang.

**Comment by DanAlbert** [comment]
> What will be the new default?

3.22.1

> FWIW - I've been using CMake 3.22.1 from canary with NDK r23b and r24 RC1. No issues so far, and build times on my M1 mac have almost halved with the arm64 Clang. Thank you!

Glad to hear it! We're moving a little slowly in the transition from canary -> stable at least in part because we aren't sure how widely the new version has been used yet. One vote of confidence is hardly data, but at least we can feel good about it :)

**Comment by DanAlbert** [comment]
AGP 7.3 Canary 8 should use CMake 3.22.1 (which includes ninja) by default. We'll give that some soak time (unsure how long we ought to wait, but probably not more than a month) and then promote it to the stable channel.

**Comment by DanAlbert** [comment]
Okay, now that r25 is out, CMake 3.22.1 (which includes ninja) is in the stable channel.

AGP's default still needs to be updated.
