### ISSUE TITLE
[BUG] NDK does not include the android headers

### ISSUE THREAD

**Issue by martmists-gh** [android/ndk#1550]
#### Description

Essential headers such as `hardware/audio_effect.h` or `system/audio-base.h` are not present among the headers provided by the NDK.

#### Environment Details

* NDK Version: 23.0.7196353
* Build system: CMake (3.10, 3.19 and 3.21)
* Host OS: Arch Linux
* ABI: armeabi-v7a
* NDK API level: 16
* Device API level: n/a

**Comment by enh-google** [comment]
those are not NDK APIs.

**Comment by martmists-gh** [comment]
Then where do I get these headers from? These (and others) seem pretty important to developing certain apps for android...

**Comment by enh-google** [comment]
> Then where do I get these headers from? These (and others) seem pretty important to developing certain apps for android...

if you're working on a bundled app on the vendor partition that's allowed to use this stuff, build as part of the OS build. if you're not, you can't use this stuff anyway.
