### ISSUE TITLE
[BUG] Unable to link dependent library in separate folder (example project included)

### ISSUE THREAD

**Issue by lufinkey** [android/ndk#1554]
#### Description

When linking a dependent cmake module from outside the project, the library is either unable to link (`libMyLibrary1.so not found`) or the symbols are just not found (`undefined reference to mylib1TestFunction()`).

[Here](https://github.com/lufinkey/cmakebug) is an example project that shows this bug. Just open `projects/android-studio` in android studio and attempt to build the project

The dependency structure for this project is *TestApp* => *MyLibrary2* => *MyLibrary1*

#### Environment Details

* CMake Version: Currently `3.18.1` but I've seen this bug in `3.4.1` as well
* NDK Version: 21.4.7075529
* Build system: CMake
* Host OS: Mac
* ABI: default
* NDK API level: default
* Device API level: `>= 24`

**Comment by mcclure** [comment]
I've been talking to lufinkey in a separate chat— a thing I think is important to note is that this exact same configuration of CMake files, when invoked (out of the example tree) to build a *mac* binary either using lufinkey's system cmake or the cmake vended by Android Studio on lufinkey's computer, THAT builds fine. This seems to strongly imply a bug in Google's Android-ndk fork.

**Comment by lufinkey** [comment]
Attempting to build the android native libraries directly from the command seems to work too. [Here's the script I ran to build from the command line](https://github.com/lufinkey/cmakebug/blob/master/projects/android-studio/app/src/main/cpp/test.sh)

**Comment by DanAlbert** [comment]
Android Studio doesn't support cross-module native dependencies. This isn't expected to work: https://issuetracker.google.com/120166563

There's no problem with the NDK itself here, it's the android gradle plugin and its interaction with Android Studio, so closing. The linked bug is the one you want.

**Comment by lufinkey** [comment]
Is this documented anywhere? This problem sucked tons of hours on my
project which I probably could have forgone that if it was more clear in
the documentation

**Comment by DanAlbert** [comment]
Not that I can find. The whole feature is undocumented beyond the changelog for 4.1. I'll ping the doc bug again. If I still can't get anyone to look at it I'll try to find some time this week to just do it myself.

**Comment by lufinkey** [comment]
I really appreciate that, thanks!

**Comment by DanAlbert** [comment]
Also FWIW the bug _is_ being worked on now. Lots of moving parts that all need to coordinate, but it's starting to come together. We expect that it'll require a new version of AGP.

**Comment by lufinkey** [comment]
Gotcha! I saw the discussion on there but I wasn't sure how close it was.
That's awesome to hear 🙂

**Comment by DanAlbert** [comment]
I sent a patch to update the docs. It's just the 4.1 changelog docs for `prefabPublishing` and a warning at the top of the page that says "this doesn't work within a project, see $BUG" added to https://developer.android.com/studio/build/native-dependencies. Is that what you were looking for, or is there more to do doc-wise?

**Comment by lufinkey** [comment]
I'm not seeing it at the link you sent. Mind sending a screenshot?

**Comment by DanAlbert** [comment]
It's still in review.

**Comment by lufinkey** [comment]
Ah gotcha. Yeah basically as long as it makes it clear that multiple dependent native projects can't be linked together right now I think it should be fine

**Comment by DanAlbert** [comment]
Submitted now. DAC might keep serving you a cached copy for a while but with the cache off it shows the update.

**Comment by DanAlbert** [comment]
More good news: the changes that do _most_ of the work here were submitted today, so an upcoming AGP release will be able to do this. I think it's expected to first release in Bumblebee canary 10, but I'm not that tuned into their release schedule so that could be wrong :)

I say "most" because it only works for cmake consumers until I fix https://github.com/android/ndk/issues/1559, we release it, and AGP/prefab handle it, but your example project should work. ndk-build consumers should work soonish (probably ~a quarter or so).
