### ISSUE TITLE
There is no way or option to create a C++ library project.

### ISSUE THREAD

**Issue by zezba9000** [android/ndk#1557]
**Is your feature request related to a problem? Please describe.**
There is no way or option to create a C++ library project. I have to use Visual Studio 2019 for this. Like what?

**Describe the solution you'd like**
Use Android Studio as the IDE to get contextual information on a Android NDK library's C++.
I need to create a .so dynamic library for use in Unity3D game engine.

**Describe alternatives you've considered**
Visual Studio 2019

**Additional context**
n/a

**Comment by DanAlbert** [comment]
https://developer.android.com/games/agde
