### ISSUE TITLE
[BUG] can't `simpleperf record` on emulators?

### ISSUE THREAD

**Issue by enh-google** [android/ndk#1558]
okay, strictly speaking i'm on cuttlefish rather than an emulator, but if i do a web search for the error message "Event type 'cpu-cycles' is not supported on the device" the only match is for a Mozilla bug where they're trying to work out how to use simpleperf on the emulator and hitting the same error:
```
vsoc_x86_64:/data/local/tmp# simpleperf record 2976                                                                                  
simpleperf E event_selection_set.cpp:231] Event type 'cpu-cycles' is not supported on the device
```

is there a workaround at all? it seems like the obvious alternative of `-e instructions` also isn't available?
```
vsoc_x86_64:/data/local/tmp# simpleperf record -e instructions -p 2976                                                               
simpleperf E event_selection_set.cpp:231] Event type 'instructions' is not supported on the device
```

i'm asking via a github bug so that the next person that pastes this error into a search engine gets a canonical answer from the simpleperf expert :-)

**Comment by yabinc** [comment]
A good alternative on emulator is cpu-clock, which is also used by android studio profiler on emulator.
Actually we can switch to cpu-clock by default if cpu-cycles isn't available, when user doesn't give an explicit -e option.

**Comment by enh-google** [comment]
oh, yeah, that worked fine. i like your idea of auto-switching though, so i'll leave this bug open even though i have the workaround :-)

**Comment by yabinc** [comment]
Done in https://android-review.googlesource.com/c/platform/system/extras/+/1797233

**Comment by enh-google** [comment]
thanks!
