### ISSUE TITLE
Now I‘m using NNAPI to delegate model on Qualcom DSP and I want to implement DSP zero-copy through Android Native Hardware Buffer and I want to know what should the values of the AHardwareBuffer_Format and  AHardwareBuffer_UsageFlags be.  Thanks alot![question]

### ISSUE THREAD

**Issue by pianogGG** [android/ndk#1562]
Note that we generally can't answer questions about Studio or the Android Gradle
Plugin. For those questions, [file a Studio bug](http://b.android.com).

Please include any context relevant to your question (NDK version, ABI, build
system, etc).
Now I‘m using NNAPI to delegate model on Qualcom DSP and I want to implement DSP zero-copy through Android Native Hardware Buffer and I want to know what should the values of the AHardwareBuffer_Format and  AHardwareBuffer_UsageFlags be.  Thanks a lot!

**Comment by DanAlbert** [comment]
Sorry, this slipped through the cracks. We typically can't help with "how do I use this API" type questions. We're not app developers. You probably know far more about this API than I do. You can try our mailing list or stackoverflow, which might have someone familiar with that API watching.
