### ISSUE TITLE
[BUG] LLDB shipped with NDK isn't able to find python 3.9 library

### ISSUE THREAD

**Issue by rprichard** [android/ndk#1566]
I haven't tested ndk-gdb, but I suspect it's broken. The python 3.9 dynamic library isn't in the toolchain's lib64 directory, but is instead in its python3/lib64 directory. On Linux and Darwin, there isn't an rpath pointing at the python3 directory.

macOS:
```
$ /Users/rprichard/android-ndk-r23/toolchains/llvm/prebuilt/darwin-x86_64/bin/lldb 
dyld: Library not loaded: @rpath/libpython3.9.dylib
  Referenced from: /Users/rprichard/android-ndk-r23/toolchains/llvm/prebuilt/darwin-x86_64/lib64/liblldb.12.0.5git.dylib
  Reason: image not found
```
Linux:
```
rprichard@cashew:/x/android-ndk-r23$ docker run -it -v$PWD:$PWD ubuntu:20.04 $PWD/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb
/x/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```
Windows:
```
C:\src>set PATH=C:\Windows\System32;C:\Windows
C:\src>c:\src\android-ndk-r23\toolchains\llvm\prebuilt\windows-x86_64\bin\lldb.exe
```
A dialog appears: The code execution cannot proceed because python39.dll was not found.

**Comment by MlsDmitry** [comment]
I overcame this issue via appending python library to search path.

export DYLD_LIBRARY_PATH="/Users/<name>/Library/Android/sdk/ndk/<version>/toolchains/llvm/prebuilt/darwin-x86_64/python3/lib"

**Comment by DanAlbert** [comment]
The `lldb.sh` script in the same directory solves this issue. Does this bug predate that, or is the question here "why is this necessary?"

@pirama-arumuga-nainar, is the script something we need, or just a workaround while we wait for someone to fix the `RPATH`?

**Comment by pirama-arumuga-nainar** [comment]
We also use the script to set `PYTHONHOME` - which IIUC can't be eliminated.

I also don't see a build option to set just `lldb`'s linker flags without adding this `RPATH` to the rest of the tools.  So let's continue using the script to set `LD_LIBRARY_PATH` as well.

**Comment by appujee** [comment]
Fixed in: https://android-review.git.corp.google.com/c/toolchain/llvm_android/+/2587443
