### ISSUE TITLE
[BUG] error compiling zlib: Cannot select: intrinsic %llvm.aarch64.crc32w

### ISSUE THREAD

**Issue by pomonella01** [android/ndk#1568]
--------------------------------------------------------------------------------

#### Description

Happened when compiling AOSP (or WaveOS) to my device. I don't know what this error is (haven't taken the time to look at it yet), but the compiler told me to post it here along with logs.

https://ghostbin.com/paste/SrbMp
c file: https://ghostbin.com/paste/I8vmo
sh file: https://ghostbin.com/paste/buwEt
#### Environment Details
Pop!_OS 20.10, AOSP 11

**Comment by rprichard** [comment]
This error happens while trying to compile external/zlib-ng/arch/arm/insert_string_acle.c on arm64:
```
fatal error: error in backend: Cannot select: intrinsic %llvm.aarch64.crc32w
```

**Comment by pomonella01** [comment]
I still don't really understand the error, what can I do to solve it?

**Comment by rprichard** [comment]
I think this is a bug in the user's code (zlib-ng). e.g. Maybe some functions need to be marked with TARGET_ARMV8_WITH_CRC.

I don't see an external/zlib-ng directory in AOSP, or an arch/arm/insert_string_acle.c file in external/zlib. I think someone added zlib-ng to this version of the platform build?

The armv8 CRC extension is optional. If the extension isn't enabled, then including arm_acle.h doesn't define the `__crc32X` intrinsics functions (which are just wrappers around `__builtin_arm_crc32X` functions). If I call the clang builtins anyway, I see the same LLVM backend error:
```
$ cat >test.c <<EOF
int hash(int val) {
    return __builtin_arm_crc32w(0, val);
}
EOF
$ /x/aosp/prebuilts/clang/host/linux-x86/clang-r416183c/bin/clang -target aarch64-linux-android test.c -S
fatal error: error in backend: Cannot select: intrinsic %llvm.aarch64.crc32w
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
...
```

Compiling with `-march=armv8+crc` or `-march=armv8.1-a` seems to tell Clang that the extension is supported.

I don't think the bug report's code passes a flag like that, but there is this code (from `external/zlib-ng/arch/arm/insert_string_acle.c` via the Ghostbin):
```
# 16 "external/zlib-ng/arch/arm/insert_string_acle.c"
/* CRC32 intrinsics are #ifdef'ed out of arm_acle.h unless we build with an
 * armv8 target, which is incompatible with ThinLTO optimizations on Android.
 * (Namely, mixing and matching different module-level targets makes ThinLTO
 * warn, and Android defaults to armv7-a. This restriction does not apply to
 * function-level `target`s, however.)
 *
 * Since we only need four crc intrinsics, and since clang's implementation of
 * those are just wrappers around compiler builtins, it's simplest to #define
 * those builtins directly. If this #define list grows too much (or we depend on
 * an intrinsic that isn't a trivial wrapper), we may have to find a better way
 * to go about this.
 *
 * NOTE: clang currently complains that "'+soft-float-abi' is not a recognized
 * feature for this target (ignoring feature)." This appears to be a harmless
 * bug in clang.
 */
#define __crc32b __builtin_arm_crc32b
#define __crc32d __builtin_arm_crc32d
#define __crc32w __builtin_arm_crc32w
#define __crc32cw __builtin_arm_crc32cw
```

This same block of code is in external/zlib, too:
https://android.googlesource.com/platform/external/zlib/+/refs/tags/android-11.0.0_r40/crc32_simd.c#164

For AOSP's external/zlib:
 * The armv8_crc32_little function in crc32_simd.c is marked with TARGET_ARMV8_WITH_CRC, which expands to `__attribute__((target("crc")))` for arm64 and `__attribute__((target("armv8-a,crc")))` for arm32.
 * At run-time, the library queries whether the CRC extension is present: https://android.googlesource.com/platform/external/zlib/+/refs/tags/android-11.0.0_r40/cpu_features.c#84

The Ghostbin C code is compiled with only `-march=armv8-a`, and while there is a `TARGET_ARMV8_WITH_CRC` macro defined, it isn't applied to any functions, nor is `target("crc")` applied to any functions.

**Comment by rprichard** [comment]
> I don't think the bug report's code passes a flag like that, but there is this code (from `external/zlib-ng/arch/arm/insert_string_acle.c` via the Ghostbin):
> 
> ```
> # 16 "external/zlib-ng/arch/arm/insert_string_acle.c"
> /* CRC32 intrinsics are #ifdef'ed out of arm_acle.h unless we build with an
>  * armv8 target, which is incompatible with ThinLTO optimizations on Android.
>  * (Namely, mixing and matching different module-level targets makes ThinLTO
>  * warn, and Android defaults to armv7-a. This restriction does not apply to
>  * function-level `target`s, however.)
>  *
>  * Since we only need four crc intrinsics, and since clang's implementation of
>  * those are just wrappers around compiler builtins, it's simplest to #define
>  * those builtins directly. If this #define list grows too much (or we depend on
>  * an intrinsic that isn't a trivial wrapper), we may have to find a better way
>  * to go about this.
>  *
>  * NOTE: clang currently complains that "'+soft-float-abi' is not a recognized
>  * feature for this target (ignoring feature)." This appears to be a harmless
>  * bug in clang.
>  */
> #define __crc32b __builtin_arm_crc32b
> #define __crc32d __builtin_arm_crc32d
> #define __crc32w __builtin_arm_crc32w
> #define __crc32cw __builtin_arm_crc32cw
> ```
> 
> This same block of code is in external/zlib, too:
> https://android.googlesource.com/platform/external/zlib/+/refs/tags/android-11.0.0_r40/crc32_simd.c#164

FWIW: I don't see this block of code (or the TARGET_ARMV8_WITH_CRC macro) in https://github.com/zlib-ng/zlib-ng.

**Comment by pomonella01** [comment]
i didn't quite get that, should that block of code present or no? and is this something i can solve by removing/adding it or is the solution completely different?

**Comment by rprichard** [comment]
AOSP uses external/zlib, not external/zlib-ng. Where did you get your copy of AOSP?

Without looking more into zlib-ng, it's hard to say for sure, but I would guess that the block of code is needed, but any functions using `__crcX` intrinsics also need to be marked with `TARGET_ARMV8_WITH_CRC`.

I wonder if you're using this: https://github.com/ProtonAOSP/android_external_zlib-ng. The https://github.com/ProtonAOSP/android_external_zlib-ng/commit/4b966cb85bafbc9703d4493758908ae635a930ae commit seems to have the same problem where `TARGET_ARMV8_WITH_CRC` needs to be added to the `insert_string_acle` and `quick_insert_string_acle` functions.

**Comment by pomonella01** [comment]
using this: https://github.com/Wave-Project/manifest

**Comment by pomonella01** [comment]
i'll take a look, maybe i need to add it as well

**Comment by rprichard** [comment]
+ @kdrag0n

Yeah, that's got the same commit:
 * https://github.com/Wave-Project/manifest/blob/d44b2de45b80e0dbd5ecf95e84375d16dfa21a05/wave.xml#L108
 * https://github.com/Wave-Project/external_zlib-ng/commit/4b966cb85bafbc9703d4493758908ae635a930ae

**Comment by kdrag0n** [comment]
Sorry about that, I've already been made aware of the issue in my zlib-ng port but never got around to fixing it because all the devices I build for have the arch variant set to `armv8-2a`. zlib-ng also detects CRC32 availability at runtime, so this is just a compilation issue.

I just fixed it in the ProtonAOSP port, so the fix should trickle down to other projects soon: https://github.com/ProtonAOSP/android_external_zlib-ng/commit/d08e858

**Comment by rprichard** [comment]
The fix looks good to me. Thanks!
