### ISSUE TITLE
[BUG] `ANDROID_USE_LEGACY_TOOLCHAIN_FILE` is not obeyed in try-compile

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1573]
https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/build/cmake/android.toolchain.cmake;l=255-268;drc=5bb349589cd7114b6adad1d830a4ca1a10472935 is a list of variables to be preserved for try-compile uses of the toolchain file. We didn't persist the `ANDROID_USE_LEGACY_TOOLCHAIN_FILE` value here so try-compile will only ever use the default behavior.

I already have the fix for this, just filing for visibility.

**Comment by rprichard** [comment]
This was fixed by https://android-review.googlesource.com/c/platform/ndk/+/1810691/.

**Comment by rprichard** [comment]
Fixed in r23b.
