### ISSUE TITLE
[BUG] Crash when compiling Lineage OS Kernel from Ubuntu 20.04 on Intel Core i7-11700K

### ISSUE THREAD

**Issue by Slion** [android/ndk#1578]
#### Description

Fail to compile Kernel for Lineage OS targeting F(x)tec Pro¹ device from Ubuntu 20.04.
Looks like CLang crashed early on when trying to compile the Kernel.
Worked fine when compiling from Windows host using either WSL or Virtual Box Ubuntu 20.04.

#### Environment Details

See attached files.

* NDK Version: Not sure how to find this out in my environment
* Build system: Lineage OS 18.1
* Host OS: Ubuntu 20.04 - Intel Core i7-11700K
* ABI: armv7a
* NDK API level: -
* Device API level: Android 11

[CLangCrash.zip](https://github.com/android/ndk/files/7120312/CLangCrash.zip)

**Comment by Slion** [comment]
I can't reproduce the error. It always crashes differently. Lately it just crashed and froze  the whole system, had to do a hard reset. I think it's fair to assume this is a hardware issue. I've reset my BIOS including RAM clock from 3600 Mhz down to default 2133 Mhz see how far it goes this time.

**Comment by pirama-arumuga-nainar** [comment]
The '-j' parallelism is likely set too high causing your machine to run out of memory.

**Comment by Slion** [comment]
> The '-j' parallelism is likely set too high causing your machine to run out of memory.

It's got 64GB of RAM and it never passed 20GB of use so it seems unlikely. I blame RAM overclock as explained above. Still I could not complete a build yet cause I believe my repo was corrupted too so I had to resync first.
