### ISSUE TITLE
[BUG]   SIGHUP received, exiting lldb-server... 

### ISSUE THREAD

**Issue by Catherinelhl** [android/ndk#1579]
SIGHUP received, exiting lldb-server...
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: /data/data/org.telegram.messenger.beta/lldb/bin/lldb-server platform --server --listen unix-abstract:///org.telegram.messenger.beta-0/platform-1631019858710.sock --log-file /data/data/org.telegram.messenger.beta/lldb/log/platform.log --log-channels lldb process:gdb-remote packets 
1.	Program arguments: /data/data/org.telegram.messenger.beta/lldb/bin/lldb-server platform --server --listen unix-abstract:///org.telegram.messenger.beta-0/platform-1631019858710.sock --log-file /data/data/org.telegram.messenger.beta/lldb/log/platform.log --log-channels lldb process:gdb-remote packets 
[归档.zip](https://github.com/android/ndk/files/7121894/default.zip)

**Comment by stephenhines** [comment]
This needs more information @Catherinelhl. We'll need an apk or binary that reproduces this problem to proceed.
