### ISSUE TITLE
[BUG] ndk-r21b failed to build openmp_llvm

### ISSUE THREAD

**Issue by xingjinglu** [android/ndk#1583]
When build armv8a version openmp_llvm with NDK-r21b, it failed.

1. openmp_llvm: https://android.googlesource.com/toolchain/openmp_llvm
android-ndk tool: android-ndk-r21b

2. CMake version: 3.16.5

3. CMake command: 
```bash   
NDK=/root/software/android-ndk-r21b
CXX=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
CC=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

CXX=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
CC=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

function build_armv8(){
  rm -rf armv8
  mkdir -p armv8
  pushd armv8
  cmake -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX" \
    -DANDROID_NDK=$NDK \
    -DCMAKE_TOOLCHAIN_FILE="$NDK/build/cmake/android.toolchain.cmake" \
    -DANDROID=1 \
    -DANDROID_ABI=arm64-v8a \
    -DOPENMP_ENABLE_LIBOMPTARGET=FALSE \
    -DLIBOMP_LIBFLAGS="-llog" \
    -DLIBOMP_ENABLE_SHARED=on  \
    -DLIBOMP_ARCH=aarch64 \
    -DCMAKE_BUILD_TYPE=release ../..

```  

4. Error msseages:

[ 91%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_version.cpp.o
cd /project/openmp_llvm/build/armv8/runtime/src && /root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -Domp_EXPORTS -I/project/openmp_llvm/build/armv8/runtime/src -I/project/openmp_llvm/runtime/src -I/project/openmp_llvm/runtime/src/i18n -I/project/openmp_llvm/runtime/src/include/50 -I/project/openmp_llvm/runtime/src/thirdparty/ittnotify -I/project/openmp_llvm/runtime/src/android  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++11 -O2 -DNDEBUG  -fPIC   -D _GNU_SOURCE -D _REENTRANT -fno-exceptions -fno-rtti -Wsign-compare -Wunused-function -Wunused-local-typedef -Wunused-value -Wunused-variable -Wdeprecated-register -Wunknown-pragmas -Wcomment -Wself-assign -Wformat-pedantic -Wno-switch -Wno-covered-switch-default -Wno-gnu-anonymous-struct -Wno-missing-field-initializers -Wno-missing-braces -Wno-vla-extension -Wcast-qual -o CMakeFiles/omp.dir/kmp_version.cpp.o -c /project/openmp_llvm/runtime/src/kmp_version.cpp
[ 94%] Building CXX object runtime/src/CMakeFiles/omp.dir/ompt-general.cpp.o

cd /project/openmp_llvm/build/armv8/runtime/src && /root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/ro
ot/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -Domp_EXPORTS -I/project/openmp_llvm/build/armv8/runtime/src -I/project/openmp_llvm/runtime/src -I/project/openmp_llvm/runtime/src/i18n -I/project/openmp_llvm/runtime/src/include/50 -I/project/openmp_llvm/runtime/src/thirdparty/ittnotify -I/project/openmp_llvm/runtime/src/android  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++11 -O2 -DNDEBUG  -fPIC   -D _GNU_SOURCE -D _REENTRANT -fno-exceptions -fno-rtti -Wsign-compare -Wunused-function -Wunused-local-typedef -Wunused-value -Wunused-variable -Wdeprecated-register -Wunknown-pragmas -Wcomment -Wself-assign -Wformat-pedantic -Wno-switch -Wno-covered-switch-default -Wno-gnu-anonymous-struct -Wno-missing-fiel
d-initializers -Wno-missing-braces -Wno-vla-extension -Wcast-qual -o CMakeFiles/omp.dir/ompt-general.cpp.o -c /project/openmp_llvm/runtime/src/ompt-general.cpp
[ 97%] Building C object runtime/src/CMakeFiles/omp.dir/z_Linux_asm.S.o
cd /project/openmp_llvm/build/armv8/runtime/src && /root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --gcc-toolchain=/root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/root/software/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Domp_EXPORTS -I/project/openmp_llvm/build/armv8/runtime/src -I/project/openmp_llvm/runtime/src -I/project/openmp_llvm/runtime/src/i18n -I/project/openmp_llvm/runtime/src/include/50 -I/project/openmp_llvm/runtime/src/thirdparty/ittnotify -I/project/openmp_llvm/runtime/src/android  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O2 -DNDEBUG  -fPIC   -D _GNU_SOURCE -D _REENTRANT -x assembler-with-cpp -o CMakeFiles/omp.dir/z_Linux_asm.S.o   -c /project/openmp_llvm/runtime/src/z_Linux_asm.S
**/project/openmp_llvm/runtime/src/z_Linux_asm.S:1419:18: error: expected '[su]xt[bhw]' with optional integer in range [0, 4]
 sub sp, sp, w9, lsl #4**

**Comment by DanAlbert** [comment]
r21 is no longer supported. Do you see this with r23?

**Comment by enh-google** [comment]
seems like your copy of openmp is *very* out of date, and in particular missing https://github.com/llvm/llvm-project/commit/025df3b8270083666c5e091810216d1bc9e7fe6e#diff-086f7c2cb91c4a027b64f1859c9898934c313a688e25b3af8adf4499cdb6732c which fixed this in 2019...

@pirama-arumuga-nainar --- is https://android.googlesource.com/toolchain/openmp_llvm meant to be supported/used?

**Comment by enh-google** [comment]
@kongy too, since it looks like you did the last update to toolchain/openmp_llvm 2.5 years ago?

**Comment by pirama-arumuga-nainar** [comment]
No, `toolchain/openmp_llvm` is no longer supported.  We migrated to LLVM's [monorepo](https://github.com/llvm/llvm-project).  Please use `toolchain/llvm-project/openmp`.

**Comment by stephenhines** [comment]
For any of these defunct projects, perhaps we should make a pass through the LLVM-related ones and remove them, with a note on where to get the latest versions. I think I'll file a bug internally about this.

**Comment by enh-google** [comment]
yeah, +1 to not just removing them from the manifest but actually emptying out the repository --- other than a README.md (containing what you just said) and an OWNERS file (to prevent necromancy :-( ).

**Comment by stephenhines** [comment]
http://b/199747447 for internal folks. Thanks, @enh-google for reminding me about OWNERS too.
