### ISSUE TITLE
M1 simpleperf

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1584]
Subtask of https://github.com/android/ndk/issues/1299.

**Comment by yabinc** [comment]
I have checked that simpleperf binaries in ndk r25 beta are universal binaries, and simpleperf scripts can load the report library correctly. So I think no work is needed for supporting M1 in simpleperf, except for testing on M1 when releasing new prebuilts.

**Comment by DanAlbert** [comment]
Pulling this out of the old releases because I'm not sure if there are any breaking changes in the new simpleperf that would cause issues. r25 has the fix.
