### ISSUE TITLE
[BUG] error: unknown target CPU 'xscale'

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1597]
Hi Team,

Currently I am migrating our NDK from R21b to R23 and while compiling the code I hit the following error

Running: F:\nugetcache\androidndk.23.0.1\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe @f:\ndkug\build\droidx86\debug\ourprojectsrc\objd\droidx86\android_clang_cpp_flags.rsp -c f:\ndkug\dev\ourprojectsrc\version_set.cc -o f:\ndkug\build\droidx86\debug\ourprojectsrc\objd\droidx86\clang-temp\version_set.cc\compile.tmp
**error: unknown target CPU 'xscale'**
note: valid target CPU values are: i386, i486, winchip-c6, winchip2, c3, i586, pentium, pentium-mmx, pentiumpro, i686, pentium2, pentium3, pentium3m, pentium-m, c3-2, yonah, pentium4, pentium4m, prescott, nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, lakemont, k6, k6-2, k6-3, athlon, athlon-tbird, athlon-xp, athlon-mp, athlon-4, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, geode
Exit code: 1

when I did little investigation I found clang 12.0.5 is taking argument "-tune-cpu xscale" by default but clang 9.0.8 which is shipped with R21b is not taking any such default argument. 

Could you please help me how to fix this issue.

Thanks..

#### Environment Details

* NDK Version: R23

**Comment by enh-google** [comment]
i think clang is correct to say "no, you can't compile Android code specifically for a hilariously obsolete armv*5* CPU that definitely never ran Android [https://en.wikipedia.org/wiki/XScale]"? i think the fix is to stop passing that flag?
