### ISSUE TITLE
Android NDK issue with boost/log

### ISSUE THREAD

**Issue by fanStefan** [android/ndk#1602]
While trying Android NDK [example](https://docs.bazel.build/versions/main/android-ndk.html), I add boost/log/trivial.hpp as dependency, but there is a problem when I build with any of the configurations defined in .bazelrc. Example for reproduction is [here](https://github.com/nelhage/rules_boost/files/7467928/boost-ndk-issue.zip).

Android packages should be installed and paths, to SDK and NDK, should be updated in WORKSPACE file.
Tested with `platforms;android-29`, `build-tools;29.0.3` and `ndk;21.0.6113669` packages (easiest to install is with `Command line tools`).
[Command line tools](https://developer.android.com/studio) could be found at the bottom of the page.
[Instructions](https://developer.android.com/studio/command-line/sdkmanager#install_packages) of how to install needed packages.

Here is the log of `bazel build :jni_lib --config=android_x86`:
> In file included from external/org_lzma_lzma/src/liblzma/lzma/lzma_encoder_optimum_normal.c:14:
> external/org_lzma_lzma/src/liblzma/common/memcmplen.h:97:31: error: implicit declaration of function '_mm_movemask_epi8' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>                 const uint32_t x = 0xFFFF ^ _mm_movemask_epi8(_mm_cmpeq_epi8(
>                                             ^
> external/org_lzma_lzma/src/liblzma/common/memcmplen.h:97:49: error: implicit declaration of function '_mm_cmpeq_epi8' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>                 const uint32_t x = 0xFFFF ^ _mm_movemask_epi8(_mm_cmpeq_epi8(
>                                                               ^
> external/org_lzma_lzma/src/liblzma/common/memcmplen.h:98:4: error: implicit declaration of function '_mm_loadu_si128' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>                         _mm_loadu_si128((const __m128i *)(buf1 + len)),
>                         ^
> external/org_lzma_lzma/src/liblzma/common/memcmplen.h:98:27: error: unknown type name '__m128i'
>                         _mm_loadu_si128((const __m128i *)(buf1 + len)),
>                                                ^
> external/org_lzma_lzma/src/liblzma/common/memcmplen.h:99:27: error: unknown type name '__m128i'
>                         _mm_loadu_si128((const __m128i *)(buf2 + len))));
>                                                ^

When `bazel build :jni_lib --config=android_armeabi-v7a` is used, log is different but also happens only when boost/log is used.

Is this expected behavior?

**Comment by DanAlbert** [comment]
The following file finds those functions just fine with ndk-build:

```
#include <emmintrin.h>

int main(int argc, char** argv) {
  _mm_cmpeq_epi8();
  return 0;
}
```

Either the boost source forgot the include or there's something wrong with bazel. If the former you can send a bug or patch to boost, if latter you'll need to file a bazel bug.

**Comment by fanStefan** [comment]
Thank you @DanAlbert!

**Comment by fanStefan** [comment]
I just check if `immintrin.h` is available, for x86, in NDK that I am using, and it looks like there is only for x86_64:

> ./toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/include/immintrin.h
> ./toolchains/renderscript/prebuilt/linux-x86_64/clang-include/immintrin.h

Same for `emmintrin.h`, it:

> ./toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/include/emmintrin.h
> ./toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/include/ppc_wrappers/emmintrin.h
> ./toolchains/renderscript/prebuilt/linux-x86_64/clang-include/emmintrin.h

Does x86 version intentionally missing?
