### ISSUE TITLE
CMAKE_SYSTEM_PROCESSOR variable not set in android.toolchain.cmake

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#1603]
android-ndk 23.0.7599858

[cmake document](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html)

When cross-compiling, a CMAKE_TOOLCHAIN_FILE should set the CMAKE_SYSTEM_PROCESSOR variable to match target architecture that it specifies (via CMAKE_<LANG>_COMPILER and perhaps CMAKE_<LANG>_COMPILER_TARGET).

**Comment by DanAlbert** [comment]
Works for me.

```
$ cat ./CMakeLists.txt
cmake_minimum_required(VERSION 3.6.0)
project(CMAKE_SYSTEM_PROCESSOR_test CXX)

message(STATUS "CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
$ cat ./build.sh
#!/bin/sh
if [ $# -lt 1 ]; then
  >&2 echo "usage: ./build.sh NDK_PATH"
  exit 1
fi

set -e

NDK_PATH=$(realpath $1)

cd "$(dirname "$0")"
rm -rf build
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
  ${@:2} -GNinja ..
$ ./build.sh ~/src/android-ndk-r23
-- Android: Targeting API '16' with architecture 'arm', ABI 'armeabi-v7a', and processor 'armv7-a'
-- Android: Selected unified Clang toolchain
-- The CXX compiler identification is Clang 12.0.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/danalbert/src/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM_PROCESSOR=armv7-a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/danalbert/src/ndk/ndk/foo/build
```

> -- CMAKE_SYSTEM_PROCESSOR=armv7-a

**Comment by leleliu008** [comment]
the new version ndk has belove logic:

```
if(DEFINED ANDROID_USE_LEGACY_TOOLCHAIN_FILE)
    set(_USE_LEGACY_TOOLCHAIN_FILE ${ANDROID_USE_LEGACY_TOOLCHAIN_FILE})  elseif(CMAKE_VERSION VERSION_LESS "3.21")
    set(_USE_LEGACY_TOOLCHAIN_FILE true)                                  else()
    set(_USE_LEGACY_TOOLCHAIN_FILE false)                                 endif()

if(_USE_LEGACY_TOOLCHAIN_FILE)        
    include("${CMAKE_CURRENT_LIST_DIR}/android-legacy.toolchain.cmake")
    return()
endif()
```
if cmake version less than 3.21, android-legacy.toolchain.cmake will be used. my camke version  is 3.21.3

CMAKE_SYSTEM_PROCESSOR is set in android-legacy.toolchain.cmake, not set in android.toolchain.cmake

**Comment by DanAlbert** [comment]
```
$ cmake --version
cmake version 3.21.3
```

This works just fine for me. We need an example CMake file that demonstrates a problem.

**Comment by leleliu008** [comment]
I have reading the cmake source code these days, I find that `CMAKE_SYSTEM_PROCESSOR` is set by cmake internal moudle [Android-Determine.cmake](https://github.com/Kitware/CMake/blob/master/Modules/Platform/Android-Determine.cmake) only if Host os is not Android. when Host os is Android, it is not set. there is no offical NDK for Android though, actually some people compile NDK for Android from `AOSP`, which means we can cross- compile projects on Android system. so I sugguest set `CMAKE_SYSTEM_PROCESSOR` in `android.toolchain.cmake`. of course, user can set it via command-line option: `-DCMAKE_SYSTEM_PROCESSOR=armv7-a`

**Comment by DanAlbert** [comment]
Please provide a repro case of you want us to investigate. I've provided a repro case above that shows this works. We need to know what you're doing differently.

**Comment by enh-google** [comment]
i think they're trying to say that they're running the NDK *on* the device?

**Comment by leleliu008** [comment]
Yes, I'm running own build of NDK(from AOSP) on Android device.

**Comment by leleliu008** [comment]
@DanAlbert this is not a bug. this problem occur only when running NDK on Android device.

**Comment by rprichard** [comment]
> I find that CMAKE_SYSTEM_PROCESSOR is set by cmake internal moudle Android-Determine.cmake only if Host os is not Android. when Host os is Android, it is not set.

I assume this is referring to this code in Android-Determine.cmake:

```
# Natively compiling on an Android host doesn't use the NDK cross-compilation
# tools.
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Android")
  return()
endif()
```

Apparently this code was added for termux:
https://gitlab.kitware.com/cmake/cmake/-/issues/19840

**Comment by leleliu008** [comment]
@rprichard yes, you're right. I find that many people especially Android developes use Android devices as their alternative workstation.
