### ISSUE TITLE
[BUG] NDK R23's Clang  does not support -Wno-microsoft-exception-spec

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1611]
The following code is compiled with NDK R21 but with R23 its throwing error 'func' is missing exception specification 'noexcept'
```
void func() noexcept;
void func() {}
```

Godbolt link for Clang 9 (NDK R21b is shipped with Clang 9.0.8): https://godbolt.org/z/vEha3nrrT 
Godbolt link for Clang 12 (NDK R23 is shipped with Clang 12.0.5): https://godbolt.org/z/9r8T58n6T 

So, is clang going not to support "-Wno-microsoft-exception-spec" anymore ? 
Or is support for this flag removed by mistake.

#### Environment Details

* NDK Version: NDK R23 "23.0.7599858"

**Comment by enh-google** [comment]
the fact that it still seems to accept both -fms-exception-spec and -Wno-microsoft-exception-spec (but they just don't do anything) does make it seem more like a bug than a deliberate removal...

**Comment by DanAlbert** [comment]
Looking back at this for the first time in a while, I think you've misunderstood what clang is telling you.

```
<source>:3:6: error: 'func' is missing exception specification 'noexcept'
```

You're asking about `-Wno-microsoft-exception-spec`, which would suppress a warning. This is not a warning. This is an error. The sample code you gave is almost verbatim the example of the disallowed code on cppreference: https://en.cppreference.com/w/cpp/language/noexcept_spec

```c++
void f() noexcept;
void f(); // error: different exception specification
```

Earlier clangs apparently failed to diagnose that error.
