### ISSUE TITLE
[BUG] NDK r23b caused power consumption increases

### ISSUE THREAD

**Issue by DaydreamCoding** [android/ndk#1613]
#### Description

For most algorithms, NDK R23b causes power consumption increase compared with NDK R22b/R21e.

#### Environment Details

* NDK Version: NDK r23b
* Build system: CMake
* Host OS: Mac intel
* ABI: arm64-v8a
* NDK API level: android-21
* Device API level: android-30

**Comment by DaydreamCoding** [comment]
#1607

**Comment by rumas84** [comment]
it's out of topic but what can i say is : r22b the best version until now of all versions

**Comment by DaydreamCoding** [comment]
> it's out of topic but what can i say is : r22b the best version until now of all other versions

but, dma-buff need to use NDK r23

**Comment by DanAlbert** [comment]
We need a repro case to investigate.
