### ISSUE TITLE
when unlock  the debug

### ISSUE THREAD

**Issue by xuanxuan343** [android/ndk#1615]
> Task :game:externalNativeBuildDebugFeature FAILED
:game:externalNativeBuildDebugFeature (Thread[Task worker for ':' Thread 8,5,main]) completed. Took 25 mins 23.66 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':game:externalNativeBuildDebugFeature'.
> Build command failed.
  Error while executing process D:\Android\android_SDK\ndk\19.2.5345600\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\cocosCreator\AStar_debug\build\jsb-link\frameworks\runtime-src\proj.android-studio\game\jni\Android.mk NDK_APPLICATION_MK=D:\cocosCreator\AStar_debug\build\jsb-link\frameworks\runtime-src\proj.android-studio\game\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=D:/cocosCreator/AStar_debug/build/jsb-link/frameworks/runtime-src/proj.android-studio/game/build/intermediates/ndkBuild/feature/debug/obj NDK_LIBS_OUT=D:\cocosCreator\AStar_debug\build\jsb-link\frameworks\runtime-src\proj.android-studio\game\build\intermediates\ndkBuild\feature\debug\lib NDK_TOOLCHAIN_VERSION=clang NDK_MODULE_PATH=D:\cocos\CocosDashboard\resources\.editors\Creator\2.4.3\resources\cocos2d-x;D:\cocos\CocosDashboard\resources\.editors\Creator\2.4.3\resources\cocos2d-x\cocos;D:\cocos\CocosDashboard\resources\.editors\Creator\2.4.3\resources\cocos2d-x\external -j12 NDK_DEBUG=1 D:/cocosCreator/AStar_debug/build/jsb-link/frameworks/runtime-src/proj.android-studio/game/build/intermediates/ndkBuild/feature/debug/obj/local/armeabi-v7a/libcocos2djs.so}
  Android NDK: WARNING: Unsupported source file extensions in D:\cocos\CocosDashboard\resources\.editors\Creator\2.4.3\resources\cocos2d-x/cocos/Android.mk for module cocos2dx_static    
  Android NDK:   ../external/sources/edtaa3func/edtaa3func.h renderer/memop/RecyclePool.hpp

**Comment by DanAlbert** [comment]
There's no usable information here. All that log says is "the build failed". We need a test case or at least more context for the failure.
