### ISSUE TITLE
NDK download url not contain arch info from r23

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#1616]
https://developer.android.com/ndk/downloads

I noticed that the NDK download url not contain arch info from r23. I don't know whether it was intentional or accidentally. I highly recommend NDK download url contains arch info though now NDK only support x86_64 arch. since aarch64 become more and more popular(Android, Linux, macOS, Windows all support aarch64), NDK maybe will support aarch64 in the future, x86_64 and aarch64 will coexist in the future. From the perspective of users, I knonw Linux, macOS, Windows support aarch64 but the download url not contain arch info, so I think the archive is universal(means support all arch), but actually only support x86_64, this make me confused.

**Comment by DanAlbert** [comment]
> I highly recommend NDK download url contains arch info though

It doesn't because the Darwin package is multi arch. If we left it as x86_64 the SDK couldn't show the package on M1 Macs. It was removed from all the package names for consistency.

**Comment by enh-google** [comment]
(we can worry about windows/arm64 and linux/arm64 if and when that's an actual problem :-) right now we only have plans to support darwin/arm64 where this isn't an issue, as danalbert said.)
