### ISSUE TITLE
Cmake generate random path for "cxxBuildFolder" on AGP 7.0.2

### ISSUE THREAD

**Issue by vershininds** [android/ndk#1617]
#### Description
After migrate project on:
Version of Gradle Plugin: 7.0.2
Version of Gradle: 7.2

Cmake generate random path for "cxxBuildFolder"
"project_path/.cxx/Debug/zxn24535/x86_64"
Path contains "zxn24535", this is a dynamic piece. Dynamic path breaks cache usage

if switch to AGP=4.1.1
path is correct "project_path/.cxx/cmake/debug/x86_64"

#### Environment Details

* AGP Version: 7.0.2
* Gradle Version: 7.2
* NDK Version:  23.1.7779620
* CMake Version: 3.18.1
* Build system: CMake
* Host OS: Windows, Linux
* ABI: "armeabi-v7a", "arm64-v8a", "x86_64"

**Comment by DanAlbert** [comment]
> if switch to AGP=4.1.1

Sounds like this is an AGO bug rather than an NDK bug then. You'll need to file it against Studio at b.android.com

**Comment by enh-google** [comment]
@vershininds --- so we can try to improve our process, can you help us understand why you didn't choose the "Android Studio and Gradle issues" option (which would have told you to file a bug at https://developer.android.com/studio/report-bugs instead)?

**Comment by vershininds** [comment]
@enh-google 
> @vershininds --- so we can try to improve our process, can you help us understand why you didn't choose the "Android Studio and Gradle issues" option (which would have told you to file a bug at https://developer.android.com/studio/report-bugs instead)?

I read documentation about Cmake and toolchain arguments at this link:
https://developer.android.com/ndk/guides/cmake

In the end of document I saw link for report problems about NDK and Cmake:
https://developer.android.com/ndk/guides/cmake#issue

**Comment by enh-google** [comment]
thanks! i'll get the docs updated to explicitly mention where to file grade issues too then. (since it seemed like you knew this was really a problem with AGP, but didn't know that needed to be handled differently, and i think that's a pretty common cause of confusion. sadly we haven't [yet] persuaded them to use the github bug tracker :-( )

**Comment by shakti-hub** [comment]
The folder name comes from the HASH value. I'm still not sure how to turn off the HASH.

**Comment by DanAlbert** [comment]
This is an AGP thing, not an NDK thing. You'll need to file a Studio bug to contact the right people.
