### ISSUE TITLE
No PGO profile raw file was found on Android

### ISSUE THREAD

**Issue by juniorprincewang** [android/ndk#1622]
In order to add PGO for native Android app, I was following Pirama Arumuga Nainar's blog [Profile guided optimization for native Android applications](https://medium.com/androiddevelopers/pgo-for-native-android-applications-1a48a99e95d0). 
I choose a demo from ndk samples <https://github.com/android/ndk-samples/tree/main/nn-samples/basic>

The NDK Version is 22.1.7171670, Device API level is 30.
Adding `-fprofile-generate` to cpp flags.
```
externalNativeBuild {
            cmake {
                cppFlags "-std=c++14 -fprofile-generate "
            }
        }
```
Calling the `__llvm_profile_write_file` function before the end of workload.
However, after executing the app, no profile file named default_unique_id_0.profraw was found in */data/local/tmp* on Android.
Although I set up `LLVM_PROFILE_FILE` env to */data/local/tmp*, nothing happened.

Looking forward to answering, thank you.

**Comment by stephenhines** [comment]
@pirama-arumuga-nainar should be able to check on this, as well as what might be preventing it from creating the profile files. Are you sure that `__llvm_profile_write_file` is being called before the app exits? If not, there might be nothing to write. The file should be called `default.profraw`, so maybe just look for and `.profraw` files in the output directory (and also check the app's directory too, in case the environment variable wasn't set.

**Comment by pirama-arumuga-nainar** [comment]
What is `LLVM_PROFILE_FILE` set to?  It should be a location that's writable from the app.

If you have just one native library with PGO instrumentation, you can also call [`__llvm_profile_set_filename(const char *)`](https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/profile/InstrProfiling.h#L163) to set the file name.

**Comment by juniorprincewang** [comment]
> What is `LLVM_PROFILE_FILE` set to? It should be a location that's writable from the app.
> 
> If you have just one native library with PGO instrumentation, you can also call [`__llvm_profile_set_filename(const char *)`](https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/profile/InstrProfiling.h#L163) to set the file name.

Thank you for your mention of file access operation. The original path is reported the error "Read-only file system". A writable location can generate a default.profraw file.

**Comment by juniorprincewang** [comment]
> @pirama-arumuga-nainar should be able to check on this, as well as what might be preventing it from creating the profile files. Are you sure that `__llvm_profile_write_file` is being called before the app exits? If not, there might be nothing to write. The file should be called `default.profraw`, so maybe just look for and `.profraw` files in the output directory (and also check the app's directory too, in case the environment variable wasn't set.

Your answer really helps me quite a lot, thank you!
Actually, I was misguided by the instruction from <https://source.android.com/devices/tech/perf/pgo#handling-llvm-profile-files>
> Executing an instrumented library or executable produces a profile file named default_unique_id_0.profraw in /data/local/tmp (where unique_id is a numeric hash that is unique to this library). 

Again, thanks a lot!

**Comment by enh-google** [comment]
> Actually, I was misguided by the instruction from https://source.android.com/devices/tech/perf/pgo#handling-llvm-profile-files

which part specifically? (we can improve the docs if you can point out the bit that misled you...)

**Comment by pirama-arumuga-nainar** [comment]
> we can improve the docs

+1.

We should also consider moving the "instructional" part of the medium blog to the NDK docs so we can keep it updated.

**Comment by enh-google** [comment]
since there's also an android-ndk thread about this, i'll try to keep the two in sync...

> i'll update the docs to explicitly point out that /data/local/tmp isn't usually accessible.
>
> +Pirama Arumuga Nainar --- can we just fix this in LLVM? if i'm understanding the docs right, they're implying that /data/local/tmp is the *default*[1], so there's already some Android-specific code here. can we just make it a bit cleverer? on recent versions of Android, $TMPDIR should be set correctly to a usable directory[2], so even if it's hard to do the perfect thing on old OS versions, it should be easy on new OS versions (and that shouldn't give _worse_ behavior on old OS versions).
>
> ____
> 1. tbh, the docs and source don't seem to match? the *source* seems to imply that you get a "default.profraw" file in the cwd, but the *docs* explicitly claim that it's in /data/local/tmp?
> 2. "you're welcome" :-)
