### ISSUE TITLE
[BUG] CMake crash with NDK 23.1.7779620

### ISSUE THREAD

**Issue by jkransom** [android/ndk#1624]
#### Description

When building my native project, the build stops in seemingly random places and tells me: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.

I've hopefully attached the necessary files.

#### Environment Details

* NDK Version: 23.1.7779620
* Build system: CMake
* Host OS: Windows 10
[ActionItemEditor-a3eebd.zip](https://github.com/android/ndk/files/7684739/ActionItemEditor-a3eebd.zip)

**Comment by pirama-arumuga-nainar** [comment]
> When building my native project, the build stops in seemingly random places

Your workstation may be running out of memory because the parallelism (set by `-j`) is too high.  Moreover, the reproducer works fine with the r23 clang (albeit on Linux).  If you can get a reliable crash with a lower `-j`, please reopen.
