### ISSUE TITLE
Which ndk version starts to support PGO

### ISSUE THREAD

**Issue by juniorprincewang** [android/ndk#1625]
Hello,
When I tried to add PGO for an old native Andorid project with ndk r12b, I ran into the following problem: 

> external/compiler-rt/lib/profile/InstrProfilingFile.c:36: error: undefined reference to '__llvm_profile_gather_value_data'
> external/compiler-rt/lib/profile/InstrProfilingFile.c:37: error: undefined reference to 'llvmWriteProfData'

These two functions are undefined symbols from *libclang_rt.profile-arm-android.a*.

I was wondering if r12b supports PGO. If not, from which version PGO was added?

Would appreciate any help.

**Comment by enh-google** [comment]
we don't seem to have recorded anything in the release notes (https://developer.android.com/ndk/downloads/revision_history.html) but we wouldn't recommend anything older than the current LTS release (r23) anyway :-)
