### ISSUE TITLE
[BUG] fdsan catches issue in libc++ test on new devices

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1626]
```bash
$ ./run_tests.py --filter libc++.std/input.output/file.streams/fstreams/filebuf.members/close.pass.cpp
FAIL libc++.std/input.output/file.streams/fstreams/filebuf.members/close.pass.cpp [armeabi-v7a-19-new]: adb -s 06081FQCB00096 shell 'cd /data/local/tmp/tests/armeabi-v7a-19-new/libcxx/libc++/std/input.output/file.streams/fstreams/filebuf.members && LD_LIBRARY_PATH=/data/local/tmp/tests/armeabi-v7a-19-new/libcxx/libc++ ./close.pass.cpp.exe 2>&1'
android-32 bramble 06081FQCB00096 S2B1.211112.006
fdsan: attempted to close file descriptor 3, expected to be unowned, actually owned by FILE* 0xee102ecc
Aborted 

FAIL libc++.std/input.output/file.streams/fstreams/filebuf.members/close.pass.cpp [arm64-v8a-21-new]: adb -s 06081FQCB00096 shell 'cd /data/local/tmp/tests/arm64-v8a-21-new/libcxx/libc++/std/input.output/file.streams/fstreams/filebuf.members && LD_LIBRARY_PATH=/data/local/tmp/tests/arm64-v8a-21-new/libcxx/libc++ ./close.pass.cpp.exe 2>&1'
android-32 bramble 06081FQCB00096 S2B1.211112.006
fdsan: attempted to close file descriptor 3, expected to be unowned, actually owned by FILE* 0x7b6981b028
Aborted
```

Not diagnosed yet. Probably is a bug in the test though.

**Comment by enh-google** [comment]
yeah:
```
        // Close the file descriptor directly to force filebuf::close to fail.
        assert(close(fd) == 0);
        // Ensure that filebuf::close handles the failure.
        assert(f.close() == nullptr);
```
that's not cool.

(have we really never run the tests on anything new enough to have fdsan?)

**Comment by DanAlbert** [comment]
> (have we really never run the tests on anything new enough to have fdsan?)

We were testing on API 29 devices (that's what was new when the pandemic started, and we couldn't move it forward when no one had access to their devices). Now that we do actually have easy access again I just moved us to 32: https://android-review.googlesource.com/c/platform/ndk/+/1916680.

I thought fdsan was older than that, but maybe 30/31 is when it first became enforcing rather than a warning?

**Comment by DanAlbert** [comment]
Test was added in https://reviews.llvm.org/D64979. It seems like they had some double close somewhere that asan was warning them about and they wanted to silence the warning?

**Comment by DanAlbert** [comment]
Ah, actually, it was a `filebuf::close` that was being doubled, not a `close`. That's a different story. Change seems correct but the test is just bad on Android.

**Comment by enh-google** [comment]
> I thought fdsan was older than that, but maybe 30/31 is when it first became enforcing rather than a warning?

yeah, you're right. https://android-review.googlesource.com/c/platform/bionic/+/1917499/ improves the docs to make that clearer. (the bionic "status.md" already mentions this, but it seems odd for the fdsan docs themselves not to!)

**Comment by DanAlbert** [comment]
These tests are now run as part of the toolchain tests, not here (and @rprichard already found this and was working on a fix).
