### ISSUE TITLE
[BUG] is_unsigned behavior of NDK R21 and NDK R23 is different for enums

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1632]
I have the following code

```
#include<type_traits>
enum TestEnum
{
	A,
	B,
	C
};

static_assert(is_unsigned<TestEnum>::value, "TestEnum is not unsigned");
```

on compiling this snippet,

NDK R21 output: error: static_assert failed due to requirement '**is_unsigned<TestEnum>::value**' "**TestEnum** is not unsigned"
NDK R23 output: <No output>

On little investigation, when compiling with NDKR23, it is hitting the **#if __has_keyword(__is_unsigned)** part of the code and using the  **__is_unsigned** keyword supported by Clang which is evaluating **TestEnum** to be unsigned. 

IMO, enum should be considered as unsigned. So I believe Clang's **__is_usigned** is wrong here.

Could you please confirm and get this fixed if you agree.

Also is there any compiler flag that I can use to tell the compiler not to  use **__is_unsigned** .i.e. not to take #if **__has_keyword(__is_unsigned)** path. (I want to avoid making changes to NDK).

#### Environment Details
* NDK Version: 23.0.7599858

**Comment by DanAlbert** [comment]
> IMO, enum should be considered as unsigned.

It's implementation defined behavior unless you specify the backing type explicitly. Definitely do that if you care about the size or signedness of the enum. Clang supports this even in C mode, so you don't have to worry about compatibility with legacy code.

> On little investigation, when compiling with NDKR23, it is hitting the #if __has_keyword(__is_unsigned) part of the code

What code?

> NDK R21 output: error: static_assert failed due to requirement 'is_unsigned::value' "TestEnum is not unsigned"
> NDK R23 output:

I see the same results for both r21e and r23, btw:

```
$ cat foo.cpp
#include<type_traits>
enum TestEnum
{
	A,
	B,
	C
};

static_assert(std::is_unsigned<TestEnum>::value, "TestEnum is not unsigned");
$ ~/src/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ foo.cpp
foo.cpp:9:1: error: static_assert failed due to requirement 'std::is_unsigned<TestEnum>::value' "TestEnum is not unsigned"
static_assert(std::is_unsigned<TestEnum>::value, "TestEnum is not unsigned");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
$ ~/src/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ foo.cpp
foo.cpp:9:1: error: static_assert failed due to requirement 'std::is_unsigned<TestEnum>::value' "TestEnum is not unsigned"
static_assert(std::is_unsigned<TestEnum>::value, "TestEnum is not unsigned");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

If there's additional configuration needed to reproduce the behavior you're seeing, we need to know that. Please be sure to provide repro steps for bugs in the future. It's _extremely_ difficult to guess, and just results in you getting answers more slowly.
