### ISSUE TITLE
[question] I rebuild hwasan in ndk, but it can't capture malloc overflow...

### ISSUE THREAD

**Issue by dentiscalprum** [android/ndk#1636]
I use android-ndk-r22 and i rebuild hwasan use this method.
[https://android.googlesource.com/toolchain/llvm_android/+/master/README.md](https://android.googlesource.com/toolchain/llvm_android/+/master/README.md)

and hwasan can't tag memory allocated by malloc.

I researched and found that there is no hook malloc.

how should i do to rebuild hwasan?

thanks!!!

**Comment by DanAlbert** [comment]
I think r22 is too old for hwasan.
