### ISSUE TITLE
[BUG] llvm-objcopy not generating output when .obj format of .a is not recognized whereas i686-linux-android-objcopy.exe works fine

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1637]
Hi Team,

Currently we are migrating our NDK from R21 to R23. So far we have been using tools ar, objcopy, ld from toochain folders based on architecture (arm, arm64, x86, x86-64). 

Before finally consuming .a's into .SO's, we are doing some preprocessing to strip empty symbols. We are compiling our source cpp files with -flto=thin. When I try to objdump compiler generated .obj files which constitute this .a file, objdump is throwing error file format not recognized. This is the case both NDK R21 and NDK R23. Anyways, when we run androidndk.21.0.17\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-objcopy.exe to strip symbols, though it is saying unable to recognize file format, it is generating output (after.a).

```
F:\SMLEL4\dev\appshared\src\test\subsystemdroid> F:\nugetcache\androidndk.21.0.17\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-objcopy.exe --redefine-sym =.L.str f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\after.a
F:\nugetcache\androidndk.21.0.17\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-objcopy.exe:f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a(exception_android.obj): Unable to recognise the format of file: File format not recognized
F:\nugetcache\androidndk.21.0.17\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-objcopy.exe:f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a(hubconnectionconfig_emptyimpl.obj): Unable to recognise the format of file: File format not recognized
//smilarly for other files present in .a file
```

In NDK R23, we see architecture specific tool chains are removed and unified into single llvm toolset. When we run objcopy from this toolset, it saying file format not recognized similar to NDK R21 but also not generating any output.

```
F:\SMLEL4\dev\appshared\src\test\subsystemdroid> F:\nugetcache\androidndk.23.0.1\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe  --redefine-sym =.L.str f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\after.a
F:\nugetcache\androidndk.23.0.1\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe: error: 'f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a(exception_android.obj)': The file was not recognized as a valid object file
```

using --input-target=elf32-i386 also not generating output.

```
F:\SMLEL4\dev\appshared\src\test\subsystemdroid> F:\nugetcache\androidndk.23.0.1\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe  --input-target=elf32-i386 --redefine-sym =.L.str f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\after.a
F:\nugetcache\androidndk.23.0.1\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe: error: 'f:\smlel4\build\droidx86\ship\appshared\src\test\subsystemdroid\obj\droidx86\stripempty\librtc.a.tmp\before.a(exception_android.obj)': The file was not recognized as a valid object file
```

Could you please tell how to solve this problem.

Thanks,
Pendyala Syam

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: NDK R23

**Comment by DanAlbert** [comment]
We need the artifacts to be able to investigate. Closing until we have the data we need.

> Before finally consuming .a's into .SO's, we are doing some preprocessing to strip empty symbols.

I don't think I follow, because this sounds like a less thorough `--strip-unneeded` with extra steps.

**Comment by pendyalasyam** [comment]
@DanAlbert , Here are the steps to repro issue:

attached a zip file containing source cpp file and ar scrpit. Run the following commands from extracted folder

**Steps:**
**NDK R21 (generating output after.a) :**  "F:\android-ndk-r21e\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe" -target i686-none-linux-android  "-Os" -flto=thin -c testarthematic.cpp -o testarthematic.obj & "F:\android-ndk-r21e\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-ar.exe" -M < ar_objscript.ri crs & "F:\android-ndk-r21e\toolchains\x86-4.9\prebuilt\wind
[repro.zip](https://github.com/android/ndk/files/7995637/repro.zip)
ows-x86_64\bin\i686-linux-android-objcopy.exe" --redefine-sym =.L.str libtest.a after.a 

**NDK R23 (not generating output after.a):** "F:\android-ndk-23\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe" -target i686-none-linux-android  "-Os" -flto=thin -c testarthematic.cpp -o testarthematic.obj & "F:\android-ndk-23\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ar.exe" -M < ar_objscript.ri  & "F:\android-ndk-23\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe" --redefine-sym =.L.str libtest.a after.a

**Comment by pendyalasyam** [comment]
Hi @DanAlbert , any update on this issue pls...

**Comment by DanAlbert** [comment]
We haven't had time to look. When there's an update we'll update the bug.

**Comment by stephenhines** [comment]
@chih-hung, can you take a look at this?

**Comment by stephenhines** [comment]
@pendyalasyam I actually looked into this on the Linux side, and I will say that even NDK r21e doesn't let you manipulate ThinLTO objects. It already prints an error message even with the older `ar` command, even though it still emits an `after.a` file:

```
/disk/ndk/android-ndk-r21e/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-objcopy --redefine-sym =.L.str libtest.a after.a
/disk/ndk/android-ndk-r21e/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-objcopy:libtest.a(testarthematic.obj): Unable to recognise the format of file: File format not recognized
```

I don't think you can use thinLTO like this. You might be able to produce the shared object and then possible run `llvm-objcopy` on that resulting library, but the current steps aren't expected to work (even if the old tools let you do that without actually performing the requested operations).
