### ISSUE TITLE
Android 10 Boringssl is crashing when tried to set ssl cert[question]

### ISSUE THREAD

**Issue by Trinath042** [android/ndk#1646]
Currently i am using Android 10 with libcurl 7.64.1 and zlib 1.2.11. Also the libcurl is using boringssl which produces libssl and libcrypto libs. 

when i tried to set ssl cert using libcurl API as below, the application got crashed and backtrace generated as below:

CURL option used: curl_easy_setopt(g_curl, CURLOPT_SSLCERT,"<cert_used>.pk12");
```
12-23 16:39:44.894 20138 20138 F DEBUG : backtrace:
12-23 16:39:44.894 20138 20138 F DEBUG : #00 pc 000000000007f540 /apex/com.android.runtime/lib64/bionic/libc.so (memset+256) (BuildId: 21847aa9757f000b0461310a9f5e6e51)
12-23 16:39:44.895 20138 20138 F DEBUG : #01 pc 00000000000e88cc /system/lib64/libcrypto.so (OPENSSL_free+44) (BuildId: 728e08164b8f1c00869b36c9f0e4108b)
12-23 16:39:44.895 20138 20138 F DEBUG : #02 pc 000000000003f9a0 /system/lib64/libssl.so (ssl_cert_append_cert(bssl::CERT*, x509_st*)+96) (BuildId: 5959c7e3dc7997917e57b0c6ac438cee)
12-23 16:39:44.895 20138 20138 F DEBUG : #03 pc 000000000003e830 /system/lib64/libssl.so (SSL_CTX_add_extra_chain_cert+24) (BuildId: 5959c7e3dc7997917e57b0c6ac438cee)
12-23 16:39:44.895 20138 20138 F DEBUG : #04 pc 0000000000054390 /system/lib64/libcurl.so (ossl_connect_common+7272) (BuildId: cf422a84526ae95a628c6fca8353ab50)
12-23 16:39:44.895 20138 20138 F DEBUG : #05 pc 0000000000056810 /system/lib64/libcurl.so (Curl_ssl_connect_nonblocking+300) (BuildId: cf422a84526ae95a628c6fca8353ab50)
12-23 16:39:44.896 20138 20138 F DEBUG : #06 pc 000000000002c8e4 /system/lib64/libcurl.so (Curl_http_connect+396) (BuildId: cf422a84526ae95a628c6fca8353ab50)
```
Even i tried with PEM type cert, still able to see same failure.

Tried to upgrade boringssl to 795025e40c83f27055148440b448545f54641c3e commit which was latest commit on Android 10, still facing same issue. Not able to set any cert with .PEM/P12 type using CURLOPT_SSLCERT.

It would be great if anybody helps me on this.

**Comment by DanAlbert** [comment]
This doesn't seem related to the NDK? I'm confused.

**Comment by DanAlbert** [comment]
I don't think you're asking the right people. You should probably file a platform bug.
