### ISSUE TITLE
[BUG] Compile (wget) with the static flag

### ISSUE THREAD

**Issue by cosmicDustOfLightLength** [android/ndk#1647]
When I configure without static flags, the program works
`./configure --host $ TARGET --without-ssl`

```
adb shell "file /data/local/tmp/wget"
/data/local/tmp/wget64: ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64)
```

#### The problem is when I configure with the static flag, the program[wget] won't start. The first time I see something like this so far, programs compiled with the static flag worked
`./configure --host $TARGET --without-ssl  CFLAGS=-static CXXFLAGS=-static`

```
adb shell "file /data/local/tmp/wget"
/data/local/tmp/wget: ELF executable, 64-bit LSB arm64, static
```
```
adb shell "/data/local/tmp/wget -h"
error: "/data/local/tmp/wget": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
```

--------------------------------------------------------------------------------

**Comment by cosmicDustOfLightLength** [comment]
Wrong API selected

**Comment by lingsixuan** [comment]
I also encountered this problem, can you tell me how you solved it?

**Comment by DanAlbert** [comment]
By the sound of things they used the wrong API level in their target for `-static`. `-static` requires using the maximum API level supported by that NDK (see `meta/platforms.json` to figure out what that is for a given NDK).
