### ISSUE TITLE
[BUG] 24.0.7956693 SIGILL crash on Exynos9810 due to aarch64 LSE atomics

### ISSUE THREAD

**Issue by maxmpz** [android/ndk#1655]
### Description

Android 8 variants crash with SIGILL on Exynos 9810 on aarch64 LSE atomics instructions due to the non-heterogeneous cores. 
-mno-atomics-outline won't help here as we still have those LSE instructions in libc++.

This was later fixed by Android 9+ kernels and also fixed in llvm, but the fix is not in NDK and there are still users with Android 8 on those device.

Please ensure this fix: https://github.com/llvm/llvm-project/commit/cce4a7258b81159e57a411896011ee2742f17def
is included into the next beta NDK release.
Thanks!

### Affected versions

r24

### Host OS

Mac

### Host OS version

macOS 11.6

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

21

**Comment by DanAlbert** [comment]
@stephenhines This sounds like the same bug we've been talking about. Did this make it into the update for the r24 toolchain that you gave me last week?

> Please ensure this fix: llvm/llvm-project@cce4a72 is included into the next beta NDK release.

The next beta is r25. We'll try to do this for r24 but RC 1 is already in QA.

**Comment by DanAlbert** [comment]
btw, in the future, please use the "LLVM bug" template for LLVM bugs. It won't waste your time with questions about build systems that aren't relevant to LLVM bugs, and will ask other questions that help us respond to bugs more effectively.

**Comment by stephenhines** [comment]
https://android-review.googlesource.com/c/toolchain/llvm_android/+/1947874 has this patch for r24. There is no fix needed for r23c as that toolchain doesn't have the breaking commit either.

**Comment by DanAlbert** [comment]
> and there are still users with Android 8 on those device.

To put your mind at ease a bit: my desk is covered in kitkat phones. We know how important support for old devices is :)

**Comment by DanAlbert** [comment]
> https://android-review.googlesource.com/c/toolchain/llvm_android/+/1947874 has this patch for r24.

(this is the toolchain that's in RC1, so you'll have the fix as soon as QA is done with it)
