### ISSUE TITLE
[BUG] -Wl,--icf=safe having no effect on binary size

### ISSUE THREAD

**Issue by Over17** [android/ndk#1670]
### Description

I added `-Wl,--icf=safe` flag to the linker invocation and found out the output binaries are identical with or without it.
Using NDK r23b, custom build system.
ABIs: arm64 and armv7, haven't checked Intel yet.

I expected that it makes the binary smaller, at least our build code comments say that with gold it brought a noticeable improvement (we also used 5 iterations).

Is it expected? Is the flag enabled by default (doesn't seem to be the case for pure LLVM)? Or is it doing nothing/broken?

### Affected versions

r23

### Host OS

Windows

### Host OS version

Win10

### Affected ABIs

armeabi-v7a, arm64-v8a

### Build system

Other (specify below)

### Other build system

custom

### minSdkVersion

21

**Comment by pirama-arumuga-nainar** [comment]
ICF operates at a section level - are you also passing `-ffunction-sections`?

It seems like `lld`'s ICF rules are stricter/different than `gold`.  @MaskRay any thoughts?

```
$ cat icf.cpp
int foo() { return 1; }
int bar() { return 1; }
```

For the above source, `ld.gold` folds `foo()` and `bar()` at `--icf=safe` but `lld` only folds with `--icf=all`:

```
$ clang++ icf.cpp -O2 -shared -ffunction-sections -Wl,--icf=safe -Wl,--print-icf-sections -fuse-ld=gold
/usr/bin/ld.gold: ICF Converged after 2 iteration(s)
/usr/bin/ld.gold: ICF folding section '.text._Z3barv' in file '/tmp/icf-8f77f1.o' into '.text._Z3foov' in file '/tmp/icf-8f77f1.o'

$ clang++ icf.cpp -O2 -shared -ffunction-sections -Wl,--icf=safe -Wl,--print-icf-sections -fuse-ld=lld
// no folding

$ clang++ icf.cpp -O2 -shared -ffunction-sections -Wl,--icf=all -Wl,--print-icf-sections -fuse-ld=lld
selected section /tmp/icf-0f13e6.o:(.text._Z3foov)
  removing identical section /tmp/icf-0f13e6.o:(.text._Z3barv)
```

**Comment by Over17** [comment]
Yes we're passing `-ffunction-sections`.

Enabling ICF on the main engine returned 0 diff.
There is some minor improvement on IL2CPP size tests, but the overall result is - with lld@r23b the binary is significantly larger than gold@r21. I'm looking into that. Bloaty is pretty awesome!

**Comment by Over17** [comment]
Did a single check with `--icf=all` and it looks good - the size is down to expected levels.

So, shall we say that `--icf=safe` produces significantly different results with lld comparing to gold? And that it's worth using `all` on lld.

**Comment by MaskRay** [comment]
For a `-shared` link of
```
$ cat icf.cpp
int foo() { return 1; }
int bar() { return 1; }
```

`ld.lld --icf=safe` assumes that symbols in `.dynsym` are address significant and two symbols cannot share the same address, so ld.lld conservatively suppresses merging `.text.foo` and `.text.bar`.

`gold --icf=safe` does merge `.text.foo` and `.text.bar`. Such a choice will be unsafe if a program uses an map and expects that `map[&foo]` and `map[&bar]` resolve to different objects.

**Comment by DanAlbert** [comment]
That sounds like the answer here then. Expected behavior, and if you're okay with that incorrectness risk, use all. @MaskRay any other differences between all and safe?

**Comment by MaskRay** [comment]
`--icf=safe` uses a special section `.llvm_addrsig` produced by Clang. If the section is absent, ld.lld is conservative and assumes every symbol in the file is address significant. `--icf=all` ignores `.llvm_addrsig`.

These are basically all observable differences.

**Comment by pirama-arumuga-nainar** [comment]
@Over17 you need to explicitly add `-faddrsig`.  Clang doesn't add it for Android: https://reviews.llvm.org/D56456.  We add `-faddrsig` in the platform build system as well.

> The NDK still supports linkers other than LLD, but we are changing the default to LLD in the next release. I'd prefer to keep this for the time being, but don't feel strongly about it.

@DanAlbert, is this still the case?  We could at least add it in the NDK build system when using lld.  (Granted some users may use unsupported build systems).

**Comment by Over17** [comment]
We have `-fvisibility=hidden` so obviously no exports by default. We have had no `-faddrsig` because GNU utils were in use with the old NDK; I added it and got fantastic results with `--icf=safe`; the arm64 engine binary got reduced by ~3.5% (2Mb).

Thank you so much for the help folks!

**Comment by pirama-arumuga-nainar** [comment]
Following up on my own comment, I think we should enable `-faddrsig` by default for Android and note in the NDK release notes to use `-fno-addrsig` when using a non-lld linker.

**Comment by DanAlbert** [comment]
Agreed, but we can skip the bit in the NDK release notes. Documenting behavior of all the tools we don't support would be exhausting :)

**Comment by FelixZhang00** [comment]
> We have `-fvisibility=hidden` so obviously no exports by default. We have had no `-faddrsig` because GNU utils were in use with the old NDK; I added it and got fantastic results with `--icf=safe`; the arm64 engine binary got reduced by ~3.5% (2Mb). The results are very close to those with `--icf=all`.
> 
> Thank you so much for the help folks!

hi, which linker are you using? gold or lld

**Comment by Over17** [comment]
@FelixZhang00 lld, this is the only linker available in NDK r23b.
