### ISSUE TITLE
[Bug]: Need LLVM version which is part of NDK

### ISSUE THREAD

**Issue by SunitaMK** [android/ndk#1673]
### Description

Hello Team,

Currently we have developed the app in React -native. and uploaded apk for Binary scanning. 
Our internal binary scanning tool detected  LLVM library with unknown version. We are building this app using NDK version - 
ndkVersion = "20.1.5948944" . And llvm is pointing to libc++_shared.so which is part of ndk.
We want to know what is version number of llvm is getting used in libc++_shared.so.

### Affected versions

r23

### Host OS

Mac

### Host OS version

mac11

### Affected ABIs

armeabi-v7a

**Comment by jfgoog** [comment]
libc++_shared.so is built with the same compiler as supplied with the NDK.

`~/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -v` says:

`Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)`

**Comment by DanAlbert** [comment]
I'm not sure if the question is "what version of libc++ is in r20?" or "what version of LLVM was used to build libc++?", but both answers are in the changelog: https://github.com/android/ndk/wiki/Changelog-r20

> * Updated Clang to r346389c.
> * Updated libc++ to r350972.
