### ISSUE TITLE
How to set foo-RTTI enabled during the ndk-build command 

### ISSUE THREAD

**Issue by robi56** [android/ndk#1674]
### Description

I am working on a project where boost library is used and I have found the following error 

```
./boost/serialization/extended_type_info_typeid.hpp:91:23: error: use of typeid requires -frtti
        type_register(typeid(T));
```
from the command : `ndk-build NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=./Application.mk APP_BUILD_SCRIPT=./Android.mk
`

From [boost-llvm-clang](https://caesr.uwaterloo.ca/misc/boost-llvm-clang.html) reference, I found that 

By default, [LLVM](http://llvm.org/) and [clang](http://clang.llvm.org/) are compiled with the -fno-rtti flag. This means that RTTI support is disabled. However, when using libraries such as [Boost](http://boost.org/), it is necessary to recompile LLVM and clang with RTTI enabled. While t[here](http://llvm.org/docs/Packaging.html) is documentation on how to do it here, it happened to be more involved than just that.

We need to set the LLVM_REQUIRES_RTTI variable in order to get LLVM to compile with RTTI. Assuming $LLVM_ROOT is the directory location for the LLVM source, and $CLANG_ROOT points to the directory where clang is installed.

Since Android NDK uses prebuild version of LLVM and Clang , how I can resolve the problem.

**Comment by enh-google** [comment]
see the first match for a web search for "ndk-build rtti": https://developer.android.com/ndk/guides/cpp-support#rt
