### ISSUE TITLE
[FR] auto-enable ELF TLS in clang driver when minSdkVersion is sufficiently high

### ISSUE THREAD

**Issue by AndroidInternal** [android/ndk#1679]
### Description

Hi,

Disabled emulate tls With cflags to enable TLS:
```
-fno-emulated-tls
-Wl,-plugin-opt=-emulated-tls=0
```

Then ELF TLS works fine with the static library, and I can see .tbss section in the binary :
```
llvm-readelf libkmalloc_scudo.a -S | grep tbss

[275] .tbss._ZN5scudo18TSDRegistrySharedTINS_9AllocatorINS_13AndroidConfigEXadL_Z21scudo_malloc_postinitEEEELj32ELj8EE9ThreadTSDE NOBITS 0000000000000000 008f80 000008 00 WAGT  0   0  8
[281] .tbss._ZN5scudo18TSDRegistrySharedTINS_9AllocatorINS_19AndroidSvelteConfigEXadL_Z28scudo_svelte_malloc_postinitEEEELj2ELj1EE9ThreadTSDE NOBITS 0000000000000000 009280 000008 00 WAGT  0   0  8

```

But when adding LTO in flag:
```
-flto
```

Then the static library compiled is not an ELF format any more, instead it is LLVM IR code:
```
file flags_parser.cpp.o 
flags_parser.cpp.o: LLVM IR bitcode
```

Then .tbss section is not in the static library, and when a shared library compiled with this prebuilt static library,  it will use `emulate tls` rather than `elf tls`.

Thanks.

### Affected versions

r23

### Host OS

Mac

### Host OS version

macOS 12.2.1

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

30

**Comment by rprichard** [comment]
AFAIK we haven't added an ELF TLS -vs- emutls flag to the IR. i.e. This is WAI, at least for now.

> Disabled emulate tls With cflags to enable TLS:
>
> -fno-emulated-tls
> -Wl,-plugin-opt=-emulated-tls=0

If I understand correctly: `-Wl,-plugin-opt=-emulated-tls=0` is an ldflag, passed to the linker, which then configures an instance of Clang launched by the linker to compile IR. Archiving object files into a static library (whether IR or machine code) doesn't use the linker.

**Comment by AndroidInternal** [comment]
Thanks for the reply and pointing out the improper ld flag.

By removing the ldflag

```
-Wl,-plugin-opt=-emulated-tls=0
```

And just use cflags
```
-fno-emulated-tls
```

Then will have the same result: works find when LTO disabled, but lost .tbss section in the static library.

Now this is WAI(works as intended), 

Whether I can assume that it is not supported using ELF TLS in static library with LTO in Android? 

Or whether there is another way to use both ELF TLS and LTO at the same time in static library?

**Comment by rprichard** [comment]
> Or whether there is another way to use both ELF TLS and LTO at the same time in static library?

I think `-Wl,-plugin-opt=-emulated-tls=0` is the right flag, but you need to pass it to clang when you link something (e.g. executable or shared library) that uses the static library. It would go on a list of LDFLAGS, not CFLAGS.

**Comment by AndroidInternal** [comment]
Thanks for the reminding, I do have the `-Wl,-plugin-opt=-emulated-tls=0` in the LDFLAGS at the beginning in this case, but it do have the same result.

**Comment by AndroidInternal** [comment]
Sorry I need to reopen this issue..  :)

Because I find it do have the same result after adding the ldflags, there isn't `.tbss section` in the final shared library either. 

Like this:
```
./llvm-readelf libkmalloc.so  -S
There are 32 section headers, starting at offset 0x89808:
  [21] .bss              NOBITS          0000000000014500 011500 04c4b8 00  WA  0   0 64
```

I've already add `-Wl,-plugin-opt=-emulated-tls=0` in the LDFLAGS of the shared library

**Comment by AndroidInternal** [comment]
Update: By adding the ldflag **correctly** can do solve this problem.

The wired behavior not works fine described above is causing by a confusing *cmake* ldflags behavior.

This can add the `-Wl,-plugin-opt=-emulated-tls=0` in the final `build.ninja` rightly：
```
#CMakeLists.txt
SET (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,-plugin-opt=-emulated-tls=0")

#build.ninja
LINK_FLAGS = -Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-plugin-opt=-emulated-tls=0
```

This can't generate wright ldflags in the final `build.ninja`:
```
#CMakeLists.txt
set_target_properties(
        libkmalloc_scudo
        PROPERTIES LINK_FLAGS -Wl,-plugin-opt=-emulated-tls=0
)
```

But according [cmake document ](https://cmake.org/cmake/help/v2.8.8/cmake.html#command%3aset_target_properties) `set_target_properties` is supposed to works, but it isn't.

Whatever, by adding the ldflag **correctly** can do solve this problem, thanks again.

**Comment by DanAlbert** [comment]
> Whether I can assume that it is not supported using ELF TLS in static library with LTO in Android?

I probably should have said this is working as _expected_ rather than as intended. The follow up work we have planned that will make this work smoothly is to teach the clang driver to do this automatically when your minSdkVersion is high enough for ELF TLS to be available. There's no reason each developer should need to configure this on their own; clang has all the information it needs to do the right thing by default.

It doesn't appear we have a bug filed to track that (it doesn't show up when I search for "tls", anyway), so I'll reopen this to track since it contains some useful context.

**Comment by brad0** [comment]
I happened upon this issue searching via Google, but I think the diff I commited was a start in the right direction..

https://github.com/llvm/llvm-project/commit/b71f2fcd46790dd63dd2688c208139ea26f027d4

**Comment by DanAlbert** [comment]
That may actually be "done" aside from us needing to pull that update (that _might_ be in r26 but I'd have to dig to check)? Thanks again for that patch 👍 

@rprichard do you know of anything else we'd need to do?

**Comment by rprichard** [comment]
No, I think that LLVM change is all we would need.

**Comment by brad0** [comment]
So the Android NDK r26 beta includes an update to LLVM 17 that would include this?

**Comment by DanAlbert** [comment]
It seems so. Updated the changelog: https://android-review.googlesource.com/c/platform/ndk/+/2724316

For future reference, you can look at the `clang_source_info.md` file in the NDK to learn that kind of thing:

```
Base revision: [14f0776550b5a49e1c42f49a00213f7f3fa047bf](https://github.com/llvm/llvm-project/commits/14f0776550b5a49e1c42f49a00213f7f3fa047bf)
```

That's newer than that commit, so yes.
