### ISSUE TITLE
[BUG] ndk-r24 failed to build when with cmake-3.23.0-rc5

### ISSUE THREAD

**Issue by zchrissirhcz** [android/ndk#1688]
### Description

I would like to use ndk-r24 and cmake to compile a hello-world executable target.

With my own build scripts/steps, ndk-r24 fails, while ndk-r23b and ndk-r25-beta2 success.

Full reproduce example is: https://github.com/zchrissirhcz/min-repros/tree/master/test_cmake_ndk-r24 .

### Affected versions

r24

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

armeabi-v7a, arm64-v8a

### Build system

CMake

### minSdkVersion

I don't know this..

### Device API level

30

**Comment by rprichard** [comment]
I can't get this to reproduce. It builds fine for me:
```
rprichard@cashew:/x/test0/work/github/min-repros/test_cmake_ndk-r24/build$ rm -fr android-arm64 && ./android-arm64-build.sh 
+ CMAKE=/x/test0/soft/cmake-3.23.0-rc5/bin/cmake
+ ANDROID_NDK=/x/test0/soft/android-ndk-r24
+ TOOLCHAIN=/x/test0/soft/android-ndk-r24/build/cmake/android.toolchain.cmake
+ BUILD_DIR=android-arm64
+ mkdir -p android-arm64
+ cd android-arm64
+ /x/test0/soft/cmake-3.23.0-rc5/bin/cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/x/test0/soft/android-ndk-r24/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-31 -DCMAKE_BUILD_TYPE=Release ../..
-- Android: Targeting API '31' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected unified Clang toolchain
-- The C compiler identification is Clang 14.0.1
-- The CXX compiler identification is Clang 14.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /x/test0/soft/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /x/test0/soft/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /x/test0/work/github/min-repros/test_cmake_ndk-r24/build/android-arm64
+ /x/test0/soft/cmake-3.23.0-rc5/bin/cmake --build .
[2/2] Linking CXX executable testbed
+ cd ..
```

**Comment by zchrissirhcz** [comment]
> I can't get this to reproduce. It builds fine for me:
> 
> ```
> rprichard@cashew:/x/test0/work/github/min-repros/test_cmake_ndk-r24/build$ rm -fr android-arm64 && ./android-arm64-build.sh 
> + CMAKE=/x/test0/soft/cmake-3.23.0-rc5/bin/cmake
> + ANDROID_NDK=/x/test0/soft/android-ndk-r24
> + TOOLCHAIN=/x/test0/soft/android-ndk-r24/build/cmake/android.toolchain.cmake
> + BUILD_DIR=android-arm64
> + mkdir -p android-arm64
> + cd android-arm64
> + /x/test0/soft/cmake-3.23.0-rc5/bin/cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/x/test0/soft/android-ndk-r24/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-31 -DCMAKE_BUILD_TYPE=Release ../..
> -- Android: Targeting API '31' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
> -- Android: Selected unified Clang toolchain
> -- The C compiler identification is Clang 14.0.1
> -- The CXX compiler identification is Clang 14.0.1
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /x/test0/soft/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /x/test0/soft/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /x/test0/work/github/min-repros/test_cmake_ndk-r24/build/android-arm64
> + /x/test0/soft/cmake-3.23.0-rc5/bin/cmake --build .
> [2/2] Linking CXX executable testbed
> + cd ..
> ```

Thanks for verifying. I checked again, delete my android-ndk-r24, checked the sha1sum, unzip and compile again, now it success to build. Maybe I modified some of the android-ndk-r24 previously (which I can't remember ..)

**Comment by Ryggs** [comment]
Has this had any fix around it?

Did you get a fix for it?

**Comment by zchrissirhcz** [comment]
> Has this had any fix around it?
> 
> Did you get a fix for it?

This is a bug of the zipping/unzipping GUI software "Ark" on ubuntu 20.04. It failed to handle soft links. I use command line `tar` as solution.
