### ISSUE TITLE
[BUG] ld.lld: error: cannot open crtbegin_so.o: No such file or directory

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1690]
### Description

Hi Team,

Currently we are migrating from NDK R21 to NDK R23. 

In NDK R21, crtbegin_so.o and crtend.so.o are present in platforms\android-<API>\arch-<ABI>\usr\lib. So if we pass platforms\android-<API>\arch-<ABI> to --sysroot then linker is able to find those .o files while linking.

But in NDK R23 I see platforms folder is removed and all these .o's/.a's/.so's are moved to toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\<TRIPLE>\<API>. 

Since the path is changed, I passed toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\<TRIPLE>\<API> to --sysroot and built the project.  The linker is failing like below unable to find crtbegin_so.o and crtend_so.o

```
E:\NFUL\dev\platformsdk\android\plat\native>"D:\nugetcache\androidndk.23.0.4\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi23-clang++.cmd"  @e:\nful\build\droidarm\ship\platformsdk\android\plat\native\obj\droidarm\linker.rsp -o e:\nful\build\droidarm\ship\platformsdk\android\plat\native\obj\droidarm\tmp\libplat.so_unstripped
ld.lld: error: cannot open crtbegin_so.o: No such file or directory
ld.lld: error: cannot open crtend_so.o: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

Where linker.rsp is below

-Wl,--whole-archive

e:/nful/build/droidarm/ship/platformsdk/lib/libplatnlsnew.a
<<Few other project private .a files>>
-Wl,--no-whole-archive
--gcc-toolchain=D:/nugetcache/androidndk.23.0.4/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64
--target=armv7-none-linux-androideabi
-Wl,-z,relro
-Wl,-z,now
--sysroot=D:/nugetcache/androidndk.23.0.4/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/arm-linux-androideabi/23
-LD:/nugetcache/androidndk.23.0.4/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/arm-linux-androideabi/23
-llog
-lEGL
-lGLESv1_CM
-lOpenSLES
-lGLESv2
-nostdlib++
-Wformat
-Wformat-security
-Werror=format-security
-fstack-protector-strong
-fPIC
-Wl,--dynamic-linker,/system/bin/linker
-Wl,-soname,libplat.so
-Wl,--build-id=sha1
-shared
"-O2"
-fuse-ld=lld
-flto=thin
-Wl,--icf=safe
-Wl,--lto-O2
-Wl,--thinlto-cache-dir=E:/NFUL/Build/thinlto_cache/droidarm/ship
-Wl,--thinlto-cache-policy,cache_size_bytes=10g
-Wl,--fix-cortex-a8
-landroid
-Wl,-z,noexecstack
-Wl,-Bsymbolic
-Wl,--no-undefined
-Wl,--gc-sections
-Wl,--version-script=version.expmap
-Wl,-rpath-link=D:/nugetcache/androidndk.23.0.4/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/arm-linux-androideabi/23
-lc
-lm
-latomic
d:/nugetcache/androidndk.23.0.4/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so
-Wl,--start-group

-Wl,--end-group

```

Its working fine If I move all the .o's, .a's, .so's in toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\arm-linux-androideabi\23 to toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\arm-linux-androideabi\23\usr\lib.

I think it is expected because linker tries to find .o files/ .so files in **<given_sysroot_path>\usr\lib**. When we know that linker ALWAYS looks for files in **<given_sysroot_path>\usr\lib**, why aren't these .o's/.a's/.so's are placed in **toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\<TRIPLE>\<API>\usr\lib** instead of **toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\<TRIPLE>\<API>** to make things simpler ?? Otherwise we need to explicitly create usr\lib folder and move all of them which I think is not a nice solution

Or is there any solution that can work directly with **--sysroot=toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\<TRIPLE>\<API>**. Any flag or something?

Please suggest. Thanks.

### Affected versions

r23

### Host OS

Windows

### Host OS version

Windows 10 Enterprise

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### Other build system

Custom

### minSdkVersion

23

### Device API level

>23

**Comment by DanAlbert** [comment]
https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md

**Comment by DanAlbert** [comment]
`-B` is not required. If clang isn't finding CRT objects without `-B` you've made a mistake. See the doc above. Neither ndk-build nor CMake use `-B`. The usual problem is that you're passing unnecessary flags, and with incorrect values. Usually that's some old cruft trying to get pre-r19 NDKs to behave like regular compilers. Clang will compile and link successfully with nothing but `--target` (though it will not necessarily produce runnable binaries for all OS versions, the only complete answer is the doc above).
