### ISSUE TITLE
[BUG] java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "line" is null'

### ISSUE THREAD

**Issue by maitreyi2711** [android/ndk#1691]
### Description

I have an existing working APK project which I was building using the following set of tools:

NDK version r19b
Gradle version 6.5
CMake tools version 3.17.0
JAVA 8
Recently, there was a need to upgrade the CMake tools to 3.22.2. With this, I also upgraded the other tools as follows:

NDK version r23c
Gradle version 7.3
CMake tools version 3.22.2
JAVA 17
With the above combination of tools, I am seeing the below error:

_java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "line" is null'_

**Is there any other dependency I am missing here?**

I have an existing working APK project which I was building using the following set of tools:

NDK version r19b
Gradle version 6.5
CMake tools version 3.17.0
JAVA 8
Recently, there was a need to upgrade the CMake tools to 3.22.2. With this, I also upgraded the other tools as follows:

NDK version r23c
Gradle version 7.3
CMake tools version 3.22.2
JAVA 17
With the above combination of tools, I am seeing the below error:

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "line" is null'
Is there any other dependency I am missing here?

Build logs:

_>gradlew build
> Task :app:configureCMakeDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeDebug'.
> Cannot invoke "String.equals(Object)" because "line" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
11 actionable tasks: 11 executedo-date
C:\Qualcomm\Hexagon_SDK\4.5\lib-src\calculator_c++_apk\Calculator>gradlew build
> Task :app:configureCMakeDebug FAILED

_FAILURE: Build failed with an exception._

* What went wrong:
Execution failed for task ':app:configureCMakeDebug'.
> Cannot invoke "String.equals(Object)" because "line" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
11 actionable tasks: 11 executed_

### Affected versions

r23

### Host OS

Windows

### Host OS version

Windows 10

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

30.0.2

**Comment by DanAlbert** [comment]
There's no Java anywhere on the NDK so this is the wrong bug tracker. File a bug against Android Studio. And if possible, do those upgrades one at a time and figure out which one cashed the break. Those products are all owned by different people. Without a repro case or a more specific bug there's no way to triage this.
