### ISSUE TITLE
Apple M1 chip support[BUG]

### ISSUE THREAD

**Issue by jianrui** [android/ndk#1702]
### Description

Using Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 17, 2022
Runtime version: 11.0.11+0-b60-7772763 aarch64
Virtual Machine: OpenJDK 64-bit server virtual machine from JetBrains s.r.o.
macOS 12.3.1

<img width="950" alt="image" src="https://user-images.githubusercontent.com/3873291/164038537-41f56952-f106-4a68-8212-14a90657799a.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/3873291/164038843-1bac96c8-cb5b-4018-a0a8-6a7769e767c2.png">

### Affected versions

r24

### Host OS

Mac

### Host OS version

macos 12.3.1

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

25

### Device API level

29

**Comment by DanAlbert** [comment]
Wrong bug tracker. Studio bugs need to be filed against Android Studio. There's a link in the "new bug" page.
