### ISSUE TITLE
NDK 23.* can not build shaderc source code for target libshaderc_combined

### ISSUE THREAD

**Issue by ggfan** [android/ndk#1704]
### Description

this is seems to be related to the llvm-ar replacement for ${TOOLCHAIN_PREFIX}ar in NDK 23. in file shaderc/Android.mk  packed inside NDK.  The latest repo seems to [have the fix already](https://github.com/google/shaderc/blob/main/Android.mk).

### Affected versions

r23

### Host OS

Linux, Mac, Windows

### Host OS version

Windows 10 Enterprise

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

24

**Comment by DanAlbert** [comment]
Duplicate of #1634
