### ISSUE TITLE
[BUG] SendEvent from NdkMediaDrm does not send events with empty data

### ISSUE THREAD

**Issue by dr0ndv** [android/ndk#1709]
### Description

My problem is that AMediaDrmListener from NDK does not receive any events from the widevine driver on Pixel devices.

AMediaDrm allows to register a custom listener with [AMediaDrm_setOnEventListener](https://developer.android.com/ndk/reference/group/media#amediadrm_setoneventlistener) function to receive information about internal events. The list of supported event types can be found in [AMediaDrmEventType](https://developer.android.com/ndk/reference/group/media#amediadrmeventtype) enumeration. For example, *EVENT_KEY_REQUIRED* event is useful to support periodical license renewals.

Using the API is straitforward and in a simplified form, it might look like this:

    AMediaDrm* drm = AMediaDrm_createByUUID("...");

    ...

    void OnEventListener(AMediaDrm* drm, const AMediaDrmSessionId* sessionId, AMediaDrmEventType eventType, int extra, const uint8_t* data, size_t dataSize)
    {
        ...
    }

    ...
    
    media_status_t status = AMediaDrm_setOnEventListener(drm, OnEventListener);
    if (status != AMEDIA_OK) {
        std::cout << "Error while setting EventListener" << std::endl;
        return status;
    }

*AMediaDrm_setOnEventListener* returns *AMEDIA_OK*, which means that the callback was succesfully registered. Unfortunately, during the playback of protected content, there are no evidences of *OnEventListener* callback execution. Log file, that was collected using `adb logcat` command, contains `NdkMediaDrm: invalid event data size=0` errors. Searching for the error message in the AOSP source code pointed to a *SendEvent* function in [NdkMediaDrm.cpp](https://android.googlesource.com/platform/frameworks/av/+/refs/heads/master/media/ndk/NdkMediaDrm.cpp#187). This function only sends events if the data vector (3rd function argument) is not empty, otherwise nothing is sent and error message is printed. Such logic exists in *SendEvent* function since the commit from more than 3 years ago <https://android.googlesource.com/platform/frameworks/av/+/ad02cc6c4091a44fb60c475731c8f4cac9a55ab0%5E%21/#F0>. Before that, it was possible to send events with empty data.

Seems that drivers/plugins that are responsible for DRMs (like widevine) send events with empty data vectors. And new "logic" in SendEvent breaks existing implementations of such drivers.

However, the problem does not affect MediaDrm Java API. In such case, no NDK code is involved. My guess, that code that is responsible for sending the events is located here: <https://android.googlesource.com/platform/frameworks/base.git/+/refs/heads/master/media/jni/android_media_MediaDrm.cpp#523>. There are no additional checks for data vector emptiness. It was tested with the same device and ExoPlayer application.

AMediaDrm events seems to be important to support correct playback of protected content on Android devices. It should work in the same way for C++ and Java applications.

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

30

**Comment by DanAlbert** [comment]
The NDK only ships stubs. Implementation issues need to be filed against the framework. Follow the link for "Android OS issues" in the NDK bug template picker.
