### ISSUE TITLE
[Bug]: [WARNING]: sysroot doesn't exist: /home/appdeveloper/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-aarch64/sysroot

### ISSUE THREAD

**Issue by Deadlooks** [android/ndk#1711]
### Description

**While Converting Kivy file to apk :**  `[WARNING]: sysroot doesn't exist: /home/appdeveloper/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-aarch64/sysroot`
[Error.txt](https://github.com/android/ndk/files/8627451/Error.txt)

**and [ERROR]:**   Build failed: python-for-android cannot continue due to the missing executables above
`#Command failed: /home/appdeveloper/kivymdapp/venv/bin/python3 -m pythonforandroid.toolchain create --dist_name=adilkivyicons --bootstrap=sdl2 --requirements=python3,kivy==2.1.0,kivymd,pillow --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/appdeveloper/kivymdapp/demos/icons/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug`

### Affected versions

Canary

### Canary version

android-ndk-r19c

### Host OS

Linux

### Host OS version

PRETTY_NAME="Kali GNU/Linux Rolling" NAME="Kali GNU/Linux" ID=kali VERSION="2022.2" VERSION_ID="2022.2" VERSION_CODENAME="kali-rolling" ID_LIKE=debian ANSI_COLOR="1;31"

### Affected ABIs

armeabi-v7a

**Comment by DanAlbert** [comment]
> linux-aarch64

https://github.com/android/ndk/discussions/1692
