### ISSUE TITLE
[Bug] Inconsistent ASan report for GoogleTest across build types and NDK versions

### ISSUE THREAD

**Issue by zchrissirhcz** [android/ndk#1712]
### Description

The very simple gtest usage code in the following:
```c++
#include "gtest/gtest.h"

void foo(const std::vector<std::vector<int>>& mat)
{
    std::vector<int> ofs;
    int i, j;
    for (i = 0; i < mat.size(); i++)
        for (j = 0; j < mat[i].size(); j++)
            ofs.push_back(i + j);
}

TEST(Imgproc_Sobel, t1){}
TEST(Imgproc_Sobel, t2){}
TEST(Imgproc_Sobel, t3){}
TEST(Imgproc_Sobel, t4){}
TEST(Imgproc_Sobel, t5){}
```

Cause inconsistent ASan report with different build types and NDK version combinations:

![图片](https://user-images.githubusercontent.com/3831847/167083916-8a58061b-7c42-4d03-a0ea-74a49ae8a072.png)

The minimal, complete reproduce files are stores in https://github.com/zchrissirhcz/min-repros/tree/master/test_gtest_ndk_asan .

### Affected versions

r23, r24, r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

Not sure. See my reproduce build script.

**Comment by zchrissirhcz** [comment]
This bug was also reported in GoogleTest in several days ago: https://github.com/google/googletest/issues/3808

**Comment by DanAlbert** [comment]
Your repro project shows that the sanitizer runtime being used is the one in `/system/lib64`. How did that get there?

**Comment by enh-google** [comment]
> Your repro project shows that the sanitizer runtime being used is the one in `/system/lib64`. How did that get there?

(if the answer wasn't "i was naughty and did that myself in an attempt to _fix_ this", that might be a missing CTS test we should add...)

**Comment by zchrissirhcz** [comment]
>Your repro project shows that the sanitizer runtime being used is the one in `/system/lib64`. How did that get there?

1. I build and install googletest with **NDK-r21e** in Release mode (At the very beginning when give the repro, I didn't notice this ndk version, but later find it is required, higher version can't reproduce).
2. Then in my repro project, with the mentioned C++ snippet, and links to the googletest library just built in step1,  but with **NDK-r25-beta3**, specify **Debug mode**(CMAKE_BUILD_TYPE=Debug).
3. Then run in on Android XiaoMi 11 Phone. 

I've do a clean build of both googletest and my repro with the two mentioned NDK version and correspond CMAKE_BUILD_TYPE. It still report `/system/lib64` folder's sanitizer runtime library.

>(if the answer wasn't "i was naughty and did that myself in an attempt to fix this", that might be a missing CTS test we should add...)

I didn't change directory into `/system/lib64`, nor do I know how to "attemp to fix this". But to verify if I sometime made a mistake, I use **another android phone (Meizu 17 Pro)**, run the same executable, and still see `/system/lib64`'s sanitizer runtime being reported:

![图片](https://user-images.githubusercontent.com/3831847/167522429-747c4922-2ea3-4613-b0ec-f6085c555b6b.png)

**Comment by enh-google** [comment]
> nor do I know how to "attemp to fix this"

yeah, i should have been clearer and said "unless you've rooted the device and added these files to /system/lib64 yourself". because, no, it _shouldn't_ be possible for you get into this situation without a rooted device.

i thought we'd had this problem before and already had a CTS test for this, but i can't see anything. @eugenis --- do you remember anything like that? and we should actually fail CTS for devices that ship the sanitizer runtimes in /system/lib, right?

**Comment by DanAlbert** [comment]
This appears to be a device bug (that library should not be in `/system/lib64`) which is out of our hands. ASan has also lost support since it was replaced by HWASan (which is explained [here](https://developer.android.com/ndk/guides/memory-debug)), so even if it is an ASan bug I'm doubtful we'd be able to get anyone to fix it.

**Comment by enh-google** [comment]
should we have a CTS test that devices aren't shipping sanitizer runtimes in /system/lib*?

**Comment by appujee** [comment]
> should we have a CTS test that devices aren't shipping sanitizer runtimes in /system/lib*?

makes sense to have a cts for this.

**Comment by DanAlbert** [comment]
I agree but CTS isn't part of the NDK :) I'm trying to figure out where to file that for the OS.

**Comment by DanAlbert** [comment]
Filed http://b/294911032 (non-googlers: nothing interesting to see, it's just what was said above)
