### ISSUE TITLE
release branches on ci.android.com not visible to non-googlers

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1715]
The new [link](https://ci.android.com/builds/branches/aosp-ndk-release-r23/grid?) shows and empty list. I cannot see asop-ndk-release branch. 

![Screenshot 2022-05-11 at 21 22 45](https://user-images.githubusercontent.com/25881325/167929518-7aeb07ff-3988-4ce9-9851-55b14011ffe3.png)

_Originally posted by @orifmilod in https://github.com/android/ndk/issues/1671#issuecomment-1124203141_

**Comment by orifmilod** [comment]
I can see `aosp-master-ndk` branch although not the build #8568313 - maybe any other build number from there would solve our problem?

**Comment by DanAlbert** [comment]
I'm not sure when this broke, but I'll start chasing it with the build team. We'd asked for all our release builds to always be publicly visible and I believe that was working until recently.

**Comment by orifmilod** [comment]
Got it! Thanks for the swift responses.

**Comment by DanAlbert** [comment]
http://b/140114921 is the internal bug for this (I know you can't see it, that's just so I can find it again later). It seems like there isn't any actual wildcard pattern for our release branches which is what I'd wanted, they'd just added all the branches that existed at the time we made the request. We mostly only end up sharing links to the master branch, so that could be an explanation of why we haven't noticed the problem sooner...

**Comment by orifmilod** [comment]
@DanAlbert Any updates on this one?

**Comment by DanAlbert** [comment]
No. The person I need to talk to was OOO.

**Comment by DanAlbert** [comment]
r25 is visible now. We will probably forget to do this for future release branches, and unfortunately the tool does not support wild cards, so there's no way for me to fix this permanently. If we forget again, file a bug and I'll go bother people.
