### ISSUE TITLE
"C:\***\Downloads\ndk-r16b\android-ndk-r16b\ndk-build" exited with code 9009

### ISSUE THREAD

**Issue by wasimalam072** [android/ndk#1720]
### Description

I have an old project Xamarin.Android.
I want to deploy on the Visual Studio 2019 and download the NDK file "ndk-r16b" and try it. but its comes same error all time.

The Error is: **"C:\***\Downloads\ndk-r16b\android-ndk-r16b\ndk-build" exited with code 9009"**

Please suggest to me how to resolve this issue.

### Affected versions

r23

### Host OS

Windows

### Host OS version

Window 11 Home Single Language / Window 10 Home Single Language

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

API Level 21

### Device API level

API Level 27

**Comment by enh-google** [comment]
a quick Google search says "error code 9009" on Windows means "file not found", suggesting you haven't installed successfully (or not in the place you think you did).

but note that NDK r16 hasn't been supported for _years_ now. r23 is the oldest still-supported version.
