### ISSUE TITLE
[FR] Outdated Vulkan headers

### ISSUE THREAD

**Issue by Zingam** [android/ndk#1721]
### Description

The current headers in NDK are version: 1.2.158.
LunarG current SDK provides 1.3.211.
https://vulkan.lunarg.com/
Khronos' specs are at: 1.3.217
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/index.html

What is the deal with Vulkan on Android? Doesn't it support anything newer than 1.2? 1.2.158 is from over a year ago and not even the latest in the 1.2 series.

**Comment by DanAlbert** [comment]
Which version of the NDK are you looking at?

@dneto0 in case android needs an update. All we do is ship what the platform provides.

**Comment by jfgoog** [comment]
From parsing sources/third_party/vulkan/src/include/vulkan/vulkan_core.h in NDK 24.0.8215888, it is version 1.2.158.

The version in NDK 25.0.8528842 is the same.

**Comment by DanAlbert** [comment]
That's the newest we have available then. Up to the platform to update their headers. Will leave this open to track, but there's no work for us to do other than pulling the update when it's available (which happens as part of our normal process, since it's just another part of the sysroot).

**Comment by truboxl** [comment]
To make things even confusing, right now in NDK r25, there lives 2 different versions of vulkan headers (1.2.158, 1.3.203)
```
$ grep VK_HEADER_VERSION -nHR android-ndk-r25 | sort
...
android-ndk-r25/sources/third_party/vulkan/src/include/vulkan/vulkan_core.h:46:#define VK_HEADER_VERSION 158
android-ndk-r25/sources/third_party/vulkan/src/include/vulkan/vulkan_core.h:49:#define VK_HEADER_VERSION_COMPLETE VK_MAKE_VERSION(1, 2, VK_HEADER_VERSION)
...
android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/vulkan/vulkan_core.h:75:#define VK_HEADER_VERSION 203
android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/vulkan/vulkan_core.h:78:#define VK_HEADER_VERSION_COMPLETE VK_MAKE_API_VERSION(0, 1, 3, VK_HEADER_VERSION)
...
```

**Comment by Zingam** [comment]
Very nice?!

Which ones are valid?

What is the difference between toolchains vs sources, which ones to use and is that documented?

**Comment by Zingam** [comment]
Why aren't vendor updating their drivers with newer support, e.g. a device which got Android 11 a few months ago uses a GPU which has 1.3 drivers at least for Linux, was released with 1.1 for Android.
What is the Vulkan on Android 12 (1.2 I guess), 13?

**Comment by DanAlbert** [comment]
You're preaching to the choir. This isn't something I have any power over. The NDK is just the messenger.

Use the header that's automatically on your include path: the one in the sysroot. That's the one that's provided by the OS. The one in `sources/third_party` is for the shader compiler. Both use cases are pre-configured to use the right headers. Exact header locations are not things app developers should need to think about. If your build system is making you think about this, file a bug against that build system.

**Comment by Zingam** [comment]
I'm just trying to understand what's the situation with Vulkan on Android and what are the plans/designs besides some anecdotal writings I've seen on forums. At least I never was able to find any hard evidence/documentation.

It seems that my complaint was incorrect and I'm doing something wrong. So I'm closing this for now. The available headers aren't that old. Thank you for the explanation.

**Comment by DanAlbert** [comment]
I was looking at the vulkan headers for an unrelated reason just now and see where the confusion is coming from. As you found, yes, the _sysroot_ has a recent vulkan.h (about as new as possible; it was brand new when the OS was updated in January, and around then is when dependencies start being frozen), but the one in `$NDK/sources/third_party/vulkan` is old. Why? Because that's for the validation layers, [which are distributed separately as of r23](https://github.com/android/ndk/wiki/Changelog-r23#changes), specifically because the NDK can never be as up to date as upstream, so you're better off getting them from upstream. See https://github.com/android/ndk/issues/1374.

If you're using ndk-build you'll see this warning:

> The Vulkan Validation Layers are now distrubted on GitHub. See https://github.com/KhronosGroup/Vulkan-ValidationLayers for more information.

We can't inject warnings for CMake, unfortunately.

**Comment by enh-google** [comment]
> The Vulkan Validation Layers are now distrubted on GitHub. See https://github.com/KhronosGroup/Vulkan-ValidationLayers for more information.

including the typo for "distributed"? :-)

**Comment by DanAlbert** [comment]
/facepalm yes. https://android-review.googlesource.com/c/platform/ndk/+/2216930
