### ISSUE TITLE
[BUG] --dynamic-linker=VALUE is not ignored when creating a statically linked executable

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#1722]
### Description

step1. create a C source file `test.c`:
```C
#include <stdio.h>

int main() {
    printf("%s\n", "Hello NDK");
    return 0;
}
```
step2. build a statically linked executable:
```bash
~/Downloads/android-ndk-r25-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -static -Wl,--dynamic-linker=/system/bin/linker64 test.c
```
step3. show the Program Headers:
![Screenshot from 2022-06-13 18-18-23](https://user-images.githubusercontent.com/3040852/173333152-11a85bc2-b8ed-409f-8189-189200e9e927.png)

**I think the `-Wl,--dynamic-linker=/system/bin/linker64` shall be ignored when `-static` is given**

**I tried my host's clang, it compiled as my expected.**

**Although ELF specification not say `INTERP` segment shouldn't be exist in statically linked executable, but It seems that if it exist, it will report follwoing error**

![Screenshot_2022-06-13-18-34-14-373_com termux](https://user-images.githubusercontent.com/3040852/173336031-8198c3d4-e1b8-485d-84e6-4d5374a12059.jpg)

### Affected versions

r23, r24, r25

### Host OS

Linux

### Host OS version

Ubuntu 22.04

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### Other build system

none

### minSdkVersion

21

**Comment by jfgoog** [comment]
This behavior does not happen with NDK 20.1.5948944 or 21.4.7075529, but does with newer versions.

**Comment by rprichard** [comment]
> I think the -Wl,--dynamic-linker=/system/bin/linker64 shall be ignored when -static is given

ld.bfd and ld.gold appear to ignore it for `-static`. LLD respects the flag instead. I don't know whether LLD's behavior is intentional or not. You could omit the flag, or if using ld.bfd/LLD (but not gold), append `-Wl,--no-dynamic-linker` to override `-Wl,--dynamic-linker=/system/bin/linker64`.

Aside: for `-shared -Wl,--dynamic-linker=/system/bin/linker64`, ld.bfd and LLD omit PT_INTERP, but ld.gold includes it. LLD used to include PT_INTERP, but that changed between NDK r21 and r22. https://github.com/llvm/llvm-project/commit/2d7a8cf90478cd845ffb39763b0e95b7715322d2

**Comment by leleliu008** [comment]
@rprichard Yes, exactly. Thanks for your comments.

**Comment by jfgoog** [comment]
If this is causing a problem in the behavior of programs complied with the NDK, please let us know and we will address it.

Otherwise, you are welcome to file upstream with LLVM.

**Comment by leleliu008** [comment]
@rprichard I find that if `-Wl,--hash-style=gnu` is given, `-Wl,--no-dynamic-linker` is ignored. I find most projects use this argument .

**Comment by leleliu008** [comment]
It seems that LLD's behavior is by design, I don't known why that design.

I'm writing a package manager named [ndk-pkg](https://github.com/leleliu008/ndk-pkg), I counldn't port projects one by one, If I want to controll these compiler arguments, the best way that I can thought is writing a compiler intercepter, is there another easy way can do this?

**Comment by DanAlbert** [comment]
Send a patch to clang?

> I find most projects use [`-Wl,--no-dynamic-linker`] .

Why? And why does it matter for Android? Apps load shared libraries, and afaik this argument doesn't affect shared libraries, so I don't see why this would matter to anything being ported for android apps.
