### ISSUE TITLE
[Bug]: clang silently ignores garbage target versions

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1728]
### Description

Invalid android versions are silently ignored by clang.

```bash
$ ~/Library/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -target aarch64-linux-android31 -dM -E - < /dev/null | grep __ANDROID_MIN_SDK_VERSION__
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
#define __ANDROID_MIN_SDK_VERSION__ 31
$ ~/Library/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -target aarch64-linux-androidS -dM -E - < /dev/null | grep __ANDROID_MIN_SDK_VERSION__
# Not set.
```

In the second case, `android/api-level.h` (which will be included transitively by any file that includes any libc header) will set `__ANDROID_API__` to `__ANDROID_API_FUTURE__` (AKA 10000), but won't set `__ANDROID_MIN_SDK_VERSION__` at all.

### Affected versions

r24, r25, Canary

### Host OS

Linux, Mac, Windows

### Host OS version

all

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by appujee** [comment]
good task for intern so i'm claiming it.

**Comment by enh-google** [comment]
see also internal issue http://b/315788463 where this is still silently breaking things internally 1.5 years later...

**Comment by appujee** [comment]
Even options like `./bin/clang a.cpp -c -target i686-linux-andfasdf` compile silently.

**Comment by ZijunZhaoCCK** [comment]
> Even options like `./bin/clang a.cpp -c -target i686-linux-andfasdf` compile silently.

Now I just detect the version after `android`.  How about making it a followup?

**Comment by appujee** [comment]
yeah sure.

**Comment by pirama-arumuga-nainar** [comment]
@ZijunZhaoCCK fixed the "invalid version" parts in https://github.com/llvm/llvm-project/pull/75373.  We will pull this into the next release.  There is follow-up to detect invalid "environments" (`i686-linux-andfasdf`).

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar since it was merged last week, you mean the next-next release, right? r28? Or is that going to be cherry-picked into the r27 toolchain?

**Comment by pirama-arumuga-nainar** [comment]
We can cherry-pick to the r27 toolchain.
