### ISSUE TITLE
[DOC] NDK compatibility table

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1760]
### URL

new page, probably

### Problem

Forking from the bazel thread. I don't think we have such a thing, but probably should.

>> Unless you're talking about _extremelely_ old devices (close to a decade), r25 works just fine. r25 was actively tested against KitKat.
>
> @oakad do you have a particularly old device in mind? Older than KitKat? Perhaps we need a clearer FAQ or table explaining how NDK releases, API levels, OSes, and devices are all related and the various levels of compatibility? Maybe with some example devices?

_Originally posted by @jiawen in https://github.com/bazelbuild/bazel/issues/12889#issuecomment-1233624605_

**Comment by oakad** [comment]
Actually, it seems we will stop supporting all pre-Lollipop devices this year.

So, older than KitKat is no longer a problem.

(Kind of funny how it is a struggle to stop supporting Android 4.x in 2022 :-)

**Comment by EwoutH** [comment]
Great idea, I will love to see a NDK compatibility table somewhere in the documentation!

**Comment by DanAlbert** [comment]
All this info is already available, FWIW. It just isn't consolidated across NDKs into one location. The changelogs will tell you when an API level loses support, and the meta/platforms.json file contains that information for each NDK.

**Comment by EwoutH** [comment]
> It just isn't consolidated across NDKs into one location.

This would add value and is the point of this issue, I think.

**Comment by DanAlbert** [comment]
Agreed, just checking.

**Comment by DanAlbert** [comment]
https://github.com/android/ndk/wiki/Compatibility
