### ISSUE TITLE
[BUG] ndk-gdb fails with -f

### ISSUE THREAD

**Issue by jfgoog** [android/ndk#1764]
### Description

When running `ndk-gdb -f`:
```
Traceback (most recent call last):
  File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 951, in <module>
    main()
  File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 882, in main
    device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)
TypeError: can only concatenate list (not "map") to list
```

### Affected versions

r25

### Host OS

Windows

### Host OS version

n/a

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### minSdkVersion

n/a

**Comment by MarijnS95** [comment]
This is another Python 2 -> Python 3 conversion problem just like #1763:

The current code is as follows:

```python
        kill_pids = map(str, kill_pids)
        if kill_pids:
            log("Killing processes: {}".format(", ".join(kill_pids)))
            device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)
```

In Python 2, `map()` returns a list which you can freely concatenate to another list. In Python 3 `map()` is lazy (a generator) and can't be concatenated. Besides, `map()` is discouraged in favour of generator expressions, or in this specific case a list comprehension:

```python
kill_pids = [str(pid) for pid in kill_pids]
```

**Comment by DanAlbert** [comment]
Whoever fixes this should extend our pylint check over this script. Pylint would have caught this.

**Comment by Hendooo1** [comment]
> ### Description
> When running `ndk-gdb -f`:
> 
> ```
> Traceback (most recent call last):
>   File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 951, in <module>
>     main()
>   File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 882, in main
>     device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)
> TypeError: can only concatenate list (not "map") to list
> ```
> 
> ### Affected versions
> r25
> 
> ### Canary version
> _No response_
> 
> ### Host OS
> Windows
> 
> ### Host OS version
> n/a
> 
> ### Affected ABIs
> armeabi-v7a, arm64-v8a, x86, x86_64
> 
> ### Build system
> Other (specify below)
> 
> ### Other build system
> _No response_
> 
> ### minSdkVersion
> n/a
> 
> ### Device API level
> _No response_
Traceback (most recent call last):
  File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 951, in <module>
    main()
  File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 882, in main
    device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)
TypeError: can only concatenate list (not "map") to list

**Comment by DanAlbert** [comment]
@appujee has uploaded a fix here: https://android-review.git.corp.google.com/c/platform/ndk/+/2579812 (thanks!)

Will leave the bug open for myself to extend pylint coverage and to update the changelog.

**Comment by MarijnS95** [comment]
https://r.android.com/c/platform/ndk/+/2579812 link for non-Googlers.

There's actually a nicer way to write this now, using the splat operator to expand one array within another array:

```python
        kill_pids = [str(pid) for pid in kill_pids]
        if kill_pids:
            log("Killing processes: {}".format(", ".join(kill_pids)))
            device.shell_nocheck(["run-as", pkg_name, "kill", "-9", *kill_pids])
```

(Notice the splat operator on the last line)

---

Regarding pylint, I've seen some of the many Python linters recommend using the splat operator over `+`.

**Comment by DanAlbert** [comment]
> https://r.android.com/c/platform/ndk/+/2579812 link for non-Googlers.

Ugh. Sorry. A while ago someone decided that my URL bar should be rewritten to something useless. I don't always remember to rewrite it by hand before pasting.

**Comment by DanAlbert** [comment]
The fix for this appears to have been in r26 beta 1 and I just forgot to add it to the changelog. In any case it's certainly in RC 1 (and I've updated the changelog).
