### ISSUE TITLE
[BUG] ld: error: unknown argument '-fPIE'

### ISSUE THREAD

**Issue by telleo** [android/ndk#1766]
### Description

using CMake ExternalProject_add execute  third library(FFmpeg) ./configure command  linking x264.a library .In it's config.log record  this error.
[NDK_PATH]/toolchains/llvm/prebuilt/darwin-x86_64/bin/ld -L/[X264_LIBRARY_PATH]/arm64-v8a/lib -fPIE -pie -o /var/folders/vw/cgjh95wx1gj4ymxh76bgkq1r0000gn/T//ffconf.Muk0GEr2/test /var/folders/vw/cgjh95wx1gj4ymxh76bgkq1r0000gn/T//ffconf.Muk0GEr2/test.o -lx264
ld: error: unknown argument '-fPIE'

### Affected versions

r25

### Canary version

25.1.8937393

### Host OS

Mac

### Host OS version

12.1

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

21

**Comment by DanAlbert** [comment]
Nothing we can do here without a repro case. Our tests show this isn't a problem, so it's configuration specific.
