### ISSUE TITLE
[FR] ship vulkan-hpp?

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#1767]
### Description

Actually a bug for the platform, but filing here for tracking while I track down an answer to why we don't do this.

We have this header in the platform already: https://cs.android.com/android/platform/superproject/+/master:external/vulkan-headers/include/vulkan/vulkan.hpp. It's version locked to vulkan.h (I can't use the current upstream release with the NDK because they are not the same version). They're C++ headers (duh), but since they're header only they should be okay to ship in the sysroot.

**Comment by Zingam** [comment]
This library has a C++ module now.
The part about modules disappeared from the roadmap.

**Comment by trevordblack** [comment]
After internal discussion we're not in a position to support the .hpp files, and so aren't going to be explicitly adding them at the moment.

There was some additional discussion around this captured in #1974
