### ISSUE TITLE
[Bug]: Crash when unwinding exception on armeabi-v7a

### ISSUE THREAD

**Issue by hlewin** [android/ndk#1769]
### Description

When using ndk r25b the following test case results in a crash on android armeabi-v7a:

```
#include <stdexcept>
#include <string>
#include <iostream>

void f() {
    std::string s = "test";
    std::cout<<s<<std::endl;
    throw std::runtime_error("Test");
}


int main() {
    try {
        f();
    } catch(const std::exception&) {}
}
```

`armv7a-linux-androideabi23-clang++ tst.cpp`

When running the same binary against the libc++_shared.so from the previous ndk-version (r25)  everything works fine.

The following reconstruction comes from another program where this error was first discovered:

```
#0  0xf70daa56 in __gxx_personality_v0 (state=<optimized out>, unwind_exception=0xf6a29028, context=0xfffeec58) at /buildbot/src/android/ndk-r24-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_personality.cpp:1120
#1  0xf70de730 in _Unwind_RaiseException () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#2  0xf70da2bc in __cxa_throw (thrown_object=0xf6a29080, tinfo=<optimized out>, dest=0xf6f11805 <wdy::ImageDecoder::DecodeException::~DecodeException()>) at /buildbot/src/android/ndk-r24-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_exception.cpp:279
#3  0xf6f1643e in (anonymous namespace)::throwJpegError (jpeg=<optimized out>) at conan-pkg/wdyImageDecoder/conan-pkg/wdyImageDecoder/src/ImageCodecJpeg.cpp:76
#4  0xf6e15b3c in first_marker (cinfo=0xfffef3e0) at conan-pkg/libjpeg-turbo/jdmarker.c:949
#5  read_markers (cinfo=0xfffef3e0) at conan-pkg/libjpeg-turbo/jdmarker.c:974
#6  0xf6e140d8 in consume_markers (cinfo=0xfffef3e0) at conan-pkg/libjpeg-turbo/jdinput.c:323
#7  0xf6e09a34 in jpeg_consume_input (cinfo=0xfffef3e0) at conan-pkg/libjpeg-turbo/jdapimin.c:314
#8  0xf6e09954 in jpeg_read_header (cinfo=0xfffef3e0, require_image=1) at conan-pkg/libjpeg-turbo/jdapimin.c:262
#9  0xf6f139a2 in wdy::ImageDecoder::detail::ImageCodecJpeg::isImage (this=<optimized out>, input=...) at conan-pkg/wdyImageDecoder/conan-pkg/wdyImageDecoder/src/ImageCodecJpeg.cpp:316
#10 0xf6f2278c in wdy::ImageDecoder::detail::WDYImageDecoder::decodeImage (this=<optimized out>, input=..., options=...) at conan-pkg/wdyImageDecoder/conan-pkg/wdyImageDecoder/src/wdyImageDecoder.cpp:43
#11 0xaaab0488 in run () at conan-pkg/wdyImageDecoder/src/image-recode.cpp:158
#12 0xaaab0a2c in main (argc=5, argv=0xfffef7b4) at conan-pkg/wdyImageDecoder/src/image-recode.cpp:195
#13 0xf737a268 in __libc_init () from target:/apex/com.android.runtime/lib/bionic/libc.so
#14 0xaaaafeb0 in _start_main ()
```

In `__gxx_personality_v0` there is a call to
```
<__cxxabiv1::scan_eh_tab(__cxxabiv1::(anonymous namespace)::scan_results&, _Unwind_Action, bool, _Unwind_Control_Block*, _Unwind_Context*)>
```
The debugger disconnects when stepping then... However, after a reconnect I get a trace like

```
#0  0xf70b4cca in abort () from target:/apex/com.android.runtime/lib/bionic/libc.so
#1  0xf72e28c4 in unwind_phase2(unw_context_t*, unw_cursor_t*, _Unwind_Control_Block*, bool) () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#2  0xf72e2910 in _Unwind_Resume () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#3  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#4  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#5  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#6  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#7  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#8  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
#9  0xf72de1d8 in __cxa_end_cleanup () from target:/data/local/tmp/image_decoder/lib/libc++_shared.so
(More stack frames follow...)
```
With infinitely more frames in `__cxa_end_cleanup`

### Affected versions

r25

### Host OS

Linux

### Host OS version

Arch linux

### Affected ABIs

armeabi-v7a

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/2237201 shows that this isn't a problem in either of our build systems in the master branch. I still need to check the trivial case of using the compiler without a build system in case CMake and ndk-build are doing something to protect against the crash, and also verify r25b.

**Comment by DanAlbert** [comment]
Tested using r25b, and also by compiling directly with clang rather than going through the build system. All is working fine, so there's a configuration detail absent from the bug report. I ran this on a bramble (4a 5G?) running API 32.

**Comment by hlewin** [comment]
I am sorry - it seems I have wasted your time: The libc++_shared.so that was deployed to the system seems to have been corrupted in some way: It has a file-size of 4177484 which is slightly different to the one originally found in the ndk.
I am still puzzled of how this could have happened - it even floats around in our package-management in this form...
WIth everything re-deployed freshly it indeed seems to work.
I will check the processes involved and let you know if this happened due to stripping, gradle packaging or whatever.

Sorry again - I should have thoroughly checked that in first place

**Comment by DanAlbert** [comment]
> I am sorry - it seems I have wasted your time

No worries, we apparently didn't have a regression test for this case (we had many indirect tests via libc++'s tests, but nothing specifically for this), and now we do, so something improved either way :)

**Comment by hlewin** [comment]
Fun fact: The libc++_shared.so was the one from ndk24. This of course does not work.
Anyhow - it ended being packaged up and uploaded as libcxx-r25b.aar
