### ISSUE TITLE
[FR] zstd-compressed debug info support

### ISSUE THREAD

**Issue by enh-google** [android/ndk#1770]
### Description

zstd compression is something we should look at as llvm support for it improves (and in particular we should make sure that the unwinder can handle it), but i wondered whether @Over17 would be interested in using it. knowing that might help us prioritize...

**Comment by enh-google** [comment]
(https://stackoverflow.com/questions/63544670/unity-android-build-symbols-zip-file-too-big made me wonder, since it seems like Unity hits the Play Store's 300MiB limit --- even  if only (?) because of a bug rather than because they're actually close to it.)

**Comment by DanAlbert** [comment]
Are there docs for what we need to do for this?

**Comment by enh-google** [comment]
> Are there docs for what we need to do for this?

i actually don't think the NDK needs to do much/anything at all? i think this is just a case of getting a new enough llvm in the NDK and fixing debuggerd. but i don't have any other way to talk to @Over17 :-)

**Comment by Over17** [comment]
The stackoverflow thread is clearly a bug/obsolete behavior that we need to fix.
I'll read up on the matter and start conversations on zstd'ed symbols internally. will let you know!
Oh BTW, we are definitely on some email threads so feel free to ping me on email if you feel like doing it ;) It's my first name _at_ the company domain

**Comment by enh-google** [comment]
> The stackoverflow thread is clearly a bug/obsolete behavior that we need to fix.

oh, i actually assumed that was already fixed in a newer release and they just needed to update. if not, i'm glad i included the link :-)

> I'll read up on the matter and start conversations on zstd'ed symbols internally. will let you know!

thanks!

> BTW, we are definitely on some email threads so feel free to ping me on email if you feel like doing it ;) It's my first name at the company domain

i thought so too, and i swear i tried gmail autocomplete yesterday and found nothing ... but you're right, and i can find it today. (maybe i was too impatient with the autocomplete; it wouldn't be the first time i timed out before it finished!)

**Comment by akaStiX** [comment]
Symbols for Unreal Engine can go above 4GB.
Having zstd compressed debug symbols would be extremely helpful, especially considering that Unreal Build Tool copies unstripped DSO 4 or 5 times on each build, wearing down your SSD.

**Comment by DanAlbert** [comment]
Based on the conversation above... is this done? If not, what LLVM revision are we waiting for? Is there any build support we need to create?

**Comment by enh-google** [comment]
(@DanAlbert : http://b/248113754 is the internal bug, but there's not much there. i've added you to a thread [called "lzma", funnily enough!] that has the most recent discussions of zstd support.)

**Comment by akaStiX** [comment]
Please also add Emre K. into the loop as he's working on AGDE and we use it exclusively for Android debugging.
Without the debugger support it's pointless

**Comment by enh-google** [comment]
> Please also add Emre K. into the loop as he's working on AGDE and we use it exclusively for Android debugging. Without the debugger support it's pointless

i _thought_ he was, but thanks for making me check! i've added him and explicitly asked this question...

**Comment by akaStiX** [comment]
For you info, I just tried -gz (zlib) option and it reduced DSO size from 4.03GB down to 1.26GB. A huge win for us.
I believe zstd will push it even more

**Comment by enh-google** [comment]
well, if you're not actually specifically committed to zstd, lzma is pretty well supported --- we use that ourselves. (the latest upstream version of lzma breaks mingw builds and armv7 builds, which is why _i_ was wondering whether we can get out of the lzma business and move to zstd. not actually for any time/space reason. it's just a very Windows-first project, which isn't the most convenient for us.)

**Comment by DanAlbert** [comment]
If I've followed all the threads correctly, there's nothing left for the NDK to do here. LLVM is the part we ship, and that's fixed. The Studio half is tracked here: https://issuetracker.google.com/271430145

**Comment by akaStiX** [comment]
@DanAlbert I think this request was closed prematurely. NDK25 supports zlib compression, but not zstd and that's what this request is about. I just took it off original track and I apologize for that.
My understanding is that zstd compression was added to llvm 16, so this might be quite a while before it gets to Android

**Comment by DanAlbert** [comment]
Thanks for confirming. Too many Zs and apparently I can't keep them straight. The next compiler we're upgrading to (for r26) will be from the LLVM 17 development, so it'll include that.

**Comment by enh-google** [comment]
(despite it being "my" internal thread, i don't remember the resolution of the "does upstream lldb support zstd, and -- even if it does -- have we enabled that in our lldb build?" question...)

**Comment by DanAlbert** [comment]
I'd felt like the answer was "yes", but now I have no clue if that was actually about zlib.

**Comment by enh-google** [comment]
from the fact it's not even listed as an optional dependency to the lldb build (https://lldb.llvm.org/resources/build.html#optional-dependencies) i'm guessing "no" :-(

(and a quick search of the thread didn't obviously turn up anyone explicitly saying "yes".)

**Comment by DanAlbert** [comment]
@emrekultursay may be the only one that can make sense of this :)

**Comment by pirama-arumuga-nainar** [comment]
zstd support should be included in clang-r487747c and r26.  The reason lldb explicitly calls out LZMA is that lld/clang don't produce lzma-compressed debug info but lldb needs it to read them from binaries generated by other toolchains.  For zlib and zstd, lldb uses the compression support in llvm (https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Compression.cpp#L20).
