### ISSUE TITLE
[Bug]: Java method is not visible from C/C++ code via JNI

### ISSUE THREAD

**Issue by HolimaX** [android/ndk#1774]
### Description

Full details already provided at StackOverflow: https://stackoverflow.com/questions/73961658/c-c-does-not-see-java-method-in-jni-via-android-ndk

### Affected versions

r25

### Host OS

Linux

### Host OS version

Android 8.0+

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by DanAlbert** [comment]
Not something we have control over, and definitely isn't an LLVM bug, which is the template used here. Follow b.android.com and file a framework bug against the Java component of the API, probably?

**Comment by HolimaX** [comment]
Maybe. I have already made an ticket; trying to find spare time to actually provide debug logs ;/
