### ISSUE TITLE
[BUG] ndk/tools/ndk_bin_common.sh FreeBSD invalid definition..

### ISSUE THREAD

**Issue by cederom** [android/ndk#1781]
### Description

* In the file `ndk/build/tools/ndk_bin_common.sh` there is an invalid definition for FreeBSD.
* FreeBSD can natively emulate Linux ELF so all binaries provided for Linux can be used on FreeBSD.
* Line 22 currently `FreeBsd) HOST_OS=freebsd;;` should be `FreeBSD) HOST_OS=linux;;`.
* In perfect works Google would release build tools and binaries also for FreeBSD.
* Another issue that prevents running shell scripts on FreeBSD Unix is hardcoding Linux only `#!/bin/bash` shell interpreter instead valid `#!/usr/bin/env bash` that I have reported separately in https://github.com/android/ndk/issues/1780.

[1] https://android.googlesource.com/a/platform/ndk/+/refs/heads/master/build/tools/ndk_bin_common.sh

### Affected versions

r23, r24, r25, Canary

### Canary version

270076ca936ed0dca16de84e302dde296aaf1ca4

### Host OS

Linux

### Host OS version

FreeBSD 13-STABLE

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

20

### Device API level

21

**Comment by cederom** [comment]
Fixed here: https://github.com/cederom/google-android-ndk/compare/master...cederom-freebsd-recognition-fix-20221017

**Comment by DanAlbert** [comment]
We don't support freebsd.
