### ISSUE TITLE
[BUG] Inconsistent `#!/usr/bin/env python` and `#!/usr/bin/env python3` interpreter calls.

### ISSUE THREAD

**Issue by cederom** [android/ndk#1785]
### Description

* Python scripts in the NDK repo use inconsistent `#!/usr/bin/env python` and `#!/usr/bin/env python3` interpreter calls.
* Is this on purpose?
* The most portable and accurate way of calling Python interpreter is `#!/usr/bin/env python3` if we want to use Python 3.X.
* On FreeBSD there can be several different Python interpreters residing in the userland, or the venv, but they should be called explicitly by `python3.X` or simply `python3` (even `python2` in extreme cases), but that is custom non-standard environment.
* `python` was often used for Python 2 but this guy is obsolete.
* `python` may be pointing to `python3.X` in the local Virtual Environment, or can be linked by user, but that is not the generic way that would provide consistent behavior among different OS in their default setup.
* Please consider unification to `#!/usr/bin/env python3` in all python scripts :-)
```
% grep -r '#!/usr/bin/env python3' *
build/tools/make_standalone_toolchain.py:#!/usr/bin/env python3
scripts/update_kokoro_prebuilts.py:#!/usr/bin/env python3
tests/ndk-stack/ndk_stack_systemtest.py:#!/usr/bin/env python3
tests/ndk-stack/ndk_stack_unittest.py:#!/usr/bin/env python3

% grep -r '#!/usr/bin/env python' *
build/ldflags_to_sanitizers.py:#!/usr/bin/env python
build/tools/make_standalone_toolchain.py:#!/usr/bin/env python3
build/test_ldflags_to_sanitizers.py:#!/usr/bin/env python
checkbuild.py:#!/usr/bin/env python
ndk/run_tests.py:#!/usr/bin/env python
ndk/checkbuild.py:#!/usr/bin/env python
ndk-gdb.py:#!/usr/bin/env python
ndk-stack.py:#!/usr/bin/env python
parse_elfnote.py:#!/usr/bin/env python
run_tests.py:#!/usr/bin/env python
scripts/gen_release_table.py:#!/usr/bin/env python
scripts/update_dac.py:#!/usr/bin/env python
scripts/create_windows_instance.py:#!/usr/bin/env python
scripts/update_kokoro_prebuilts.py:#!/usr/bin/env python3
tests/ndk-stack/ndk_stack_systemtest.py:#!/usr/bin/env python3
tests/ndk-stack/ndk_stack_unittest.py:#!/usr/bin/env python3
```

### Affected versions

r23, r24, r25, Canary

### Canary version

ae5482fd065180af950edc365bb7e2a5710a7881

### Host OS

Linux, Mac, Windows

### Host OS version

FreeBSD 13-STABLE AMD64.

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

20

### Device API level

20

**Comment by cederom** [comment]
Here is the proposed fix, please verify: https://github.com/cederom/google-android-ndk/tree/cederom-python-scripts-interpreter-fix-20221017

**Comment by jfgoog** [comment]
This is very low priority and not really necessary.

The instances of `#!/usr/bin/env python3` you found are for testing, and don't affected the NDK. The exception is build/tools/make_standalone_toolchain.py, which is deprecated and we should probably remove.

**Comment by cederom** [comment]
`#!/usr/bin/env python` is a blocker on FreeBSD. Not only test scripts seems to use them (list of files is provided above in the report). It's a trivial fix that does lots of good.. but please verify if not break anything on Linux and macOS :-)

**Comment by DanAlbert** [comment]
If those shebangs are a problem you've made a mistake in your environment.

**Comment by cederom** [comment]
Google really hires this kind of ignorant people in their Open-Source projects?

Tell me why some scripts in the same repository use `#!/usr/bin/env python`  and some use `#!/usr/bin/env python3`?

**Comment by DanAlbert** [comment]
Personal attacks will not be tolerated. This is your only warning.

Those shebangs have identical behavior if you've followed the docs.

**Comment by suarezvictor** [comment]
Why it's so difficult to harmonize the shebang it that makes easier to run the tool in other platforms? "python" may be python 2.X or 3.X in many environments

**Comment by DanAlbert** [comment]
It's not hard, it's pointless. There will be zero behavior difference. It **does not** improve support for other platforms. You need to read the docs. These tools are not meant to be invoked directly in your system's python environment on _any_ platform. We don't do that specifically because using our own python environment avoids cross-platform issues.

**Comment by sporkman** [comment]
Seems like a best practices thing, not understanding the pushback here.

**Comment by cederom** [comment]
Not really, if I we want to create Android NDK port for FreeBSD (or any other OS) as the system package, it needs to adhere to (Unix) OS standards and packages dependencies. It is very nice that packages for Windows, macOS and Linux are provided. It wold be also nice to have that "OpenSource" tool working on different platforms. We can either patch the upstream or create separate fork and patch it. The first approach seems more reasonable. All we want is to adhere to general Unix standards and best practices. If we make it happen other parts of the Android SDK will follow.

**Comment by DanAlbert** [comment]
> not understanding the pushback here.

If it's important to you, feel free to send a patch.

**Comment by cederom** [comment]
All three related patches are sent  for review:
* https://android-review.googlesource.com/c/platform/ndk/+/2261302
* https://android-review.googlesource.com/c/platform/ndk/+/2261303
* https://android-review.googlesource.com/c/platform/ndk/+/2261304

**Comment by cederom** [comment]
Wow, thank  you @DanAlbert for accepting one of my first patches! :-)
