### ISSUE TITLE
[BUG] [CMake] ANDROID_TOOLCHAIN_PREFIX is malformed in NDK r25

### ISSUE THREAD

**Issue by alalek** [android/ndk#1802]
### Description

During migration on newer NDK observing the following problem.

`ANDROID_TOOLCHAIN_PREFIX` is broken in NDK r25
Value is useless, mentioned files are missing.

Actual value:

```
/opt/android/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
```

Expected:

```
/opt/android/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-
```

Reproducer:

CMakeLists.txt:

```.cmake
cmake_minimum_required(VERSION 3.5)
project(test_android)

message(FATAL_ERROR "ANDROID_TOOLCHAIN_PREFIX=${ANDROID_TOOLCHAIN_PREFIX}")
```

Command:

```.bash
$ ${ANDROID_SDK}/cmake/3.22.1/bin/cmake -GNinja \
  -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
  -DANDROID_ABI="arm64-v8a"
```

---

No such files in NDK r25:

```.bash
ls -1 /opt/android/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-*
ls: cannot access '/opt/android/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-*': No such file or directory
```

---

**Note**: r23 is partially broken (there is `as` tool symbolic link, but other tools like `ranlib` are missing)

### Affected versions

r25

### Host OS

Linux, Mac, Windows

### Host OS version

any

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

21

**Comment by DanAlbert** [comment]
What's the actual thing you're trying to do that doesn't work? From my read of this bug the actual mistake is that we forgot to delete that variable.

**Comment by alalek** [comment]
Some build scripts uses value of this variable to specify `ar` / `ranlib` build tools (cross-compilation is designed through `target triplet` prefixes).
E.g., problem is observed here: https://github.com/ARM-software/ComputeLibrary/blob/v22.08/SConstruct#L392-L394
(this is not a CMake script, but value from CMake Android toolchain is passed there "as is")


I'm personally OK to remove it, but we need some correct way to specify this its path through CMake toolchain variables:

```
/opt/android/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-
```

**Comment by DanAlbert** [comment]
`CMAKE_AR` and `CMAKE_RANLIB`. You don't need or want android specific code here :)

**Comment by DanAlbert** [comment]
Triaging to r26 so we remember to clean up the misleading leftover, but it doesn't appear to be needed:

```bash
danalbert-macbookpro2 :: src/ndk/ndk ‹249d0ebe› » git grep ANDROID_TOOLCHAIN_PREFIX
build/cmake/android-legacy.toolchain.cmake:set(ANDROID_TOOLCHAIN_PREFIX
build/cmake/android-legacy.toolchain.cmake:set(_CMAKE_TOOLCHAIN_PREFIX "${ANDROID_TOOLCHAIN_PREFIX}")
build/cmake/android-legacy.toolchain.cmake:  set(CMAKE_ASM_ANDROID_TOOLCHAIN_PREFIX "${ANDROID_TOOLCHAIN_PREFIX}")
build/cmake/android-legacy.toolchain.cmake:  set(CMAKE_C_ANDROID_TOOLCHAIN_PREFIX "${ANDROID_TOOLCHAIN_PREFIX}")
build/cmake/android-legacy.toolchain.cmake:  set(CMAKE_CXX_ANDROID_TOOLCHAIN_PREFIX "${ANDROID_TOOLCHAIN_PREFIX}")
```

The fact that it's never been exposed in the new toolchain file supports that theory.

@ZijunZhaoCCK, want to take this one? Doesn't need any new tests or docs or anything, just delete the old unused code.

**Comment by ZijunZhaoCCK** [comment]
Sure. I am interested in this one :D

**Comment by ZijunZhaoCCK** [comment]
The fix is merged. Done.

**Comment by ZijunZhaoCCK** [comment]
The fix is merged. Done.
