### ISSUE TITLE
[FR] build-tools / emulator package on M1

### ISSUE THREAD

**Issue by kasperk81** [android/ndk#1807]
### Description

following https://github.com/android/ndk/issues/1299, these days ndk and sdk are installing on M1/arm64 just fine.
but emulator experience isn't as nice as it is on amd64 machine..

ndk/sdk installation:
```sh
NDK=~/android/ndk
SDK=~/android/sdk

# install ndk
curl https://dl.google.com/android/repository/android-ndk-r23c-darwin.zip -L --output ~/x.zip
unzip ~/x.zip -d $(dirname $NDK) && rm -rf ~/x.zip

# install sdk
curl https://dl.google.com/android/repository/commandlinetools-linux-r23c.zip -L --output ~/x.zip
mkdir $SDK && unzip ~/x.zip -d $SDK/cmdline-tools && rm -rf ~/x.zip
yes | $SDK/cmdline-tools/tools/bin/sdkmanager --sdk_root=$SDK --licenses
```

all good, so far.. now install build-tools
```
$SDK/cmdline-tools/tools/bin/sdkmanager --sdk_root=$SDK "platform-tools" "platforms;android-29" "build-tools;29.0.3"
```

it warns:
```
Warning: Dependant package with key emulator not found!                         
Warning: Unable to compute a complete list of dependencies.
```
and exists without installing anything.

is this something on your radar or unexpected? apparently i'm not the only one struggling with it https://stackoverflow.com/questions/71545278/install-build-tools-on-arm64-doesnt-work.

**Comment by DanAlbert** [comment]
We don't work on those tools. File a bug against Studio on b.android.com

**Comment by kasperk81** [comment]
ok..
#1299 was discussing SDK & NDK (see the top post) and it got locked, so i didn't realize it is "prohibited"

**Comment by DanAlbert** [comment]
Prohibited is a strong word. It's just pointless. We can't help you with those products because we have no say in them.
