### ISSUE TITLE
[Bug]: No support for std::derived_from concept

### ISSUE THREAD

**Issue by SarkisKhachatryan** [android/ndk#1808]
### Description

when trying to use `std::derived_from` concept, getting this error.

```
error: no template named 'derived_from' in namespace 'std'
      template <std::derived_from<smth> T>
```

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

arm64-v8a

**Comment by SarkisKhachatryan** [comment]
As a workaround, added this code snippet to use it for now
```
template <class Derived, class Base>
concept derived_from = std::is_base_of_v<Base, Derived> &&
    std::is_convertible_v<const volatile Derived*, const volatile Base*>;
```

this works fine

**Comment by DanAlbert** [comment]
Any reason to believe this isn't a duplicate of the pinned issue https://github.com/android/ndk/issues/1530?

**Comment by DanAlbert** [comment]
Closing for lack of feedback. Probably a dup.

**Comment by SarkisKhachatryan** [comment]
Sure, thanks
