### ISSUE TITLE
[BUG] [CXX1301] Could not get version from cmake.dir path '/opt/homebrew/bin/cmake'.

### ISSUE THREAD

**Issue by magnusja** [android/ndk#1809]
### Description

```
[CXX1301] Could not get version from cmake.dir path '/opt/homebrew/bin/cmake'.
```

```
 /opt/homebrew/bin/cmake --version
cmake version 3.25.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

wuuut?

### Affected versions

r23, r24, r25

### Host OS

Mac

### Host OS version

12.6.1 (21G217)

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

15

**Comment by DanAlbert** [comment]
Nothing in the report mentions how this relates to the NDK.

**Comment by safy1** [comment]
> <img width="1219" alt="Screenshot 2022-12-06 at 15 13 17" src="https://user-images.githubusercontent.com/1659457/205935000-d2ecc048-3859-4408-8176-a5e2c12fd263.png">
> 
> 
> Very sorry, but this is all I have. My thinking was: cmake is used by the NDK. So that is why I would have thought that this best goes here. What would you suggest? Reporting it on the Android IntelliJ Plugin?
>

**Comment by DanAlbert** [comment]
Cmake is not used by the NDK. The NDK is used by cmake. In other words, we're not driving anything here. You need to file a bug against AGP (see b.android.com).

If this is somehow an NDK issue, you need to follow the bug template and provide a repro case. We can't do anything about bugs we can see.

**Comment by jfgoog** [comment]
I'm actually surprised that Studio is trying to use cmake from HomeBrew.

I would recommend installing it from the SDK manager in Android Studio, and see if that helps.
