### ISSUE TITLE
[Bug]: When compiling one of my projects with bzael, I get an unexpected error. According to the error message prompt, seek some help. Below is my working environment

### ISSUE THREAD

**Issue by honggang0524** [android/ndk#1810]
### Description

ERROR: /home/one-sports/HG/MediaPipe/one_sports/functionality/landmark_processing/BUILD.bazel:69:11: Compiling one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp failed: (Exit 254): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 71 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Stack dump:
0.      Program arguments: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -cc1 -triple aarch64-none-linux-android -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name landmark_map_to_list_converter.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -mllvm -aarch64-fix-cortex-a53-835769=1 -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /proc/self/cwd/bazel-out/android-arm64-v8a-dbg/bin/one_sports/functionality/landmark_processing/_objs/landmark_map_to_list_converter/landmark_map_to_list_converter.pic.gcno -resource-dir external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7 -dependency-file bazel-out/android-arm64-v8a-dbg/bin/one_sports/functionality/landmark_processing/_objs/landmark_map_to_list_converter/landmark_map_to_list_converter.pic.d -MT bazel-out/android-arm64-v8a-dbg/bin/one_sports/functionality/landmark_processing/_objs/landmark_map_to_list_converter/landmark_map_to_list_converter.pic.o -sys-header-deps -isystem external/androidndk/ndk/sysroot/usr/include/aarch64-linux-android -iquote . -iquote bazel-out/android-arm64-v8a-dbg/bin -iquote external/com_google_protobuf -iquote bazel-out/android-arm64-v8a-dbg/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/android-arm64-v8a-dbg/bin/external/zlib -iquote external/com_github_glog_glog_no_gflags -iquote bazel-out/android-arm64-v8a-dbg/bin/external/com_github_glog_glog_no_gflags -iquote external/com_google_absl -iquote bazel-out/android-arm64-v8a-dbg/bin/external/com_google_absl -iquote external/androidndk -iquote bazel-out/android-arm64-v8a-dbg/bin/external/androidndk -isystem external/com_google_protobuf/src -isystem bazel-out/android-arm64-v8a-dbg/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/android-arm64-v8a-dbg/bin/external/zlib -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystem external/androidndk/ndk/sysroot/usr/include -D __ANDROID_API__=21 -U NDEBUG -D MEDIAPIPE_PROFILER_AVAILABLE -I bazel-out/android-arm64-v8a-dbg/bin/external/com_github_glog_glog_no_gflags/_virtual_includes/default_glog_headers -isysroot external/androidndk/ndk/platforms/android-21/arch-arm64 -internal-isystem external/androidndk/ndk/platforms/android-21/arch-arm64/usr/local/include -internal-isystem external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7/include -internal-externc-isystem external/androidndk/ndk/platforms/android-21/arch-arm64/include -internal-externc-isystem external/androidndk/ndk/platforms/android-21/arch-arm64/usr/include -O0 -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -w -std=c++2a -fdeprecated-macro -fdebug-compilation-dir /proc/self/cwd -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o bazel-out/android-arm64-v8a-dbg/bin/one_sports/functionality/landmark_processing/_objs/landmark_map_to_list_converter/landmark_map_to_list_converter.pic.o -x c++ one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp 
1.      one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp:19:5: current parser token '{'
2.      one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp:5:1: parsing namespace 'one_sports'
3.      one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp:11:1: parsing struct/union/class body 'one_sports::LandmarkMapToListConverter'
4.      one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp:16:3: parsing function body 'one_sports::LandmarkMapToListConverter::convert'
5.      one_sports/functionality/landmark_processing/landmark_map_to_list_converter.cpp:16:3: in compound statement ('{}')
#0 0x000000000242f066 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x242f066)
#1 0x000000000242dca0 llvm::sys::RunSignalHandlers() (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x242dca0)
#2 0x000000000242f34f (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x242f34f)
#3 0x00007f8b2a1fa420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
#4 0x000000000335e360 (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x335e360)
#5 0x0000000003338645 (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x3338645)
#6 0x0000000003337875 clang::Sema::CheckCompleteDecompositionDeclaration(clang::DecompositionDecl*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x3337875)
#7 0x00000000032bb435 clang::Sema::CheckCompleteVariableDeclaration(clang::VarDecl*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x32bb435)
#8 0x00000000032b9c19 clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x32b9c19)
#9 0x00000000035098e4 clang::Sema::BuildCXXForRangeStmt(clang::SourceLocation, clang::SourceLocation, clang::Stmt*, clang::SourceLocation, clang::Stmt*, clang::Stmt*, clang::Stmt*, clang::Expr*, clang::Expr*, clang::Stmt*, clang::SourceLocation, clang::Sema::BuildForRangeKind) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x35098e4)
#10 0x0000000003508e1b clang::Sema::ActOnCXXForRangeStmt(clang::Scope*, clang::SourceLocation, clang::SourceLocation, clang::Stmt*, clang::Stmt*, clang::SourceLocation, clang::Expr*, clang::SourceLocation, clang::Sema::BuildForRangeKind) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x3508e1b)
#11 0x0000000003092c42 clang::Parser::ParseForStatement(clang::SourceLocation*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x3092c42)
#12 0x000000000308ff62 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x308ff62)
#13 0x000000000308fc40 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x308fc40)
#14 0x00000000030946cd clang::Parser::ParseCompoundStatementBody(bool) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30946cd)
#15 0x0000000003094f09 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x3094f09)
#16 0x00000000030e6a51 clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30e6a51)
#17 0x00000000030e5f69 clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30e5f69)
#18 0x00000000030d4597 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30d4597)
#19 0x00000000030d1ea4 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30d1ea4)
#20 0x00000000030a8d9e clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30a8d9e)
#21 0x000000000307ffd2 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x307ffd2)
#22 0x000000000307fd52 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x307fd52)
#23 0x000000000307ece3 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x307ece3)
#24 0x00000000030ce482 clang::Parser::ParseInnerNamespace(std::__1::vector<clang::SourceLocation, std::__1::allocator<clang::SourceLocation> >&, std::__1::vector<clang::IdentifierInfo*, std::__1::allocator<clang::IdentifierInfo*> >&, std::__1::vector<clang::SourceLocation, std::__1::allocator<clang::SourceLocation> >&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30ce482)
#25 0x00000000030cd3e2 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30cd3e2)
#26 0x00000000030a85b7 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x30a85b7)
#27 0x000000000307ec86 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x307ec86)
#28 0x000000000307e73c clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x307e73c)
#29 0x000000000307b782 clang::ParseAST(clang::Sema&, bool, bool) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x307b782)
#30 0x00000000028d0cf5 clang::FrontendAction::Execute() (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x28d0cf5)
#31 0x000000000286db67 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x286db67)
#32 0x0000000002932ff5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x2932ff5)
#33 0x00000000018876d4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x18876d4)
#34 0x0000000001883f22 main (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x1883f22)
#35 0x00007f8b29daa083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#36 0x0000000001883029 _start (external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+0x1883029)
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: aarch64-none-linux-android
Thread model: posix
InstalledDir: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/landmark_map_to_list_converter-3220b6.cpp
clang: note: diagnostic msg: /tmp/landmark_map_to_list_converter-3220b6.sh
clang: note: diagnostic msg: 

********************

### Affected versions

Canary

### Canary version

r20b

### Host OS

Linux

### Host OS version

Ubuntu20.04

### Affected ABIs

arm64-v8a

**Comment by DanAlbert** [comment]
r20 is not supported. Try with r25. If the problem persists, we'll re-open.
