### ISSUE TITLE
[Bug]: Missing strip utils

### ISSUE THREAD

**Issue by djtolib** [android/ndk#1814]
### Description

In NDK r25b missed utils like [arch]-linux-android-strip. Build  fails. 

Execution failed for task ':app:stripDebugDebugSymbols'.
> 1 exception was raised by workers:
  org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'c:\ndkr25b\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip''

### Affected versions

r25

### Host OS

Windows

### Host OS version

10

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by jessopb** [comment]
What ended up being the issue here? (I have this error msg)

**Comment by DanAlbert** [comment]
Use llvm-strip.
