### ISSUE TITLE
[BUG] android.toolchain.cmake should stop injecting CFLAGS with clang incompatible switches

### ISSUE THREAD

**Issue by ceztko** [android/ndk#1816]
### Description

`cmake/android-legacy.toolchain.cmake` and `cmake/flags.cmake` are currently injecting[1][2] `CFLAGS` with `-march=armv7-a` when the `armeabi-v7a` ABI is selected. This has been done for a long time and it's referring to issue https://github.com/android-ndk/ndk/issues/906. Today this looks like quite an arbitrary and legacy setting, and at the current moment it seems to cause harm when trying to take advantage of `CMAKE_C_FLAGS` to feed other build systems using CMake, causing failures like the one below to me (observed also in other [reports](https://github.com/conan-io/conan-center-index/issues/12723)):

```
lang: error: the clang compiler does not support '-march=armv7-a'
```

As a matter of fact, `clang` compilers seems to refuse to observe any `-march` switch when the non standalone binary is used togheter with the `--target` switch, eg. `--target=armv7-none-linux-androideabi23`, so maybe that setting was intended for legacy `gcc` compilations or standalone toolchains. At the same time, on recent versions, CMake compilations seems to munge the switch anyway, as they are unaffected by either its presence or absence when using `clang`, which should be the only supported compiler available today.

I recommend removing the injection of the `-march` switch or limit it to the context where it is actually needed.

[1] https://android.googlesource.com/platform/ndk/+/47003c4e6beefcdb0300fc26ce1ea8176d09b010/build/cmake/android-legacy.toolchain.cmake#515
[2] https://android.googlesource.com/platform/ndk/+/47003c4e6beefcdb0300fc26ce1ea8176d09b010/build/cmake/flags.cmake#73

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

armeabi-v7a

### Build system

ndk-build

### minSdkVersion

1

**Comment by ceztko** [comment]
Similarly `-mthumb` which is [similarly](https://android.googlesource.com/platform/ndk/+/47003c4e6beefcdb0300fc26ce1ea8176d09b010/build/cmake/android-legacy.toolchain.cmake#517) [added](https://android.googlesource.com/platform/ndk/+/47003c4e6beefcdb0300fc26ce1ea8176d09b010/build/cmake/flags.cmake#76) seems to be completely unnecessary when building with clang and produces the warnings below. Probably CMake trims it away silently, that's why it was not noticed before. I also recommend to remove injecting it in `CFLAGS`.

```
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
...
```

**Comment by ceztko** [comment]
As a matter of fact, removing any special `armeabi` ABI treatment, as in the attached patch, fixed all the issues I had by using `CMAKE_C_FLAGS` in non CMake projects compiled with `ExternalProject_Add`.

[remove-clang-incompatible-switches-injection.diff.txt](https://github.com/android/ndk/files/10200002/remove-clang-incompatible-switches-injection.diff.txt)

**Comment by DanAlbert** [comment]
I don't understand what the actual problem is here. What thing is receiving cflags that doesn't understand cflags?

**Comment by ceztko** [comment]
The use case is the following: I'm using CMake to build other CMake based and non CMake based dependent projects using `ExternalProject_Add`. In the latter, I pipe `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` to build the dependencies consistently. C projects may fail because of the above cited incompatible flag `-march=arm7v-a` or `-mthumb`. The easiest way to see this is really running clang with the smallest number of flags trying to compile anything like in the following:

```
$ export ANDROID_NDK_HOME=/opt/android-ndk
$ export PATH="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
$ clang -target armv7-none-linux-androideabi23 --sysroot=/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -march=arm7v-a test.c
clang-14: error: the clang compiler does not support '-march=arm7v-a'
```

I hope this is enough to prove my point. If required I can make a hello world CMake project using `ExternalProject_Add` trying to build something with the invalid `CMAKE_C_FLAGS`. As said previously I think CMake projects don't care about because it may purge invalid switches, but I can't really prove it at this moment. Still I believe my use case is a good one and `CMAKE_C_FLAGS` should not carry invalid/spurious switches.

**Comment by ceztko** [comment]
Hold on, I deleted my previous comment. I want to double check all the matter once again since now I noticed some switches are position sensitive, which may explain (or not) the issue I had.

**Comment by DanAlbert** [comment]
`~/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -target armv7-none-linux-androideabi23 -march=armv7-a foo.c -shared`

Works fine for me.

**Comment by ceztko** [comment]
I know prebuilt toolchains are are less sensible to such issues. With non prebuilt toolchains if the `-march` switch is after the `--sysroot` then you have all the issue I mentioned, but if you have it just after the `--target` switch then it works fine. I found the right way to compose the various CMake variables into an usable `CFLAGS`. Here it follow a working hello world example that shows my original use case:

```
cmake_minimum_required(VERSION 3.5)

project(foo)

set(TOOLCHAIN_ROOT ${ANDROID_TOOLCHAIN_ROOT})
set(SYSROOT "${TOOLCHAIN_ROOT}/sysroot")
set(CFLAGS_BASE "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_TARGET}")
separate_arguments(CFLAGS_BASE)
set(CFLAGS "--target=${CMAKE_C_COMPILER_TARGET}" ${CFLAGS_BASE} "--sysroot=${SYSROOT}")

message("CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}")
message("CFLAGS: ${CFLAGS}")

include(ExternalProject)

ExternalProject_Add(foo
    URL "${CMAKE_CURRENT_SOURCE_DIR}/foo.tar"
    CONFIGURE_COMMAND ""
    BUILD_COMMAND "${CMAKE_C_COMPILER}" ${CFLAGS} foo.c
    INSTALL_COMMAND ""
    BUILD_IN_SOURCE 1
)
```

Attached the full working example, if it's useful for someone else.
[TestCMakeExternalProject.tar.gz](https://github.com/android/ndk/files/10212620/TestCMakeExternalProject.tar.gz)

The mistake was on my side: I was inverting `${CMAKE_C_FLAGS}` and `${CMAKE_C_FLAGS_TARGET}`, confusing non prebuilt toolchain clang. I cleaned some comments of mine with wrong assumptions. Sorry for the disturb, please flag the issue as invalid.

**Comment by DanAlbert** [comment]
What is a non prebuilt toolchain?

**Comment by ceztko** [comment]
> What is a non prebuilt toolchain?

My bad, I meant **non standalone**. [Standalone](https://developer.android.com/ndk/guides/standalone_toolchain) toolchains (which should be deprecated) were less sensitive to switches positioning. The following shows the issue I was having with *prebuilt non standalone* toolchain (the recommended way). Notice the switch `-march` after `--sysroot`.

```
$ export ANDROID_NDK_HOME=/opt/android-ndk
$ export PATH="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
$ clang -target armv7-none-linux-androideabi23 --sysroot=/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -march=arm7v-a test.c
clang-14: error: the clang compiler does not support '-march=arm7v-a'
```

The error message was very misleading but at least now I found a way to handle the situation properly.

**Comment by DanAlbert** [comment]
```
~/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -target armv7-none-linux-androideabi23 --sysroot=/Users/danalbert/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -march=armv7-a foo.c -shared
```

Works just fine on my machine. There's no difference between a standalone toolchain and the regular toolchain aside from the overhead of a shell script that passes a `-target` argument.

**Comment by DanAlbert** [comment]
My guess is that you have another `clang` on your path that doesn't include the Arm backend, and you're somehow invoking that one by mistake.

**Comment by ceztko** [comment]
> My guess is that you have another clang on your path

It doesn't look like:

```
$ clang
bash: clang: command not found
$ which clang
/usr/bin/which: no clang in ....
```

In my machine the following produces the above mentioned error:
```
$ /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7-none-linux-androideabi23 --sysroot=/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -march=arm7v-a test.c -shared
clang-14: error: the clang compiler does not support '-march=arm7v-a'
```

While the next one (only difference `-march` is before `--sysroot`) works correctly.
```
/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7-none-linux-androideabi23 -march=armv7-a --sysroot=/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot test.c -shared
```

I was already able to produce an openssl static library that links correctly in another complex arm shared library this way. Thank you for keeping supporting me: I also would love to understand why switches positioning seems to make a difference (at least in my machine). I will monitor the situation, but unless the produced binaries are problematic (not so far) I will accept the behavior on this build setup (actually, a containerized Centos 7).

**Comment by rprichard** [comment]
`-march=arm7v-a` is a typo. `7v` should be `v7`.

**Comment by rprichard** [comment]
(FWIW, it took me a while to notice the typo. e.g. At one point, I was running both the correct and incorrect command-lines and could not figure out the difference. I even echoed the command-line to `hd` thinking there was maybe some invisible control character, but no.)

**Comment by ceztko** [comment]
Oh my gosh, thank you for spotting the typo. Please note that those are bare commands that I tried to debug the original issue. Everything started with me trying to use CMake+`android.toolchain.cmake` to build openssl. I **never** tried supplying the `-march` switch my self and that's what I got:

```
lang: error: the clang compiler does not support '-march=armv7-a'
```

No typo here and the original report is [consistent](https://github.com/android/ndk/issues/1816#issue-1486867378). I can dig more the exact circumstances why I received this, and if I find something interesting I can update here.

**Comment by ceztko** [comment]
But, most probably, any more digging will end with me discovering extra mistakes I was doing. Fortunately, thanks to all your support, I was able to reason and setup things more correctly. You can safely mark this issue as "invalid", if you have such label.
