### ISSUE TITLE
[FR] add callback to `ANativeActivityCallbacks` for handling `startActivityForResult()`

### ISSUE THREAD

**Issue by ITotalJustice** [android/ndk#1818]
### Description

Hi. I was wondering if we could have a callback added to `ANativeActivityCallbacks` that would be called on activity result.

Afaik there is no way to handle the result of `startActivityForResult()` in native only code (C/C++, no java). Having a callback for this would be very helpful.

In my app, i almost have everything i need to have the code be completely C/C++ (with a lot of jni 😄 ) but the lack of handling `startActivityForResult()` is the only thing holding me back. I need let the user select a directory which i can r/w files to (good old scoped storage). I can start the activity fine https://gist.github.com/ITotalJustice/73f2a65617af5a8fd46c04fbef8326b8 but have no way of handling it.

Thanks!

**Comment by DanAlbert** [comment]
API requests should be made against the OS (we are only the delivery mechanism for these APIs; we don't implement or design them). Use the framework component on http://b.android.com.
