### ISSUE TITLE
[BUG] std::map contains does not work properly

### ISSUE THREAD

**Issue by SarkisKhachatryan** [android/ndk#1820]
### Description

Non-working code with r25 version.

```
bool boo(const std::map<std::string, int, std::less<>>& map, std::string_view str) {
    return map.contains(str);
}

int main(int, char**) {
    std::map<std::string, int, std::less<>> map;

    map["a"] = 1;
    map["b"] = 2;
    map["c"] = 3;
    map["d"] = 4;

    std::string_view s = "a";
    std::cout << std::boolalpha << boo(map, s);

    return 0;
}
```

code won't compile on Android studio, generating the following error message:

```
error: no viable conversion from 'std::string_view' (aka 'basic_string_view<char>') to 'const std::map<std::basic_string<char>, int,  std::less<>>::key_type' (aka 'const std::basic_string<char>')
      return map.contains(str);
```

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

23

**Comment by yujincheng08** [comment]
`return map.contains(std::string(str))`

**Comment by jfgoog** [comment]
Converting from string_view to string is not automatic, because it requires a copy and and allocation.

[The C++ standard library does not ](https://stackoverflow.com/questions/47525238/why-is-there-no-implicit-conversion-from-stdstring-view-to-stdstring)
