### ISSUE TITLE
buildFeatures.prefab equivalent when calling ndk-build.cmd?

### ISSUE THREAD

**Issue by znakeeye** [android/ndk#1825]
### Description

In my `android.mk` I include these [AGDK](https://developer.android.com/games/agdk) libraries:
```mk
$(call import-module,prefab/game-activity)
$(call import-module,prefab/games-controller)
```
That works when `ndk` is invoked via `gradle` (i.e. via Android Studio), since it (from what I understand) sets `NDK_GRADLE_INJECTED_IMPORT_PATH`. Now, when calling `ndk-build.cmd` outside Android Studio - e.g. from `buildbot` - how do you determine/add this path? Is there any way to trigger the "prefab" loop from within `ndk-build`?

In `build.gradle` it's easy:
```gradle
android {
    buildFeatures.prefab true
}
```
It seems to me that `ndk-build` will **not** be able to build any `prefab` powered `Android` project. Correct me if I'm wrong.

### Affected versions

r25

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

19

### Device API level

30

**Comment by DanAlbert** [comment]
ndk-build doesn't have native support for extracting and processing prefab packages, no. https://google.github.io/prefab/example-workflow.html has an example of doing this for CMake, and ndk-build will be essentially the same, aside from the name of the variable you pass. https://github.com/google/prefab/issues/150 is the FR to make that workflow not painful.
