### ISSUE TITLE
Hilarious problem! Simple project gets link errors if you don't specify "-v"

### ISSUE THREAD

**Issue by znakeeye** [android/ndk#1827]
### Description

This one is indeed hilarious. Bear with me :)

I've been struggling with link errors the whole week. A simple app consumes a simple library as a prefab (which, by the way, also consumes a prefab). When built, I get link errors for the most basic stuff. Going nuts here.

**The error:**
```
> Task :bar:buildNdkBuildDebug[armeabi-v7a] FAILED
C/C++: ld: error: undefined symbol: TheBar()
C/C++: >>> referenced by foobar.cpp:5 (src/main/jni/foobar.cpp:5)
C/C++: >>>               C:\baferp\bar\build\intermediates\cxx\Debug\1n6p734j/obj/local/armeabi-v7a/objs-debug/foobar/C_/Users/krist/Desktop/baferp/bar/src/main/jni/foobar.o:(android_main())
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [C:Android/Sdk/ndk/25.1.8937393/build/../build/core/build-binary.mk:657: C:\baferp\bar\build\intermediates\cxx\Debug\1n6p734j/obj/local/armeabi-v7a/libfoobar.so] Error 1
```
Aha! So let's add that "-v" argument to get some details! Heading to `defaultConfig`, adding the usual stuff:
```gradle
externalNativeBuild {
    ndkBuild {
        arguments "-v"
    }
}
```
Make project again, and...
```
BUILD SUCCESSFUL in 20s
69 actionable tasks: 22 executed, 47 up-to-date

Build Analyzer results available
```

Boom! We have a workaround! 🤣 

Attaching a sample project (for `Electric Eel`) demonstrating this peculiarity. Search for "HILARIOUS" and you'll find the piece where you can toggle this "-v" thing on and off.
[Sample project](https://github.com/android/ndk/files/10421483/baferp.zip)

### Affected versions

r23, r25

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

19

**Comment by DanAlbert** [comment]
Your gradle change doesn't do what you think it does:

```
$ ~/Library/Android/sdk/ndk/25.1.8937393/ndk-build -v 
GNU Make 4.3
Built for x86_64-apple-darwin19.3.0
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

It builds "successfully" because you've told ndk-build to print the version information and exit successfully rather than actually build anything. You need `LOCAL_LDFLAGS += -v`
