### ISSUE TITLE
Static libraries unconditionally stripped in .a inside .aar

### ISSUE THREAD

**Issue by znakeeye** [android/ndk#1830]
### Description

I have a `com.android.library` where I use `prefabPublishing` to publish an `.aar` with a **static** library to be consumed from my app. The build system insists on stripping the produced `.a` file, resulting in linking errors when compiling the app.

See attached **sample project**: [linking-errors.zip](https://github.com/android/ndk/files/10439952/linking-errors.zip)

I've tried pretty much everything. The only (ugly) workaround I found, is to re-include all static (and dynamic) libraries in the app's shared library.

**THE QUESTION**
How can I bundle the `.a` library in the `.aar` without having to specify a gazillion known dependencies in the consumer app?

**Details**
I read about whole archives, and thought that would do the trick. But no. From the errors, it looks like all these are completely ignored:
```mk
# Does NOT work:
# LOCAL_STATIC_LIBRARIES := game-activity paddleboat_static

# Should work?
LOCAL_WHOLE_STATIC_LIBRARIES := game-activity paddleboat_static

# Trying everything here...
LOCAL_EXPORT_STATIC_LIBRARIES := $(LOCAL_WHOLE_STATIC_LIBRARIES)
LOCAL_EXPORT_CFLAGS := $(LOCAL_CFLAGS)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)
LOCAL_EXPORT_LDLIBS := -llog -lGLESv2 -landroid -lEGL
# Still no good! Linking errors in consuming project! :(
```
No matter what I type in `Android.mk`, Android Studio keeps throwing these errors at me:
```
> Task :bar:buildNdkBuildDebug[arm64-v8a] FAILED
C/C++: Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
C/C++: Target: aarch64-none-linux-android21
C/C++: Thread model: posix
C/C++: InstalledDir: C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin
C/C++:  "C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/ld" -EL --fix-cortex-a53-843419 --warn-shared-textrel -z now -z relro -z max-page-size=4096 --hash-style=both --enable-new-dtags --eh-frame-hdr -m aarch64linux -shared -o "C:\\Users\\yo\\Desktop\\baferp\\bar\\build\\intermediates\\cxx\\Debug\\1n6p734j/obj/local/arm64-v8a/libfoobar.so" C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/crtbegin_so.o -LC:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/lib/linux/aarch64 -LC:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21 -LC:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android -LC:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/lib --gc-sections -soname libfoobar.so "C:\\Users\\yo\\Desktop\\baferp\\bar\\build\\intermediates\\cxx\\Debug\\1n6p734j/obj/local/arm64-v8a/objs-debug/foobar/C_/Users/yo/Desktop/baferp/bar/src/main/jni/foobar.o" C:/Users/yo/Desktop/baferp/foo/build/intermediates/cxx/Debug/43h375w1/obj/local/arm64-v8a/libfoo.a C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/lib/linux/aarch64/libunwind.a -latomic "C:\\Users\\yo\\Desktop\\baferp\\bar\\build\\intermediates\\cxx\\Debug\\1n6p734j/obj/local/arm64-v8a/libc++_shared.so" --build-id=sha1 --no-rosegment --no-undefined --fatal-warnings -llog -lGLESv2 -landroid -lEGL -lc -lm -lm C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl -lc C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/crtend_so.o
C/C++: ld: error: undefined symbol: Paddleboat_getActiveAxisMask
C/C++: >>> referenced by foo.cpp:12 (src/main/jni/foo.cpp:12)
C/C++: >>>               foo.o:(TheBar) in archive C:/Users/yo/Desktop/baferp/foo/build/intermediates/cxx/Debug/43h375w1/obj/local/arm64-v8a/libfoo.a
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [C:/Users/yo/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../build/core/build-binary.mk:657: C:\Users\yo\Desktop\baferp\bar\build\intermediates\cxx\Debug\1n6p734j/obj/local/arm64-v8a/libfoobar.so] Error 1
```

### Affected versions

r23, r25

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

19

### Device API level

30

**Comment by DanAlbert** [comment]
`LOCAL_WHOLE_STATIC_LIBRARIES` doesn't do anything for a static library. Static libraries are never linked, and that field controls the `--whole-archive` flag, which is a linker argument.

None of the `LOCAL_EXPORT_*` fields have any effect on an AAR. AGP does not read those (probably cannot do so reliably because make is basically impossible for any tool other than make to understand), so they cannot be included in the module metadata automatically.

Those are both good things in this case. You **should not** be bundling the contents of other AARs into your AAR like this, because it's an ODR problem waiting to happen.

You need the metadata in the AAR to name the dependency. That's https://issuetracker.google.com/214034366 (the NDK does not produce AARs, AGP does).

**Comment by znakeeye** [comment]
> 

Thanks for your answer, and the link!

Are you saying that the solution here is to simply add
`$(call import-module,prefab/game-activity)`
plus
`LOCAL_STATIC_LIBRARIES := game-activity`
in the app's module **too**? (Or wait until that metadata feature is released?)

**Comment by DanAlbert** [comment]
For now, yes, that's what you'd need to do to workaround the missing feature. You could maybe work out some gradle-fu that would write that info to the metadata explicitly, but that's not something we know how to do.

Once that AGP feature is done you can name the dependency in your build.gradle and it will transitively apply to the consumer.

**Comment by znakeeye** [comment]
> For now, yes, that's what you'd need to do to workaround the missing feature. You could maybe work out some gradle-fu that would write that info to the metadata explicitly, but that's not something we know how to do.
> 
> Once that AGP feature is done you can name the dependency in your build.gradle and it will transitively apply to the consumer.

Is there no way to hook into the generation of the `export_libraries` field, and populate it according to one's needs?

**Comment by DanAlbert** [comment]
I have no idea.

**Comment by znakeeye** [comment]
My use case is described below. Any pointers are greatly appreciated, as Internet is of no help anymore. You're my only hope, Dan Albert 😆

I understand that pre-compiling a static library is risky. Thus, having a whole static library means I would have to provide a whole static library for all NDK versions, all platforms etc (like prefab does). And I guess it could still break. But...

**Use case**
- A game engine is available as open source.
- The code changes frequently. Thus, any consumer must frequently `git pull`, re-compile (and install) the library.
- I successfully integrated with `AGDK`, e.g. `GameActivity` and `Paddleboat` (both statically linked).
- For the game project, one single `.so` is preferable. (I read all about `c++shared` and the problems it comes with...)
- `GameActivity` requires `c++shared`...

Now, I want to make the integration with this library as simple as possible. Ideally, I want one single `my-game.so` to be used, but I realize this might be too hard to maintain due to `AGDK` integration (c++shared etc). What is the best approach here? Solutions I tried so far include:

**Solution A**
Publish an `.aar` to `MavenLocal`, allowing for a simple `implementation 'org.lib:the-engine-release:1.0`. The static library `engine.a` includes a `prefab` library to be consumed in `Android.mk`. The `module.json` file declares some required libraries. This seemed like a great solution, but I keep getting linking errors which is why I keep asking about a way to include some static libraries in the prefab-published `engine.a` file. So far no success.

**Solution B**
Using a `project ':the-engine'` reference, I can accomplish something similar to the above. However, it seems project references will not respect the `module.json` in the `.aar` and instead produce its own, empty variant. [Issue here](https://issuetracker.google.com/issues/265962210).

**Solution C**
Include an `Android.mk` module from the game engine folder, into the `my-game` module of the custom game project. This works 100%, but requires too much maintainance. The consumer of the library needs to know which static/dynamic libraries to link, choose between debug/release/other configurations, consider NDK version etc. It's just not a good solution.


Thus, the goal is to allow for a new android project to easily integrate this game engine. E.g. Add a dependency in `build.gradle`, add a prefab module (static is preferred) in `android.mk` and build.

**Comment by DanAlbert** [comment]
Solutions A and B are effectively the same thing. Those are the ones you want (whichever is more convenient).

> GameActivity requires c++shared...

Not afaict. 1.2.2 includes a `game-activity_static` module that can use either libc++ variant. If you're trying to build a single .so file, that's the one you need to use.

> This seemed like a great solution, but I keep getting linking errors which is why I keep asking about a way to include some static libraries in the prefab-published engine.a file. So far no success.

Yes, because you need https://issuetracker.google.com/214034366. That's the bug you need to press on. It's not something I can fix from our side.
