### ISSUE TITLE
[BUG] Building Library\Bee\artifacts\Android\iz17e\idcj_Generics22.o failed with output:

### ISSUE THREAD

**Issue by quackQUACK-1** [android/ndk#1837]
### Description

So I was trying to build my Android game on Unity 2022.2.2f1 with ironSource ads mediation and after fixing a few issues with the mobile dependency resolver I attempted to build it but it gave me this error

![2023-02-01 01-32-05 1675215125](https://user-images.githubusercontent.com/79320844/215925731-ccb8dcc3-a28f-42ed-af65-df2beeb9425c.png)

I have not modified/added/removed any scripts since the last time I've built my game with no errors

There's not much else I can say to get the same result but it told me to post the bug here so that's what I'm doing

**Error:**
Building Library\Bee\artifacts\Android\iz17e\idcj_Generics22.o failed with output:
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: "C:/Program Files/Unity/Editors/2022.2.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++" -march=armv7-a -mfloat-abi=softfp -mfpu=neon-fp16 -marm -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -mllvm -hoist-common-insts=1 -DANDROID -DHAVE_INTTYPES_H -no-canonical-prefixes -funwind-tables -fstack-protector -fomit-frame-pointer -std=c++11 -Wswitch -Wno-trigraphs -Wno-tautological-compare -Wno-invalid-offsetof -Wno-implicitly-unsigned-literal -Wno-integer-overflow -Wno-shift-negative-value -Wno-unknown-attributes -Wno-implicit-function-declaration -Wno-null-conversion -Wno-missing-declarations -Wno-unused-value -Wno-pragma-once-outside-header -fvisibility=hidden -fexceptions -fno-rtti -g -Os -fPIC -fno-strict-overflow -ffunction-sections -fdata-sections -fmessage-length=0 -pipe -D_GLIBCXX_USE_CXX11_ABI=0 -DBASELIB_INLINE_NAMESPACE=il2cpp_baselib -DIL2CPP_MONO_DEBUGGER_DISABLED -DRUNTIME_IL2CPP -DIL2CPP_ENABLE_WRITE_BARRIERS=1 -DIL2CPP_INCREMENTAL_TIME_SLICE=3 -DHAVE_BDWGC_GC -DNDEBUG -I. "-IC:/Users/David/Actual Games/A Very Simple Game/Library/Bee/artifacts/Android/il2cppOutput/cpp" "-IC:/Program Files/Unity/Editors/2022.2.2f1/Editor/Data/il2cpp/libil2cpp/pch" "-IC:/Program Files/Unity/Editors/2022.2.2f1/Editor/Data/il2cpp/libil2cpp" "-IC:/Program Files/Unity/Editors/2022.2.2f1/Editor/Data/il2cpp/external/baselib/Include" "-IC:/Program Files/Unity/Editors/2022.2.2f1/Editor/Data/il2cpp/external/baselib/Platforms/Android/Include" -o Library/Bee/artifacts/Android/iz17e/idcj_Generics22.o -fcolor-diagnostics -fdiagnostics-absolute-paths -target armv7a-linux-androideabi22 -fstrict-aliasing -fdiagnostics-format=msvc -c -x c++ "C:/Users/David/Actual Games/A Very Simple Game/Library/Bee/artifacts/Android/il2cppOutput/cpp/Generics22.cpp"
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'C:/Users/David/Actual Games/A Very Simple Game/Library/Bee/artifacts/Android/il2cppOutput/cpp/Generics22.cpp'.
4.	Running pass 'Live DEBUG_VALUE analysis' on function '@Enumerator_get_Current_m6AF552684A6136E5163CC3C09360202C85160FBC_gshared'
 #0 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x167109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x2b4586e
 #1 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x2b45c56 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x2caddb7
 #2 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x7caf23 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x23a748
 #3 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x240f53 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x23af72
 #4 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x127d1e1 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x15d8683
 #5 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x2914b13 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1540374
 #6 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x6c9da0 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x744473
 #7 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x6482 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x4661
 #8 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1354156 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x577d11
 #9 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1353bf4 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x692424
#10 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x692809 C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x6a5786
#11 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x3dcd C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1395
#12 0x00007ff66f76109a C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x14c8 (C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x167109a)
#13 0x00007ff66f76109a 
#14 0x00007ff66f76109a (C:\Program Files\Unity\Editors\2022.2.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x167109a)
0x00007FF66F76109A (0x0000000400000000 0x000002B5A818D838 0x000000C2C45FA9A0 0x000000C2C45FAB68)
0x00007FF670C3586E (0x0000000000000000 0x00000000000000D8 0x0000000000000000 0x000002B5A9A2F550)
0x00007FF670C35C56 (0x000000C2C45FAD60 0x000002B500000000 0x0000000000000230 0x0000000000000000)
0x00007FF670D9DDB7 (0x000002B5A150AA84 0x00000000000000FB 0x00000002A351C7A0 0x000000C20000000D)
0x00007FF66E8BAF23 (0x00007FF673087164 0x00007FF600000000 0x000000C200000000 0x00007FF66F2BD1E9)
0x00007FF66E32A748 (0x000002B5A15FE2C0 0x000000C2C45FBD70 0x000000C2C45FBD70 0x000002B5A654C470)
0x00007FF66E330F53 (0x0000001000000000 0x000002B500000000 0x000002B5A69E06B8 0x00007FFA675B5BA1)
0x00007FF66E32AF72 (0x0000000000000000 0x00007FF600000000 0x0000000000000000 0x000000C2C45FBFC8)
0x00007FF66F36D1E1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF66F6C8683 (0x000000C2C45FD3C0 0x000000C2C45FD3B0 0x000000C2C45FD390 0x00007FF66E7B798A)
0x00007FF670A04B13 (0x000002B5A15A35F0 0x0000000D00000001 0x0000000900000000 0x000000020000000A)
0x00007FF66F630374 (0x00000428000016F0 0x0000042A00000429 0x000002B5A1470000 0x0000169F0000156C)
0x00007FF66E7B9DA0 (0x000002B5A1595A10 0x000000C200000000 0x000000C2C45FDCE0 0x000002B5A1559170)
0x00007FF66E834473 (0x0000000000000004 0x00007FF66E839949 0x000000C2C45FD8B8 0x00007FF66E8397AB)
0x00007FF66E0F6482 (0x0000000000000012 0x000000000000003F 0x000000C2C34A7080 0x0000000000000002)
0x00007FF66E0F4661 (0x000000C2C45FDE78 0x000002B5A150ED40 0x000000C2C45FDE78 0x000002B5A150ED40)
0x00007FF66F444156 (0x000002B5A150ED40 0x000002B5A150ED40 0x000002B5A15A8180 0x00007FF66E6B9620)
0x00007FF66E667D11 (0x000002B5A159AA20 0x0000000000001051 0x0000000000001058 0x00007FF66E6B670D)
0x00007FF66F443BF4 (0x0000000000000010 0x000002B5A1470CC0 0x0000000200000004 0x0000000000000000)
0x00007FF66E782424 (0x000002B5A1560A31 0x000002B5A15A8950 0x00000000000000AD 0x000002B5A1509000)
0x00007FF66E782809 (0x000002B5A152EFC0 0x000002B5A152EFC0 0x000000C2C45FE460 0x000000C2C45FE460)
0x00007FF66E795786 (0x000000000000016C 0x00007FFA00000000 0x00000000000000DF 0x000000000000016C)
0x00007FF66E0F3DCD (0x0000000000000043 0x0000000000000000 0x00007FFA66A9B570 0x0000000000000000)
0x00007FF66E0F1395 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF66E0F14C8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA66A97614 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA675E26A1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (7714059, based on r416183c1) clang version 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
Target: armv7a-unknown-linux-android22
Thread model: posix
InstalledDir: C:/Program Files/Unity/Editors/2022.2.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:\Users\David\AppData\Local\Temp\Generics22-77481e.cpp
clang++: note: diagnostic msg: C:\Users\David\AppData\Local\Temp\Generics22-77481e.sh
clang++: note: diagnostic msg: 

********************

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

### Affected versions

r23

### Host OS

Windows

### Host OS version

Windows 10 22H2

### Affected ABIs

x86_64

### Build system

ndk-build

### minSdkVersion

26.1.1

### Device API level

32 (target api level)

**Comment by DanAlbert** [comment]
NDK r23 is no longer supported. If the problem recurs with r25 we can reopen, but we will need the information that the error message asked for:

```
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:\Users\David\AppData\Local\Temp\Generics22-77481e.cpp
clang++: note: diagnostic msg: C:\Users\David\AppData\Local\Temp\Generics22-77481e.sh
clang++: note: diagnostic msg:
```
