### ISSUE TITLE
[BUG] R22 ndk-build has native crash Not enough stack information

### ISSUE THREAD

**Issue by baneyue** [android/ndk#1850]
### Description

After the application runs for a period of time, a thread is killed, which leads to the application being killed.

An error of 0xb8 memory address is always reported on the MTK tablet android12, but no more exception stack information can be found. Observe that CPU and memory usage are normal.

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'LIANSHI/T101/T101:12/SP1A.210812.016/mp1V824:userdebug/test-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2023-03-08 16:04:22.508886081+0800
Process uptime: 0s
Cmdline: com.allynav.precisionag
pid: 3214, tid: 3283, name: pool-2-thread-2  >>> com.allynav.precisionag <<<
uid: 10062
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb8
Cause: null pointer dereference
    r0  00000000  r1  131a9d50  r2  00000000  r3  e39bace8
    r4  00000000  r5  00000000  r6  d51da380  r7  d51df098
    r8  00000000  r9  daef8010  r10 133c0658  r11 00000000
    ip  00000000  sp  b507adf0  lr  ba27478f  pc  ba27479a

backtrace:
      #00 pc 0009679a  /data/app/~~WFiBqMNflc9ZTKDWAihqAg==/com.allynav.precisionag-fHQh6CoGEYQESX9wMblwTA==/oat/arm/base.odex (com.allynav.precisionag.Mapvis.MapRefresh.run+1490)
      #01 pc 0030578b  /apex/com.android.art/javalib/arm/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+1002) (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
      #02 pc 002ff74f  /apex/com.android.art/javalib/arm/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+62) (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
      #03 pc 0018b927  /apex/com.android.art/javalib/arm/boot.oat (java.lang.Thread.run+70) (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
      #04 pc 000effd5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 8bca78f465a2249a8e79fd5a76d28b39)
      #05 pc 00502e13  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+282) (BuildId: 8bca78f465a2249a8e79fd5a76d28b39)
      #06 pc 001451a1  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136) (BuildId: 8bca78f465a2249a8e79fd5a76d28b39)
      #07 pc 00401ccd  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+368) (BuildId: 8bca78f465a2249a8e79fd5a76d28b39)
      #08 pc 00401ddb  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+42) (BuildId: 8bca78f465a2249a8e79fd5a76d28b39)
      #09 pc 0044114b  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+998) (BuildId: 8bca78f465a2249a8e79fd5a76d28b39)
      #10 pc 000804c7  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: a6bf7aae36b9c571897e9391e99e49e8)
      #11 pc 00039745  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: a6bf7aae36b9c571897e9391e99e49e8)

memory near r1 ([anon:dalvik-main space (region space)]):
    131a9d30 00000000 00000000 00000000 00000000  ................
    131a9d40 00000000 00000000 00000000 00000000  ................
    131a9d50 d522dc08 00000000 73b96eec 41143c6d  .."......n.sm<.A
    131a9d60 f835223b 414a501b 00000000 00000000  ;"5..PJA........
    131a9d70 00000000 00000000 00000000 00000000  ................
    131a9d80 00000000 00000000 00000000 00000000  ................
    131a9d90 d5218478 00000000 5ddaf409 410950c1  x.!........].P.A
    131a9da0 910e5fc7 41081877 b19a2e44 414a533d  ._..w..AD...=SJA
    131a9db0 385fc267 414a537e d5218478 00000000  g._8~SJAx.!.....
    131a9dc0 910e5fc7 41081877 5ddaf409 410950c1  ._..w..A...].P.A
    131a9dd0 385fc267 414a537e b19a2e44 414a533d  g._8~SJAD...=SJA
    131a9de0 d5218478 00000000 5ddaf409 410950c1  x.!........].P.A
    131a9df0 910e5fc7 41081877 b19a2e44 414a533d  ._..w..AD...=SJA
    131a9e00 385fc267 414a537e d5218478 00000000  g._8~SJAx.!.....
    131a9e10 910e5fc7 41081877 5ddaf409 410950c1  ._..w..A...].P.A
    131a9e20 385fc267 414a537e b19a2e44 414a533d  g._8~SJAD...=SJA

memory near r3 (/apex/com.android.art/lib/libart.so):
    e39bacc0 e9bc95b0 e9bca540 e9bc96d0 e9bc7e70  ....@.......p~..
    e39bacd0 e9bc8650 e9bca3f0 e9bca1b0 e9bc9bb0  P...............
    e39bace0 e9bc98b0 e9b94cf0 e9bca660 e9bc86b0  .....L..`.......
    e39bacf0 e9bca060 e9bc8500 00000000 e9bca030  `...........0...
    e39bad00 e9bc9f40 e9bc98e0 e9bca5a0 e9bca120  @........... ...
    e39bad10 e9b94db0 e9b94dbc e9b94dc0 00000000  .M...M...M......
    e39bad20 00000000 00000000 00000000 00000000  ................
    e39bad30 00000000 00000000 00000000 00000000  ................
    e39bad40 00000000 00000000 e9b958b0 e9b958b8  .........X...X..
    e39bad50 e9b958b8 00000000 00000000 00000000  .X..............
    e39bad60 e9f919a1 fffbfeff 1c000804 ea007cac  .............|..
    e39bad70 00000001 315d6278 00001000 00001000  ....xb]1........
    e39bad80 ffffffff 00200000 00000000 00000000  ...... .........
    e39bad90 00000000 00000000 00000000 00000000  ................
    e39bada0 00000000 00000000 00000000 00000000  ................
    e39badb0 00000000 00000000 00000000 00000000  ................

memory near r6 ([anon:dalvik-/data/app/~~WFiBqMNflc9ZTKDWAihqAg==/com.allynav.precisionag-fHQh6CoGEYQESX9wMblwTA==/oat/arm/base.art]):
    d51da360 70195ce4 70195cfc 70195d14 70195d2c  .\.p.\.p.].p,].p
    d51da370 70195d44 d5313950 13545a48 00000000  D].pP91.HZT.....
    d51da380 7002d5c8 20000000 133d3dc0 00000000  ...p... .==.....
    d51da390 d51d20f8 00000000 70034f70 00000000  . ......pO.p....
    d51da3a0 7002c1a8 00000000 d5290274 00000000  ...p....t.).....
    d51da3b0 d5313968 00000000 d5290230 00000000  h91.....0.).....
    d51da3c0 00080001 00000000 00000198 00000c8e  ................
    d51da3d0 00000cec 00001516 00000019 00000004  ................
    d51da3e0 00000085 00000088 00020000 01ffffff  ................
    d51da3f0 f0000000 0006003d 00000042 701b0fbc  ....=...B......p
    d51da400 70195c54 70195c6c 70195c84 70195c9c  T\.pl\.p.\.p.\.p
    d51da410 70195cb4 70195ccc 70195ce4 70195cfc  .\.p.\.p.\.p.\.p
    d51da420 70195d14 70195d2c 70195d44 d53139fc  .].p,].pD].p.91.
    d51da430 d5313a14 d5313a2c d5313a44 d5313a5c  .:1.,:1.D:1.\:1.
    d51da440 d5313a74 d5313a8c d5313aa4 d5313abc  t:1..:1..:1..:1.
    d51da450 d5313ad4 d5313aec d5313b04 d5313b1c  .:1..:1..;1..;1.

memory near r7 ([anon:dalvik-/data/app/~~WFiBqMNflc9ZTKDWAihqAg==/com.allynav.precisionag-fHQh6CoGEYQESX9wMblwTA==/oat/arm/base.art]):
    d51df070 70195c84 70195c9c 70195cb4 70195ccc  .\.p.\.p.\.p.\.p
    d51df080 70195ce4 70195cfc 70195d14 70195d2c  .\.p.\.p.].p,].p
    d51df090 70195d44 135499a0 7002d5c8 20000000  D].p..T....p... 
    d51df0a0 133d3dc0 00000000 d51d20f8 00000000  .==...... ......
    d51df0b0 70034f70 00000000 7002c1a8 00000000  pO.p.......p....
    d51df0c0 00000000 00000000 d5315168 00000000  ........hQ1.....
    d51df0d0 d529cfa8 00000000 00080001 00000001  ..).............
    d51df0e0 000000e6 00000c8e 00000f92 00001c7b  ............{...
    d51df0f0 00000000 0000000c 00000008 00000008  ................
    d51df100 00020000 00000000 f0000000 00180018  ................
    d51df110 0000000b 701b0fbc 70195c54 70195c6c  .......pT\.pl\.p
    d51df120 70195c84 70195c9c 70195cb4 70195ccc  .\.p.\.p.\.p.\.p
    d51df130 70195ce4 70195cfc 70195d14 70195d2c  .\.p.\.p.].p,].p
    d51df140 70195d44 700c6978 700c6978 135499d0  D].pxi.pxi.p..T.
    d51df150 133d8a00 00000000 700c6978 00000000  ..=.....xi.p....
    d51df160 133d8ab8 00000000 13543d90 700c6978  ..=......=T.xi.p

memory near r9 ([anon:scudo:primary]):
    daef7ff0 00000000 00000000 00000000 00000000  ................
    daef8000 00db0d28 bf7e0000 00000000 00000000  (.....~.........
    daef8010 00430000 00000000 0000002d 00000cd3  ..C.....-.......
    daef8020 00000000 00000000 00000000 00000000  ................
    daef8030 00000000 00000000 00000000 00000000  ................
    daef8040 00000000 00000000 00000001 00000001  ................
    daef8050 00000000 00000000 00000000 00000001  ................
    daef8060 00000000 00000000 00000000 00000000  ................
    daef8070 00000000 00000000 00000000 00000000  ................
    daef8080 00000000 00000000 00000000 00000000  ................
    daef8090 00000000 00000000 00000000 00000000  ................
    daef80a0 00000000 00000000 de5bf070 00000000  ........p.[.....
    daef80b0 b4f7a000 b507ad60 b507b048 00000000  ....`...H.......
    daef80c0 00000000 e3f2df00 00000000 00000000  ................
    daef80d0 133c0080 00000000 b4f78000 001031c0  ..<..........1..
    daef80e0 00000000 00000000 00000000 00000000  ................

memory near r10 ([anon:dalvik-main space (region space)]):
    133c0630 00000000 00000000 00000000 00000000  ................
    133c0640 00000013 00000000 00000000 00000000  ................
    133c0650 00000001 00000000 d521ada0 00000000  ..........!.....
    133c0660 00000000 13558848 133d3dc0 70039830  ....H.U..==.0..p
    133c0670 00000000 13558850 13558858 13558860  ....P.U.X.U.`.U.
    133c0680 00000000 00000000 00000000 00000000  ................
    133c0690 00000000 00000005 00000000 00000000  ................
    133c06a0 00000000 00000000 00000000 00000000  ................
    133c06b0 00000000 00000000 00000045 00000000  ........E.......
    133c06c0 00000000 00000000 00000000 01000000  ................
    133c06d0 13625c18 13625cd8 13625b98 13625bd8  .\b..\b..[b..[b.
    133c06e0 13623d58 13624058 13624018 136244f0  X=b.X@b..@b..Db.
    133c06f0 135583c0 13549b20 133c1978 135583e0  ..U. .T.x.<...U.
    133c0700 133d8d28 00000000 00000000 13558408  (.=...........U.
    133c0710 00000000 133dc9e8 13624098 133d8df0  ......=..@b...=.
    133c0720 13558420 13549b08 133c02d8 13558440   .U...T...<.@.U.

memory near sp ([anon:stack_and_tls:3283]):
    b507add0 70ecbfcc 00000000 00000006 133c08a0  ...p..........<.
    b507ade0 133d8be8 00000000 d51da380 ba27476f  ..=.........oG'.
    b507adf0 d52c7f78 13558458 13623d18 00000000  x.,.X.U..=b.....
    b507ae00 00000014 00000000 00000000 00000000  ................
    b507ae10 00000000 00000010 133c08a0 131a9d50  ..........<.P...
    b507ae20 d51da380 13625c18 13621940 c03ff168  .....\b.@.b.h.?.
    b507ae30 00000186 00000002 00000000 1241229d  ............."A.
    b507ae40 3fd360c9 00000000 00000000 00000000  .`.?............
    b507ae50 00000000 00000000 00000000 00000000  ................
    b507ae60 00000000 00000000 00000000 00000000  ................
    b507ae70 00000000 00000000 00000000 00000000  ................
    b507ae80 00000000 00000000 00000000 00000000  ................
    b507ae90 00000000 00000000 00000000 00000000  ................
    b507aea0 133c0908 133c0080 133c08c0 7056e78d  ..<...<...<...Vp
    b507aeb0 7017e7c8 133c0658 00000000 00000000  ...pX.<.........
    b507aec0 00000000 00000000 00000000 133c0658  ............X.<.

memory near lr (/data/app/~~WFiBqMNflc9ZTKDWAihqAg==/com.allynav.precisionag-fHQh6CoGEYQESX9wMblwTA==/oat/arm/base.odex):
    ba274760 0017f2c0 68004478 e014f8d0 f20f47f0  ....xD.h.....G..
    ba274770 f1b80e0f f0710f00 f8d7ad03 f20f00b8  ......q.........
    ba274780 f1b80e0f f0700f00 f8d0ae9f 910b1020  ......p..... ...
    ba274790 0b12ed90 0b42ed8a f8d06808 f8d000b8  ......B..h......
    ba2747a0 47f0e014 0080f8ca f8d9b120 ea4f1098  ...G.... .....O.
    ba2747b0 5489229a 0e0df20f 0f00f1b8 ace0f071  .".T........q...
    ba2747c0 00b8f8d7 0e0bf20f 0f00f1b8 ad74f071  ............q.t.
    ba2747d0 910b6941 f8d06808 f8d000b8 47f0e014  Ai...h.........G
    ba2747e0 114ff89a 0084f8ca f8d9b120 ea4f2098  ..O..... .... O.
    ba2747f0 54d2239a f0402900 f20f8010 f1b80e0f  .#.T.)@.........
    ba274800 f0710f00 f8d7acbd f20f00b8 f1b80e0d  ..q.............
    ba274810 f0710f00 68c1ad51 f20fe00e f1b80e0f  ..q.Q..h........
    ba274820 f0710f00 f8d7acad f20f00b8 f1b80e0d  ..q.............
    ba274830 f0710f00 6941ad41 6808910b 00b8f8d0  ..q.A.Ai...h....
    ba274840 e014f8d0 f8ca47f0 b1200078 1098f8d9  .....G..x. .....
    ba274850 229aea4f f20f5489 f1b80e0f f0710f00  O..".T........q.

memory near pc (/data/app/~~WFiBqMNflc9ZTKDWAihqAg==/com.allynav.precisionag-fHQh6CoGEYQESX9wMblwTA==/oat/arm/base.odex):
    ba274770 f1b80e0f f0710f00 f8d7ad03 f20f00b8  ......q.........
    ba274780 f1b80e0f f0700f00 f8d0ae9f 910b1020  ......p..... ...
    ba274790 0b12ed90 0b42ed8a f8d06808 f8d000b8  ......B..h......
    ba2747a0 47f0e014 0080f8ca f8d9b120 ea4f1098  ...G.... .....O.
    ba2747b0 5489229a 0e0df20f 0f00f1b8 ace0f071  .".T........q...
    ba2747c0 00b8f8d7 0e0bf20f 0f00f1b8 ad74f071  ............q.t.
    ba2747d0 910b6941 f8d06808 f8d000b8 47f0e014  Ai...h.........G
    ba2747e0 114ff89a 0084f8ca f8d9b120 ea4f2098  ..O..... .... O.
    ba2747f0 54d2239a f0402900 f20f8010 f1b80e0f  .#.T.)@.........
    ba274800 f0710f00 f8d7acbd f20f00b8 f1b80e0d  ..q.............
    ba274810 f0710f00 68c1ad51 f20fe00e f1b80e0f  ..q.Q..h........
    ba274820 f0710f00 f8d7acad f20f00b8 f1b80e0d  ..q.............
    ba274830 f0710f00 6941ad41 6808910b 00b8f8d0  ..q.A.Ai...h....
    ba274840 e014f8d0 f8ca47f0 b1200078 1098f8d9  .....G..x. .....
    ba274850 229aea4f f20f5489 f1b80e0f f0710f00  O..".T........q.
    ba274860 f8d7ac8f f89000b8 ed9010b2 f88a0b0e  ................

memory map (2926 entries):
    0863a000-0863bfff r--         0      2000  /system/bin/app_process32 (BuildId: bd709f4905874e15ceb6fd4946d0f1fe) (load bias 0x1000)
    0863c000-0863cfff r-x      1000      1000  /system/bin/app_process32 (BuildId: bd709f4905874e15ceb6fd4946d0f1fe) (load bias 0x1000)
    0863d000-0863dfff r--      1000      1000  /system/bin/app_process32 (BuildId: bd709f4905874e15ceb6fd4946d0f1fe) (load bias 0x1000)
    12c00000-32bfffff rw-         0  20000000  [anon:dalvik-main space (region space)]
    7002c000-701edfff rw-         0    1c2000  [anon:dalvik-/apex/com.android.art/javalib/boot.art]
    701ee000-7021ffff rw-         0     32000  [anon:dalvik-/apex/com.android.art/javalib/boot-core-libart.art]
    70220000-7023cfff rw-         0     1d000  [anon:dalvik-/apex/com.android.art/javalib/boot-okhttp.art]
    7023d000-70267fff rw-         0     2b000  [anon:dalvik-/apex/com.android.art/javalib/boot-bouncycastle.art]
    70268000-70268fff rw-         0      1000  [anon:dalvik-/apex/com.android.art/javalib/boot-apache-xml.art]
    70269000-7030ffff r--         0     a7000  /apex/com.android.art/javalib/arm/boot.oat (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
    70310000-705e9fff r-x     a7000    2da000  /apex/com.android.art/javalib/arm/boot.oat (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
    705ea000-705eafff rw-         0      1000  [anon:.bss]
    705eb000-705f6fff rw-         0      c000  /apex/com.android.art/javalib/arm/boot.vdex
    705f7000-705f7fff r--    381000      1000  /apex/com.android.art/javalib/arm/boot.oat (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
    705f8000-705f8fff rw-    382000      1000  /apex/com.android.art/javalib/arm/boot.oat (BuildId: 2cd7440154ca1b41e380e616d3ea27e64d984662)
    705f9000-70606fff r--         0      e000  /apex/com.android.art/javalib/arm/boot-core-libart.oat (BuildId: 65bf5861deba9045b97349963377ce87ac0b567c)
    70607000-70641fff r-x      e000     3b000  /apex/com.android.art/javalib/arm/boot-core-libart.oat (BuildId: 65bf5861deba9045b97349963377ce87ac0b567c)
    70642000-70642fff rw-         0      1000  [anon:.bss]
    70643000-70644fff rw-         0      2000  /apex/com.android.art/javalib/arm/boot-core-libart.vdex
    70645000-70645fff r--     49000      1000  /apex/com.android.art/javalib/arm/boot-core-libart.oat (BuildId: 65bf5861deba9045b97349963377ce87ac0b567c)
    70646000-70646fff rw-     4a000      1000  /apex/com.android.art/javalib/arm/boot-core-libart.oat (BuildId: 65bf5861deba9045b97349963377ce87ac0b567c)
    70647000-70653fff r--         0      d000  /apex/com.android.art/javalib/arm/boot-okhttp.oat (BuildId: 82eaebee44a13c4e75d303131c06012b04e3b66a)
    70654000-70683fff r-x      d000     30000  /apex/com.android.art/javalib/arm/boot-okhttp.oat (BuildId: 82eaebee44a13c4e75d303131c06012b04e3b66a)
    70684000-70684fff rw-         0      1000  [anon:.bss]
    70685000-70685fff rw-         0      1000  /apex/com.android.art/javalib/arm/boot-okhttp.vdex
    70686000-70686fff r--     3d000      1000  /apex/com.android.art/javalib/arm/boot-okhttp.oat (BuildId: 82eaebee44a13c4e75d303131c06012b04e3b66a)
    70687000-70687fff rw-     3e000      1000  /apex/com.android.art/javalib/arm/boot-okhttp.oat (BuildId: 82eaebee44a13c4e75d303131c06012b04e3b66a)
    70688000-7068efff r--         0      7000  /apex/com.android.art/javalib/arm/boot-bouncycastle.oat (BuildId: 71ab03c58e724c900971e8e38c0eb04b5425455c)
    7068f000-7069dfff r-x      7000      f000  /apex/com.android.art/javalib/arm/boot-bouncycastle.oat (BuildId: 71ab03c58e724c900971e8e38c0eb04b5425455c)
    7069e000-7069efff rw-         0      1000  [anon:.bss]
    7069f000-706a4fff rw-         0      6000  /apex/com.android.art/javalib/arm/boot-bouncycastle.vdex
    706a5000-706a5fff r--     16000      1000  /apex/com.android.art/javalib/arm/boot-bouncycastle.oat (BuildId: 71ab03c58e724c900971e8e38c0eb04b5425455c)
    706a6000-706a6fff rw-     17000      1000  /apex/com.android.art/javalib/arm/boot-bouncycastle.oat (BuildId: 71ab03c58e724c900971e8e38c0eb04b5425455c)
    706a7000-706a9fff r--         0      3000  /apex/com.android.art/javalib/arm/boot-apache-xml.oat (BuildId: c2f6c2670cd1328bb9ecae24d2dd5aaf79b5729f)
    706aa000-706acfff rw-         0      3000  /apex/com.android.art/javalib/arm/boot-apache-xml.vdex
    706ad000-706adfff r--      3000      1000  /apex/com.android.art/javalib/arm/boot-apache-xml.oat (BuildId: c2f6c2670cd1328bb9ecae24d2dd5aaf79b5729f)
    706ae000-706aefff rw-      4000      1000  /apex/com.andr

### Affected versions

r23

### Canary version

22

### Host OS

Linux

### Host OS version

Ubuntu

### Affected ABIs

armeabi-v7a

### Build system

ndk-build

### Other build system

android12 mtk tablet

### minSdkVersion

21

### Device API level

31

**Comment by DanAlbert** [comment]
Am I overlooking the relevant part of the stack trace? I can't figure out what this bug has to do with the NDK. That's a Java crash, isn't it?

**Comment by baneyue** [comment]
not java crash，when run app app on android12 , it happen.

This is a java thread that operates the jni method in the thread. When the application runs for a period of time and the time is not fixed, this thread will be killed by the system, and then the application will crash. When I remove the part of the thread that operates jni, there will be no crash. And it only appears on android12. It crashes three times a day. The error always indicates 0xb8000000, and the available native stack information cannot be found.

**Comment by baneyue** [comment]
> Am I overlooking the relevant part of the stack trace? I can't figure out what this bug has to do with the NDK. That's a Java crash, isn't it?

not java crash，when run app app on android12 , it happen.

This is a java thread that operates the jni method in the thread. When the application runs for a period of time and the time is not fixed, this thread will be killed by the system, and then the application will crash. When I remove the part of the thread that operates jni, there will be no crash. And it only appears on android12. It crashes three times a day. The error always indicates 0xb8000000, and the available native stack information cannot be found.

**Comment by DanAlbert** [comment]
> The error always indicates 0xb8000000

No, that's 0x000000b8. The null page. The crash dump says:

> Cause: null pointer dereference

Your app's Java code is for some reason indexing into a null reference. The normal reason for that is memory corruption. If changing your native code is causing Java to crash, you've probably got a memory bug somewhere that's writing off the end of a buffer and corrupting some memory used by Java. If your native code overwrote a Java reference to be null and then you tried to access that object's data, this is what that would look like.

Without a repro case there's really nothing else we can do here. There's nothing provided that gives us a place to start investigating. I've asked someone to look that might be able to tell you if the stack trace is representative of a common problem, but failing that, if all we have is a Java stack trace there's nothing we can do.

https://developer.android.com/ndk/guides/asan might help you find the source of the memory bug.
