### ISSUE TITLE
[FR] Include `clang-scan-deps` in the ndk

### ISSUE THREAD

**Issue by yujincheng08** [android/ndk#1853]
### Description

Since llvm-16 now supports `p1689`, if `clang-scan-deps` is included in the ndk, we can use c++ modules with a newer version of cmake (say 3.26+).

**Comment by DanAlbert** [comment]
This is already in the next compiler, it just hasn't shipped yet.

**Comment by rnikander** [comment]
When is NDK r27 going to be released?

**Comment by DanAlbert** [comment]
https://github.com/android/ndk/wiki#ndk-r27
