### ISSUE TITLE
[Bug]: Miscompilation on armv7 with NDK r25c

### ISSUE THREAD

**Issue by ngg** [android/ndk#1860]
### Description

When we tried to switch from NDK r24 to r25c, our application has started to crash when compiled to armv7.

Unfortunately, I couldn't easily minimize our code to submit it here, but I managed to reproduce the same crash on armv7 Linux using upstream clang 15.0.7. Updating clang to 16.0.1 solved the crash, so I bisected the llvm-project repo to find that the necessary commit for the fix is https://github.com/llvm/llvm-project/commit/8a09875dd1e55f1920e58b7a01f380ef35465636. The fix itself is not armv7 specific, I assume it can cause problems on any platform.

I found a discussion here https://discourse.llvm.org/t/instcombine-struct-w-padding-aggregate-loads-stores-as-scalars/67035/5 that describes the issue and has small testcases that can reproduce the miscompilation, but on CUDA target. I don't have a small isolated testcase for Android, I hope the information I'm providing here is enough.

I tried to cherry-pick the commit onto https://github.com/llvm/llvm-project/commit/282c83c32384cb2f37030c28650fef4150a8b67c which clang-r450784d1 is based on which is included in NDK r25c, there is a conflict in the test case that this fix modifies but the fix itself in llvm/lib/Analysis/InstructionSimplify.cpp is ok and works, it no longer crashes.

Please cherry-pick the https://github.com/llvm/llvm-project/commit/8a09875dd1e55f1920e58b7a01f380ef35465636 commit into the next NDK release.

### Upstream bug

https://github.com/llvm/llvm-project/issues/59156

### Commit to cherry-pick

https://github.com/llvm/llvm-project/commit/8a09875dd1e55f1920e58b7a01f380ef35465636

### Affected versions

r25

### Host OS

Linux

### Host OS version

Debian 11

### Affected ABIs

armeabi-v7a

**Comment by DanAlbert** [comment]
I don't think we're going to be doing an r25d, so we'll get this "for free" when we update the compiler in r26. Leaving this open since we don't actually have a newer working compiler for r26 yet.

**Comment by DanAlbert** [comment]
Oh, and thanks for the detailed investigation :) That saves us a ton of time.
