### ISSUE TITLE
[Bug]: Frontend failed with exit code 139

### ISSUE THREAD

**Issue by A248** [android/ndk#1861]
### Description

Please clone this gitlab repository
https://gitlab.com/blackberry-savior/sipdroid/-/tree/d2044a74f5e92429649c9157adc1cdee21b3a9ab

Run `./gradlew clean build`. The result is that `clang frontend failed with exit code 139` and this stacktrace:
https://pastebin.com/ZxAZ7irg

Here are the relevant files mentioned in the stacktrace:
[/tmp/gsm0610_lpc-93e495.c](https://github.com/android/ndk/files/11182051/tmp__gsm0610_lpc-93e495.c.txt) (attached because it is very large)
[/tmp/gsm0610_lpc-93e495.sh](https://pastebin.com/1uGk9Uga) (pastebin)

### Affected versions

r23, r25

### Host OS

Linux

### Host OS version

PureOS 10 (Byzantium)

### Affected ABIs

armeabi-v7a

**Comment by pirama-arumuga-nainar** [comment]
This is broken in the `r25` compiler but is fixed in the `r26` compiler.  The fix is below.  We can respin the toolchain with this fix for the next point release of `r25`, if any.

```
commit 447c411fef6ed97a404087cc8289aeeb02a8ae5c
Author: Sam Parker <sam.parker@arm.com>
Date:   Thu Jun 9 08:41:44 2022 +0000

    [ARM][ParallelDSP] Fix self reference bug
    
    Ensure we don't generate a smlad intrinsic that takes itself as an
    argument.
    
    Differential Revision: https://reviews.llvm.org/D127213

```
