### ISSUE TITLE
[FR] NativeActivity window decorations

### ISSUE THREAD

**Issue by vasekp** [android/ndk#1863]
### Description

NativeActivity seems to be targetting full-screen apps, taking over the entire Window's surface, but this may not be what a developer wants. In a desktop environment (tested with Android Emulator, Android 12L Desktop), for example, this results in the application having no window decorations (minimize, maximize, close etc.), simply covering a rectangle area from corner to corner instead. This is unaesthetic and inconsistent with the rest of the ecosystem, however, being a hardcoded behaviour, there seems not to be any way around it, short of developing a full-featured version of NativeActivity of one's own. This avenue is further complicated by android.app.NativeActivity using some non-exposed API for its internal functionality.

I would like my application to run in a window, and only render to the content rectangle left after drawing all usual window decorations, as if the surface passed to C++ was not taken from the entire window but only a SurfaceView covering its user area. Can this perhaps be made an optional – or even default – behaviour of NativeActivity? Alternatively, what are my other options to reach this goal?

For reference, here is the official demo sample launched in Android 12L desktop (blue rectangle in the middle of screen), along with two system applications. There is no obvious way to move or close the window, let alone minimize or maximize it.
![obrazek](https://user-images.githubusercontent.com/11852447/231218446-0725c02c-0db4-483a-bcfe-22c5c5cc5ee2.png)

**Comment by DanAlbert** [comment]
`NativeActivity` is part of the framework, so this should follow 
![image](https://user-images.githubusercontent.com/315852/231260567-0d4970c4-0d39-4478-9dc1-047cde07d7ac.png)

Use the framework component.

We're not app developers, so we can't really offer any advice here. It sounds like you already know more than I do.

**Comment by vasekp** [comment]
Oh, I understood the instruction at that link as sending me here! OK, will give it another try.

**Comment by DanAlbert** [comment]
Oh, is _that_ why so many people end up filing bugs here? Going in a circle? I just pushed an update to that description that should hopefully help with that:

![image](https://user-images.githubusercontent.com/315852/231265676-7f2de7cc-d21b-41ae-aeec-a3384242faa4.png)

**Comment by DanAlbert** [comment]
I also just sent an update to b.android.com so that advice is present on both ends, but that'll take longer to show up online.
