### ISSUE TITLE
[BUG] C/C++: CMake Error: The source directory ... does not exist.

### ISSUE THREAD

**Issue by ShootingKing-AM** [android/ndk#1872]
### Description

When building ndk with r25c, CMake gives a `C/C++: CMake Error: The source directory "/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/""" does not exist.`

```java
C/C++: CMake Error: The source directory "/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/""" does not exist.
Execution failed for task ':app:configureCMakeDebug[armeabi-v7a]'.
C/C++: Specify --help for usage, or press the help button on the CMake GUI.
> [CXX1429] error when building with cmake using /home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/CMakeLists.txt: C++ build system [configure] failed while executing:

      /usr/local/lib/android/sdk/cmake/3.22.1/bin/cmake \
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
        -H/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app \

        -DCMAKE_SYSTEM_NAME=Android \
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \

        -DCMAKE_SYSTEM_VERSION=24 \
See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
        -DANDROID_PLATFORM=android-24 \
27 actionable tasks: 12 executed, 15 up-to-date
        -DANDROID_ABI=armeabi-v7a \
        -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
        -DANDROID_NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653 \
        -DCMAKE_ANDROID_NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653 \
        -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/usr/local/lib/android/sdk/cmake/3.22.1/bin/ninja \
        "-DCMAKE_CXX_FLAGS=-std=c++17 -fexceptions -frtti -D_DEBUG=1" \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/build/intermediates/cxx/Debug/6x543a17/obj/armeabi-v7a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/build/intermediates/cxx/Debug/6x543a17/obj/armeabi-v7a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/.cxx/Debug/6x543a17/armeabi-v7a \
        -GNinja \
    from /home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app
  CMake Error: The source directory "/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/""" does not exist.
  Specify --help for usage, or press the help button on the CMake GUI.
```
CI: https://github.com/ShootingKing-AM/PhoneVR/actions/runs/4789821517/jobs/8518144941#step:9:266
CMakeFile: https://github.com/ShootingKing-AM/PhoneVR/blob/ab750209d9191f53842230848d09a362eedf50fa/code/mobile/android/PhoneVR/app/CMakeLists.txt

Erroring Starts from CMake >= v3.18
Erroring only on *nix systems, windows-images in github-actions-CI as well as local builds are fine

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu github-actions latest

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

24

**Comment by DanAlbert** [comment]
This appears to be either a CMake bug or an AGP bug, neither or which is part of the NDK. Does this really only happen with r25?

**Comment by ShootingKing-AM** [comment]
Yes, it also happens with '25.1.8937393'. One more frustrating thing is its only happens with CI, I can build locally on Android Studio with both ndks.

There is clearly something weird going on with the cmake inputs ` "/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/""" `, Last three `"`. I thought that path would be routed though ndk/toolchain file to gradle (idk?)

Updated both AGP and gradle to lastest stable, still can build locally in all configs but not on CI. ( 1.6.x -> 1.7.x, 7.5 -> 8.1.1, respectively)

Any clues on how do I downgrade cmake version ? 3.22.x to something older ?

**Comment by DanAlbert** [comment]
> There is clearly something weird going on with the cmake inputs "/home/runner/work/PhoneVR/PhoneVR/code/mobile/android/PhoneVR/app/""", Last three ". I thought that path would be routed though ndk/toolchain file to gradle (idk?)

I'm fairly certain the error is happening before you even get that far. In any case, the toolchain file does not manipulate it. `grep -r CMAKE_SOURCE ~/Library/Android/sdk/ndk/25.2.9519653/build/cmake` finds nothing.

> Any clues on how do I downgrade cmake version ? 3.22.x to something older ?

https://developer.android.com/studio/projects/install-ndk#vanilla_cmake

**Comment by ShootingKing-AM** [comment]
Gradle seems to download and use 3.22.x always, even if there is a different cmake specified. The cmake.version seems not being applied.

**Comment by ShootingKing-AM** [comment]
WHAT !? This would have been the last thing I would check.
Seems like AGP is buggy.

It worked thanks ! 🙏

**Comment by DanAlbert** [comment]
Please file that AGP bug.
