### ISSUE TITLE
[BUG]clang++: error: clang frontend command failed with exit code 139

### ISSUE THREAD

**Issue by gcd0318** [android/ndk#1891]
### Description

error when building android on docker

[ 61% 81002/131658] //hardware/interfaces/power/stats/1.0:android.hardware.power.stats@1.0 clang
FAILED: out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0/android_arm64_armv8-a_static/obj/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.o
PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++ -c  -Werror=implicit-function-declaration -DANDROID -DANDROID_12 -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wunreachable-code-loop-increment -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fdebug-info-for-profiling -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=string-plus-int -Werror=unreachable-code-loop-increment -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-gnu-folding-constant -Wunguarded-availability -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -march=armv8-a  -target aarch64-linux-android10000 -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIC -Wsign-promo -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -Ihardware/interfaces/power/stats/1.0 -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Isystem/libhidl/base/include -Isystem/libhidl/transport/include -Isystem/libfmq/base -Isystem/libhwbinder/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libutils/include -Isystem/unwinding/libbacktrace/include -Isystem/logging/liblog/include -Isystem/core/libsystem/include -Isystem/core/libcutils/include -Isystem/core/libprocessgroup/include -Iout/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.1/android.hidl.manager@1.1_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager@1.2_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen -Ibionic/libc/async_safe/include -Ibionic/libc/system_properties/include -Isystem/core/property_service/libpropertyinfoparser/include -Iout/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen -Iout/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++_headers/gen -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -Wall -Werror -Wextra-semi -D__ANDROID_DEBUGGABLE__ -DDO_NOT_CHECK_MANUAL_BINDER_INTERFACES -std=gnu++17 -fno-rtti -Isystem/core/include -Isystem/logging/liblog/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include  -Werror=bool-operation -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=string-compare -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-string-concatenation -MD -MF 'out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0/android_arm64_armv8-a_static/obj/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.o'.d -o 'out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0/android_arm64_armv8-a_static/obj/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.o' 'out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.cpp'
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real -c -Werror=implicit-function-declaration -DANDROID -DANDROID_12 -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wunreachable-code-loop-increment -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fdebug-info-for-profiling -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=string-plus-int -Werror=unreachable-code-loop-increment -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-gnu-folding-constant -Wunguarded-availability -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -march=armv8-a -target aarch64-linux-android10000 -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIC -Wsign-promo -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden -Ihardware/interfaces/power/stats/1.0 -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Isystem/libhidl/base/include -Isystem/libhidl/transport/include -Isystem/libfmq/base -Isystem/libhwbinder/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libutils/include -Isystem/unwinding/libbacktrace/include -Isystem/logging/liblog/include -Isystem/core/libsystem/include -Isystem/core/libcutils/include -Isystem/core/libprocessgroup/include -Iout/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.1/android.hidl.manager@1.1_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager@1.2_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen -Ibionic/libc/async_safe/include -Ibionic/libc/system_properties/include -Isystem/core/property_service/libpropertyinfoparser/include -Iout/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen -Iout/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++_headers/gen -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -Wall -Werror -Wextra-semi -D__ANDROID_DEBUGGABLE__ -DDO_NOT_CHECK_MANUAL_BINDER_INTERFACES -std=gnu++17 -fno-rtti -Isystem/core/include -Isystem/logging/liblog/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include -Werror=bool-operation -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=string-compare -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-string-concatenation -MD -MF out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0/android_arm64_armv8-a_static/obj/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.o.d -o out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0/android_arm64_armv8-a_static/obj/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.o out/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++/gen/android/hardware/power/stats/1.0/PowerStatsAll.cpp
 #0 0x0000000003fba0e8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x3fba0e8)
 #1 0x0000000003fb9f70 llvm::sys::RunSignalHandlers() (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x3fb9f70)
 #2 0x0000000003f86c53 (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x3f86c53)
 #3 0x0000000003f86e51 (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x3f86e51)
 #4 0x00007f686364c390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #5 0x00000000022975e0 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e0)
 #6 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
 #7 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
 #8 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
 #9 0x00000000022975f4 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975f4)
#10 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
#11 0x00000000022975f4 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975f4)
#12 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
#13 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
#14 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
#15 0x00000000022975f4 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975f4)
#16 0x00000000022975e8 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975e8)
#17 0x00000000022975f4 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975f4)
#18 0x00000000022975f4 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975f4)
#19 0x00000000022975f4 std::__1::__tree<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::__map_value_compare<llvm::StringRef, std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, std::__1::less<llvm::StringRef>, true>, std::__1::allocator<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl> > >::destroy(std::__1::__tree_node<std::__1::__value_type<llvm::StringRef, clang::GlobalDecl>, void*>*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x22975f4)
#20 0x00000000034d42f4 clang::CodeGen::CodeGenModule::~CodeGenModule() (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x34d42f4)
#21 0x000000000537d110 (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x537d110)
#22 0x000000000537cd8b (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x537cd8b)
#23 0x00000000032423c5 clang::FrontendAction::EndSourceFile() (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x32423c5)
#24 0x0000000003241add clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x3241add)
#25 0x000000000323f06f clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x323f06f)
#26 0x000000000323d669 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x323d669)
#27 0x00000000038a5de7 (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x38a5de7)
#28 0x0000000005364b82 clang::driver::CC1Command::setEnvironment(llvm::ArrayRef<char const*>) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x5364b82)
#29 0x00000000034faf85 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x34faf85)
#30 0x00000000034fad45 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x34fad45)
#31 0x0000000003310564 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x3310564)
#32 0x0000000002f9a1f1 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x2f9a1f1)
#33 0x0000000002f95312 main (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x2f95312)
#34 0x00007f686274c840 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20840)
#35 0x0000000005283ca9 _start (prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++.real+0x5283ca9)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Android (7485623, based on r416183b1) clang version 12.0.7 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
Target: aarch64-unknown-linux-android10000
Thread model: posix
InstalledDir: prebuilts/clang/host/linux-x86/clang-r416183b1/bin
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /mnt/rock-android12/out/soong/.temp/PowerStatsAll-89fec8.cpp
clang++: note: diagnostic msg: /mnt/rock-android12/out/soong/.temp/PowerStatsAll-89fec8.sh
clang++: note: diagnostic msg:

********************
14:53:30 ninja failed with: exit status 1

### Affected versions

r23

### Host OS

Linux

### Host OS version

Linux dc58a1eb345d 6.3.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 May 2023 16:15:22 +0000 x86_64 x86_64 x86_64 GNU/Linux

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

31

**Comment by gcd0318** [comment]
[PowerStatsAll-89fec8.zip](https://github.com/android/ndk/files/11566566/PowerStatsAll-89fec8.zip)

add scripts as attached

**Comment by DanAlbert** [comment]
r23 hasn't been supported in a long time. Does the crash reproduce with the r26 canary? Or r25c?

**Comment by pirama-arumuga-nainar** [comment]
We have seen several errors when building AOSP that end up being crashes when the system is under memory pressure.  Please re-run reproducer on idle system and see if it fails.

**Comment by gcd0318** [comment]
> 

Yes I'm retrying and really got failure occassionally. and maybe really caused by memory limitation as the error message. But I'm pretty confusing because I'm using an i7 host and 16g RAM

**Comment by pirama-arumuga-nainar** [comment]
Unfortunately, building AOSP on low RAM can cause similar issues.

> At least 16 GB of available RAM is required, but Google recommends 64 GB.

from https://source.android.com/docs/setup/start/requirements#hardware-requirements.
