### ISSUE TITLE
[BUG] Shared library size doubled caused by upgrading NDK from r16b to 25.1.8937393  

### ISSUE THREAD

**Issue by xyz1001** [android/ndk#1893]
### Description

After upgrading NDK from r16b to 25.1.8937393, the shared library size increase from 9.5M to 22M. 
before:
```
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  42.5%  4.03Mi  42.2%  4.03Mi    .text
  17.1%  1.62Mi  17.0%  1.62Mi    .dynstr
   7.2%   695Ki   7.1%   695Ki    .rodata
   6.9%   670Ki   6.8%   670Ki    .rela.dyn
   6.7%   647Ki   6.6%   647Ki    .eh_frame
   4.4%   428Ki   4.4%   428Ki    .gcc_except_table
   4.2%   409Ki   4.2%   409Ki    .dynsym
   2.7%   265Ki   2.7%   265Ki    .data.rel.ro
   1.6%   158Ki   1.6%   158Ki    .rela.plt
   1.6%   156Ki   1.6%   156Ki    .eh_frame_hdr
   1.4%   136Ki   1.4%   136Ki    .hash
   1.2%   115Ki   1.2%   115Ki    .gnu.hash
   1.1%   105Ki   1.1%   105Ki    .plt
   0.0%       0   0.9%  90.1Ki    .bss
   0.5%  52.8Ki   0.5%  52.7Ki    .got.plt
   0.4%  34.2Ki   0.3%  34.2Ki    .gnu.version
   0.2%  21.5Ki   0.2%  21.4Ki    .data
   0.2%  15.7Ki   0.2%  15.6Ki    .got
   0.0%  2.12Ki   0.0%  1.37Ki    [10 Others]
   0.0%  1.34Ki   0.0%  1.28Ki    .init_array
   0.0%     768   0.0%       0    .comment
 100.0%  9.48Mi 100.0%  9.57Mi    TOTAL
```
After
```
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  40.7%  8.74Mi  40.5%  8.74Mi    .text
  21.9%  4.71Mi  21.8%  4.71Mi    .dynstr
  13.4%  2.88Mi  13.3%  2.88Mi    .eh_frame
   3.7%   824Ki   3.7%   824Ki    .dynsym
   3.5%   768Ki   3.5%   768Ki    .eh_frame_hdr
   3.2%   700Ki   3.2%   700Ki    .rodata
   3.1%   688Ki   3.1%   688Ki    .rela.dyn
   2.6%   570Ki   2.6%   570Ki    .rela.plt
   1.7%   380Ki   1.7%   380Ki    .plt
   1.2%   274Ki   1.2%   274Ki    .hash
   1.2%   271Ki   1.2%   271Ki    .data.rel.ro
   1.2%   262Ki   1.2%   262Ki    .gcc_except_table
   1.1%   233Ki   1.1%   233Ki    .gnu.hash
   0.9%   190Ki   0.9%   190Ki    .got.plt
   0.0%       0   0.4%  94.3Ki    .bss
   0.3%  68.7Ki   0.3%  68.7Ki    .gnu.version
   0.1%  21.9Ki   0.1%  21.8Ki    .data
   0.1%  16.1Ki   0.1%  16.0Ki    .got
   0.0%  1.80Ki   0.0%     896    [9 Others]
   0.0%  1.34Ki   0.0%  1.28Ki    .init_array
   0.0%     608   0.0%     544    .dynamic
 100.0%  21.5Mi 100.0%  21.6Mi    TOTAL
```
My project is a JNI wrapper. Main features are implemented by a dozen static libraries. The project link with these static libraries and output a single shared libraries. If I build these static libraries with NDK r16b and build the project with NDK r25, the size would not increase. 

Building with NDK 20.1.5948944 would not increase the size.

I try compare the compile flags, and remove the flags that NDK 25 added. The flags are `-g -DANDROID -fdata-sections -ffunction-sections  -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security`. However, After remove these flags, it only reduced size by 1M.

### Affected versions

r25

### Canary version

25.1.8937393  

### Host OS

Linux

### Host OS version

ArchLinux

### Affected ABIs

armeabi-v7a, arm64-v8a

### Build system

CMake

### minSdkVersion

21

### Device API level

any

**Comment by xyz1001** [comment]
If I only link with few static libraries, little size increase. The more static libraries linked, the more size increase.
NDK r25
Static libraries count  Output so size
4                                   4.4M
6                                   9.7M
12                                  15M
16                                  21M

NDK r20
Static libraries count  Output so size
4                                   4.1M
6                                   6.0M
12                                  7.8M
16                                  9.9M

**Comment by DanAlbert** [comment]
Nothing we can do without a repro case.
