### ISSUE TITLE
[BUG] `iconv_open()` function parameter description error in NDK above `android-ndk-r23`

### ISSUE THREAD

**Issue by th1nk3r-ing** [android/ndk#1895]
### Description

In `android-ndk-r23` and above, the `iconv_open()` parameter description appears to be incorrect  :
```c
// android-ndk-r23/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/iconv.h

/**
 * [iconv_open(3)](http://man7.org/linux/man-pages/man3/iconv_open.3.html) allocates a new converter
 * from `__src_encoding` to `__dst_encoding`.
 *
 * Returns a new `iconv_t` on success and returns `((iconv_t) -1)` and sets `errno` on failure.
 *
 * Available since API level 28.
 */

#if __ANDROID_API__ >= 28
iconv_t iconv_open(const char* __src_encoding, const char* __dst_encoding) __INTRODUCED_IN(28);
#endif
```
But in `man 3 iconv_open`

```c
 #include <iconv.h>

 iconv_t iconv_open (const char* tocode, const char* fromcode);
```

### Affected versions

r23, r24, r25

### Host OS

Mac

### Host OS version

MACOS

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### minSdkVersion

r23

**Comment by enh-google** [comment]
yes, you're correct. i've uploaed https://android-review.googlesource.com/c/platform/bionic/+/2624749 to fix this. thanks for the bug report!

**Comment by DanAlbert** [comment]
(I expect this doesn't need to be cherry-picked and it's fine for it to just roll out to an NDK when we update the sysroot for some other reason, so marking fixed and not triaging to any release. lmk if that's incorrect and this needs to be chased for r26.)

**Comment by enh-google** [comment]
is the icu4c ndk documentation on the web anywhere? probably the most useful thing i could add to the <iconv.h> documentation is making it super clear that it's really just for the various UCS variants, and for anything more esoteric you'll want icu4c... oh, but the `ucnv_*` functions aren't in our subset for some reason. that's unfortunate. any idea why?

**Comment by DanAlbert** [comment]
> oh, but the `ucnv_*` functions aren't in our subset for some reason. that's unfortunate. any idea why?

They're all added as-needed, I believe. You'd have to ask vichang if you want a real answer :)

**Comment by enh-google** [comment]
> > oh, but the `ucnv_*` functions aren't in our subset for some reason. that's unfortunate. any idea why?
> 
> They're all added as-needed, I believe. You'd have to ask vichang if you want a real answer :)

yeah, i had a similar conversation about `ucal_*` with nfuller last week, and he said the same. seems like the wrong way to do it to me, based on how well that philosophy worked for bionic before we inherited it...
