### ISSUE TITLE
[BUG] clang++ got segmentation fault when build AOSP Android 10 

### ISSUE THREAD

**Issue by stevetsai-dev** [android/ndk#1896]
### Description

clang got segmentation fault when build AOSP android 10. From the following message, it suggests to submit a bug here.
[lstm-5a64f1.zip](https://github.com/android/ndk/files/11777707/lstm-5a64f1.zip)

clang++: error: unable to execute command: Segmentation fault
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5484270 based on r353983c) clang version 9.0.3 (https://android.googlesource.com/toolchain/clang 745b335211bb9eadfa6aa6301f84715cee4b37c5) (https://android.googlesource.com/toolchain/llvm 60cf23e54e46c807513f7a36d0a7b777920b5881) (based on LLVM 9.0.3svn)
Target: i686-unknown-linux-android
Thread model: posix
InstalledDir: prebuilts/clang/host/linux-x86/clang-r353983c/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /home/steve/android10/out/soong/.temp/lstm-5a64f1.cpp
clang++: note: diagnostic msg: /home/steve/android10/out/soong/.temp/lstm-5a64f1.sh
clang++: note: diagnostic msg:
[lstm-5a64f1.zip](https://github.com/android/ndk/files/11777701/lstm-5a64f1.zip)

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu 22.04 and Ubuntu 18.04

### Affected ABIs

x86_64

### Build system

ndk-build

### Other build system

AOSP Android 10

### minSdkVersion

Android 10

**Comment by pirama-arumuga-nainar** [comment]
We have seen several clang segfaults/crashes when building AOSP that are due to memory pressure in the build host. Please re-run reproducer on idle system and see if it fails.

`clang-r353983c` is quite old.  Please file if this reproduces in newer `clang-r487747c` or newer.
