### ISSUE TITLE
[Bug]: Consequence of Infinite Memory Allocation: Kernel Panic

### ISSUE THREAD

**Issue by Piorosen** [android/ndk#1897]
### Description

As a researcher working on native Android application development, I conducted experiments to test memory behavior. During the process, I observed that continuously calling push_back on a vector led to the Android system freezing and becoming unresponsive.

I'd like to clarify that the experiments were conducted using the NDK r25b and Clang version 14.0.6. It's important to note that the tests were performed by accessing the shell via adb, rather than using JNI within the application itself.

When running the application directly, it resulted in the application forcibly terminating. However, when executing the binary through adb shell, it caused the Android system UI to halt.

The code used in the experiment is as follows, and the YouTube link is https://www.youtube.com/watch?v=Ici8rg1EVog.

```cpp
#include <vector>
#include <iostream>
#include <random>

static std::vector<double> data;

int main(int argc, char** argv) {
    std::cout << "RUN!\n";    
    std::random_device rd{};

    double random[1024];
    for (int i = 0; i < 1024; i++){ 
        random[i] = rd();
    }

    for (int j = 0; ; j++)
    { 
        for (int i = 0; i < 1024 * 1024; i++) { 
            data.push_back(random[i % 1024]);
        }
        std::cout << (j + 1) * (sizeof(double)) << " MB\n";    
    }
    return 0;
}
```

### Commit to cherry-pick

Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)

### Affected versions

r25

### Host OS

Linux

### Host OS version

Linux PC 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Affected ABIs

arm64-v8a

**Comment by jmgao** [comment]
This is intended behavior, processes from `adb shell` have a default oom_score_adj of -950, so the launcher will get oom-killed before anything you run from `adb shell` does.

**Comment by Piorosen** [comment]
However, in the case of the code below, only the `bad_alloc` exception is raised, and the `adb shell` does not terminate.

```
#include <iostream>
int main(int argc, char** argv) {
    for (int i = 0; ; i++) { 
        new int[1024 * 1024]; 
        std::cout << (i + 1) * 4 << " MB \n";
    }
}
```

**Comment by jmgao** [comment]
That's because you're not touching the allocations, so no actual memory pages are being allocated. You're running out of address space or virtual memory mappings, not actual memory.

**Comment by enh-google** [comment]
yeah, this is WAI but it definitely causes confusion, so i've explicitly mentioned it in the docs: https://android-review.googlesource.com/c/platform/bionic/+/2638672
