### ISSUE TITLE
[BUG] The repository now only contains CONTRIBUTING.md and README.md

### ISSUE THREAD

**Issue by hackwrench** [android/ndk#1902]
### Description

What's going on? The repository now essentially no longer exists.

### Affected versions

Canary

### Host OS

Windows

### Host OS version

This is a problem with the repo and not the os it would be running on.

### Affected ABIs

x86_64

### Build system

ndk-build

### minSdkVersion

this is a problem with the repo

**Comment by enh-google** [comment]
i think that's always been the case, no? see the first section of the README.md if you're looking for the _source_ to the ndk.
