### ISSUE TITLE
[FR] Provide TRIPLE to CMake users

### ISSUE THREAD

**Issue by juan-lunarg** [android/ndk#1905]
### Description

I ran into this problem recently where I needed to get the `triple` in our CMake code.

I ended up using `abis.json` to get the `triple` reliably.

```cmake
file(READ "${CMAKE_ANDROID_NDK}/meta/abis.json" JSON_FILE)
string(JSON TRIPLE GET "${JSON_FILE}" "${CMAKE_ANDROID_ARCH_ABI}" "triple")
```

**Comment by DanAlbert** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_TARGET.html

**Comment by juan-lunarg** [comment]
> https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_TARGET.html

That almost works but it's not what I need.

```
file(READ "${CMAKE_ANDROID_NDK}/meta/abis.json" JSON_FILE)
string(JSON TRIPLE GET "${JSON_FILE}" "${CMAKE_ANDROID_ARCH_ABI}" "triple")

message(STATUS "TRIPLE = ${TRIPLE}")
message(STATUS "CMAKE_CXX_COMPILER_TARGET = ${CMAKE_CXX_COMPILER_TARGET}")
```

output

```
[cmake] -- TRIPLE = aarch64-linux-android # <--- I need this value
[cmake] -- CMAKE_CXX_COMPILER_TARGET = aarch64-none-linux-android26
```

**Comment by DanAlbert** [comment]
What's the X/Y problem you're trying to solve?

**Comment by juan-lunarg** [comment]
Link to our code: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2ce44f7f1928edb981adc587d8d3e2fb0f41e975/tests/android/CMakeLists.txt#L72

According to the Android NDK documentation (https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#STL).

> If using the shared variant, libc++_shared.so must be included in the APK.

Therefore as part of my CMake installation I'd like to install libc++_shared.so during my CMake installation if CMAKE_ANDROID_STL_TYPE is equal to c++_shared.

I achieve this with the following code:

```
if ("${CMAKE_ANDROID_STL_TYPE}" MATCHES "shared")
    file(READ "${CMAKE_ANDROID_NDK}/meta/abis.json" JSON_FILE)
    string(JSON TRIPLE GET "${JSON_FILE}" "${CMAKE_ANDROID_ARCH_ABI}" "triple")
    install(FILES "${CMAKE_SYSROOT}/usr/lib/${TRIPLE}/libc++_shared.so" DESTINATION "${CMAKE_INSTALL_LIBDIR}")
endif()
```

**Comment by DanAlbert** [comment]
Thanks, I understand now 👍 

I think what you have now is the most future-proof way to go about this. I can add something to our toolchain file that would export this more directly, but if we ever succeed at deduping the two CMake NDK implementations (we have our toolchain file, CMake added its own support for the NDK directly at the same time), that will probably stop working.

If you're willing to adapt to breakages that may or may not happen in the future, the data in abis.json is already serialized to a CMake friendly format (CMake didn't natively support JSON when we were first implementing this):


`$NDK/build/cmake/abis.cmake`:

```cmake
set(NDK_DEFAULT_ABIS "arm64-v8a;armeabi-v7a;x86;x86_64")
set(NDK_DEPRECATED_ABIS "")
set(NDK_KNOWN_DEVICE_ABI32S "armeabi-v7a;x86")
set(NDK_KNOWN_DEVICE_ABI64S "arm64-v8a;x86_64")
set(NDK_KNOWN_DEVICE_ABIS "arm64-v8a;armeabi-v7a;x86;x86_64")
set(NDK_ABI_armeabi-v7a_PROC "armv7-a")
set(NDK_ABI_armeabi-v7a_ARCH "arm")
set(NDK_ABI_armeabi-v7a_TRIPLE "arm-linux-androideabi")
set(NDK_ABI_armeabi-v7a_LLVM_TRIPLE "armv7-none-linux-androideabi")
set(NDK_PROC_armv7-a_ABI "armeabi-v7a")
set(NDK_ARCH_arm_ABI "armeabi-v7a")
set(NDK_ABI_arm64-v8a_PROC "aarch64")
set(NDK_ABI_arm64-v8a_ARCH "arm64")
set(NDK_ABI_arm64-v8a_TRIPLE "aarch64-linux-android")
set(NDK_ABI_arm64-v8a_LLVM_TRIPLE "aarch64-none-linux-android")
set(NDK_PROC_aarch64_ABI "arm64-v8a")
set(NDK_ARCH_arm64_ABI "arm64-v8a")
set(NDK_ABI_x86_PROC "i686")
set(NDK_ABI_x86_ARCH "x86")
set(NDK_ABI_x86_TRIPLE "i686-linux-android")
set(NDK_ABI_x86_LLVM_TRIPLE "i686-none-linux-android")
set(NDK_PROC_i686_ABI "x86")
set(NDK_ARCH_x86_ABI "x86")
set(NDK_ABI_x86_64_PROC "x86_64")
set(NDK_ABI_x86_64_ARCH "x86_64")
set(NDK_ABI_x86_64_TRIPLE "x86_64-linux-android")
set(NDK_ABI_x86_64_LLVM_TRIPLE "x86_64-none-linux-android")
set(NDK_PROC_x86_64_ABI "x86_64")
set(NDK_ARCH_x86_64_ABI "x86_64")
```

`NDK_ABI_${ANDROID_ABI}_TRIPLE` is the thing you're looking for. I don't really think that's any better than what you already have though.

(it'd perhaps be interesting to take this out of your hands entirely and automatically create the libc++ install rule, but that's not something we're able to do from a toolchain file)

**Comment by juan-lunarg** [comment]
> (it'd perhaps be interesting to take this out of your hands entirely and automatically create the libc++ install rule, but that's not something we're able to do from a toolchain file)

Yeah I'd really like this to be streamlined somehow.

Perhaps the correct avenue is to add Android support for `install(RUNTIME_DEPENDENCY_SET`? Since it seems like it's meant for this exact kind of situation. However, [file(GET_RUNTIME_DEPENDENCIES)](https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies) only supports collecting the runtime dependencies for Windows, Linux and macOS platforms, so install(RUNTIME_DEPENDENCY_SET) has the same limitation.

I'm not sure what the correct answer is.

Out of curiosity I noticed that the `ndk-build` handles this automatically but I wasn't able to figure out how exactly. I'm currently transitioning our `ndk-build` to CMake and noticed this minor detail. Could this method be utilized for CMake?

**Comment by DanAlbert** [comment]
> Out of curiosity I noticed that the ndk-build handles this automatically but I wasn't able to figure out how exactly.

Nothing fancy. We have full control over what ndk-build does so we can just do that. We have almost no control over what CMake does.

**Comment by juan-lunarg** [comment]
Gotcha.

Is there an appropriate place to add documentation for this somewhere for CMake Android developers? I think this is enough of a head scratcher it should be documented somewhere.

**Comment by DanAlbert** [comment]
Well, the recommended way to do this is via AGP, which handles the packaging details for you. I'm not sure what to document for custom setups beyond what's already in https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md.

**Comment by juan-lunarg** [comment]
What is AGP?

**Comment by DanAlbert** [comment]
Android Gradle Plugin.

**Comment by juan-lunarg** [comment]
Gotcha. Yes we aren't using Gradle with our CMake Android build currently.

I couldn't figure out how to implement it cleanly. And using straight CMake seamed easier minus 1 or 2 edge cases.
