### ISSUE TITLE
[FR] include LLVM commit in r26: a2684acfb61d [HWASan] use hwasan linker for Android 14+

### ISSUE THREAD

**Issue by fmayer** [android/ndk#1907]
### Description

Please include https://reviews.llvm.org/rGa2684acfb61d40f441e240035d7f1ba50da637c8 in the next NDK release, this will ensure that binaries built with `-fsanitize=hwaddress` with API 34 and newer will work on Android U devices.

**Comment by fmayer** [comment]
This is already cherrypicked onto Android LLVM r487747 https://android-review.git.corp.google.com/c/toolchain/llvm_android/+/2655792

**Comment by DanAlbert** [comment]
The toolchain update that fixed this was accidentally not included in r26 RC 1 as we had intended. The fix will be in r26b.
