### ISSUE TITLE
[Bug]: Fix ABI mismatch between FMV and ifunc resolver

### ISSUE THREAD

**Issue by pirama-arumuga-nainar** [android/ndk#1909]
### Description

Need to cherry-pick https://reviews.llvm.org/D155026

Snippet of the discussion:

Android iFunc resolver ABI FMV issue.
It takes (uint64_t hwcap, __ifunc_arg_t *arg), but FMV expects (uint64_t hwcap, uint64_t hwcap2) [ifunc resolver call](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/bionic/bionic_call_ifunc_resolver.cpp) [arg struct](https://android.googlesource.com/platform/bionic/+/master/libc/include/sys/ifunc.h)
Need to get init_cpu_features_resolver [compiler-rt/lib/builtins/cpu_model.c](https://github.com/llvm/llvm-project/blob/dc04b18ad7e45c67df4b8b3a756257eb62447970/compiler-rt/lib/builtins/cpu_model.c#L1143) fixed in NDK, patch for review https://reviews.llvm.org/D155026

### Commit to cherry-pick

https://reviews.llvm.org/rG61962aa1eec922c7dddd36897bb29888b4c98174

### Affected versions

r26

### Host OS

Linux, Mac, Windows

### Host OS version

All

### Affected ABIs

arm64-v8a

**Comment by pirama-arumuga-nainar** [comment]
@ilinpv the fix doesn't cherry-pick cleanly to the llvm-r487747 branch slated for r26.  Can you fix the merge conflicts and upload a CL?

**Comment by ilinpv** [comment]
@pirama-arumuga-nainar here it is https://android-review.googlesource.com/c/toolchain/llvm_android/+/2672879

**Comment by DanAlbert** [comment]
The toolchain update that fixed this was accidentally not included in r26 RC 1 as we had intended. The fix will be in r26b.
