### ISSUE TITLE
[BUG] NDK 26 beta includes duplicated clang resource directory

### ISSUE THREAD

**Issue by keith** [android/ndk#1910]
### Description

Downloading the macOS NDK 26 beta from https://developer.android.com/ndk/downloads contains 2 identical clang resource directories in:

```
26.0.10404224/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang
```

Named `17` and `17.0.2`. It seems like these could potentially be symlinks if they both needed to exist, but maybe one could be removed instead? As far as I can tell there is no diff between these directories.

### Affected versions

r26

### Host OS

Mac

### Host OS version

macOS 13.4.1

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

N/A

**Comment by DanAlbert** [comment]
They almost certainly were symlinks that get unsymlinked at some point... Can probably undo that.

Presumably we have this problem for all the OSs. For windows we'll need to figure out whichever one isn't actually used and just delete that.

**Comment by finagolfin** [comment]
On linux, the longer number is a symlink:
```bash
> ls -l android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/
total 4
drwxr-xr-x 6 foo foo 4096 Jun 28 23:46 17
lrwxrwxrwx 1 foo foo    2 Jul 24 16:47 17.0.2 -> 17
```

**Comment by DanAlbert** [comment]
Oh, interesting. I'd assumed this was a non-link on all platforms. Odd that we have the symlink for Linux but not for Darwin...

**Comment by pirama-arumuga-nainar** [comment]
https://android.googlesource.com/platform/prebuilts/clang/host/darwin-x86/+/refs/heads/main/clang-r487747c/lib/clang/ shows the symlink in the AOSP prebuilts.  The symlink could be getting dropped while packaging.

**Comment by jfgoog** [comment]
It looks like NDK sizes jumped some time in late April (I have an internal dashboard for build sizes that I won't post here)

I did some work awhile back to clean up duplicate files and symlinks, so I'm guessing this is a regression that crept back in.

When we package, we should be preserving symlinks, except on Windows: See https://android.googlesource.com/platform/ndk/+/refs/heads/main/ndk/checkbuild.py#289 and https://android.googlesource.com/platform/ndk/+/refs/heads/main/ndk/checkbuild.py#225

**Comment by jfgoog** [comment]
It looks like something happened on 4/27 or 4/28.

Build #10026030 is ~700MB, 
Build #10030768 is ~950MB

**Comment by finagolfin** [comment]
RISC-V was added then?

**Comment by finagolfin** [comment]
I also see a handful of musl directories, not sure what that's about:
```bash
> find android-ndk-r26-beta1/ -name "*musl"
android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/lib/i686-unknown-linux-musl
android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/lib/x86_64-unknown-linux-musl
android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__support/musl
android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/musl
android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/musl/lib/i686-unknown-linux-musl
android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/musl/lib/x86_64-unknown-linux-musl
```

**Comment by DanAlbert** [comment]
The problem is the copy from prebuilts to out:

```
$ ls -l ../prebuilts/clang/host/darwin-x86/clang-r498229/lib/clang
total 0
drwxr-xr-x  5 danalbert  primarygroup  160 Jul 13 15:31 17
lrwxr-xr-x  1 danalbert  primarygroup    2 Jul 13 15:31 17.0.3 -> 17
$ ls -l ../out/darwin/android-ndk-r27-canary/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang 
total 0
drwxr-xr-x  6 danalbert  primarygroup  192 Jul 13 15:31 17
drwxr-xr-x  6 danalbert  primarygroup  192 Jul 13 15:31 17.0.3
```

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/2673337 (i haven't been able to test yet because apparently our Darwin build is still broken from the latest clang).

**Comment by keith** [comment]
thanks for debugging!

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/2673482 presumably works on Windows. Will let CI prove it.

**Comment by pirama-arumuga-nainar** [comment]
(For posterity, the symlinks are not needed for the NDK.  It's created by the llvm-toolchain build scripts until we can fix platform/assorted-instances where folks hard-coded the long version.  This shouldn't be the case for the NDK.)

**Comment by DanAlbert** [comment]
Oh, I thought that was just a regular clang thing. TIL
