### ISSUE TITLE
[Bug]: ndk-r26-beta1 clang++ preprocessor chokes when building libicuuc (part of icu library)

### ISSUE THREAD

**Issue by johanwiden** [android/ndk#1919]
### Description

I have downloaded https://android.googlesource.com/platform/external/icu, and am using the main branch.
The clang++ preprocessor seems to choke (silently!) when trying to compile files in subdirectory icu4c/source/common.
What happens is that it stops processing include files.
Example, you will have to adjust the paths for your setup:

```
~/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable.cpp -I/home/jw/projects/android
/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION   -DPIC -fPIC -E -C -H -std=c++11
```

Now open the generated file libicuuc-shared-appendable.cpp, and search for appendable.h.
Repeat the command but instead use your hosts clang++, I used clang++-15. Compare the generated files. The file generated by the cross compiler has an essentially empty appendable.h. The same goes for other include files that come late in the processing.

### Affected versions

r25, r26

### Canary version

10660052 (2023-08-15)

### Host OS

Linux

### Host OS version

Ubuntu 23.04

### Affected ABIs

arm64-v8a

**Comment by DanAlbert** [comment]
Presumably you're not defining [U_SHOW_CPLUSPLUS_API](https://cs.android.com/android/platform/superproject/main/+/main:external/icu/icu4c/source/common/unicode/utypes.h;drc=99d5ccbf5ea2aa2cc87f85d3322b32ee5781d725;l=64)?

> `-o libicuuc-shared-appendable.cpp`

Mind attaching that?

**Comment by johanwiden** [comment]
Adding option -DU_SHOW_CPLUSPLUS_API, or option -DU_SHOW_CPLUSPLUS_API=1 makes no difference. I tried this, in my desperation, before submitting the bug report. But maybe I messed up? So I now tried this again. Below, I append all the compile commands I now used. But first a report of what I found out.

I ran the host clang++-15 preprocessor on the source file, without -DU_SHOW_CPLUSPLUS_API, with -DU_SHOW_CPLUSPLUS_API, and with -DU_SHOW_CPLUSPLUS_API=1. This generated three .cpp files, with no difference between them (I checked with "diff -c").

I ran the android-ndk-r26-beta1 aarch64-linux-android33-clang++ preprocessor on the source file, without -DU_SHOW_CPLUSPLUS_API, with -DU_SHOW_CPLUSPLUS_API, and with -DU_SHOW_CPLUSPLUS_API=1. This generated three .cpp files, with no difference between them (I checked with "diff -c").

However: There are significant differences between the preprocessor output from clang++-15 and aarch64-linux-android33-clang++. Among them that the content of appendable.h is missing from the output of aarch64-linux-android33-clang++. Again I checked with diff -c.

I can attach the generated files, if this is of interest.

I now used aarch64-linux-android33-clang++ to try to compile the preprocessed cpp files to object files, just changing -E to -c, and changing the names of the file to be compiled and the output file:
- The preprocessed file generated by the host clang++-15 compiled with essentially no complaint (there was a warning clang-17: warning: /home/jw/projects/android/icu/icu4c/source/common/: 'linker' input unused [-Wunused-command-line-argument])
- The preprocessed file generated by aarch64-linux-android33-clang++, did not compile. I got the following errors:
  clang-17: warning: /home/jw/projects/android/icu/icu4c/source/common/: 'linker' input unused [-Wunused-command-line-argument]
  /home/jw/projects/android/icu/icu4c/source/common//appendable.cpp:23:1: error: use of undeclared identifier 'Appendable'
Appendable::~Appendable() {}
  ^
  /home/jw/projects/android/icu/icu4c/source/common//appendable.cpp:26:1: error: use of undeclared identifier 'Appendable'
Appendable::appendCodePoint(UChar32 c) {
  ^
  /home/jw/projects/android/icu/icu4c/source/common//appendable.cpp:35:1: error: use of undeclared identifier 'Appendable'
Appendable::appendString(const UChar *s, int32_t length) {
  ^
  /home/jw/projects/android/icu/icu4c/source/common//appendable.cpp:55:1: error: use of undeclared identifier 'Appendable'
Appendable::reserveAppendCapacity(int32_t ) {
  ^
  /home/jw/projects/android/icu/icu4c/source/common//appendable.cpp:60:1: error: use of undeclared identifier 'Appendable'
Appendable::getAppendBuffer(int32_t minCapacity,
  ^
  5 errors generated.

I now append all the preprocessing command, and the commands used to compile to object file:
clang++-15  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable_host_path.cpp -I/home/jw/projects/android/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION   -DPIC -fPIC -std=c++11

clang++-15  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable_host_dapi.cpp -I/home/jw/projects/android/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION -DU_SHOW_CPLUSPLUS_API  -DPIC -fPIC -std=c++11

clang++-15  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable_host_dapi_1.cpp -I/home/jw/projects/android/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION -DU_SHOW_CPLUSPLUS_API=1  -DPIC -fPIC -std=c++11

~/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable_r26.cpp -I/home/jw/projects/android/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION   -DPIC -fPIC -std=c++11

~/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable_r26_dapi.cpp -I/home/jw/projects/android/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION -DU_SHOW_CPLUSPLUS_API  -DPIC -fPIC -std=c++11

~/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++  -E ~/projects/android/icu/icu4c/source/common//appendable.cpp -o libicuuc-shared-appendable_r26_dapi_1.cpp -I/home/jw/projects/android/icu/icu4c/source/common/ -I/home/jw/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION -DU_SHOW_CPLUSPLUS_API=1  -DPIC -fPIC -std=c++11

~/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++  -c libicuuc-shared-appendable_host.cpp -o libicuuc-shared-appendable_host-r26.o -I~/projects/android/icu/icu4c/source/common/ -I~/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION   -DPIC -fPIC -std=c++11

~/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++  -c libicuuc-shared-appendable_r26.cpp -o libicuuc-shared-appendable_r26-r26.o -I~/projects/android/icu/icu4c/source/common/ -I~/projects/android/icu/icu4c/source/common//../i18n ~/projects/android/icu/icu4c/source/common/  -D_REENTRANT -DU_COMMON_IMPLEMENTATION   -DPIC -fPIC -std=c++11

**Comment by DanAlbert** [comment]
> I can attach the generated files, if this is of interest.

Yes please

**Comment by johanwiden** [comment]
Below is a link to a tar archive, that contains two files preprocessed by host clang++-15 and c++ from android-ndk-r26-beta1, respectively. I was unable to attach the tar (tgz) archive directly to this comment, even though it says at the bottom of the comment that .tgz files can be attached.

https://drive.google.com/file/d/1RypRcV0jyZvqoTOTVmwbNufLo-GrcZwR/view?usp=sharing

**Comment by DanAlbert** [comment]
I don't have access to that...

**Comment by DanAlbert** [comment]
(in the future, you can just attach a .zip directly to github)

**Comment by johanwiden** [comment]
I hop you have access now.

**Comment by DanAlbert** [comment]
Yes, but I assume only I do, and not anyone else on my team?

**Comment by johanwiden** [comment]
Sorry about that, it was not my intention. Now anyone who have the link,
should be able to get the file.

**Comment by DanAlbert** [comment]
Adding this just above the `#if U_SHOW_CPLUSPLUS_API` shows that it's not enabled:

```c++
#if !U_SHOW_CPLUSPLUS_API
#error no cpp api
#endif
```

```
$ android-ndk-r27-canary/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang++  -E /Volumes/src/icu/icu4c/source/common/appendable.cpp -o libicuuc-shared-appendable.cpp -DU_SHOW_CPLUSPLUS_API=1
In file included from /Volumes/src/icu/icu4c/source/common/appendable.cpp:18:
/Volumes/src/icu/icu4c/source/common/unicode/appendable.h:28:2: error: no cpp api
#error no cpp api
 ^
1 error generated.
```

`-dM` agrees:

```
$ android-ndk-r27-canary/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang++  -E /Volumes/src/icu/icu4c/source/common/appendable.cpp -DU_SHOW_CPLUSPLUS_API=1 -dM | grep U_SHOW_CPLUSPLUS_API
#define LIBICU_U_SHOW_CPLUSPLUS_API 1
#define U_SHOW_CPLUSPLUS_API 0
```

Looking at your preprocessed source:

```
# 1 "/home/jw/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/uconfig_local.h" 1 3 4
# 22 "/home/jw/Android/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/uconfig_local.h" 3 4
```

That file has an unconditional `#define U_SHOW_CPLUSPLUS_API 0` because the NDK does not support the C++ interface (C++ does not have a stable ABI, so it can't). You're using your own ICU, but the build command you provided above uses the NDK's headers. You need to `-I` the headers of your ICU4C distribution.
