### ISSUE TITLE
[BUG] Performance loss after NDK 21.4.7075529

### ISSUE THREAD

**Issue by flsobral** [android/ndk#1923]
### Description

A user of my library reported a performance loss after I switched from NDK 21 to 23.
In a test provided by this user, using the library built with NDK 21 takes roughly 500 ms, while the version built with NDK 23 takes 3800-4000 ms.

I thought this could be related to the issue #1740, but got the same results with NDK 25.2.9519653.

I did try forcing -O3 both in the gradle file and directly in the CMake file, I also tried using -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF, forcing a release build using -DCMAKE_BUILD_TYPE=Release, and every NDK released between 21 and 25, but the results are always the same.

I checked every configuration file to make sure the flags are properly set and everything checks out.

I'm working on a smaller test that reproduces the issue, but I'd like to know if there's anything else I can already provide, like CMakeCache, build.ninja, logs and other CMake files.

### Affected versions

r25

### Host OS

Mac

### Host OS version

Mac M1 - 13.5, Mac Intel - 12.1

### Affected ABIs

armeabi-v7a, arm64-v8a

### Build system

CMake

### minSdkVersion

19, but have also tried with 28 and got the same results

### Device API level

29

**Comment by DanAlbert** [comment]
Have you tried r26 RC1? r25 will not be receiving any more updates.

We need a repro case. Without that there's nothing we can investigate. Closing until we get one.
