### ISSUE TITLE
[BUG] bionic strstr slower than glibc's

### ISSUE THREAD

**Issue by sekaiacg** [android/ndk#1924]
### Description

**Device:** soc is 865 (sm8250)
In a simple string search test program, search for a string a million times.
The performance of ndk is too low.
```
cmi:/cache # ./test1                                                                                  
t1Count=1000000
The operation took: test 1 : 0.220184 second(s).
t2Count=1000000
The operation took: test 2 : 0.335908 second(s).

cmi:/cache # ./test2                                                                                  
t1Count=1000000
The operation took: test 1 : 5.185180 second(s).
t2Count=1000000
The operation took: test 2 : 2.775288 second(s).
```

**example:**
[test.cpp.txt](https://github.com/android/ndk/files/12487394/test.cpp.txt)

```
clang -o test1 test.cpp --target=aarch64-linux-gnu \
--sysroot=/usr/aarch64-linux-gnu \
-lstdc++ -std=c++20 -O3 \
-flto=full -fuse-ld=lld \
-static -s \
-Wl,-icf=safe,--lto-O3 
```

```
${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++ \
-o test2 test.cpp \
-lc++_static -std=c++20 -O3 \
-flto=full -fuse-ld=lld \
-static -s \
-Wl,-icf=safe,--lto-O3
```

**I have used various CFLAGs and nothing has solved the problem.**

### Affected versions

r25

### Host OS

Linux

### Host OS version

archlinux

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### minSdkVersion

33

### Device API level

33

**Comment by DanAlbert** [comment]
> clang

What is this?

**Comment by appujee** [comment]
i'm wondering if the mem* functions are loewred to for loops instead of directing to a libc call?

**Comment by sekaiacg** [comment]
> > clang
> 
```
clang --version

clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
clang --target=aarch64-linux-gnu  -print-target-triple
aarch64-unknown-linux-gnu
```
```
aarch64-linux-gnu-gcc --version

aarch64-linux-gnu-gcc (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
> 
> > Device: soc is 865 (sm8250)
> 
https://forum.xda-developers.com/c/xiaomi-mi-10-pro.10293/
> 
> How do we actually reproduce this?

Compile using the code provided by example to obtain the test program.
I think this bug can be reproduced on any SOC platform using arm-v8a.

**Comment by sekaiacg** [comment]
> i'm wondering if the mem* functions are loewred to for loops instead of directing to a libc call?

I don't know this.

**Comment by appujee** [comment]
> > i'm wondering if the mem* functions are loewred to for loops instead of directing to a libc call?
> 
> I don't know this.

you can pass `--save-temps` or (-S flag) to get the assembly files in each case.

**Comment by appujee** [comment]
In the bug description you used  `${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++` but  later in the comment you have `aarch64-linux-gnu-gcc --version`. These are different compilers.


Also in each case you are using different C++ standard library versions.
in the first example you have `-lstdc++` which is libstdc++ (gnu)
in the second example you have `-lc++_static` which is libc++.

**Comment by sekaiacg** [comment]
> > > i'm wondering if the mem* functions are loewred to for loops instead of directing to a libc call?
> > 
> > 
> > I don't know this.
> 
> you can pass `--save-temps` or (-S flag) to get the assembly files in each case.
[test1.zip](https://github.com/android/ndk/files/12491942/test1.zip)
[test2.zip](https://github.com/android/ndk/files/12491944/test2.zip)

**Comment by appujee** [comment]
> > > > i'm wondering if the mem* functions are loewred to for loops instead of directing to a libc call?
> > > 
> > > 
> > > I don't know this.
> > 
> > 
> > you can pass `--save-temps` or (-S flag) to get the assembly files in each case.
> > [test1.zip](https://github.com/android/ndk/files/12491942/test1.zip)
> > [test2.zip](https://github.com/android/ndk/files/12491944/test2.zip)

Thanks. Both are different toolchains and it is likely that libc internals are causing the performance issue. My first guess is that bionic_strstr and bionic_strchr in the test2 might be causing the regression.

**Comment by sekaiacg** [comment]
> > > > > i'm wondering if the mem* functions are loewred to for loops instead of directing to a libc call?
> > > > 
> > > > 
> > > > I don't know this.
> > > 
> > > 
> > > you can pass `--save-temps` or (-S flag) to get the assembly files in each case.
> > > [test1.zip](https://github.com/android/ndk/files/12491942/test1.zip)
> > > [test2.zip](https://github.com/android/ndk/files/12491944/test2.zip)
> 
> Thanks. Both are different toolchains and it is likely that libc internals are causing the performance issue. My first guess is that bionic_strstr and bionic_strchr in the test2 might be causing the regression.

Thank you for your help.
I think they are both c++20 standards and they should not have such a big gap.

**Comment by appujee** [comment]
These (strstr, strchr etc) are C library implementations and they don't have any implementation in C++ standard libraries. The C++ standard library only invokes the C library implementations that are linked to the binary.

**Comment by sekaiacg** [comment]
> These (strstr, strchr etc) are C library implementations and they don't have any implementation in C++ standard libraries. The C++ standard library only invokes the C library implementations that are linked to the binary.

I used 2 methods to test.
strstr is in libc,
string_view.find in c++_static.
Is there a problem with their implementation in ndk?

**Comment by DanAlbert** [comment]
Their implementation is not in the NDK at all, it's part of the OS. I'll leave this open for the moment in case @enh-google wants to track that here, but that's not likely a thing that can be fixed in an NDK release (the only way we could would be by inlining it into the app, and we generally prefer not to do that for APK size reasons).

**Comment by DanAlbert** [comment]
Yeah, closing as this is a platform issue. If you want this looked at for the OS soon, the best way to do that is to reduce the case you uploaded to something that you could add to https://cs.android.com/android/platform/superproject/main/+/main:bionic/benchmarks/ and upload that to gerrit.
