### ISSUE TITLE
windows 32bit support for NDK and everything... i want it back

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [android/ndk#1925]
### Description

i want windows 32bit support back... it's stupid that i need 64bit to just compile for android...
even if it would be without the emulator or without the IDE... since i dont plan to use any of those bloated tools... even less android studio....

so then release a minimal version that just have the toolchain to compile for android and let me worry about how i run that... but dont stop supporting 32bit that's discrimination 32bit matter too...

**Comment by MyTDT-Mysoft** [comment]
i really got angry when i did a pause on my projects and back to know that incompetent people removed support for 32bit windows...

**Comment by enh-google** [comment]
if you want to build your own NDK for unsupported platforms, see https://android.googlesource.com/platform/ndk/+/master/docs/Building.md

**Comment by DanAlbert** [comment]
Personal attacks will not be tolerated. Making a different trade-off than you would have is not incompetence.

Use the link above if you need to build this support yourself, but we do not have the resources to maintain or test that platform (which Microsoft does not even support any more).
