### ISSUE TITLE
[Bug]: llvm-strip --strip-debug  crash

### ISSUE THREAD

**Issue by lqwu** [android/ndk#1927]
### Description

command: prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip -o 【output】 --strip-debug 【input】
 
#0 0x0000564fa934e412 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x404412)
 #1 0x0000564fa934d5a0 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x4035a0)
 #2 0x0000564fa934e90a (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x40490a)
 #3 0x000014b263192980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #4 0x0000564fa9221f3e (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d7f3e)
 #5 0x0000564fa9221b2f (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d7b2f)
 #6 0x0000564fa921c5c8 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d25c8)
 #7 0x0000564fa921c260 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d2260)
 #8 0x0000564fa921bba5 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d1ba5)
 #9 0x0000564fa921b991 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d1991)
#10 0x0000564fa921b92a (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2d192a)
#11 0x0000564fa9167832 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x21d832)
#12 0x0000564fa9165ee3 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x21bee3)
#13 0x0000564fa916387f (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x21987f)
#14 0x000014b2621d1c87 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c87)
#15 0x0000564fa9242bc9 (prebuilts/clang/host/linux-x86/clang-r487747c/bin/llvm-strip+0x2f8bc9)

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu 18.04.6

### Affected ABIs

arm64-v8a

**Comment by enh-google** [comment]
this shows there was a signal received:
```
 0x000014b263192980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
```
so you'll need to include the corresponding log output from the crash handler --- that'll explain what went wrong.

but you'll probably want to try the current version -- r498229b -- first anyway.

**Comment by DanAlbert** [comment]
There isn't anything we can do to help without a repro case. We know strip works, the inputs here are relevant.
