### ISSUE TITLE
[DOC] Various documentation issues

### ISSUE THREAD

**Issue by MarijnS95** [android/ndk#1933]
### URL

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=474-489?q=data_Space.h

### Problem

I reported a bunch of low-hanging fruit to @jfgoog who forwarded me to report issues here instead. Perhaps it's more convenient if I immediately send fixes upstream rather than attempting to describe them, but on the other hand that that's an endless and mundane task while I'm also porting them to https://docs.rs/ndk.

## `DataSpace` variant docs mixed up for `BT.601`

Per https://developer.android.com/ndk/reference/group/a-data-space / https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=474-489;drc=f83160f3f022ee04a68f1293631e0898ba5bb52f the docs for `BT601_525` state that it's the BT.706 standard, and `BT601_625` states that it's `BT.601_525`. Looks like there are multiple copy-paste errors here (also observe the `525` being mentioned twice in `625`'s docs)?

## `ADATASPACE_BT2020` says `BT.709` transfer function (which is a standard instead)

This is more clear to describe as `TRANSFER_SMPTE_170M`?

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=496-498;drc=f83160f3f022ee04a68f1293631e0898ba5bb52f

Same for the `BT709` dataspace itself; its transfer function is `SMPTE 170M`:

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=505-507;drc=2091109ac95d110aa51cea6198866585a1ccd01e

## `*rgb*` dataspaces lack generic sentence

All variants document their range/transfer/standard in the form `Use X range, Y transfer and Z standard.`, except these. Would be complete to include that.

## `ADATASPACE_ADOBE_RGB` and `ADATASPACE_DCI_P3` missing period and newline before `Note:`

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=456-460;drc=f83160f3f022ee04a68f1293631e0898ba5bb52f
https://developer.android.com/ndk/reference/group/a-data-space#group___a_data_space_1gga2759ad19cae46646cc5f7002758c4a1ca6f0382d97e9e72ef961883800ff9bc44

## `ASharedMemory_create` `FD_SETFD` => `F_SETFD`

(https://github.com/rust-mobile/ndk/pull/427#discussion_r1302259866)

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/include/android/sharedmem.h;l=68;drc=5d5faa47b48263837f8d3083ae5c94173927ddf1

And in general crooked sentences over at https://developer.android.com/ndk/reference/group/memory:

> Create shared memory region and returns an file descriptor.

And linking to `android.os.SharedMemory` might be nice.

## `Thermal` has codeblocks for what should be inline monospace

https://developer.android.com/ndk/reference/group/thermal#athermal_getthermalheadroom

Notice how words like `NaN` and `forecastSeconds` render as code blocks.

## `AndroidBitmap_compress` uses pipe symbols to "indicate" monospace, while they don't render as such

https://developer.android.com/ndk/reference/group/bitmap#androidbitmap_compress

**Comment by DanAlbert** [comment]
Not our docs, we're just the distributor. https://source.android.com/docs/setup/contribute/report-bugs and file against framework.

**Comment by MarijnS95** [comment]
@DanAlbert then please remove the obvious "documentation bugs" template from the issue council here?

**Comment by DanAlbert** [comment]
We have a lot of our own docs, we just don't own the API docs. I'll update the form to say that.

**Comment by MarijnS95** [comment]
Copy-pasted to https://issuetracker.google.com/issues/300602767.

**Comment by DanAlbert** [comment]
Thanks! Form is updated now.

(if no one bites on that bug for a while, lmk, I can try to track down an owner)

**Comment by enh-google** [comment]
i've uploaded fixes for ASharedMemory_create(), AThermal_getThermalHeadroom(), and AndroidBitmap_compress(), since they were trivial. i didn't really understand the others, so a subject matter expert probably needs to look at those :-)

**Comment by enh-google** [comment]
> @enh-google thanks! Should various documentation like sharedmem (re. [msft-mirror-aosp/platform.frameworks.native@950ee79](https://github.com/msft-mirror-aosp/platform.frameworks.native/commit/950ee79d9376e0c63436aa1ab1385fcdc4507977)) also have backticks around code things (e.g. `PROT_READ | PROT_WRITE | PROT_EXEC`)?

yeah, i don't think there's much existing consistency (outside of the libc headers, which aren't currently published to the web anyway :-( ), but that's probably the style we should be aiming for everywhere.

(that one's especially awkward because i think it needs a human --- i can't imagine writing a linter to spot this in general.)

**Comment by enh-google** [comment]
https://android-review.googlesource.com/c/platform/frameworks/native/+/2779447 for <android/sharedmem.h>.
