### ISSUE TITLE
[QUESTION] ndk-build: libomp.so copy with LOCAL_EXPORT_LDFLAGS := -fopenmp

### ISSUE THREAD

**Issue by emaschino** [android/ndk#1935]
### Description

Hi,

Not sure if this is a bug, so answering first ;-)

In [1] was added the copy of libomp.so by ndk-build when app LDFLAGS have -fopenmp. So far, so good, working as expected (tested with LOCAL_LDFLAGS += -fopenmp in app's Android.mk).

Now, I have an app that relies upon a 3rd-party library, the latter making use of OpenMP. In library's Android.mk, the library is imported as PREBUILT_SHARED_LIBRARY and defines LOCAL_EXPORT_LDFLAGS := -fopenmp (as well as LOCAL_EXPORT_CFLAGS := -fopenmp and LOCAL_EXPORT_CPPFLAGS := -fopenmp, BTW). libomp.so is NOT copied by ndk-build. Of course, if I replace LOCAL_EXPORT_LDFLAGS by LOCAL_LDFLAGS (or define LOCAL_LDFLAGS += -fopenmp in app's Android.mk), libomp.so is copied correctly. This is with NDK r25 if it does matter.

It was my understanding that LOCAL_EXPORT_CFLAGS, LOCAL_EXPORT_CPPFLAGS and LOCAL_EXPORT_LDFLAGS from imported 3rd-party libraries were propagated to the app CFLAGS, CPPFLAGS and LDFLAGS. So, with LOCAL_EXPORT_LDFLAGS := -fopenmp defined in my 3rd-party library, shouldn't have the app inherited -fopenmp in its LOCAL_LDFLAGS, thus triggering the copy of libomp.so by ndk-build?

Thanks!

[1] https://android-review.googlesource.com/c/platform/ndk/+/1127561

### Affected versions

r25

### Host OS

Windows

### Host OS version

Windows 10.0.19044.3324

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

29

**Comment by DanAlbert** [comment]
Repro case please. Will reopen if we get one.

**Comment by pirama-arumuga-nainar** [comment]
> the library is imported as PREBUILT_SHARED_LIBRARY

https://developer.android.com/ndk/guides/android_mk#local_export_cflags has `module that uses this one via the LOCAL_STATIC_LIBRARIES or LOCAL_SHARED_LIBRARIES variables.`.  It's WAI that these variables don't work for `PREBUILT_SHARED_LIBRARY`.

**Comment by DanAlbert** [comment]
That's probably a doc bug (or a missing feature). The code in ndk-build makes it look like this is supposed to work.
