### ISSUE TITLE
[FR]<exection> doesn't work for android 

### ISSUE THREAD

**Issue by kaizer1** [android/ndk#1951]
### Description

Parallelization does not work using this header. Do I think I should add or just use openMP?

**Comment by DanAlbert** [comment]
I've got no idea what this means. What did you do, what did you expect, and what happened instead?

**Comment by DanAlbert** [comment]
Sure, but what isn't working, and in what way is it not working?

**Comment by enh-google** [comment]
we don't have it yet, right? i think this is another dupe of "need a libc++
update"? (not that i know that upstream libc++ has it either, to be fair!)

**Comment by pirama-arumuga-nainar** [comment]
> we don't have it yet, right? i think this is another dupe of "need a libc++
update"?

The NDK has the libc++ built alongside clang.  libc++ in r26 has a `<execution>` - but that's from ~Jan.

**Comment by kaizer1** [comment]
This is the answer I wanted to get. Thank you

> > we don't have it yet, right? i think this is another dupe of "need a libc++
> > update"?
> 
> The NDK has the libc++ built alongside clang. libc++ in r26 has a `<execution>` - but that's from ~Jan.

**Comment by DanAlbert** [comment]
> This is the answer I wanted to get.

For future reference, that information is in the changelog:

> Updated LLVM to clang-r487747c. See AndroidVersion.txt and clang_source_info.md in the toolchain directory for version information.
