### ISSUE TITLE
[FR] arm64 binary of the NDK

### ISSUE THREAD

**Issue by MatteoBax** [android/ndk#1952]
### Description

I would like to ask if it is possible to have NDK binaries for Linux and macOS arm64.

**Comment by DanAlbert** [comment]
https://github.com/android/ndk/discussions/1692

**Comment by DanAlbert** [comment]
(you've already got macOS arm64)

**Comment by MatteoBax** [comment]
I also meant for Linux arm64.

**Comment by DanAlbert** [comment]
Yes. See the link.
