### ISSUE TITLE
[DOC] clang, not clang++ is being used and I can't find documentation on how to fix it.

### ISSUE THREAD

**Issue by dexmagic** [android/ndk#1954]
### URL

https://developer.android.com/ndk/guides/cmake

### Problem

My build at some point started using clang to build and not clang++:

Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang

I can't find any information that explains why this would happen or how to fix it.
Can you please let us know? This is a blocking my builds.

It's not important where you put it, but it should be somewhere. 

Thanks.

**Comment by DanAlbert** [comment]
Not related to the NDK. CMake chooses which compiler to use. The only thing the NDK toolchain file does is tell CMake where each compiler is, and I'm looking at the code that does this and it does set clang++. It'll be somewhere in https://cmake.org/cmake/help/latest/index.html, and if it's not, file a CMake bug.

The exception would be if you're seeing `CMAKE_CXX_COMPILER` set incorrectly, and that would be a bug, not a documentation issue, and we'll need a repro case.
