### ISSUE TITLE
[DOC] NDK revision history on developer.android.com is missing r26

### ISSUE THREAD

**Issue by janisozaur** [android/ndk#1959]
### URL

https://developer.android.com/ndk/downloads/revision_history

### Problem

The page is missing r26b

**Comment by DanAlbert** [comment]
_puts on his pedant hat_ It's not history yet.

That page has never listed current releases. Does it matter?

**Comment by enh-google** [comment]
you're not wrong, but i too have been confused/surprised by this before. the most similar document i've looked at this week [https://sourceware.org/glibc/wiki/Glibc%20Timeline] even includes _future_ releases [which is maybe going too far!] but certainly including the current one seems natural to me. the doc before that [https://curl.se/docs/releases.html] is similar too, modulo the future releases. it's definitely nice to just have one place to look.

actually, we seem to contradict ourselves slightly on our current page --- "This page provides information on changes in all released stable versions of the NDK" does sound like it should include r26 :-)

**Comment by janisozaur** [comment]
> That page has never listed current releases. Does it matter?

I'd say it does. I asked copilot to update the Gradle file for me and it insisted the latest ndk lts version was 23 and claimed this page is the source of truth.

For additional context, pretty much every page with release history (e.g. https://curl.se/docs/releases.html, https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information, https://developer.android.com/about/versions, https://releases.llvm.org/) list current versions and past ones.

> It's not history yet.

Philosophically it is. The present becomes history as soon as the moment passes. If the page was only meant to list _previous_ releases, it is misnamed.

**Comment by DanAlbert** [comment]
Considering copilot was wrong by over a year even ignoring r26, you probably shouldn't trust copilot to do that.

I've sent a CL to add r26 to that page. I'd just as happily replace the page with a link to https://groups.google.com/g/android-ndk-announce, since that's more complete anyway.

**Comment by enh-google** [comment]
even if you don't replace the _incoming_ link, add that link to the top of the revision_history.md page?
