### ISSUE TITLE
[BUG] Can not build wasi-libc sysroot with NDK r26b

### ISSUE THREAD

**Issue by truboxl** [android/ndk#1960]
### Description

I can not use the new WASM target in NDK r26b to build wasi-libc sysroot.

```
git clone https://github.com/WebAssembly/wasi-libc --depth=1 --recursive
make -C wasi-libc \
CC=../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
AR=../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar \
NM=../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm
make -C wasi-libc \
CC=../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
AR=../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar \
NM=../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm \
THREAD_MODEL=posix
```
```
../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -O2 -DNDEBUG --target=wasm32-wasi-threads -fno-trapping-math -Wall -Wextra -Werror -Wno-null-pointer-arithmetic -Wno-unused-parameter -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -Wno-ignored-attributes -Wno-missing-braces -Wno-ignored-pragmas -Wno-unused-but-set-variable -Wno-unknown-warning-option -mthread-model posix -pthread -ftls-model=local-exec -Ilibc-bottom-half/cloudlibc/src -isystem "../build/share/wasi-sysroot/include" -Ilibc-bottom-half/headers/private -Ilibc-bottom-half/cloudlibc/src/include -Ilibc-bottom-half/cloudlibc/src -Ilibc-top-half/musl/src/include -Ilibc-top-half/musl/src/internal -fPIC -fvisibility=default -MD -MP -o build/wasm32-wasi-threads/libc-bottom-half/crt/crt1.o -c libc-bottom-half/crt/crt1.c
In file included from libc-bottom-half/crt/crt1.c:3:
In file included from libc-bottom-half/crt/crt1-command.c:2:
/content/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/stdatomic.h:33:10: fatal error: 
      'sys/cdefs.h' file not found
#include <sys/cdefs.h>
         ^~~~~~~~~~~~~
```

Replacing the https://android.googlesource.com/toolchain/prebuilts/ndk/r26/+/e87abe7cbe9143d239ba54f32c64ca697adcba75/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/stdatomic.h
with
https://github.com/llvm/llvm-project/blob/llvmorg-17.0.3/clang/lib/Headers/stdatomic.h
allows to build the wasi-libc sysroot.

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### Other build system

make

### minSdkVersion

n/a

### Device API level

n/a

**Comment by appujee** [comment]
cc: @matthias-blume

**Comment by pirama-arumuga-nainar** [comment]
The stdatomic.h in AOSP-Clang/NDK is a copy of the bionic stdatomic.h (why we do this - that's for another time).

The failing command implies it's using a (partial?) musl sysroot and fails because musl doesn't have `sys/cdefs.h`.  Looks like we don't really need `sys/cdefs.h` in the header?  @truboxl if you remove the header from the ndk `stdatomic.h`, does that fix the build?  If it works, we can check if it's ok to remove it in AOSP as well.

**Comment by truboxl** [comment]
@pirama-arumuga-nainar 

> The stdatomic.h in AOSP-Clang/NDK is a copy of the bionic stdatomic.h (why we do this - that's for another time).

I definitely like to learn why there's such a difference between NDK and upstream LLVM.

> if you remove the header from the ndk stdatomic.h, does that fix the build?

Commenting out `#include <sys/cdefs.h>` in `android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/stdatomic.h` yields a different error:
```
../android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -O2 -DNDEBUG --target=wasm32-wasi-threads -fno-trapping-math -Wall -Wextra -Werror -Wno-null-pointer-arithmetic -Wno-unused-parameter -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -Wno-ignored-attributes -Wno-missing-braces -Wno-ignored-pragmas -Wno-unused-but-set-variable -Wno-unknown-warning-option -mthread-model posix -pthread -ftls-model=local-exec -Ilibc-bottom-half/cloudlibc/src -isystem "/content/wasi-libc/sysroot/include" -Ilibc-bottom-half/headers/private -Ilibc-bottom-half/cloudlibc/src/include -Ilibc-bottom-half/cloudlibc/src -Ilibc-top-half/musl/src/include -Ilibc-top-half/musl/src/internal -fPIC -fvisibility=default -MD -MP -o build/wasm32-wasi-threads/libc-bottom-half/crt/crt1.o -c libc-bottom-half/crt/crt1.c
In file included from libc-bottom-half/crt/crt1.c:3:
In file included from libc-bottom-half/crt/crt1-command.c:2:
In file included from /content/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/stdatomic.h:131:
/content/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/bits/stdatomic.h:32:10: fatal error: 
      'sys/cdefs.h' file not found
#include <sys/cdefs.h>
         ^~~~~~~~~~~~~
```
Commenting out `#include <sys/cdefs.h>` in `android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/bits/stdatomic.h` allows to build wasi-libc sysroot successfully.

**Comment by pirama-arumuga-nainar** [comment]
> I definitely like to learn why there's such a difference between NDK and upstream LLVM.

It relates to the `stdatomic.h` clang/C header gets included in C++ compilation.  The source would end up with conflicting or duplicate definitions across `stdatomic.h` and `<atomic>`.  This was recently resolved in the C++ WG (https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0943r6.html) but unfortunately is only enabled when targetting C++23 (look at the `<stdatomic.h>` in libcxx).  IIUC, we might have to stick with the bionic stdatomic.h for a while.

**Comment by enh-google** [comment]
> IIUC, we might have to stick with the bionic stdatomic.h for a while.

is it worth asking the folks who reviewed the <stdckdint.h> patch about this C++23 restriction? seems like there's a decent argument here to have the new behavior even for old language versions?

**Comment by pirama-arumuga-nainar** [comment]
b/147765083 is the internal bug for using clang's `stdatomic.h`.  I'm running presubmit on https://android-review.googlesource.com/c/toolchain/llvm_android/+/2806395 to get a breakage that we can then discuss in upstream.

@enh-google mentions in https://android-review.googlesource.com/c/platform/bionic/+/2806534 that bionic needs the `sys/cdefs.h` header to avoid subtle issues.

@truboxl what's the significance of using musl in Android?  Is it possible to use the Android sysroots in the NDK?

**Comment by truboxl** [comment]
The `wasi-libc` is needed to build `wasm32-wasi` applications as well as `libclang_rt.builtins-wasm32.a`, `libc++.a`, `libc++abi.a` etc for `wasm32-wasi`.

I do not know if I can build wasm applications out of bionic libc sysroot yet but I can try investigate.

**Comment by DanAlbert** [comment]
(feel free to continue discussing here, but this doesn't appear to be an NDK bug because you're not using the NDK sysroot, so I'm closing so it doesn't show in my triage)
