### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huazai023** [android/ndk#1969]
### Description

Function JNI cannot be used in Android 11_ GetCreatedJavaVMs, this function has been exported in libnativehelper in Android 12. How to solve this problem in Android 11

### Affected versions

r26

### Host OS

Linux

### Host OS version

ubuntu22.04

### Affected ABIs

x86_64

### Build system

ndk-build

### minSdkVersion

android-ndk-r25c

### Device API level

30

**Comment by enh-google** [comment]
you can't. it wasn't exported before then:
```
LIBNATIVEHELPER_S { # introduced=S
  global:
    # NDK API for libnativehelper.
    AFileDescriptor_create;
    AFileDescriptor_getFd;
    AFileDescriptor_setFd;

    # JNI Invocation methods available to platform and apps.
    JNI_CreateJavaVM;
    JNI_GetDefaultJavaVMInitArgs;
    JNI_GetCreatedJavaVMs;

  local:
    *;
};
```
