### ISSUE TITLE
[FR] Support profiling release builds

### ISSUE THREAD

**Issue by ericoporto** [android/ndk#1970]
### Description

Currently, starting a new profiling session in a device running a release built apk is not possible. It would be nice if it would be possible to profile a release build (like we can in Windows using Visual Studio), so it would be easier to pickup bottlenecks in native Android apps.

**Comment by DanAlbert** [comment]
I assume this is about simpleperf? @yabinc (though I suspect this is an OS restriction and you'll need to file a platform bug at b.android.com).

**Comment by yabinc** [comment]
Security doesn't allow profiling a release build apk freely on a user device. There are two ways to profile a release build apk:
1. Add <profileable android:shell="true" /> in the app's manifest to explicitly allow profiling through adb shell, as in https://android.googlesource.com/platform/system/extras/+/refs/heads/main/simpleperf/doc/android_application_profiling.md#prepare-an-android-application.
2.  On an eng or userdebug device, run `adb root` to gain root permission first, then you can profile any process.

**Comment by pirama-arumuga-nainar** [comment]
Closing per @yabinc's  comment above.
