### ISSUE TITLE
[BUG] vulkan.hpp accidentally included in sources/third_party/vulkan, very broken

### ISSUE THREAD

**Issue by sstarosz** [android/ndk#1974]
### Description

I updated the NDK version of my project from version 25.2.9519653 to 26.1.10909125, after which my Vulkan project stopped compiling due to errors in with repeated definitions in the vulkan.hpp header shipped with NDK 

`(26.1.10909125\sources\third_party\vulkan\src\include\vulkan\)`

Version 26.1.10909125 has a lot of repeated definitions in the vulkan.hpp and vulkan_enums.hpp headers. At least from these files come most of the compilation errors, I don't know if other files in the vulkan folder are not also affected.

<details>
<summary>Compilation output</summary>

```
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:1161:10: error: class member cannot be redeclared
    void link( void * dstBase, void const * srcBase, VkBaseOutStructure * dst, VkBaseInStructure const * src )
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:1149:10: note: previous definition is here
    void link( void * dstBase, void const * srcBase, VkBaseOutStructure * dst, VkBaseInStructure const * src )
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:1342:9: error: redefinition of 'DispatchLoaderBase'
  class DispatchLoaderBase
        ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:1318:9: note: previous definition is here
  class DispatchLoaderBase
        ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5881:7: error: class member cannot be redeclared
      vkSetDeviceMemoryPriorityEXT( VkDevice device, VkDeviceMemory memory, float priority ) const VULKAN_HPP_NOEXCEPT
      ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5552:10: note: previous definition is here
    void vkSetDeviceMemoryPriorityEXT( VkDevice device, VkDeviceMemory memory, float priority ) const VULKAN_HPP_NOEXCEPT
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5888:10: error: class member cannot be redeclared
    void vkGetDeviceBufferMemoryRequirementsKHR( VkDevice                                 device,
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5559:10: note: previous definition is here
    void vkGetDeviceBufferMemoryRequirementsKHR( VkDevice                                 device,
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5895:10: error: class member cannot be redeclared
    void vkGetDeviceImageMemoryRequirementsKHR( VkDevice                                device,
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5566:10: note: previous definition is here
    void vkGetDeviceImageMemoryRequirementsKHR( VkDevice                                device,
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5902:10: error: class member cannot be redeclared
    void vkGetDeviceImageSparseMemoryRequirementsKHR(
         ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:5573:10: note: previous definition is here
    void vkGetDeviceImageSparseMemoryRequirementsKHR( VkDevice                                device,
         ^
In file included from C:/Users/Sebastian/AndroidStudioProjects/AndroidVulkanDemo/Renderer/Source/StRenderer/Renderer.cpp:1:
In file included from C:/Users/Sebastian/AndroidStudioProjects/AndroidVulkanDemo/Renderer/Include/StRenderer/Renderer.hpp:8:
In file included from C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:6176:
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:1841:14: error: redefinition of 'MemoryMapFlagBits'
  enum class MemoryMapFlagBits : VkMemoryMapFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:1828:14: note: previous definition is here
  enum class MemoryMapFlagBits : VkMemoryMapFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:1941:14: error: redefinition of 'SemaphoreCreateFlagBits'
  enum class SemaphoreCreateFlagBits : VkSemaphoreCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:1928:14: note: previous definition is here
  enum class SemaphoreCreateFlagBits : VkSemaphoreCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2061:14: error: enumeration redeclared with different underlying type 'int' (was 'VkQueryPoolCreateFlags' (aka 'unsigned int'))
  enum class QueryPoolCreateFlagBits
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2048:14: note: previous declaration is here
  enum class QueryPoolCreateFlagBits : VkQueryPoolCreateFlags
             ^                         ~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2171:14: error: redefinition of 'BufferViewCreateFlagBits'
  enum class BufferViewCreateFlagBits : VkBufferViewCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2158:14: note: previous definition is here
  enum class BufferViewCreateFlagBits : VkBufferViewCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2772:14: error: redefinition of 'PipelineDynamicStateCreateFlagBits'
  enum class PipelineDynamicStateCreateFlagBits : VkPipelineDynamicStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2681:14: note: previous definition is here
  enum class PipelineDynamicStateCreateFlagBits : VkPipelineDynamicStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2781:14: error: redefinition of 'PipelineInputAssemblyStateCreateFlagBits'
  enum class PipelineInputAssemblyStateCreateFlagBits : VkPipelineInputAssemblyStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2694:14: note: previous definition is here
  enum class PipelineInputAssemblyStateCreateFlagBits : VkPipelineInputAssemblyStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2799:14: error: redefinition of 'PipelineMultisampleStateCreateFlagBits'
  enum class PipelineMultisampleStateCreateFlagBits : VkPipelineMultisampleStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2707:14: note: previous definition is here
  enum class PipelineMultisampleStateCreateFlagBits : VkPipelineMultisampleStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2808:14: error: redefinition of 'PipelineRasterizationStateCreateFlagBits'
  enum class PipelineRasterizationStateCreateFlagBits : VkPipelineRasterizationStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2720:14: note: previous definition is here
  enum class PipelineRasterizationStateCreateFlagBits : VkPipelineRasterizationStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2817:14: error: redefinition of 'PipelineTessellationStateCreateFlagBits'
  enum class PipelineTessellationStateCreateFlagBits : VkPipelineTessellationStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2733:14: note: previous definition is here
  enum class PipelineTessellationStateCreateFlagBits : VkPipelineTessellationStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2826:14: error: redefinition of 'PipelineVertexInputStateCreateFlagBits'
  enum class PipelineVertexInputStateCreateFlagBits : VkPipelineVertexInputStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2746:14: note: previous definition is here
  enum class PipelineVertexInputStateCreateFlagBits : VkPipelineVertexInputStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2835:14: error: redefinition of 'PipelineViewportStateCreateFlagBits'
  enum class PipelineViewportStateCreateFlagBits : VkPipelineViewportStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2759:14: note: previous definition is here
  enum class PipelineViewportStateCreateFlagBits : VkPipelineViewportStateCreateFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2978:14: error: redefinition of 'DescriptorPoolResetFlagBits'
  enum class DescriptorPoolResetFlagBits : VkDescriptorPoolResetFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:2965:14: note: previous definition is here
  enum class DescriptorPoolResetFlagBits : VkDescriptorPoolResetFlags
             ^
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:3354:14: error: redefinition of 'CommandPoolTrimFlagBits'
  enum class CommandPoolTrimFlagBits : VkCommandPoolTrimFlags
             ^
he command: "C:\Program Files\CMake\bin\cmake.EXE" --build C:/Users/Sebastian/AndroidStudioProjects/AndroidVulkanDemo/out/build/Android-armeabi-v7a-Debug --config Debug --target StRenderer exited with code: 1
C:/Users/Sebastian/AppData/Local/Android/Sdk/ndk/26.1.10909125/sources/third_party/vulkan/src/include/vulkan/vulkan_enums.hpp:3340:14: note: previous definition is here
  enum class CommandPoolTrimFlagBits : VkCommandPoolTrimFlags
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

</details>

Some errors look like typical merge mistakes, because the function code itself is the same, only the formatting is different:

Vulkan.hpp:
![image](https://github.com/android/ndk/assets/48087467/f325f974-2a1b-499a-a1f9-cc7126e9c223)

![image](https://github.com/android/ndk/assets/48087467/76da58b1-9b1d-4e73-9fa9-97437aad2347)

Vulkan_enums.hpp:
![image](https://github.com/android/ndk/assets/48087467/3fa364bf-6c88-4eb5-accc-19c390d82be3)

### Affected versions

r26

### Host OS

Windows

### Host OS version

19045.3693

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

24

**Comment by DanAlbert** [comment]
@cnorthrop

I'm not actually sure what that header is doing there. That directory I thought was just for the validation layers, which are no longer bundled with the NDK itself (https://github.com/android/ndk/issues/1374). As best as I can tell this was only ever included because the validation layers needed it to build?

You probably don't want the vulkan headers from that directory. You want the one from the sysroot, which is automatically on the `#include` search path. `vulkan.hpp` is _not_ something the graphics team currently supports. https://github.com/android/ndk/issues/1767 tracks that, but it's not actually something in my power to fix. That needs to come from the OS (it needs to exactly match the version of vulkan.h that ships with the OS headers).

The one time I tried using vulkan.hpp with the NDK, I did that by checking the vulkan version in the NDK (`VK_HEADER_VERSION` in `$NDK/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/vulkan/vulkan_core.h`), downloaded the matching version from https://github.com/KhronosGroup/Vulkan-Hpp/releases, and vendored that into my source tree. It was annoying that it wasn't included, but it worked fine (though tbh I actually found it easier to work with the C API since the hpp version was very poorly documented at the time, and the conversion between the two was not always obvious).

I suspect the actual fix you want here is "please support vulkan.hpp", which is that other bug I linked, and that in at least the short term we should be less confusing and delete the directory with the stale headers?

**Comment by sstarosz** [comment]
I wasn't sure about Vulkan-Hpp support, because on the one side there is a issue whether to support Vulkan-Hpp, on the other side you can find updated Vulkan-Hpp in NDK. So far, I've been using the headers from this folder because it was the easiest way for me to add Vulkan-Hpp to my project, but if you wants to remove it, I don't mind.

If it's not supported ofically, I agree that it should be removed because, somes people probably use those headers.....

I managed to find a way to add Vulkan-Hpp to my Android project using vcpkg and it seems to work for me
[Vcpkg: Using Vulkan SDK](https://learn.microsoft.com/en-us/vcpkg/users/platforms/android#using-vulkan-sdk)

Thank you for clarifying the situation

**Comment by DanAlbert** [comment]
Ah, I didn't realize that was in vcpkg. Yeah, that's probably your best bet. You may need to be cautious about matching the version to what's in the NDK sysroot as before though.

vcpkg does support AAR generation, which might be easier to integrate than the normal vcpkg output depending on what your build looks like (hard if you're not using gradle, but definitely easier to keep builds reproducible across your team if you are): https://learn.microsoft.com/en-us/vcpkg/users/platforms/android#consume-libraries-using-vcpkg-and-android-prefab-archives-aar-files

**Comment by DanAlbert** [comment]
> It's honestly better if this can just be band-aided in the NDK repo. Not sure where the right place for that fix is.

We ship directly from external/vulkan-headers. A band aid in the NDK repo would be a band aid in external/vulkan-headers. If we want to fix this in a point release of r26c, we could do that in the aosp/ndk-r26-release branch of that project, which wouldn't auto merge anywhere. That's an option, but since we didn't support this on purpose, and the OP sounds happy just using vcpkg until we do, we may not need to.

> and I don't know when I'm going to find the time to do that... January?

We're not shipping anything until January anyway.

> Hmm. I guess, is the explicit ask for me (as person with OS changing power) to just remove the duplicates above in external/vulkan-headers? It'll be annoying later on, but later-on Trevor has a lot more bandwidth than today-now Trevor.

The best thing would be to fix external/vulkan-headers when you're able, but also update https://cs.android.com/android/platform/superproject/main/+/main:external/vulkan-headers/Android.bp;l=51-56;drc=1783d5ae806ca53d8f180dc03f470712527072eb to include this header, which would let us close https://github.com/android/ndk/issues/1767. You may also want to add a test that does nothing but `#include <vulkan.hpp>` to make sure this doesn't regress :)

A fix for a future release of the NDK has even more time than until January, btw. I'd only need a fix by late Feb for that?

**Comment by trevordblack** [comment]
OK

I'll try to get to this late December or early January. I'd rather not push it to the end of the month.

**Comment by DanAlbert** [comment]
@trevordblack we're going to be cutting a release in the near future. I'm going to drop the headers that are being installed to `<NDK>/sources/third_party` since those weren't ever supposed to be there in the first place, but it'd be nice if we could pick up a new sysroot that has a proper vulkan.hpp at the same time :)

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/2924824 removes the broken and misleading stuff. Unclear whether or not we're going to be able to fix https://github.com/android/ndk/issues/1767 in r27, but it doesn't sound too likely right now.

**Comment by trevordblack** [comment]
We're working on fixing the broken build and should have that done within a week or two.
When it lands into the NDK is more Dan's department.

> I suspect the actual fix you want here is "please support vulkan.hpp", which is that other bug I linked, and that in at least the short term we should be less confusing and delete the directory with the stale headers?

After internal discussion we're not in a position to support the .hpp files, and so aren't going to be explicitly adding them

**Comment by DanAlbert** [comment]
> We're working on fixing the broken build and should have that done within a week or two.
> When it lands into the NDK is more Dan's department.

It'll go out in r27 beta 1 if that's the case 👍

**Comment by timprepscius** [comment]
For future readers of this thread.  Maybe it's fixed in r27.  But maybe you can't use that version for whatever reason.

If you go to the official VulkanHeaders on github, go through the release tags to match the one google is using.  I think it's 237 at the moment, not sure of new release.  

You can get get that repository-tag and then set up a directory with all of the ndk's vulkan/*.h and the VulkanHeaders/vulkab/*.hpp symbolically linked in, and it *seems* to work.

**Comment by DanAlbert** [comment]
The much better fix is to use vcpkg like sstarosz suggested above. The NDK's vulkan.hpp was only ever shipped by accident and thus never tested.

**Comment by timprepscius** [comment]
Possibly so, I would rather not.  Package managers are great until they aren't.

**Comment by DanAlbert** [comment]
In that case you're still better off getting it from somewhere else, like the official repo: https://github.com/KhronosGroup/Vulkan-Hpp. Just make sure you download the version that's matched to the vulkan.h in whatever NDK you're using.

**Comment by timprepscius** [comment]
I feel like your comment was generated by ChatGPT. That's hilarious.  To me.  At le a s  t.

By the way, if there was anyway you could make Vulkan work about the same across the Android devices, that would be great.  Every device has some problem.  It's like win32 all over again.  Anyway.
