### ISSUE TITLE
[Bug]: Building Library\Bee\artifacts\Android\a7sem\w7f5ojd1sl7e.o failed with output:

### ISSUE THREAD

**Issue by seoil0728** [android/ndk#1975]
### Description

Building Library\Bee\artifacts\Android\a7sem\w7f5ojd1sl7e.o failed with output:
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
```
Stack dump:
0.	Program arguments: "C:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++" -march=armv8-a -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -mllvm -hoist-common-insts=1 -DANDROID -DHAVE_INTTYPES_H -no-canonical-prefixes -funwind-tables -fstack-protector -fomit-frame-pointer -std=c++11 -Wswitch -Wno-trigraphs -Wno-tautological-compare -Wno-invalid-offsetof -Wno-implicitly-unsigned-literal -Wno-integer-overflow -Wno-shift-negative-value -Wno-unknown-attributes -Wno-implicit-function-declaration -Wno-null-conversion -Wno-missing-declarations -Wno-unused-value -Wno-pragma-once-outside-header -fvisibility=hidden -fexceptions -fno-rtti -g -Os -fPIC -fno-strict-overflow -ffunction-sections -fdata-sections -fmessage-length=0 -pipe -D_GLIBCXX_USE_CXX11_ABI=0 -DBASELIB_INLINE_NAMESPACE=il2cpp_baselib -DIL2CPP_MONO_DEBUGGER_DISABLED -DRUNTIME_IL2CPP -DTARGET_ARM64 -DHAVE_BDWGC_GC -DNDEBUG -I. -ID:/Workspace/BLUE1/Library/Bee/artifacts/Android/il2cppOutput/cpp "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/libil2cpp/pch" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/libil2cpp" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/external/baselib/Include" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/libil2cpp/os/ClassLibraryPAL/brotli/include" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/external/baselib/Platforms/Android/Include" -o Library/Bee/artifacts/Android/a7sem/w7f5ojd1sl7e.o -fcolor-diagnostics -fdiagnostics-absolute-paths -target aarch64-linux-android22 -fstrict-aliasing -fdiagnostics-format=msvc -c -x c++ D:/Workspace/BLUE1/Library/Bee/artifacts/Android/il2cppOutput/cpp/Assembly-CSharp__7.cpp

1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'D:/Workspace/BLUE1/Library/Bee/artifacts/Android/il2cppOutput/cpp/Assembly-CSharp__7.cpp'.
4.	Running pass 'AArch64 Instruction Selection' on function '@UIWrapContentExtension_ResetChildPositions_m5B698D44B7A062DF158F1B74ACA39AC02408DEC9'
 #0 0x00007ff6923d22a3 C:\Program Files\Unity\Hub\Editor\2022.3.14f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1c922a3 C:\Program Files\Unity\Hub\Editor\2022.3.14f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x4ab1e90
 #1 0x00007ff6923d22a3 C:\Program Files\Unity\Hub\Editor\2022.3.14f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x4ab1ec8 
0x00007FF6923D22A3 (0x000000ABCCFFA778 0x0000002000000000 0xF77203500000000B 0x00007FF6951F1E90)
0x0000022CFA1A66B0 (0x0000002000000000 0xF77203500000000B 0x00007FF6951F1E90 0x000000ABCCFFA7A0) <unknown module>
0x000000ABCCFFA778 (0xF77203500000000B 0x00007FF6951F1E90 0x000000ABCCFFA7A0 0x0000022CF5D04300) <unknown module>
0x0000002000000000 (0x00007FF6951F1E90 0x000000ABCCFFA7A0 0x0000022CF5D04300 0x000000ABCCFFA958) <unknown module>
0xF77203500000000B (0x000000ABCCFFA7A0 0x0000022CF5D04300 0x000000ABCCFFA958 0x00007FF6951F1EC8) <unknown module>
0x00007FF6951F1E90 (0x0000022CF5D04300 0x000000ABCCFFA958 0x00007FF6951F1EC8 0x0000000000000000)
0x000000ABCCFFA7A0 (0x000000ABCCFFA958 0x00007FF6951F1EC8 0x0000000000000000 0x0000022CF5D04300) <unknown module>
0x0000022CF5D04300 (0x00007FF6951F1EC8 0x0000000000000000 0x0000022CF5D04300 0x000000ABCCFFA958) <unknown module>
0x000000ABCCFFA958 (0x0000000000000000 0x0000022CF5D04300 0x000000ABCCFFA958 0x0000000000000000) <unknown module>
0x00007FF6951F1EC8 (0x0000022CF5D04300 0x000000ABCCFFA958 0x0000000000000000 0x0000000000000000)

clang++: error: clang frontend command failed due to signal (use -v to see invocation)

Android (7714059, based on r416183c1) clang version 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
Target: aarch64-unknown-linux-android22
Thread model: posix
InstalledDir: C:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:\Users\KIMSEO~1\AppData\Local\Temp\Assembly-CSharp__7-544223.cpp
clang++: note: diagnostic msg: C:\Users\KIMSEO~1\AppData\Local\Temp\Assembly-CSharp__7-544223.sh
clang++: note: diagnostic msg: 

********************

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

this error is shown when i build il2cpp in unity.
sometimes it builds succeed, but most of time, this error occurs or windows crash.
this unity version is 2022.3.14f1, but other version of unity engine shows similar error.

```
OS - Windows 10 Pro (build 19045)
CPU - Intel 14th 14700k
RAM - DDR5 32GB 5600Mhz
GPU - RTX 3080

Unity Version - 2022.3.14f1
NDK Version - 23.1.7779620 (r23b)
```

[temps.zip](https://github.com/android/ndk/files/13482502/temps.zip)

### Affected versions

r26

### Host OS

Windows

### Host OS version

windows 10 pro 19045

### Affected ABIs

x86_64

**Comment by seoil0728** [comment]
in additional, i tried to build in ndk r26b, but its same.

**Comment by seoil0728** [comment]
Sure!
and heres Files for bug reports.
[temps2.zip](https://github.com/android/ndk/files/13495403/temps2.zip)

i use the latest ndk r26b version (26.1.10909125)
and to use to build with unity, i change the 'source.properties' file.
(Pkg.Revision = 26.1.10909125 -> 23.1.7779620)

and this is the error of using r26b build.
Building Library\Bee\artifacts\Android\a7sem\rryifei4ktle.o failed with output:
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -march=armv8-a -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -mllvm -hoist-common-insts=1 -DANDROID -DHAVE_INTTYPES_H -no-canonical-prefixes -funwind-tables -fstack-protector -fomit-frame-pointer -std=c++11 -Wswitch -Wno-trigraphs -Wno-tautological-compare -Wno-invalid-offsetof -Wno-implicitly-unsigned-literal -Wno-integer-overflow -Wno-shift-negative-value -Wno-unknown-attributes -Wno-implicit-function-declaration -Wno-null-conversion -Wno-missing-declarations -Wno-unused-value -Wno-pragma-once-outside-header -fvisibility=hidden -fexceptions -fno-rtti -g -Os -fPIC -fno-strict-overflow -ffunction-sections -fdata-sections -fmessage-length=0 -pipe -D_GLIBCXX_USE_CXX11_ABI=0 -DBASELIB_INLINE_NAMESPACE=il2cpp_baselib -DIL2CPP_MONO_DEBUGGER_DISABLED -DRUNTIME_IL2CPP -DTARGET_ARM64 -DHAVE_BDWGC_GC -DNDEBUG -I. -ID:/Workspace/BLUE1/Library/Bee/artifacts/Android/il2cppOutput/cpp "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/libil2cpp/pch" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/libil2cpp" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/external/baselib/Include" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/libil2cpp/os/ClassLibraryPAL/brotli/include" "-IC:/Program Files/Unity/Hub/Editor/2022.3.14f1/Editor/Data/il2cpp/external/baselib/Platforms/Android/Include" -o Library/Bee/artifacts/Android/a7sem/rryifei4ktle.o -fcolor-diagnostics -fdiagnostics-absolute-paths -target aarch64-linux-android22 -fstrict-aliasing -fdiagnostics-format=msvc -c -x c++ D:/Workspace/BLUE1/Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.Common.cpp
1.	C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1/string:4121:8 <Spelling=C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1/__config:628:38>: current parser token '_LIBCPP_TOSTRING'
2.	C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1/string:605:1 <Spelling=C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1/__config:653:39>: parsing namespace 'std'
3.	C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1/string:605:1 <Spelling=C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1/__config:653:62>: parsing namespace 'std::__ndk1'
Exception Code: 0xC0000005
 #0 0x00007ff685da7130 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1687130)
 #1 0x00007ff68767a94f (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2f5a94f)
 #2 0x00007ff68767874b (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2f5874b)
 #3 0x00007ff687677bac (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2f57bac)
 #4 0x00007ff68767c031 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2f5c031)
 #5 0x00007ff685eaa1a2 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x178a1a2)
 #6 0x00007ff685da6d35 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1686d35)
 #7 0x00007ff68767a394 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2f5a394)
 #8 0x00007ff685da7169 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1687169)
 #9 0x00007ff688d466eb (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x46266eb)
#10 0x00007ff688d4629d (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x462629d)
#11 0x00007ff688d45a1e (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4625a1e)
#12 0x00007ff688d57c75 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4637c75)
#13 0x00007ff688d72652 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4652652)
#14 0x00007ff688d7158c (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x465158c)
#15 0x00007ff688d70ef6 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4650ef6)
#16 0x00007ff688d50c82 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4630c82)
#17 0x00007ff6885f680c (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3ed680c)
#18 0x00007ff688d29d1e (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4609d1e)
#19 0x00007ff688d29388 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4609388)
#20 0x00007ff688d50ffe (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4630ffe)
#21 0x00007ff6885f680c (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3ed680c)
#22 0x00007ff688d29d1e (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4609d1e)
#23 0x00007ff688d29388 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4609388)
#24 0x00007ff688d50d24 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4630d24)
#25 0x00007ff6885f680c (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3ed680c)
#26 0x00007ff6885f4db4 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3ed4db4)
#27 0x00007ff68775cd9e (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x303cd9e)
#28 0x00007ff685e85264 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1765264)
#29 0x00007ff684e1a7a4 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6fa7a4)
#30 0x00007ff684e9fccf (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x77fccf)
#31 0x00007ff684728941 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x8941)
#32 0x00007ff684725432 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x5432)
#33 0x00007ff685c4add6 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x152add6)
#34 0x00007ff684c6d31d (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x54d31d)
#35 0x00007ff685c4a711 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x152a711)
#36 0x00007ff684dd83b6 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6b83b6)
#37 0x00007ff684dd862e (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6b862e)
#38 0x00007ff684df2c9b (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6d2c9b)
#39 0x00007ff6847246be (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x46be)
#40 0x00007ff684721395 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1395)
#41 0x00007ff6847214c8 (C:\ndkr26b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x14c8)
#42 0x00007fff78a87344 (C:\WINDOWS\System32\KERNEL32.DLL+0x17344)
#43 0x00007fff79e026b1 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x526b1)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (10552028, based on r487747d) clang version 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d16663d5012e5c09495f3b30ece3d2362)
Target: aarch64-unknown-linux-android22
Thread model: posix
InstalledDir: C:/ndkr26b/toolchains/llvm/prebuilt/windows-x86_64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:/Users/KIMSEO~1/AppData/Local/Temp/GoogleMobileAds-5c6e1a.cpp
clang++: note: diagnostic msg: C:/Users/KIMSEO~1/AppData/Local/Temp/GoogleMobileAds-5c6e1a.sh
clang++: note: diagnostic msg: 

********************

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by pirama-arumuga-nainar** [comment]
Sorry for the delay in looking at this.

The reproducer for r26b passes for me on linux.  The error message (`clang++: error: clang frontend command failed due to signal (use -v to see invocation)`) is common when there is memory pressure due to the number of processes.  Can you see if it crashes regularly?

Another point to note is that the crash with r25 and r26 are different sources.

**Comment by pirama-arumuga-nainar** [comment]
Please re-open if there's a crash in r26 (with reproducer).

**Comment by FahimKamal** [comment]
Hello, I'm facing the same problem. 

```
Building Library\Bee\artifacts\Android\iz17e\q9xdm0lmm4eb.o failed with output:
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: C:/UnityEditors/2022.3.5f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -march=armv7-a -mfloat-abi=softfp -mfpu=neon-fp16 -marm -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -mllvm -hoist-common-insts=1 -DANDROID -DHAVE_INTTYPES_H -no-canonical-prefixes -funwind-tables -fstack-protector -fomit-frame-pointer -std=c++11 -Wswitch -Wno-trigraphs -Wno-tautological-compare -Wno-invalid-offsetof -Wno-implicitly-unsigned-literal -Wno-integer-overflow -Wno-shift-negative-value -Wno-unknown-attributes -Wno-implicit-function-declaration -Wno-null-conversion -Wno-missing-declarations -Wno-unused-value -Wno-pragma-once-outside-header -fvisibility=hidden -fexceptions -fno-rtti -g -Os -fPIC -fno-strict-overflow -ffunction-sections -fdata-sections -fmessage-length=0 -pipe -D_GLIBCXX_USE_CXX11_ABI=0 -DBASELIB_INLINE_NAMESPACE=il2cpp_baselib -DIL2CPP_MONO_DEBUGGER_DISABLED -DRUNTIME_IL2CPP -DHAVE_BDWGC_GC -DNDEBUG -I. "-ID:/Unity Projects/Unity_Boat_Blitz_v2/Boat Blitz Clone/Library/Bee/artifacts/Android/il2cppOutput/cpp" -IC:/UnityEditors/2022.3.5f1/Editor/Data/il2cpp/libil2cpp/pch -IC:/UnityEditors/2022.3.5f1/Editor/Data/il2cpp/libil2cpp -IC:/UnityEditors/2022.3.5f1/Editor/Data/il2cpp/external/baselib/Include -IC:/UnityEditors/2022.3.5f1/Editor/Data/il2cpp/libil2cpp/os/ClassLibraryPAL/brotli/include -IC:/UnityEditors/2022.3.5f1/Editor/Data/il2cpp/external/baselib/Platforms/Android/Include -o Library/Bee/artifacts/Android/iz17e/q9xdm0lmm4eb.o -fcolor-diagnostics -fdiagnostics-absolute-paths -target armv7a-linux-androideabi22 -fstrict-aliasing -fdiagnostics-format=msvc -c -x c++ "D:/Unity Projects/Unity_Boat_Blitz_v2/Boat Blitz Clone/Library/Bee/artifacts/Android/il2cppOutput/cpp/Unity.RenderPipelines.Universal.Runtime__1.cpp"
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'D:/Unity Projects/Unity_Boat_Blitz_v2/Boat Blitz Clone/Library/Bee/artifacts/Android/il2cppOutput/cpp/Unity.RenderPipelines.Universal.Runtime__1.cpp'.
4.	Running pass 'ARM Instruction Selection' on function '@ClipperOffset_DoMiter_m7050BFCD4EA5A0BF0DE873A01698D1D61F9F42F8'
 #0 0x00007ff7fca431c8 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1c931c8)
 #1 0x00007ff7fc69ade4 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x18eade4)
 #2 0x00007ff7fc69ab55 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x18eab55)
 #3 0x00007ff7fc69a2ac (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x18ea2ac)
 #4 0x00007ff7fc697ee5 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x18e7ee5)
 #5 0x00007ff7fb7a7514 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x9f7514)
 #6 0x00007ff7fb57af23 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x7caf23)
 #7 0x00007ff7fafea748 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x23a748)
 #8 0x00007ff7faff0f53 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x240f53)
 #9 0x00007ff7fafeaf72 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x23af72)
#10 0x00007ff7fc02d1e1 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x127d1e1)
#11 0x00007ff7fc388683 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x15d8683)
#12 0x00007ff7fd6c4b13 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2914b13)
#13 0x00007ff7fc2f0374 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1540374)
#14 0x00007ff7fb479da0 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6c9da0)
#15 0x00007ff7fb4f4473 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x744473)
#16 0x00007ff7fadb6482 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6482)
#17 0x00007ff7fadb4661 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x4661)
#18 0x00007ff7fc104156 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1354156)
#19 0x00007ff7fb327d11 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x577d11)
#20 0x00007ff7fc103bf4 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1353bf4)
#21 0x00007ff7fb442424 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x692424)
#22 0x00007ff7fb442809 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x692809)
#23 0x00007ff7fb455786 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x6a5786)
#24 0x00007ff7fadb3dcd (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3dcd)
#25 0x00007ff7fadb1395 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1395)
#26 0x00007ff7fadb14c8 (C:\UnityEditors\2022.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x14c8)
#27 0x00007fff6093257d (C:\Windows\System32\KERNEL32.DLL+0x1257d)
#28 0x00007fff6158aa58 (C:\Windows\SYSTEM32\ntdll.dll+0x5aa58)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (7714059, based on r416183c1) clang version 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
Target: armv7a-unknown-linux-android22
Thread model: posix
InstalledDir: C:/UnityEditors/2022.3.5f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:\Users\Fahim\AppData\Local\Temp\Unity-518d1e.cpp
clang++: note: diagnostic msg: C:\Users\Fahim\AppData\Local\Temp\Unity-518d1e.sh
clang++: note: diagnostic msg: 

********************

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

```

Any suggestion on how can I solve the issue. 

Same project, same settings on my office PC everything works just fine. But My Home PC is causing this error. 

My home PC configuration is:
<br>Motherboard: `Assus PRIME Z790 P CSM (WiFi)`
<br>Processor: `14900K`
<br>RAM: `G. Skill Trident Z5 DDR5 6000MHz 16GB X2`
<br>GPU: `MSI GEFORCE RTX 4070 Ti GAMING X TRIO`

**Comment by FahimKamal** [comment]
After a lot of internet searching and discussing with others I found a solution for my problem.

Usually when you use dual RAM sticks you install them on 2-4 or 1-3 slots of your motherboard. In my case it was 2-4 slots. I confirmed it by reading the user manual and on the web. But for some reason it was causing problem for Unity when I tried to build my project for android.

So now I installed my RAM sticks on 3-4 slots. Basically, instead of dual channel now I'm using single channel and unity seems to like it. I can build my projects with no problem.

**Comment by BM-Code-F** [comment]
Im pretty sure this might be realted to the known itel 13 and 14th gen issues, my laptop with way worse hardware build all my unity projects as my desktop using a 13900k fails, [](https://au.pcmag.com/processors/106560/intels-raptor-lake-desktop-cpu-bug-what-to-know-what-to-do-now). And it seems you are using a 14700k.
