### ISSUE TITLE
[BUG] r26b erroneously marks std:system() as non-null

### ISSUE THREAD

**Issue by agrieve** [android/ndk#1976]
### Description

This showed up when trying to update NDK in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1505825

According to https://en.cppreference.com/w/c/program/system, the parameter can be null, but `toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdlib.h` marks it as:
```
int system(const char* _Nonnull __command);
```

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

Chrome

### minSdkVersion

24

**Comment by DanAlbert** [comment]
The docs hint that this is probably trying to protect you from something that won't behave as expected on Android:

```
/**
 * [system(3)](http://man7.org/linux/man-pages/man3/system.3.html) executes
 * the given command in a new shell process.
 *
 * On Android, the special case of `[system](https://source.corp.google.com/h/googleplex-android/platform/superproject/main/+/main:bionic/libc/bionic/system.cpp;drc=cb4b90e51702b0dcf9ad09739084e747d8fd3220;l=39)(NULL)` always returns 1,
 * as specified by POSIX. Passing `NULL` to determine whether or
 * not a shell is available is not portable. Callers should just try
 * the command they actually want to run, since there are many reasons
 * why it might fail, both temporarily (for lack of resources, say)
 * or permanently (for lack of permission, say).
 *
 * Returns -1 and sets errno if process creation fails; returns a
 * [waitpid(2)](http://man7.org/linux/man-pages/man2/waitpid.2.html)
 * status otherwise.
 */
```

But that's perhaps a bit aggressive. @enh-google @ZijunZhaoCCK, was that intentional for the reason above?

**Comment by DanAlbert** [comment]
The check in the fuzzer that's being flagged is in fact a no-op on POSIX systems: https://pubs.opengroup.org/onlinepubs/9699919799/functions/system.html

> The `system()` function shall always return non-zero when `command` is `NULL`.

**Comment by enh-google** [comment]
yeah, we had this argument over on the Austin group mailing list too (that maybe POSIX is a bit weak here), but found no support for that argument. given that, we've left Android's implementation untouched, and kept the "this probably doesn't do what you think it does" attribute and comment.
