### ISSUE TITLE
[FR] Add a BatteryManager native utility

### ISSUE THREAD

**Issue by ContingencyOfTautologicalContradictions** [android/ndk#1979]
### Description

Having the option of requesting the battery information of the device natively would be a nice enhancement for the NDK

**Comment by DanAlbert** [comment]
We don't make the APIs, we just ship them. You wanted this section:

![image](https://github.com/android/ndk/assets/315852/fb8fb58c-b102-481c-9eac-2a27e09b47f3)

You might be wanting me to go advocate for this API on your behalf, but they're more likely to listen to you than they are to me. I'm not an app developer so my opinion in this matter is worth very little. They won't be able to do anything without you available to answer follow up questions anyway.
