### ISSUE TITLE
[BUG] How to use `ASurfaceControl_createFromWindow()` with `ANativeActivity`?

### ISSUE THREAD

**Issue by MarijnS95** [android/ndk#1983]
### Description

When calling `ASurfaceControl_createFromWindow()` on the `NativeWindow` received in `onNativeWindowCreated`, my API level 33 phone (Xperia 1 IV, Android 13) complains:

```
SurfaceComposerClient: SurfaceComposerClient::createWithSurfaceParent error Invalid argument
```

And the returned pointer is NULL.

On an Android 14 Samsung S22 Ultra, the return argument is also NULL but no error message is printed (the code linked below seems to have changed slightly in Android 14).

I'm inclined to believe that this message perhaps originates from:

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r74:frameworks/native/services/surfaceflinger/Client.cpp;l=94-96https://cs.android.com/android/platform/superproject/+/android-13.0.0_r74:frameworks/native/libs/gui/SurfaceComposerClient.cpp;l=2101

---

It is also not working on a `SurfaceTexture`->`Surface` from a `<TextureView>`, but it _does_ work on a `Surface` from a `<SurfaceView>`.

Is this intended? I'd like to create and position new surfaces within a native activity _without_ having to create a `SurfaceView` in Java.

### Affected versions

r26

### Host OS

Linux

### Host OS version

Arch Linux

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

Both Mozilla's rust-android-gradle as well as a native library/APK build from https://github.com/rust-mobile/xbuild

### minSdkVersion

28, 33, 34

### Device API level

33 and 34

**Comment by MarijnS95** [comment]
As far as I understand from the [`getWindow().takeSurface(this)` call that `NativeActivity` does](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/app/NativeActivity.java;l=133;drc=5d123b67756dffcfdebdb936ab2de2b29c799321) this should be a surface from a "root?" `SurfaceView`. The [`SurfaceView#getSurfaceControl()` getter is documented as](https://developer.android.com/reference/android/view/SurfaceView#getSurfaceControl()):

> Return a SurfaceControl which can be used for parenting Surfaces to this SurfaceView. Note that this SurfaceControl is effectively read-only. Its only well-defined usage is in using the SurfaceControl as a parent for an application's hierarchy of SurfaceControls. All other properties of the SurfaceControl, such as its position, may be mutated by the SurfaceView at any time which will override what the application is requesting. Do not apply any [SurfaceControl.Transaction](https://developer.android.com/reference/android/view/SurfaceControl.Transaction) to this SurfaceControl except for reparenting child SurfaceControls. See: [SurfaceControl.Transaction#reparent](https://developer.android.com/reference/android/view/SurfaceControl.Transaction#reparent(android.view.SurfaceControl,%20android.view.SurfaceControl)).

I'd very much like to use it for that; reparenting (new) child surfaces ("new", assuming `ASurfaceControl_create(parent, debug_name)` is available for that). But perhaps also for dispatching new `HardwareBuffer`s to a `Surface`, is that allowed?
(If not, creating a child surface with the same size should solve that)

---

On that note, since there is a Java representation for `SurfaceControl` and `SurfaceTransaction`, should there be JNI interop functions?

EDIT: The Java->C transition seems to have been added in API 34 and should show up in the next (r26c or r27?) NDK release: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/include/android/surface_control_jni.h

It seems functionality is somewhat disjoint; Java allows [creating a `SurfaceControl` with quite a a few parameters](https://developer.android.com/reference/android/view/SurfaceControl.Builder) while in C it is only possible to create one from a parent `Surface`/`SurfaceControl` (with a debug name) but all other parameters are "set" using a transaction. Except for the buffer size and format of `the controlled surface's buffers`: 

I don't see how a `Surface` or those "controlled surface's buffers" mentioned there are retrieved from a `SurfaceControl` in C. [Java has a constructor for this](https://developer.android.com/reference/android/view/Surface#Surface(android.view.SurfaceControl)), but does the "C counterpart" not manage buffers?

Instead, thus far I've been playing with an [`ImageReader`](https://developer.android.com/ndk/reference/group/media#aimagereader) to get access to a producer, and send acquired images to a `surfaceControl` via [`ASurfaceTransaction_setBuffer()`](https://developer.android.com/ndk/reference/group/native-activity#asurfacetransaction_setbuffer).

Same disjoint observation for transactions: C bindings allow setting HDR metadata, [Java bindings](https://developer.android.com/reference/android/view/SurfaceControl.Transaction) do not (note that there are some new Java functions on API 34, they are available in C but are also not yet in an NDK release).

---

And regarding [HDR metadata functions](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/include/android/surface_control.h;l=503-527;drc=172d5a3281d6b1dd1e6cf5871db2484098f14dc2), they only read the structs and should have `const` added to the pointer.

**Comment by DanAlbert** [comment]
In general, this isn't going to be the place to ask "how does this API work?" type questions, because you know way more than we do. We neither make nor use these APIs; the NDK is just the delivery vehicle for the sysroot. Our mailing list (linked in the [readme.md](https://github.com/android/ndk?tab=readme-ov-file#other-resources)) often will have other users that know the answer (and there are some framework folks that monitor that too), but if you need to talk to someone that works on the API, file a framework bug following b.android.com.

(that said, I've DM'd this to someone that might know)

Closing since there doesn't appear to be an NDK bug here.

**Comment by DanAlbert** [comment]
>> It is also not working on a SurfaceTexture->Surface from a <TextureView>
>
> this is WAI

They don't know about the other bit (it doesn't work with native activity).

**Comment by MarijnS95** [comment]
That makes sense after what was explained to me in the other issues.
 
> They don't know about the other bit (it doesn't work with native activity).

Will that contact get back here with more information about the `SurfaceView`->`Surface`->`NativeWindow` that is passed to `ANativeActivity` users, or should I open a new issue on b.android.com (assuming someone can triage/assign it to the relevant person)? Thanks for putting this through, by the way.

---

> > > It is also not working on a SurfaceTexture->Surface from a
> > 
> > this is WAI [Working As Intended, had to look that up]

That makes sense in hindsight. `SurfaceTexture` is a mechanism that uploads images to OpenGL textures, to present them in a view. The producer-end (`Surface`) from which it performs these uploads is thus not part of the view hierarchy (not on screen) [^1] and can thus not be controlled by the composer via a `SurfaceTransaction`.

[^1]: This is what I assume it is doing from reading https://developer.android.com/reference/android/graphics/SurfaceTexture. It would not be very efficient when already having a presentable image / `HardwareBuffer` on the GPU, that's what a `SurfaceView` `would be for.

Fortunately, as found in the followup-comment above, `NativeActivity` is using a `SurfaceView` and not a `TextureView` with `SurfaceTexture`. The limitation must lie elsewhere.

**Comment by DanAlbert** [comment]
> Will that contact get back here with more information about the SurfaceView->Surface->NativeWindow that is passed to ANativeActivity users, or should I open a new issue on b.android.com (assuming someone can triage/assign it to the relevant person)?

Open a framework issue via b.android.com. I don't understand the APIs well enough to even really understand the question (which is why I'm woefully inadequate to be a middle man, and am forwarding you along instead 🙂). We can definitely help it get triaged correctly though. If you don't see a response within a week, post the link here and we'll see if it was mistriaged (it happens, same problem as us, the people doing the triage don't necessarily know enough to triage appropriately on the first try, but I can at least try with `git blame`).

**Comment by MarijnS95** [comment]
Sure! I'll reformat the request a bit (while also structuring all the additional questions around this API more properly), perhaps with a minimal example (written in Rust, though it should be easy to translate it to C) to demonstrate what I would like to achieve.

**Comment by DanAlbert** [comment]
FWIW, you might get less response if your example is written in rust. The assignee doesn't necessarily know rust, and effectively none of us know how the rust builds work for apps.

**Comment by MarijnS95** [comment]
That will cause some struggles as there's a lot of extra boiler-plate to set up.

**Comment by DanAlbert** [comment]
Up to you, but the less unsupported your sample is, the more likely it'll get looked at (remember that, same as anywhere else, everyone here is massively oversubscribed, so the more complicated something is, so the easier the thing looks, the more likely it'll go at the top of the todo list).

**Comment by MarijnS95** [comment]
Surely I can just clone https://github.com/android/ndk-samples/tree/master/native-activity and extend that with a minimal repro. Everyone should be aware how to use Android Studio I hope.

**Comment by MarijnS95** [comment]
Cross-posted to https://issuetracker.google.com/issues/320706287, with a link to a reproducer example.

**Comment by DanAlbert** [comment]
> Everyone should be aware how to use Android Studio I hope.

No, actually. That's probably rare knowledge among OS developers. It's a thing we support though, so I expect they'll figure it out :)

**Comment by MarijnS95** [comment]
Phew, how should I send reproducers: `make run` with a custom `ndk-build`, `adb push`, `adb shell am start` combination?

**Comment by DanAlbert** [comment]
A Studio project is far enough imo. If a makefile is easier for you, that's probably also fine. The first thing I do when I'm given a Studio project is remove Studio from the equation, but idk about others.

**Comment by MarijnS95** [comment]
@DanAlbert this requires running on the device. I can provide an alternate sample based on https://github.com/DanAlbert/dynamic-cast-repro if upstream needs it.
