### ISSUE TITLE
[BUG]why NDK r17c can compile successfully and r25b cannot?

### ISSUE THREAD

**Issue by xxxxxxLD** [android/ndk#1984]
### Description

I ndk-build the code with NDK r17c, it wodks successfully, and it doesn't work in NDK r25b，with the same code and android.mk files, the error shows in the picture below, and the code doesn't have any atomic operation. How to solve this problem? Is this the NDK r25b's bug?
The error shows: undefined symbol: __aarch64_ldadd4_cag_re >>> referenced by atomic:1021 (/buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/include/atomic:1021 ios.o:(std::ndki:ios basetxalloc(>in archive D:/xxx/android-ndk-r25b-vindous/android-ndk-r25b/build/../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_static.a

### Affected versions

r26

### Host OS

Windows

### Host OS version

Windows server 2012 R2

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

r17c--r25b

### Device API level

34

**Comment by appujee** [comment]
please provide more details about the bug like:
- file that resulted in error
- build commands that you used

Also, the picture you refer to is missing.

**Comment by xxxxxxLD** [comment]
> The errors are: undefined symbol:__cax_allocate_exception,referenced by stdexcept:257 (D:/android-ndk-r26b/build/../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/stdexcept: 257)  
D:/vdot/obj/local/arm64-v8a/objs/vdot_so/_//common/src_xml/pugixml.o:<std::ndk1::__throw_length_error[abi:v170000](const char *)>

> build command is ndk-build -B.

**Comment by pirama-arumuga-nainar** [comment]
The original error was about undefined `__aarch64_ldadd4_cag_re` which is specific to atomic operations while the second report has unrelated symbols.  `r26` is the latest release and `r25` is unsupported.  For the failure with `r26`, add `Wl,--reproduce=repro.tar` to the failing linker command and share `repro.tar`.

**Comment by DanAlbert** [comment]
Not enough information. You need to provide a repro case before it's possible for us to help. Will reopen if we get that.
