### ISSUE TITLE
[Bug]: `__attribute__((preserve_all))` crashes on aarch64

### ISSUE THREAD

**Issue by licy183** [android/ndk#1988]
### Description

Compiling the following source and clang will crash with `Unsupported calling convention.`.

Source:

```c
// test.c
__attribute__((preserve_all)) float bar(float a);

float run(float foo) {
    return bar(foo);
}
```

Repro:
```
r26/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang -c test.c -O2
```

Crash log:
```
fatal error: error in backend: Unsupported calling convention.
clang-17: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Android (10552028, +pgo, +bolt, +lto, -mlgo, based on r487747d) clang version 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d16663d5012e5c09495f3b30ece3d2362)
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /home/builder/lib/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin
clang-17: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-17: note: diagnostic msg: /tmp/main-538331.c
clang-17: note: diagnostic msg: /tmp/main-538331.sh
clang-17: note: diagnostic msg:

********************
```

### Upstream bug

https://github.com/llvm/llvm-project/issues/58145

### Commit to cherry-pick

https://github.com/llvm/llvm-project/commit/d75e70d7ae1f84cea71f0be5fbee836bdc22138a

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu 22.04

### Affected ABIs

arm64-v8a

**Comment by pirama-arumuga-nainar** [comment]
Thanks for finding the llvm-project bug and fix.  However,
* this is not a regression from r25
* the "fix" is to _add_ support for the `preserve_all` calling convention to aarch64.

Considering this, we shouldn't backport the fix to r26.  Please wait for r27.
