### ISSUE TITLE
make_standalone_toolchain.py doesn't support rv64

### ISSUE THREAD

**Issue by enh-google** [android/ndk#1990]
### Description

make-standalone-toolchain came up in the risc-v Android SIG meeting today. (because it doesn't have riscv64 in it.) it seems unfortunate that we're explaining in 2024 that the only thing they need to know about it is that it's obsolete...

do we think there are enough people stuck on make-standalone-toolchain _and_ using a current NDK to be worth keeping this? if so, isn't that an argument that we should add the missing line for riscv64 (at _some_ time between now and any Play "you need to target this architecture too" decision)? if not, is this a good time to just remove it and consign it to the dustbin of history?

### Affected versions

r26

### Host OS

Linux

### Host OS version

(why do i have to choose a host os when the answer is "all" :-) )

### Affected ABIs

armeabi-v7a

### Build system

Other (specify below)

### Other build system

(all ABIs, but only custom build systems)

### minSdkVersion

any

**Comment by DanAlbert** [comment]
> do we think there are enough people stuck on make-standalone-toolchain and using a current NDK to be worth keeping this?

We have no data, so impossible to say for sure. I expect it's still in use because it's remained functional, and if it's not costing anyone to keep using it, why migrate? It's always been an edge use case, but I can't guess at how many users (I know it's non-zero because I've spoken to at least one, but that's about all I know) actually switched off it once it became unnecessary.

> do we think there are enough people stuck on make-standalone-toolchain and using a current NDK to be worth keeping this? if so, isn't that an argument that we should add the missing line for riscv64 (at some time between now and any Play "you need to target this architecture too" decision)? if not, is this a good time to just remove it and consign it to the dustbin of history?

I think my preference would be to keep it around as a canary for now. If we see a lot of bug reports about it missing rv64 support, maybe we should just add that. More likely, no one says anything because they've either moved on already, or do so when they read the "you don't need this and it's just slowing you down" warning that comes with the "rv64 is not supported" error message, and we can feel more confident about removing it in a year or so.

It's not really costing us anything to maintain (though the tests for it are actually some of the slower ones due to all the I/O), but I'd sure prefer to remove it since its existence probably misleads a few users. It's not _wrong_ to use it, but it does add an unnecessary extra build cost, and since it's yet another variable, it's just another opportunity for things to go wrong.

**Comment by enh-google** [comment]
well, as you probably guessed, the reason _i'm_ asking is because _i_ was asked about the missing riscv64 support. (funnily enough, by someone new to Android who thought this sounded like a good choice and who didn't know that effectively all toolchains are now standalone toolchains.)

if we're not going to remove it, and we [reasonably] don't think we can fix the internet to stop making it look like a reasonable choice and/or fix everyone's existing build files, i think we should just fix it. especially because i looked and _we_ did have to maintain it, specifically to _explicitly reject_ riscv64 --- when we could have just added it with fewer lines and one less special case!

https://android-review.googlesource.com/c/platform/ndk/+/2907781 makes riscv64 just like all the others. (though "remove this for everyone" would also be consistent, and i don't have a strong preference other than "having it there but not work for all architectures just makes us look silly/seem like assholes". _especially_ because it's literally a smaller change to have it just work!)

**Comment by DanAlbert** [comment]
> well, as you probably guessed, the reason i'm asking is because i was asked about the missing riscv64 support. (funnily enough, by someone new to Android who thought this sounded like a good choice and who didn't know that effectively all toolchains are now standalone toolchains.)

Someone that actually wanted to use it, or someone that made a checklist of things that the other ABIs had and compared without asking whether the items in the list were actually useful? We've definitely seen people add support for working with standalone toolchains just because someone told them "support the NDK", and that was part of the NDK, even if it was a pointless part.

> who thought this sounded like a good choice and who didn't know that effectively all toolchains are now standalone toolchains.

Are you sure? When you run the script the only thing it prints is:

```
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm64 --api 21 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ src.cpp
```

> i think we should just fix it. especially because i looked and we did have to maintain it, specifically to explicitly reject riscv64 --- when we could have just added it with fewer lines and one less special case!
>
> https://android-review.googlesource.com/c/platform/ndk/+/2907781 makes riscv64 just like all the others. (though "remove this for everyone" would also be consistent, and i don't have a strong preference other than "having it there but not work for all architectures just makes us look silly/seem like assholes". especially because it's literally a smaller change to have it just work!)

SGTM though. Like I said this doesn't really cost us anything so I'm not in a hurry to remove it. The only upside is that it might be confusing to keep useless interfaces around.

**Comment by enh-google** [comment]
> Someone that actually wanted to use it

someone trying to answer the question "how do i build?". (i wonder if people are getting linked directly to something like https://developer.android.com/ndk/guides/standalone_toolchain#building_open_source_projects_using_standalone_toolchains and missing the "obsolete" that's only at the _top_ of the page?)

> We've definitely seen people add support for working with standalone toolchains just because someone told them "support the NDK", and that was part of the NDK, even if it was a pointless part.

yeah, and maybe the only way to get out of this mess is to delete the damn thing?

> Are you sure? When you run the script the only thing it prints is <message saying "don't use this">

maybe, but if they're like me, they did this:
```
~/Downloads/android-ndk-r26b$ ./build/tools/make_standalone_toolchain.py 
usage: make_standalone_toolchain.py [-h] --arch {arm,arm64,x86,x86_64}
                                    [--api API] [--stl STL] [--force] [-v]
                                    [--package-dir PACKAGE_DIR | --install-dir INSTALL_DIR]
make_standalone_toolchain.py: error: the following arguments are required: --arch
~/Downloads/android-ndk-r26b$ ./build/tools/make_standalone_toolchain.py --arch riscv64
usage: make_standalone_toolchain.py [-h] --arch {arm,arm64,x86,x86_64} [--api API] [--stl STL] [--force] [-v]
                                    [--package-dir PACKAGE_DIR | --install-dir INSTALL_DIR]
make_standalone_toolchain.py: error: argument --arch: invalid choice: 'riscv64' (choose from 'arm', 'arm64', 'x86', 'x86_64')
~/Downloads/android-ndk-r26b$ 
```

> SGTM though. Like I said this doesn't really cost us anything so I'm not in a hurry to remove it. The only upside is that it might be confusing to keep useless interfaces around.

i've gone back and forth several times just during this conversation! i really can't decide. (though i am still pretty convinced that "exists, but broken for riscv64" is the _worst_ of the three options!)

**Comment by DanAlbert** [comment]
> maybe, but if they're like me, they did this:

Ah, right. https://android-review.googlesource.com/c/platform/ndk/+/2908744 fixes that.

> Someone that actually wanted to use it

someone trying to answer the question "how do i build?". (i wonder if people are getting linked directly to something like https://developer.android.com/ndk/guides/standalone_toolchain#building_open_source_projects_using_standalone_toolchains and missing the "obsolete" that's only at the top of the page?)

r19 is far enough behind us that maybe we should just delete the content of that page...

**Comment by enh-google** [comment]
> r19 is far enough behind us that maybe we should just delete the content of that page...

yeah, that sounds like a good idea too.

(though i _still_ feel like we should either remove make_standalone_toolchain.py itself, or make it work!)

**Comment by DanAlbert** [comment]
> (though i still feel like we should either remove make_standalone_toolchain.py itself, or make it work!)

Yeah, making it work is the path of least resistance, so let's just do that. (Isn't that what your already-merged CL does, or are there some other missing pieces?)

**Comment by DanAlbert** [comment]
Sent a CL to redirect the standalone_toolchain page links to the newer doc, and deleting the old doc.

**Comment by enh-google** [comment]
> Isn't that what your already-merged CL does, or are there some other missing pieces?

well, i didn't actually hit submit yet (in part because i was confused by your claim that the to-be-used argument would cause a lint failure but treehugger seemed happy), but you were pointing out that it's wrong if you ask for riscv64 but don't ask for a specific abi (because the current default is 21), and that should glob through the sysroot?

**Comment by DanAlbert** [comment]
> well, i didn't actually hit submit yet 

Ah, okay.

> (in part because i was confused by your claim that the to-be-used argument would cause a lint failure but treehugger seemed happy)

We can't run the lints in CI because Android more or less doesn't support Python development.

> but you were pointing out that it's wrong if you ask for riscv64 but don't ask for a specific abi (because the current default is 21), and that should glob through the sysroot?

Ah, I thought you were just going to hard code that for now and leave me to clean up later. Gotcha.

**Comment by enh-google** [comment]
my stupid implementation is in (which should work fine as long as you give a valid api level), but over to danalbert to make it look at the sysroot for a better answer...
