### ISSUE TITLE
[BUG]Undefined symbol :operator new[](unsigned long) when using r25 or r26 version of NDK

### ISSUE THREAD

**Issue by xxxxxxLD** [android/ndk#1995]
### Description

The same code and the same Android.mk compiled by NDK r19, it works successfully, but using r25 or r26 it appears some error,such as 

> undefined symbol: operator new[](unsigned long) 

> undefined symbol: __cxa_begin_catch

and the **LOCAL_FDFLAGS:=-nodefaultlibs -lc -lm -ldl**.
When add libgcc.a in linked libraries, NDK r26 can build successfully.The higher NDK removes gcc and uses llvm instead,so Is this  the reason of title said?

### Affected versions

r26

### Host OS

Windows

### Host OS version

Windows server 2012 R2

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

r19

**Comment by DanAlbert** [comment]
> `-nodefaultlibs`

That's what this does. You've excluded the C++ stdlib, which provides the definition for `new`. Older versions of Clang had a bug where `-lstdc++` was passed to the linker even when it should not have been. Why are you passing that flag?

> When add libgcc.a in linked libraries, NDK r26 can build successfully.

There is no libgcc in NDK r26 (nor any recent NDK, going back to like r23? it's been quite a while), so something else is happening here.

**Comment by 486946** [comment]
> > `-nodefaultlibs`
> 
> That's what this does. You've excluded the C++ stdlib, which provides the definition for `new`. Older versions of Clang had a bug where `-lstdc++` was passed to the linker even when it should not have been. Why are you passing that flag?
> 
> > When add libgcc.a in linked libraries, NDK r26 can build successfully.
> 
> There is no libgcc in NDK r26 (nor any recent NDK, going back to like r23? it's been quite a while), so something else is happening here.

Changes to Android 8.1：
Remove libstdc++ so from the LL-NDK library. Use libc++.so. Some versions of standalone toolchains can add -lstDC ++ to the default linker tag. To deactivate the default Settings, add -nodefaultlibs-lc-lm-ldl to LDFLAGS.

**Comment by DanAlbert** [comment]
If you're reporting an LL-NDK bug you're in the wrong place. The NDK and LL-NDK are unrelated (trust me, _everyone_ hates the name). If you're trying to report a LL-NDK issue you should go through your TAM.
