### ISSUE TITLE
[BUG] Unable to Handle Exceptions Properly

### ISSUE THREAD

**Issue by lingsixuan** [android/ndk#1997]
### Description

I am using CLion to develop an Android ELF executable, compiling the code with the toolchain provided by NDK. When throwing an exception in a C++ function, if there is an object located in the stack before the point where the exception is thrown, and this object has a destructor, the exception triggers a segmentation fault during the execution of stack unwinding, leading to a program crash.

## Test Code :

~~~ C++
class Test {
public:
    ~Test() {
        std::cout << "delete" << std::endl;
    }
};

void text() {
    Test t;
    throw std::runtime_error("");
}

int main(){
    try{
        text();
    }catch (const std::runtime_error & e){
        std::cout << "catch" << std::endl;
    }
}
~~~
Run the following command to compile and run:
~~~ bash
${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ file_name.cpp -o file_name
adb push file_name /data/local/tmp
adb shell chmod +x /data/local/tmp/file_name
adb shell /data/local/tmp/file_name
~~~
The result is the following output
> delete
> Segmentation fault

I observed that the expected exception handling did not occur, and the code crashed after invoking the destructor of the Test class. After consulting relevant resources, it seems that this is due to an error in stack unwinding when throwing an exception. However, I have not found a viable solution

### Affected versions

r26

### Host OS

Linux

### Host OS version

Arch Linux 

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

21

### Device API level

33

**Comment by DanAlbert** [comment]
Your instructions are incomplete, so it's possible that whatever you did different in the gaps I had to guess at is the source of the problem, but this worked fine for me. I had to add the missing `#include <stdio>` and `#include <exception>`, and I needed to add the flag `-static-libstdc++` (or to also push libc++_shared.so and us `LD_LIBRARY_PATH`, both worked). The only other deviation from your instructions was the device version. I don't have an API 33 device on hand right now, so I tested 32. I can try to check 34 later today when I figure out where that phone went, but you should recheck your instructions.

> CMake

Is your snippet wrong, or is this field wrong?

**Comment by lingsixuan** [comment]
Thank you. The issue was caused by my omission of the -static-libstdc++ linker option. After adding it, I observed that the exception handling is working correctly. I apologize for wasting your time.
