### ISSUE TITLE
[BUG] With Buildozer for Python/Kivy project for Android NDK 26b

### ISSUE THREAD

**Issue by RadoslawGlebicki** [android/ndk#1998]
### Description

command:
buildozer android debug

```
error:

/vmDisk/forBuildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/jni/SDL2_ttf/external/harfbuzz/src/hb-ft.cc:759:73: error: cast from 'void ()(FT_Face)' (aka 'void ()(FT_FaceRec_ )') to 'FT_Generic_Finalizer' (aka 'void ()(void )') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
if (unlikely (!ft_face->generic.data || ft_face->generic.finalizer != (FT_Generic_Finalizer) hb_ft_face_finalize))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/vmDisk/forBuildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/jni/SDL2_ttf/external/harfbuzz/src/hb.hh:263:25: note: expanded from macro 'unlikely'
#define unlikely(expr) (expr)
^~~~
/vmDisk/forBuildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/jni/SDL2_ttf/external/harfbuzz/src/hb-ft.cc:765:34: error: cast from 'void ()(FT_Face)' (aka 'void ()(FT_FaceRec_ )') to 'FT_Generic_Finalizer' (aka 'void ()(void )') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
ft_face->generic.finalizer = (FT_Generic_Finalizer) hb_ft_face_finalize;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/vmDisk/forBuildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/jni/SDL2_ttf/external/harfbuzz/src/hb-ft.cc:1035:32: error: cast from 'void ()(FT_Face)' (aka 'void ()(FT_FaceRec_ )') to 'FT_Generic_Finalizer' (aka 'void ()(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
ft_face->generic.finalizer = (FT_Generic_Finalizer) _release_blob;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
make: *** [/vmDisk/.buildozer/android/platform/android-ndk-r26b/build/core/build-binary.mk:415: /vmDisk/forBuildozer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2/obj/local/armeabi-v7a/objs-debug/harfbuzz/src/hb-ft.o] Error 1

```

### Affected versions

r26

### Host OS

Linux

### Host OS version

Fedora 39

### Affected ABIs

armeabi-v7a

### Build system

ndk-build

### minSdkVersion

21

### Device API level

31

**Comment by RadoslawGlebicki** [comment]
Sorry if is something not ok but maybe this is BUG.

**Comment by DanAlbert** [comment]
I don't understand what you think the bug is. There's a compiler warning. Do you think it's wrong?

**Comment by appujee** [comment]
It is a bug in the user's source code.  Look at https://stackoverflow.com/questions/59041367/silence-wcast-function-type-on-a-function-structure for some guidance on how to fix it.

Alternatively, which is not a good idea IMO, you can silence the warning by adding `-Wno-cast-function-type-strict` flag to the build rule.

**Comment by DanAlbert** [comment]
@RadoslawGlebicki, I'm assuming you read the warning, but thinks it's incorrect? Otherwise I'm not sure what bug you're trying to report here.

**Comment by RadoslawGlebicki** [comment]
Quote:
"Sorry if is something not ok but maybe this is BUG."
As you see there is 'MAYBE this is bug' and of course my mistake there is yes 'warning' But wait no: 'error' and even 3 errors. 
But problem solved. I go back to NDK 25b and packets was doubled:
rpm and pip so I removed those rpms and now I can compile my project.

Thanks for help. ;-D

**Comment by DanAlbert** [comment]
The warnings are errors because you're compiling with `-Werror`.
