### ISSUE TITLE
Simpleperf: Only one FEAT_FILE2 feature section can be read from the file

### ISSUE THREAD

**Issue by mstange** [android/ndk#2002]
### Description

I am very confused by the code in `RecordFileWriter::WriteFileFeatures` and `RecordFileReader::LoadBuildIdAndFileFeatures`.

[`RecordFileWriter::WriteFileFeatures`](https://cs.android.com/android/platform/superproject/+/main:system/extras/simpleperf/record_file_writer.cpp;l=331;drc=06ed3efac24ba19a837b6a4110f15b7c78ab42d0) writes one file2 section for every DSO. So it might be writing more than one section, right? But after writing each of them, it updates the section offset + size of the `FEAT_FILE2` feature to point to the last-written section. Doesn't this mean that only the last-written section can be found?

[`RecordFileReader::LoadBuildIdAndFileFeatures`](https://cs.android.com/android/platform/superproject/+/main:system/extras/simpleperf/record_file_reader.cpp;l=738;drc=6601cb4ec033b0ed03de8b9f55cffbc9619c50d3) appears to try to read multiple file feature sections. But the offset + size for each section is obtained from `feature_section_descriptors_.find(FEAT_FILE2)->second`, which will return the same values every time.

Is this working as intended? @yabinc
Given a perf.data file from Simpleperf, is there a way to obtain the used symbols for more than one DSO?

### Affected versions

Canary

### Host OS

Mac

### Host OS version

macOS 14.1

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

-

**Comment by yabinc** [comment]
Yes, it works as intended. You can use `simpleperf dump` to dump a perf.data, and check symbols from multiple dsos in FEAT_FILE2 section.

**Comment by mstange** [comment]
Oh indeed, it does work! The code is just a bit confusing - it looks as if it's trying to write multiple different feature sections, but instead it's all concatenated into one single big feature section.

> But after writing each of them, it updates the section offset + size of the `FEAT_FILE2` feature to point to the last-written section.

No, it only updates the size. `RecordFileWriter::WriteFeatureBegin` leaves the offset untouched if the feature already exists in `RecordFileWriter::features_`.
`RecordFileWriter::WriteFeatureEnd` updates the size.

So really, I was confused by the repeated calls to `WriteFeatureBegin` and `WriteFeatureEnd`. It would be clearer if there was only one call to each of them total, rather than one call per DSO. Repeated calls to `WriteFeatureBegin` are no-ops, and repeated calls to `WriteFeatureEnd` overwrite the previous call's effects.

> [`RecordFileReader::LoadBuildIdAndFileFeatures`](https://cs.android.com/android/platform/superproject/+/main:system/extras/simpleperf/record_file_reader.cpp;l=738;drc=6601cb4ec033b0ed03de8b9f55cffbc9619c50d3) appears to try to read multiple file feature sections. But the offset + size for each section is obtained from `feature_section_descriptors_.find(FEAT_FILE2)->second`, which will return the same values every time.

That's correct, but the `read_pos` will be the relative offset to the start of the section, and when `RecordFileReader::ReadFileFeature` returns, only the data for one DSO has been read, so `read_pos` will now point partway into the section, to the beginning of the data for the next DSO. So `read_pos` is different for each call to `RecordFileReader::ReadFileFeature`. Only once the data for all DSOs has been read will `read_pos` be equal to `desc.size`.

Again, what's confusing here is that there are multiple calls to `RecordFileReader::ReadFileFeature`, even though all calls are reading bytes from the same feature section. And the feature section descriptor is obtained repeatedly on each call even though it's always the same.
