### ISSUE TITLE
AES support (arm/arm64 vaeseq_u8)

### ISSUE THREAD

**Issue by mgood7123** [android/ndk#2003]
### Description

in regards to compiling `lzma2301` for android, which uses AES on `x86/x86_64` and `arm/arm64`, how can i determine if support for the `vaeseq_u8` intrinsic is actually present on my device

as on armv7 i am not sure if such is supported

on armv8 crypto is apparently `optional` so there is no gaurentee that it will or will not be available for all android armv8 devices

for x86 and x86_64 i think AES is mandatory or very strongly supported ?

for arm64 i get

```
implicit declaration of function 'vaeseq_u8' is invalid in C99 [-Wimplicit-function-declaration]
```

```c
#elif defined(MY_CPU_ARM_OR_ARM64) && defined(MY_CPU_LE)

  #if defined(__clang__)
    #if (__clang_major__ >= 8) // fix that check
      #define USE_HW_AES
    #endif
  #elif defined(__GNUC__)
    #if (__GNUC__ >= 6) // fix that check
      #define USE_HW_AES
    #endif
  #elif defined(_MSC_VER)
    #if _MSC_VER >= 1910
      #define USE_HW_AES
    #endif
  #endif

#ifdef USE_HW_AES

// #pragma message("=== AES HW === ")

#if defined(__clang__) || defined(__GNUC__)
  #ifdef MY_CPU_ARM64
    #define ATTRIB_AES __attribute__((__target__("+crypto")))
  #else
    #define ATTRIB_AES __attribute__((__target__("fpu=crypto-neon-fp-armv8")))
  #endif
#else
  // _MSC_VER
  // for arm32
  #define _ARM_USE_NEW_NEON_INTRINSICS
#endif

#ifndef ATTRIB_AES
  #define ATTRIB_AES
#endif

#if defined(_MSC_VER) && defined(MY_CPU_ARM64)
#include <arm64_neon.h>
#else
#include <arm_neon.h>
#endif

typedef uint8x16_t v128;

#define AES_FUNC_START(name) \
    void Z7_FASTCALL name(UInt32 *ivAes, Byte *data8, size_t numBlocks)
    // void Z7_FASTCALL name(v128 *p, v128 *data, size_t numBlocks)

#define AES_FUNC_START2(name) \
AES_FUNC_START (name); \
ATTRIB_AES \
AES_FUNC_START (name)

#define MM_OP(op, dest, src)  dest = op(dest, src);
#define MM_OP_m(op, src)      MM_OP(op, m, src)
#define MM_OP1_m(op)          m = op(m);

#define MM_XOR( dest, src)    MM_OP(veorq_u8, dest, src)
#define MM_XOR_m( src)        MM_XOR(m, src)

#define AES_E_m(k)     MM_OP_m (vaeseq_u8, k)
#define AES_E_MC_m(k)  AES_E_m (k)  MM_OP1_m(vaesmcq_u8)
```

**Comment by enh-google** [comment]
yeah, i've struggled to even explain the problem to the maintainer --- https://sourceforge.net/p/sevenzip/bugs/2383/

i don't think they think armv7 is a real thing.

**Comment by DanAlbert** [comment]
Closing as it sounds like this is a 7-zip bug, not an NDK bug. If I've misunderstood, just lmk and we can reopen.

**Comment by mgood7123** [comment]
this would apply to other projects using AES encryption (not just 7-zip)

**Comment by mgood7123** [comment]
(my current workaround is to disable such AES/SHA256 code from compiling when targeting `__ANDROID__`)

**Comment by DanAlbert** [comment]
> this would apply to other projects using AES encryption (not just 7-zip)

But in each case it's the projects that are wrong, right? The problem here is that projects are assuming availability of optional hardware features?

**Comment by enh-google** [comment]
> tho this then introduces a situation where x86 based android devices support AES encryption and arm based android devices do not support AES encryption

no, because Android's x86-64 ABI _also_ doesn't include AES. (but again, you may happen to be running on a device that does, given that your x86-64 "device" is likely a modern laptop!) but if your code _assumes_ x86-64 AES, it's still strictly wrong.

look at zlib for an example of how to do this kind of thing correctly.

**Comment by pirama-arumuga-nainar** [comment]
>     #define ATTRIB_AES __attribute__((__target__("+crypto")))

This indicates that the code is _trying_ to do the right thing.  This attribute should build functions with aes support even if the source file isn't: https://godbolt.org/z/Ts934oox5.  Can you check if the attribute is set at the relevant functions (or share a repro)?

> how can i determine if support for the vaeseq_u8 intrinsic is actually present on my device

The library would also need to do runtime detection using a cpu-features library (or use ifuncs) to check if crypto is available on the device.

**Comment by enh-google** [comment]
> This indicates that the code is trying to do the right thing

well, for _armv8_ --- my point was that it's broken for armv7: https://sourceforge.net/p/sevenzip/bugs/2383/

**Comment by pirama-arumuga-nainar** [comment]
> well, for _armv8_ --- my point was that it's broken for armv7: https://sourceforge.net/p/sevenzip/bugs/2383/

Aah, yea, that's correct.  @mgood7123 if you're already modifying the library code, use enh's suggested fix - to move the aes functions to a separate file and build them for armv8.

**Comment by mgood7123** [comment]
so to be clear

on "desktop" x86 devices, AES support is (probably?) high

on "android" x86/arm devices, AES support is low (optional but probably only rarely actually supported in the cpu itself, eg one x86 device may have AES support while another x86 device lacks AES support)

would this be right?

**Comment by enh-google** [comment]
> on "android" x86/arm devices, AES support is low (optional but probably only rarely actually supported in the cpu itself, eg one x86 device may have AES support while another x86 device lacks AES support)

i don't think "high" or "low" are really the point --- the point is that it's not _guaranteed_ so you need to check at runtime (with `if ((getauxval(AT_HWCAP) & HWCAP_AES) != 0)` for arm64, say), and then _either_ call the routine that uses the instruction or a routine that doesn't.

lzma _tries_ to do this but (as explained in https://sourceforge.net/p/sevenzip/bugs/2383/) they got it wrong, or at least "don't believe that armv7 still exists".
