### ISSUE TITLE
[BUG] With Compose AndroidView on API 29, ANativeWindow_fromSurface with SurfaceView without an additional ViewGroup makes AndroidViewsHandle go black

### ISSUE THREAD

**Issue by paxbun** [android/ndk#2015]
### Description

Tested with Compose 1.5.0, 1.6.2, and 1.6.5.

I'm making a Compose app that needs some rendering logic using NDK. I embedded a SurfaceView into a Compose hierarchy like the following:

```kotlin
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      MaterialTheme {
        var showContent by remember { mutableStateOf(false) }
        Column {
          Button(onClick = { showContent = !showContent }) { Text("Click me!") }
          AnimatedVisibility(showContent) { MyView(Modifier.fillMaxHeight()) }
        }
      }
    }
  }
}

@Composable
fun MyView(modifier: Modifier) {
  AndroidView(
    factory = {
      SurfaceView(it).apply {
        holder.addCallback(object : SurfaceHolder.Callback {
          private var nativeWindow: Long = 0
          override fun surfaceCreated(holder: SurfaceHolder) {
            nativeWindow = MyLibrary.surfaceAsNativeWindow(holder.surface)
          }
          // others omitted for brevity, does nothing in their body
        })
      }
    },
    modifier = modifier,
  )
}

private object MyLibrary {
  init {
    System.loadLibrary("my-library")
  }
  @JvmStatic
  external fun surfaceAsNativeWindow(surface: Surface): Long
}
```

where MyLibrary.surfaceAsNativeWindow is just a wrapper of ANativeWindow_fromSurface.

```cpp
#include <jni.h>
#include <android/native_window_jni.h>

extern "C" JNIEXPORT jlong JNICALL
Java_my_package_MyLibrary_surfaceAsNativeWindow(
  JNIEnv* env,
  jclass clazz,
  jobject surface  
) {
  return reinterpret_cast<jlong>(ANativeWindow_fromSurface(env, surface));
}
```

On an API 34 VM, the black background is rendered below the button as expected:

![image](https://github.com/android/ndk/assets/17005454/4db0d6a8-fb99-40c2-b20d-f95e37628b74)

but on an API 29 VM, the black background covers the button when clicked, but it can still be clicked so I can turn on and off the SurfaceView.

<img width="360" alt="image" src="https://github.com/android/ndk/assets/17005454/eb493393-cda8-44f5-b91c-abb69b877336">

I don't know the internal details of Compose, but it seems that `@Composable fun AndroidView()` inserts a ViewGroup called AndroidViewsHandle, and the issue is that AndroidViewsHandle went black.

<img width="1205" alt="image" src="https://github.com/android/ndk/assets/17005454/f3fbd838-f965-48ac-a189-8de849d49141">

I'm sure it is not an issue with my rendering pipeline because the above result does not run the loop, and when I run the loop, the result is as expected, except for the black rectangle covering the other part. The result is from my app, whose NDK part is written in Rust.

![image](https://github.com/android/ndk/assets/17005454/8b27edd7-4ee4-48b4-9ec7-4d54b6075daa)

Still, the button hidden by the black rectangle is clickable.

This issue also does not occur when I do the same with XML, even on API 29.

![image](https://github.com/android/ndk/assets/17005454/8b073296-e5fc-463d-9900-f6b75150ad0a)
![image](https://github.com/android/ndk/assets/17005454/4fbd9562-7442-40ed-807b-4f392dcb5a17)

This also should not be the problem of layoutParams -- setting layoutParams to `ViewGroup.LayoutParams(100, 100)` makes the following result.

<img width="307" alt="image" src="https://github.com/android/ndk/assets/17005454/c2e1fe3a-9046-475a-b04e-b4fd70281ce1">

Since this is due to AndroidViewsHandle being black, returning LinearLayout in AndroidView's factory and adding the SurfaceView to LinearLayout also works well.

<img width="312" alt="image" src="https://github.com/android/ndk/assets/17005454/f4a9f8d4-303d-4156-9b68-7a2a34dcdfe5">

```kotlin
AndroidView(
  factory = {
    LinearLayout(it).apply {
      addView(SurfaceView(it).apply {
        holder.addCallback(/* same as above */)
      })
    }
  },
  modifier = modifier,
)
```

It may be a problem of Compose, but I left these for those who want to use graphics API in their Compose app.

### Affected versions

r26

### Host OS

Mac

### Host OS version

macOS 14.4.1

### Affected ABIs

arm64-v8a

### Build system

CMake

### Other build system

Rust Cargo

### minSdkVersion

29

### Device API level

29

**Comment by DanAlbert** [comment]
I'm confused. What's the NDK bug you're trying to report?

**Comment by paxbun** [comment]
@DanAlbert ANativeWindow_fromSurface makes the ViewGroup (or AndroidViewsHandle) containing the SurfaceView black, not the SurfaceView itself, not on the latest Android, but on API 29. I actually couldn't find whether this is the issue of the Android framework or the issue of NDK, but since this does not happen on the latest Android, I decided to report it here. This just happens after the invocation of ANativeWindow_fromSurface; would it be not related to NDK? Sorry for making you confused...

**Comment by DanAlbert** [comment]
The NDK is essentially just an LLVM distribution (okay, and some build system stuff). We ship the headers and library stubs for the OS APIs, but that all comes from the OS; the NDK is just the box it ships in. Anything related to API behavior is an OS thing, not an NDK thing.

What fix are you looking for here? Do you want future versions of the OS to behave like 29? If so, file a framework bug. If you want androidx to paper over things and pretend each OS behaves identically, file an androidx bug.
