### ISSUE TITLE
[Feature request] consider to provide libc.a for each API level

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#2017]
### Description

**step1. create a simple C source file test.c**

```C
char lockf();

int main(int agc, char* agv[]) {
    lockf();
    return 0;
}
```

**step2. compile it**

```bash
/home/leleliu008/.ndk-pkg/uppm/installed/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-17 --target=aarch64-none-linux-android21 --sysroot=/home/leleliu008/.ndk-pkg/uppm/installed/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot -c test.c
```

**step3. create a fully statically linked executable**

```bash
/home/leleliu008/.ndk-pkg/uppm/installed/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-17 --target=aarch64-none-linux-android21 --sysroot=/home/leleliu008/.ndk-pkg/uppm/installed/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot -static test.o
```

It didn't report me `undefined symbol lockf`, if I remove the `-static` flag it will report me.

`lockf` function was introduced in Android-24. It is not supposed to exist in Android-21.

```c
int lockf(int __fd, int __cmd, off_t __length) __RENAME_IF_FILE_OFFSET64(lockf64) __INTRODUCED_IN(24);
```

This behaver breaks the cmake https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html moudle.

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu23.10

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

21

**Comment by leleliu008** [comment]
I find `libc.a` locations are following , they are the latest version of libc?

```
sysroot/usr/lib/x86_64-linux-android/libc.a
sysroot/usr/lib/i686-linux-android/libc.a
sysroot/usr/lib/aarch64-linux-android/libc.a
sysroot/usr/lib/arm-linux-androideabi/libc.a
sysroot/usr/lib/riscv64-linux-android/libc.a
```

This behaver breaks the cmake https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html moudle.

It seems that the only way to fix this  is to ask for cmake to remove `-static` and `--static` arguments when do CheckFunctionExists .

**Comment by leleliu008** [comment]
many cmake project create shared libraries, static libraries, dynamically linked executables or  fully statically linked executables at the same time, In this case, `CheckFunctionExists`'s result is not correct for shared libraries and dynamically linked executables if I pass `-static`  to clang.

**Comment by leleliu008** [comment]
https://github.com/android/ndk/issues/1600

**Comment by leleliu008** [comment]
why NDK only provides the latest version of libc.a? to reduce the size?

**Comment by leleliu008** [comment]
this behaver force me to split a big project (including shared libraries, static libraries, dynamically linked executables or fully statically linked executables) into some small packages, and each package is either a library package or an executable package.

**Comment by DanAlbert** [comment]
> why NDK only provides the latest version of libc.a? to reduce the size?

Because there's no reason to do otherwise. There's no value in using an old libc.a.

> This behaver breaks the cmake https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html moudle.

You have to test the same configuration that you ship. If you're building multiple configurations, you need multiple tests.
