### ISSUE TITLE
[BUG] using thread_local in x64 Android 12L/13 desktop simulator for release build generates invalid init function for thread_local variable that leads to SIGSEGV

### ISSUE THREAD

**Issue by StoyanovVlad** [android/ndk#2018]
### Description

<img width="903" alt="Screenshot 2024-04-23 at 02 25 28" src="https://github.com/android/ndk/assets/10288328/bd66d071-a6a2-4391-9e1f-e914f7ef8f51">
<img width="1073" alt="Screenshot 2024-04-23 at 02 29 52" src="https://github.com/android/ndk/assets/10288328/76a3d783-97c2-4e78-84ef-dc673d3b4141">
<img width="850" alt="Screenshot 2024-04-23 at 02 21 13" src="https://github.com/android/ndk/assets/10288328/277f0590-b8df-4a5a-86d9-be2a88fa5fbc">
<img width="781" alt="Screenshot 2024-04-23 at 15 34 26" src="https://github.com/android/ndk/assets/10288328/4f56c7ac-6cd6-45fe-af68-d89e4be71214">
<img width="730" alt="Screenshot 2024-04-23 at 15 34 49" src="https://github.com/android/ndk/assets/10288328/0fae25d5-681b-4e65-aff3-8b85ab5ba1e8">
<img width="1890" alt="Screenshot 2024-04-23 at 15 40 03" src="https://github.com/android/ndk/assets/10288328/4aae2672-99d6-4f1d-b634-9626966b13b4">

### Affected versions

r26, r27

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

x86_64

### Build system

ndk-build

### minSdkVersion

Android 12L (Android SDK Platform 32)

**Comment by DanAlbert** [comment]
We can't help without a repro case. Upload one (not photos, I'm not reconstructing your source code from photos, and in any case those photos are insufficient, see the bug template for an example of what we need) and we can reopen, but there's nothing we can do with the information given.
