### ISSUE TITLE
[DOC] cherry-pick changelog update to r27

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#2025]
### URL

N/A

### Problem

Reminder to myself to cherry-pick https://r.android.com/3106738 to r27 before the final release.

**Comment by vvb2060** [comment]
> Android V will allow OEMs to ship arm64-v8a and x86_64 devices with 16KiB page sizes. 

Why include x86_64 devices? 16kB pages are only supported on arm64 targets with 16kB kernels. I know there is also an option to simulate 16KB userspace on x86_64 for Cuttlefish, but it is not possible to ship by OEM.

**Comment by DanAlbert** [comment]
I think you're on the wrong bug :) This isn't about 16k.

**Comment by DanAlbert** [comment]
And another, so I don't forget: https://r.android.com/3114619
