### ISSUE TITLE
[BUG] ndk 27's `lib.a` does not support 16k page size

### ISSUE THREAD

**Issue by yujincheng08** [android/ndk#2026]
### Description

Crash with `WriteProtected mprotect 1 failed: Invalid argument`. (same as prebuilt lldb-server)

For AOSP it has been fixed: https://android-review.googlesource.com/c/platform/bionic/+/2713655

But `libc.a` in ndk does not contain this fix. Need prebuilt update?

28.0.11913967 works FYI.

### Affected versions

r27

### Host OS

Mac

### Host OS version

MacOS 14.5

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

26

**Comment by DanAlbert** [comment]
Already fixed. This is why RC 1 got delayed multiple weeks.
