### ISSUE TITLE
[BUG] `std::isblank( charT c, const locale& loc)` is missing from `<locale>`

### ISSUE THREAD

**Issue by CraigHutchinson** [android/ndk#2028]
### Description

C++11 function `std::isblank(c, locale)` is missing as per https://en.cppreference.com/w/cpp/locale/isblank 

I checked the `<locale>` header ans see `r27` still doens't define it:
![image](https://github.com/android/ndk/assets/54269136/571ee1be-d04f-4851-ae0b-fd24bbf276fb)

### Affected versions

r27

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

21

**Comment by appujee** [comment]
isblank was implemented quite late in libc++. Around April last year: https://reviews.llvm.org/D147850

**Comment by pirama-arumuga-nainar** [comment]
> isblank was implemented quite late in libc++. Around April last year: https://reviews.llvm.org/D147850

https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r522817/include/c++/v1/__locale#733 - the above change _is_ included in r27.  @CraigHutchinson  Can you post a repro on what's failing?

**Comment by DanAlbert** [comment]
Closing for lack of feedback. We can't help without a repro case.

**Comment by CraigHutchinson** [comment]
Hi, sorry I missed the message. 

Tlinked `isblank` is the ctype facet. You should note that `isblank` isn't in the `locale` interface which is really odd oversight: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r522817/include/c++/v1/locale

**Comment by CraigHutchinson** [comment]
Also, great comment on the linked LLVM ticket which was my sentiment when finding this but looks liek its resolved/to-be-solved etc


> Crazy that nobody complained about this in the past 10 years. LGTM.
