### ISSUE TITLE
[DOC] Clarification on 16k page size support for x86_64 devices

### ISSUE THREAD

**Issue by vvb2060** [android/ndk#2033]
### URL

https://github.com/android/ndk/wiki/Changelog-r27

### Problem

> Android V will allow OEMs to ship arm64-v8a and x86_64 devices with 16KiB page sizes. 

https://github.com/android/ndk/wiki/Changelog-r27

> 16kB pages are only supported on arm64 targets with 16kB kernels. However, there is also an option to simulate 16KB userspace on x86_64 for Cuttlefish.

https://source.android.com/docs/core/architecture/16kb-page-size/16kb

> Note: If you're planning to emulate a supported Google Pixel device, you will only need the ARM 64 v8a System Image.

https://developer.android.com/guide/practices/page-sizes#16kb-emulator

Need clarification if the 16k x86_64 device is only for developer test app without Apple M2, or can OEMs ship 16k x86_64 devices?

**Comment by DanAlbert** [comment]
@smoreland

**Comment by DanAlbert** [comment]
@smore-lore

**Comment by smore-lore** [comment]
x86_64 16 KB support is for testing only.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/3146659 fixes the changelog.
