### ISSUE TITLE
[Bug]: clang compile with -D_FORTIFY_SOURCE=2 -Dstatic= cause undefined symbol: snprintf

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#2043]
### Description

**step1:** ceate a simple C source file:

```c
#include <stdio.h>

int main() {
    char buf[5];
    snprintf(buf, 5, "%s\n", "ab");
    return 0;
}
```

**step2:** compile with `-D_FORTIFY_SOURCE=2 -Dstatic=`:

```bash
aarch64-linux-android21-clang -D_FORTIFY_SOURCE=2 -Dstatic= test.c
```

report errors:

```
ld.lld: error: undefined symbol: snprintf(char*, unsigned long pass_object_size1, char const*, ...)
>>> referenced by test.c
>>>               /var/folders/c8/cst2t7tn3rsbk47q2zd247800000gp/T/test-308a87.o:(test)
>>> did you mean: extern "C" snprintf
>>> defined in: /Users/fpliu/Downloads/android-ndk-r27-beta2/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/libc.so

ld.lld: error: undefined symbol: main
>>> referenced by crtbegin.c
>>>               /Users/fpliu/Downloads/android-ndk-r27-beta2/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/crtbegin_dynamic.o:(_start_main)
>>> referenced by crtbegin.c
>>>               /Users/fpliu/Downloads/android-ndk-r27-beta2/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/crtbegin_dynamic.o:(_start_main)
```

I test my host machine clang and gcc, all successfully compiled.

### Affected versions

r26, r27

### Host OS

Linux, Mac

### Host OS version

Ubuntu24.04

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by leleliu008** [comment]
This is not a good example. 

I got `000000000000003c U _ZL8snprintfPcU17pass_object_size1mPKcz` when build a third-party project, which case linker report following:

```
ld: error: undefined symbol: snprintf(char*, unsigned long pass_object_size1, char const*, ...)
>>> referenced by packcc.c:836 (/home/runner/work/pegof/pegof/packcc/src/packcc.c:836)
>>>               CMakeFiles/pegof.dir/src/packcc_wrapper.c.o:(escape_character)
>>> referenced by packcc.c:838 (/home/runner/work/pegof/pegof/packcc/src/packcc.c:838)
>>>               CMakeFiles/pegof.dir/src/packcc_wrapper.c.o:(escape_character)
>>> did you mean: extern "C" snprintf
>>> defined in: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/33/libc.so
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm closing this, I will ropen this when find a good example.

**Comment by leleliu008** [comment]
background is a want to use a third-party project, it has some static functions, I want to use these static functions in my project. The simpest way is pass `-Dstatic=` to compiler, this works indeed for GCC and Clang oh my host machine, but NDK's clang do not work.

**Comment by enh-google** [comment]
`-Dstatic=` will break the `__BIONIC_FORTIFY_VARIADIC` macro used in the implementation of `_FORTIFY_SOURCE`.

you don't say what your host it, but macOS doesn't have fortification of snprintf() so i assume it's not that. interestingly though, glibc uses `extern inline __attribute__((__always_inline__))` even for clang, though our macro has this comment before it:
```
/*
 * Because clang-FORTIFY uses overloads, we can't mark functions as `extern inline` without making
 * them available externally. FORTIFY'ed functions try to be as close to possible as 'invisible';
 * having stack protectors detracts from that (b/182948263).
 */
#  define __BIONIC_FORTIFY_INLINE static __inline __attribute__((__no_stack_protector__)) \
      __always_inline __VERSIONER_FORTIFY_INLINE
```
@gburgessiv did you do the glibc clang fortify sufficiently differently that this concern isn't relevant there?

**Comment by DanAlbert** [comment]
Making any codebase tolerant of removing keywords from the language sounds impractical to maintain. It's up to @enh-google if he wants to try to deal with this as a one-off since he's the one that'd have to live with it, but I suspect this isn't worth the cost of having to write everything in a dialect of C without that keyword.

**Comment by gburgessiv** [comment]
+1 to DanAlbert's note. `-Dstatic=` seems like it'd be pretty fragile. The less-fragile solution I'd recommend is seeing if the 3p code maintainers would be amenable to surfacing this functionality. If not, you also have the alternative of maintaining a patch that removes the `static`s you care about`.

> @gburgessiv did you do the glibc clang fortify sufficiently differently that this concern isn't relevant there?

Clang used to entirely ignore the majority of glibc's FORTIFY impl. It'd parse the functions, but never actually emit them to LLVM IR. AIUI there've been efforts upstream to make Clang more tolerant of glibc's FORTIFY impl, so `extern inline` may work now.

Can't hurt to try if you'd like to maintain this, though if we want `static` without spelling it `static`, looks like `__attribute__((internal_linkage))` DTRT: https://godbolt.org/z/xsEzKMYzv

**Comment by leleliu008** [comment]
@enh-google 

> you don't say what your host it

my host is `Ubuntu-24.04` `gcc` and `clang` installed via `sudo apt install -y gcc clang lld`

**Comment by leleliu008** [comment]
@enh-google @DanAlbert @gburgessiv I got it. Please feel free to close this.

**Comment by enh-google** [comment]
> Clang used to entirely ignore the majority of glibc's FORTIFY impl. It'd parse the functions, but never actually emit them to LLVM IR. AIUI there've been efforts upstream to make Clang more tolerant of glibc's FORTIFY impl, so extern inline may work now.

ah, because there are references to clang in glibc's fortify, i just _assumed_ that it worked ... your explanation makes more sense :-)
