### ISSUE TITLE
[BUG] android-ndk-r26c use -pg ld.lld: error: undefined symbol: _mcount

### ISSUE THREAD

**Issue by mckaylinux** [android/ndk#2044]
### Description

Hi All,

I want to use the -pg option in LLVM for performance profiling, but I'm encountering an error during linking that indicates _mcount is undefined. Can anyone help me out? Thank you.

android-ndk-r26c-linux/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang -pg simd.c -o simdpg

ld.lld: error: undefined symbol: _mcount

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu20.04

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

android-ndk-r26c

**Comment by DanAlbert** [comment]
That symbol doesn't seem to come from bionic, so I'm guessing it's a compiler-rt thing?

**Comment by enh-google** [comment]
i'd ask @pirama-arumuga-nainar --- i don't know whether it's compiler-rt exactly, or there's an extra library you need for profiling? the latter rings a bell...

**Comment by DanAlbert** [comment]
There is (and it's part of the collection of libraries collectively called compiler-rt, I think), but Clang should be linking it automatically as long as those flags are correct.

**Comment by DanAlbert** [comment]
Oh, they might not be? https://github.com/DanAlbert/ndk-samples/blob/9cc55c332cfd9db9f8aaf9c7f0e042ada5b5d46f/pgo/app/src/main/cpp/CMakeLists.txt (sorry, I'd forgotten that I had to revert that sample and haven't put it back yet)

**Comment by mckaylinux** [comment]
@DanAlbert , Does that mean I need to use -fprofile-generate for profile data?

**Comment by DanAlbert** [comment]
That's how I was able to do it successfully. I don't know if that's the _only_ way to do it, but the flags you used in the OP aren't familiar to me (they could be an alias for all I know).

**Comment by pirama-arumuga-nainar** [comment]
Yes, please use the clang-based technicues, which are supported. 
 https://clang.llvm.org/docs/SourceBasedCodeCoverage.html has instructions to use clang source-based coverage - which also doubles up as the profiling method (unlike `gcov` vs `gprof`).  For Android specifically, there was an example in NDK samples which @DanAlbert is planning to resurrect (https://github.com/android/ndk-samples/pull/956, https://github.com/android/ndk-samples/issues/1070).

Alternatively, if you are looking for flame graphs and such to debug performance issues, use [simpleperf](https://developer.android.com/ndk/guides/simpleperf).

(`_mcount` is [provided](https://codebrowser.dev/glibc/glibc/sysdeps/x86_64/_mcount.S.html) by glibc.  compiler-rt does not provide alternate implementations for non-glibc environments.)
