### ISSUE TITLE
[BUG] sysroot wrongly includes tflite_support_libz.a?

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#2053]
### Description

```bash
$ find ../out/android-ndk-r28-canary/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -name "tflite_support_libz.a"
../out/android-ndk-r28-canary/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/aarch64-linux-android/tflite_support_libz.a
../out/android-ndk-r28-canary/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/arm-linux-androideabi/tflite_support_libz.a
../out/android-ndk-r28-canary/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android/tflite_support_libz.a
../out/android-ndk-r28-canary/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/i686-linux-android/tflite_support_libz.a
../out/android-ndk-r28-canary/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/riscv64-linux-android/tflite_support_libz.a
```

That's not supposed to be there. Looking at the `Android.bp` and the soong code that backs it, I can't explain why it is. It showed up some time in r27. They take up about 2MB altogether, which isn't a lot, but is pointless.

### Affected versions

r27, Canary

### Host OS

Linux, Mac, Windows

### Host OS version

any

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### Other build system

n/a

### minSdkVersion

all

**Comment by enh-google** [comment]
presumably a regex/glob somewhere that's missing a `/`? (since libz_static.a didn't end up here, despite looking very similar from soong's perspective, modulo the name...)

**Comment by DanAlbert** [comment]
There's no globbing involved though. It's controlled by the `static_ndk_lib` property, which is set in so few places that it's easy to audit all of them as leaf-nodes which shouldn't be affecting this: https://cs.android.com/search?q=static_ndk_lib&sq=&ss=android%2Fplatform%2Fsuperproject%2Fmain

Within soong there aren't all that many ways for things to end up here: https://cs.android.com/android/platform/superproject/main/+/main:build/soong/cc/ndk_sysroot.go;l=157-195?q=ndkSysrootPath&ss=android%2Fplatform%2Fsuperproject%2Fmain. Those all look correct, and `tflite_support_libz` doesn't appear to meet any of those criteria...

**Comment by DanAlbert** [comment]
I've got no idea what caused it, but it's gone now. Actually was already gone at the time I filed this, but my out directory was stale. Was present in r27, but I won't bother updating the sysroot just for that.
