### ISSUE TITLE
[BUG] UndefinedBehaviorSanitizer cannot crash the program

### ISSUE THREAD

**Issue by CoolCaicaixian** [android/ndk#2061]
### Description

I set wrap.sh based on [this](https://developer.android.com/ndk/guides/asan?hl=zh-cn) article, but when my program appeared UndefinedBehaviorSanitizer, it did not crash. Why?
Here is my wrap.sh：
```
cmd="$@"
export ASAN_OPTIONS=log_to_syslog=true,allow_user_segv_handler=1,abort_on_error=1
export UBSAN_OPTIONS=abort_on_error=1
ASAN_LIB=$(ls "$HERE"/libclang_rt.asan-*-android.so)
if [ -f "$HERE/libc++_shared.so" ]; then
    # Workaround for https://github.com/android-ndk/ndk/issues/988.
    export LD_PRELOAD="$ASAN_LIB $HERE/libc++_shared.so"
else
    export LD_PRELOAD="$ASAN_LIB"
fi
exec $cmd
```

Here is a screenshot of my run log：
<img width="806" alt="截屏2024-08-26 14 57 44" src="https://github.com/user-attachments/assets/c4429b23-d936-49be-ade4-da454bfc7e38">

### Affected versions

Canary

### Canary version

NDKr21e

### Host OS

Mac

### Host OS version

14.2.1

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

24

**Comment by DanAlbert** [comment]
There's a sample: https://github.com/android/ndk-samples/tree/main/sanitizers/app

There's not enough context here for us to be able to help more than that. Closing until we get a repro case, but you can probably just look at the sample and see what you've done differently? I don't think you need a wrap.sh at all for ubsan.

**Comment by pirama-arumuga-nainar** [comment]
In particular, since you're seeing the diagnostic without a crash, make sure the `-fno-sanitize-recover=undefined` flag is used (in both the compile and linker options).
