### ISSUE TITLE
[FR]TSAN runtime support?

### ISSUE THREAD

**Issue by bibop4** [android/ndk#2063]
### Description

I found libclang_rt.tsan-aarch64-android.so in the toolchain, so I'm wondering if TSan is currently supported? The roadmap seems to suggest that it's a future task. I am currently using ASan without issues, but I've tried several ways to get TSan working without success. If it is supported, do I need to run something in wrap.sh like I do with ASan?

**Comment by DanAlbert** [comment]
See the pinned bug: https://github.com/android/ndk/issues/1041
