### ISSUE TITLE
[BUG] #include "system_utils.h" in GameActivity 

### ISSUE THREAD

**Issue by kaizer1** [android/ndk#2066]
### Description

Hi, I have a question. I created an empty project in Android Studio with NDC support, but it doesn't compile. It writes this error (it seems to be a system error). I checked everything, everything is fine, but it doesn't start. Is this normal or not?

Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `L:\AndroidProject\Great\app\.cxx\Debug\3t171o67\arm64-v8a'
  [1/2] Building CXX object CMakeFiles/great.dir/main.cpp.o
  FAILED: CMakeFiles/great.dir/main.cpp.o 
  Q:\AndroidSDK\ndk\27.0.11718014\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android30 --sysroot=Q:/AndroidSDK/ndk/27.0.11718014/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgreat_EXPORTS -isystem C:/Users/loskutnikov/.gradle/caches/transforms-4/1de3c4a37baa744e547c3d91efe960f6/transformed/games-activity-3.0.5/prefab/modules/game-activity/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++20 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/great.dir/main.cpp.o -MF CMakeFiles\great.dir\main.cpp.o.d -o CMakeFiles/great.dir/main.cpp.o -c L:/AndroidProject/Great/app/src/main/cpp/main.cpp
  In file included from L:/AndroidProject/Great/app/src/main/cpp/main.cpp:6:
  C:/Users/loskutnikov/.gradle/caches/transforms-4/1de3c4a37baa744e547c3d91efe960f6/transformed/games-activity-3.0.5/prefab/modules/game-activity/include/game-activity/GameActivity.cpp:43:10: fatal error: 'system_utils.h' file not found
     43 | #include "system_utils.h"
        |          ^~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

Android studio: Android Studio Koala Feature Drop | 2024.1.2
System: Windows 11 
ndk version : ( 25.1.8937393 and test 27.0.12077973)
sdk: last ( 35 build tools )

### Affected versions

r27

### Host OS

Windows

### Host OS version

  23H2

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

31

### Device API level

32

**Comment by Ggjorven** [comment]
I have the exact same issue. Have you figured out a solution?

**Comment by kaizer1** [comment]
In a way - I just did it without GameActivity - and I'm still waiting for an answer

**Comment by Ggjorven** [comment]
I really just wanted to continue with my project, so as a temporary solution you can manually retrieve the file from here:
https://android.googlesource.com/platform/frameworks/opt/gamesdk/+/fc0183533cdb8aa7a0d54b2b6dc95c7c1879dbb4/src/common/system_utils.h

**Comment by kaizer1** [comment]
There is this file there, it just doesn't include it with the cmake build

**Comment by DanAlbert** [comment]
If this is a problem with an unmodified Android Studio project template (sounds like it), that's a Studio bug: "Android Studio" on http://b.android.com.

Otherwise, if this is a problem with GameActivity itself, you'll have to file a bug against the Games SDK ("Games SDK" on 
 http://b.android.com), as `GameActivity` isn't a part of the NDK.

Regardless, save yourself the pain and use the static library in the AAR rather than building from source: https://developer.android.com/games/agdk/game-activity/get-started#build-setup. See the [hello-vulkan](https://github.com/android/ndk-samples/blob/f3b1f879f17db913b9aa380e2fe890d228aa2eb2/hello-vulkan/app/build.gradle#L54) NDK sample as well.
