### ISSUE TITLE
[BUG] linking error (undefined symbol: __tls_get_addr) when using thread_local on armeabi-v7a builds (arm64-v8a works)

### ISSUE THREAD

**Issue by ArsenalLondon** [android/ndk#2069]
### Description

simply use "static thread_local xx yy" and the linker error appears on armeabi-v7a builds
Previously that worked without problems!

PS: One important thing I forgot to mention: this happens only with option -flto!!

### Affected versions

r27

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

armeabi-v7a

### Build system

CMake

### minSdkVersion

21

### Device API level

33, 34

**Comment by enh-google** [comment]
that's only available since api level 29...
```
LIBC_Q { # introduced=29
  global:
    ___tls_get_addr; # x86
    __aeabi_read_tp; # arm
    __res_randomid;
    __tls_get_addr; # arm riscv64 x86_64
```
but if your minSdkVersion is 21, you should only be getting emutls anyway (for all architectures)...

**Comment by ArsenalLondon** [comment]
> that's only available since api level 29...
> 
> ```
> LIBC_Q { # introduced=29
>   global:
>     ___tls_get_addr; # x86
>     __aeabi_read_tp; # arm
>     __res_randomid;
>     __tls_get_addr; # arm riscv64 x86_64
> ```
> 
> but if your minSdkVersion is 21, you should only be getting emutls anyway (for all architectures)...

sorry for my late PS, but still having any ideas?

**Comment by enh-google** [comment]
does `-femulated-tls` make it go away? (my best guess is that something's broken the logic that should have meant that minSdkVersion implied `-femulated-tls` and you're accidentally getting ELF TLS [which doesn't work that far back] where you weren't before.)

**Comment by DanAlbert** [comment]
My guess would actually be that something in your build is not actually `minSdkVersion 21`. Can you upload your build scripts? Or better yet a repro case? (IME bugs like this become obvious in the process of reducing the repro case)

**Comment by ArsenalLondon** [comment]
`-femulated-tls` didn't help. 
Yes, `minSDKVersion` is 21 and also the `arm64-v8a` build works correctly.
Only `armeabi-v7a` with `-flto` has the problem.

**Comment by DanAlbert** [comment]
We'll need a repro case.

**Comment by ArsenalLondon** [comment]
[MyApplication34.zip](https://github.com/user-attachments/files/16977892/MyApplication34.zip)

It's not exactly the same behavior I have, but hopefully it helps to fix the problem.
just compile & link attached 'Hello World' app and you will get 

```
ld.lld: error: undefined symbol: __tls_get_addr
>>> referenced by native-lib.cpp:8 (C:/Users/chr/AndroidStudioProjects/Mist/app/src/main/cpp/native-lib.cpp:8)
>>>               lto.tmp:(Java_com_example_myapplication_MainActivity_stringFromJNI)
>>> referenced by native-lib.cpp:9 (C:/Users/chr/AndroidStudioProjects/Mist/app/src/main/cpp/native-lib.cpp:9)
>>>               lto.tmp:(Java_com_example_myapplication_MainActivity_stringFromJNI)
>>> referenced by string:1865 (C:/Users/chr/AppData/Local/Android/Sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/string:1865)
>>>               lto.tmp:(Java_com_example_myapplication_MainActivity_stringFromJNI)
>>> referenced 1 more times

```
As soon as `thread_local` is removed from `static thread_local std::string hello = "Hello from C++";` or `android {  ndkVersion "27.1.12297006" }` is removed from the gradle file, the error goes away.

Does this help?

**Comment by DanAlbert** [comment]
You forgot to add `target_link_options(${CMAKE_PROJECT_NAME} PRIVATE -flto)`. You have to pass that while compiling _and_ linking.
