### ISSUE TITLE
[Bug]: NDK 27 crashes when building gdal 

### ISSUE THREAD

**Issue by fornwall** [android/ndk#2070]
### Description

See https://github.com/llvm/llvm-project/issues/67979 about a clang crash when building https://github.com/OSGeo/gdal - reproducible crash in NDK r27 (and r27b), works in NDK r26.

### Upstream bug

https://github.com/llvm/llvm-project/issues/67979

### Commit to cherry-pick

https://github.com/llvm/llvm-project/commit/5f4ee5a2dfa97fe32ee62d1d67aa1413d5a059e6

### Affected versions

r27

### Host OS

Linux

### Host OS version

Ubuntu 22.04

### Affected ABIs

arm64-v8a

**Comment by pirama-arumuga-nainar** [comment]
Thanks for the report.  https://android-review.googlesource.com/c/toolchain/llvm_android/+/3260808 picks up the fix into r27.

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar already fixed in the r28 toolchain, or is a cherry-pick needed there too?

**Comment by pirama-arumuga-nainar** [comment]
r28 toolchain already has the fix.
