### ISSUE TITLE
[DOC]Lỗi biên dịch với clang++ trong NDK r20b

### ISSUE THREAD

**Issue by TrinhBaoDuy** [android/ndk#2076]
### URL

clang++: note: diagnostic msg: C:\Users\TRINHB~1\AppData\Local\Temp\RenderInterfaceTypes-0bb43c.cpp clang++: note: diagnostic msg: C:\Users\TRINHB~1\AppData\Local\Temp\RenderInterfaceTypes-0bb43c.sh

### Problem

clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
![image](https://github.com/user-attachments/assets/5c231d3b-8285-4b5f-8241-88701038b280)

**Comment by enh-google** [comment]
r20b from 2019 is no longer supported. please try this year's r27b instead.
