### ISSUE TITLE
[BUG] Android-NDK build error (Unity 2032.2.20f1)

### ISSUE THREAD

**Issue by dstallmann** [android/ndk#2086]
### Description

Since I was asked to report this bug, I'll just do so. Please excuse any formal errors, as this is my first bug report.
The bug occurs when trying to build an application that previously worked for Android. There have been several updates and changes, so I can't pin it down to any singular change, that must have caused the issue.

`Stack dump:
0.	Program arguments: "C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++" -march=armv7-a -mfloat-abi=softfp -mfpu=neon-fp16 -marm -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -mllvm -hoist-common-insts=1 -mllvm --dse-memoryssa-defs-per-block-limit=0 -DANDROID -DHAVE_INTTYPES_H -no-canonical-prefixes -fstack-protector -fomit-frame-pointer -std=c++11 -Wswitch -Wno-trigraphs -Wno-tautological-compare -Wno-invalid-offsetof -Wno-implicitly-unsigned-literal -Wno-integer-overflow -Wno-shift-negative-value -Wno-unknown-attributes -Wno-implicit-function-declaration -Wno-null-conversion -Wno-missing-declarations -Wno-unused-value -Wno-pragma-once-outside-header -Wno-unknown-warning-option -Wno-undef-prefix -Wno-unused-command-line-argument -fvisibility=hidden -fexceptions -fno-rtti -funwind-tables -g -Os -fPIC -fno-strict-overflow -ffunction-sections -fdata-sections -fmessage-length=0 -pipe -D_GLIBCXX_USE_CXX11_ABI=0 -DBASELIB_INLINE_NAMESPACE=il2cpp_baselib -DIL2CPP_MONO_DEBUGGER_DISABLED -DRUNTIME_IL2CPP -DIL2CPP_ENABLE_WRITE_BARRIERS=1 -DIL2CPP_INCREMENTAL_TIME_SLICE=3 -DHAVE_BDWGC_GC -DNDEBUG -I. -IC:/Users/[Username]/Documents/UnityProjects/[ProjectName]/Library/Bee/artifacts/Android/il2cppOutput/cpp "-IC:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/il2cpp/libil2cpp/pch" "-IC:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/il2cpp/libil2cpp" "-IC:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/il2cpp/external/baselib/Include" "-IC:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/il2cpp/libil2cpp/os/ClassLibraryPAL/brotli/include" "-IC:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/il2cpp/external/baselib/Platforms/Android/Include" -o Library/Bee/artifacts/Android/iz17e/oey8d0ygggfn.o -fcolor-diagnostics -fdiagnostics-absolute-paths -target armv7a-linux-androideabi22 -fstrict-aliasing -fdiagnostics-format=msvc -c -x c++ C:/Users/[Username]/Documents/UnityProjects/[ProjectName]/Library/Bee/artifacts/Android/il2cppOutput/cpp/Generics.cpp
1.	C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\string_view:558:16: current parser token '__str_find_last_not_of'
2.	C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\string_view:192:1 <Spelling=C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\__config:793:37>: parsing namespace 'std'
3.	C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\string_view:192:1 <Spelling=C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\__config:793:60>: parsing namespace 'std::__ndk1'
4.	C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\string_view:195:1: parsing struct/union/class body 'std::basic_string_view'
5.	C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\string_view:557:5: parsing function body 'std::basic_string_view::find_last_not_of'
6.	C:/Program Files/Unity/Hub/Editor/2023.2.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/c++/v1\string_view:557:5: in compound statement ('{}')
#0 0x00007ff799446899 C:\Program Files\Unity\Hub\Editor\2023.2.20f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1296899 C:\Program Files\Unity\Hub\Editor\2023.2.20f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 0x1296812
0x00007FF799446899 (0x0000000000000001 0x00007FF79C88CE88 0x0000000000000001 0x0000012B53093A88)
0x00007FF799446812 (0x0000012B53B0E698 0x0000000000000000 0x0000012B53B0E740 0x000000081A7F8F70)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

### Device API level 34

Update:
-I created a new project, copied my assets from there, re-imported the relevant packages and the error still persists.
-The error does not occur on another project that is using the same Unity version and the same NDK
-Tried to migrate to Unity 6000.0.22f1 and the error still persists

**Comment by DanAlbert** [comment]
> Affected versions r23b

Not supported. Try with r27. If the problem persists, upload the artifacts the error message points to (there should be a section of the crash dump that says "PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT", we need those files)
