### ISSUE TITLE
[DOC] please, replace `go` domain link with `developer.android.com` in wiki.

### ISSUE THREAD

**Issue by twaik** [android/ndk#2088]
### URL

https://github.com/android/ndk/wiki/Changelog-r28

### Problem

`Issue 2058: Weak API references` points to `http://go/android-dev/ndk/guides/using-newer-apis`. Probably it will be better to use `https://developer.android.com/ndk/guides/using-newer-apis` link instead because it is publicly available.
Thank you.

**Comment by DanAlbert** [comment]
/me sighs

The Chrome extension I use that copies public links rather than the internal-only rewritten URL bar does the opposite for developer.android.com. Sorry about that.

**Comment by DanAlbert** [comment]
The live copy is fixed and I've got a change up to fix the source so I don't accidentally revert the fix when the next version of r28 ships. Closing, but it's still tagged as todo in r28 so I don't forget to cherry-pick the fix.
