### ISSUE TITLE
[Bug]: clang: error: clang frontend command failed due to signal (use -v to see invocation)

### ISSUE THREAD

**Issue by desaco1989** [android/ndk#2091]
### Description

#42 0x00007ff6591714c8 (F:\dev_env\android-sdk\ndk\android-ndk-r22b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe+0x14c8)
#43 0x00007ff9381854e0 (C:\Windows\System32\KERNEL32.DLL+0x154e0)
#44 0x00007ff93908485b (C:\Windows\SYSTEM32\ntdll.dll+0x485b)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Android (7155654, based on r399163b1) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
Target: aarch64-unknown-linux-android29
Thread model: posix
InstalledDir: F:\dev_env\android-sdk\ndk\android-ndk-r22b\toolchains\llvm\prebuilt\windows-x86_64\bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: C:\msys64\tmp\vf_curves-09e3ca.c
clang: note: diagnostic msg: C:\msys64\tmp\vf_curves-09e3ca.sh
clang: note: diagnostic msg:

********************
make: *** [ffbuild/common.mak:59: libavfilter/vf_curves.o] Error 1

### Affected versions

r27

### Host OS

Windows

### Host OS version

Windows11

### Affected ABIs

armeabi-v7a

**Comment by DanAlbert** [comment]
```
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: C:\msys64\tmp\vf_curves-09e3ca.c
clang: note: diagnostic msg: C:\msys64\tmp\vf_curves-09e3ca.sh
clang: note: diagnostic msg:
```

**Comment by desaco1989** [comment]
-- C:\msys64\tmp\vf_curves-09e3ca.sh
# Crash reproducer for Android (7155654, based on r399163b1) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
# Driver args: "--target=aarch64-linux-android29" "-I" "." "-I" "./" "--sysroot=F:/dev_env/android-sdk/ndk/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot" "-D" "_ISOC99_SOURCE" "-D" "_FILE_OFFSET_BITS=64" "-D" "_LARGEFILE_SOURCE" "-D" "strtod=avpriv_strtod" "-D" "PIC" "-D" "ZLIB_CONST" "-D" "HAVE_AV_CONFIG_H" "-D" "BUILDING_avfilter" "-march=armv8-a" "-std=c11" "-fPIE" "-fomit-frame-pointer" "-fPIC" "-pthread" "-g" "-Wdeclaration-after-statement" "-Wall" "-Wdisabled-optimization" "-Wpointer-arith" "-Wredundant-decls" "-Wwrite-strings" "-Wtype-limits" "-Wundef" "-Wmissing-prototypes" "-Wno-pointer-to-int-cast" "-Wstrict-prototypes" "-Wempty-body" "-Wno-parentheses" "-Wno-switch" "-Wno-format-zero-length" "-Wno-pointer-sign" "-Wno-unused-const-variable" "-Wno-bool-operation" "-Wno-char-subscripts" "-Oz" "-fno-math-errno" "-fno-signed-zeros" "-mstack-alignment=16" "-Qunused-arguments" "-Werror=implicit-function-declaration" "-Werror=missing-prototypes" "-Werror=return-type" "-MMD" "-MF" "libavfilter/vf_curves.d" "-MT" "libavfilter/vf_curves.o" "-c" "-o" "libavfilter/vf_curves.o" "libavfilter/vf_curves.c"
# Original command:  "F:\\dev_env\\android-sdk\\ndk\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe" "-cc1" "-triple" "aarch64-unknown-linux-android29" "-emit-obj" "-mnoexecstack" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "vf_curves.c" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=none" "-fno-signed-zeros" "-fno-rounding-math" "-mconstructor-aliases" "-target-cpu" "generic" "-target-feature" "+neon" "-target-abi" "aapcs" "-mllvm" "-aarch64-fix-cortex-a53-835769=1" "-fallow-half-arguments-and-returns" "-fno-split-dwarf-inlining" "-debug-info-kind=limited" "-dwarf-version=4" "-debugger-tuning=gdb" "-resource-dir" "F:\\dev_env\\android-sdk\\ndk\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\11.0.5" "-dependency-file" "libavfilter/vf_curves.d" "-MT" "libavfilter/vf_curves.o" "-I" "." "-I" "./" "-D" "_ISOC99_SOURCE" "-D" "_FILE_OFFSET_BITS=64" "-D" "_LARGEFILE_SOURCE" "-D" "strtod=avpriv_strtod" "-D" "PIC" "-D" "ZLIB_CONST" "-D" "HAVE_AV_CONFIG_H" "-D" "BUILDING_avfilter" "-isysroot" "F:/dev_env/android-sdk/ndk/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot" "-internal-isystem" "F:/dev_env/android-sdk/ndk/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include" "-internal-isystem" "F:\\dev_env\\android-sdk\\ndk\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\11.0.5\\include" "-internal-externc-isystem" "F:/dev_env/android-sdk/ndk/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android" "-internal-externc-isystem" "F:/dev_env/android-sdk/ndk/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include" "-internal-externc-isystem" "F:/dev_env/android-sdk/ndk/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include" "-Oz" "-Wdeclaration-after-statement" "-Wall" "-Wdisabled-optimization" "-Wpointer-arith" "-Wredundant-decls" "-Wwrite-strings" "-Wtype-limits" "-Wundef" "-Wmissing-prototypes" "-Wno-pointer-to-int-cast" "-Wstrict-prototypes" "-Wempty-body" "-Wno-parentheses" "-Wno-switch" "-Wno-format-zero-length" "-Wno-pointer-sign" "-Wno-unused-const-variable" "-Wno-bool-operation" "-Wno-char-subscripts" "-Werror=implicit-function-declaration" "-Werror=missing-prototypes" "-Werror=return-type" "-std=c11" "-fconst-strings" "-fdebug-compilation-dir" "F:\\A_Demo\\compile_FFmpeg\\ffmpeg-4.3.8" "-ferror-limit" "19" "-fmessage-length=100" "-pthread" "-mstack-alignment=16" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-vectorize-slp" "-o" "libavfilter/vf_curves.o" "-x" "c" "libavfilter/vf_curves.c"
 "F:\\dev_env\\android-sdk\\ndk\\android-ndk-r22b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe" "-cc1" "-triple" "aarch64-unknown-linux-android29" "-emit-obj" "-mnoexecstack" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "vf_curves.c" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=none" "-fno-signed-zeros" "-fno-rounding-math" "-mconstructor-aliases" "-target-cpu" "generic" "-target-feature" "+neon" "-target-abi" "aapcs" "-mllvm" "-aarch64-fix-cortex-a53-835769=1" "-fallow-half-arguments-and-returns" "-fno-split-dwarf-inlining" "-debug-info-kind=limited" "-dwarf-version=4" "-debugger-tuning=gdb" "-D" "_ISOC99_SOURCE" "-D" "_FILE_OFFSET_BITS=64" "-D" "_LARGEFILE_SOURCE" "-D" "strtod=avpriv_strtod" "-D" "PIC" "-D" "ZLIB_CONST" "-D" "HAVE_AV_CONFIG_H" "-D" "BUILDING_avfilter" "-Oz" "-Wdeclaration-after-statement" "-Wall" "-Wdisabled-optimization" "-Wpointer-arith" "-Wredundant-decls" "-Wwrite-strings" "-Wtype-limits" "-Wundef" "-Wmissing-prototypes" "-Wno-pointer-to-int-cast" "-Wstrict-prototypes" "-Wempty-body" "-Wno-parentheses" "-Wno-switch" "-Wno-format-zero-length" "-Wno-pointer-sign" "-Wno-unused-const-variable" "-Wno-bool-operation" "-Wno-char-subscripts" "-Werror=implicit-function-declaration" "-Werror=missing-prototypes" "-Werror=return-type" "-std=c11" "-fconst-strings" "-ferror-limit" "19" "-fmessage-length=100" "-pthread" "-mstack-alignment=16" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-vectorize-slp" "-x" "c" "vf_curves-09e3ca.c"

**Comment by desaco1989** [comment]
[Uploading vf_curves-09e3ca.zip…]()

**Comment by desaco1989** [comment]
please help me to analyze

**Comment by pirama-arumuga-nainar** [comment]
> Uploading vf_curves-09e3ca.zip…

This file did not upload correctly - please re-upload.
