### ISSUE TITLE
[DOC] Wiki page still shows NDK r27b as latest release

### ISSUE THREAD

**Issue by fornwall** [android/ndk#2096]
### URL

https://github.com/android/ndk/wiki#ndk-r27b-2024-lts

### Problem

The title at https://github.com/android/ndk/wiki#ndk-r27b-2024-lts still shows `NDK r27b`:

![Screenshot from 2024-10-24 16-40-25](https://github.com/user-attachments/assets/9cef5dfb-885d-43cb-b0ab-e4c4e853e0f4)

**Comment by DanAlbert** [comment]
Fixed, thanks
