### ISSUE TITLE
[BUG] Segmentation fault when I trying to use llvm-bolt with instrumentation

### ISSUE THREAD

**Issue by jzyxbb** [android/ndk#2103]
### Description

I want to use llvm-bolt with instrumentation to optimize binary.
I create an Android.bp to compile main.cpp:

Android.bp
```
cc_library {
    name: "testbin",
    srcs: [
        "main.cpp",
    ],

    ldflags: [
        "-Wl,--emit-relocs",
        "-shared",
    ],
}
```

main.cpp
```
#include <unistd.h>

int main()
{
    int a = 1;
    while(a <= 10) {
        a++;
        sleep(1);
    }
}
```

And then use llvm-bolt to instrument the testbin.so
```
./llvm-bolt testbin.so  -instrument -o testbin.so
```

The error as below
```
BOLT-INFO: shared object or position-independent executable detected
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: d8003a456d14a3deb8054cdaa529ffbf02d9b262
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: creating new program header table at address 0x200000, offset 0x200000
BOLT-WARNING: debug info will be stripped from the binary. Use -update-debug-sections to keep it.
BOLT-INFO: enabling relocation mode
BOLT-INFO: forcing -jump-tables=move for instrumentation
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
BOLT-INFO: number of removed linker-inserted veneers: 0
BOLT-INFO: 0 out of 5 functions in the binary (0.0%) have non-empty execution profile
 #0 0x0000556148d41372 (./llvm-bolt+0x2886372)
 #1 0x0000556148d402d2 (./llvm-bolt+0x28852d2)
 #2 0x0000556148d417e2 (./llvm-bolt+0x28867e2)
 #3 0x00007f27af0c1980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #4 0x0000556148f4525e (./llvm-bolt+0x2a8a25e)
 #5 0x0000556148d72733 (./llvm-bolt+0x28b7733)
 #6 0x0000556148d7574a (./llvm-bolt+0x28ba74a)
 #7 0x0000556148d8a802 (./llvm-bolt+0x28cf802)
 #8 0x0000556148924a4e (./llvm-bolt+0x2469a4e)
 #9 0x00007f27ae100c87 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c87)
#10 0x000055614882c489 (./llvm-bolt+0x2371489)
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: ./llvm-bolt testbin.so -instrument -o testbin.so
Segmentation fault (core dumped)
```

### Affected versions

Canary

### Canary version

25.1.8937393

### Host OS

Linux

### Host OS version

Ubuntu 18.04.2 LTS

### Affected ABIs

arm64-v8a

### Build system

ndk-build

### minSdkVersion

1

**Comment by pirama-arumuga-nainar** [comment]
(@kongy as FYI)

Note that BOLT is a fairly new tool in LLVM, so we cannot provide any stability or support across NDK releases.

> Canary version
> 25.1.8937393

This is fairly old, and IIUC, bolt had some fixes to arm64 instrumentation mode recently.  Can you try a newer NDK - r28 beta1 or r27?

**Comment by DanAlbert** [comment]
Will reopen if the problem persists with a supported NDK.

**Comment by jzyxbb** [comment]
Hi Dan

Could you tell me the relationship between ndk and llvm-bolt?
I build the module with aosp. The ndk version  is 25.0.8474149, how to update it?
![image](https://github.com/user-attachments/assets/25066338-1308-4268-8fc4-98dde96edfac)

thx

**Comment by DanAlbert** [comment]
Oh, you're not actually using the NDK. Ignore `prebuilts/ndk`, that wasn't a very accurate name when it was used and I think it's now actually completely obsolete.

@pirama-arumuga-nainar this a platform thing, not the NDK. (in the future, https://groups.google.com/g/android-llvm is I think the best place to get answers for platform toolchain questions)
