### ISSUE TITLE
[BUG] libc++_shared.so does not have canary enabled on ndk 27.2.12479018 ,and setting fortify_source does not take effect when compiling so with toolchain

### ISSUE THREAD

**Issue by tonyzzz** [android/ndk#2108]
### Description

1. check the libc++_shared.so from Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so and find out the lib does not have canary enabled
2. when we build our so use cmakelist and set the -D_FORTIFY_SOURCE=2 param but it does not take effect.

### I am using a supported NDK

- [X] I have checked and the NDK I'm using is currently supported

### Affected versions

r27

**Comment by DanAlbert** [comment]
In the future, please file two bug reports when you want to report two bugs. GitHub's tools only let me track whole bug reports. Things will get lost if a single bug report contains multiple unrelated issues.

1. Yes. Do you expect otherwise?
2. Upload a repro case. Will reopen when we get one.

**Comment by tonyzzz** [comment]
> In the future, please file two bug reports when you want to report two bugs. GitHub's tools only let me track whole bug reports. Things will get lost if a single bug report contains multiple unrelated issues.
> 
> 1. Yes. Do you expect otherwise?
> 2. Upload a repro case. Will reopen when we get one.

when will be the first issue fixed?

**Comment by DanAlbert** [comment]
What issue? I don't understand what the problem is.
