### ISSUE TITLE
linker.list does not properly escape the slashes in Windows when using LOCAL_SHORT_COMMANDS

### ISSUE THREAD

**Issue by styill** [android/ndk#213]
When building a shared library with LOCAL_SHORT_COMMANDS set to true, a linker list is generated that uses Windows slashes, but linking will fail because it won't be able to find any of the files due to the slash being used as an escape character in the path. This is similar to issue 186 with the archiver.

**Comment by DanAlbert** [comment]
I think we're going to experiment with updating make in r20, and newer versions have built in support for generating list files.

**Comment by DanAlbert** [comment]
Duping into https://github.com/android/ndk/issues/986 since it has the suggested fix.
