### ISSUE TITLE
Decrement the cmake version required for the toolchain file

### ISSUE THREAD

**Issue by tberghammer** [android/ndk#225]
The current toolchain file specifies that it requires cmake version 3.6.0 but it actually works with older versions of cmake as well (tested with 3.5.2). It would be great if we can figure out the actual minimum requirement and set it accordingly as most Linux distributions ship an older version of cmake (Trusty: 2.8.12, Xenial: 3.5.1)

**Comment by DanAlbert** [comment]
@chaoren: I don't know the story behind why we chose such a recent version. I thought we were using some features that required at least a 3.x release, but idk which one we need specifically.

**Comment by tberghammer** [comment]
I think the story is that Android Studio ships its own copy of cmake and that is based on 3.6.0 so somebody decided to specify that version.

**Comment by chaoren** [comment]
We need 3.6 for CMAKE_<LANG>_STANDARD_LIBRARIES, CMAKE_<LANG>_STANDARD_INCLUDE_DIRECTORIES, and and CMAKE_TRY_COMPILE_PLATFORM_VARIABLES.

I don't see how it could work for < 3.6.

**Comment by tberghammer** [comment]
Chaoren is right that some of these variables are only available since 3.6.0 (CMAKE_STANDARD_INCLUDE_DIRECTORIES, CMAKE_TRY_COMPILE_PLATFORM_VARIABLES).

In that case the different question is can we change the toolchain file to work with an older version of cmake considering that most user of the NDK will have an old version?

**Comment by DanAlbert** [comment]
IIRC earlier versions of cmake also assume that Android means Tegra Nsight. That error message popped up a lot when I ran the NDK tests on my Windows box that had a version of cmake installed from the web rather than from studio (I don't remember what version).

Might be worth looking in to since even Xenial isn't on 3.6, but I'm not sure how feasible that is since aiui we're still adding features even to the latest release of cmake.

**Comment by chaoren** [comment]
Those variables are added specifically to make toolchain files work nicer. It'd be a mess to try to get everything working with < 3.6 (See mess here: https://github.com/taka-no-me/android-cmake/blob/master/android.toolchain.cmake).

I guess we could move our CMake binary from the SDK into the NDK. IIRC, it's like 50MB.

**Comment by DanAlbert** [comment]
Yeah, that seems reasonable to me.

Not scheduling for a particular release since this just a nice to have and we still have plenty of fires to put out :)

**Comment by chaoren** [comment]
We need 3.6 for CMAKE_<LANG>_STANDARD_LIBRARIES,
CMAKE_<LANG>_STANDARD_INCLUDE_DIRECTORIES, and
and CMAKE_TRY_COMPILE_PLATFORM_VARIABLES.

**Comment by DanAlbert** [comment]
We're not likely to do this. If anything we'd probably raise it, but so far we have no need to do that.
