### ISSUE TITLE
What is the equivalent of `import-module` (of Android.mk) in CMake?

### ISSUE THREAD

**Issue by kuldeepdhaka** [android/ndk#268]
What is the equivalent of `import-module` (of Android.mk) in CMake?

https://android.googlesource.com/platform/ndk/+/675fe49445e65ba44d91f4d85ed9b4d5b5ff6745/docs/IMPORT-MODULE.TXT

**Comment by kuldeepdhaka** [comment]
https://android.googlesource.com/platform/ndk/+/675fe49445e65ba44d91f4d85ed9b4d5b5ff6745/docs/IMPORT-MODULE.TXT

**Comment by DanAlbert** [comment]
AFAIK there isn't one. @chaoren: was there a plan in place to support something like this in CMake, or is this still an open question?

**Comment by chaoren** [comment]
CMake has [`add_subdirectory`](https://cmake.org/cmake/help/v3.6/command/add_subdirectory.html) for including other `CMakeLists.txt` files, similar to how you would include one `Android.mk` from another with `import-module`. If you mean you want to include an entirely separate project or include an `Android.mk` from CMake, then you could also use [`ExternalProject`](https://cmake.org/cmake/help/v3.6/module/ExternalProject.html) to build the `Android.mk` and use the output of that as a target for linking.

**Comment by DanAlbert** [comment]
Thanks, @chaoren!

We should get a guide for doing this into the docs.

**Comment by ggfan** [comment]
once get into CMake area, we would depend on CMake's documentation https://cmake.org/documentation/; our documentation would focus on interface between gradle and cmake -- what parameters could be used to pass to cmake and the syntax.

**Comment by DanAlbert** [comment]
Our docs should at least point to the relevant cmake docs. This part in particular would be good for a "cmake for ndk-build users" guide.

**Comment by timluther** [comment]
Stumbling upon this in 2018: is this still an issue, is there any way to build previously working android libraries and have them link correctly in the new build system.
I don't mind messing about with cmake, that's easy enough but linking external libraries is _still a total pain_. 
Is this an appropriate place to ask questions? I'm in library linking hell right now with this new build system - it's very frustrating as I had it all running perfectly under ndk-build (which, in itself, took ages and mountains of scripts to achieve) and now nothing works again. I feel like I'm being sabotaged by well funded teams of belligerent build engineers.

**Comment by alexcohn** [comment]
@timluther 

1. **ndk-build** is fully supported, including Android Studio
2. if you need a hybrid setup, with some libraries are built via **cmake**, and other libraries are built via **ndk-build**, you can set up separate Modules in Android Studio, each having **externalNativeBuild**. This way, you have full power of IDE support for your C++ editor and debugger. Consider wisely splitting your Java sources between these modules. If the C++ libraries depend on one another, be careful to set up correct paths to **PREBUILT** (in ndk-build terms) or **IMPORTED** (in cmake terms) libs, and arrange the correct build order in gradle.
3. use ExternalTarget, e.g. as in https://stackoverflow.com/a/47636956/192373. The drawback of this approach is that Android Studio will not understand how your C++ code is related to you project.

**Comment by timluther** [comment]
Thanks for the reply Alex.
Having full debugging support and being able to keep older ndk-build based projects as is sounds ideal, although there a few things I can't figure out yet.
I might be a bit green with the terminology here - a 'module' in Android studio parlance is like a project in visual studio? If I have an external ndk-build based library, how do I import that as a module in to android studio (I can't see any options to...)
I've been trying to add libraries in the 'CMakeLists.txt' file (as explained here: https://stackoverflow.com/questions/49781205/linking-external-libraries-using-ndk-gradle-cmake-in-android-studio) but I've got nowhere with this (I can't even see the CMake errors from within android studio, for some reason)
I'm new to both gradle and cmake so I should think I'm probably labouring under some misconceptions.

**Comment by ggfan** [comment]
you already have your top level Android.mk file, could you open your [application project's module](https://github.com/googlesamples/android-ndk/blob/master-ndkbuild/Teapot/app/build.gradle) build.gradle file, and add:
    externalNativeBuild {
        ndkBuild {
            path 'point/to/your/Android.mk'
        }
    }
The top level Application.mk's setting needs to be set inside build.gradle too. To my understanding, module of Android Studio is same as Project in MSVC.

Let's first modify your build.gradle to connect to your Android.mk, see how it goes.  Will find the parameters to set inside build.gradle to match your application.mk

**Comment by timluther** [comment]
Ah, OK, that makes sense! Thank you, I'll try that. That's one piece I was missing, the scope of the 'externalNativeBuild' section: I didn't know it could do that. 
Will this handle the linking as well, as in will my main project also be aware of these projects and 'just work' if I reference the libraries using 'target_link_libraries' or something similar?

**Comment by DanAlbert** [comment]
I've sent a CL to add the following to :

## Building third-party code

There are a handful of ways to build third-party code as part of your CMake
project, and which option works best will depend on your situation. The best
option will often be to not do this at all. Instead, [build an AAR] for the
library and consume that in your application. You do not necessarily need to
*publish* that AAR. It can be internal to your Gradle project.

If that's not an option:

*   Vendor (i.e. copy) the third-party source into your repository and use
    [add_subdirectory] to build it. This only works if the other library is also
    built with CMake.
*   Define an [ExternalProject].
*   Build the library separately from your project and follow
    [Use prebuilt libraries] to import it as a prebuilt.

[build an AAR]: https://developer.android.com/studio/build/dependencies?buildsystem=cmake&agpversion=4.1#publish-native-libs-in-aars
[add_subdirectory]: https://cmake.org/cmake/help/latest/command/add_subdirectory.html
[ExternalProject]: https://cmake.org/cmake/help/latest/module/ExternalProject.html
[Use prebuilt libraries]: https://developer.android.com/ndk/guides/cmake#using_prebuilt_libraries

And also expanded the other section to:

## Use prebuilt libraries

If the prebuilt library you need to import is distributed as an AAR, follow
[Studio's dependency docs](https://developer.android.com/studio/build/dependencies#native-dependencies-with-agp)
to import and use those. If you are not using AGP you can follow
https://google.github.io/prefab/example-workflow.html, but it is likely much
easier to migrate to AGP.

For libraries that are not distributed as an AAR, instructions on using prebuilt
libraries with CMake, see the `add_library` documentation regarding `IMPORTED`
targets in the [CMake manual].

[CMake manual]: https://cmake.org/cmake/help/latest/command/add_library.html
