### ISSUE TITLE
reject invalid arguments to make-standalone-toolchain.sh

### ISSUE THREAD

**Issue by enh** [android/ndk#270]
#### Description

on the toybox mailing list there's a thread about building with the NDK. trying to reproduce http://lists.landley.net/pipermail/toybox-landley.net/2016-December/008771.html i downloaded r14beta1 and used make-standalone-toolchain. a few things confused me:

* .sh versus .py --- i used the .sh first because - feels more natural and Unixy than _, so when tab-completion offered me the choice, i took the wrong one. can we make it (a) clearer that .sh is deprecated and (b) clearer when you've used an option that .sh doesn't understand that you should use .py? (iirc there's some reason why the .sh can't just exec the .py.)

* --unified-headers versus --abi --- at first i used --unified-headers, which seemed to leave me in a state where `__ANDROID_API__` wasn't defined, so i didn't get most of the new stuff. when i tried to add `-D__ANDROID_API__` to the toybox cflags (CROSS_COMPILE=/tmp/arm64-unified/bin/aarch64-linux-android- CC=clang CFLAGS=-D__ANDROID_API__=25 make) i got weird errors about redefining `__ANDROID_API__` (maybe the toybox build system's fault?) but using --unified-headers *and* --abi 25 did what i wanted. but that wasn't what i was expecting to have to say. can we improve the docs to explain the choices/trade offs here?

* link to make-standalone-toolchain docs from unified header docs? it was surprising to me that there wasn't an easy route from one to the other (even if they are on different sites).

**Comment by DanAlbert** [comment]
> .sh versus .py --- i used the .sh first because - feels more natural and Unixy than _, so when tab-completion offered me the choice, i took the wrong one. can we make it (a) clearer that .sh is deprecated

It isn't really: https://github.com/android-ndk/ndk/issues/121

I'd like the just remove the old one (at one point I did), but that is a pain for some users. I suppose I could put back the message that people might want to consider the new one, but the idea was that both are valid options.

> and (b) clearer when you've used an option that .sh doesn't understand that you should use .py? (iirc there's some reason why the .sh can't just exec the .py.)

Ack. This could probably use some cleanup.

> at first i used --unified-headers, which seemed to leave me in a state where __ANDROID_API__ wasn't defined

GCC or Clang? That's expected for GCC: https://github.com/android-ndk/ndk/wiki/Changelog-r14-beta1#wont-fix

> --unified-headers versus --abi --- at first i used --unified-headers, which seemed to leave me in a state where __ANDROID_API__ wasn't defined, so i didn't get most of the new stuff. when i tried to add -D__ANDROID_API__ to the toybox cflags (CROSS_COMPILE=/tmp/arm64-unified/bin/aarch64-linux-android- CC=clang CFLAGS=-D__ANDROID_API__=25 make) i got weird errors about redefining __ANDROID_API__ (maybe the toybox build system's fault?) but using --unified-headers and --abi 25 did what i wanted. but that wasn't what i was expecting to have to say. can we improve the docs to explain the choices/trade offs here?

itym `--api`. That change makes this whole report less confusing :)

Wasn't defined, or wasn't defined to the latest version? It defaults to the lowest for the ABI: https://android.googlesource.com/platform/ndk/+/master/build/tools/make_standalone_toolchain.py#600

If it was defined to 9 or 21, then WAI and we should improve the doc.

If not defined at all, then that's a bug. I don't see how that would happen for Clang though, so I'd need a repro case for these.

> link to make-standalone-toolchain docs from unified header docs? it was surprising to me that there wasn't an easy route from one to the other (even if they are on different sites).

https://android-review.googlesource.com/c/317802/

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/319649 fixes the `--api` default confusion.

I've retitled the bug to cover the final point:

>> and (b) clearer when you've used an option that .sh doesn't understand that you should use .py? (iirc there's some reason why the .sh can't just exec the .py.)

> Ack. This could probably use some cleanup.

**Comment by DanAlbert** [comment]
The shell script variant of this tool was removed in r25.
