### ISSUE TITLE
include libFuzzer in the NDK

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#305]
Including LLVM's libFuzzer in the NDK would make it easier for developers to track down odd crashes that they see reported in the field but can't reproduce locally.

**Comment by juneJuly** [comment]
@DanAlbert 
so, libFuzzer is ready for Android yet?

**Comment by stephenhines** [comment]
No, it is not. We are hoping to have it in r16, but it could be later than that depending on other bugs.

**Comment by DanAlbert** [comment]
@stephenhines: I forget where we landed on this. Is this going to require moving the NDK's libc++ into the toolchain?

**Comment by stephenhines** [comment]
Yes, all of libc++ will have to live inside the toolchain if we want to do anything like this. That is the cost of shipping "prebuilts".

**Comment by DanAlbert** [comment]
Yeah, I'm afraid that's a pretty big change on our end that will probably hinder development quite a bit (and this is the worst possible time to hinder our libc++ work), so this is going to have to go on the back burner until we're in a different position.

**Comment by juneJuly** [comment]
so , it's impossible to use libfuzzer to test Android for now

**Comment by DanAlbert** [comment]
Out of the box, yes. I think you could fetch the LLVM sources matching the NDK compiler release (the SVN revision is in AndroidVersion.txt) and build your own libFuzzer with the NDK and use it. In fact, this is probably a better choice for us than trying to move libc++ into the toolchain. @stephenhines, do you see any issues with that?

**Comment by stephenhines** [comment]
That should mostly work for a dedicated developer. We do occasionally have other patches on top of that SVN revision, but I don't think I have ever seen one that would impact libFuzzer. Ultimately we do need to move libc++ into the toolchain to support many other prebuilts, but right now, I think this is the most timely option.

**Comment by juneJuly** [comment]
@stephenhines @DanAlbert 
i will try AndroidVersion.txt.
thanks all the way.
may i contact you if i encountered problems ?

**Comment by juneJuly** [comment]
well, there comes the problem.
the latest ndk version r14b just support clang-3.8.256229,
while clang-3.8 not support libfuzzer.
so, can't cross compile libFuzzer.a

**Comment by DanAlbert** [comment]
r15's Clang should.

**Comment by juneJuly** [comment]
@DanAlbert 
thank u, ndk-r15-beta works well.
and if someone encountered error like:
    "error: no member named 'to_string' in namespace 'std'"
plz take a look into this link: 
    https://github.com/android-ndk/ndk/issues/82

**Comment by DanAlbert** [comment]
Yeah, we know. It's the main priority and has been for a few releases, but other things keep getting in the way.

**Comment by DanAlbert** [comment]
Apparently I opened this bug twice. The fuzzer works now. Not sure when it was first supported, but there's a working example in https://github.com/android/ndk/issues/653
