### ISSUE TITLE
Document that cmake will override user specified cflags with release/debug flags

### ISSUE THREAD

**Issue by silentnuke** [android/ndk#378]
#### Description
Depending on build type it automatically adds flags for release (`-Os -DNDEBUG`) and for debug (`-O0 -fno-limit-debug-info`). (android_gradle_build.json) 
```json
{
	"flags" : "  -target armv7-none-linux-androideabi -gcc-toolchain /Users/kostiantyn.zghirovskyi/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/kostiantyn.zghirovskyi/Library/Android/sdk/ndk-bundle/platforms/android-16/arch-arm  -Dnative_lib_EXPORTS -isystem /Users/kostiantyn.zghirovskyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/kostiantyn.zghirovskyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /Users/kostiantyn.zghirovskyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward  -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -std=c++11 -frtti -fexceptions -O3 -Os -DNDEBUG -Os -DNDEBUG  -fPIC    -c ",
	"src" : "/Users/kostiantyn.zghirovskyi/Snapchat/Dev/snapchat/SilentTest/app/src/main/cpp/native-lib.cpp",
	"workingDirectory" : "/Users/kostiantyn.zghirovskyi/Snapchat/Dev/snapchat/SilentTest/app/.externalNativeBuild/cmake/release/armeabi-v7a"
}
```

E.g. I passed optimization level -O3, however the default -Os was added to the end.
This makes impossible for the app to specify different optimization level, since default flags for build type are always added to the end of the final flags, so user choice will be always overridden.

#### Environment Details
* NDK Version: 13.1.3345770
* Build sytem: cmake
* Host OS: Mac
* Compiler: clang

**Comment by DanAlbert** [comment]
Where are you adding your flags? If you're adding them to `CMAKE_CXX_FLAGS_RELEASE`, yours should be appended to ours. We don't really have any control over where things appear. CMake itself makes those decisions.

**Comment by kostiantynzghirovskyisc** [comment]
@DanAlbert oh, yeah, my bad. I was trying to add from `CMakeLists.txt` to `CMAKE_CXX_FLAGS` and also from gradle to `externalNativeBuild.cmake.cppFlags`.

Adding to `CMAKE_CXX_FLAGS_RELEASE` works, as expected

**Comment by DanAlbert** [comment]
Alright, if that works that's probably the expected behavior. `CMAKE_CXX_FLAGS` would probably have been my first guess too, but I suppose it makes sense for those to be overridden by `RELEASE`/`DEBUG` flags since those are going to be more specific.

Probably worth us documenting, so I'll reopen this to track that.

**Comment by DanAlbert** [comment]
@qchong: Probably don't need anything more than a blurb telling people that flags for optimization level need to be added specifically to the `CMAKE_CXX_FLAGS_RELEASE` (or `DEBUG`) lists rather than to `CMAKE_CXX_FLAGS`.

**Comment by kostiantynzghirovskyisc** [comment]
@DanAlbert yeah, docs would be useful.

Also, there is no way to pass these flags from gradle. Should we create feature request?
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.ExternalNativeCmakeOptions.html

cppFlags would be passed as `CMAKE_CXX_FLAGS`. Just to make sure, I also checked the behaviour if I specify them in `release` build type. Result is the same, they passed as `CMAKE_CXX_FLAGS`.

```
buildTypes {
        release {
            minifyEnabled false

            externalNativeBuild {
                cmake {
                    cppFlags "-Ddoes_this_works"
                }
            }
        }
    }
```

**Comment by guilhemvors** [comment]
Yes, this would be most appreciated

**Comment by LoveDaisy** [comment]
I'm wondering what is the best practice, 
1. to set c++ flags directly in CMakelists.txt like:
```shell
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
```
2. to pass c++ flags via gradle like:
```groovy
externalNativeBuild {
    cmake {
        cppFlags "-O3"
    }
}
```
I guess the first way always works, but I'm not sure about the second one. Does it override those flags set in CMakelists.txt or append flags to them?

**Comment by DanAlbert** [comment]
http://cl/666459937 adds new docs. Should be live soon after I get past code review.

**Comment by DanAlbert** [comment]
http://go/android-dev/ndk/guides/cmake#manage_compiler_flags
