### ISSUE TITLE
add native_heapdump_viewer.py to NDK

### ISSUE THREAD

**Issue by enh** [android/ndk#435]
development/scripts/native_heapdump_viewer.py seems like something that would be useful for NDK developers, not just platform developers. cferris makes it sound like the only thing we'd need to change would be how/where it finds symbols.

"...the script was really meant for platform developers so it looks for shared libraries in a very specific way. For example, it will look for the symbols in OUR_SYMBOL_DIR/data/app/..snapchat../lib/arm (or arm64). If you've put all of your shared library symbolized files in the OUR_SYMBOL_DIR top level directory, then it won't be able to find anything. You need to mirror the directory structure for the app in the OUR_SYMBOL_DIR directory."

**Comment by dturner** [comment]
`native_heapdump_viewer.py` is also referenced here (right after the section for app developers): https://android.googlesource.com/platform/bionic/+/master/libc/malloc_debug/README.md

**Comment by DanAlbert** [comment]
@enh-google: Do you want to look at this for r21? It's a similar task to the ndk-stack change you did last release, right?

If not, I think I'll punt out of the release.

**Comment by enh-google** [comment]
not sure whether it's worth doing this or just going straight to Perfetto... command-line perfetto (https://developer.android.com/studio/command-line/perfetto) is probably a better choice for app developers already, and i'm assuming there will be a Studio GUI at some point?

**Comment by DanAlbert** [comment]
I'm assuming neither will get done particularly soon, so moving to r23.

**Comment by enh-google** [comment]
https://android-review.googlesource.com/c/platform/development/+/1747255 removes the script from the platform, and https://android-review.googlesource.com/c/platform/bionic/+/1747574 removes the mention in the documentation...

**Comment by DanAlbert** [comment]
Obsolete since perfetto is the recommended approach: https://perfetto.dev/
