### ISSUE TITLE
While RenderScript filename with UpperCase, ndk-build output a LowerCase filename bc file

### ISSUE THREAD

**Issue by adhere** [android/ndk#448]
#### Description

Using ndk-build to build RenderScript, while the RenderScript filename with UpperCase, that have problem. Such as, while the RenderScript filename is Mone.rs, the intermediate bc file will name "mono.bc". So it will be fail. E/bcc (30154): Failed to load bitcode from path ./obj/local/armeabi-v7a/objs/hellocomputendk/Mono.bc! (No such file or directory).
Actually It generates a file "./obj/local/armeabi-v7a/objs/hellocomputendk/mono.bc"

Calling from Java, the RenderScript filename with UpperCase is ok.

#### Environment Details

* NDK Version: 15.1.4119039
* Build sytem: cmake (The android studio bundle)
* Host OS: 14.04
* Compiler: Clang

**Comment by DanAlbert** [comment]
@miaowang14: ping, in case you didn't see this

**Comment by miaowang14** [comment]
I reported the bug to the team, will update here once we have a fix.

**Comment by enh-google** [comment]
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html
