### ISSUE TITLE
expose gtest to cmake

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#500]
Using gtest from ndk-build is trivial. No so for cmake. Fix that.

**Comment by headupinclouds** [comment]
What are the current problems or limitations (compilation, running)?  For what it's worth, I've been using this fork with Android toolchains and devices and it has worked well.

https://github.com/hunter-packages/googletest

Maybe these changes would be useful upstream?  Thanks for all the NDK work, btw.

**Comment by DanAlbert** [comment]
It's not the source that's the problem, it's just a matter of convenience that's missing. For ndk-build you can just `$(call import-module,third_party/googletest)` and then trivially add the library to your module. For CMake you need to add the build rules to your project yourself. Hunter gets you out of dealing with that, but it'd be good to have the CMake's [FindGTest](https://cmake.org/cmake/help/v3.0/module/FindGTest.html) work out of the box with the NDK.

Hunter and cdep are good options for the time being though.

**Comment by dturner** [comment]
I believe the idea is to run the unit tests on the host/build machine. An example **CMakeLists.txt** file showing how **gtest** can be used with NDK projects would be a good starting point.

**Comment by DanAlbert** [comment]
No, the goal is not to build/run tests on the host. CMake can already do that. The goal is to be able to trivially use the gtest that is bundled in the NDK from CMake.

**Comment by alexcohn** [comment]
@DanAlbert, is https://stackoverflow.com/a/46448545/192373 not trivial enough?

Actually, I believe that 
```
set(GOOGLETEST_ROOT ${ANDROID_NDK}/sources/third_party/googletest/googletest)
add_library(gtest STATIC ${GOOGLETEST_ROOT}/src/gtest_main.cc ${GOOGLETEST_ROOT}/src/gtest-all.cc)
target_include_directories(gtest PRIVATE ${GOOGLETEST_ROOT})
target_include_directories(gtest PUBLIC ${GOOGLETEST_ROOT}/include)
```

can safely go into `${ANDROID_NDK}/build/cmake/android.toolchain.cmake`, making **gtest** integration one-liner:
```
target_link_libraries(footest gtest)
```

**Comment by enh** [comment]
yeah, i think that's more like what he has in mind: a one-liner (or something that "just works" by convention if you put your files in the right place) are more suited to general consumption.

**Comment by alexcohn** [comment]
On the other hand, I would be much happier if **gtest** could be seamlessly integrated into Android Studio, to make deployment and control as easy as for the Java instrumented tests, or JUint tests.

**Comment by alexcohn** [comment]
**Update:** above is correct for Android Studio 3.0, with https://services.gradle.org/distributions/gradle-4.1-all.zip and `classpath 'com.android.tools.build:gradle:3.0.0-beta6'`.

In Android Studio 2.3.3, with https://services.gradle.org/distributions/gradle-3.3-all.zip and `classpath 'com.android.tools.build:gradle:2.3.3'`, you need to explicitly specify the unittest target in **build.gradle**:

        android { defaultConfig { externalNativeBuild { cmake { targets "foo_unittest" }}}}

 - with Android Studio 3.0, [gradle-4.1](https://services.gradle.org/distributions/gradle-4.1-all.zip), and `classpath 'com.android.tools.build:gradle:3.0.0-beta6'` the executable is easier to find under `app/build/intermediates/cmake/debug/obj`.

**Comment by epicstar** [comment]
If this was to be revisited, I believe the correct way to get GTest running is to use the FindGTest method:

```cmake
enable_testing()
find_package(GTest REQUIRED)

add_executable(foo foo.cc) # example
target_link_libraries(foo GTest::GTest GTest::Main)

add_test(AllTestsInFoo foo)
```

https://cmake.org/cmake/help/v3.6/module/FindGTest.html

**Comment by epicstar** [comment]
Welp, turns out our historical gtests use gmock, and the NDK doesn't have it directly, so I ended up successfully building googletest via these instructions in CMake: https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project

**Comment by DanAlbert** [comment]
Doing this the nice way doesn't work with how we currently ship GTest. FindGTest requires that GTest is available as a prebuilt, whereas the NDK ships source. Given that we're pretty close to having https://github.com/android/ndk/issues/916 done (for a somewhat forgiving definition of "close"), I don't think it makes much sense for us to be changing how we do this given that we'll have an even better solution fairly soon.

The one thing we will need to do is be careful and make sure that prefab exposes the same interface as FindGTest. From a cursory glance it looks like what we have does generate everything in such a way that it will match, we just need to make sure we get all the library names the same when we go to make the package.

I'll leave this open to keep a record of the fact that we still have work to do here, but it's blocked on the other bug which isn't directly connected to any NDK release so I'm going to move this out of the r21 milestone.

**Comment by DanAlbert** [comment]
https://maven.google.com/web/index.html?q=googlete#com.android.ndk.thirdparty:googletest
