### ISSUE TITLE
Remove or update old tutorials & documentation on official Google sites

### ISSUE THREAD

**Issue by alexcohn** [android/ndk#551]
> [Really wish Google would clean up their documentation and remove old legacy stuff](https://stackoverflow.com/questions/46845152/do-you-have-to-use-gradle-experimental-for-jni/46846463?noredirect=1#comment80643692_46846463). 

E.g. [this tutorial]( https://codelabs.developers.google.com/codelabs/android-studio-jni) on [codelabs](https://codelabs.developers.google.com).

**Comment by qchong** [comment]
The 'Create Hello-CMake with Android Studio' codelab has been updated:
[https://codelabs.developers.google.com/codelabs/android-studio-cmake/index.html](https://codelabs.developers.google.com/codelabs/android-studio-cmake/index.html#0)

Closing this issue.

**Comment by DanAlbert** [comment]
We're probably do for an audit on other docs. I'm going to reopen this to track that, but I'll assign to myself to look through dac for the problem areas.

**Comment by DanAlbert** [comment]
Doc audits are going to be ongoing forever. No use keeping this open.
