### ISSUE TITLE
NDK headers could validate __ANDROID_API__

### ISSUE THREAD

**Issue by alexcohn** [android/ndk#656]
#### To avoid some common mistakes, extra compiler checks may be helpful

For example, [this question](https://stackoverflow.com/q/49311595/192373) has a subtle and quite understandable mistake: they used ` -D__ANDROID_API__=android-21` instead of ` -D__ANDROID_API__=21`. 

The Unified Header logic relies heavily on this define. It could be rather easy to perform a quick check that **__ANDROID_API__** is defined and is one of numbers supported by the current NDK release (e.g., at least 14 for r16; maybe, at least 21 for r16 for 64-bit toolchain).

#### Environment Details

* NDK Version: 16 and up

**Comment by jmgao** [comment]
I don't think it's possible to solve this in general.

In the linked example, the preprocessor is turning `android-21` into `0 - 21`, since android isn't defined. `-D__ANDROID_API__=21-android` or `-Dandroid=42` would "work" just fine. C++14 would let us do fancy constexpr stuff on the stringified macro to ensure that it's actually an integer literal, but it'd reject things like `-D__ANDROID_API__=MY_OWN_MACRO_THAT_EXPANDS_TO_21` (assuming we wanted to permit that).

Maybe a dumb check like the following would be helpful, though?
```code=c
#if !(__ANDROID_API__ > 0)
#pragma message("Invalid __ANDROID_API__ '" __STR(__ANDROID_API__)) "'"
#endif
```

**Comment by alexcohn** [comment]
I was thinking exactly about such simple check. It can be taken one step further, like

```
#if !((__ANDROID_API__) > 14) || !((__ANDROID_API__) <= 28)
#pragma message("Invalid __ANDROID_API__ '" __STR(__ANDROID_API__)) "'"
#endif
```

for NDK r17. Actually, this usage also suggests wrapping all entries of `__ANDROID_API__` in round parenthesis to keep it safer.

**Comment by DanAlbert** [comment]
Better yet, we should stop passing that define manually and just let clang do it. The support is there, we just need to make sure our build systems use it.

For other build system maintainers: use `-target aarch64-linux-android26` (or whatever arch/API combo) and Clang will define `__ANDROID_API__` for you.

**Comment by alexcohn** [comment]
As @jmgao showed above, it may be nice to be able to define `__ANDROID_API__` to some expression that eventually evaluates to a legal integer.

**Comment by DanAlbert** [comment]
I don't remember for sure, but probably r14 or r15?

**Comment by DanAlbert** [comment]
This is mostly fixed since `__ANDROID_API__` hasn't needed explicit definition for a while now, but we haven't added the validation. Simple enough to do, so I'll get that added for r21.

**Comment by DanAlbert** [comment]
Tried it, and the check above doesn't let us produce a useful error message. The condition for the check itself will result in an error (invalid token at start of a preprocessor expression). Unless @jmgao has some other macro trickery he wants to try, I think the fact that everything explodes if you give us a bad API level (and the fact that Clang will enforce that it's an integer already) has us fairly well covered.

**Comment by alexcohn** [comment]
If you force it through clang, can you make sure it's not passed as command line define? And which one takes precedence when there is a collision?

**Comment by DanAlbert** [comment]
If you do define it both on the command line (`-D__ANDROID_API__=22`) and through the target (`-target aarch64-linux-android21` with different values, you'll get `-Wmacro-redefined`. If you ignore the warning then the explicit define argument wins, which is the right precedence.

**Comment by alexcohn** [comment]
> you'll get `-Wmacro-redefined`.

Good enough. I always build with `-Werror`.
