### ISSUE TITLE
[MediaDrm] Multiple key requests fail because of missing buffer clearage

### ISSUE THREAD

**Issue by peak3d** [android/ndk#661]
#### Description

For kodi application we currently use the MediaDrm NDK to play DRM protected media.

1.)
If your DRM logic needs multiple key requests (AMediaDrm_getKeyRequest) (e.g. Service Certification + key request in private mode) or if you have update calls (e.g. youtube),  AMediaDrm_getKeyRequest returns the new requests at the end of the old request (means that you have both requests in the returned request).

2.)
New DRM functionality is missing in the NDK, for me most important onKeyStatusChange Event handler.

3.) 
AMediaDrm_queryKeyStatus deadlocks with android M, and returns wrong information in Android 7.
On Android 7 the value part contains the key part, so I have the same string in key and value. 

I have switched to JNI currently because of those issues and after switching everything is fine.
If the above mentioned things are solved, I'ld like to switch back to NDK.

#### Environment Details
* NDK Version: 16b 
* Build sytem: ndk-build + cmake
* Host OS: Linux x86_64 / Ubuntu 17.04
* Compiler: CLang
* ABI: 23
* STL: ??
* NDK API level: 23
* Device API level: various devices here / tested mainly 23 + 25

**Comment by gkasten** [comment]
Thank you for reporting these issues.  We are now tracking them in our internal bug-tracking system,
and I've made a note to request that we update this GitHub issue also when there is more information.

**Comment by pulkitpurohit** [comment]
Anyone - if available for a contract job for the location of Philadelphia, PA as Android NDK Developer then let me know. feel free to share me your updated resume on pulkit.purohit@cyberthink.com.

**Comment by DanAlbert** [comment]
Based on the internal bugs, looks like 1 is fixed in Q (http://b/77713912), 2 is mostly fixed in Q (http://b/77712870), and 3 was fixed in O-MR1 (http://b/77710855).

Will keep this bug open until the NDK with the new APIs are out (no idea exactly when that will be, but you can probably extrapolate a rough date based on when we've shipped previews in the past few years).

**Comment by DanAlbert** [comment]
We've definitely shipped an NDK or two since 2018.
