### ISSUE TITLE
arm-linux-androideabi-ar.exe takes an extraordinarily long time to finish

### ISSUE THREAD

**Issue by martinbonaciugome** [android/ndk#689]
#### Description

Our project builds various static libs, and then of course the .so. Compiling and linking takes around the time it should compared to XCode, but the whole process is dominated by the archiver, taking over 5 minutes, resulting in android not being a viable developer environment. XCode with our same cross platform apps don't exhibit this behaviour.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 16b and 17-beta2
* Build sytem: cmake
* Host OS: Windows
* Compiler: Clang
* ABI: arm
* STL: c++_static or c++_shared
* NDK API level:
* Device API level:

**Comment by stephenhines** [comment]
@DanAlbert, depending on whether this is specific to GNU ar, we could also look at moving to llvm-ar in the NDK. We already switched to this for the platform.

**Comment by martinbonaciugome** [comment]
hopefully it is specific to GNU ar, as it just looks like an n^2 algorithm somewhere. will the switch be in r18?

**Comment by stephenhines** [comment]
The NDK switching to all LLVM tools is on a different timeline from what we use to build the rest of the Android platform. I was just reminding Dan that we did switch the platform use to llvm-ar in January (http://b/71618641 from our internal bug tracker). It could also be an issue with Windows + archiving Android/Linux binaries in general (which I am hoping it isn't).

**Comment by martinbonaciugome** [comment]
oh ok, thanks for the explanation. I think its not windows specific, as our final build machines are linux, and they do take longer than our iOS builds, but I never drilled down to confirm why.

**Comment by DanAlbert** [comment]
@stephenhines: iirc llvm-ar and GNU ar are not command line compatible? If that's the case then I think the bug may need to be filed with CMake proper, since we don't control the build recipes for static libraries in CMake.

**Comment by DanAlbert** [comment]
> @stephenhines: iirc llvm-ar and GNU ar are not command line compatible? If that's the case then I think the bug may need to be filed with CMake proper, since we don't control the build recipes for static libraries in CMake.

Unless I didn't find all the platform commits (just https://android-review.googlesource.com/c/platform/build/soong/+/551700 and https://android-review.googlesource.com/c/platform/build/soong/+/585802), it's just that `-format=gnu` needs to be passed for Darwin hosts. Presumably that should be fixed in ar to pick the format based on the target rather than the host.

**Comment by DanAlbert** [comment]
We've moved to llvm-ar now. If this is still a problem with llvm-ar, let me know and we'll re-open.
