### ISSUE TITLE
Undefined reference to stdout stderr

### ISSUE THREAD

**Issue by bolds07** [android/ndk#714]
#### Description
 
I'm using ubuntu 16.04 to try to build ffmpeg for android,
I've sucessfully built all dependencies but ffmpeg itself cannot be built

to generate my toolchain I ran:
`$NDK/build/tools/make-standalone-toolchain.sh --use-llvm  --platform=${PLATFORM} --install-dir=${TOOLCHAIN}  --arch=${ARCH} --stl=libc++ `

in my test ARCH=arm and PLATFORM=android-21

I'm using ffmpeg 4.0.0 on the build process
I'm using nkd 17

PS. I was trying to target api 19 but i saw this https://github.com/android-ndk/ndk/issues/315 so i targeted 21 and it reduced the number of "undefined references" but still getting problem to stdout and stderr

**Comment by DanAlbert** [comment]
How are you invoking the compiler?

**Comment by bolds07** [comment]
export PKG_CONFIG="$(which pkg-config)"
export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"
export CC="${CROSS_PREFIX}clang"
export CXX="${CROSS_PREFIX}clang++"
export CPP="${CROSS_PREFIX}cpp"
export AR="${CROSS_PREFIX}ar"
export LD="${CROSS_PREFIX}ld"
export NM="${CROSS_PREFIX}nm"
export RANLIB="${CROSS_PREFIX}ranlib"
export STRIP="${CROSS_PREFIX}strip"
export LDFLAGS="-L${PREFIX}/lib -L${TOOLCHAIN}/lib -L${SYSROOT}/usr/lib -fPIE  --sysroot=${SYSROOT} "
export CFLAGS="${OPTIMIZE_CFLAGS} -I${PREFIX}/include  -I${SYSROOT}/usr/include -fPIE " 
export CXXFLAGS="${CFLAGS} "
export CPPFLAGS="${CFLAGS} "
export PATH="$PATH:$PREFIX/bin:$NDK/build"
export CROSS_SYSROOT="${SYSROOT}"

 
pushd ffmpeg
 
 CROSS_COMPILE_FLAGS="--target-os=linux \
        --arch=$ARCH \
        --cross-prefix=$CROSS_PREFIX \
        --enable-cross-compile \
        --sysroot=$SYSROOT"


   ./configure --prefix=$PREFIX \
        $CROSS_COMPILE_FLAGS \
        --pkg-config=$(which pkg-config) \
        --pkg-config-flags="--static" \
        --enable-pic \
        --enable-gpl \
        --enable-nonfree \
        \
        --disable-shared \
        --disable-static \
        \
        --enable-ffmpeg \
        --disable-ffplay \
        --disable-ffprobe 
   
	
make clean
make  
make install
```

pretty sure it's a ndk mistaske as i've read many similar problems on this github

**Comment by enh** [comment]
`stdin`/`stdout`/`stderr` first appear as actual symbols in M (see `<stdio.h>`):
```
#if __ANDROID_API__ >= __ANDROID_API_M__
extern FILE* stdin __INTRODUCED_IN(23);
extern FILE* stdout __INTRODUCED_IN(23);
extern FILE* stderr __INTRODUCED_IN(23);

/* C99 and earlier plus current C++ standards say these must be macros. */
#define stdin stdin
#define stdout stdout
#define stderr stderr
#else
/* Before M the actual symbols for stdin and friends had different names. */
extern FILE __sF[] __REMOVED_IN(23);

#define stdin (&__sF[0])
#define stdout (&__sF[1])
#define stderr (&__sF[2])
#endif
```
so if you're seeing undefined references to them, it seems highly unlikely you're actually targeting 19 or 21. you can test this theory by checking `__ANDROID_API__` yourself.

**Comment by bolds07** [comment]
where is ``` __ANDROID_API__``` defined?

the only mention i found was 

```

#ifndef __ANDROID_API__
#define __ANDROID_API__ __ANDROID_API_FUTURE__
#else
#define __ANDROID_NDK__ 1
#endif
```

**Comment by DanAlbert** [comment]
> where is `__ANDROID_API__` defined?

Implicitly by `-target`. i.e. `-target aarch64-linux-android24` sets it to 24. The `clang` in the standalone toolchain bin directory is actually a script that does this for you:

```bash
$ cat arm64-android-24-toolchain/bin/clang
#!/bin/bash
if [ "$1" != "-cc1" ]; then
    `dirname $0`/clang70 -target aarch64-none-linux-android24 --sysroot `dirname $0`/../sysroot "$@"
else
    # target/triple already spelled out.
    `dirname $0`/clang70 "$@"
fi
```

FYI, passing `--sysroot` shouldn't be necessary with a standalone toolchain. I don't think it would be causing this issue though.

Any chance there are other libraries in this build that were built against android-23 or newer? I'm guessing not because iirc ffmpeg doesn't have any external dependencies, but that could explain it.

**Comment by bolds07** [comment]
> Any chance there are other libraries in this build that were built against android-23 or newer? I'm guessing not because iirc ffmpeg doesn't have any external dependencies, but that could explain it.

No, i'm using a huge script which download and build every dependency each time it runs, the only thing it keeps is the ndk... but even the toolchain is deleted and created each run.

This way i'm sure all dependencies were built on same scenario...

I tested and if I define manually the target api in that header i mentioned it works

**Comment by DanAlbert** [comment]
Your build script doesn't work. There's a bunch of undefined variables in it. If I guess at how those are supposed to be set, it complains that either `--enable-static` or `--enable-shared` must be used, and if I fix it with `--enable-shared` it then complains that it's not being properly configured for cross-compiling.

I strongly suspect that this is a bug in the ffmpeg build scripts rather than an NDK issue, so unless there's a simple repro case this isn't going to get looked at until that assumption is proven wrong.

**Comment by danoli3** [comment]
No known solutions for Android.mk:

Solution:
Added -L/Path/ to LDFLAGS in Android.mk to force the minimum Android API Path to a sub library directory
${SYSROOT}/usr/lib/${ABI}/${ANDROID_NATIVE_API_LEVEL}

`LOCAL_LDLIBS    += -L$(SYSROOT)/$(LIBRARY_ARCHITECTURE)/$(TARGET_API) `

**Comment by DanAlbert** [comment]
Overriding the internals of the build system is not usually a good plan. File a bug with repro steps and we can help. All our tests show that this works fine, so there's something unique to your configuration causing it and we can't guess at what it would be.
