### ISSUE TITLE
Static or shared C++ runtime for 3rd-party Java library

### ISSUE THREAD

**Issue by afjoseph** [android/ndk#796]
Description

I'm compiling a 3rd-party Java library for Android that uses JNI. I read [the relevant pages on adding C++ support on developer.android](https://developer.android.com/ndk/guides/cpp-support#static_runtimes) but I'm still confused about a couple of issues regarding C++ STL runtime that I was hoping I could clear up here:

1-  My library has no control over the app it will be embedded in, so I don't know if there will be other libraries that might use a static/shared STLs. If I use a _static_ C++ runtime with `ANDROID_STL=c++_static`, is it safe, or should I have to worry about another library that could be using something like `gnustl_static` which might conflict with mine?

2- If I use a _shared_ C++ runtime with `ANDROID_STL=c++_shared`, is it a guarantee that a specific element in the STL will use the libc++ runtime or could it be possible to use gnustl if it doesn't exist? For example, If I was using `std::string` with a shared c++ runtime (`c++_shared`) in an app that has another library of `gnustl_static`, will my `std::string` implementation be taken from libc++ or gnustl?

Ideally, I'd like to have a very stripped down version of a static c++ runtime with (`c++_static`) that only includes `std::vector, std::string and std::map`. I was actually planning to use something [like `-ffunction-sections` as described here](https://github.com/android-ndk/ndk/issues/748) and https://github.com/android-ndk/ndk/issues/768.

Please advise and thank you.

Environment Details
Pkg.Desc = Android NDK
Pkg.Revision = r15c
Android Studio = 3.1.2
system: cmake
Host OS: Arch Linux (`$ uname -r % 4.18.5-arch1-1-ARCH`)
Compiler: Clang++
STL: c++_static/c++_shared
API: 27

**Comment by Obaied** [comment]
Thanks @DanAlbert. That cleared up everything.
If I can make a small comment, I really like phrasing of this [old document](https://android.googlesource.com/platform/ndk/+/ics-mr0/docs/CPLUSPLUS-SUPPORT.html) regarding static/shared runtimes as opposed to the [current document](https://developer.android.com/ndk/guides/cpp-support#static_runtimes) since it provided a clearer example. 

This could just be me since I was misinformed about the situation, so please take my criticism with a heavy grain of salt and thanks again.

**Comment by DanAlbert** [comment]
That does have some good pieces worth cherry picking I think. Will reopen this to track.

**Comment by alexcohn** [comment]
@Obaied, you cite the old document that says,

> In other words, if your project requires several shared library modules, then use the shared library variant of your C++ runtime.

This is not exactly true. Let me explain.

1. It is true that if you control all the shared library modules of your app, the best and easiest choice is to choose a common shared variant of C++ runtime. Furthermore, at the time of this writing, this choice will ultimately be **libc++**.
2. If your app uses some 3rd party libraries that require some specific variant of C++ shared runtime, the easiest choice is to use the same runtime for all libraries that you can rebuild.
3. If your app uses some 3rd party static library that requires static C++ runtime, you can link it with shared C++ runtime. It will simply work, except very special situations. So, we are back in §2.
4. If your app uses some 3rd party shared library that uses some static C++ runtime, try not communicate with this library from your native code. Hopefully it comes with its own Java wrapper classes. If you let them separate from the rest of your native code, you are essentially back to §1.
5. If your app uses some 3rd party shared library that requires some static C++ runtime, and you *must* communicate with it from native code, you should not share C++ objects (including streams and exceptions) with it. Working with it through a C API will probably be OK.
6. If your app uses some 3rd party shared library that requires some static C++ runtime, and another 3rd party library requires some other C++ runtime, this will hopefully be OK if they know nothing about each other, and only communicate with their Java classes.
7. If your app uses 3rd party shared libraries that use different shared C++ runtime, you are in a big trouble.

**Comment by Obaied** [comment]
Thanks @alexcohn for the super detailed and answer in both here and [SO](https://stackoverflow.com/questions/52387886/android-ndk-static-or-shared-c-runtime-for-3rd-party-java-library/52389560#52389560). This was a tremendous help.

@DanAlbert, If I can make a humble suggestion, I think this post was much more illuminating that the current docs, so I highly encourage you guys cherrypick some of the answers provided by you and Mr. Cohn.

Thanks again to both of you. This was very helpful.

**Comment by alexcohn** [comment]
I believe that these nuances should not be promoted to the top docs. They may be too confusing for a novice, and not complete for an expert. The level of required detail depends actually on the specific situation.

**Comment by DanAlbert** [comment]
I'm not sure when I did it, but it looks like I fixed this a while back: https://developer.android.com/ndk/guides/cpp-support#static_runtimes

There's also the more targeted https://developer.android.com/ndk/guides/middleware-vendors which covers the specific question in the OP: what to do when your native libraries are merely an implementation detail of your AAR.

**Comment by foobra** [comment]
I have a question, if different vendor third-party libraries  use their own c++_static link , but their compiled ndk versions are different, Will the final apk be  be incompatible? 

Another question is, if different vendor third-party libraries use their own c++_shared, but their ndk versions are different, and they are finally integrated into the apk, which ndk version of libc++_shared.so should be kept?

**Comment by DanAlbert** [comment]
What he said :)
