### ISSUE TITLE
cannot locate symbol "_ZNSt12length_errorD1Ev"

### ISSUE THREAD

**Issue by perracolabs** [android/ndk#833]
Environment Details

* NDK Version:  18.1.5063045
* Build system: cmake
* Host OS: Windows
* Compiler: Clang
* ABI: armeabi-v7a
* STL: c++_static
* NDK API level: android-22
* Device API level: 22

I’m getting the next runtime crash, only in Android 5.1. No problems in other Android versions:

**E/art: dlopen("/data/app/com.perracolabs.stitch-2/lib/arm/libstitcher.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_ZNSt12length_errorD1Ev" referenced by "libstitcher.so"...**
      
I don't know what the symbol **_ZNSt12length_errorD1Ev** is, or what does refers to. 

The library does not link any third-party library neither uses any special compile flags, and even tried just with -O0 and nothing more. No errors or warnings in the compilation, and as mentioned it works fine in other android versions.

**Comment by DanAlbert** [comment]
```bash
$ echo '_ZNSt12length_errorD1Ev' | c++filt 
std::length_error::~length_error()
````

(that won't be in your path since you're on Windows, but the NDK does include c++filt alongside the rest of binutils, or you can use demangler.com)

> I’m getting the next runtime crash, only in Android 5.1.

Probably need to use [ReLinker](https://github.com/KeepSafe/ReLinker).

**Comment by perracolabs** [comment]
Update: changed STL from **c++_static** to **c++_shared** solves the runtime crash.

Is there any special considerations to take into account when using **c++_static**?

**Comment by DanAlbert** [comment]
Yes, many: https://developer.android.com/ndk/guides/cpp-support#static_runtimes

**Comment by perracolabs** [comment]
Yes, I've tried relinker, but didn't solve the problem. I end up using  c++_shared instead of c++_static.
