### ISSUE TITLE
RenderScript will fail to build cause  path is directly concatenated with NDK_OUT argument

### ISSUE THREAD

**Issue by qtiuto** [android/ndk#856]
--------------------------------------------------------------------------------

#### Description
I failed to build a project with renderscript files as source file on windows.
From the error message, I found something interesting
error: error opening 'E:/AppProjects/HoloGraphy/app/E:/AppProjects/HoloGraphy/app/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/rsCompute/rs/\copydata.bc': Invalid argument
  
 
From the path above, you can see that the NDK_OUT path is concatenated directly with the current path directly. I can specific a relative NDK_OUT arguement manually  to overwrite the existed one. But I think it should be fixed.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 18.1.5063045
  the latest version, check there before filing.
* Build system: ndk-build or gradle
* Host OS: Windows
* Compiler:  Clang 
* ABI:any
* STL:any
* NDK API level:any
* Device API level:any

**Comment by qtiuto** [comment]
This is a bug due to abspath. It doesn't work well on windows
The error is for build-definition.mk:1468
cd $$(call host-path,$$(dir $$(PRIVATE_RS_SRC))) && $$(PRIVATE_RS_CC) -o $$(call host-path,$$(abspath $$(dir $$(PRIVATE_OBJ))))/ -d $$(abspath $$(call host-path,$$(dir $$(PRIVATE_OBJ)))) -MD -reflect-c++ -target-api $(strip $(subst android-,,$(APP_PLATFORM))) $$(PRIVATE_RS_FLAGS) $$(notdir $$(PRIVATE_RS_SRC))
I wonder if you can remove abspath or use python  or define a macro to do it.

**Comment by DanAlbert** [comment]
Tentatively want to look at this for beta 2 since it looks simple to fix, but I'm running out of time on that so it may get punted to r20.

**Comment by DanAlbert** [comment]
Actually, going to need a test case here. We have tests that show that the trivial cases at least work, even on Windows, so I don't know what's specific to your environment or invocation that's causing the problem.

https://android.googlesource.com/platform/ndk/+/master/tests/build/rs-hello-compute is one of our test cases. This works fine on Windows when invoking ndk-build from that directory.

**Comment by qtiuto** [comment]
> Actually, going to need a test case here. We have tests that show that the trivial cases at least work, even on Windows, so I don't know what's specific to your environment or invocation that's causing the problem.
> 
> https://android.googlesource.com/platform/ndk/+/master/tests/build/rs-hello-compute is one of our test cases. This works fine on Windows when invoking ndk-build from that directory.
use the following comand: `ndk-build NDK_OUT=E:\test` and you will hava a surprise

**Comment by DanAlbert** [comment]
Another report, with a test case: https://stackoverflow.com/q/58654502/632035

**Comment by enh-google** [comment]
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html
