### ISSUE TITLE
default to NEON for all API levels

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#859]
It seems there are an insignificant number of devices without NEON support even prior to API 23, so we should just default this to on for all ARM32.

- [x] Patch Clang to default to NEON.
- [x] Pull patches to Android.
- [x] Update NDK's Clang to the new Android Clang.
- [x] Fix https://developer.android.com/ndk/guides/cpu-arm-neon#runtime_detection

**Comment by tangobravo** [comment]
It'd certainly be good to have official blessing for a NEON-enabled armeabi-v7a build.

AFAIK it was just the Tegra 2 SoCs that were armeabi-v7a but without NEON, which were used by some of the very first batch of Android tablets (around Android 4 timeframe). @DanAlbert - can you share any data to quantify your "insignificant number of devices" assertion? It would be nice to blacklist those few devices on Play Store, but would need a full list for that.

Out of interest, is NEON guaranteed for armeabi-v7a on API level 23 and up? I can't find a reference for that anywhere.

One other slight consideration - there may be issues with some of the old x86 devices that transpile from armeabi-v7a - I hit some transpiler bugs with NEON code at some point. I suppose it's possible to build an x86 library for them that should work better anyway.

**Comment by enh** [comment]
yes, NEON is required for Android 6.0 Marshmallow (API level 23): https://source.android.com/compatibility/6.0/android-6.0-cdd

**Comment by DanAlbert** [comment]
@tangobravo: Fortunately you don't need a list of devices. Just blacklist Tegra 2. The Play console will show you a list of devices that are excluded by that rule. iirc for JB+ it was only two or three devices, and all of them had a very small number of active users (don't remember actual numbers, but it was low enough for us to decide it wasn't worth dragging down the perf of other devices).

**Comment by DanAlbert** [comment]
Reminder to myself to update https://developer.android.com/ndk/guides/cpu-arm-neon#runtime_detection when this reaches the NDK.

**Comment by DanAlbert** [comment]
I've submitted the change to upstream Clang, but we're far too close to r20 beta 1 for that to reach the NDK in time, so moving to r21.

**Comment by DanAlbert** [comment]
This is all done aside from updating dac. I've sent the patch to fix it, but probably shouldn't submit until r21 is at least in beta.

**Comment by DanAlbert** [comment]
https://developer.android.com/ndk/guides/cpu-arm-neon
