### ISSUE TITLE
FieldPacker in rsCppStructs.h will failed to add any value derived from BaseObj due to wrong method definition

### ISSUE THREAD

**Issue by qtiuto** [android/ndk#860]
#### Description

The [rsCppStructs.h](https://android.googlesource.com/platform/frameworks/rs/+/android-9.0.0_r18/cpp/rsCppStructs.h) exists in ndkpath/toolchains/renderscript/prebuilt/{my platform}/rs/cpp/
and in the Android source code the path is frameworks/rs/cpp.
None of them is fixed until now. Maybe no user uses this feature.
FieldPacker is defined in [line 1454](https://android.googlesource.com/platform/frameworks/rs/+/android-9.0.0_r18/cpp/rsCppStructs.h#1454).
Here is the original method definition
in [line 1510](https://android.googlesource.com/platform/frameworks/rs/+/android-9.0.0_r18/cpp/rsCppStructs.h#1510)：
```c++
template <typename T>
        void add(T t) {
        align(sizeof(t));
        if (mPos + sizeof(t) <= mLen) {
            memcpy(&mData[mPos], &t, sizeof(t));
            mPos += sizeof(t);
        }
    }
```
and in [line 1539](https://android.googlesource.com/platform/frameworks/rs/+/android-9.0.0_r18/cpp/rsCppStructs.h#1510):
```c++
    void add(const sp<BaseObj>& obj) {
        if (obj != NULL) {
            add((uint32_t) (uintptr_t) obj->getID());
        } else {
            add((uint32_t) 0);
        }
    }
```
I think the author intends to add any obj derived from BaseObj through the second method, However,
Only the the type BaseObj will fit into the second mehod, the others will only fit into the  first method.
Nevertheless the llvm-rs-cc will never cast value to BaseObj when generating code.

To solve it, not only should I fix the header but I must also rebuild RScpp_static.so. The privided one 
even doesn't use inline for any simple method. Is the author a kid?
The header can be fixed like this
```c++
//maybe std::is_trivial is also ok
 template <typename T>
    inline  typename std::enable_if<std::is_integral<T>::value||std::is_floating_point<T>::value>::type
    add(T t) {
        align(sizeof(t));
        if (mPos +  sizeof(t)<= mLen) {
            memcpy(&mData[mPos], &t, sizeof(t));
            mPos +=  sizeof(t);
        }
    }
template <typename T >
    inline __always_inline typename std::enable_if<std::is_base_of<BaseObj,T>::value>::type
    add(const sp<T>& obj) {
        if (obj != NULL) {
            add<uint >((uint32_t) (uintptr_t) obj->getID());
        } else {
            add<uint >((uint32_t) 0);
        }
    }
```
#### Environment Details

* NDK Version: 18.1.5063045
* Build system: any
* Host OS: Windows
* Compiler: Clang 
* ABI:any
* STL:any
* NDK API level:19
* Device API level:28

**Comment by qtiuto** [comment]
Still I wanna say, why is new everywhere in the library? Why can't I directly use object in the stack and must use new to define one. The  **sp**  is not a good design. Redesigning it with c++11 will make it more elegant. 
Moreover, can you define an kernel id enum in the generated header instead of an integer literal ? It would be helpful for custom extension.

**Comment by enh-google** [comment]
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html
