### ISSUE TITLE
The CMake toolchain is missing CMAKE_ANDROID_ARCH

### ISSUE THREAD

**Issue by arcanis** [android/ndk#861]
#### Description

The CMake toolchain doesn't define the `CMAKE_ANDROID_ARCH` variable, which seems to be instead named `ANDROID_SYSROOT_ABI`. This causes issues when compiling Boost.Context using the Hunter package manager, since it only check for the former property rather than the later.

Also see: https://github.com/ruslo/hunter/issues/1634

(More generally, I'd be interested to hear your opinion regarding which of the two toolchains is the "official" one and should be supported - the NDK one or the one directly embed into CMake?)

#### Environment Details

* NDK Version: r18
* Build system: CMake

**Comment by kervala** [comment]
I suspect it's the one in the NDK since it's more often updated, but yes it could be cool to remove the other one :)

**Comment by DanAlbert** [comment]
Sorry, missed this one and am just spotting it now as I sweep through all of our backlog...

https://android-review.googlesource.com/c/platform/ndk/+/1125984

> (More generally, I'd be interested to hear your opinion regarding which of the two toolchains is the "official" one and should be supported - the NDK one or the one directly embed into CMake?)

Unifying these has been on the todo list for a very long time (https://github.com/android/ndk/issues/463), we've just unfortunately had bigger problems in the way. At this point it's finally the next big thing on the todo list, so probably some time next year.

For the time being, which one you should prefer depends a lot on your usage. As this bug shows, the interfaces aren't identical and this causes problems for some systems (especially Hunter, it seems). As long as you *don't* run in to any of those issues though, you're generally better off with the NDK's toolchain file despite its... non-ideal implementation (we're really stretching the limits of what a toolchain file can/should do). It's the one that we can actually fix to accommodate NDK changes. Essentially, the toolchain file is going to have the best behavior for Android, but the upstream interface is going to be more likely to work with non-Android CMake workflows.
