### ISSUE TITLE
'make' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by hongtou820** [android/ndk#872]
Build command failed.
Error while executing process ...\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build ...\wireguard-android2\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target libwg.so}
[1/20] Building wireguard-go
FAILED: cmd.exe /C "cd /D ...\wireguard-android2\app\tools\libwg-go && make ANDROID_ARCH_NAME=arm ANDROID_C_COMPILER=...Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe ANDROID_TOOLCHAIN_ROOT=...Local/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 ANDROID_LLVM_TRIPLE=armv7-none-linux-androideabi21 ANDROID_SYSROOT=...Local/Android/Sdk/ndk-bundle/sysroot ANDROID_PACKAGE_NAME=com.wireguard.android.debug "CFLAGS=-isystem ...Local/Android/Sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -Wno-unused-command-line-argument" "LDFLAGS=-Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot ...Local/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L...Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now  -fuse-ld=gold" DESTDIR=...\wireguard-android2\app\build\intermediates\cmake\debug\obj\armeabi-v7a BUILDDIR=...\wireguard-android2\app\build\intermediates\cmake\debug\obj\armeabi-v7a/../generated-src"
'make' is not recognized as an internal or external command,
operable program or batch file.
ninja: build stopped: subcommand failed.

**Comment by DanAlbert** [comment]
Sorry, never saw this one somehow.

Not totally sure how you were building. It looks like you're using ninja but your CMake project shells out to make? Make is not installed on your system, so the build failed. You can add `%NDK%\prebuilt\windows-x86_64\bin` to your `PATH`. On the other hand, calling make from within CMake is fairly suspicious, so maybe that should just be fixed instead?

Either way, this isn't an NDK bug.
