### ISSUE TITLE
[DOC] -static-libstdc++ to get static libc++ in NDK documentation

### ISSUE THREAD

**Issue by yagnasrinath** [android/ndk#891]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
URL to the incorrect documentation (if the problem is that there is no documentation and it belongs on a new page, say so).
https://developer.android.com/ndk/guides/standalone_toolchain

**Problem**
What's wrong? Does something need clarification/expansion? Is there a typo?
`Use -static-libstdc++ to get the static library version of libc++. Doing so ensures that all required C++ STL code is included into your final binary. This method is ideal if you are only generating a single shared library or executable, which is our recommendation.`

Is the documentation right? It says that -static-libstdc++ will provide static version of libc++ instead of libstdc++ ? Please clarify.

**Comment by DanAlbert** [comment]
Yes, that's correct.

**Comment by DanAlbert** [comment]
We'll call it out explicitly in the docs that the argument name is dumb.

**Comment by yagnasrinath** [comment]
Thanks for clarifying it.

**Comment by DanAlbert** [comment]
Current form of the docs looks right to me. While reviewing I spotted that the language on the C++ Support page is less clear though, so I just sent a patch to fix that.
