### ISSUE TITLE
gdb-stub: fails to AssignProcessToObject

### ISSUE THREAD

**Issue by screwer** [android/ndk#923]
Reproduce: run gdb stub on any Windows with "Program Compatibility Assistant" service is running. In my case this is Windows 2019 server, configured only through ServiceManager, i.e. w/o any manual 
intervention.

Observed behavior: print to stderr "Could not AssignProcessToObject"

Cause: AssignProcessToObject function fails with ACCESS_DENIED error. According to MSDN, this may take place if Program Compatibility Assistant (PCA) is monitored created process.

Fix: Thus, process must be created with flag CREATE_BREAKAWAY_FROM_JOB. In my tests adding this flag to CreateProcess completely solves the issue.

**Comment by enh** [comment]
> run gdb stub

what exactly do you mean? you're running `ndk-gdb.cmd`?

**Comment by screwer** [comment]
> what exactly do you mean?

for example
https://android.googlesource.com/platform/ndk.git/+/refs/tags/ndk-r19b/sources/host-tools/gdb-stub/

>  you're running ndk-gdb.cmd?

This is no matter, because all scripts (cmd, python) runs gdb w/o '-orig' suffix. I.e. all of them runs WRAPPER executable, instead of real gdb. So all of them have this bug in executable run-flow.

**Comment by DanAlbert** [comment]
We might need some more info. From what I can tell, PCA is enabled by default, and we haven't encountered this issue (need to follow up to check that it _is_ actually enabled by default though).

@hhb assuming offering lldb as a backend for `ndk-gdb` isn't going to be an option in r22, is this something you'd want to look at?

**Comment by hhb** [comment]
I can not reproduce this on my Windows 10 but the suggested fix sounds reasonable. I'll send a change.

At the bottom of MSDN [AssignProcessToJobObject](https://docs.microsoft.com/en-us/windows/win32/api/jobapi2/nf-jobapi2-assignprocesstojobobject):
> If the process is being monitored by the Program Compatibility Assistant (PCA), it is placed into a compatibility job. Therefore, the process must be created using CREATE_BREAKAWAY_FROM_JOB before it can be placed in another job. Alternatively, you can embed an application manifest that specifies a User Account Control (UAC) level in your application and PCA will not add the process to the compatibility job.
