### ISSUE TITLE
[FR] support packing IMPORTED SHARED library with CMake

### ISSUE THREAD

**Issue by alexcohn** [android/ndk#928]
This Feature Request should be part of the *[NDK integration for CMake](https://github.com/android-ndk/ndk/issues/463)*, and is based on a common scenario, see *[How can I integrate OpenCV 4.0 into a pure C++ Android NDK project?](https://stackoverflow.com/a/54980053/192373)*.

When we use an IMPORTED SHARED library in **CMake** build, it is not packed into the APK. This behaviour is not consistent with what happens when we use **ndk-build** instead of **CMake**. 

An official sample suggest a [way to do this in Gradle](https://github.com/googlesamples/android-ndk/blob/master/hello-libs/app/build.gradle):

    sourceSets {
        main {
            // let gradle pack the shared library into apk
            jniLibs.srcDirs = ['../distribution/gperf/lib']
        }
    }

The latter solution is less attractive to me because it involves sharing some knowledge (e.g. paths to native dependencies) between CMake and Gradle. It's preferable IMO to [handle this entirely in CMake](https://stackoverflow.com/a/39205396/192373) and copy the file to `CMAKE_LIBRARY_OUTPUT_DIRECTORY`:

```
get_target_property(__src opencv_java IMPORTED_LOCATION_RELEASE )
add_custom_command(TARGET app POST_BUILD COMMAND
    ${CMAKE_COMMAND} -E copy ${__src} ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
)
``` 

At the very least, this issue should be properly documented. 

It would help a lot to add some helper macro to the CMake toolchain file, which would take care of  declaring an imported shared library and packing it into the APK, so that CMake is on par with ndk-build.

I believe it's possible to teach the Gradle plugin pack such libraries without changing the user-side scripts, but maybe today this would cause more confusion, because this would be a braking change for the behaviour that has been there for quite a while.

**Comment by DanAlbert** [comment]
I'm pretty sure I fixed this as part of #916. AGP 4.0 shouldn't have this problem. It's definitely fixed for the case of a library imported via a config package. I'll wait to make sure your project agrees before fixing the docs :)
