### ISSUE TITLE
[DOC] Document cmake {version: ... }

### ISSUE THREAD

**Issue by H-G-Hristov** [android/ndk#941]
Document the CMake "version" option here: https://developer.android.com/ndk/guides/cmake

externalNativeBuild {
        cmake {
            // Tells Gradle to put outputs from external native
            // builds in the path specified below.
            buildStagingDirectory = "${rootProject.ext.nativeStagingDirectory}/${project.name}"

            // Tells Gradle to find the root CMake build script in the same
            // directory as the module's build.gradle file. Gradle requires this
            // build script to add your CMake project as a build dependency and
            // pull your native sources into your Android project.
            path "${rootProject.ext.appProjectDirectory}/CMakeLists.txt"
            version "3.12.0"
        }

I know that it is already described in the Android Studio docs. I think that it really needs to be described in the NDK docs or at least to provide a link to the Android Studio page.

The main reason is that this page is easier to find in Google search.

**Comment by DanAlbert** [comment]
That doc *does* link to the Studio docs that cover this... but maybe we should turn that paragraph into a call out so it's more obvious.

**Comment by DanAlbert** [comment]
Seems I did that at some point.
