### ISSUE TITLE
[BUG] CMake+YASM uses "-f elf" for x86 while ndk-build uses "-f elf32"

### ISSUE THREAD

**Issue by aadithyabk** [android/ndk#946]
I am working on migrating our project from ndk-build to cmake. While I was migrating a module with a lot of .asm files, I ran into issues trying to build for x86. A lot of our .asm files rely on output format being elf32 to build correctly for x86. However that is not the case when using cmake. It ends up using "-f elf" but works correctly for x86_64 with "-f elf64" 

Here's the output from CMake while building
`/opt/android_ndk/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/yasm -DELF  -f elf -o CMakeFiles/native-lib.dir/print_hello_x86.asm.o /CmakeYasm/app/src/main/cpp/print_hello_x86.asm`

[Here](https://github.com/aadithyabk/CmakeYasm) is a sample project that I created to showcase this. It is a sample C++ project created from Android Studio with only additional code being a test .asm file that I added. 

I tried adding `set_source_files_properties(print_hello_x86.asm PROPERTIES COMPILE_FLAGS "-f elf32")` but this ends up adding the flag before "-f elf" which makes it useless because it gets overridden anyway. 

Here's the output with the above change
`/opt/android_ndk/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/yasm -DELF  -f elf32 -f elf -o CMakeFiles/native-lib.dir/print_hello_x86.asm.o /CmakeYasm/app/src/main/cpp/print_hello_x86.asm`

#### Environment Details

* NDK Version: r19c
* Build system: CMake+YASM with the default toolchain
* Host OS: Mac
* ABI: x86

**Comment by DanAlbert** [comment]
That flag is configured by CMake, not the NDK: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CMakeASM_NASMInformation.cmake#L26. I think that's a bug? Based on the yasm manual it doesn't seem like a raw `elf` is even a supported argument.

If that's the case, I think this probably should be filed against CMake rather than the NDK.

> I am working on migrating our project from ndk-build to cmake.

Just in case this was your reasoning, ndk-build isn't deprecated. No need to switch to CMake if you don't want to. If you *do* want to, then ignore this :)

**Comment by aadithyabk** [comment]
Ah! ok. I am not sure if I'll have any luck trying to get them to look into it. Would you happen to know if there's anything special I need to do to make CMake append `set_source_files_properties(..)` after the existing flags instead of before them. THat way, I could just override it with "-f elf32".

>  Just in case this was your reasoning, ndk-build isn't deprecated.

Wasn't there an announcement at I/O 18 about ndk-build being deprecated in the near future? I didn't hear this first hand but it actually was the motivation for the project.

**Comment by enh** [comment]
> Wasn't there an announcement at I/O 18 about ndk-build being deprecated in the near future? 

if there was, no-one told the folks who maintain ndk-build :-)

**Comment by DanAlbert** [comment]
You might be remembering `ndkCompile`, which was a pre-`externalNativeBuild` Gradle syntax for the NDK. That's gone now.

ndk-build isn't going anywhere any time soon. It's extremely prevalent and has some strong advantages over CMake for Android only projects (and it's also what most of our tests are written in). If you're currently using that and happy with it, keep using it.

**Comment by enh** [comment]
(i've added a slide [slide 15] to our I/O 2019 talk saying that ndk-build and CMake are equally supported, since this really does seem to be a major source of confusion...)

**Comment by DanAlbert** [comment]
What is the behavior you see for this? Does it outright fail, or is there some behavioral difference between elf and elf32. Asking because if the latter than CMake might be correct and we do actually need to make a change in our toolchain file.

> Ah! ok. I am not sure if I'll have any luck trying to get them to look into it. Would you happen to know if there's anything special I need to do to make CMake append set_source_files_properties(..) after the existing flags instead of before them. THat way, I could just override it with "-f elf32".

I don't, no.

**Comment by aadithyabk** [comment]
It outright fails to build in our case because we have code checking the output format in .asm files. Something like `%ifidn __OUTPUT_FORMAT__,elf32` and similarly for elf64. When building through cmake, all of the checks fail because it is elf and not elf32. 

We could modify our code to account for this change but when I was creating the issue, I was under the impression it is being set by the NDK and not cmake itself. 

I did find a [stackoverflow](https://stackoverflow.com/questions/49131996/compile-asm-and-c-with-asm-for-debugging) post which has fixed my issue for now but the solution is a little fishy because `CMAKE_ASM_NASM_COMPILE_OBJECT` is not documented and I am guessing CMake devs didn't want to expose it. 

It'd be nice if things are consistent with ndk-build but I am not sure if there's anything you folks can do about it. 

Also, upon further discussions internally, we have decided we want to migrate to CMake anyway which unlocks few other things for us.

**Comment by DanAlbert** [comment]
The part I'm not clear on is if there's a difference between elf32 and elf other than just the spelling. i.e. is CMake's behavior wrong, different in a meaningless way, or different in a meaningful way? Will try to find an answer...

**Comment by Orphis** [comment]
It is documented [here](https://cmake.org/cmake/help/git-master/variable/CMAKE_LANG_COMPILE_OBJECT.html). It should be fine to override it with anything you prefer.

**Comment by aadithyabk** [comment]
@DanAlbert Curious to know if you found an answer for difference between elf and elf32.

Also, seems like there is nothing you folks can do about this? Shall I close this issue?

If I have some questions regarding differences that I see between ndk-build and cmake, that are not necessarily bugs, would this still be the right forum to ask?

**Comment by DanAlbert** [comment]
I haven't had time to look any deeper yet. I'll keep the bug open until I confirm, but you might be right.

It's certainly a fine place to start with questions. We might end up telling you it's the wrong place and to go ask CMake, but it might also be the right place. If you're not sure, feel free to start with us. We usually want to be aware of any mismatches even if we can't fix them anyway.

**Comment by DanAlbert** [comment]
(forgot to close this, but yeah, I think nothing to do on the NDK side)
