### ISSUE TITLE
[r19c] error: no matching constructor for initialization of 'std::shared_ptr<uint8_t []>'

### ISSUE THREAD

**Issue by SravanaLakshmiSunkara** [android/ndk#950]
**Description**
 I am trying to use std::shared_ptr <uint8_t []> in my NDK application, but compiler throws below error.

> error: no matching constructor for initialization of 'std::shared_ptr<uint8_t []>'
> 
> std::shared_ptr<uint8_t[]> x_data(new uint8_t[bytes_to_send]);

The CMake looks like below

```
cmake {
        version "3.10.2"
        cppFlags "-std=c++17 -stdlib=libc++ -frtti -fexceptions"
        .....
}

```
**Environment Details**
NDK Version: r19c (19.2.5345600)
Build sytem: any
Compiler: clang++
ABI: any
STL: libc++
NDK API level: 21
Device API level: n/a

**Comment by alexcohn** [comment]
https://wandbox.org/ shows that this compiles for gcc 7.1.0 and higher, but fails on any clang

**Comment by DanAlbert** [comment]
Seems this is a C++17 feature, and not one that libc++ supports yet.

**Comment by rprichard** [comment]
> Seems this is a C++17 feature, and not one that libc++ supports yet.

Yeah, that seems to be the case. This StackOverflow link looks relevant: https://stackoverflow.com/questions/13061979/shared-ptr-to-an-array-should-it-be-used

**Comment by andrei-datcu** [comment]
@DanAlbert libc++ added support in https://reviews.llvm.org/rGce195fb22b542c20745e3ed46d1516e8b4e3a76f (v11)
However, ndk master build still misses the patch. Any idea when are we going to see this picked up? Thanks!

**Comment by DanAlbert** [comment]
No timeline. Upstream redid how testing works so we have to redo all our infrastructure again. It's the next thing on my list but I have no idea how long it will take.

**Comment by glebm** [comment]
Still an issue in 2023, NDK version 25.2.9519653.

**Comment by glebm** [comment]
For anyone landing here from Google, looks like libc++ is finally updated in r26 per https://github.com/android/ndk/issues/1530
