### ISSUE TITLE
[BUG] llvm-rs-cc asserts out when compiling renderscript file..

### ISSUE THREAD

**Issue by Ardy123** [android/ndk#952]
#### Description
When building a renderscript file with the ndk framework, llvm-rs-cc asserts and fails..

Assert:
"slangAssert failed at frameworks/compile/slang/slang_rs_reflection_cpp.cpp:329 - 'ef->getIns().size() == 1'"

renderscript code..
`#pragma version(1)
#pragma rs java_package_name(com.sixdegreesai.renderscriptndk)

int __attribute__((kernel)) add_vec(int lhs, int rhs) {
    return lhs + rhs;
}`

The issue can be reproduce by running llvm-rs-cc from the commandline...

./llvm-rs-cc -O 3 -I Library/Android/sdk/build-tools/28.0.3/renderscript/include/ -I Library/Android/sdk/build-tools/28.0.3/renderscript/clang-include/ -rs-package-name=android.support.v8.renderscript -p code/RenderscriptNDK/app/build/generated/renderscript_source_output_dir/debug/compileDebugRenderscript/out -reflect-c++ -o code/RenderscriptNDK/app/build`/addvec.rs

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 19.2.5345600
* Build system: CMAKE
* Host OS: OSX
* BUILD_TOOLS: 28.0.3

**Comment by stephenhines** [comment]
Can you show the actual assertion here? @miaowang14 might be able to help out too.

**Comment by Ardy123** [comment]
updated comment, but for clarity...

slangAssert failed at frameworks/compile/slang/slang_rs_reflection_cpp.cpp:329 - 'ef->getIns().size() == 1'

**Comment by Ardy123** [comment]
Looking at the llvm code... it looks like a 'FIXME' that has not been implemented (strange it works when generating a java file wrapping the script)..

    if (ef->hasIns()) {
     // FIXME: Add support for kernels with multiple inputs.
      slangAssert(ef->getIns().size() == 1);
      Arguments.push_back(Argument(kAllocationSp, "ain"));
    }

**Comment by stephenhines** [comment]
Interesting. It seems that this isn't supported for generating C++ bindings. Do you actually want to use RenderScript with an NDK-based part of your project? The Java bindings do support multiple inputs and are much more common.

**Comment by Ardy123** [comment]
Yeah, I have to.... I'm adding renderscript support to an already large c/c++ codebase

**Comment by NewProggie** [comment]
I just tried to export a struct defined in an RS file [1] and hit a similar error:
`slangAssert failed at frameworks/compile/slang/slang_rs_reflection_cpp.cpp:701 - 'false'`.

Indeed, looking at the implementation

```
void RSReflectionCpp::genGetterAndSetter(const RSExportRecordType *ERT,
                                         const RSExportVar *EV) {
  slangAssert(false);
}
```
Can we somehow assume from this, that RS support for NDK will be deprecated in the upcoming/near future?

[1] https://developer.android.com/guide/topics/renderscript/advanced#struct

**Comment by enh-google** [comment]
> Yeah, Java isn't an option.... I'm adding renderscript support to an already large c/c++ codebase. Could you please schedule it to be added and in sync (featurewise) with java please?

that's unlikely to happen.

if you want well-supported actively-developed high-performance graphics APIs, see Vulkan: https://developer.android.com/ndk/guides/graphics (note that there are a whole bunch of vulkan documentation topics in the sidebar, not just that short intro page i've linked to!)

similarly, if you're trying to do machine learning kinds of operations, see the NNAPI docs: https://developer.android.com/ndk/guides/neuralnetworks

> Can we somehow assume from this, that RS support for NDK will be deprecated in the upcoming/near future?

as a general rule in life, you should expect the future to look similar to the past, and if you run `git log` in frameworks/compile/slang/ you can see that it's been in maintenance mode for several years now.

if you're writing _new_ code, you should probably be looking at vulkan or nnapi instead, as appropriate. and if you have renderscript use cases that _aren't_ well covered by existing better-supported alternatives, please let us know so we can work on addressing those gaps.

**Comment by NewProggie** [comment]
> > Can we somehow assume from this, that RS support for NDK will be deprecated in the upcoming/near future?
> 
> as a general rule in life, you should expect the future to look similar to the past, and if you run `git log` in frameworks/compile/slang/ you can see that it's been in maintenance mode for several years now.

The first half sentence of your answer is not only simply wrong, but also somewhat jerky. You can do better than this.


> if you're writing _new_ code, you should probably be looking at vulkan or nnapi instead, as appropriate. and if you have renderscript use cases that _aren't_ well covered by existing better-supported alternatives, please let us know so we can work on addressing those gaps.

Right, thank you for the suggestions. However, neither Vulkan nor NNAPI cover the use cases I'm interested in: Doing heterogeneous computing on Android, namely parallelizing ML inference with sufficient support for many hardware chips used in all the different Android devices out there.

**Comment by enh-google** [comment]
> The first half sentence of your answer is not only simply wrong, but also somewhat jerky. You can do better than this.

it was a geological joke. see [Uniformitarianism](https://en.wikipedia.org/wiki/Uniformitarianism).

> > if you're writing _new_ code, you should probably be looking at vulkan or nnapi instead, as appropriate. and if you have renderscript use cases that _aren't_ well covered by existing better-supported alternatives, please let us know so we can work on addressing those gaps.
> 
> Right, thank you for the suggestions. However, neither Vulkan nor NNAPI cover the use cases I'm interested in: Doing heterogeneous computing on Android, namely parallelizing ML inference with sufficient support for many hardware chips used in all the different Android devices out there.

you know renderscript is just running on the cpu these days?

**Comment by NewProggie** [comment]
> you know renderscript is just running on the cpu these days?

Except it's not? What _does_ happen is that the output from slang gets JIT compiled onto target specific hardware. Last time I've checked almost all of the devices I looked into did indeed come preinstalled with custom RS drivers for their own hw stack.

**Comment by enh-google** [comment]
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html
