### ISSUE TITLE
[BUG] Poor code generation for the neon instruction vcvtq_f16_s16

### ISSUE THREAD

**Issue by alankelly** [android/ndk#957]
--------------------------------------------------------------------------------

#### Description

Poor code generation for the neon instruction vcvtq_f16_s16

Test case:
~~~~
#include <arm_neon.h>

float16x8_t convert(int16x8_t a){
    return vcvtq_f16_s16(a);
}
~~~~

When compiled with -march=armv8.2-a+fp16 -O3 this generates

f16.o:     file format elf64-littleaarch64

Disassembly of section .text:
~~~~
<convert(__Int16x8_t)>:
    sxtl2   v1.4s, v0.8h
    sxtl    v0.4s, v0.4h
    scvtf   v1.4s, v1.4s
    scvtf   v0.4s, v0.4s
    fcvtn   v1.4h, v1.4s
    fcvtn   v0.4h, v0.4s
    mov     v0.d[1], v1.d[0]
    ret
~~~~
It looks like it is converting one register of 16 bit integers to two registers of 32 bit integers, converting these to 32 bit floats and then converting both of these to 16 bit float.

Using godbolt and gcc8.2 with the same flags I get:
~~~~
convert(__Int16x8_t):
        scvtf   v0.8h, v0.8h
        ret
~~~~
#### Environment Details

* NDK Version: 19b, r19c and r20-beta2 have been tested
* Build system: Standalone toolchain? flags: -march=armv8.2-a+fp16 -O3 
* Host OS: Ubuntu 16.04
* ABI: aarch64
* NDK API level: 28
* Device API level: 28

**Comment by smeijer1234** [comment]
Trunk LLVM is generating the efficient version, i.e. just the single vector scvtf instruction that operates on half elements.
I think this was fixed by commit https://reviews.llvm.org/rL355545, which was committed a month ago.

Hope this helps.

**Comment by stephenhines** [comment]
This isn't a regression or correctness bug, so not a candidate for cherry-picking into an NDK release. We'll be updating past this revision in the near future.

**Comment by alankelly** [comment]
Hi Guys,

Thanks for your quick feedback!.Looks like I'll be pulling the trunk and compiling clang!

Alan

**Comment by DanAlbert** [comment]
This is still something we need to do. Leaving it open.

**Comment by DanAlbert** [comment]
Clang has been updated for r21.

**Comment by DanAlbert** [comment]
And confirmed just to be safe. I see:

```
00000000000005ac <convert>:
 5ac:   4e79d800        scvtf   v0.8h, v0.8h
 5b0:   d65f03c0        ret
```
