### ISSUE TITLE
[BUG] Custom Structs in RenderScript causes incorrectly generated code

### ISSUE THREAD

**Issue by Ardy123** [android/ndk#958]
#### Description

Create a renderscript file using a struct for the type as an allocation object. When built, invalid C/C++ code will be generated for the reflected renderscript file... It will reference a type that does not exist and is not defined...

example...

in Renderscript file
typedef struct __attribute__((packed)) sfeature_t {
    char4 data[4];
} feature_t;

in generated code...
ScriptC_BFMatcher::ScriptC_RSTest(android::RSC::sp<android::RSC::RS> rs) {
...
 __rs_elem_ScriptField_sfeature_t = android::RSC::Element::ScriptField_sfeature_t(mRS);
...
}

compile error...

error: no member named 'ScriptField_sfeature_t' in 'android::RSC::Element'

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 19.2.5345600
* Build system: Gradle/CMAKE
* Host OS: Mac
* ABI: ALL
* NDK API level: 28
* Device API level: 28

**Comment by enh-google** [comment]
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html
