### ISSUE TITLE
[BUG] RenderScript c/c++ static lib: Can't compile with rtti enabled

### ISSUE THREAD

**Issue by Ardy123** [android/ndk#960]
#### Description
When trying to compile a project that uses rtti and renderscript, when linking, the following compile error is reported...

error: undefined reference to 'typeinfo for android::RSC::BaseObj'

#### Environment Details

    NDK Version: 19.2.5345600
    Build system: Gradle/CMAKE
    Host OS: Mac
    ABI: ALL
    NDK API level: 28
    Device API level: 28

**Comment by LiewJunTung** [comment]
There was this issue #444 and a hack to workaround this problem. But it seems like the bug isn't squashed yet.

**Comment by enh-google** [comment]
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html
