### ISSUE TITLE
[BUG] Compiler about error: use of undeclared identifier 'uselocale'

### ISSUE THREAD

**Issue by tianqu308** [android/ndk#967]
How  can I slove the following compailation problom ?
android studio 3.3.2
ndk 19.2.5345600

**build message :**
FAILED: C:\Users\liyong\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi19 --gcc-toolchain=C:/Users/liyong/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/liyong/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -DHAS_DBSDRM -DHAS_UDFEX -DHAS_VIDONDEC -DHAS_VIDONME -DHAS_XSOURCE -DHAVE_CONFIG_H -DNPT_CONFIG_ENABLE_LOGGING -DPLT_HTTP_DEFAULT_SERVER="\"\" UPnP/1.0 DLNADOC/1.50 Kodi\"\"" -DPLT_HTTP_DEFAULT_USER_AGENT="\"\" UPnP/1.0 DLNADOC/1.50 Kodi\"\"" -DTARGET_ANDROID -DTARGET_LINUX -DTARGET_POSIX -D_FILE_DEFINED -D_LINUX -D__LIBPLAYCORE_3D_SUPPORT__ -D__LIBPLAYCORE_BLURAY_PLAYER__ -D__STDC_CONSTANT_MACROS -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2 -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/addons/library.xbmc.gui -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/addons/library.xbmc.addon -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/addons/library.xbmc.pvr -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/addons/library.xbmc.codec -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/linux -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/dvdplayer -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/bdplayer -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/mkuplayer -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/dvdplayer/DVDInputStreams/NE10 -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/dvdplayer/DVDInputStreams/dvdnav -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/playercorehelper -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/playercore -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/cores/mkuplayer/libmku -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/lib -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/lib/cpluff/libcpluff -IG:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/depends/arm-linux-androideabi-android-14/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -stdlib=libc++ -std=c++11 -fexceptions -frtti -O0 -fno-limit-debug-info  -fPIC -MD -MT xbmc/CMakeFiles/xbmc.dir/DynamicDll.cpp.o -MF xbmc\CMakeFiles\xbmc.dir\DynamicDll.cpp.o.d -o xbmc/CMakeFiles/xbmc.dir/DynamicDll.cpp.o -c G:\develop\project\Plcore2.0\AndroidStudioProject\app\src\main\cpp\plcore2\xbmc\DynamicDll.cpp
In file included from G:\develop\project\Plcore2.0\AndroidStudioProject\app\src\main\cpp\plcore2\xbmc\DynamicDll.cpp:23:

In file included from G:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/xbmc/filesystem/File.h:32:

In file included from C:/Users/liyong/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\iostream:38:

In file included from C:/Users/liyong/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\ios:216:

C:/Users/liyong/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\__locale:51:55: error: use of undeclared identifier 'uselocale'

  __libcpp_locale_guard(locale_t& __loc) : __old_loc_(uselocale(__loc)) {}

**Comment by DanAlbert** [comment]
> G:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/depends/arm-linux-androideabi-android-14/include

What's in that directory?

Please fill out the bug template.

**Comment by tianqu308** [comment]
> > G:/develop/project/Plcore2.0/AndroidStudioProject/app/src/main/cpp/plcore2/depends/arm-linux-androideabi-android-14/include
> 
> What's in that directory?
> 
> Please fill out the bug template.

the directory is third part include files

**Comment by DanAlbert** [comment]
We don't have enough information to investigate. We need you to fill out the bug template and provide repro instructions. If we don't get those, there's nothing we can do and we'll have to close the bug.
