### ISSUE TITLE
[DOC] How do I use gtest with cmake?

### ISSUE THREAD

**Issue by aadithyabk** [android/ndk#968]
**Problem**
I am migrating a project from ndk-build to CMake and there are some test .mk files that I need to migrate as well. Looks like it is pretty straightforward to use gtest in .mk by doing `$(call import-module,third_party/googletest)`

I couldn't really find any docs regarding how to use this is CMake. I came across this [issue](https://github.com/android-ndk/ndk/issues/500) from 2017 and it has a piece of code
`set(GOOGLETEST_ROOT ${ANDROID_NDK}/sources/third_party/googletest/googletest)
add_library(gtest STATIC ${GOOGLETEST_ROOT}/src/gtest_main.cc ${GOOGLETEST_ROOT}/src/gtest-all.cc)
target_include_directories(gtest PRIVATE ${GOOGLETEST_ROOT})
target_include_directories(gtest PUBLIC ${GOOGLETEST_ROOT}/include)`

Is this still relevant? Can I put this in its own CMakeLists and link all of my tests CMakeLists to `gtest`? 

Also, our project is using ndk-17 and not really in my power to update it because we support up to API 15.

**Comment by DanAlbert** [comment]
Yes, that should work. The other option would be creating your own FindGTest.cmake (which is basically what #500 is about).

**Comment by aadithyabk** [comment]
Cool. Thanks for the help!

**Comment by aadithyabk** [comment]
@DanAlbert Do you happen to know any example or actual projects that I could look at understand how everything works? For example, Is Ctest still required or is it just gtest? I am a little confused.

**Comment by DanAlbert** [comment]
A sample was written for this a while ago: https://github.com/android/ndk-samples/tree/main/unit-test
