### ISSUE TITLE
Does APP_SHORT_COMMANDS work with CMake? 

### ISSUE THREAD

**Issue by aadithyabk** [android/ndk#972]
ndk-build allows passing APP_SHORT_COMMANDS through gradle dsl but I can't find any [documentation](https://developer.android.com/ndk/guides/cmake) regarding the CMake equivalent or if the same works with CMake as well.

Just using APP_SHORT_COMMANDS=true as an argument for CMake in gradle results in an error because it is interpreted incorrectly. -DAPP_SHORT_COMMANDS does work but it can mean a custom preprocessor definition to CMake as well and I don't know if it has any effect. Neither me nor my teammates have a windows machine to test it completely and I felt it is easier to ask you folks.

**Comment by DanAlbert** [comment]
No, it doesn't.

I'll have to dig around later and see if I can figure out the way to do this in CMake. It will be part of CMake proper rather than part of our interface, if that helps your search.

**Comment by alexcohn** [comment]
I believe [this answer](https://stackoverflow.com/a/43188057/192373) can help. With gradle, you can pass 

    -DCMAKE_NINJA_FORCE_RESPONSE_FILE=1

**Comment by aadithyabk** [comment]
Ah! Thanks for the link.

**Comment by DanAlbert** [comment]
This is probably worth us mentioning in the `externalNativeBuild` docs. I'll leave this open to track that.

**Comment by DanAlbert** [comment]
I haven't heard of this being a problem in a very long time. Maybe CMake is automatically enabling this when needed? I generally want to avoid repeating the CMake docs in our own docs, but if this is still relevant lmk and I can reopen.
