### ISSUE TITLE
[FR] add ndk-build option for fortify

### ISSUE THREAD

**Issue by DanAlbert** [android/ndk#976]
A command line option would make it easier to enable from Gradle.

**Comment by polishcode** [comment]
Hi @DanAlbert ,
What is currently (starting with e.g. r16b?) proper way to use this switch with ndk-build? I found some scattered info, but with no success. Also your and @enh talk at IO'19. I guess some documentation page about this would be great.
Thanks,
p

**Comment by DanAlbert** [comment]
https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid (https://developer.android.com/ndk/guides has a link to it in the sidebar; if there are ever docs you're looking for and they aren't available there or just aren't easy to find, file a bug; that should be the canonical source for information) for the how to docs and https://github.com/android-ndk/ndk/issues/954 discusses some of the current rough edges.

**Comment by DanAlbert** [comment]
I decided to go a step further and just enable it by default. There are no (known) false positives and the runtime cost is negligible. https://android-review.googlesource.com/c/platform/ndk/+/1124477

@polishcode I'm not sure why I thought I was responding to a question about ASan before. Sorry about that! You can enable it for older versions of the NDK just by defining `_FORTIFY_SOURCE=2`. Best option would be to do so in your build scripts (i.e. `APP_CFLAGS := -D_FORTIFY_SOURCE=2`) to make sure you don't forget it in some TUs.
