### ISSUE TITLE
[BUG] `*_SHORT_COMMANDS` fails to escape backslashes in linker options on Windows when building shared libraries

### ISSUE THREAD

**Issue by alyawn** [android/ndk#986]
#### Description

Similar to Issue #186 backslashes are not properly escaped on Windows when building with either `APP_SHORT_COMMAND`s or `LOCAL_SHORT_COMMANDS` when linking with `$(BUILD_SHARED_LIBRARY)` in an ndk-build (`Android.mk`).

The test case for this is exactly the same as in #186, but rather than building a static library, build a shared library.

The offending line is [here](https://android.googlesource.com/platform/ndk/+/b98bcb59926b0592c2f75b1472fb5b03ff98a475/build/core/build-binary.mk#713):

    $(call generate-list-file,$(linker_options),$(linker_list_file))

I suggest changing to: 

    $(call generate-list-file,$(call escape-backslashes,$(linker_options)),$(linker_list_file))

I've edited my local r19c `build/core/build-binary.mk` to the above and it works well.

**Comment by alyawn** [comment]
This also seems related to #213.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/1126440
